Object.assign(window.REVISION_BANK,{
'4:Truss element formulation':[
{id:'fea5-truss-transform',title:'Local-to-global truss transformation',level:'core',kind:'formula',q:'Why is a transformation matrix needed for a 2D truss element?',choices:['To express local axial stiffness in global x-y degrees of freedom','To change Young’s modulus','To remove nodal coordinates','To convert force into mass'],answer:0,explanation:'A truss carries axial deformation in its local axis, while the assembled structure uses global translational DOFs.',math:'[k]^g=[T]^T[k]^l[T]',source:'ST ZG619 Session 4 topic + standard FEM bridge (model supplement)'},
{id:'fea5-truss-dofs',title:'2D truss DOFs',level:'foundation',kind:'concept',q:'A two-node 2D truss element normally has how many translational element DOFs?',choices:['4','2','3','6'],answer:0,explanation:'Each node has u and v translations, giving four element DOFs in 2D.',source:'ST ZG619 Session 4 topic + standard FEM bridge (model supplement)'}
],
'5:Euler–Bernoulli beam finite element formulation':[
{id:'fea5-eb-kinematics',title:'Euler–Bernoulli kinematic assumption',level:'foundation',kind:'concept',q:'The Euler–Bernoulli beam theory assumes that plane cross-sections remain:',choices:['Plane and normal to the neutral axis','Warped arbitrarily','Parallel to the global x-axis','Stress-free'],answer:0,explanation:'Neglecting transverse shear deformation leads to the classical Euler–Bernoulli kinematic assumption.',source:'ST ZG619 Session 5 topic + standard beam-FEM bridge (model supplement)'},
{id:'fea5-eb-dofs',title:'Beam nodal DOFs',level:'core',kind:'concept',q:'For a two-node planar Euler–Bernoulli beam element, the common nodal DOFs are:',choices:['Transverse displacement and rotation at each node','Axial displacement only','Temperature only','Three rotations at each node'],answer:0,explanation:'Each node contributes one transverse displacement and one slope/rotation DOF.',math:'\\{d_e\\}=[v_1,\\theta_1,v_2,\\theta_2]^T',source:'ST ZG619 Session 5 topic + standard beam-FEM bridge (model supplement)'}
],
'5:Timoshenko beam finite element formulation':[
{id:'fea5-timo-shear',title:'Timoshenko shear deformation',level:'core',kind:'concept',q:'What additional deformation mechanism does Timoshenko beam theory include compared with Euler–Bernoulli theory?',choices:['Transverse shear deformation','Only thermal strain','Plasticity only','Torsional warping only'],answer:0,explanation:'Timoshenko theory allows cross-section rotation to differ from the slope of transverse displacement, thereby including shear deformation.',source:'ST ZG619 Session 5 topic + standard beam-FEM bridge (model supplement)'},
{id:'fea5-shear-strain',title:'Timoshenko shear strain',level:'advanced',kind:'formula',q:'A typical Timoshenko beam shear strain measure is:',choices:['γ=θ−dv/dx','γ=d²v/dx²','γ=du/dx','γ=θv'],answer:0,explanation:'The difference between cross-section rotation and deflection slope represents transverse shear deformation.',math:'\\gamma=\\theta-\\frac{dv}{dx}',source:'ST ZG619 Session 5 topic + standard beam-FEM bridge (model supplement)'}
],
'7:Frame element formulation':[
{id:'fea5-frame-combine',title:'Frame element combines actions',level:'foundation',kind:'concept',q:'A planar frame element combines which basic deformation modes?',choices:['Axial deformation and bending','Only torsion','Only membrane shear','Only thermal expansion'],answer:0,explanation:'A 2D frame member carries axial force together with bending and shear-resultant actions.',source:'ST ZG619 Session 7 topic + standard frame-FEM bridge (model supplement)'},
{id:'fea5-frame-dofs',title:'Planar frame DOFs',level:'core',kind:'concept',q:'A standard two-node planar frame element normally has how many DOFs?',choices:['6','4','8','2'],answer:0,explanation:'Each node has two translations and one rotation, for six element DOFs.',math:'\\{d_e\\}=[u_1,v_1,\\theta_1,u_2,v_2,\\theta_2]^T',source:'ST ZG619 Session 7 topic + standard frame-FEM bridge (model supplement)'}
],
'8:Isoparametric finite element formulation':[
{id:'fea5-iso-meaning',title:'Meaning of isoparametric',level:'foundation',kind:'concept',q:'In an isoparametric element, the same shape functions are used to interpolate:',choices:['Geometry and field variables','Only material density','Only loads','Only boundary conditions'],answer:0,explanation:'Isoparametric formulation uses one interpolation family for coordinates and unknown field variables.',source:'ST ZG619 Session 8 topic + standard FEM bridge (model supplement)'},
{id:'fea5-jacobian',title:'Jacobian role',level:'core',kind:'formula',q:'What is the main role of the Jacobian matrix in isoparametric FEM?',choices:['Map derivatives and integration between natural and physical coordinates','Store nodal loads','Replace material stiffness','Count elements'],answer:0,explanation:'The Jacobian relates natural-coordinate changes to physical-coordinate changes and appears in derivative transformations and integration.',math:'[J]=\\frac{\\partial(x,y)}{\\partial(\\xi,\\eta)}',source:'ST ZG619 Session 8 topic + standard isoparametric bridge (model supplement)'}
],
'9:Numerical integration':[
{id:'fea5-gauss-purpose',title:'Gauss integration purpose',level:'foundation',kind:'concept',q:'Why is Gaussian quadrature widely used in FEM?',choices:['It efficiently evaluates element integrals at selected sampling points','It removes the mesh','It makes all matrices diagonal','It eliminates constitutive laws'],answer:0,explanation:'Element stiffness and load terms often require numerical integration, and Gauss quadrature is efficient for polynomial-type integrands.',source:'ST ZG619 Session 9 topic + standard numerical-integration bridge (model supplement)'},
{id:'fea5-gauss1',title:'One-point Gauss rule',level:'core',kind:'formula',q:'For integration over −1≤ξ≤1, the one-point Gauss rule evaluates the integrand at:',choices:['ξ=0 with weight 2','ξ=1 with weight 1','ξ=−1 with weight 1','ξ=±1/√3'],answer:0,explanation:'The one-point rule uses the midpoint ξ=0 and weight 2.',math:'\\int_{-1}^{1}f(\\xi)d\\xi\\approx2f(0)',source:'ST ZG619 Session 9 topic + standard numerical-integration bridge (model supplement)'}
],
'12:Kirchhoff plate finite element formulation':[
{id:'fea5-kirchhoff',title:'Kirchhoff plate assumption',level:'foundation',kind:'concept',q:'Kirchhoff thin-plate theory neglects:',choices:['Transverse shear deformation','Bending curvature','Transverse displacement','In-plane coordinates'],answer:0,explanation:'Kirchhoff theory is the thin-plate analogue of Euler–Bernoulli beam theory and neglects transverse shear strains.',source:'ST ZG619 Session 12 topic + standard plate-FEM bridge (model supplement)'},
{id:'fea5-c1',title:'Continuity challenge in Kirchhoff plates',level:'advanced',kind:'concept',q:'Why are classical Kirchhoff plate elements more demanding to formulate?',choices:['They require C¹ continuity of transverse displacement','They require no interpolation','They have zero stiffness','They use only one node'],answer:0,explanation:'Because plate bending involves second derivatives of w in the weak form used by classical displacement elements, slope continuity is required across element boundaries.',source:'ST ZG619 Session 12 topic + standard plate-FEM bridge (model supplement)'}
],
'12:Mindlin plate finite element formulation':[
{id:'fea5-mindlin',title:'Mindlin plate feature',level:'core',kind:'concept',q:'Mindlin–Reissner plate theory is especially useful because it includes:',choices:['Transverse shear deformation','Only membrane stress','No rotations','No bending'],answer:0,explanation:'Mindlin theory includes independent rotations and transverse shear, making it suitable for moderately thick plates.',source:'ST ZG619 Session 12 topic + standard plate-FEM bridge (model supplement)'},
{id:'fea5-shear-lock',title:'Shear locking',level:'advanced',kind:'concept',q:'What numerical issue can occur when a low-order Mindlin plate element is used for a very thin plate?',choices:['Shear locking','Hourglass motion in every formulation','Loss of all mass','Exact rigid-body stiffness'],answer:0,explanation:'An overly stiff discrete shear field can cause shear locking as the plate becomes thin.',source:'ST ZG619 Session 12 topic + standard plate-FEM bridge (model supplement)'}
],
'16:Free vibration using FEM':[
{id:'fea5-eigen',title:'FEM free-vibration eigenproblem',level:'core',kind:'formula',q:'The undamped FEM free-vibration problem is commonly written as:',choices:['([K]−ω²[M]){φ}=0','[K]{u}={f} only','[M]{u}={0}','[C]{u}=ω{f}'],answer:0,explanation:'Natural frequencies and mode shapes are obtained from the generalized eigenvalue problem involving stiffness and mass matrices.',math:'([K]-\\omega^2[M])\\{\\phi\\}=0',source:'ST ZG619 Session 16 topic + standard structural-dynamics FEM bridge (model supplement)'},
{id:'fea5-det',title:'Characteristic equation',level:'advanced',kind:'formula',q:'Non-trivial mode shapes require:',choices:['det([K]−ω²[M])=0','det[K]=1','[M]=0','ω=0 for every mode'],answer:0,explanation:'A non-zero eigenvector exists only when the dynamic stiffness matrix is singular.',math:'\\det([K]-\\omega^2[M])=0',source:'ST ZG619 Session 16 topic + standard structural-dynamics FEM bridge (model supplement)'}
],
'16:Transient dynamic problems':[
{id:'fea5-transient',title:'Semi-discrete transient equation',level:'core',kind:'formula',q:'After spatial FEM discretization, the structural transient equation is:',choices:['[M]{ü}+[C]{u̇}+[K]{u}={f(t)}','[K]{u}=0 only','[M]{u}={f}','[C]{ü}={0}'],answer:0,explanation:'The finite element model produces a system of second-order ordinary differential equations in time.',math:'[M]\\{\\ddot u\\}+[C]\\{\\dot u\\}+[K]\\{u\\}=\\{f(t)\\}',source:'ST ZG619 Session 16 topic + standard dynamic-FEM bridge (model supplement)'},
{id:'fea5-time-step',title:'Time discretization',level:'application',kind:'concept',q:'After spatial discretization, what is still required to solve a transient FEM problem numerically?',choices:['A time-integration scheme','A second spatial mesh only','Removal of mass matrix','Zero initial conditions always'],answer:0,explanation:'Methods such as Newmark or central difference advance the semi-discrete equations through time.',source:'ST ZG619 Session 16 topic + standard transient-analysis bridge (model supplement)'}
]
});