Object.assign(window.REVISION_BANK,{
'10:Axisymmetric finite element formulation':[
{id:'fea4-axisym-meaning',title:'Axisymmetric idealization',level:'foundation',kind:'concept',q:'An axisymmetric finite-element model is appropriate when:',choices:['Geometry, material and loading are symmetric about an axis','The structure is necessarily a beam','Only one node exists','All displacements are zero'],answer:0,explanation:'Axisymmetry reduces a 3D body of revolution to a 2D meridional domain when geometry, material and loading do not vary with circumferential angle.',source:'ST ZG619 Session 10 topic + standard FEM bridge (model supplement)'},
{id:'fea4-hoop-strain',title:'Hoop strain',level:'core',kind:'formula',q:'For an axisymmetric radial displacement u_r at radius r, the circumferential strain contains the term:',choices:['u_r/r','du_r/dz only','r/u_r','u_z/r'],answer:0,explanation:'Change in circumference produces the hoop strain ε_θ=u_r/r.',math:'\\varepsilon_\\theta=\\frac{u_r}{r}',source:'ST ZG619 Session 10 topic + standard axisymmetric FEM bridge (model supplement)'}
],
'11:2D finite element numerical problems':[
{id:'fea4-2d-dofs',title:'2D nodal DOFs',level:'foundation',kind:'concept',q:'A standard 2D continuum node in plane stress/strain usually carries which displacement DOFs?',choices:['u and v','u only','w and θ only','Temperature only'],answer:0,explanation:'Two in-plane displacement components are the usual primary variables for 2D elasticity elements.',source:'ST ZG619 Session 11 topic + standard FEM bridge (model supplement)'},
{id:'fea4-2d-system',title:'2D assembled system',level:'core',kind:'formula',q:'After assembly and boundary conditions, a linear 2D elasticity problem is solved from:',choices:['KU=F','MU=K','BU=D','J=0'],answer:0,explanation:'The global stiffness matrix multiplies the nodal displacement vector to balance the global load vector.',math:'[K]\\{U\\}=\\{F\\}',source:'ST ZG619 Session 11 topic + standard FEM bridge (model supplement)'}
],
'13:Shell finite element formulation':[
{id:'fea4-shell-combine',title:'What shell elements combine',level:'foundation',kind:'concept',q:'A structural shell element commonly combines:',choices:['Membrane and bending action','Only axial bar action','Only thermal conduction','Only rigid-body motion'],answer:0,explanation:'Shells resist both in-plane membrane forces and out-of-plane bending, often with transverse shear depending on theory.',source:'ST ZG619 Session 13 topic + standard shell-FEM bridge (model supplement)'},
{id:'fea4-shell-dofs',title:'Shell nodal variables',level:'core',kind:'concept',q:'Compared with a 2D plane-stress element, a shell element generally needs:',choices:['Additional transverse displacement and rotational DOFs','Fewer than one DOF per node','No displacement DOFs','Only pressure DOFs'],answer:0,explanation:'Shell kinematics include out-of-plane deformation and rotations in addition to in-plane displacement.',source:'ST ZG619 Session 13 topic + standard shell-FEM bridge (model supplement)'}
],
'14:Mixed finite element formulation':[
{id:'fea4-mixed-meaning',title:'Mixed FEM idea',level:'foundation',kind:'concept',q:'A mixed finite-element formulation treats:',choices:['More than one field variable as independent unknowns','Only nodal coordinates as unknowns','Only one scalar in every problem','No variational statement'],answer:0,explanation:'Mixed methods may approximate displacement together with stress, pressure or another field independently.',source:'ST ZG619 Session 14 topic + standard mixed-FEM bridge (model supplement)'},
{id:'fea4-mixed-example',title:'Displacement-pressure example',level:'core',kind:'concept',q:'A common mixed formulation for nearly incompressible elasticity introduces which additional unknown alongside displacement?',choices:['Pressure','Temperature only','Time step','Mesh size'],answer:0,explanation:'Independent pressure is often introduced to avoid volumetric locking and enforce incompressibility constraints.',source:'ST ZG619 Session 14 topic + standard mixed-FEM bridge (model supplement)'}
],
'15:Material nonlinearity':[
{id:'fea4-material-nl',title:'Material nonlinearity',level:'foundation',kind:'concept',q:'Material nonlinearity occurs when:',choices:['Stress is not a linear function of strain over the response range','Geometry is always unchanged','The mesh has more than one element','Loads are constant'],answer:0,explanation:'Plasticity, cracking, hyperelasticity and other constitutive responses make the stress-strain relation nonlinear.',source:'ST ZG619 Session 15 topic + standard nonlinear-FEM bridge (model supplement)'},
{id:'fea4-tangent-stiffness',title:'Tangent stiffness',level:'core',kind:'formula',q:'In an incremental nonlinear solution, the tangent stiffness relates an increment of force to:',choices:['An increment of displacement','Absolute temperature','Element count only','Time squared'],answer:0,explanation:'Newton-type nonlinear iterations use the current tangent stiffness to update displacement.',math:'[K_T]\\{\\Delta U\\}=\\{R\\}',source:'ST ZG619 Session 15 topic + standard nonlinear-FEM bridge (model supplement)'}
],
'15:Geometric nonlinearity':[
{id:'fea4-geo-nl',title:'Geometric nonlinearity',level:'foundation',kind:'concept',q:'Geometric nonlinearity becomes important when:',choices:['Deformation changes the equilibrium configuration or strain-displacement relation significantly','Material is always elastic','The model has one element','Forces are measured in newtons'],answer:0,explanation:'Large displacement/rotation can alter geometry enough that equilibrium must be written on the deformed configuration.',source:'ST ZG619 Session 15 topic + standard nonlinear-FEM bridge (model supplement)'},
{id:'fea4-pdelta',title:'P-Delta effect',level:'application',kind:'concept',q:'The P-Δ effect is an example of:',choices:['Geometric nonlinearity','Material yielding only','Thermal conduction','Mass lumping'],answer:0,explanation:'Axial force acting through lateral displacement creates a secondary moment that depends on the deformed geometry.',math:'M_{2}\\approx P\\Delta',source:'ST ZG619 Session 15 topic + standard structural-stability bridge (model supplement)'}
],
'16:Free vibration using FEM':[
{id:'fea4-eigenproblem',title:'FEM free-vibration eigenproblem',level:'core',kind:'formula',q:'Undamped free vibration of an FE model leads to which eigenvalue problem?',choices:['(K−ω²M)φ=0','KU=F only','Mφ=F','K+M=0'],answer:0,explanation:'Assuming harmonic motion converts the semi-discrete equation into the generalized eigenproblem for natural frequencies and mode shapes.',math:'([K]-\\omega^2[M])\\{\\phi\\}=\\{0\\}',source:'ST ZG619 Session 16 topic + standard structural-dynamics FEM bridge (model supplement)'},
{id:'fea4-mode-shape',title:'Mode shape meaning',level:'foundation',kind:'concept',q:'An eigenvector φ from the free-vibration FE problem represents:',choices:['A mode shape','A material yield surface','A load combination','A mesh Jacobian'],answer:0,explanation:'Each eigenvector gives the relative nodal deformation pattern associated with one natural frequency.',source:'ST ZG619 Session 16 topic + standard structural-dynamics FEM bridge (model supplement)'}
],
'16:Transient dynamic problems':[
{id:'fea4-transient-eom',title:'Semi-discrete transient equation',level:'core',kind:'formula',q:'The standard linear transient structural FE equation is:',choices:['MÜ+CŮ+KU=F(t)','KU=0 always','M+K=F','BU=D'],answer:0,explanation:'After spatial discretization, the time-dependent structural problem becomes a coupled system of second-order ODEs.',math:'[M]\\{\\ddot U\\}+[C]\\{\\dot U\\}+[K]\\{U\\}=\\{F(t)\\}',source:'ST ZG619 Session 16 topic + standard structural-dynamics FEM bridge (model supplement)'},
{id:'fea4-time-step',title:'Role of time step',level:'application',kind:'reasoning',q:'In direct time integration, choosing an excessively large time step can:',choices:['Miss important high-frequency response and reduce accuracy','Always improve accuracy','Eliminate mass','Make boundary conditions unnecessary'],answer:0,explanation:'Temporal resolution must be sufficient for the response frequencies of interest, even when the integration algorithm is stable.',source:'ST ZG619 Session 16 topic + standard time-integration bridge (model supplement)'}
],
'16:Finite element code for bars':[
{id:'fea4-bar-code-loop',title:'Bar-code assembly loop',level:'foundation',kind:'sequence',q:'Which ordering best describes a basic bar FEM code?',choices:['Read mesh/properties → form element matrices → assemble → apply BCs → solve → postprocess','Solve → mesh → assemble → read input','Plot → solve → define DOFs','Apply BCs after postprocessing only'],answer:0,explanation:'A minimal implementation follows the same mathematical workflow as hand assembly.',source:'ST ZG619 Session 16 topic + programming bridge (model supplement)'},
{id:'fea4-bar-ke',title:'2-node bar stiffness',level:'core',kind:'formula',q:'For a uniform 2-node axial bar element, the local stiffness matrix is:',choices:['AE/L [[1,-1],[-1,1]]','EI/L³ [[1,1],[1,1]]','ρAL I','GJ/L [[0,0],[0,0]]'],answer:0,explanation:'Linear axial interpolation produces the familiar symmetric 2×2 bar stiffness matrix.',math:'[k^{(e)}]=\\frac{AE}{L}\\begin{bmatrix}1&-1\\\\-1&1\\end{bmatrix}',source:'ST ZG619 Session 16 topic + standard bar-element formulation (model supplement)'}
],
'16:Finite element code for beams':[
{id:'fea4-beam-code-dofs',title:'Beam code DOF mapping',level:'core',kind:'concept',q:'A planar Euler-Bernoulli beam element typically contributes which nodal DOFs?',choices:['Transverse displacement and rotation at each node','Axial displacement only','Pressure only','Temperature only'],answer:0,explanation:'The standard two-node bending element has four local DOFs: v1, θ1, v2, θ2.',math:'\\{d_e\\}=\\{v_1,\\theta_1,v_2,\\theta_2\\}^T',source:'ST ZG619 Session 16 topic + standard beam-element formulation (model supplement)'},
{id:'fea4-beam-code-sym',title:'Stiffness-matrix check',level:'application',kind:'reasoning',q:'For a conservative linear beam element, a useful implementation check is that the stiffness matrix should be:',choices:['Symmetric','Random','Strictly diagonal','Antisymmetric'],answer:0,explanation:'Energy-derived linear elastic element stiffness matrices are symmetric; loss of symmetry often indicates an implementation error.',source:'ST ZG619 Session 16 topic + programming bridge (model supplement)'}
]
});