Object.assign(window.REVISION_BANK,{
'5:Timoshenko beam finite element formulation':[
{id:'fea6-timo-shear',title:'Timoshenko adds shear deformation',level:'foundation',kind:'concept',q:'Compared with Euler–Bernoulli beam theory, Timoshenko beam theory additionally includes:',choices:['Transverse shear deformation','Only axial deformation','No rotation variable','No bending stiffness'],answer:0,explanation:'Timoshenko theory allows cross-sections to rotate independently of the slope of the transverse displacement, thereby including transverse shear deformation.',source:'ST ZG619 Session 5 topic + standard FEM beam-theory bridge (model supplement)'},
{id:'fea6-timo-kin',title:'Timoshenko shear strain',level:'core',kind:'formula',q:'With transverse displacement w(x) and cross-section rotation φ(x), a common Timoshenko shear-strain measure is:',choices:['γ=φ−dw/dx','γ=dφ/dx','γ=wφ','γ=d²w/dx²'],answer:0,explanation:'The difference between cross-section rotation and beam slope represents transverse shear deformation, subject to sign convention.',math:'\\gamma_{xz}=\\phi-\\frac{dw}{dx}',source:'ST ZG619 Session 5 topic + standard beam-theory bridge (model supplement)'}
],
'6:Beam numerical problems':[
{id:'fea6-beam-dofs',title:'Beam element nodal DOFs',level:'foundation',kind:'concept',q:'A 2-node planar Euler–Bernoulli beam element commonly has which nodal degrees of freedom?',choices:['Transverse displacement and rotation at each node','Only one axial displacement total','Three translations at each node only','No rotational degrees of freedom'],answer:0,explanation:'The standard planar beam element uses w and θ at each of two nodes, giving four element DOFs.',math:'\\{d^{(e)}\\}=\\{w_1,\\theta_1,w_2,\\theta_2\\}^T',source:'ST ZG619 Session 6 topic + standard FEM beam bridge (model supplement)'},
{id:'fea6-beam-bc',title:'Cantilever beam boundary conditions',level:'application',kind:'reasoning',q:'For a cantilever beam finite-element model, what is imposed at the fixed-end node?',choices:['Both transverse displacement and rotation are zero','Only rotation is zero','Only displacement is zero','Neither displacement nor rotation is constrained'],answer:0,explanation:'A fixed support restrains both transverse translation and cross-section rotation in the planar bending model.',math:'w=0,\\qquad \\theta=0',source:'ST ZG619 Session 6 topic + standard FEM boundary-condition bridge (model supplement)'}
],
'7:Frame numerical examples':[
{id:'fea6-frame-transform',title:'Why frame elements need transformation',level:'core',kind:'reasoning',q:'Why is a local-to-global transformation used for a 2D frame element?',choices:['Element stiffness is naturally derived in member axes but assembly uses one global coordinate system','It changes Young’s modulus','It eliminates nodal rotations','It converts forces into strains only'],answer:0,explanation:'Each inclined member has its own local axes; transformation expresses its stiffness and forces consistently in global coordinates before assembly.',source:'ST ZG619 Session 7 topic + standard FEM frame bridge (model supplement)'},
{id:'fea6-frame-ktransform',title:'Transform element stiffness',level:'advanced',kind:'formula',q:'If [T] maps global element DOFs to local DOFs, the global element stiffness is commonly written as:',choices:['K_g=T^T K_l T','K_g=T K_l','K_g=K_l/T','K_g=T^T T only'],answer:0,explanation:'The congruence transformation preserves virtual work while converting local stiffness to the global coordinate basis.',math:'[K_g]=[T]^T[K_l][T]',source:'ST ZG619 Session 7 topic + standard FEM frame bridge (model supplement)'}
],
'8:Isoparametric finite element formulation':[
{id:'fea6-iso-sameN',title:'Meaning of isoparametric',level:'foundation',kind:'concept',q:'What is the defining idea of an isoparametric finite element?',choices:['The same shape functions interpolate geometry and field variables','Every element must be square','Material properties must be isotropic','Natural coordinates equal global coordinates'],answer:0,explanation:'Isoparametric formulation uses the same interpolation basis for element geometry and unknown field variables.',math:'x=\\sum_iN_i x_i,\\qquad u=\\sum_iN_i u_i',source:'ST ZG619 Session 8 topic + standard FEM bridge (model supplement)'},
{id:'fea6-jacobian',title:'Jacobian role',level:'core',kind:'concept',q:'In isoparametric FEM, the Jacobian matrix is used primarily to:',choices:['Transform derivatives and integration between natural and physical coordinates','Store nodal loads','Define material density only','Replace the stiffness matrix'],answer:0,explanation:'The Jacobian relates coordinate differentials and derivatives between the parent element and the physical element.',math:'[J]=\\frac{\\partial(x,y)}{\\partial(\\xi,\\eta)}',source:'ST ZG619 Session 8 topic + standard FEM bridge (model supplement)'}
],
'9:Plane stress formulation':[
{id:'fea6-planestress',title:'Plane-stress assumption',level:'foundation',kind:'concept',q:'Plane stress is appropriate when:',choices:['Out-of-plane stresses are negligible compared with in-plane stresses','Out-of-plane strain must be zero','All shear stresses are zero','The body is infinitely thick'],answer:0,explanation:'Thin plates loaded in their plane are commonly idealized with σ_z, τ_xz and τ_yz approximately zero.',math:'\\sigma_z=\\tau_{xz}=\\tau_{yz}\\approx0',source:'ST ZG619 Session 9 topic + standard 2D elasticity bridge (model supplement)'},
{id:'fea6-planestressD',title:'Plane-stress constitutive matrix',level:'advanced',kind:'formula',q:'For isotropic plane stress, the elastic constitutive matrix carries the factor:',choices:['E/(1−ν²)','E/((1+ν)(1−2ν))','GJ/L','EA/L'],answer:0,explanation:'The isotropic plane-stress matrix is E/(1−ν²) times the standard in-plane coefficient matrix.',math:'[D]_{ps}=\\frac{E}{1-\\nu^2}\\begin{bmatrix}1&\\nu&0\\\\\\nu&1&0\\\\0&0&(1-\\nu)/2\\end{bmatrix}',source:'ST ZG619 Session 9 topic + standard 2D FEM bridge (model supplement)'}
],
'9:Plane strain formulation':[
{id:'fea6-planestrain',title:'Plane-strain assumption',level:'foundation',kind:'concept',q:'Plane strain assumes which out-of-plane strain components vanish?',choices:['ε_z, γ_xz and γ_yz','σ_z, τ_xz and τ_yz','ε_x and ε_y','All stresses'],answer:0,explanation:'Plane strain suppresses out-of-plane deformation while allowing a nonzero out-of-plane normal stress to develop.',math:'\\varepsilon_z=\\gamma_{xz}=\\gamma_{yz}=0',source:'ST ZG619 Session 9 topic + standard 2D elasticity bridge (model supplement)'},
{id:'fea6-planechoice',title:'Plane stress versus plane strain',level:'application',kind:'reasoning',q:'A very long retaining wall cross-section away from its ends is more naturally idealized as:',choices:['Plane strain','Plane stress','Pure torsion','Axisymmetric by default'],answer:0,explanation:'If geometry and loading vary little along a long direction and deformation in that direction is constrained, plane strain is often appropriate.',source:'ST ZG619 Session 9 topic + standard continuum/FEM bridge (model supplement)'}
],
'9:Numerical integration':[
{id:'fea6-gauss',title:'Why Gauss integration is used',level:'foundation',kind:'concept',q:'Gaussian quadrature is widely used in FEM because it:',choices:['Efficiently evaluates element integrals in natural coordinates','Eliminates shape functions','Makes every stiffness matrix diagonal','Removes the need for a Jacobian'],answer:0,explanation:'Gauss quadrature evaluates polynomial-like integrands accurately with a small number of optimally placed integration points.',source:'ST ZG619 Session 9 topic + standard numerical-integration bridge (model supplement)'},
{id:'fea6-gauss1d',title:'Two-point Gauss locations',level:'core',kind:'formula',q:'For two-point Gauss quadrature over ξ∈[−1,1], the integration points are:',choices:['ξ=±1/√3','ξ=±1','ξ=0 and 1','ξ=±√3'],answer:0,explanation:'The two Gauss points are symmetric at ±1/√3 with unit weights.',math:'\\xi_{1,2}=\\pm\\frac{1}{\\sqrt3},\\qquad w_{1,2}=1',source:'ST ZG619 Session 9 topic + standard numerical-methods bridge (model supplement)'}
],
'10:Axisymmetric finite element formulation':[
{id:'fea6-axisym',title:'Axisymmetric modeling condition',level:'foundation',kind:'concept',q:'An axisymmetric finite-element idealization requires geometry, material and loading to be:',choices:['Independent of circumferential angle','Independent of radial coordinate','Two-dimensional in Cartesian x-y only','Free of radial displacement'],answer:0,explanation:'Axisymmetry permits a 3D body of revolution to be modeled using its meridional cross-section when circumferential variation is absent.',source:'ST ZG619 Session 10 topic + standard FEM bridge (model supplement)'},
{id:'fea6-hoopstrain',title:'Axisymmetric hoop strain',level:'core',kind:'formula',q:'For radial displacement u_r at radius r, the small circumferential strain in an axisymmetric model is:',choices:['ε_θ=u_r/r','ε_θ=du_r/dr only','ε_θ=r/u_r','ε_θ=0 always'],answer:0,explanation:'Circumferential expansion is radial displacement divided by the original radius.',math:'\\varepsilon_\\theta=\\frac{u_r}{r}',source:'ST ZG619 Session 10 topic + standard axisymmetric-elasticity bridge (model supplement)'}
],
'13:Shell finite element formulation':[
{id:'fea6-shell',title:'Shell element structural action',level:'foundation',kind:'concept',q:'A shell finite element is intended to represent structures carrying:',choices:['Membrane action together with bending action','Only axial bar action','Only rigid-body motion','Only point loads with no deformation'],answer:0,explanation:'Shells combine in-plane membrane behavior with plate-like bending, making them suitable for thin curved or flat surfaces.',source:'ST ZG619 Session 13 topic + standard FEM shell bridge (model supplement)'},
{id:'fea6-shell-curved',title:'Why shells suit curved surfaces',level:'application',kind:'reasoning',q:'Why are shell elements preferred over beam elements for a thin cylindrical tank wall?',choices:['They represent two-dimensional membrane and bending behavior over the surface','They require no mesh','They remove Poisson effects','They model only one spatial direction'],answer:0,explanation:'A tank wall carries stresses in multiple in-surface directions and may bend; a shell formulation captures both.',source:'ST ZG619 Session 13 topic + standard FEM modeling bridge (model supplement)'}
],
'14:Mixed finite element formulation':[
{id:'fea6-mixed',title:'Mixed formulation idea',level:'core',kind:'concept',q:'A mixed finite-element formulation treats:',choices:['More than one field variable as independent unknowns','Only nodal displacement and nothing else','Material properties as random variables only','All boundary conditions as natural'],answer:0,explanation:'Mixed formulations introduce additional independent fields such as displacement and pressure or stress, which can improve performance for constrained problems.',source:'ST ZG619 Session 14 topic + standard FEM bridge (model supplement)'},
{id:'fea6-incompress',title:'Mixed formulation for incompressibility',level:'application',kind:'reasoning',q:'Why can a displacement-pressure mixed formulation be useful for nearly incompressible materials?',choices:['It helps avoid volumetric locking by treating pressure independently','It forces ν to zero','It removes stiffness entirely','It converts the mesh to 1D'],answer:0,explanation:'Independent pressure interpolation can satisfy incompressibility constraints without excessively stiff volumetric response.',source:'ST ZG619 Session 14 topic + standard FEM bridge (model supplement)'}
],
'16:Transient dynamic problems':[
{id:'fea6-transient',title:'Semidiscrete dynamic FEM equation',level:'core',kind:'formula',q:'After spatial finite-element discretization, the standard structural transient equation is:',choices:['Mü+C u̇+Ku=F(t)','Ku=0 only','Mu=F without derivatives','Kü+Mu=0'],answer:0,explanation:'Spatial discretization yields a system of second-order ordinary differential equations in time.',math:'[M]\\{\\ddot u\\}+[C]\\{\\dot u\\}+[K]\\{u\\}=\\{F(t)\\}',source:'ST ZG619 Session 16 topic + standard dynamic-FEM bridge (model supplement)'},
{id:'fea6-timestep',title:'Time stepping purpose',level:'foundation',kind:'concept',q:'In transient FEM, a time-integration algorithm is used to:',choices:['Advance displacement, velocity and acceleration through successive time steps','Generate the spatial mesh only','Compute Young’s modulus','Eliminate the mass matrix'],answer:0,explanation:'Methods such as Newmark integrate the semidiscrete equations in time to obtain the response history.',source:'ST ZG619 Session 16 topic + standard dynamic-FEM bridge (model supplement)'}
]
});