Object.assign(window.REVISION_BANK,{
'5:Timoshenko beam finite element formulation':[
{id:'timo-shear',title:'Timoshenko beam shear deformation',level:'foundation',kind:'concept',q:'What key deformation mode does Timoshenko beam theory include that Euler–Bernoulli theory neglects?',choices:['Transverse shear deformation','Axial deformation only','Thermal strain only','Plastic flow only'],answer:0,explanation:'Timoshenko theory permits cross-section rotation to differ from the slope of transverse deflection, thereby representing transverse shear deformation.',source:'FEA Session 5 tracked-topic bridge'},
{id:'timo-kinematics',title:'Timoshenko shear strain',level:'core',kind:'formula',q:'With transverse displacement w(x) and independent section rotation φ(x), a common Timoshenko shear-strain measure is:',choices:['γ = φ − dw/dx','γ = d²w/dx²','γ = wφ','γ = dφ/dt'],answer:0,explanation:'The difference between section rotation and deflection slope produces transverse shear strain, subject to sign convention.',math:'\\gamma_{xz}=\\phi-\\frac{dw}{dx}',source:'FEA Session 5 tracked-topic bridge'}
],
'6:Beam numerical problems':[
{id:'beam-element-dofs',title:'Beam element DOF count',level:'foundation',kind:'classification',q:'For a standard 2-node Euler–Bernoulli beam element in planar bending, how many bending DOFs are typically used?',choices:['4','2','6 axial-only','1'],answer:0,explanation:'Each node has transverse displacement and rotation, giving four bending DOFs per element.',math:'\\{d^e\\}=\\{w_1,\\theta_1,w_2,\\theta_2\\}^T',source:'FEA Session 6 beam-problem bridge'},
{id:'beam-k-scale',title:'Beam stiffness scaling',level:'core',kind:'reasoning',q:'If E and I stay fixed while an Euler–Bernoulli beam element length doubles, characteristic bending stiffness terms proportional to EI/L³ become:',choices:['One eighth','One half','One quarter','Eight times'],answer:0,explanation:'Bending stiffness terms contain inverse powers of element length; the leading translational stiffness scales as L^{-3}.',math:'k_b\\propto\\frac{EI}{L^3}',source:'FEA Session 6 beam-problem bridge'}
],
'7:Frame element formulation':[
{id:'frame-combination',title:'What a plane frame element combines',level:'foundation',kind:'concept',q:'A standard 2D frame element combines which basic member actions?',choices:['Axial deformation and bending','Only torsion','Only plate membrane action','Only thermal expansion'],answer:0,explanation:'A plane frame element usually combines axial bar behaviour with beam bending behaviour.',source:'FEA Session 7 tracked-topic bridge'},
{id:'frame-node-dof',title:'Plane frame nodal DOFs',level:'core',kind:'classification',q:'How many usual DOFs does each node of a 2D frame element have?',choices:['3: u, v and rotation θ','1 only','2 rotations only','6 translations'],answer:0,explanation:'Each plane-frame node typically has two translations and one in-plane rotation.',math:'\\{d_i\\}=\\{u_i,v_i,\\theta_i\\}^T',source:'FEA Session 7 tracked-topic bridge'}
],
'9:2D finite element formulation':[
{id:'2d-field',title:'2D displacement field',level:'foundation',kind:'concept',q:'In a standard small-strain 2D elasticity element, which primary nodal field variables are interpolated?',choices:['u(x,y) and v(x,y)','Only temperature','Only rotation about x','Only stress components directly'],answer:0,explanation:'Plane elasticity formulations usually interpolate the two in-plane displacement components.',math:'\\{u\\}=\\begin{Bmatrix}u(x,y)\\\\v(x,y)\\end{Bmatrix}',source:'FEA Session 9 tracked-topic bridge'},
{id:'2d-b-matrix',title:'Role of the B matrix',level:'core',kind:'concept',q:'What does the strain-displacement matrix B do in a 2D finite element?',choices:['Maps nodal displacements to strains','Maps stress directly to loads without geometry','Stores only node numbers','Replaces the constitutive matrix'],answer:0,explanation:'Differentiated shape functions are assembled into B so that element strains follow from nodal DOFs.',math:'\\{\\varepsilon\\}=[B]\\{d^e\\}',source:'FEA Session 9 tracked-topic bridge'}
],
'9:Plane stress formulation':[
{id:'plane-stress-cond',title:'Plane-stress assumption',level:'foundation',kind:'classification',q:'Which stress components are neglected in the ideal plane-stress approximation?',choices:['σ_z, τ_xz and τ_yz','σ_x and σ_y','τ_xy only','All normal stresses'],answer:0,explanation:'Thin bodies loaded in their plane are often idealised with negligible out-of-plane stresses.',math:'\\sigma_z=\\tau_{xz}=\\tau_{yz}=0',source:'FEA Session 9 tracked-topic bridge'},
{id:'plane-stress-use',title:'Typical plane-stress application',level:'application',kind:'classification',q:'Which structure is most naturally idealised using plane stress?',choices:['A thin plate loaded in its own plane','A very long thick dam cross-section restrained out of plane','A circular shaft in torsion','A 1D truss bar only'],answer:0,explanation:'Plane stress is appropriate when thickness is small and out-of-plane surfaces are essentially traction-free.',source:'FEA Session 9 tracked-topic bridge'}
],
'9:Plane strain formulation':[
{id:'plane-strain-cond',title:'Plane-strain assumption',level:'foundation',kind:'classification',q:'Which strain components are zero in the ideal plane-strain approximation?',choices:['ε_z, γ_xz and γ_yz','ε_x and ε_y','γ_xy only','All strains'],answer:0,explanation:'Plane strain assumes no out-of-plane normal or transverse shear strain.',math:'\\varepsilon_z=\\gamma_{xz}=\\gamma_{yz}=0',source:'FEA Session 9 tracked-topic bridge'},
{id:'plane-strain-use',title:'Typical plane-strain application',level:'application',kind:'classification',q:'Which situation is commonly approximated as plane strain away from end effects?',choices:['A very long prismatic body with uniform cross-section and loading along its length','A thin sheet in membrane tension','A simple truss','A point mass on a spring'],answer:0,explanation:'Long bodies with restrained or negligible longitudinal variation can often be analysed using a plane-strain cross-section.',source:'FEA Session 9 tracked-topic bridge'}
],
'9:Numerical integration':[
{id:'gauss-purpose',title:'Why numerical integration is used',level:'foundation',kind:'concept',q:'Why is Gauss quadrature widely used in finite-element calculations?',choices:['To evaluate element integrals efficiently in parent coordinates','To replace boundary conditions','To create node numbers','To avoid constitutive laws'],answer:0,explanation:'Element stiffness and load integrals are often evaluated numerically after mapping to a parent domain.',source:'FEA Session 9 tracked-topic bridge'},
{id:'gauss-1d',title:'Two-point Gauss locations',level:'core',kind:'formula',q:'For standard two-point Gauss quadrature on −1≤ξ≤1, the sampling locations are:',choices:['ξ=±1/√3','ξ=±1','ξ=0 only','ξ=±√3'],answer:0,explanation:'Two-point Gauss-Legendre integration uses equal weights at ±1/√3 and exactly integrates polynomials through degree three.',math:'\\xi_{1,2}=\\pm\\frac{1}{\\sqrt3},\\quad w_1=w_2=1',source:'FEA Session 9 tracked-topic bridge'}
],
'12:Kirchhoff plate finite element formulation':[
{id:'kirchhoff-thin',title:'Kirchhoff plate assumption',level:'foundation',kind:'concept',q:'What transverse deformation is neglected in classical Kirchhoff thin-plate theory?',choices:['Transverse shear deformation','Bending curvature','Transverse displacement','In-plane stress entirely'],answer:0,explanation:'Kirchhoff plate theory assumes normals remain normal to the midsurface, analogous to Euler–Bernoulli beam theory.',source:'FEA Session 12 tracked-topic bridge'},
{id:'kirchhoff-continuity',title:'Continuity demand in Kirchhoff plates',level:'core',kind:'concept',q:'Why are Kirchhoff plate finite elements more demanding to formulate directly?',choices:['The bending energy involves second derivatives of transverse displacement, leading to C1-continuity requirements in classical displacement elements','They have no stiffness matrix','They require no shape functions','Only one node is permitted'],answer:0,explanation:'Classical Kirchhoff bending depends on curvatures, which are second derivatives of w.',math:'\\kappa_x=-\\frac{\\partial^2w}{\\partial x^2}',source:'FEA Session 12 tracked-topic bridge'}
],
'12:Mindlin plate finite element formulation':[
{id:'mindlin-shear',title:'Mindlin plate capability',level:'foundation',kind:'concept',q:'Compared with Kirchhoff plate theory, Mindlin–Reissner theory explicitly includes:',choices:['Transverse shear deformation','No rotations','Only membrane action','No bending'],answer:0,explanation:'Mindlin theory introduces independent rotations and is suitable for moderately thick plates as well as thin plates with care for locking.',source:'FEA Session 12 tracked-topic bridge'},
{id:'shear-locking',title:'Shear locking',level:'core',kind:'concept',q:'What is shear locking in a low-order Mindlin plate element?',choices:['Artificial over-stiffness as the plate becomes thin because transverse shear constraints are represented too strongly','Physical yielding of the plate','Loss of all bending stiffness','A mesh connectivity error only'],answer:0,explanation:'In the thin limit, inappropriate interpolation can make the discrete shear strain unable to vanish properly, causing excessive stiffness.',source:'FEA Session 12 tracked-topic bridge'}
],
'15:Geometric nonlinearity':[
{id:'geo-nonlinear',title:'Meaning of geometric nonlinearity',level:'foundation',kind:'concept',q:'Geometric nonlinearity becomes important when:',choices:['Equilibrium or strain-displacement relations depend materially on the deformed configuration','Young’s modulus is always constant','Loads are zero','Only temperature changes'],answer:0,explanation:'Large displacements, rotations, or instability can make geometry changes influence equilibrium and stiffness.',source:'FEA Session 15 tracked-topic bridge'},
{id:'tangent-stiffness',title:'Tangent stiffness in nonlinear FEM',level:'core',kind:'concept',q:'In an incremental Newton–Raphson solution, the tangent stiffness matrix relates:',choices:['An incremental displacement correction to the current residual-force correction','Only initial geometry to density','Stress directly to time period','Node numbers to coordinates only'],answer:0,explanation:'The nonlinear equilibrium equations are linearised about the current state using the tangent stiffness.',math:'[K_T]\\{\\Delta d\\}=\\{R\\}',source:'FEA Session 15 tracked-topic bridge'}
]
});