Object.assign(window.REVISION_BANK,{
'2:1D bar governing equation':[
{id:'bar-strong-form',title:'1D bar strong form',level:'core',kind:'formula',q:'For axial deformation of a bar with distributed load f(x), which governing equation is standard?',choices:['d/dx(AE du/dx)+f=0','AEu=f','d²u/dt²+ku=0','EI d⁴u/dx⁴=f'],answer:0,explanation:'Axial force equilibrium with constitutive law N=AE du/dx gives the strong form.',math:'\\frac{d}{dx}\\left(AE\\frac{du}{dx}\\right)+f=0',source:'Reddy Chapter 3'},
{id:'bar-constant-ae',title:'Constant AE simplification',level:'core',kind:'formula',q:'If A and E are constant, the bar equation becomes:',choices:['AE d²u/dx² + f = 0','AE du/dx + f = 0','d²u/dx² = AEf','u=f/AE always'],answer:0,explanation:'Constant AE can be taken outside the derivative.',math:'AE\\frac{d^2u}{dx^2}+f=0',source:'Reddy Chapter 3'}
],
'2:1D bar boundary conditions':[
{id:'bar-essential',title:'Bar essential boundary condition',level:'foundation',kind:'classification',q:'Which boundary condition is essential for a 1D displacement formulation?',choices:['u=u_bar at an end','N=N_bar only','E=constant','A=constant'],answer:0,explanation:'The primary variable displacement is prescribed as an essential boundary condition.',source:'Reddy Chapter 3'},
{id:'bar-natural',title:'Bar natural boundary condition',level:'core',kind:'formula',q:'At a loaded bar end, what quantity is naturally prescribed?',choices:['Axial force N=AE du/dx','Displacement only','Young modulus','Shape function number'],answer:0,explanation:'The natural quantity is the traction/resultant axial force emerging from integration by parts.',math:'N=AE\\frac{du}{dx}',source:'Reddy Chapter 3'}
],
'2:Linear Lagrange interpolation':[
{id:'lagrange-idea',title:'Lagrange interpolation idea',level:'foundation',kind:'concept',q:'What characterises Lagrange interpolation in FEM?',choices:['Interpolation functions pass exactly through nodal values','All shape functions are constant','Derivatives are always zero','Only one node is allowed'],answer:0,explanation:'Lagrange polynomials satisfy the Kronecker-delta nodal property.',source:'Reddy Chapter 3'},
{id:'linear-field',title:'Linear field reproduction',level:'core',kind:'reasoning',q:'A two-node linear bar element can reproduce exactly which displacement field?',choices:['u=a+bx','u=ax² only','u=sin x exactly for all x','Any cubic polynomial'],answer:0,explanation:'Linear interpolation exactly represents constant and linear fields.',math:'u^h(x)=N_1u_1+N_2u_2',source:'Reddy Chapter 3'}
],
'2:Weak form of a 1D element':[
{id:'bar-weak-core',title:'Bar weak-form core term',level:'core',kind:'formula',q:'Which stiffness-like term appears in the weak form of an axial bar element?',choices:['∫ AE v′u′ dx','∫ EI v″u″ dx','∫ ρuv dx only','∫ ku dx'],answer:0,explanation:'Integration by parts leads to first derivatives of test and trial functions for the axial bar.',math:'\\int_{x_1}^{x_2}AE\\,v\\prime u\\prime\\,dx',source:'Reddy Chapter 3'},
{id:'weak-boundary',title:'Weak-form boundary term',level:'core',kind:'concept',q:'What physical quantity appears in the bar weak-form boundary term?',choices:['Axial traction/force','Density only','Element number','Time period'],answer:0,explanation:'The boundary term contains the natural force quantity.',source:'Reddy Chapter 3'}
],
'3:Element connectivity':[
{id:'connectivity-meaning',title:'Connectivity meaning',level:'foundation',kind:'concept',q:'What does an element connectivity table specify?',choices:['Which global nodes belong to each element','Only material colour','The solver tolerance only','The final displacement values'],answer:0,explanation:'Connectivity maps local element node numbers to global node numbers.',source:'Reddy Chapter 3'},
{id:'connectivity-example',title:'Connectivity example',level:'application',kind:'reasoning',q:'If element e has connectivity [2,5], which global DOFs receive its two local axial-node contributions?',choices:['Those associated with global nodes 2 and 5','Only node 1','Nodes 2 through 5 all at once','No global DOFs'],answer:0,explanation:'Assembly uses the local-to-global connectivity map directly.',source:'Reddy Chapter 3'}
],
'3:Imposition of boundary conditions':[
{id:'bc-reduction',title:'Applying prescribed displacement',level:'core',kind:'reasoning',q:'Why is a prescribed displacement usually separated from unknown DOFs before solving KU=F?',choices:['Because its value is already known and the equations can be reduced accordingly','Because stiffness must be deleted entirely','Because loads become zero','Because all reactions are known first'],answer:0,explanation:'Known and unknown DOFs are partitioned so the unknown displacement vector can be solved.',source:'Reddy Chapter 3'},
{id:'reaction',title:'Recovering reactions',level:'application',kind:'formula',q:'After solving nodal displacements, reactions at restrained DOFs can be obtained from:',choices:['R=KU−F','R=K+U','R=F/U²','R=det K'],answer:0,explanation:'Substitution into the full equilibrium equations recovers support reactions.',math:'\\{R\\}=[K]\\{U\\}-\\{F\\}',source:'Reddy Chapter 3'}
],
'4:Truss element formulation':[
{id:'truss-local-k',title:'2D truss stiffness structure',level:'core',kind:'concept',q:'What additional ingredient is required to express a 2D truss element stiffness in global x-y coordinates?',choices:['Direction cosines of the member','Plate thickness only','Poisson ratio only','Beam curvature'],answer:0,explanation:'The local axial stiffness is transformed using member direction cosines.',source:'FEA Session 4 formulation bridge'},
{id:'truss-dof',title:'2D truss nodal DOFs',level:'foundation',kind:'classification',q:'How many translational DOFs does a standard 2D truss node have?',choices:['2','1','3 rotations only','6'],answer:0,explanation:'A plane truss node generally has x and y translations.',source:'FEA Session 4 formulation bridge'}
],
'5:Euler–Bernoulli beam finite element formulation':[
{id:'eb-assumption',title:'Euler–Bernoulli assumption',level:'foundation',kind:'concept',q:'Which kinematic assumption defines Euler–Bernoulli beam theory?',choices:['Plane sections remain plane and normal to the neutral axis','Shear deformation dominates','Cross-sections warp freely','Axial strain is always zero'],answer:0,explanation:'Neglecting transverse shear deformation makes section rotation equal the slope of deflection.',source:'FEA Session 5 beam bridge'},
{id:'eb-curvature',title:'Beam curvature relation',level:'core',kind:'formula',q:'For small Euler–Bernoulli bending, curvature is proportional to:',choices:['d²w/dx²','dw/dx only','w itself','d⁴w/dt⁴'],answer:0,explanation:'Bending strain and moment depend on the second derivative of transverse displacement.',math:'\\kappa\\approx\\frac{d^2w}{dx^2}',source:'FEA Session 5 beam bridge'}
],
'8:Isoparametric finite element formulation':[
{id:'iso-idea',title:'Isoparametric idea',level:'foundation',kind:'concept',q:'What does isoparametric formulation use the same shape functions to interpolate?',choices:['Geometry and field variables','Only loads','Only material modulus','Only time'],answer:0,explanation:'The same interpolation basis maps coordinates and unknown fields from the parent element.',source:'FEA Session 8 bridge'},
{id:'jacobian',title:'Jacobian role',level:'core',kind:'concept',q:'What is the main role of the Jacobian matrix in isoparametric FEM?',choices:['Transform derivatives and integration between parent and physical coordinates','Store boundary loads only','Replace constitutive matrix','Count nodes'],answer:0,explanation:'The Jacobian maps coordinate changes between ξ-η space and x-y space.',math:'[J]=\\frac{\\partial(x,y)}{\\partial(\\xi,\\eta)}',source:'FEA Session 8 bridge'}
]
});