window.REVISION_BANK={
'1:What a finite element is':[
{id:'element-idea',title:'Element as a local approximation',level:'foundation',kind:'concept',q:'What is the main purpose of a finite element?',choices:['Approximate the unknown field over a small region of the domain','Replace all boundary conditions','Represent only material density','Eliminate the need for algebra'],answer:0,explanation:'The domain is split into finite elements so the unknown field can be approximated locally and assembled globally.',source:'Reddy Chapters 1–2'},
{id:'element-field',title:'Local field approximation',level:'core',kind:'formula',q:'Which expression represents the standard interpolation idea inside an element?',choices:['u(x)=ΣN_i(x)u_i','u(x)=Σu_i/N_i','u(x)=0 for every element','u(x)=det[K]'],answer:0,explanation:'Shape functions N_i interpolate the field from nodal degrees of freedom.',math:'u(x)=\\sum_{i=1}^{n}N_i(x)u_i',source:'Reddy Chapters 1–2'},
{id:'element-benefit',title:'Why many small elements?',level:'core',kind:'reasoning',q:'Why can many simple finite elements approximate a complicated field?',choices:['Piecewise simple approximations can collectively represent complex variation','Every element is exact regardless of mesh','The governing equation disappears after meshing','Material properties no longer matter'],answer:0,explanation:'Mesh refinement and suitable interpolation let local approximations capture more complex global behaviour.',source:'Reddy Chapters 1–2'}
],
'1:Nodes and element boundaries':[
{id:'node-role',title:'Role of a node',level:'foundation',kind:'concept',q:'What is normally stored at a finite-element node?',choices:['Degrees of freedom or primary-variable values','Only element colour','Only density for the full model','The final determinant only'],answer:0,explanation:'Nodes carry the discrete unknowns used to interpolate the field inside connected elements.',source:'Reddy Chapters 1–2'},
{id:'shared-node',title:'Shared nodes and continuity',level:'core',kind:'reasoning',q:'Why do adjacent compatible elements share nodal values?',choices:['To help enforce continuity of the primary field across the mesh','To double the material stiffness automatically','To remove equilibrium equations','To avoid using shape functions'],answer:0,explanation:'Common nodal values allow compatible interpolation between neighbouring elements.',source:'Reddy Chapters 1–2'}
],
'1:Degrees of freedom':[
{id:'dof-meaning',title:'Meaning of degree of freedom',level:'foundation',kind:'concept',q:'In an FEM model, what is a degree of freedom?',choices:['An independent nodal unknown needed to describe the approximate field','A material safety factor','An element thickness only','A mesh plotting option'],answer:0,explanation:'Degrees of freedom are the discrete unknowns solved by the global algebraic system.',source:'Reddy Chapters 1–2'},
{id:'bar-dof',title:'DOF of a 1D axial bar node',level:'core',kind:'classification',q:'For a basic 1D axial bar element, what is the usual nodal degree of freedom?',choices:['Axial displacement u','Two rotations and three translations','Temperature only','Bending moment only'],answer:0,explanation:'A 1D axial bar model normally retains one axial displacement DOF per node.',source:'Reddy Chapter 3'},
{id:'beam-dof',title:'Beam nodal variables',level:'application',kind:'concept',q:'For a simple Euler–Bernoulli beam element in bending, which nodal variables are commonly used at each node?',choices:['Transverse displacement and rotation','Only axial displacement','Only stress','Only density'],answer:0,explanation:'Beam bending interpolation commonly uses transverse displacement and slope/rotation at each node.',source:'FEA beam-element prerequisite'}
],
'1:Essential and natural boundary conditions':[
{id:'essential',title:'Essential boundary condition',level:'foundation',kind:'classification',q:'Which is an essential boundary condition for a displacement-based bar problem?',choices:['Specified displacement u','Specified traction only','Material modulus E','Element length L'],answer:0,explanation:'Essential conditions prescribe the primary variable itself.',math:'u=\\bar u\\quad\\text{on }\\Gamma_u',source:'Reddy Chapters 1–3'},
{id:'natural',title:'Natural boundary condition',level:'foundation',kind:'classification',q:'Which is a natural boundary condition for a 1D bar?',choices:['Specified end force or traction','Specified displacement only','Specified node number','Specified interpolation order'],answer:0,explanation:'Natural conditions prescribe the secondary or flux/traction quantity that emerges from the weak form.',source:'Reddy Chapters 1–3'},
{id:'bc-weak',title:'Boundary conditions in weak form',level:'core',kind:'reasoning',q:'Why are natural boundary conditions called “natural” in a variational/weak formulation?',choices:['They arise naturally in the boundary term after integration by parts','They never need physical interpretation','They are always zero','They are chosen by the mesh generator'],answer:0,explanation:'Integration by parts produces a boundary term containing the natural quantity.',source:'Reddy Chapters 1–3'}
],
'1:Weak form and integration by parts':[
{id:'why-weak',title:'Why form a weak statement?',level:'foundation',kind:'concept',q:'What is one major reason for converting a strong differential equation to a weak form?',choices:['Reduce differentiability requirements on the trial solution','Remove all boundary conditions','Guarantee an exact solution with one element','Avoid numerical integration completely'],answer:0,explanation:'The weak form shifts derivatives through integration by parts and permits lower-order interpolation.',source:'Reddy Chapters 1–3'},
{id:'ibp',title:'Integration by parts pattern',level:'core',kind:'formula',q:'Which identity is the one-dimensional integration-by-parts relation?',choices:['∫v u′ dx = [vu] − ∫v′u dx','∫v u′ dx = ∫v′u dx','∫v u′ dx = vu everywhere','∫v u′ dx = 0 always'],answer:0,explanation:'Integration by parts transfers a derivative from one factor to the other and creates a boundary term.',math:'\\int_a^b v u\\prime\\,dx=[vu]_a^b-\\int_a^b v\\prime u\\,dx',source:'Reddy Chapters 1–3'},
{id:'derivative-order',title:'Derivative order reduction',level:'core',kind:'reasoning',q:'If a strong form contains a second derivative of u, what derivative order often appears on u in the corresponding weak form after one integration by parts?',choices:['First derivative','Third derivative','No u term at all','Fourth derivative'],answer:0,explanation:'One integration by parts reduces the derivative order imposed on the trial field by one.',source:'Reddy Chapters 1–3'},
{id:'test-function',title:'Role of the weight/test function',level:'application',kind:'concept',q:'In the weighted-residual or Galerkin weak form, what does the test function do?',choices:['Weights the residual so its integral statement is enforced over the domain','Sets all nodal values equal','Defines material density','Replaces the stiffness matrix'],answer:0,explanation:'The test function probes the residual in an integral sense.',source:'Reddy Chapters 1–3'}
],
'2:Shape functions':[
{id:'shape-purpose',title:'Purpose of shape functions',level:'foundation',kind:'concept',q:'What do shape functions N_i do?',choices:['Interpolate the field within an element from nodal values','Store only loads','Compute only material density','Set all elements to equal size'],answer:0,explanation:'Shape functions connect discrete nodal values to the approximate continuous field in each element.',math:'u^h(x)=\\sum_i N_i(x)u_i',source:'Reddy Chapter 3'},
{id:'linear-shape',title:'Two-node linear shape functions',level:'core',kind:'formula',q:'For a two-node 1D element spanning x₁ to x₂ with L=x₂−x₁, which pair is correct?',choices:['N₁=(x₂−x)/L, N₂=(x−x₁)/L','N₁=N₂=x/L','N₁=x², N₂=1−x²','N₁=N₂=1'],answer:0,explanation:'These functions are linear, satisfy the nodal interpolation property, and sum to one.',math:'N_1=\\frac{x_2-x}{L},\\qquad N_2=\\frac{x-x_1}{L}',source:'Reddy Chapter 3'},
{id:'partition-unity',title:'Partition of unity',level:'core',kind:'formula',q:'For standard two-node linear shape functions, what is N₁+N₂ everywhere in the element?',choices:['1','0','x','L'],answer:0,explanation:'Partition of unity ensures a constant field can be represented exactly.',math:'N_1+N_2=1',source:'Reddy Chapter 3'},
{id:'shape-graph',title:'Read the shape-function graph',level:'visual',kind:'graph',q:'At x/L = 0, what are the values of N₁ and N₂ for a standard two-node linear element?',choices:['N₁=1, N₂=0','N₁=0, N₂=1','N₁=N₂=0.5','N₁=N₂=1'],answer:0,explanation:'At node 1, its own shape function equals one and the other equals zero.',graph:{xLabel:'x/L',yLabel:'N',alt:'Linear shape functions',series:[{label:'N1',points:[[0,1],[1,0]]},{label:'N2',points:[[0,0],[1,1]]}]},source:'Reddy Chapter 3'}
],
'2:Kronecker-delta interpolation property':[
{id:'delta-property',title:'Nodal interpolation property',level:'core',kind:'formula',q:'What does N_i(x_j)=δ_ij mean?',choices:['Shape function i is 1 at its own node and 0 at the other interpolation nodes','All shape functions are always 1','Every node has the same displacement','Shape functions are derivatives of loads'],answer:0,explanation:'This property makes nodal coefficients equal to nodal values of the approximated field.',math:'N_i(x_j)=\\delta_{ij}',source:'Reddy Chapter 3'},
{id:'node2',title:'Evaluate at node 2',level:'application',kind:'numerical',q:'For a two-node linear element, what are N₁ and N₂ at x=x₂?',choices:['N₁=0, N₂=1','N₁=1, N₂=0','N₁=N₂=0','N₁=N₂=1'],answer:0,explanation:'At node 2, the second shape function is one and the first is zero.',source:'Reddy Chapter 3'}
],
'2:Element coefficient/stiffness matrix':[
{id:'bar-k',title:'Axial bar stiffness matrix',level:'core',kind:'formula',q:'For a uniform 2-node axial bar element, which stiffness matrix is correct?',choices:['(AE/L)[[1,−1],[−1,1]]','(AE/L)[[1,1],[1,1]]','(L/AE)[[1,−1],[−1,1]]','AE L I'],answer:0,explanation:'The bar stiffness follows from integrating BᵀEA B over the element.',math:'[k^{(e)}]=\\frac{AE}{L}\\begin{bmatrix}1&-1\\\\-1&1\\end{bmatrix}',source:'Reddy Chapter 3'},
{id:'matrix-symmetry',title:'Why stiffness is symmetric',level:'core',kind:'concept',q:'For the standard linear elastic bar formulation, the element stiffness matrix is:',choices:['Symmetric','Always diagonal','Always nonsquare','Skew-symmetric'],answer:0,explanation:'The standard energy-based linear elastic formulation produces a symmetric stiffness matrix.',source:'Reddy Chapter 3'},
{id:'rigid-mode',title:'Rigid translation check',level:'application',kind:'reasoning',q:'What internal force should the bar stiffness matrix produce for nodal displacement vector [a,a]ᵀ?',choices:['Zero internal force','A nonzero tensile force','A nonzero bending moment','An undefined result'],answer:0,explanation:'Equal translation of both nodes causes no strain, so the element develops no axial internal force.',math:'[k^{(e)}]\\begin{bmatrix}a\\\\a\\end{bmatrix}=\\mathbf0',source:'Reddy Chapter 3'}
],
'3:Assembly into global equations':[
{id:'assembly-purpose',title:'Purpose of assembly',level:'foundation',kind:'concept',q:'What does assembly do in FEM?',choices:['Combines element equations into one global system using connectivity','Deletes shared nodes','Makes every element independent','Replaces the material model'],answer:0,explanation:'Element contributions are added into global rows and columns corresponding to shared global degrees of freedom.',source:'Reddy Chapter 3'},
{id:'global-form',title:'Global equilibrium form',level:'core',kind:'formula',q:'Which equation is the standard assembled linear static FEM system?',choices:['KU=F','K+U=F','K/F=U²','det(K)=F'],answer:0,explanation:'The assembled stiffness matrix K relates global nodal unknowns U to the global load vector F.',math:'[K]\\{U\\}=\\{F\\}',source:'Reddy Chapter 3'},
{id:'shared-add',title:'Shared-node contribution',level:'application',kind:'reasoning',q:'If two elements meet at one global node, what happens to their stiffness contributions associated with that DOF?',choices:['They are added into the same global matrix location','One contribution is discarded','They are multiplied together','The node is duplicated permanently'],answer:0,explanation:'Assembly superposes all element contributions acting on a shared global degree of freedom.',source:'Reddy Chapter 3'}
]};