window.REVISION_BANK={
'1:Indicial Notation':[
{id:'indices-free-dummy',title:'Free and dummy indices',level:'foundation',kind:'concept',q:'In the expression a_i b_i, what happens to the repeated index i?',choices:['It is summed over its allowed values','It is a free index that remains in the answer','It means both terms are differentiated','It means i is a physical unit'],answer:0,explanation:'Under Einstein summation convention, an index repeated exactly twice in a term is a dummy index and is summed.',math:'a_i b_i=\\sum_{i=1}^{3}a_i b_i',source:'Session 1 prerequisite bridge'},
{id:'kronecker',title:'Kronecker delta',level:'core',kind:'formula',q:'Which value does the Kronecker delta δ_ij take when i = j?',choices:['1','0','−1','It depends on the vector magnitude'],answer:0,explanation:'The Kronecker delta is 1 when the indices match and 0 otherwise.',math:'\\delta_{ij}=\\begin{cases}1,&i=j\\\\0,&i\\ne j\\end{cases}',source:'Session 1 prerequisite bridge'},
{id:'index-validity',title:'Check an index equation',level:'core',kind:'reasoning',q:'Which equation is index-consistent?',choices:['a_i=b_i+c_i','a_i=b_j+c_i','a_i=b_i+c_j','a_i=b_j c_j'],answer:0,explanation:'Free indices must match on every additive term. In a_i=b_i+c_i, i is the same free index throughout.',source:'Session 1 prerequisite bridge'},
{id:'dot-index',title:'Dot product in indices',level:'application',kind:'formula',q:'Which indicial expression represents the dot product a·b?',choices:['a_i b_i','a_i b_j','a_i+b_i','a_i/b_j'],answer:0,explanation:'The repeated index is summed, giving a scalar.',math:'\\mathbf a\\cdot\\mathbf b=a_i b_i',source:'Session 1 prerequisite bridge'}
],
'1:Vectors':[
{id:'vector-magnitude',title:'Vector magnitude',level:'foundation',kind:'formula',q:'For a vector a = [3, 4, 0], what is its magnitude?',choices:['5','7','12','25'],answer:0,explanation:'Magnitude is the square root of the sum of squared components.',math:'\\|\\mathbf a\\|=\\sqrt{a_x^2+a_y^2+a_z^2}=\\sqrt{3^2+4^2}=5',source:'Session 1 prerequisite bridge'},
{id:'unit-vector',title:'Construct a unit vector',level:'core',kind:'numerical',q:'If a = [0, 3, 4], which is the unit vector in the direction of a?',choices:['[0, 3/5, 4/5]','[0, 3, 4]','[0, 5, 5]','[1, 3, 4]'],answer:0,explanation:'Divide every component by the vector magnitude 5.',math:'\\hat{\\mathbf a}=\\frac{\\mathbf a}{\\|\\mathbf a\\|}',source:'Session 1 prerequisite bridge'},
{id:'resultant',title:'Add vector components',level:'application',kind:'numerical',q:'For F₁ = [10, 0, 0] N and F₂ = [0, 5, 0] N, what is the resultant?',choices:['[10, 5, 0] N','[15, 0, 0] N','[10, 0, 5] N','[5, 10, 0] N'],answer:0,explanation:'Vector addition is performed component by component.',math:'\\mathbf R=\\mathbf F_1+\\mathbf F_2',source:'Session 1 prerequisite bridge'}
],
'2:Dot Product and Cross Product':[
{id:'dot-angle',title:'Angle from dot product',level:'core',kind:'formula',q:'Which relation connects the dot product to the angle θ between two vectors?',choices:['a·b = |a||b| cos θ','a·b = |a||b| sin θ','a×b = |a||b| cos θ','a+b = |a||b|'],answer:0,explanation:'The dot product measures the component of one vector along another.',math:'\\mathbf a\\cdot\\mathbf b=\\|\\mathbf a\\|\\|\\mathbf b\\|\\cos\\theta',source:'Session 2 prerequisite bridge'},
{id:'cross-direction',title:'Cross-product direction',level:'core',kind:'concept',q:'For non-parallel vectors a and b, the vector a×b is:',choices:['Perpendicular to both a and b','Parallel to both a and b','Always zero','Always a scalar'],answer:0,explanation:'The cross product produces a vector normal to the plane containing the two vectors.',source:'Session 2 prerequisite bridge'},
{id:'orthogonal-dot',title:'Recognise orthogonality',level:'application',kind:'numerical',q:'If a·b = 0 and neither vector is zero, what is the angle between them?',choices:['90°','0°','45°','180°'],answer:0,explanation:'A zero dot product means cos θ = 0, hence θ = 90°.',math:'\\cos\\theta=0\\Rightarrow\\theta=90^\\circ',source:'Session 2 prerequisite bridge'}
],
'3:Definition of stress as a tensor':[
{id:'stress-symmetry',title:'Stress tensor symmetry',level:'core',kind:'concept',q:'In classical continuum mechanics with no couple stresses, what relation follows from moment equilibrium?',choices:['σ_ij = σ_ji','σ_ij = −σ_ji','All shear stresses are zero','All normal stresses are equal'],answer:0,explanation:'Angular momentum balance makes the Cauchy stress tensor symmetric in the classical theory.',math:'\\sigma_{ij}=\\sigma_{ji}',source:'Continuum mechanics bridge from Session 3'},
{id:'tensor-components',title:'Independent components',level:'core',kind:'concept',q:'How many independent components does a symmetric 3D stress tensor have?',choices:['6','9','3','12'],answer:0,explanation:'Three normal stresses plus three independent shear stresses give six independent components.',source:'Session 3 tensor concept'},
{id:'normal-shear',title:'Normal versus shear components',level:'foundation',kind:'classification',q:'Which are the normal stress components in Cartesian coordinates?',choices:['σ_xx, σ_yy, σ_zz','σ_xy, σ_yz, σ_zx','σ_xx, σ_xy, σ_xz','τ_xy only'],answer:0,explanation:'Normal stress uses the same direction for face normal and traction component.',source:'Session 3 stress tensor concept'},
{id:'tensor-matrix',title:'Read a stress matrix',level:'application',kind:'numerical',q:'For σ = [[3,2,15],[2,−7,−16],[15,−16,−1]] MPa, what is σ_yy?',choices:['−7 MPa','3 MPa','2 MPa','−16 MPa'],answer:0,explanation:'σ_yy is the second-row, second-column normal stress component.',source:'Uploaded Session 3 stress-tensor example'}
],
'3:Traction to stress relationship':[
{id:'cauchy-formula',title:'Cauchy traction formula',level:'core',kind:'formula',q:'Which equation gives traction t on a plane with unit normal n?',choices:['t_i = σ_ij n_j','t_i = n_i/σ_ij','t_i = σ_ii only','t_i = ∂σ/∂t'],answer:0,explanation:'Cauchy’s formula maps the plane normal through the stress tensor to the traction vector.',math:'t_i=\\sigma_{ij}n_j\\quad\\text{or}\\quad\\mathbf t^{(n)}=\\boldsymbol\\sigma\\mathbf n',source:'Session 3 traction–stress relationship'},
{id:'normal-traction',title:'Extract normal traction',level:'application',kind:'formula',q:'After finding traction t on a plane, which expression gives the scalar normal stress on that plane?',choices:['σ_n = t·n','σ_n = |t×n|','σ_n = tr(σ)','σ_n = det(σ)'],answer:0,explanation:'Project traction onto the unit normal to obtain the normal component.',math:'\\sigma_n=\\mathbf t\\cdot\\mathbf n',source:'Session 3 traction concept'}
],
'4:Principal Stress':[
{id:'principal-def',title:'Principal-plane condition',level:'foundation',kind:'concept',q:'On a principal plane, the traction vector is:',choices:['Parallel to the plane normal','Perpendicular to the plane normal','Always zero','Always parallel to the x-axis'],answer:0,explanation:'Principal planes carry no shear traction, so traction is purely normal.',source:'Session 4 principal stress bridge'},
{id:'2d-principal',title:'2D principal stresses',level:'application',kind:'formula',q:'For a 2D stress state, which expression gives the two principal stresses?',choices:['(σx+σy)/2 ± √[((σx−σy)/2)²+τxy²]','σx+σy±τxy','σxσy−τxy','√(σx²+σy²)'],answer:0,explanation:'The principal stresses are the eigenvalues of the 2D stress matrix.',math:'\\sigma_{1,2}=\\frac{\\sigma_x+\\sigma_y}{2}\\pm\\sqrt{\\left(\\frac{\\sigma_x-\\sigma_y}{2}\\right)^2+\\tau_{xy}^2}',source:'Session 4 continuum mechanics bridge'},
{id:'principal-shear',title:'Shear on a principal plane',level:'core',kind:'concept',q:'What is the shear stress on an ideal principal plane?',choices:['0','σ1','σ2','Always the maximum shear stress'],answer:0,explanation:'Principal directions are defined by zero shear traction.',source:'Session 4 principal stress bridge'}
],
'11:Euler’s Buckling':[
{id:'euler-load',title:'Euler critical load',level:'core',kind:'formula',q:'Which expression gives Euler critical load for a prismatic ideal column?',choices:['Pcr = π²EI/(KL)²','Pcr = EI/L','Pcr = AE/L','Pcr = σyA only'],answer:0,explanation:'The effective length KL controls the elastic buckling load.',math:'P_{cr}=\\frac{\\pi^2EI}{(KL)^2}',source:'Session 11 buckling bridge'},
{id:'length-effect',title:'Effect of column length',level:'application',kind:'reasoning',q:'If an Euler column effective length doubles while E and I stay unchanged, Pcr becomes:',choices:['One quarter','One half','Twice','Four times'],answer:0,explanation:'Euler load varies inversely with the square of effective length.',math:'P_{cr}\\propto\\frac{1}{L_e^2}',source:'Session 11 buckling bridge'},
{id:'slenderness',title:'Slenderness ratio',level:'core',kind:'formula',q:'Which expression defines member slenderness ratio?',choices:['λ = KL/r','λ = A/L','λ = EI/L','λ = P/A'],answer:0,explanation:'Slenderness compares effective length with radius of gyration.',math:'\\lambda=\\frac{KL}{r}',source:'Session 11 buckling bridge'}
]};