Object.assign(window.REVISION_BANK,{
'7:2D Problems':[
{id:'asms7-2d-airy',title:'Recovering shear stress from an Airy function',level:'core',kind:'formula',q:'For an Airy stress function \\(\\Phi(x,y)\\), the in-plane shear stress is obtained from:',choices:['\\(-\\partial^2\\Phi/(\\partial x\\partial y)\\)','\\(\\partial^2\\Phi/\\partial x^2\\)','\\(\\partial\\Phi/\\partial y\\)','\\(\\nabla^2\\Phi\\)'],answer:0,explanation:'The Airy stress-function definition gives the shear component as the negative mixed second derivative.',math:'\\tau_{xy}=-\\frac{\\partial^2\\Phi}{\\partial x\\partial y}',source:'ST ZG552 Session 7 topic + standard elasticity bridge (model supplement)'},
{id:'asms7-2d-biharmonic-check',title:'Checking an admissible Airy field',level:'application',kind:'reasoning',q:'A proposed polynomial Airy stress function is admissible for homogeneous isotropic plane elasticity without body force only if it satisfies:',choices:['\\(\\nabla^4\\Phi=0\\)','\\(\\nabla\\Phi=0\\)','\\(\\Phi=0\\) on every boundary','\\(\\det[\\sigma]=0\\)'],answer:0,explanation:'Equilibrium is automatically satisfied by the Airy representation; compatibility and constitutive relations require the biharmonic equation.',math:'\\nabla^4\\Phi=\\left(\\frac{\\partial^2}{\\partial x^2}+\\frac{\\partial^2}{\\partial y^2}\\right)^2\\Phi=0',source:'ST ZG552 Session 7 topic + standard elasticity bridge (model supplement)'}
],
'8:Constitutive Relationship':[
{id:'asms7-ortho-constants',title:'Orthotropic material directions',level:'foundation',kind:'concept',q:'An orthotropic elastic material has how many mutually perpendicular material symmetry directions?',choices:['Three','One','Two only','Infinitely many identical directions'],answer:0,explanation:'Orthotropy is defined by three mutually orthogonal planes/directions of material symmetry, with generally different elastic properties along them.',source:'ST ZG552 Session 8 topic + standard anisotropic-elasticity bridge (model supplement)'},
{id:'asms7-ortho-reciprocity',title:'Poisson-ratio reciprocity',level:'advanced',kind:'formula',q:'For a linear orthotropic solid, symmetry of the compliance matrix requires which reciprocity relation?',choices:['\\(\\nu_{12}/E_1=\\nu_{21}/E_2\\)','\\(\\nu_{12}E_1=\\nu_{21}E_2=1\\)','\\(E_1=E_2=E_3\\) always','\\(G_{12}=E_1\\)'],answer:0,explanation:'Reciprocal Poisson ratios are not independent; major symmetry of the elastic compliance tensor gives this relation.',math:'\\frac{\\nu_{12}}{E_1}=\\frac{\\nu_{21}}{E_2}',source:'ST ZG552 Session 8 topic + standard anisotropic-elasticity bridge (model supplement)'}
],
'10:Concept of Shear centre':[
{id:'asms7-sc-definition',title:'Shear-centre loading condition',level:'foundation',kind:'concept',q:'A transverse load applied through the shear centre of a thin-walled section ideally causes:',choices:['Bending without twist due to that load','Pure twist with no bending','Uniform axial strain only','Zero shear stress everywhere'],answer:0,explanation:'The shear centre is the point through which transverse loading produces no resultant twisting moment.',source:'ST ZG552 Session 10 topic + standard thin-walled-section bridge (model supplement)',visual:{type:'section-diagram',description:'Channel or angle section showing centroid, shear centre and transverse load line'}},
{id:'asms7-sc-channel',title:'Open channel shear centre location',level:'application',kind:'reasoning',q:'For a thin-walled channel section with one axis of symmetry, the shear centre must lie:',choices:['On the symmetry axis, and it may lie outside the material area','At any point inside the web','Always at the centroid','At the flange tip only'],answer:0,explanation:'Symmetry constrains the shear centre to the symmetry axis; for open channels its location is commonly outside the section.',source:'ST ZG552 Session 10 topic + standard thin-walled-section bridge (model supplement)',visual:{type:'section-diagram',description:'C-channel with symmetry axis and external shear-centre point'}}
],
'12:Equations for elastic support':[
{id:'asms7-elastic-support',title:'Spring support force',level:'core',kind:'formula',q:'For a linear translational elastic support of stiffness \\(k_s\\) undergoing displacement \\(v\\), the support force magnitude is:',choices:['\\(k_s v\\)','\\(k_s/v\\)','\\(EI v\\)','\\(v/k_s^2\\)'],answer:0,explanation:'A linear elastic support follows Hooke-type behaviour: reaction is proportional to local displacement.',math:'R_s=k_s v',source:'ST ZG552 Session 12 topic + standard beam-column stability bridge (model supplement)'}
],
'16:Introduction to Buckling of plates':[
{id:'asms7-plate-k',title:'Elastic plate-buckling stress form',level:'advanced',kind:'formula',q:'For a thin rectangular plate in uniform compression, the classical elastic buckling stress has the form:',choices:['\\(\\sigma_{cr}=k\\pi^2E/[12(1-\\nu^2)](t/b)^2\\)','\\(\\sigma_{cr}=EA/L\\)','\\(\\sigma_{cr}=kEt/b\\)','\\(\\sigma_{cr}=\\pi^2EI/L^2\\)'],answer:0,explanation:'Plate buckling depends on the plate coefficient k, material stiffness, Poisson ratio and the square of thickness-to-width ratio.',math:'\\sigma_{cr}=\\frac{k\\pi^2E}{12(1-\\nu^2)}\\left(\\frac{t}{b}\\right)^2',source:'ST ZG552 Session 16 topic + standard plate-stability bridge (model supplement)',visual:{type:'buckling-mode',description:'Simply supported rectangular plate with half-wave buckling pattern'}}
]
});