Object.assign(window.REVISION_BANK,{
'5:Strain':[
{id:'strain-normal',title:'Normal strain meaning',level:'foundation',kind:'concept',q:'What does normal strain measure?',choices:['Change in length divided by original length','Force divided by area','Moment divided by curvature','Energy per cycle'],answer:0,explanation:'Normal strain measures relative extension or shortening.',math:'\\varepsilon=\\frac{\\Delta L}{L_0}',source:'Session 5 continuum mechanics bridge'},
{id:'strain-small',title:'Small-strain kinematics',level:'core',kind:'formula',q:'For small deformation in 1D, normal strain is approximated by:',choices:['du/dx','u/x²','d²u/dx²','EA/L'],answer:0,explanation:'The displacement gradient gives axial strain in the small-strain approximation.',math:'\\varepsilon_x=\\frac{du}{dx}',source:'Session 5 continuum mechanics bridge'},
{id:'strain-number',title:'Axial strain numerical',level:'application',kind:'numerical',q:'A 2 m bar elongates by 1 mm. What is the axial strain?',choices:['0.0005','0.005','0.05','0.5'],answer:0,explanation:'Use consistent units: 0.001/2 = 0.0005.',math:'\\varepsilon=\\frac{0.001}{2}=5\\times10^{-4}',source:'Session 5 continuum mechanics bridge'}
],
'5:Generalized Hookes Law':[
{id:'hooke-1d',title:'1D Hooke law',level:'foundation',kind:'formula',q:'In uniaxial linear elasticity, which relation is correct?',choices:['σ=Eε','σ=ε/E','σ=E/ε','σ=Gγ²'],answer:0,explanation:'Young’s modulus relates normal stress and normal strain in linear elasticity.',math:'\\sigma=E\\varepsilon',source:'Session 5 elasticity bridge'},
{id:'poisson',title:'Poisson effect',level:'core',kind:'concept',q:'Under uniaxial tension, a positive Poisson ratio means the material usually:',choices:['Contracts laterally','Expands laterally by the same strain','Has zero axial strain','Develops no stress'],answer:0,explanation:'Poisson ratio relates lateral contraction to axial extension.',math:'\\nu=-\\frac{\\varepsilon_{lat}}{\\varepsilon_{ax}}',source:'Session 5 elasticity bridge'},
{id:'shear-modulus',title:'Elastic constants relation',level:'core',kind:'formula',q:'For an isotropic linear elastic material, which relation connects E, G and ν?',choices:['G=E/[2(1+ν)]','G=E(1+ν)','G=2E/(1−ν)','G=ν/E'],answer:0,explanation:'Only two elastic constants are independent for isotropic linear elasticity.',math:'G=\\frac{E}{2(1+\\nu)}',source:'Session 5 elasticity bridge'}
],
'6:Equilibrium equations':[
{id:'equilibrium-local',title:'Local equilibrium',level:'core',kind:'formula',q:'In static continuum equilibrium with body force b_i, which index equation is correct?',choices:['σ_ij,j + b_i = 0','σ_ij + b_j = 1','σ_ii = 0','ε_ij,j = b_i'],answer:0,explanation:'The divergence of stress plus body force must vanish in static equilibrium.',math:'\\sigma_{ij,j}+b_i=0',source:'Session 6 continuum mechanics bridge'},
{id:'equilibrium-meaning',title:'Why equilibrium matters',level:'foundation',kind:'concept',q:'What does the differential equilibrium equation enforce?',choices:['Force balance on an infinitesimal material region','Only geometric compatibility','Only constitutive behaviour','Only boundary displacement'],answer:0,explanation:'Equilibrium is the local form of force balance.',source:'Session 6 continuum mechanics bridge'}
],
'6:Compatibility':[
{id:'compatibility-meaning',title:'Compatibility meaning',level:'foundation',kind:'concept',q:'What is the purpose of strain compatibility equations?',choices:['Ensure the strain field can arise from a continuous displacement field','Ensure stress always equals zero','Replace material properties','Determine only boundary traction'],answer:0,explanation:'Compatibility prevents gaps or overlaps in a continuous body.',source:'Session 6 continuum mechanics bridge'},
{id:'compatibility-2d',title:'2D compatibility relation',level:'core',kind:'formula',q:'Which expression is a standard small-strain 2D compatibility relation?',choices:['∂²εx/∂y² + ∂²εy/∂x² = ∂²γxy/∂x∂y','εx+εy=0','σx=σy','γxy=εxεy'],answer:0,explanation:'This relation ensures the strain components derive from compatible displacements.',math:'\\frac{\\partial^2\\varepsilon_x}{\\partial y^2}+\\frac{\\partial^2\\varepsilon_y}{\\partial x^2}=\\frac{\\partial^2\\gamma_{xy}}{\\partial x\\partial y}',source:'Session 6 continuum mechanics bridge'}
],
'9:Deviatoric Stress':[
{id:'deviatoric-def',title:'Deviatoric stress definition',level:'core',kind:'formula',q:'How is the deviatoric stress tensor s_ij obtained from σ_ij?',choices:['Subtract one-third of the trace times δ_ij','Add the trace to every shear term','Divide every component by determinant','Set normal stresses to zero'],answer:0,explanation:'The deviator removes the hydrostatic or mean-stress part.',math:'s_{ij}=\\sigma_{ij}-\\frac{1}{3}\\sigma_{kk}\\delta_{ij}',source:'Session 9 plasticity bridge'},
{id:'hydrostatic-dev',title:'Pure hydrostatic stress',level:'application',kind:'reasoning',q:'For σ1=σ2=σ3=p with no shear, what is the deviatoric stress tensor?',choices:['Zero','pI','3pI','Undefined'],answer:0,explanation:'Pure hydrostatic stress contains no distortional component.',source:'Session 9 plasticity bridge'},
{id:'mean-stress',title:'Mean stress',level:'core',kind:'formula',q:'What is the mean normal stress?',choices:['(σ1+σ2+σ3)/3','σ1−σ3','σ1σ2σ3','√J2'],answer:0,explanation:'Mean stress is one-third of the first stress invariant.',math:'\\sigma_m=\\frac{\\sigma_1+\\sigma_2+\\sigma_3}{3}',source:'Session 9 plasticity bridge'}
],
'9:Yield Criteria':[
{id:'vonmises-idea',title:'Von Mises idea',level:'foundation',kind:'concept',q:'The von Mises yield criterion is primarily associated with which part of stress?',choices:['Distortional/deviatoric stress','Hydrostatic stress alone','Temperature alone','Only first principal stress'],answer:0,explanation:'Von Mises yielding is governed by the distortional energy represented through J2.',source:'Session 9 plasticity bridge'},
{id:'vonmises-principal',title:'Von Mises equivalent stress',level:'core',kind:'formula',q:'Which expression gives von Mises equivalent stress in principal stresses?',choices:['sqrt(((σ1−σ2)^2+(σ2−σ3)^2+(σ3−σ1)^2)/2)','σ1+σ2+σ3','σ1σ2σ3','(σ1+σ3)/2'],answer:0,explanation:'This principal-stress form measures distortional intensity.',math:'\\sigma_v=\\sqrt{\\frac{(\\sigma_1-\\sigma_2)^2+(\\sigma_2-\\sigma_3)^2+(\\sigma_3-\\sigma_1)^2}{2}}',source:'Session 9 plasticity bridge'},
{id:'tresca',title:'Tresca criterion',level:'core',kind:'concept',q:'Tresca yielding is based on:',choices:['Maximum shear stress','Mean normal stress only','Volumetric strain only','Young’s modulus'],answer:0,explanation:'Tresca associates yielding with the maximum shear stress reaching its uniaxial-yield value.',source:'Session 9 plasticity bridge'}
],
'10:Equation of Torsion in 1d':[
{id:'torsion-basic',title:'Circular shaft torsion',level:'core',kind:'formula',q:'For Saint-Venant torsion of a circular shaft, which relation is correct?',choices:['T/J = τ/r = Gθ/L','T/J = Eε','T=AE/L','τ=My/I'],answer:0,explanation:'Torque, shear stress and twist are linked through the torsion equation.',math:'\\frac{T}{J}=\\frac{\\tau}{r}=\\frac{G\\theta}{L}',source:'Session 10 torsion bridge'},
{id:'polar-j',title:'Polar moment role',level:'foundation',kind:'concept',q:'In circular-shaft torsion, a larger polar second moment J generally makes the shaft:',choices:['More torsionally stiff','Less torsionally stiff','Independent of geometry','Unable to carry torque'],answer:0,explanation:'Torsional stiffness is GJ/L.',math:'k_t=\\frac{GJ}{L}',source:'Session 10 torsion bridge'}
],
'10:Warping':[
{id:'warping-meaning',title:'Warping meaning',level:'foundation',kind:'concept',q:'What is warping in torsion?',choices:['Out-of-plane longitudinal displacement of cross-section points','Uniform axial shortening only','Pure rigid translation','Only local yielding'],answer:0,explanation:'Noncircular sections generally do not remain perfectly plane under torsion; points can displace longitudinally.',source:'Session 10 torsion bridge'},
{id:'circular-warping',title:'Circular shaft warping',level:'core',kind:'concept',q:'For an ideal circular shaft in Saint-Venant torsion, cross-sectional warping is:',choices:['Zero','Always maximum','Equal to bending deflection','Undefined'],answer:0,explanation:'Circular sections can twist without longitudinal warping in Saint-Venant torsion.',source:'Session 10 torsion bridge'}
]
});