Object.assign(window.REVISION_BANK,{
'7:Airys stress Function':[
{id:'airy-equilibrium',title:'Why Airy stress functions help',level:'foundation',kind:'concept',q:'In a 2D elasticity problem without body forces, why is an Airy stress function useful?',choices:['Its stress definitions satisfy the planar equilibrium equations automatically','It makes all stresses zero','It replaces constitutive relations','It is only a numerical integration rule'],answer:0,explanation:'Defining the in-plane stresses from second derivatives of a scalar Airy function makes the two static equilibrium equations identically satisfied.',math:'\\sigma_x=\\frac{\\partial^2\\Phi}{\\partial y^2},\\quad \\sigma_y=\\frac{\\partial^2\\Phi}{\\partial x^2},\\quad \\tau_{xy}=-\\frac{\\partial^2\\Phi}{\\partial x\\partial y}',source:'Session 7 Airy-stress-function bridge'},
{id:'airy-biharmonic',title:'Biharmonic requirement',level:'core',kind:'formula',q:'For homogeneous isotropic plane elasticity with no body forces, the Airy stress function must satisfy which equation?',choices:['∇⁴Φ = 0','∇²Φ = 1','dΦ/dt = 0','det(Φ) = 0'],answer:0,explanation:'Compatibility together with linear isotropic elasticity leads to the biharmonic equation for the Airy stress function.',math:'\\nabla^4\\Phi=0',source:'Session 7 Airy-stress-function bridge'}
],
'7:2D Problems':[
{id:'plane-stress-2d',title:'Recognise plane stress',level:'foundation',kind:'classification',q:'Which condition best represents an ideal plane-stress state?',choices:['σ_z = τ_xz = τ_yz = 0','ε_z = γ_xz = γ_yz = 0','All in-plane stresses are zero','σ_x = σ_y = σ_z always'],answer:0,explanation:'Thin plates loaded in their plane are commonly idealised with negligible out-of-plane stress components.',math:'\\sigma_z=\\tau_{xz}=\\tau_{yz}=0',source:'Session 7 two-dimensional elasticity bridge'},
{id:'2d-equilibrium',title:'2D equilibrium equations',level:'core',kind:'formula',q:'With no body forces, which pair is the planar equilibrium system?',choices:['∂σ_x/∂x + ∂τ_xy/∂y = 0 and ∂τ_xy/∂x + ∂σ_y/∂y = 0','∂σ_x/∂y = 1 and ∂σ_y/∂x = 1','σ_x+σ_y=0 only','τ_xy=0 always'],answer:0,explanation:'Force balance in the x and y directions gives the two planar differential equilibrium equations.',math:'\\frac{\\partial\\sigma_x}{\\partial x}+\\frac{\\partial\\tau_{xy}}{\\partial y}=0,\\qquad \\frac{\\partial\\tau_{xy}}{\\partial x}+\\frac{\\partial\\sigma_y}{\\partial y}=0',source:'Session 7 two-dimensional elasticity bridge'}
],
'8:Constitutive Relationship':[
{id:'constitutive-purpose',title:'Constitutive law role',level:'foundation',kind:'concept',q:'What does a constitutive relationship connect in solid mechanics?',choices:['Stress and strain through material properties','Load and time only','Geometry and mesh size only','Boundary conditions and node numbers'],answer:0,explanation:'Equilibrium and compatibility describe mechanics and kinematics; a constitutive law supplies the material stress-strain response.',math:'\\{\\sigma\\}=[D]\\{\\varepsilon\\}',source:'Session 8 constitutive-relationship bridge'},
{id:'orthotropic-axes',title:'Orthotropic material axes',level:'core',kind:'concept',q:'An orthotropic elastic material has:',choices:['Three mutually perpendicular material symmetry directions','Exactly the same properties in every direction','No elastic constants','Only one possible stress component'],answer:0,explanation:'Orthotropy allows different elastic properties along three orthogonal material axes while retaining symmetry about those axes.',source:'Session 8 orthotropic-material bridge'}
],
'8:Rotation and Reduction of the constants':[
{id:'rotate-stiffness',title:'Why rotate material constants?',level:'foundation',kind:'reasoning',q:'Why must an orthotropic constitutive matrix sometimes be transformed?',choices:['The material principal axes may not coincide with the global analysis axes','Young’s modulus changes with mesh size','Stress is always coordinate independent component-by-component','Rotation eliminates shear strain'],answer:0,explanation:'The physical tensor relation is invariant, but its component matrix changes when expressed in a rotated coordinate system.',source:'Session 8 orthotropic-transformation bridge'},
{id:'transform-stress',title:'Tensor transformation idea',level:'core',kind:'formula',q:'Which compact tensor expression represents rotation of a second-order stress tensor?',choices:['σ′ = Q σ Qᵀ','σ′ = Q + σ','σ′ = det(Q)σ only','σ′ = QᵀQ only'],answer:0,explanation:'A second-order tensor transforms with the rotation matrix on both sides.',math:'[\\sigma\\prime]=[Q][\\sigma][Q]^T',source:'Session 8 tensor-rotation bridge'}
],
'9:Principal Stress Axes':[
{id:'principal-axis-eigenvector',title:'Principal axes as eigenvectors',level:'core',kind:'concept',q:'The principal stress directions are obtained from:',choices:['Eigenvectors of the stress tensor','The trace alone','Young’s modulus alone','The determinant of strain only'],answer:0,explanation:'Each principal direction is an eigenvector of the symmetric stress tensor, paired with a principal-stress eigenvalue.',math:'[\\sigma]\\mathbf n=\\sigma_p\\mathbf n',source:'Session 9 principal-axis bridge'},
{id:'principal-orthogonal',title:'Orthogonality of principal axes',level:'core',kind:'reasoning',q:'For a real symmetric Cauchy stress tensor with distinct principal stresses, the principal directions are:',choices:['Mutually orthogonal','Always parallel','Undefined','Necessarily aligned with global x only'],answer:0,explanation:'A real symmetric tensor has orthogonal eigenvectors associated with distinct eigenvalues.',source:'Session 9 principal-axis bridge'}
],
'9:Introduction to Plastic Flow Theory':[
{id:'flow-rule',title:'Plastic flow direction',level:'foundation',kind:'concept',q:'What does a plastic flow rule determine after yielding begins?',choices:['The direction of the plastic strain increment','Only the elastic modulus','The member span','The hydrostatic pressure alone'],answer:0,explanation:'A flow rule connects the yield/plastic-potential surface to the increment of plastic strain.',source:'Session 9 plastic-flow bridge'},
{id:'associated-flow',title:'Associated flow rule',level:'core',kind:'formula',q:'In associated plasticity, the plastic strain increment is normal to which surface?',choices:['The yield surface','The undeformed boundary','The Mohr circle only','The elastic stress-strain line'],answer:0,explanation:'For an associated flow rule, the plastic potential is the yield function, so the plastic strain increment follows its stress gradient.',math:'d\\varepsilon^p_{ij}=d\\lambda\\,\\frac{\\partial f}{\\partial\\sigma_{ij}}',source:'Session 9 plastic-flow bridge'}
],
'12:Equations for elastic support':[
{id:'spring-support',title:'Elastic support reaction',level:'foundation',kind:'formula',q:'For a linear translational elastic support of stiffness k_s and displacement y, what reaction magnitude does the spring develop?',choices:['k_s y','k_s/y','EIy','y/k_s²'],answer:0,explanation:'A linear spring develops a restoring force proportional to its displacement.',math:'R_s=k_s y',source:'Session 12 elastic-support bridge'},
{id:'support-limit',title:'Very stiff elastic support',level:'application',kind:'reasoning',q:'As an elastic support stiffness k_s becomes extremely large, its supported translation tends toward:',choices:['Zero','Infinity','The member length','A fixed nonzero value independent of load'],answer:0,explanation:'A very stiff spring approaches an ideal translational restraint because finite force produces vanishing displacement.',source:'Session 12 elastic-support bridge'}
],
'13:Application to frames':[
{id:'frame-sidesway',title:'Frame sidesway and stability',level:'foundation',kind:'concept',q:'Why can frame sidesway reduce the elastic stability load?',choices:['Lateral translation creates additional second-order moments under axial load','It removes axial load','It makes member stiffness infinite','It prevents all bending'],answer:0,explanation:'Axial forces acting through lateral frame displacement create P-Δ moments that amplify sway.',math:'M_{2}\\sim P\\Delta',source:'Session 13 frame-stability bridge'},
{id:'frame-effective-length',title:'Frame restraint and effective length',level:'core',kind:'reasoning',q:'Compared with a well-braced frame, a sway-permitted frame generally gives a column:',choices:['Larger effective length and lower elastic buckling resistance','Zero effective length','Higher stiffness independent of joints','No need for stability analysis'],answer:0,explanation:'Reduced lateral restraint allows a longer effective buckling mode and therefore lowers Euler-type critical load.',source:'Session 13 frame-stability bridge'}
],
'15:Equations for lateral torsional buckling':[
{id:'ltb-phenomenon',title:'What lateral-torsional buckling combines',level:'foundation',kind:'concept',q:'Lateral-torsional buckling of a beam primarily combines:',choices:['Lateral displacement of the compression region and twist of the cross-section','Pure axial shortening only','Only local web yielding','Only vertical shear deformation'],answer:0,explanation:'An unrestrained beam can buckle by moving laterally while simultaneously twisting.',source:'Session 15 LTB bridge'},
{id:'ltb-restraint',title:'Effect of lateral restraint',level:'application',kind:'reasoning',q:'Adding effective intermediate lateral restraint to the compression flange generally causes the elastic LTB resistance to:',choices:['Increase','Decrease','Become zero','Remain completely unchanged'],answer:0,explanation:'Restraint reduces the unbraced length and suppresses lateral movement/twist, raising the critical moment.',source:'Session 15 LTB bridge'}
],
'16:Introduction to Buckling of plates':[
{id:'plate-buckling',title:'Plate buckling concept',level:'foundation',kind:'concept',q:'A thin plate in compression may lose stability before the material reaches yield because of:',choices:['Elastic local plate buckling','Pure tensile rupture','Hydrostatic yielding only','Zero bending stiffness'],answer:0,explanation:'Slender plate elements can buckle elastically under compressive membrane stress before yielding.',source:'Session 16 plate-buckling bridge'},
{id:'plate-critical-trend',title:'Plate slenderness trend',level:'core',kind:'reasoning',q:'For otherwise identical simply supported plates in compression, increasing the width-to-thickness ratio b/t generally makes the elastic critical buckling stress:',choices:['Lower','Higher','Unchanged','Always equal to yield stress'],answer:0,explanation:'Elastic plate buckling stress varies approximately with (t/b)^2 for fixed material and boundary coefficient.',math:'\\sigma_{cr}=k\\frac{\\pi^2E}{12(1-\\nu^2)}\\left(\\frac{t}{b}\\right)^2',source:'Session 16 plate-buckling bridge'}
]
});