Object.assign(window.REVISION_BANK,{
'8:Constitutive Relationship':[
{id:'asms5-ortho-constitutive',title:'Orthotropic constitutive idea',level:'core',kind:'concept',q:'What distinguishes an orthotropic elastic material from an isotropic one?',choices:['Its elastic properties depend on three mutually orthogonal material directions','It has no elastic constants','It behaves identically in every direction','It cannot sustain shear'],answer:0,explanation:'Orthotropic materials have direction-dependent stiffness aligned with three orthogonal material axes.',source:'ST ZG552 Session 8 topic + standard elasticity bridge (model supplement)'},
{id:'asms5-ortho-compliance',title:'Compliance form',level:'advanced',kind:'formula',q:'In linear elasticity, the compliance form of a constitutive law is written as:',choices:['{ε}=[S]{σ}','{σ}=[S]{ε}','{ε}=[K]{u}','{σ}=ρ{u}'],answer:0,explanation:'The compliance matrix maps stress components to strain components.',math:'\\{\\varepsilon\\}=[S]\\{\\sigma\\}',source:'ST ZG552 Session 8 topic + standard elasticity bridge (model supplement)'}
],
'8:Rotation and Reduction of the constants':[
{id:'asms5-ortho-rotation',title:'Rotate material axes',level:'core',kind:'reasoning',q:'Why must orthotropic stiffness constants be transformed when the material axes are rotated relative to the global axes?',choices:['Because the component representation changes with coordinate orientation','Because Young’s modulus becomes zero','Because stress ceases to be a tensor','Because strain becomes scalar'],answer:0,explanation:'The material law is simplest in material axes; tensor transformation is required to express it in another coordinate system.',source:'ST ZG552 Session 8 topic + standard tensor-transformation bridge (model supplement)'},
{id:'asms5-plane-stress-reduction',title:'Plane-stress reduction',level:'advanced',kind:'concept',q:'A 3D constitutive matrix is reduced to plane stress primarily by imposing:',choices:['σ_z=τ_xz=τ_yz=0','ε_z=γ_xz=γ_yz=0','σ_x=σ_y=0','All shear strains equal zero'],answer:0,explanation:'Plane stress assumes out-of-plane stress components vanish, after which the constitutive equations are reduced accordingly.',source:'ST ZG552 Session 8 topic + standard elasticity bridge (model supplement)'}
],
'12:Equations for elastic support':[
{id:'asms5-spring-support',title:'Translational elastic support',level:'foundation',kind:'formula',q:'For a linear translational spring support of stiffness k_s and displacement v, the spring reaction magnitude is:',choices:['k_s v','v/k_s','EI v','k_s/v'],answer:0,explanation:'A linear spring obeys Hooke’s law: reaction is proportional to displacement.',math:'R_s=k_s v',source:'ST ZG552 Session 12 topic + standard beam-column bridge (model supplement)'},
{id:'asms5-rotational-spring',title:'Rotational spring support',level:'core',kind:'formula',q:'For a rotational spring of stiffness k_θ, the end moment associated with rotation θ is:',choices:['M=k_θθ','M=θ/k_θ','M=EI/θ','M=k_θ/θ'],answer:0,explanation:'A rotational spring develops moment proportional to angular rotation.',math:'M=k_\\theta\\,\\theta',source:'ST ZG552 Session 12 topic + standard structural-analysis bridge (model supplement)'},
{id:'asms5-spring-limit',title:'Very stiff support limit',level:'application',kind:'reasoning',q:'As a translational spring stiffness k_s tends to infinity, the supported displacement tends toward:',choices:['Zero','Infinity','The span length','The applied force'],answer:0,explanation:'An infinitely stiff spring approaches an ideal displacement restraint.',math:'k_s\\to\\infty\\Rightarrow v\\to0',source:'ST ZG552 Session 12 topic + standard structural-analysis bridge (model supplement)'}
],
'12:Buckling based on beam column equations':[
{id:'asms5-beamcolumn-pdelta',title:'Beam-column differential equation',level:'core',kind:'formula',q:'For a prismatic beam-column under constant compressive force P and transverse loading q(x), which term represents the geometric-stiffness effect?',choices:['P v″','EI v'''' only','q(x) only','AE v'],answer:0,explanation:'Axial compression couples with curvature through the P v″ term, giving the classic beam-column equation.',math:'EI\\,v^{(4)}+P\\,v^{(2)}=q(x)',source:'ST ZG552 Session 12 topic + standard beam-column stability bridge (model supplement)'},
{id:'asms5-homogeneous-buckling',title:'Buckling as homogeneous solution',level:'advanced',kind:'reasoning',q:'Why can critical buckling loads be found from the homogeneous beam-column equation?',choices:['At buckling a non-zero deformation can exist without incremental transverse loading','Because EI becomes zero','Because P must vanish','Because displacement is prescribed everywhere'],answer:0,explanation:'Buckling corresponds to a non-trivial equilibrium shape of the homogeneous stability equation.',source:'ST ZG552 Session 12 topic + standard stability bridge (model supplement)'},
{id:'asms5-beta',title:'Beam-column stability parameter',level:'core',kind:'formula',q:'A common beam-column stability parameter is β²=P/EI. Increasing compression P therefore makes β:',choices:['Increase','Decrease','Remain zero','Become imaginary for all P'],answer:0,explanation:'For positive compressive P and constant EI, β grows as the square root of P.',math:'\\beta=\\sqrt{\\frac{P}{EI}}',source:'ST ZG552 Session 12 topic + standard stability bridge (model supplement)'}
],
'13:Buckling with elastic supports':[
{id:'asms5-elastic-restraint-critical',title:'Elastic restraint and critical load',level:'application',kind:'reasoning',q:'All else equal, strengthening a stabilizing elastic lateral support generally causes the critical buckling load to:',choices:['Increase','Decrease','Become zero','Remain exactly unchanged'],answer:0,explanation:'Additional lateral restraint suppresses deformation and raises the load required to trigger instability.',source:'ST ZG552 Session 13 topic + standard stability bridge (model supplement)'},
{id:'asms5-spring-energy',title:'Spring contribution to potential energy',level:'advanced',kind:'formula',q:'What is the elastic potential energy stored in a linear spring of stiffness k_s and displacement v?',choices:['(1/2)k_s v²','k_s/v','(1/2)EI v²','k_s v³'],answer:0,explanation:'A linear spring stores one-half stiffness times displacement squared.',math:'U_s=\\frac12 k_s v^2',source:'ST ZG552 Session 13 topic + standard energy-method bridge (model supplement)'},
{id:'asms5-mode-support-node',title:'Support at a buckling-mode node',level:'advanced',kind:'reasoning',q:'If an elastic lateral support is placed exactly at a node of a particular buckling mode, its influence on that mode is likely to be:',choices:['Small because displacement there is near zero','Maximum because curvature is always infinite','Independent of stiffness','Equivalent to removing EI'],answer:0,explanation:'A support can only develop significant force when the mode produces displacement at its location.',source:'ST ZG552 Session 13 topic + standard modal-stability bridge (model supplement)'}
],
'13:Application to frames':[
{id:'asms5-frame-sway',title:'Sway-frame instability',level:'foundation',kind:'concept',q:'A sway buckling mode of a frame primarily involves:',choices:['Lateral translation of storeys','Only local flange yielding','Pure axial shortening with no lateral movement','Only torsion of individual bolts'],answer:0,explanation:'Sway instability is a global lateral-translation mode of the frame.',source:'ST ZG552 Session 13 topic + standard frame-stability bridge (model supplement)'},
{id:'asms5-pdelta-frame',title:'Frame P–Δ effect',level:'core',kind:'formula',q:'A vertical load P acting through a lateral storey displacement Δ creates an additional overturning moment approximately equal to:',choices:['PΔ','P/Δ','EIΔ','PΔ²/L'],answer:0,explanation:'The displaced axial load generates a second-order moment P times the global lateral displacement.',math:'M_{2}\\approx P\\Delta',source:'ST ZG552 Session 13 topic + standard second-order-analysis bridge (model supplement)'},
{id:'asms5-effective-stiffness',title:'Frame stiffness near buckling',level:'advanced',kind:'reasoning',q:'As a frame approaches its elastic critical load, its effective lateral stiffness tends to:',choices:['Reduce toward zero','Increase without bound','Remain identical to first-order stiffness','Become unrelated to axial load'],answer:0,explanation:'Geometric stiffness from compression progressively offsets elastic stiffness as the critical state is approached.',source:'ST ZG552 Session 13 topic + standard frame-stability bridge (model supplement)'}
],
'15:Equations for lateral torsional buckling':[
{id:'asms5-ltb-components',title:'Coupled LTB response',level:'core',kind:'concept',q:'Elastic lateral-torsional buckling couples which two principal deformation modes?',choices:['Lateral bending and twist','Axial extension and temperature','Vertical shear and density','Local yielding and corrosion'],answer:0,explanation:'LTB is a coupled instability involving lateral deflection of the compression region and torsional rotation of the section.',source:'ST ZG552 Session 15 topic + standard LTB bridge (model supplement)'},
{id:'asms5-ltb-stiffnesses',title:'Stiffnesses resisting LTB',level:'advanced',kind:'concept',q:'Which section properties are especially important in elastic LTB resistance?',choices:['Minor-axis bending stiffness EI_y and torsional/warping stiffness','Area only','Density only','Thermal expansion only'],answer:0,explanation:'LTB resistance depends strongly on weak-axis flexural stiffness together with St Venant and warping torsional stiffness.',source:'ST ZG552 Session 15 topic + standard LTB bridge (model supplement)'},
{id:'asms5-cb',title:'Moment-gradient effect',level:'application',kind:'reasoning',q:'Why can a non-uniform bending-moment diagram alter the LTB critical moment relative to uniform moment?',choices:['Different moment gradients change how much of the span is highly stressed in compression','Because E becomes load-dependent','Because the beam length changes','Because torsion disappears'],answer:0,explanation:'Moment-gradient factors account for the stabilizing or destabilizing influence of the actual bending distribution.',source:'ST ZG552 Session 15 topic + standard LTB bridge (model supplement)'}
],
'16:Introduction to Buckling of plates':[
{id:'asms5-postbuckling',title:'Plate post-buckling reserve',level:'advanced',kind:'concept',q:'Why can a thin plate sometimes continue carrying additional load after first elastic buckling?',choices:['Membrane stress redistribution can develop post-buckling strength','Buckling permanently removes all stress','Young’s modulus doubles after buckling','Boundary conditions vanish'],answer:0,explanation:'Unlike an ideal Euler column, plates can redistribute stresses and develop membrane action after local buckling.',source:'ST ZG552 Session 16 topic + standard plate-stability bridge (model supplement)'},
{id:'asms5-aspect',title:'Plate aspect-ratio effect',level:'core',kind:'reasoning',q:'The elastic buckling coefficient of a rectangular plate can depend on aspect ratio because:',choices:['The admissible buckling-wave pattern depends on plate geometry','Elastic modulus changes with length','Thickness becomes a force','Poisson ratio becomes zero'],answer:0,explanation:'Plate dimensions control the possible half-wave patterns and therefore the lowest-energy buckling mode.',source:'ST ZG552 Session 16 topic + standard plate-stability bridge (model supplement)'}
]
});