Object.assign(window.REVISION_BANK,{
'5:Strain':[
{id:'asms6-strain-small',title:'Small-strain definition',level:'foundation',kind:'formula',q:'For a 1D bar with axial displacement u(x), the small normal strain is:',choices:['du/dx','u/L²','EAu','d²u/dx²'],answer:0,explanation:'For small deformation, normal strain is the spatial gradient of axial displacement.',math:'\\varepsilon_x=\\frac{du}{dx}',source:'ST ZG552 Session 5 topic + standard elasticity bridge (model supplement)'},
{id:'asms6-shearstrain',title:'Engineering shear strain',level:'core',kind:'concept',q:'Engineering shear strain γ_xy measures primarily:',choices:['Change in the right angle between material lines initially along x and y','Change in volume only','Rigid-body rotation only','Normal extension along z only'],answer:0,explanation:'Engineering shear strain measures angular distortion between initially orthogonal material lines.',math:'\\gamma_{xy}=\\frac{\\partial u}{\\partial y}+\\frac{\\partial v}{\\partial x}',source:'ST ZG552 Session 5 topic + standard elasticity bridge (model supplement)'}
],
'5:Generalized Hookes Law':[
{id:'asms6-hooke3d',title:'3D linear elastic mapping',level:'core',kind:'formula',q:'In compact matrix form, generalized Hooke’s law for a linear elastic solid is:',choices:['{σ}=[D]{ε}','{ε}=[K]{ü}','{σ}=ρ{u}','{F}=[M]{ε}'],answer:0,explanation:'The constitutive matrix [D] maps the strain vector to the stress vector in linear elasticity.',math:'\\{\\sigma\\}=[D]\\{\\varepsilon\\}',source:'ST ZG552 Session 5 topic + standard constitutive-law bridge (model supplement)'},
{id:'asms6-poisson',title:'Poisson coupling',level:'application',kind:'reasoning',q:'A uniaxially tensioned isotropic specimen generally contracts laterally because:',choices:['Poisson coupling links axial and transverse strain','Shear modulus becomes zero','The stress tensor must be spherical','Young’s modulus changes sign'],answer:0,explanation:'For isotropic elasticity, lateral strain is proportional to axial strain through Poisson’s ratio.',math:'\\varepsilon_y=-\\nu\\varepsilon_x',source:'ST ZG552 Session 5 topic + standard elasticity bridge (model supplement)'}
],
'6:Equilibrium equations':[
{id:'asms6-eq-local',title:'Local force equilibrium',level:'core',kind:'formula',q:'Neglecting inertia, the local equilibrium equation of a continuum with body force b_i is:',choices:['σ_{ij,j}+b_i=0','ε_{ij,j}=0','σ_{ij}=0','u_{i,j}=b_i'],answer:0,explanation:'The divergence of stress plus body force must vanish in static equilibrium.',math:'\\sigma_{ij,j}+b_i=0',source:'ST ZG552 Session 6 topic + standard continuum-mechanics bridge (model supplement)'},
{id:'asms6-eq-sym',title:'Moment equilibrium and stress symmetry',level:'advanced',kind:'reasoning',q:'For a classical continuum without body couples, local moment equilibrium implies:',choices:['σ_ij=σ_ji','σ_ij=0 for i≠j','All normal stresses are equal','All strains vanish'],answer:0,explanation:'Balance of angular momentum makes the Cauchy stress tensor symmetric in a classical continuum.',math:'\\sigma_{ij}=\\sigma_{ji}',source:'ST ZG552 Session 6 topic + standard continuum-mechanics bridge (model supplement)'}
],
'6:Compatibility':[
{id:'asms6-compat-purpose',title:'Why compatibility matters',level:'foundation',kind:'concept',q:'What is the purpose of strain-compatibility equations?',choices:['Ensure the strain field can arise from a continuous single-valued displacement field','Ensure every stress component is equal','Remove the need for boundary conditions','Force the material to remain unstressed'],answer:0,explanation:'Not every arbitrary strain field corresponds to a physically continuous displacement field; compatibility enforces that requirement.',source:'ST ZG552 Session 6 topic + standard elasticity bridge (model supplement)'},
{id:'asms6-compat2d',title:'2D compatibility relation',level:'advanced',kind:'formula',q:'For small 2D strains, which relation is the standard compatibility equation?',choices:['∂²ε_x/∂y² + ∂²ε_y/∂x² = ∂²γ_xy/∂x∂y','ε_x+ε_y=0','γ_xy=ε_xε_y','∂ε_x/∂x=0 always'],answer:0,explanation:'This relation ensures the three planar strain components derive from compatible in-plane displacements.',math:'\\frac{\\partial^2\\varepsilon_x}{\\partial y^2}+\\frac{\\partial^2\\varepsilon_y}{\\partial x^2}=\\frac{\\partial^2\\gamma_{xy}}{\\partial x\\partial y}',source:'ST ZG552 Session 6 topic + standard elasticity bridge (model supplement)'}
],
'7:Airys stress Function':[
{id:'asms6-airy-components',title:'Stress from Airy function',level:'core',kind:'formula',q:'For an Airy stress function Φ(x,y), which expression gives σ_x?',choices:['∂²Φ/∂y²','∂Φ/∂x','∂²Φ/∂x² only for σ_x','−∂Φ/∂y'],answer:0,explanation:'The Airy formulation defines planar stresses using second derivatives of one scalar function.',math:'\\sigma_x=\\frac{\\partial^2\\Phi}{\\partial y^2},\\quad \\sigma_y=\\frac{\\partial^2\\Phi}{\\partial x^2},\\quad \\tau_{xy}=-\\frac{\\partial^2\\Phi}{\\partial x\\partial y}',source:'ST ZG552 Session 7 topic + standard elasticity bridge (model supplement)'},
{id:'asms6-airy-biharmonic',title:'Biharmonic requirement',level:'advanced',kind:'formula',q:'For homogeneous isotropic plane elasticity without body forces, the Airy stress function must satisfy:',choices:['∇⁴Φ=0','∇Φ=0','∇²Φ=1','Φ=0 everywhere'],answer:0,explanation:'Compatibility combined with the constitutive relation leads to the biharmonic equation for Φ.',math:'\\nabla^4\\Phi=0',source:'ST ZG552 Session 7 topic + standard elasticity bridge (model supplement)'}
],
'9:Yield Criteria':[
{id:'asms6-vonmises',title:'Von Mises equivalent stress',level:'core',kind:'concept',q:'The von Mises yield criterion is governed by which stress content?',choices:['Deviatoric/distortional stress','Pure hydrostatic pressure only','Mean stress only','Rigid-body rotation'],answer:0,explanation:'Von Mises yielding depends on distortional energy and therefore on the deviatoric stress tensor, not hydrostatic stress alone.',source:'ST ZG552 Session 9 topic + standard plasticity bridge (model supplement)'},
{id:'asms6-tresca',title:'Tresca physical criterion',level:'core',kind:'formula',q:'Tresca yielding begins when the maximum shear stress reaches the material shear-yield threshold. In terms of principal stresses, maximum shear stress is:',choices:['(σ_max−σ_min)/2','(σ_max+σ_min)/2','σ_maxσ_min','σ_max/σ_min'],answer:0,explanation:'The maximum shear stress at a point is half the largest separation between principal stresses.',math:'\\tau_{max}=\\frac{\\sigma_{max}-\\sigma_{min}}{2}',source:'ST ZG552 Session 9 topic + standard plasticity bridge (model supplement)'}
],
'10:Warping':[
{id:'asms6-warp-open',title:'Warping of open sections',level:'foundation',kind:'concept',q:'Why is warping especially important for thin-walled open sections under torsion?',choices:['Their cross-sections can undergo significant longitudinal out-of-plane displacement','They cannot carry any torque','Their shear modulus is zero','They always remain perfectly plane'],answer:0,explanation:'Open sections often develop substantial warping displacement, and restraint of that warping can create additional normal stresses.',source:'ST ZG552 Session 10 topic + standard torsion bridge (model supplement)'},
{id:'asms6-warp-restraint',title:'Restrained warping effect',level:'application',kind:'reasoning',q:'Restraining the free warping of an open section under torsion generally introduces:',choices:['Additional longitudinal normal stresses','Only hydrostatic stress','Zero internal force','A reduction of Young’s modulus'],answer:0,explanation:'Warping restraint develops bimoment-related longitudinal stresses in addition to St Venant torsional shear.',source:'ST ZG552 Session 10 topic + standard torsion bridge (model supplement)'}
],
'11:Euler’s Buckling':[
{id:'asms6-euler-pcr',title:'Euler critical load',level:'core',kind:'formula',q:'The Euler critical load for a prismatic ideal column with effective length L_e is:',choices:['π²EI/L_e²','EI/L_e','πEI/L_e²','AE/L_e'],answer:0,explanation:'Euler buckling load scales with flexural rigidity and inversely with the square of effective length.',math:'P_{cr}=\\frac{\\pi^2EI}{L_e^2}',source:'ST ZG552 Session 11 topic + standard stability bridge (model supplement)'},
{id:'asms6-euler-slender',title:'Slenderness consequence',level:'application',kind:'reasoning',q:'If an Euler column’s effective length doubles while E and I remain unchanged, its elastic critical load becomes:',choices:['One quarter','One half','Twice','Four times'],answer:0,explanation:'Because P_cr is proportional to 1/L_e², doubling effective length reduces the critical load by a factor of four.',math:'P_{cr}\\propto L_e^{-2}',source:'ST ZG552 Session 11 topic + standard stability bridge (model supplement)'}
],
'14:Calculation of Shear flow':[
{id:'asms6-shearflow',title:'Thin-wall shear flow',level:'core',kind:'formula',q:'For a thin-walled open section under transverse shear V, the basic shear-flow relation is:',choices:['q=VQ/I','q=VI/Q','q=V/(IQ)','q=EI/V'],answer:0,explanation:'Shear flow q equals VQ/I; the corresponding average shear stress is q/t.',math:'q=\\frac{VQ}{I},\\qquad \\tau=\\frac{q}{t}',source:'ST ZG552 Session 14 topic + standard thin-walled-section bridge (model supplement)'},
{id:'asms6-q-unit',title:'Shear-flow units',level:'foundation',kind:'concept',q:'What are the physical units of shear flow q?',choices:['Force per unit length','Force per unit area','Moment per unit length','Dimensionless'],answer:0,explanation:'Since q=τt, shear stress times thickness gives force per unit length.',source:'ST ZG552 Session 14 topic + standard thin-walled-section bridge (model supplement)'}
],
'16:Continuation of torsional Buckling':[
{id:'asms6-torsbuck-mode',title:'Torsional buckling mode',level:'core',kind:'concept',q:'A pure torsional buckling mode is characterized primarily by:',choices:['Rotation of the cross-section about the member axis','Only axial shortening','Only strong-axis bending','Uniform yielding with no deformation'],answer:0,explanation:'Torsional buckling is an instability dominated by twist; in unsymmetric sections it may couple with flexure.',source:'ST ZG552 Session 16 topic + standard stability bridge (model supplement)'},
{id:'asms6-flex-tors',title:'Flexural-torsional coupling',level:'advanced',kind:'reasoning',q:'Why are singly symmetric or unsymmetric compression members susceptible to flexural-torsional buckling?',choices:['Bending and twisting modes can couple because the section geometry does not fully decouple them','Their Young’s modulus is anisotropic by definition','They have no shear centre','Axial load cannot cause bending'],answer:0,explanation:'Section asymmetry can couple lateral translation and twist, producing a combined flexural-torsional instability mode.',source:'ST ZG552 Session 16 topic + standard stability bridge (model supplement)'}
]
});