Object.assign(window.REVISION_BANK,{
'1:Fourier-series idea for periodic loading':[
{id:'dos5-fourier-meaning',title:'Why Fourier series matters',level:'foundation',kind:'concept',q:'Why is Fourier decomposition useful in structural dynamics?',choices:['A periodic load can be represented as a sum of harmonic components','It removes inertia from the structure','It converts every load into a static force','It makes damping zero'],answer:0,explanation:'Linear dynamic response to a periodic load can be studied by superposing the responses to its harmonic components.',source:'Dynamics Lecture 1 topic + standard vibration bridge (model supplement)'},
{id:'dos5-fourier-form',title:'Generic Fourier form',level:'core',kind:'formula',q:'Which expression represents a general Fourier series for a periodic force?',choices:['F(t)=a_0+Σ[a_n cos(nωt)+b_n sin(nωt)]','F(t)=kt only','F(t)=m/t²','F(t)=constant only'],answer:0,explanation:'A periodic function can be expanded into a constant term plus sine and cosine harmonics.',math:'F(t)=a_0+\\sum_{n=1}^{\\infty}[a_n\\cos(n\\omega t)+b_n\\sin(n\\omega t)]',source:'Dynamics Lecture 1 topic + standard Fourier bridge (model supplement)'}
],
'1:Random and impulsive loads':[
{id:'dos5-impulse',title:'Impulse meaning',level:'core',kind:'formula',q:'The impulse delivered by a force F(t) over a short interval is:',choices:['∫F(t)dt','dF/dt','F/t','∫F(t)²dt'],answer:0,explanation:'Impulse is the time integral of force and equals the change in momentum.',math:'J=\\int_{t_1}^{t_2}F(t)\\,dt=\\Delta(mv)',source:'Dynamics Lecture 1 topic + standard dynamics bridge (model supplement)'},
{id:'dos5-random-load',title:'Random loading',level:'foundation',kind:'concept',q:'What makes a random dynamic load different from a deterministic one?',choices:['Its exact future time history cannot be predicted uniquely','It has zero magnitude','It never varies with time','It always acts periodically'],answer:0,explanation:'Random loads are described statistically rather than by a single fully known time history.',source:'Dynamics Lecture 1 topic + standard dynamics bridge (model supplement)'}
],
'2:Generalized coordinates':[
{id:'dos5-gen-coordinate',title:'Generalized coordinate role',level:'foundation',kind:'concept',q:'A generalized coordinate is used to:',choices:['Describe the configuration of a system using independent variables','Measure only mass density','Replace all forces by moments','Eliminate boundary conditions'],answer:0,explanation:'Generalized coordinates are independent variables sufficient to describe system configuration.',source:'Dynamics Lecture 2 topic + standard analytical-mechanics bridge (model supplement)'},
{id:'dos5-one-dof-q',title:'One generalized coordinate',level:'core',kind:'reasoning',q:'If a structure is idealized as one SDOF oscillator, how many independent generalized coordinates are required?',choices:['One','Two','Three','An infinite number'],answer:0,explanation:'An SDOF model is fully described by one independent displacement coordinate.',source:'Dynamics Lecture 2 topic + standard SDOF bridge (model supplement)'}
],
'2:Methods for formulating equations of motion':[
{id:'dos5-newton',title:'Newton formulation',level:'foundation',kind:'concept',q:'Using Newton’s second law, the translational equation of motion is based on:',choices:['ΣF=mü','ΣF=ku only','ΣM=0 for every dynamic problem','Energy being identically zero'],answer:0,explanation:'The net applied force equals mass times acceleration.',math:'\\sum F=m\\ddot{u}',source:'Dynamics Lecture 2 topic + standard mechanics bridge (model supplement)'},
{id:'dos5-energy-method',title:'Energy formulation',level:'core',kind:'concept',q:'Which alternative formulation is especially useful when constraint forces are inconvenient to handle directly?',choices:['Lagrange’s equation','Archimedes principle','Bernoulli fluid equation','Hooke law alone'],answer:0,explanation:'Lagrange’s equation uses kinetic and potential energy and generalized forces, often avoiding explicit constraint reactions.',math:'\\frac{d}{dt}\\left(\\frac{\\partial T}{\\partial \\dot q}\\right)-\\frac{\\partial T}{\\partial q}+\\frac{\\partial V}{\\partial q}=Q',source:'Dynamics Lecture 2 topic + standard analytical-mechanics bridge (model supplement)'}
],
'2:Angular frequency, natural frequency and time period':[
{id:'dos5-freq-rel',title:'ω, f and T relation',level:'core',kind:'formula',q:'Which set of relations is correct?',choices:['ω=2πf and T=1/f','ω=f/2π and T=f','ω=T and f=2πT','T=ωf'],answer:0,explanation:'Angular frequency is 2π times cyclic frequency, while period is the reciprocal of frequency.',math:'\\omega=2\\pi f,\\qquad T=\\frac1f=\\frac{2\\pi}{\\omega}',source:'Dynamics Lecture 2 topic + standard vibration bridge (model supplement)'},
{id:'dos5-period-num',title:'Convert angular frequency to period',level:'application',kind:'numerical',q:'If ω_n=10 rad/s, the natural period is closest to:',choices:['0.628 s','10 s','6.28 s','0.10 s'],answer:0,explanation:'T_n=2π/ω_n=2π/10≈0.628 s.',math:'T_n=\\frac{2\\pi}{10}\\approx0.628\\,s',source:'Dynamics Lecture 2 topic + standard numerical practice (model supplement)'}
],
'4:Initial conditions u₀ and u̇₀':[
{id:'dos5-ic-constants',title:'Initial conditions determine constants',level:'core',kind:'reasoning',q:'For u(t)=A cosω_nt+B sinω_nt, which initial conditions determine A and B?',choices:['u(0) and u̇(0)','Mass and stiffness only','Force and damping only','Time period and density only'],answer:0,explanation:'Displacement and velocity at t=0 determine the two integration constants.',math:'A=u_0,\\qquad B=\\frac{\\dot u_0}{\\omega_n}',source:'Dynamics Lecture 4 topic + standard free-vibration bridge (model supplement)'},
{id:'dos5-zero-vel',title:'Released from rest',level:'application',kind:'reasoning',q:'If an undamped SDOF system is released from displacement u₀ with zero initial velocity, its response is:',choices:['u(t)=u₀ cosω_nt','u(t)=u₀ sinω_nt','u(t)=u₀e^{-ω_nt}','u(t)=0'],answer:0,explanation:'With u̇₀=0, the sine coefficient is zero.',math:'u(t)=u_0\\cos(\\omega_n t)',source:'Dynamics Lecture 4 topic + standard free-vibration practice (model supplement)'}
],
'4:Amplitude from initial conditions':[
{id:'dos5-amplitude',title:'Amplitude from u₀ and v₀',level:'core',kind:'formula',q:'For undamped free vibration, the response amplitude U is:',choices:['√(u₀²+(u̇₀/ω_n)²)','u₀+u̇₀','ω_nu₀ only','u̇₀²/u₀'],answer:0,explanation:'The cosine and sine coefficients combine vectorially to give the amplitude.',math:'U=\\sqrt{u_0^2+\\left(\\frac{\\dot u_0}{\\omega_n}\\right)^2}',source:'Dynamics Lecture 4 topic + standard free-vibration bridge (model supplement)'},
{id:'dos5-phase',title:'Phase angle relation',level:'advanced',kind:'formula',q:'If u(t)=U cos(ω_nt−φ), then tanφ is:',choices:['u̇₀/(ω_nu₀)','ω_nu₀/u̇₀ always','u₀u̇₀','ω_n²u₀'],answer:0,explanation:'Matching the initial displacement and velocity gives tanφ=(u̇₀/ω_n)/u₀.',math:'\\tan\\phi=\\frac{\\dot u_0}{\\omega_n u_0}',source:'Dynamics Lecture 4 topic + standard free-vibration bridge (model supplement)'}
],
'4:Energy in undamped free vibration':[
{id:'dos5-energy-total',title:'Conserved mechanical energy',level:'core',kind:'formula',q:'For an undamped spring-mass oscillator, the total mechanical energy is:',choices:['(1/2)mü? No: (1/2)m u̇²+(1/2)ku²','ku only','m u̇ only','c u̇² only'],answer:0,explanation:'The total energy is the sum of kinetic and elastic strain energy and remains constant in undamped free vibration.',math:'E=\\frac12m\\dot u^2+\\frac12ku^2=\\text{constant}',source:'Dynamics Lecture 4 topic + standard energy bridge (model supplement)'},
{id:'dos5-energy-turning',title:'Energy at maximum displacement',level:'application',kind:'reasoning',q:'At a turning point where displacement is maximum in undamped free vibration, the velocity is:',choices:['Zero','Maximum','Equal to ω_n always','Undefined'],answer:0,explanation:'At maximum displacement the mass instantaneously changes direction, so kinetic energy is zero and all mechanical energy is spring potential energy.',source:'Dynamics Lecture 4 topic + standard energy bridge (model supplement)'}
],
'4:Energy dissipation in damped vibration':[
{id:'dos5-diss-rate',title:'Viscous dissipation rate',level:'core',kind:'formula',q:'For viscous damping force c u̇, the instantaneous rate of energy dissipation is:',choices:['c u̇²','cu','ku²','mü²'],answer:0,explanation:'Damping power equals damping force times velocity.',math:'P_D=c\\dot u^2',source:'Dynamics Lecture 4 topic + standard damping bridge (model supplement)'},
{id:'dos5-decay-energy',title:'Energy decay',level:'advanced',kind:'reasoning',q:'In an underdamped linear oscillator, why does total mechanical energy decrease with time?',choices:['The damper continuously converts mechanical energy into heat','The spring stiffness becomes zero','Mass disappears','Natural frequency must become imaginary'],answer:0,explanation:'Positive viscous damping removes mechanical energy at a rate c u̇².',source:'Dynamics Lecture 4 topic + standard damping bridge (model supplement)'}
],
'4:Logarithmic decrement over n cycles':[
{id:'dos5-logdec-n',title:'n-cycle logarithmic decrement',level:'core',kind:'formula',q:'If x_0 and x_n are peak amplitudes n cycles apart, the logarithmic decrement per cycle is:',choices:['δ=(1/n)ln(x₀/x_n)','δ=n ln(x_n/x₀)','δ=x₀−x_n','δ=x_n/x₀'],answer:0,explanation:'Dividing the log amplitude ratio by n gives the decrement per cycle.',math:'\\delta=\\frac1n\\ln\\left(\\frac{x_0}{x_n}\\right)',source:'Dynamics Lecture 4 topic + standard damping bridge (model supplement)'},
{id:'dos5-logdec-zeta',title:'δ and damping ratio',level:'advanced',kind:'formula',q:'For an underdamped SDOF system, logarithmic decrement is related to damping ratio by:',choices:['δ=2πζ/√(1−ζ²)','δ=ζ/2π','δ=2π/ζ','δ=1−ζ²'],answer:0,explanation:'The exact relation follows from the exponential envelope over one damped period.',math:'\\delta=\\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}}',source:'Dynamics Lecture 4 topic + standard damping bridge (model supplement)'}
]
});