Object.assign(window.REVISION_BANK,{
'1:Time-varying structural response':[
{id:'response-time',title:'Response as a function of time',level:'foundation',kind:'concept',q:'In structural dynamics, displacement is generally written as u(t) because:',choices:['The response changes with time','Displacement has no units','Time replaces stiffness','Mass is ignored'],answer:0,explanation:'Dynamic response variables such as displacement, velocity and acceleration are functions of time.',math:'u=u(t),\\quad \\dot u=\\frac{du}{dt},\\quad \\ddot u=\\frac{d^2u}{dt^2}',source:'Lecture 1'},
{id:'response-derivatives',title:'Displacement to acceleration',level:'core',kind:'formula',q:'If u(t)=U sin(ωt), what is the acceleration?',choices:['−Uω² sin(ωt)','Uω cos(ωt)','Uω² cos(ωt)','−U sin(ωt)/ω²'],answer:0,explanation:'Differentiate displacement twice with respect to time.',math:'\\ddot u(t)=-U\\omega^2\\sin(\\omega t)',source:'Lecture 1'}
],
'1:Periodic and non-periodic dynamic loads':[
{id:'periodic-definition',title:'Periodic load definition',level:'foundation',kind:'concept',q:'A load p(t) is periodic with period T when:',choices:['p(t+T)=p(t)','p(t)=0 for all t','Its amplitude always increases','It acts only once'],answer:0,explanation:'A periodic load repeats the same time history after each period T.',math:'p(t+T)=p(t)',source:'Lecture 1'},
{id:'impulse-nonperiodic',title:'Classify an impulse',level:'application',kind:'classification',q:'A short-duration impact load that occurs once is best classified as:',choices:['Non-periodic impulsive loading','Steady harmonic loading','Static loading','Periodic loading with zero frequency'],answer:0,explanation:'A one-off impact does not repeat at a fixed period and is therefore non-periodic.',source:'Lecture 1'}
],
'1:Fourier-series idea for periodic loading':[
{id:'fourier-purpose',title:'Fourier decomposition purpose',level:'foundation',kind:'concept',q:'Why is Fourier-series representation useful for periodic dynamic loading?',choices:['It expresses a periodic load as a sum of harmonic components','It eliminates time from the problem','It removes stiffness','It applies only to static loads'],answer:0,explanation:'Linear dynamic response to a periodic load can be built from the responses to its harmonic components.',source:'Lecture 1'},
{id:'fourier-form',title:'Recognise a Fourier series',level:'core',kind:'formula',q:'Which expression has the standard form of a Fourier series?',choices:['a₀/2 + Σ[a_n cos(nωt)+b_n sin(nωt)]','ku=P','m/u=t','EI/L³ only'],answer:0,explanation:'A Fourier series consists of a constant term plus sine and cosine harmonics at integer multiples of a fundamental frequency.',math:'p(t)=\\frac{a_0}{2}+\\sum_{n=1}^{\\infty}\\left[a_n\\cos(n\\omega t)+b_n\\sin(n\\omega t)\\right]',source:'Lecture 1'}
],
'2:Generalized coordinates':[
{id:'generalized-coordinate',title:'Generalized coordinate meaning',level:'foundation',kind:'concept',q:'A generalized coordinate is:',choices:['An independent variable used to describe the configuration of the system','Always a Cartesian x-coordinate only','A material property','A damping coefficient'],answer:0,explanation:'Generalized coordinates are chosen variables sufficient to describe the modeled degrees of freedom.',source:'Lecture 2'},
{id:'sdof-coordinate',title:'SDOF coordinate count',level:'core',kind:'reasoning',q:'How many independent generalized coordinates are required for an ideal single-degree-of-freedom system?',choices:['1','2','3','Infinitely many after discretization'],answer:0,explanation:'By definition, an SDOF model has one independent coordinate describing its motion.',source:'Lecture 2'}
],
'2:Mass, stiffness and damping':[
{id:'three-forces',title:'Three SDOF force components',level:'foundation',kind:'classification',q:'Which set contains the three standard mechanical force contributions in a viscously damped SDOF model?',choices:['Inertia, damping and elastic restoring force','Temperature, density and area','Stress, strain and Poisson ratio','Lift, drag and buoyancy only'],answer:0,explanation:'The equation of motion balances inertia m ü, damping c u̇ and stiffness ku against applied loading.',math:'m\\ddot u+c\\dot u+ku=p(t)',source:'Lecture 2'},
{id:'units-c',title:'Damping coefficient units',level:'core',kind:'unit',q:'What are the SI units of the viscous damping coefficient c in f_D=c u̇?',choices:['N·s/m','N/m','kg/m','N·m'],answer:0,explanation:'Force divided by velocity gives (N)/(m/s)=N·s/m.',math:'[c]=\\mathrm{N\\,s/m}',source:'Lecture 2'}
],
'2:Pendulum natural angular frequency ω = √(g/L)':[
{id:'pendulum-frequency',title:'Pendulum frequency formula',level:'core',kind:'formula',q:'For a small-angle simple pendulum of length L, the natural angular frequency is:',choices:['√(g/L)','√(L/g)','gL','2πg/L'],answer:0,explanation:'Linearising sin θ≈θ gives θ̈+(g/L)θ=0, so ω_n²=g/L.',math:'\\omega_n=\\sqrt{\\frac{g}{L}}',source:'Lecture 2'},
{id:'pendulum-length',title:'Effect of pendulum length',level:'application',kind:'reasoning',q:'If a small-angle pendulum length is increased by a factor of 4, its natural angular frequency becomes:',choices:['One half','Twice','One quarter','Four times'],answer:0,explanation:'Natural frequency varies inversely with the square root of length.',math:'\\omega_n\\propto L^{-1/2}',source:'Lecture 2'}
],
'4:Natural frequency from static deflection':[
{id:'static-deflection-frequency',title:'Frequency from static deflection',level:'core',kind:'formula',q:'For a vertical SDOF system whose static deflection under its own weight is δ_st, which relation gives natural angular frequency?',choices:['ω_n=√(g/δ_st)','ω_n=gδ_st','ω_n=δ_st/g','ω_n=2πδ_st'],answer:0,explanation:'Since k=mg/δ_st and ω_n=√(k/m), mass cancels.',math:'\\omega_n=\\sqrt{\\frac{g}{\\delta_{st}}}',source:'Lecture 4'},
{id:'deflection-frequency-trend',title:'Static deflection trend',level:'application',kind:'reasoning',q:'If static deflection under self-weight becomes four times larger, the natural angular frequency becomes:',choices:['One half','Twice','Four times','Unchanged'],answer:0,explanation:'Frequency varies as the inverse square root of static deflection.',source:'Lecture 4'}
],
'4:Damping ratio ζ = c/c_cr':[
{id:'zeta-definition',title:'Damping ratio definition',level:'core',kind:'formula',q:'Which expression defines viscous damping ratio ζ?',choices:['ζ=c/c_cr','ζ=c_cr/c²','ζ=k/m','ζ=ω_n/c'],answer:0,explanation:'The damping ratio compares actual damping with the critical damping coefficient.',math:'\\zeta=\\frac{c}{c_{cr}}=\\frac{c}{2m\\omega_n}',source:'Lecture 4'},
{id:'zeta-classify',title:'Classify ζ=0.20',level:'application',kind:'classification',q:'A system has ζ=0.20. Its free response is:',choices:['Underdamped','Critically damped','Overdamped','Undamped only if ζ>1'],answer:0,explanation:'0<ζ<1 corresponds to oscillatory underdamped decay.',source:'Lecture 4'}
],
'4:Underdamped response':[
{id:'under-form',title:'Underdamped response form',level:'core',kind:'formula',q:'Which qualitative form describes underdamped free vibration?',choices:['Exponentially decaying sinusoid','Linearly increasing displacement only','Constant displacement','Pure exponential with no oscillation for every case'],answer:0,explanation:'An underdamped system oscillates at ω_D while its amplitude decays with e^{-ζω_nt}.',math:'u(t)=e^{-\\zeta\\omega_n t}\\left[A\\cos(\\omega_D t)+B\\sin(\\omega_D t)\\right]',source:'Lecture 4'},
{id:'under-envelope',title:'Decay envelope',level:'visual',kind:'graph',q:'For 0<ζ<1, what happens to successive peak amplitudes in free vibration?',choices:['They decrease according to an exponential envelope','They remain exactly constant','They grow linearly','They instantly become zero'],answer:0,explanation:'Viscous damping removes energy, producing exponentially decaying peak amplitudes.',graph:{type:'function',xLabel:'t',yLabel:'u',functions:[{label:'upper envelope',expr:'exp(-zeta*wn*t)'},{label:'lower envelope',expr:'-exp(-zeta*wn*t)'}]},source:'Lecture 4'}
],
'4:Logarithmic decrement':[
{id:'logdec-definition',title:'Logarithmic decrement definition',level:'core',kind:'formula',q:'For two positive peak amplitudes x_0 and x_n separated by n cycles, logarithmic decrement per cycle is:',choices:['(1/n) ln(x_0/x_n)','n ln(x_n/x_0)','x_0−x_n','x_n/x_0 without logarithm'],answer:0,explanation:'Logarithmic decrement measures the natural logarithm of the amplitude ratio per cycle.',math:'\\delta=\\frac{1}{n}\\ln\\left(\\frac{x_0}{x_n}\\right)',source:'Lecture 4'},
{id:'logdec-zeta',title:'Log decrement and damping ratio',level:'application',kind:'formula',q:'For an underdamped viscous SDOF system, which relation connects logarithmic decrement and damping ratio?',choices:['δ=2πζ/√(1−ζ²)','δ=ζ/(2π)','δ=2π/ζ','δ=1−ζ²'],answer:0,explanation:'The decay over one damped period gives the standard exact relation.',math:'\\delta=\\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}}',source:'Lecture 4'}
]
});