Object.assign(window.REVISION_BANK,{
'1:Time-varying structural response':[
{id:'dos6-tv-kinematics',title:'Response variables vary with time',level:'foundation',kind:'concept',q:'In a dynamic structural problem, displacement u(t) varies with time. Which associated quantities appear naturally?',choices:['Velocity u̇ and acceleration ü','Only density and area','Only bending moment','Only temperature'],answer:0,explanation:'Time-varying displacement gives velocity and acceleration, and acceleration generates inertia force.',math:'\\dot u=\\frac{du}{dt},\\qquad \\ddot u=\\frac{d^2u}{dt^2}',source:'Dynamics Lecture 1 topic + standard structural-dynamics bridge (model supplement)'},
{id:'dos6-tv-peak',title:'Peak displacement is not peak velocity',level:'core',kind:'reasoning',q:'For simple harmonic motion u=A sin(ωt), what is the velocity when displacement reaches its positive peak u=A?',choices:['Zero','Aω','Aω²','Infinite'],answer:0,explanation:'At peak displacement the motion reverses direction, so instantaneous velocity is zero.',math:'u=A\\sin\\omega t,\\quad \\dot u=A\\omega\\cos\\omega t',source:'Dynamics Lecture 1 topic + standard vibration bridge (model supplement)'}
],
'1:Static and dynamic force classification':[
{id:'dos6-loadrate',title:'Why loading rate matters',level:'foundation',kind:'concept',q:'A load is treated dynamically when:',choices:['Its time variation produces significant inertia effects','It is always vertical','It is applied to steel only','Its magnitude is less than the structure weight'],answer:0,explanation:'Dynamic classification depends on whether inertia and often damping materially affect response, not simply on load direction or magnitude.',source:'Dynamics Lecture 1 topic + standard structural-dynamics bridge (model supplement)'},
{id:'dos6-quasistatic',title:'Quasi-static limit',level:'application',kind:'reasoning',q:'If a load changes very slowly compared with the structure’s natural period, the response tends toward:',choices:['Quasi-static behaviour','Resonance automatically','Impulsive behaviour','Zero stiffness'],answer:0,explanation:'Slow loading allows the structure to remain close to static equilibrium because inertia effects are small.',source:'Dynamics Lecture 1 topic + standard structural-dynamics bridge (model supplement)'}
],
'1:Periodic and non-periodic dynamic loads':[
{id:'dos6-periodic',title:'Definition of periodic load',level:'foundation',kind:'formula',q:'A periodic load satisfies which condition for some period T?',choices:['p(t+T)=p(t)','p(t)=0 always','ṗ(t)=0 always','p(t+T)=-p(t) always'],answer:0,explanation:'Periodic loading repeats exactly after a fixed time interval T.',math:'p(t+T)=p(t)',source:'Dynamics Lecture 1 topic + standard vibration bridge (model supplement)'},
{id:'dos6-nonperiodic',title:'Non-periodic example',level:'foundation',kind:'concept',q:'Which loading is typically non-periodic?',choices:['A single blast pulse','Steady rotating-machine imbalance','Ideal sinusoidal forcing','A repeating harmonic force'],answer:0,explanation:'A single transient pulse does not repeat at a fixed period and is therefore non-periodic.',source:'Dynamics Lecture 1 topic + standard vibration bridge (model supplement)'}
],
'1:Deterministic and non-deterministic analysis':[
{id:'dos6-deterministic',title:'Deterministic excitation',level:'foundation',kind:'concept',q:'What makes a dynamic load deterministic?',choices:['Its time history can be specified explicitly','Its future value is fundamentally random','It has zero amplitude','It must be sinusoidal'],answer:0,explanation:'A deterministic load has a prescribed or predictable time history, even if it is complicated.',source:'Dynamics Lecture 1 topic + standard dynamics bridge (model supplement)'},
{id:'dos6-randomstats',title:'Random excitation description',level:'core',kind:'concept',q:'Random dynamic loading is commonly characterized using:',choices:['Statistical quantities such as mean, variance or spectral density','Only one exact future time history','Only Young’s modulus','Only static reactions'],answer:0,explanation:'Stochastic loads are described statistically because their exact future realization is not known deterministically.',source:'Dynamics Lecture 1 topic + standard random-vibration bridge (model supplement)'}
],
'2:Lumped mass and degrees of freedom':[
{id:'dos6-lumped',title:'Lumped-mass idealization',level:'foundation',kind:'concept',q:'In a lumped-mass model, distributed structural mass is idealized as:',choices:['Discrete masses associated with selected coordinates','Zero mass everywhere','A continuous fluid only','A stiffness matrix with no inertia'],answer:0,explanation:'Lumping replaces continuous mass distribution by discrete masses to obtain a finite number of dynamic degrees of freedom.',source:'Dynamics Lecture 2 topic + standard structural-dynamics bridge (model supplement)'},
{id:'dos6-dofcount',title:'Meaning of one DOF',level:'foundation',kind:'concept',q:'A single-degree-of-freedom model requires how many independent coordinates to describe its motion?',choices:['One','Two','Three','Infinitely many'],answer:0,explanation:'By definition, one independent generalized coordinate completely describes an SDOF system configuration.',source:'Dynamics Lecture 2 topic + standard dynamics bridge (model supplement)'}
],
'2:Generalized coordinates':[
{id:'dos6-generalized',title:'Generalized coordinate role',level:'core',kind:'concept',q:'A generalized coordinate is best described as:',choices:['An independent parameter used to describe system configuration','A material strength only','A support reaction only','A damping coefficient only'],answer:0,explanation:'Generalized coordinates need not be Cartesian displacements; they can be rotations or other independent variables describing configuration.',source:'Dynamics Lecture 2 topic + standard analytical-mechanics bridge (model supplement)'},
{id:'dos6-pendulumcoord',title:'Pendulum generalized coordinate',level:'application',kind:'concept',q:'For an ideal simple pendulum of fixed length constrained to planar motion, a convenient generalized coordinate is:',choices:['Angular displacement θ','Bob mass m only','Gravity g only','String tension only'],answer:0,explanation:'The fixed-length constraint means one angle is sufficient to define the pendulum position.',math:'q_1=\\theta(t)',source:'Dynamics Lecture 2 pendulum topic + standard dynamics bridge (model supplement)'}
],
'2:Small-angle approximation sin θ ≈ θ':[
{id:'dos6-smallangle',title:'Linearizing the pendulum',level:'core',kind:'reasoning',q:'Why is sinθ≈θ used in the small-angle pendulum equation?',choices:['It converts the nonlinear equation into a linear harmonic-oscillator equation','It removes gravity','It makes mass infinite','It sets angular acceleration to zero'],answer:0,explanation:'Replacing sinθ by θ linearizes the restoring term and leads to simple harmonic motion.',math:'\\sin\\theta\\approx\\theta\\quad (|\\theta|\\ll1\\text{ rad})',source:'Dynamics Lecture 2 topic + standard vibration bridge (model supplement)'},
{id:'dos6-smallangle-unit',title:'Angle must be in radians',level:'foundation',kind:'concept',q:'The approximation sinθ≈θ is mathematically valid when θ is expressed in:',choices:['Radians','Degrees only','Metres','Hertz'],answer:0,explanation:'The Taylor expansion sinθ=θ−θ³/6+… assumes θ is in radians.',math:'\\sin\\theta=\\theta-\\frac{\\theta^3}{6}+\\cdots',source:'Dynamics Lecture 2 topic + standard calculus bridge (model supplement)'}
],
'2:Angular frequency, natural frequency and time period':[
{id:'dos6-freqconvert',title:'Convert ω to f',level:'core',kind:'formula',q:'If natural angular frequency is ω_n, the natural frequency in hertz is:',choices:['ω_n/(2π)','2πω_n','1/ω_n','ω_n²'],answer:0,explanation:'Angular frequency is radians per second and cyclic frequency is cycles per second, linked by 2π radians per cycle.',math:'f_n=\\frac{\\omega_n}{2\\pi}',source:'Dynamics Lecture 2 topic + standard vibration bridge (model supplement)'},
{id:'dos6-period',title:'Frequency-period relation',level:'foundation',kind:'formula',q:'The natural period T_n and natural frequency f_n satisfy:',choices:['T_n=1/f_n','T_n=f_n²','T_n=2πf_n','T_n=f_n'],answer:0,explanation:'Period is the time per cycle, so it is the reciprocal of cycles per second.',math:'T_n=\\frac{1}{f_n}=\\frac{2\\pi}{\\omega_n}',source:'Dynamics Lecture 2 topic + standard vibration bridge (model supplement)'}
],
'3:Mixed spring systems':[
{id:'dos6-mixedreduce',title:'Reduce mixed spring network',level:'application',kind:'reasoning',q:'For a mixed series-parallel spring system, the safest reduction strategy is to:',choices:['Identify simple series or parallel groups and reduce them step by step','Add every stiffness directly','Take the reciprocal of every stiffness directly','Ignore connectivity'],answer:0,explanation:'Equivalent stiffness depends on connectivity; reducing identifiable subgroups sequentially avoids applying the wrong rule.',source:'Dynamics Lecture 3 topic + standard mechanics bridge (model supplement)'},
{id:'dos6-series2',title:'Two springs in series',level:'core',kind:'formula',q:'Two springs k1 and k2 in series have equivalent stiffness:',choices:['k1k2/(k1+k2)','k1+k2','k1−k2','(k1+k2)/(k1k2)'],answer:0,explanation:'For series springs the same force passes through each and displacements add.',math:'k_{eq}=\\frac{k_1k_2}{k_1+k_2}',source:'Dynamics Lecture 3 topic + standard mechanics bridge (model supplement)'}
],
'4:Exponential decay of underdamped vibration':[
{id:'dos6-envelope',title:'Underdamped decay envelope',level:'core',kind:'formula',q:'The amplitude envelope of free underdamped viscous vibration decays approximately as:',choices:['e^{−ζω_n t}','e^{+ζω_n t}','sin(ζω_n t) only','A constant independent of damping'],answer:0,explanation:'Viscous damping multiplies the oscillatory response by an exponential decay factor.',math:'u(t)\\propto e^{-\\zeta\\omega_n t}',source:'Dynamics Lecture 4 topic + standard vibration bridge (model supplement)'},
{id:'dos6-envelope-rate',title:'Effect of damping ratio on decay',level:'application',kind:'reasoning',q:'For the same ω_n, increasing damping ratio ζ within the underdamped range causes the free-vibration envelope to:',choices:['Decay faster','Decay slower','Grow exponentially','Remain unchanged'],answer:0,explanation:'The decay exponent ζω_n becomes larger as ζ increases, so amplitude dies out more rapidly.',source:'Dynamics Lecture 4 topic + standard vibration bridge (model supplement)'}
],
'4:Logarithmic decrement':[
{id:'dos6-logdec',title:'Logarithmic decrement definition',level:'core',kind:'formula',q:'For successive positive peaks x_1 and x_2 of an underdamped free response, logarithmic decrement δ is:',choices:['ln(x_1/x_2)','x_1−x_2','x_2/x_1','ln(x_1x_2)'],answer:0,explanation:'Logarithmic decrement measures the natural log of the ratio of successive amplitudes.',math:'\\delta=\\ln\\left(\\frac{x_1}{x_2}\\right)',source:'Dynamics Lecture 4 topic + standard vibration bridge (model supplement)'},
{id:'dos6-logdec-zeta',title:'Log decrement and damping ratio',level:'advanced',kind:'formula',q:'For viscous underdamped SDOF motion, δ relates to damping ratio ζ by:',choices:['δ=2πζ/√(1−ζ²)','δ=ζ/(2π)','δ=2πω_n','δ=1/ζ'],answer:0,explanation:'The exact relation follows from the exponential decay over one damped period.',math:'\\delta=\\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}}',source:'Dynamics Lecture 4 topic + standard vibration bridge (model supplement)'}
]
});