window.REVISION_BANK={
'1:Static spring relation F = kx':[
{id:'hooke-meaning',title:'Meaning of stiffness',level:'foundation',kind:'concept',q:'In F = kx, what does the stiffness k measure?',choices:['Force required per unit displacement','Mass per unit volume','Energy lost per cycle','Natural period directly'],answer:0,explanation:'Stiffness is the restoring force generated for each unit of displacement.',math:'k=\\frac{F}{x}',source:'Lecture 1 structural dynamics foundations'},
{id:'spring-number',title:'Simple spring calculation',level:'application',kind:'numerical',q:'A linear spring has k = 2000 N/m and extends by 0.01 m. What force acts in the spring?',choices:['20 N','200 N','2 N','2000 N'],answer:0,explanation:'Multiply stiffness by displacement.',math:'F=kx=(2000)(0.01)=20\\,\\text{N}',source:'Lecture 1 structural dynamics foundations'}
],
'1:Undamped spring-mass equation m ẍ + kx = 0':[
{id:'terms',title:'Read the equation of motion',level:'foundation',kind:'concept',q:'In m ẍ + kx = 0, which term represents inertia?',choices:['m ẍ','kx','0','x only'],answer:0,explanation:'Mass multiplied by acceleration is the inertia term.',math:'m\\ddot{x}+kx=0',source:'Lecture 1'},
{id:'equilibrium',title:'Dynamic equilibrium',level:'core',kind:'reasoning',q:'Why can the two terms in m ẍ + kx = 0 balance even though the mass is moving?',choices:['The inertia term and restoring force are opposite in dynamic equilibrium','The spring force vanishes during motion','Mass becomes zero','Acceleration is always zero'],answer:0,explanation:'Free vibration continuously exchanges inertia and restoring-force effects.',source:'Lecture 1'}
],
'1:Sinusoidal harmonic loading F(t) = F₀ sin ωt':[
{id:'symbols',title:'Read harmonic loading symbols',level:'foundation',kind:'notation',q:'In F(t)=F₀ sin(ωt), what does F₀ represent?',choices:['Load amplitude','Angular frequency','Time period','Mass'],answer:0,explanation:'F₀ is the maximum magnitude of the sinusoidal load.',math:'F(t)=F_0\\sin(\\omega t)',source:'Lecture 1'},
{id:'period',title:'Period from angular frequency',level:'core',kind:'formula',q:'Which formula gives the period T of a harmonic function with angular frequency ω?',choices:['T = 2π/ω','T = ω/2π','T = 1/ω²','T = 2πω'],answer:0,explanation:'Angular frequency is 2π radians per cycle.',math:'T=\\frac{2\\pi}{\\omega}',source:'Lecture 1'},
{id:'zero-load',title:'Evaluate the sinusoid',level:'application',kind:'numerical',q:'For F(t)=10 sin(2πt) N, what is F at t = 0.5 s?',choices:['0 N','10 N','−10 N','5 N'],answer:0,explanation:'At t=0.5, the angle is π and sin π = 0.',math:'F(0.5)=10\\sin(\\pi)=0',source:'Lecture 1'}
],
'2:General SDOF equation m ü + c u̇ + ku = p(t)':[
{id:'four-terms',title:'Identify all SDOF terms',level:'foundation',kind:'classification',q:'Which list correctly identifies the left-hand terms in m ü + c u̇ + ku = p(t)?',choices:['Inertia, damping, stiffness','Load, mass, temperature','Velocity, density, force','Energy, stress, strain'],answer:0,explanation:'The standard SDOF equation balances inertia, damping and restoring force against applied load.',math:'m\\ddot{u}+c\\dot{u}+ku=p(t)',source:'Lecture 2'},
{id:'free-vibration',title:'From forced to free vibration',level:'core',kind:'reasoning',q:'What change converts the general SDOF equation into free vibration?',choices:['Set p(t)=0','Set m=0','Set u=0','Set k=0'],answer:0,explanation:'Free vibration means no continuing external forcing after the initial disturbance.',math:'m\\ddot{u}+c\\dot{u}+ku=0',source:'Lecture 2'},
{id:'undamped-case',title:'Undamped special case',level:'core',kind:'reasoning',q:'What additional condition gives undamped free vibration?',choices:['c=0','m=0','k=0','u̇=0 for all time'],answer:0,explanation:'Removing viscous damping leaves only inertia and stiffness.',math:'m\\ddot{u}+ku=0',source:'Lecture 2'},
{id:'units',title:'Check damping units',level:'application',kind:'units',q:'Which SI unit is appropriate for viscous damping coefficient c in f_D=c u̇?',choices:['N·s/m','N/m','kg/m³','N·m²'],answer:0,explanation:'Force divided by velocity gives N/(m/s)=N·s/m.',math:'c=\\frac{f_D}{\\dot{u}}',source:'Lecture 2'}
],
'2:Pendulum natural angular frequency ω = √(g/L)':[
{id:'pendulum-formula',title:'Pendulum frequency formula',level:'foundation',kind:'formula',q:'For small oscillations of a simple pendulum, which expression gives natural angular frequency?',choices:['ω = √(g/L)','ω = √(L/g)','ω = gL','ω = 2πgL'],answer:0,explanation:'Linearising sin θ≈θ gives the standard small-angle pendulum frequency.',math:'\\omega_n=\\sqrt{\\frac{g}{L}}',source:'Lecture 2'},
{id:'length-effect',title:'Effect of pendulum length',level:'core',kind:'reasoning',q:'If pendulum length increases, what happens to its natural angular frequency?',choices:['It decreases','It increases linearly','It remains unchanged','It becomes zero immediately'],answer:0,explanation:'ω_n varies as 1/√L.',math:'\\omega_n\\propto L^{-1/2}',source:'Lecture 2'},
{id:'pendulum-number',title:'Numerical pendulum frequency',level:'application',kind:'numerical',q:'Using g≈9.81 m/s² and L=1 m, approximately what is ω_n?',choices:['3.13 rad/s','9.81 rad/s','1.00 rad/s','6.28 rad/s'],answer:0,explanation:'√9.81≈3.13.',math:'\\omega_n=\\sqrt{9.81/1}\\approx3.13\\,\\text{rad/s}',source:'Lecture 2'}
],
'2:Undamped spring-mass natural frequency ωₙ = √(k/m)':[
{id:'frequency-formula',title:'Spring-mass natural frequency',level:'foundation',kind:'formula',q:'Which formula gives the undamped natural angular frequency of a spring-mass SDOF system?',choices:['ωₙ = √(k/m)','ωₙ = √(m/k)','ωₙ = k/m','ωₙ = km'],answer:0,explanation:'Natural frequency increases with stiffness and decreases with mass.',math:'\\omega_n=\\sqrt{\\frac{k}{m}}',source:'Lecture 2'},
{id:'mass-effect',title:'Effect of mass',level:'core',kind:'reasoning',q:'If mass is multiplied by 4 while stiffness stays unchanged, ωₙ becomes:',choices:['Half','Double','Four times','Unchanged'],answer:0,explanation:'ω_n is inversely proportional to √m.',math:'\\omega_{n,new}=\\sqrt{\\frac{k}{4m}}=\\frac{1}{2}\\omega_n',source:'Lecture 2'},
{id:'freq-period',title:'Convert angular frequency to period',level:'core',kind:'formula',q:'How is natural period Tₙ related to ωₙ?',choices:['Tₙ = 2π/ωₙ','Tₙ = ωₙ/2π','Tₙ = 1/ωₙ²','Tₙ = 2πωₙ'],answer:0,explanation:'One full cycle is 2π radians.',math:'T_n=\\frac{2\\pi}{\\omega_n}',source:'Lecture 2'},
{id:'spring-number',title:'Natural-frequency numerical',level:'application',kind:'numerical',q:'For k=800 N/m and m=2 kg, what is ωₙ?',choices:['20 rad/s','400 rad/s','40 rad/s','10 rad/s'],answer:0,explanation:'800/2=400 and √400=20.',math:'\\omega_n=\\sqrt{800/2}=20\\,\\text{rad/s}',source:'Lecture 2'}
],
'3:Springs in parallel':[
{id:'parallel-rule',title:'Parallel stiffness rule',level:'foundation',kind:'formula',q:'For two springs in parallel, what is the equivalent stiffness?',choices:['k_eq = k₁+k₂','1/k_eq = 1/k₁+1/k₂','k_eq = k₁k₂','k_eq = k₁−k₂'],answer:0,explanation:'Parallel springs undergo the same displacement and their restoring forces add.',math:'k_{eq}=k_1+k_2',source:'Lecture 3'},
{id:'parallel-number',title:'Parallel numerical',level:'application',kind:'numerical',q:'Two parallel springs have stiffnesses 1000 and 1500 N/m. What is k_eq?',choices:['2500 N/m','600 N/m','1500 N/m','500 N/m'],answer:0,explanation:'Add the two stiffnesses.',math:'k_{eq}=1000+1500=2500\\,\\text{N/m}',source:'Lecture 3'}
],
'3:Springs in series':[
{id:'series-rule',title:'Series stiffness rule',level:'foundation',kind:'formula',q:'For two springs in series, which relation is correct?',choices:['1/k_eq = 1/k₁+1/k₂','k_eq = k₁+k₂','k_eq = k₁−k₂','k_eq = 0 always'],answer:0,explanation:'Series springs carry the same force while their displacements add.',math:'\\frac{1}{k_{eq}}=\\frac{1}{k_1}+\\frac{1}{k_2}',source:'Lecture 3'},
{id:'series-number',title:'Series numerical',level:'application',kind:'numerical',q:'Two equal springs of stiffness 1000 N/m are connected in series. What is k_eq?',choices:['500 N/m','2000 N/m','1000 N/m','250 N/m'],answer:0,explanation:'Two identical series springs have half the stiffness of one.',math:'k_{eq}=\\frac{k}{2}=500\\,\\text{N/m}',source:'Lecture 3'}
],
'4:Undamped response u(t) = A cos ωₙt + B sin ωₙt':[
{id:'constants',title:'Meaning of A and B',level:'foundation',kind:'concept',q:'What determines constants A and B in the undamped free-vibration response?',choices:['Initial displacement and initial velocity','Only mass density','Only damping ratio','Only external load after t=0'],answer:0,explanation:'Initial conditions select the particular motion from the general solution.',math:'u(t)=A\\cos\\omega_nt+B\\sin\\omega_nt',source:'Lecture 4'},
{id:'initial-displacement',title:'Apply initial displacement',level:'core',kind:'derivation',q:'If u(0)=u₀, what does the general solution immediately give for A?',choices:['A=u₀','A=0 always','A=ωₙu₀','A=u₀/ωₙ'],answer:0,explanation:'At t=0, cos0=1 and sin0=0.',math:'u(0)=A=u_0',source:'Lecture 4'},
{id:'initial-velocity',title:'Apply initial velocity',level:'core',kind:'derivation',q:'If u̇(0)=v₀, what is B?',choices:['B=v₀/ωₙ','B=v₀ωₙ','B=u₀','B=0 always'],answer:0,explanation:'Differentiate u(t), then evaluate at t=0: u̇(0)=Bωₙ.',math:'B=\\frac{v_0}{\\omega_n}',source:'Lecture 4'}
],
'4:Damping ratio ζ = c/c_cr':[
{id:'zeta-meaning',title:'Meaning of damping ratio',level:'foundation',kind:'concept',q:'What does ζ compare?',choices:['Actual damping to critical damping','Mass to stiffness','Frequency to period','Displacement to velocity'],answer:0,explanation:'The damping ratio non-dimensionalises damping using the critical damping coefficient.',math:'\\zeta=\\frac{c}{c_{cr}}',source:'Lecture 4'},
{id:'state-under',title:'Identify underdamping',level:'core',kind:'classification',q:'Which range corresponds to an underdamped system?',choices:['0 < ζ < 1','ζ > 1 only','ζ = 1 only','ζ < 0 only'],answer:0,explanation:'Underdamped systems oscillate while their amplitude decays.',source:'Lecture 4'},
{id:'state-critical',title:'Identify critical damping',level:'core',kind:'classification',q:'What value of ζ corresponds to critical damping?',choices:['1','0','0.5','2π'],answer:0,explanation:'Critical damping occurs when actual damping equals critical damping.',math:'\\zeta=1',source:'Lecture 4'},
{id:'zeta-number',title:'Compute damping ratio',level:'application',kind:'numerical',q:'If c=60 N·s/m and c_cr=300 N·s/m, what is ζ?',choices:['0.20','5.0','0.02','240'],answer:0,explanation:'Divide actual damping by critical damping.',math:'\\zeta=60/300=0.20',source:'Lecture 4'}
],
'4:Damped natural frequency ω_D = ωₙ√(1 − ζ²)':[
{id:'wd-formula',title:'Damped natural frequency',level:'core',kind:'formula',q:'For an underdamped SDOF system, which expression gives ω_D?',choices:['ω_D=ωₙ√(1−ζ²)','ω_D=ωₙ(1+ζ)','ω_D=ζ/ωₙ','ω_D=ωₙ/ζ'],answer:0,explanation:'Damping reduces the oscillation frequency slightly below the undamped natural frequency.',math:'\\omega_D=\\omega_n\\sqrt{1-\\zeta^2}',source:'Lecture 4'},
{id:'wd-number',title:'Compute damped frequency',level:'application',kind:'numerical',q:'For ωₙ=10 rad/s and ζ=0.6, what is ω_D?',choices:['8 rad/s','6 rad/s','10 rad/s','4 rad/s'],answer:0,explanation:'√(1−0.36)=0.8, so ω_D=8 rad/s.',math:'\\omega_D=10\\sqrt{1-0.6^2}=8\\,\\text{rad/s}',source:'Lecture 4'}
]};