Object.assign(window.REVISION_BANK,{
'1:Fourier-series idea for periodic loading':[
{id:'dos7-fourier-superpose',title:'Why Fourier decomposition helps',level:'core',kind:'concept',q:'Why is Fourier decomposition useful for a linear structure subjected to a complicated periodic load?',choices:['The periodic load can be represented as harmonics and the corresponding linear responses superposed','It converts every load into a static load','It removes inertia from the equation of motion','It makes damping exactly zero'],answer:0,explanation:'A periodic excitation can be decomposed into sinusoidal harmonics. For a linear system, the response to each harmonic can be solved and added by superposition.',math:'p(t)=a_0+\\sum_{n=1}^{\\infty}[a_n\\cos(n\\omega t)+b_n\\sin(n\\omega t)]',source:'Dynamics Lecture 1 topic + standard Fourier-analysis bridge (model supplement)',visual:{type:'graph',description:'Periodic waveform and its first few harmonic components versus time'}},
{id:'dos7-fourier-frequency',title:'Harmonic frequencies',level:'application',kind:'formula',q:'If a periodic load has fundamental angular frequency \\(\\omega\\), the third harmonic acts at:',choices:['\\(3\\omega\\)','\\(\\omega/3\\)','\\(\\omega+3\\)','\\(\\sqrt{3}\\omega\\)'],answer:0,explanation:'Fourier harmonics occur at integer multiples of the fundamental frequency.',math:'\\omega_n=n\\omega',source:'Dynamics Lecture 1 topic + standard Fourier-analysis bridge (model supplement)'}
],
'1:Random and impulsive loads':[
{id:'dos7-impulse',title:'Impulse measures force-time area',level:'core',kind:'formula',q:'The impulse delivered by a force history \\(p(t)\\) over \\(t_1\\le t\\le t_2\\) is:',choices:['\\(\\int_{t_1}^{t_2}p(t)\\,dt\\)','\\(dp/dt\\)','\\(p(t_2)-p(t_1)\\) only','\\(\\int p(t)^2dt\\)'],answer:0,explanation:'Impulse is the time integral of force and equals the resulting change in linear momentum.',math:'I=\\int_{t_1}^{t_2}p(t)\\,dt=\\Delta(m\\dot u)',source:'Dynamics Lecture 1 topic + standard dynamics bridge (model supplement)',visual:{type:'graph',description:'Short force pulse p(t) with shaded area representing impulse'}}
],
"2:d'Alembert's principle":[
{id:'dos7-dalembert',title:'Dynamic equilibrium using inertia force',level:'core',kind:'formula',q:"In d'Alembert's formulation, the inertia force associated with displacement \\(u(t)\\) is written as:",choices:['\\(-m\\ddot u\\)','\\(m u\\)','\\(-ku\\)','\\(c\\dot u\\)'],answer:0,explanation:'The inertia force is introduced opposite to acceleration so that the dynamic problem can be written in an equilibrium-like form.',math:'F_I=-m\\ddot u',source:"Dynamics Lecture 2 topic + d'Alembert bridge (model supplement)"}
],
'2:Inertia, damping and stiffness force terms':[
{id:'dos7-threeforces',title:'Three resisting terms in an SDOF model',level:'foundation',kind:'formula',q:'Which expression correctly pairs the three standard SDOF resisting forces with their response variables?',choices:['\\(m\\ddot u,\ c\\dot u,\ ku\\)','\\(mu,\ cu,\ ku^2\\)','\\(m\\dot u,\ c\\ddot u,\ k\\dot u\\)','\\(m/k,\ c/k,\ u/k\\)'],answer:0,explanation:'Mass multiplies acceleration, viscous damping multiplies velocity, and linear stiffness multiplies displacement.',math:'F_I=m\\ddot u,\\qquad F_D=c\\dot u,\\qquad F_S=ku',source:'Dynamics Lecture 2 topic + standard SDOF bridge (model supplement)'}
],
'3:Torsional disk free vibration':[
{id:'dos7-torsional-disk',title:'Torsional natural frequency',level:'core',kind:'formula',q:'For a rigid disk with mass moment of inertia \\(I_\\theta\\) attached to a torsional spring of stiffness \\(k_\\theta\\), the undamped natural angular frequency is:',choices:['\\(\\sqrt{k_\\theta/I_\\theta}\\)','\\(\\sqrt{I_\\theta/k_\\theta}\\)','\\(k_\\theta I_\\theta\\)','\\(k_\\theta/I_\\theta^2\\)'],answer:0,explanation:'The torsional oscillator has the same form as a translational SDOF system, with rotational inertia replacing mass and torsional stiffness replacing translational stiffness.',math:'I_\\theta\\ddot\\theta+k_\\theta\\theta=0,\\qquad \\omega_n=\\sqrt{\\frac{k_\\theta}{I_\\theta}}',source:'Dynamics Lecture 3 topic + standard torsional-vibration bridge (model supplement)'}
],
'3:Single-storey frame equivalent stiffness':[
{id:'dos7-frame-stiffness',title:'Storey stiffness from parallel columns',level:'application',kind:'reasoning',q:'If two identical columns restrain the same rigid floor translation and each contributes lateral stiffness \\(k_c\\), their idealized storey stiffness is:',choices:['\\(2k_c\\)','\\(k_c/2\\)','\\(k_c^2\\)','\\(1/k_c\\)'],answer:0,explanation:'The columns experience the same floor displacement, so their restoring forces add like springs in parallel.',math:'k_{storey}=k_c+k_c=2k_c',source:'Dynamics Lecture 3 topic + standard frame-stiffness bridge (model supplement)',visual:{type:'frame-diagram',description:'Rigid floor supported laterally by two identical columns represented as parallel springs'}}
],
'4:Critical damping coefficient c_cr = 2mωₙ':[
{id:'dos7-ccr',title:'Critical damping threshold',level:'core',kind:'formula',q:'The critical viscous damping coefficient of an SDOF system is:',choices:['\\(c_{cr}=2m\\omega_n=2\\sqrt{km}\\)','\\(c_{cr}=m\\omega_n/2\\)','\\(c_{cr}=k/m\\)','\\(c_{cr}=2k\\omega_n\\)'],answer:0,explanation:'Critical damping separates oscillatory and non-oscillatory free response.',math:'c_{cr}=2m\\omega_n=2\\sqrt{km}',source:'Dynamics Lecture 4 topic + standard vibration bridge (model supplement)'}
],
'4:Energy in undamped free vibration':[
{id:'dos7-energy-conservation',title:'Energy exchange in undamped vibration',level:'core',kind:'formula',q:'For an undamped spring-mass oscillator with no external work, which quantity remains constant?',choices:['\\(\\tfrac12m\\dot u^2+\\tfrac12ku^2\\)','\\(m\\dot u\\) alone','\\(ku\\) alone','\\(\\tfrac12c\\dot u^2\\)'],answer:0,explanation:'Kinetic and elastic strain energies exchange continuously, while their sum remains constant in ideal undamped free vibration.',math:'E=\\frac12m\\dot u^2+\\frac12ku^2=\\text{constant}',source:'Dynamics Lecture 4 topic + standard vibration-energy bridge (model supplement)',visual:{type:'graph',description:'Kinetic and strain energy versus time, out of phase, with constant total energy'}}
]
});