Object.assign(window.REVISION_BANK,{
'1:Static and dynamic force classification':[
{id:'dos4-static-force',title:'Static force test',level:'foundation',kind:'classification',q:'A load that is applied slowly enough that inertia effects are negligible is treated as:',choices:['Static','Impulsive','Random','Resonant'],answer:0,explanation:'Static analysis assumes the load changes slowly enough that acceleration and inertia can be neglected.',source:'Lecture 1'},
{id:'dos4-dynamic-force',title:'When does a load become dynamic?',level:'core',kind:'reasoning',q:'A load should be treated dynamically when:',choices:['Its time variation causes significant inertia effects','Its magnitude is always small','Its direction is vertical','It acts on steel only'],answer:0,explanation:'The defining issue is whether time variation generates significant mass-acceleration response.',math:'F_I=m\\ddot u',source:'Lecture 1'}
],
'1:Random and impulsive loads':[
{id:'dos4-random-load',title:'Random load meaning',level:'foundation',kind:'concept',q:'A random dynamic load is one whose exact time history:',choices:['Cannot be predicted deterministically in advance','Repeats perfectly every period','Is always zero','Is necessarily sinusoidal'],answer:0,explanation:'Random loading is described statistically rather than by one fully deterministic time function.',source:'Lecture 1'},
{id:'dos4-impulse',title:'Impulse definition',level:'core',kind:'formula',q:'The impulse associated with a force F(t) acting from t1 to t2 is:',choices:['∫F(t)dt','F/t','dF/dt only','F²t'],answer:0,explanation:'Impulse is the time integral of force and equals change in linear momentum for a particle/system.',math:'J=\\int_{t_1}^{t_2}F(t)\\,dt',source:'Lecture 1'}
],
'1:Deterministic and non-deterministic analysis':[
{id:'dos4-deterministic',title:'Deterministic analysis',level:'foundation',kind:'concept',q:'In deterministic dynamic analysis, the applied load history is:',choices:['Specified as a known function of time','Known only through probability distributions','Always zero','Ignored'],answer:0,explanation:'A deterministic analysis starts from a prescribed time history such as a harmonic force.',source:'Lecture 1'},
{id:'dos4-stochastic',title:'Non-deterministic analysis',level:'core',kind:'concept',q:'When loading is described using probability or spectral properties rather than one exact history, the analysis is:',choices:['Non-deterministic/stochastic','Purely static','Geometric only','Kinematic only'],answer:0,explanation:'Stochastic dynamics uses statistical descriptors of uncertain excitation.',source:'Lecture 1'}
],
'2:Methods for formulating equations of motion':[
{id:'dos4-eom-methods',title:'Equation-of-motion routes',level:'foundation',kind:'concept',q:'Which is a valid route for deriving equations of motion?',choices:['Newton/d’Alembert, virtual work or energy methods','Only dimensional analysis','Only plotting','Only finite differences'],answer:0,explanation:'Structural dynamics commonly uses force equilibrium, d’Alembert principle, virtual work/Lagrange or energy approaches.',source:'Lecture 2'},
{id:'dos4-lagrange-form',title:'Recognise Lagrange’s equation',level:'advanced',kind:'formula',q:'Which expression is Lagrange’s equation for generalized coordinate q_i with generalized force Q_i?',choices:['d/dt(∂T/∂q̇_i)−∂T/∂q_i+∂V/∂q_i=Q_i','ku=P only','m=q_i','E=mc²'],answer:0,explanation:'Lagrange’s equation balances kinetic and potential energy contributions with generalized forcing.',math:'\\frac{d}{dt}\\left(\\frac{\\partial T}{\\partial \\dot q_i}\\right)-\\frac{\\partial T}{\\partial q_i}+\\frac{\\partial V}{\\partial q_i}=Q_i',source:'Lecture 2 + standard dynamics bridge'}
],
'2:The simplest SDOF model':[
{id:'dos4-sdof-components',title:'SDOF physical model',level:'foundation',kind:'concept',q:'The simplest linear SDOF oscillator is idealized using:',choices:['One lumped mass and one restoring spring, optionally a damper','Two independent masses minimum','No inertia','Only a rigid support'],answer:0,explanation:'A single independent displacement coordinate describes the motion of the idealized mass-spring-damper system.',source:'Lecture 2'},
{id:'dos4-sdof-free',title:'Undamped free SDOF equation',level:'core',kind:'formula',q:'For an undamped SDOF system with no external force, the equation of motion is:',choices:['m ü+ku=0','m u̇+ku=0','ku=p(t)','m u=0'],answer:0,explanation:'With c=0 and p(t)=0, inertia and elastic restoring force balance.',math:'m\\ddot u+ku=0',source:'Lecture 2'}
],
'2:Unit conversion and weight-to-mass example':[
{id:'dos4-weight-mass',title:'Weight to mass',level:'core',kind:'formula',q:'If a body has weight W in newtons, its mass is:',choices:['W/g','Wg','g/W','W²/g'],answer:0,explanation:'Weight is gravitational force, W=mg.',math:'m=\\frac{W}{g}',source:'Lecture 2'},
{id:'dos4-kn-mass',title:'Numerical weight-to-mass',level:'application',kind:'numerical',q:'A machine weighs 19.62 kN. Using g=9.81 m/s², its mass is approximately:',choices:['2000 kg','19.62 kg','192.5 kg','20 kg'],answer:0,explanation:'Convert 19.62 kN to 19620 N and divide by 9.81 m/s².',math:'m=19620/9.81=2000\\,\\mathrm{kg}',source:'Lecture 2'}
],
'3:Mixed spring systems':[
{id:'dos4-mixed-spring',title:'Mixed spring reduction',level:'core',kind:'reasoning',q:'For a mixed spring network, the safest reduction strategy is to:',choices:['Identify clear series/parallel groups and reduce them step by step','Add every stiffness directly','Invert every stiffness directly','Ignore connectivity'],answer:0,explanation:'Equivalent stiffness depends on topology; series and parallel rules must be applied to the correct subgroups.',source:'Lecture 3'},
{id:'dos4-series-num',title:'Series spring numerical',level:'application',kind:'numerical',q:'Springs 300 N/m and 600 N/m are in series. Their equivalent stiffness is:',choices:['200 N/m','900 N/m','450 N/m','300 N/m'],answer:0,explanation:'For series springs, 1/k_eq=1/300+1/600=1/200.',math:'k_{eq}=\\left(\\frac1{300}+\\frac1{600}\\right)^{-1}=200\\,\\mathrm{N/m}',source:'Lecture 3'}
],
'3:Beam plus spring equivalent stiffness':[
{id:'dos4-beam-spring-parallel',title:'Beam and spring in parallel',level:'core',kind:'formula',q:'If a structural member with lateral stiffness k_b and an added spring k_s resist the same displacement in parallel, the equivalent stiffness is:',choices:['k_b+k_s','k_b k_s/(k_b+k_s)','k_b−k_s','1/(k_b+k_s)'],answer:0,explanation:'Parallel resisting elements undergo the same displacement and their restoring forces add.',math:'k_{eq}=k_b+k_s',source:'Lecture 3'},
{id:'dos4-beam-spring-freq',title:'Effect on natural frequency',level:'application',kind:'reasoning',q:'Adding a positive spring stiffness in parallel to a fixed mass generally causes natural frequency to:',choices:['Increase','Decrease','Remain unchanged','Become zero'],answer:0,explanation:'Natural frequency increases with the square root of total stiffness.',math:'\\omega_n=\\sqrt{\\frac{k_b+k_s}{m}}',source:'Lecture 3'}
],
'3:Torsional disk free vibration':[
{id:'dos4-torsional-eom',title:'Torsional oscillator equation',level:'core',kind:'formula',q:'For a rigid disk with mass moment of inertia I_θ and torsional stiffness k_θ, undamped free vibration is governed by:',choices:['I_θ θ̈+k_θ θ=0','mθ̈+kθ=0','I_θ θ̇+k_θ=0','k_θ θ̈=0'],answer:0,explanation:'Rotational inertia times angular acceleration balances the torsional restoring moment.',math:'I_\\theta\\ddot\\theta+k_\\theta\\theta=0',source:'Lecture 3'},
{id:'dos4-torsional-freq',title:'Torsional natural frequency',level:'application',kind:'formula',q:'The torsional natural angular frequency of that disk is:',choices:['√(k_θ/I_θ)','√(I_θ/k_θ)','k_θ I_θ','k_θ/I_θ'],answer:0,explanation:'Comparing the torsional oscillator equation with the standard SDOF form gives ω_n²=k_θ/I_θ.',math:'\\omega_n=\\sqrt{\\frac{k_\\theta}{I_\\theta}}',source:'Lecture 3'}
],
'4:Critically damped response':[
{id:'dos4-critical-root',title:'Critical damping roots',level:'core',kind:'concept',q:'At critical damping, the characteristic equation has:',choices:['A repeated real root','Two distinct imaginary roots','No roots','Two positive real roots always'],answer:0,explanation:'At ζ=1, the discriminant vanishes and both characteristic roots equal −ω_n.',math:'r_1=r_2=-\\omega_n',source:'Lecture 4'},
{id:'dos4-critical-use',title:'Why critical damping matters',level:'application',kind:'concept',q:'Critical damping is often desirable when the aim is to:',choices:['Return to equilibrium rapidly without oscillation','Maximize sustained oscillation','Remove stiffness','Create resonance'],answer:0,explanation:'Critical damping is the boundary between oscillatory and non-oscillatory response and gives the fastest non-oscillatory return for the ideal SDOF model.',source:'Lecture 4'}
],
'4:Overdamped response':[
{id:'dos4-over-roots',title:'Overdamped roots',level:'core',kind:'concept',q:'For ζ>1, the free-vibration characteristic roots are:',choices:['Two distinct negative real roots','Pure imaginary roots','A repeated zero root','Positive imaginary roots'],answer:0,explanation:'Overdamped systems return without oscillating and are represented by two decaying exponentials.',source:'Lecture 4'},
{id:'dos4-over-form',title:'Overdamped response form',level:'advanced',kind:'formula',q:'Which qualitative form describes overdamped free vibration?',choices:['C₁e^{r₁t}+C₂e^{r₂t} with r₁,r₂<0','A constant-amplitude sinusoid','A growing exponential only','A triangular wave'],answer:0,explanation:'Distinct negative real roots produce a sum of two decaying exponential terms.',math:'u(t)=C_1e^{r_1t}+C_2e^{r_2t}',source:'Lecture 4'}
]
});