(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, Ch.11 source-grounded lesson; IS 800:2007 plate-girder provisions where noted';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('11:Introduction',[
{id:'ch11-intro-1',title:'Why fabricate a girder?',level:'foundation',kind:'concept',q:'Why is a plate girder considered when ordinary rolled beams become uneconomical?',choices:['Its depth and plate sizes can be fabricated to suit larger span or load demands','Its elastic modulus can be increased by welding','It eliminates bending moment','It requires no web'],answer:0,explanation:'A fabricated plate girder lets the designer tailor web depth and flange size when rolled sections are no longer economical.',source:S},
{id:'ch11-intro-2',title:'Built-up form',level:'foundation',kind:'recognition',q:'A conventional welded plate girder is most closely represented by which built-up form?',choices:['A deep I-shaped member made from flange and web plates','A solid circular shaft','A cable-only member','A masonry arch'],answer:0,explanation:'The conventional plate girder is a deep built-up I-section assembled from plates, usually by welding.',source:S},
{id:'ch11-intro-3',title:'Alternative systems',level:'core',kind:'reasoning',q:'Before selecting a plate girder for a long span or heavy load, what comparison does the chapter encourage?',choices:['Compare fabricated girders with alternatives such as compound beams, cover-plated beams and trusses','Compare only paint colours','Ignore fabrication cost','Use the deepest possible girder automatically'],answer:0,explanation:'Structural form is selected by comparing feasible alternatives for strength, span, fabrication and economy.',source:S},
{id:'ch11-intro-4',title:'Primary action',level:'core',kind:'classification',q:'A plate girder is primarily designed as which kind of structural member?',choices:['A flexural member','A pure tension cable','A soil-retaining wall','A compression-only strut'],answer:0,explanation:'Plate girders are deep built-up flexural members carrying bending and shear.',source:S},
{id:'ch11-intro-5',title:'Span-load context',level:'application',kind:'reasoning',q:'Which situation most strongly points toward investigating a plate-girder solution?',choices:['A heavy load over a span beyond the economical range of standard rolled beams','A tiny wall opening carrying negligible load','A member carrying no transverse load','A short timber joist'],answer:0,explanation:'The chapter positions plate girders for relatively heavy loads and longer spans where rolled sections become inefficient.',source:S},
{id:'ch11-intro-6',title:'Fabrication implication',level:'retrieval',kind:'concept',q:'What extra design dimension comes with choosing a fabricated plate girder instead of a stock rolled section?',choices:['Plate proportioning and fabrication detailing become part of the structural design','Steel density must be redesigned','Yield stress becomes arbitrary','Shear force disappears'],answer:0,explanation:'The designer must proportion and connect individual web, flange and stiffener plates.',source:S}
]);
add('11:Plate Girders',[
{id:'ch11-pg-1',title:'Tailored geometry',level:'foundation',kind:'concept',q:'What geometric freedom is a major advantage of plate girders?',choices:['Web depth and flange size can be varied to suit demand','Poisson ratio can be varied along the span','Steel density can be changed by welding','Support reactions can be eliminated'],answer:0,explanation:'Fabrication allows the cross-section to be tailored rather than fixed to a rolled catalogue shape.',source:S},
{id:'ch11-pg-2',title:'Typical application',level:'foundation',kind:'classification',q:'Which is a typical plate-girder application identified in the chapter?',choices:['Long-span bridge or heavy gantry girder','Light curtain wall only','Timber roof batten only','Nonstructural partition'],answer:0,explanation:'Plate girders are common in bridges, gantry girders, power-plant structures and other heavy-load applications.',source:S},
{id:'ch11-pg-3',title:'Modern fabrication',level:'core',kind:'recognition',q:'How are modern plate girders predominantly assembled?',choices:['By welding','By casting the complete girder as one steel block','By gluing timber laminations','By prestressing concrete only'],answer:0,explanation:'The textbook describes modern plate girders as predominantly welded built-up members.',source:S},
{id:'ch11-pg-4',title:'Haunched form',level:'core',kind:'reasoning',q:'Why might a plate girder be tapered or haunched?',choices:['To vary depth where force demand or geometry justifies it','To make the steel modulus larger near supports','To prevent all shear','To avoid using flanges'],answer:0,explanation:'Fabrication permits variation in depth to better follow structural demand or geometric constraints.',source:S},
{id:'ch11-pg-5',title:'Force matching',level:'application',kind:'reasoning',q:'What is the structural benefit of varying a fabricated cross-section along the span?',choices:['Material can be placed more closely in proportion to changing force demand','The load combination is removed','The web need not carry shear','Deflection becomes zero'],answer:0,explanation:'A varying section can improve material efficiency by responding to changing moments and shears.',source:S},
{id:'ch11-pg-6',title:'Rolled versus fabricated',level:'retrieval',kind:'concept',q:'Which statement best distinguishes a plate girder from a standard rolled I-section?',choices:['The plate girder is assembled from separate plates and can be custom proportioned','The plate girder cannot resist bending','The rolled section has no web','Only the plate girder uses steel'],answer:0,explanation:'The defining advantage is custom fabrication of the web and flanges.',source:S}
]);
add('11:General Considerations',[
{id:'ch11-gen-1',title:'Why stability governs',level:'foundation',kind:'reasoning',q:'Why is web stability a central plate-girder issue?',choices:['The web is often deep and slender','The web is always solid and stocky','Steel webs have no shear strength','Flanges carry all shear by definition'],answer:0,explanation:'Deep slender webs are efficient but susceptible to shear and local buckling.',source:S},
{id:'ch11-gen-2',title:'Failure mode',level:'foundation',kind:'classification',q:'Which is a genuine plate-girder failure concern?',choices:['Web shear buckling','Concrete punching through a slab only','Cable sag only','Timber splitting only'],answer:0,explanation:'The chapter highlights flange yielding or buckling, web shear buckling and local effects near concentrated loads.',source:S},
{id:'ch11-gen-3',title:'Intermediate stiffener role',level:'core',kind:'concept',q:'What is a principal role of intermediate transverse stiffeners?',choices:['Improve web shear stability and enable useful post-buckling behaviour','Increase steel yield strength chemically','Carry all flange bending','Eliminate support reactions'],answer:0,explanation:'Intermediate stiffeners subdivide the slender web into panels and support shear-buckling resistance.',source:S},
{id:'ch11-gen-4',title:'Bearing stiffener role',level:'core',kind:'classification',q:'Where are bearing stiffeners especially relevant?',choices:['At concentrated loads or reactions that can locally distress the web','Only at zero-shear locations','Only at the tension flange midspan','Only for corrosion protection'],answer:0,explanation:'Bearing stiffeners protect the web near large concentrated forces and reactions.',source:S},
{id:'ch11-gen-5',title:'Post-buckling concept',level:'application',kind:'reasoning',q:'Does initial shear buckling of a suitably stiffened slender web necessarily mean immediate loss of all girder resistance?',choices:['No, post-buckling tension-field action can provide additional resistance','Yes, the web instantly carries zero force','Yes, both flanges must fracture immediately','No, because the web never buckles'],answer:0,explanation:'The chapter explicitly uses post-buckling tension-field action where the surrounding system can anchor it.',source:S},
{id:'ch11-gen-6',title:'Design mindset',level:'retrieval',kind:'concept',q:'What must be balanced in economical plate-girder design?',choices:['Strength, stability and fabrication efficiency','Only maximum plate thickness','Only steel density','Only flange colour'],answer:0,explanation:'Plate girder design is strongly influenced by thin-plate stability as well as ordinary strength and practical fabrication.',source:S}
]);
add('11:Distribution of Stress in a Plate Girder',[
{id:'ch11-stress-1',title:'Bending stress pattern',level:'foundation',kind:'concept',q:'Under ordinary beam bending, where is the normal bending stress largest in magnitude?',choices:['Farther from the neutral axis','Exactly at the neutral axis','Only at web centre','Uniform everywhere'],answer:0,explanation:'Bending normal stress increases with distance from the neutral axis, making the flanges efficient moment-resisting elements.',source:S},
{id:'ch11-stress-2',title:'Flange role',level:'foundation',kind:'classification',q:'Why are plate-girder flanges placed far from the neutral axis?',choices:['To resist bending moment efficiently','To carry all vertical shear only','To reduce section depth','To eliminate welds'],answer:0,explanation:'Material far from the neutral axis contributes strongly to flexural resistance.',source:S},
{id:'ch11-stress-3',title:'Web role',level:'core',kind:'concept',q:'What internal action is concentrated mainly in the plate-girder web?',choices:['Vertical shear','All bending moment only','Torsion only','Temperature force only'],answer:0,explanation:'The web is proportioned primarily for shear while the flanges resist most bending.',source:S},
{id:'ch11-stress-4',title:'Neutral axis',level:'core',kind:'recognition',q:'At the neutral axis in elastic bending, what is the longitudinal bending stress?',choices:['Approximately zero','Maximum tension','Maximum compression','Equal to yield stress automatically'],answer:0,explanation:'Elastic bending stress passes through zero at the neutral axis.',source:S},
{id:'ch11-stress-5',title:'Efficient division of roles',level:'application',kind:'reasoning',q:'Why is a deep thin web with substantial flanges structurally efficient?',choices:['The web supplies depth and shear area while flanges place bending material far from the neutral axis','The web removes all bending moment','The flanges remove all shear force from equilibrium','The arrangement changes steel modulus'],answer:0,explanation:'The cross-section exploits the different stress distributions of bending and shear.',source:S},
{id:'ch11-stress-6',title:'Proportioning clue',level:'retrieval',kind:'concept',q:'Which simple design allocation follows from the chapter stress-distribution discussion?',choices:['Flanges mainly for bending; web mainly for shear','Web mainly for bending; stiffeners mainly for axial tension','Flanges only for shear; web only for torsion','Welds carry all global actions'],answer:0,explanation:'This division of roles is the central starting point for plate-girder proportioning.',source:S}
]);
add('11:Preliminary Design Procedure',[
{id:'ch11-prelim-1',title:'Start with actions',level:'foundation',kind:'sequence',q:'Which pair of factored actions is central at the start of preliminary plate-girder design?',choices:['Bending moment and shear force','Only temperature and shrinkage','Only axial tension and torsion','Only corrosion and fatigue'],answer:0,explanation:'Preliminary proportioning starts from the governing factored moment and shear, together with an estimate of self-weight.',source:S},
{id:'ch11-prelim-2',title:'Trial depth',level:'foundation',kind:'sequence',q:'What major geometric choice is made early in preliminary design?',choices:['A trial girder depth','A new value of Young’s modulus','A new steel density','A final paint thickness'],answer:0,explanation:'The trial depth strongly influences web slenderness, flange force and overall economy.',source:S},
{id:'ch11-prelim-3',title:'Web sizing',level:'core',kind:'reasoning',q:'After selecting a trial depth, the web is primarily proportioned against what demand?',choices:['Shear and web slenderness requirements','Only flange bending stress','Only torsional rotation','Only thermal strain'],answer:0,explanation:'The web is principally sized for shear while satisfying minimum thickness and stability requirements.',source:S},
{id:'ch11-prelim-4',title:'Flange sizing',level:'core',kind:'reasoning',q:'The flange area in preliminary design is primarily controlled by which action?',choices:['Bending moment','Vertical shear alone','Hydrostatic pressure','Only support bearing'],answer:0,explanation:'Flanges supply most of the flexural resistance.',source:S},
{id:'ch11-prelim-5',title:'Practical depth limit',level:'application',kind:'reasoning',q:'Why might the theoretically most efficient deep girder not be adopted?',choices:['Transport and fabrication constraints may limit practical depth','Deeper girders have no bending resistance','Steel cannot be welded when deep','Support reactions vanish with depth'],answer:0,explanation:'Practical transport, fabrication and erection constraints influence the selected depth.',source:S},
{id:'ch11-prelim-6',title:'Flange curtailment',level:'retrieval',kind:'concept',q:'Why can cover plates or flange material sometimes be curtailed along the span?',choices:['Bending moment demand varies along the span','Steel yield stress varies with position','Shear is always zero near supports','The web cannot be welded continuously'],answer:0,explanation:'Where flexural demand reduces, flange area may sometimes be reduced with proper development and detailing.',source:S}
]);
add('11:Web Panel Subjected to Shear',[
{id:'ch11-webshear-1',title:'Principal stress directions',level:'foundation',kind:'concept',q:'A web panel subjected mainly to shear develops which principal stress pattern?',choices:['Diagonal tension and diagonal compression','Only vertical tension','Only horizontal compression','Uniform hydrostatic stress'],answer:0,explanation:'Pure shear resolves into diagonal principal tension and compression.',source:S},
{id:'ch11-webshear-2',title:'First buckling direction',level:'foundation',kind:'reasoning',q:'Which diagonal is associated with the initial buckling tendency of a slender web panel in shear?',choices:['The principal compression diagonal','The principal tension diagonal only','The neutral axis only','The flange weld line only'],answer:0,explanation:'Buckling develops along the compressive principal-stress direction.',source:S},
{id:'ch11-webshear-3',title:'After buckling',level:'core',kind:'concept',q:'What post-buckling mechanism can develop in a suitably bounded slender web panel?',choices:['Diagonal tension field','Euler column buckling of the whole flange only','Pure torsional yielding','Zero-stress membrane'],answer:0,explanation:'After shear buckling, a diagonal tension field can carry additional load if anchored by the surrounding elements.',source:S},
{id:'ch11-webshear-4',title:'Boundary requirement',level:'core',kind:'reasoning',q:'Why do stiffeners and flanges matter to tension-field action?',choices:['They provide boundaries that anchor and equilibrate the diagonal membrane forces','They change steel chemistry','They make shear vanish','They remove the web from the load path'],answer:0,explanation:'Post-buckling membrane action requires an adequate surrounding frame.',source:S},
{id:'ch11-webshear-5',title:'Pre versus post buckling',level:'application',kind:'classification',q:'Which statement correctly distinguishes pre- and post-buckling web behaviour?',choices:['Elastic shear buckling may occur before ultimate shear resistance if tension-field action is available','Ultimate resistance must equal first buckling load in every case','Post-buckling means the web carries no load','Pre-buckling behaviour requires no shear'],answer:0,explanation:'Stiffened slender webs can retain and develop resistance beyond first elastic buckling.',source:S},
{id:'ch11-webshear-6',title:'Design consequence',level:'retrieval',kind:'reasoning',q:'Why can a thin stiffened web still be economical despite a relatively low elastic buckling load?',choices:['Its post-buckling tension-field resistance may be intentionally utilized','Its density is lower than steel','Its yield stress becomes infinite','The flanges carry no moment'],answer:0,explanation:'The chapter treats post-buckling resistance as a legitimate source of shear capacity where conditions permit.',source:S}
]);
add('11:Webs Subjected to Combined Bending and Shear',[
{id:'ch11-comb-1',title:'Interaction need',level:'foundation',kind:'reasoning',q:'Why should high bending and high shear not always be checked independently in a plate girder?',choices:['They alter the same stress state and can reduce the available resistance to each other','They occur in different materials','Shear cannot exist with bending','Bending cannot act in a web'],answer:0,explanation:'When both actions are significant, their effects interact and an interaction check is required.',source:S},
{id:'ch11-comb-2',title:'High shear effect',level:'core',kind:'concept',q:'What can high shear do to the moment resistance available at a section?',choices:['Reduce the available moment resistance','Always increase it','Make it independent of flange strength','Set it to zero for every section'],answer:0,explanation:'Combined-action provisions account for the reduction in one resistance when the other action becomes large.',source:S},
{id:'ch11-comb-3',title:'Bending effect on web',level:'core',kind:'reasoning',q:'How can bending influence web shear behaviour?',choices:['Longitudinal bending stresses change the web stress state and can affect shear resistance','It eliminates principal compression','It makes web slenderness irrelevant','It changes steel density'],answer:0,explanation:'The web is simultaneously subjected to bending-related longitudinal stress and shear stress.',source:S},
{id:'ch11-comb-4',title:'Possible governing mode',level:'application',kind:'classification',q:'Under combined bending and shear, which additional limit state may become important besides web shear buckling?',choices:['Flange yielding or flange instability','Concrete punching only','Cable rupture only','Timber bearing only'],answer:0,explanation:'The chapter notes that flange yielding or instability can govern in regions where flexure is significant.',source:S},
{id:'ch11-comb-5',title:'Low interaction region',level:'application',kind:'reasoning',q:'If one action is small compared with its resistance, what is generally true conceptually about interaction?',choices:['The other action may dominate and interaction becomes less severe','The small action always doubles the other','Both resistances become zero','The web must be replaced'],answer:0,explanation:'Interaction becomes important as both bending and shear approach significant fractions of their capacities.',source:S},
{id:'ch11-comb-6',title:'Integrated check',level:'retrieval',kind:'concept',q:'What is the safest design mindset for a section carrying substantial moment and shear?',choices:['Use the prescribed combined-action interaction procedure rather than isolated maximum checks only','Check only moment','Check only shear','Average the two actions directly'],answer:0,explanation:'The source treats combined bending and shear through an interaction approach.',source:S}
]);
add('11:Design of Plate Girders using IS 800 Provisions',[
{id:'ch11-is800-1',title:'Code design roles',level:'foundation',kind:'classification',q:'In the textbook IS 800 plate-girder model, which allocation is used?',choices:['Flanges mainly resist bending and the web mainly resists shear','Stiffeners resist all bending and welds resist all shear','Web resists all bending and flanges all shear','Only the web is structurally effective'],answer:0,explanation:'This division organizes the chapter design sequence.',source:S},
{id:'ch11-is800-2',title:'Shear resistance modes',level:'core',kind:'concept',q:'According to the uploaded IS 800 provisions, nominal web shear strength may be governed by what?',choices:['Plastic shear resistance or web shear buckling resistance','Only flange rupture','Only bolt bearing','Only torsion'],answer:0,explanation:'IS 800 distinguishes plastic shear resistance from shear-buckling-governed resistance for slender webs.',source:S},
{id:'ch11-is800-3',title:'Stiffener trigger',level:'core',kind:'reasoning',q:'When an unstiffened web is inadequate, what type of design measure is specifically provided for in IS 800?',choices:['Provide suitable web stiffeners','Increase Young’s modulus','Ignore shear','Remove the compression flange'],answer:0,explanation:'The code includes intermediate and other stiffeners to improve web behaviour and resist local effects.',source:S},
{id:'ch11-is800-4',title:'Web effective area',level:'core',kind:'recognition',q:'For a normal plate-girder web, what simple effective web area is stated in the uploaded IS 800 text for shear calculations?',choices:['Full web depth multiplied by web thickness','Flange width multiplied by flange thickness only','Half the gross girder area','Weld throat area only'],answer:0,explanation:'The cited provision takes the effective web sectional area as full web depth times web thickness, subject to noted exceptions.',source:S},
{id:'ch11-is800-5',title:'Web-flange connection',level:'application',kind:'reasoning',q:'What must the flange-to-web connection be capable of transmitting?',choices:['The required longitudinal shear transfer, plus relevant directly applied flange loads','Only paint weight','Only flange self-weight regardless of force flow','No force if the girder is welded'],answer:0,explanation:'IS 800 requires sufficient welds or fasteners to transmit the horizontal shear associated with moment gradient and applicable direct loads.',source:S},
{id:'ch11-is800-6',title:'Full code workflow',level:'retrieval',kind:'concept',q:'Which group best represents a complete textbook IS 800 plate-girder check?',choices:['Bending, web slenderness/shear buckling, stiffeners, connections and restraint','Only section weight','Only flange area','Only support reaction'],answer:0,explanation:'The chapter integrates member resistance, plate stability, stiffener design and force transfer.',source:S}
]);
add('11:Behaviour of Longitudinally Stiffened Plate Girders',[
{id:'ch11-long-1',title:'Longitudinal direction',level:'foundation',kind:'recognition',q:'How is a longitudinal stiffener oriented relative to the girder span?',choices:['Along the girder length','Vertically across the web depth only','Normal to the web plate','Around the flange edge'],answer:0,explanation:'A longitudinal stiffener runs along the member and subdivides the web depth into smaller plate sub-panels.',source:S},
{id:'ch11-long-2',title:'Structural purpose',level:'foundation',kind:'concept',q:'Why add a longitudinal stiffener to a very slender web?',choices:['To increase web buckling resistance','To make the web carry no shear','To increase steel yield strength chemically','To eliminate flanges'],answer:0,explanation:'Subdividing the web increases its plate-buckling resistance.',source:S},
{id:'ch11-long-3',title:'Stiffener rigidity',level:'core',kind:'reasoning',q:'Why must the longitudinal stiffener itself have adequate rigidity?',choices:['So it remains essentially straight at first buckling and forces buckling into the web sub-panels','So it yields before the web','So it carries all bending moment','So it can replace the flange'],answer:0,explanation:'The stiffener must function as a stable line of support to the adjacent web plates.',source:S},
{id:'ch11-long-4',title:'Sub-panel effect',level:'core',kind:'concept',q:'What geometric change does a longitudinal stiffener create in the web stability problem?',choices:['It divides the web depth into smaller plate sub-panels','It doubles the member span','It removes the neutral axis','It makes the web a solid block'],answer:0,explanation:'Buckling behaviour is then governed by the smaller web panels rather than the full web depth alone.',source:S},
{id:'ch11-long-5',title:'Economy comparison',level:'application',kind:'reasoning',q:'Why is adding a longitudinal stiffener not automatically the most economical solution?',choices:['Its weight and fabrication cost may exceed the benefit compared with a thicker web','It always reduces shear capacity','It prevents welding','It lowers steel modulus'],answer:0,explanation:'The source explicitly recommends comparing stiffening with simply increasing web thickness.',source:S},
{id:'ch11-long-6',title:'When most useful',level:'retrieval',kind:'application',q:'Longitudinal stiffening is most relevant to which web condition?',choices:['A very slender web where plate buckling resistance needs improvement','A massive stocky web with no stability concern','A tension rod','A solid shaft'],answer:0,explanation:'Its purpose is to improve the buckling behaviour of slender web plates.',source:S}
]);
add('11:Girders with Openings in Slender Webs',[
{id:'ch11-open-1',title:'Why openings exist',level:'foundation',kind:'concept',q:'Why might an opening be introduced into a plate-girder web?',choices:['To pass services or satisfy functional requirements','To increase steel density','To eliminate flanges','To remove bending moment'],answer:0,explanation:'Web openings may be required for services, but they disturb the structural web action.',source:S},
{id:'ch11-open-2',title:'Main structural effect',level:'foundation',kind:'reasoning',q:'What important post-buckling mechanism is interrupted by a large web opening?',choices:['Diagonal tension-field action','Flange yielding only','Elastic modulus','Support bearing pressure in concrete'],answer:0,explanation:'An opening cuts across the diagonal membrane load path and can reduce shear resistance.',source:S},
{id:'ch11-open-3',title:'Capacity consequence',level:'core',kind:'concept',q:'What is the expected effect of a large opening on a slender web panel?',choices:['Reduced shear resistance','Guaranteed higher shear resistance','No effect on force flow','Elimination of bending in flanges'],answer:0,explanation:'Removing web material and interrupting the tension field weakens the panel.',source:S},
{id:'ch11-open-4',title:'Conservative treatment',level:'core',kind:'reasoning',q:'What conservative approach does the chapter mention for a slender web panel containing an opening?',choices:['Limit the panel resistance to its buckling resistance rather than relying fully on post-buckling strength','Assume infinite tension-field strength','Ignore the opening','Treat the web as solid'],answer:0,explanation:'The chapter notes that conservative design may avoid crediting the full post-buckling resistance in the weakened panel.',source:S},
{id:'ch11-open-5',title:'Local mitigation',level:'application',kind:'reasoning',q:'What practical measure can help a web panel adjacent to an opening?',choices:['Reduce the adjacent stiffener spacing','Remove all stiffeners','Cut a larger opening','Reduce flange area'],answer:0,explanation:'Closer stiffeners can strengthen the weakened zone and help its resistance approach neighbouring panels.',source:S},
{id:'ch11-open-6',title:'Design mindset',level:'retrieval',kind:'concept',q:'How should a service opening be treated structurally?',choices:['As a deliberate discontinuity requiring local web-strength and stability checks','As structurally invisible','As an automatic stiffener','As a replacement for a diaphragm'],answer:0,explanation:'Openings alter the web load path and must be included explicitly in design.',source:S}
]);
add('11:Hybrid Plate Girders',[
{id:'ch11-hybrid-1',title:'Meaning of hybrid',level:'foundation',kind:'definition',q:'What makes the plate girder described in this chapter “hybrid”?',choices:['Different steel strengths are used in different parts of the cross-section','It combines steel and timber in every case','It has two webs only','It has no welds'],answer:0,explanation:'A hybrid girder uses different steel grades in the web and flanges to suit their different structural roles.',source:S},
{id:'ch11-hybrid-2',title:'Typical strength layout',level:'foundation',kind:'recognition',q:'Which strength arrangement does the chapter specifically describe for a hybrid plate girder?',choices:['Higher-strength flanges with a lower-strength web','Higher-strength web with no flanges','Identical grades are mandatory','Aluminium flanges with timber web'],answer:0,explanation:'Higher-strength steel is especially valuable in the flanges where flexural stress is high.',source:S},
{id:'ch11-hybrid-3',title:'Why strong flanges?',level:'core',kind:'reasoning',q:'Why is higher-strength steel particularly useful in the flanges?',choices:['Flanges carry most of the bending resistance','Flanges carry all web shear buckling','Flanges determine steel density','Flanges eliminate support reactions'],answer:0,explanation:'Bending normal stresses are concentrated in the flanges.',source:S},
{id:'ch11-hybrid-4',title:'Web behaviour',level:'core',kind:'reasoning',q:'Why may a lower-strength web still be efficient in a hybrid girder?',choices:['Web design depends strongly on shear and slender-plate buckling behaviour, not flange yield strength alone','The web carries no force','The web is always concrete','Yield strength has no effect anywhere'],answer:0,explanation:'The web role and governing stability phenomena differ from the flange role.',source:S},
{id:'ch11-hybrid-5',title:'Material efficiency',level:'application',kind:'concept',q:'What is the intended economic benefit of hybrid construction?',choices:['Place higher-strength material where it gives the most structural benefit','Use the most expensive steel everywhere','Eliminate fabrication','Make all plates thicker'],answer:0,explanation:'Hybrid design matches material strength more closely to demand.',source:S},
{id:'ch11-hybrid-6',title:'Design caution',level:'retrieval',kind:'reasoning',q:'Why can a hybrid girder not be designed by checking flange strength only?',choices:['Web shear, slenderness and buckling still require independent verification','The web has no structural function','Only corrosion matters','Different steel grades remove all stability checks'],answer:0,explanation:'Hybrid material selection does not remove web stability or force-transfer requirements.',source:S}
]);
add('11:Welding of Girder Components',[
{id:'ch11-weld-1',title:'Web-flange joint',level:'foundation',kind:'concept',q:'What is the main structural purpose of the web-to-flange weld?',choices:['Transfer longitudinal shear and integrate the plates into one girder','Increase steel yield strength','Act only as corrosion protection','Prevent every form of buckling by itself'],answer:0,explanation:'The connection must transfer force between web and flange so the built-up cross-section acts together.',source:S},
{id:'ch11-weld-2',title:'Weld sizing',level:'core',kind:'reasoning',q:'Why does the chapter generally avoid oversizing web-to-flange fillet welds?',choices:['Welds should be no larger than structurally required because excess weld metal adds cost and heat effects','Larger welds always reduce strength to zero','Small welds eliminate fatigue','Weld size has no structural relevance'],answer:0,explanation:'Efficient fabrication uses the weld size required for force transfer rather than unnecessary excess.',source:S},
{id:'ch11-weld-3',title:'Automatic welding',level:'core',kind:'recognition',q:'What fabrication method is preferred where practical for long continuous plate-girder welds?',choices:['Continuous automatic welding','Random intermittent tack welding only','Adhesive bonding only','Hand drilling without welding'],answer:0,explanation:'The chapter favours continuous automatic welding where practical for repetitive long joints.',source:S},
{id:'ch11-weld-4',title:'Bearing stiffener fit',level:'core',kind:'reasoning',q:'Why must a bearing stiffener fit tightly at the flange carrying a concentrated load?',choices:['To provide an effective direct force path for the concentrated reaction or load','To change the flange steel grade','To prevent longitudinal shear entirely','To make the web opening larger'],answer:0,explanation:'Bearing stiffeners transfer concentrated forces into the web and need proper bearing/detailing at the loaded flange.',source:S},
{id:'ch11-weld-5',title:'Tension-flange detail',level:'application',kind:'reasoning',q:'Why may an intermediate transverse stiffener stop short of the tension flange?',choices:['A weld there can create an undesirable fatigue- or fracture-sensitive detail','The stiffener must never connect to the web','The tension flange carries no force','It increases elastic modulus'],answer:0,explanation:'The chapter notes that avoiding this weld can improve fatigue and brittle-fracture performance.',source:S},
{id:'ch11-weld-6',title:'Force path check',level:'retrieval',kind:'concept',q:'What should govern weld layout in a plate girder?',choices:['The actual force transfer required between web, flanges and stiffeners','A fixed decorative pattern','Steel density','Only ease of painting'],answer:0,explanation:'Connection design follows the structural load path as well as fabrication practicality.',source:S}
]);
add('11:Proportioning of the Section',[
{id:'ch11-prop-1',title:'Multiple objectives',level:'foundation',kind:'concept',q:'Which set best describes the goals of plate-girder proportioning?',choices:['Strength, stiffness, stability and economy','Only minimum weight','Only maximum depth','Only web thickness'],answer:0,explanation:'A satisfactory plate girder must satisfy several structural and practical criteria simultaneously.',source:S},
{id:'ch11-prop-2',title:'Vertical stiffness',level:'core',kind:'classification',q:'Which service behaviour is strongly related to vertical flexural stiffness?',choices:['Deflection','Corrosion rate','Weld chemistry','Bolt pretension'],answer:0,explanation:'Adequate flexural stiffness is needed to control vertical deflection.',source:S},
{id:'ch11-prop-3',title:'Lateral stiffness',level:'core',kind:'reasoning',q:'Why is lateral stiffness important in plate-girder proportioning?',choices:['It helps control compression-flange lateral instability','It removes web shear','It increases density','It eliminates reactions'],answer:0,explanation:'The compression flange and overall girder require adequate lateral stability.',source:S},
{id:'ch11-prop-4',title:'Web area',level:'core',kind:'reasoning',q:'Why must adequate web area be provided even if the flanges are very strong?',choices:['The web carries most of the vertical shear','The web carries no force','The web only paints the girder','Flange strength automatically provides shear area'],answer:0,explanation:'Flexural capacity in the flanges does not replace web shear capacity.',source:S},
{id:'ch11-prop-5',title:'Minimum weight trap',level:'application',kind:'reasoning',q:'Why can a minimum-weight design fail to be a minimum-cost design?',choices:['Extra stiffeners, welds and fabrication complexity can outweigh steel-weight savings','Steel weight has no cost','Fabrication cost is always zero','Erection is independent of geometry'],answer:0,explanation:'Fabrication and erection costs are important economic variables.',source:S},
{id:'ch11-prop-6',title:'Balanced section',level:'retrieval',kind:'concept',q:'What characterizes a well-proportioned plate girder?',choices:['No single avoidable weakness in bending, shear, stability or serviceability dominates unnecessarily','Every plate is as thick as possible','The web and flanges have equal thickness by rule','Stiffeners are always omitted'],answer:0,explanation:'Economical design balances the required functions rather than maximizing one component.',source:S}
]);
add('11:Plate Girders with Corrugated Webs',[
{id:'ch11-corr-1',title:'Corrugation form',level:'foundation',kind:'recognition',q:'How is a corrugated web geometrically different from a flat web?',choices:['It has repeated waves or folds such as trapezoidal or sinusoidal corrugations','It is a solid circular bar','It has no thickness','It is made only from concrete'],answer:0,explanation:'The web plate is cold-formed into a repeated corrugated profile before assembly.',source:S},
{id:'ch11-corr-2',title:'Primary benefit',level:'foundation',kind:'concept',q:'What is a principal structural benefit of web corrugation?',choices:['Greater out-of-plane stiffness and improved shear-buckling resistance','Higher steel modulus','No need for flanges','Zero shear stress'],answer:0,explanation:'Corrugation stiffens the thin web against out-of-plane buckling.',source:S},
{id:'ch11-corr-3',title:'Stiffener substitution',level:'core',kind:'reasoning',q:'Why can corrugated webs often avoid conventional transverse stiffeners?',choices:['The corrugation itself provides web stability','The web carries no shear','The flanges become infinitely stiff','The girder is no longer a beam'],answer:0,explanation:'The repeated folds act as geometric stiffening of the web.',source:S},
{id:'ch11-corr-4',title:'Bending role',level:'core',kind:'classification',q:'In the chapter model for a corrugated-web girder, which elements provide the primary bending resistance?',choices:['The flanges','Only the corrugated web','Only the welds','Only diaphragms'],answer:0,explanation:'The web is treated primarily as a shear-resisting element while the flanges resist bending.',source:S},
{id:'ch11-corr-5',title:'Buckling modes',level:'application',kind:'concept',q:'What stability issue must still be checked for a corrugated web?',choices:['Local and global web buckling modes','Only Euler buckling of the whole building','No buckling is possible','Only flange corrosion'],answer:0,explanation:'Corrugation improves stability but does not eliminate local or global buckling checks.',source:S},
{id:'ch11-corr-6',title:'Design logic',level:'retrieval',kind:'reasoning',q:'What makes a corrugated web an alternative to a flat stiffened web?',choices:['Geometry supplies web stiffening that would otherwise require separate stiffeners','It changes the steel grade automatically','It removes shear force','It eliminates fabrication'],answer:0,explanation:'The corrugated shape provides stiffness through form rather than added transverse plates.',source:S}
]);
add('11:Box Girders',[
{id:'ch11-box-1',title:'Closed section',level:'foundation',kind:'recognition',q:'What geometric feature distinguishes a box girder from an open I-shaped plate girder?',choices:['It forms a closed cross-section','It has no webs','It has no flanges','It is always solid'],answer:0,explanation:'The closed cell is the key to the box girder torsional behaviour.',source:S},
{id:'ch11-box-2',title:'Torsional advantage',level:'foundation',kind:'concept',q:'What major stiffness advantage does a closed box provide?',choices:['High torsional stiffness','Zero bending stiffness','Zero shear strength','No thermal expansion'],answer:0,explanation:'Closed thin-walled sections are much more efficient in torsion than comparable open sections.',source:S},
{id:'ch11-box-3',title:'Curved bridge use',level:'core',kind:'reasoning',q:'Why are box girders attractive for horizontally curved bridges?',choices:['Curvature and eccentric loading create torsional demand that the closed box resists efficiently','Curved bridges have no bending','The box removes all reactions','Only open sections can twist'],answer:0,explanation:'High torsional stiffness is especially useful where geometry induces significant torsion.',source:S},
{id:'ch11-box-4',title:'Plate behaviour',level:'core',kind:'concept',q:'Which thin-plate phenomena remain important in box-girder design?',choices:['Buckling and shear lag','Only corrosion colour','Only bolt pitch','No plate effects'],answer:0,explanation:'The closed form is torsionally efficient, but its slender plates still require stability and stress-distribution checks.',source:S},
{id:'ch11-box-5',title:'Diaphragm role',level:'application',kind:'reasoning',q:'Why are diaphragms important in box girders?',choices:['They help maintain cross-sectional shape and distribute concentrated/support forces','They change steel modulus','They eliminate web plates','They carry only paint'],answer:0,explanation:'Diaphragms stabilize the box and transfer local forces through the closed section.',source:S},
{id:'ch11-box-6',title:'Application retrieval',level:'retrieval',kind:'classification',q:'Which loading situation most clearly benefits from a box girder over an open plate girder?',choices:['Large eccentric or torsional demand','Pure axial tension in a cable','A nonstructural partition','A masonry wall'],answer:0,explanation:'The defining advantage of the box is its torsional efficiency.',source:S}
]);
add('11:Steel Plate Shear Walls (SPSW)',[
{id:'ch11-spsw-1',title:'System role',level:'foundation',kind:'concept',q:'What structural role does the thin steel infill plate play in an SPSW system?',choices:['It forms the lateral-load-resisting web of the frame','It acts only as cladding with no force','It replaces all boundary members','It carries gravity only'],answer:0,explanation:'The infill plate participates directly in lateral resistance.',source:S},
{id:'ch11-spsw-2',title:'Post-buckling action',level:'foundation',kind:'concept',q:'After buckling, how can a thin SPSW plate continue resisting lateral load?',choices:['Through diagonal tension-field action','Through hydrostatic compression','By becoming a rigid concrete wall','By carrying no stress'],answer:0,explanation:'The thin plate develops a diagonal tensile membrane field under lateral loading.',source:S},
{id:'ch11-spsw-3',title:'Boundary members',level:'core',kind:'reasoning',q:'Why must the surrounding beams and columns be sufficiently strong and stiff?',choices:['They anchor and equilibrate the infill tension field','They make the steel plate corrosion-proof','They eliminate all cyclic loading','They carry no force'],answer:0,explanation:'The tension field can develop only if the boundary frame provides adequate anchorage and equilibrium.',source:S},
{id:'ch11-spsw-4',title:'Analogy',level:'core',kind:'reasoning',q:'Which plate-girder concept most closely explains SPSW post-buckling behaviour?',choices:['Tension-field action in a slender web panel','Euler buckling of a pin-ended column only','Plastic hinge in a solid shaft','Bearing of a base plate'],answer:0,explanation:'Both systems exploit diagonal membrane tension after thin-plate buckling.',source:S},
{id:'ch11-spsw-5',title:'Cyclic response',level:'application',kind:'concept',q:'What type of loading context makes SPSW post-buckling behaviour particularly relevant?',choices:['Lateral cyclic loading such as building sway demands','Only permanent hydrostatic pressure','Only axial prestress','No lateral load'],answer:0,explanation:'The chapter discusses thin infill behaviour as part of a lateral-force-resisting building system.',source:S},
{id:'ch11-spsw-6',title:'Whole-system design',level:'retrieval',kind:'reasoning',q:'Why should an SPSW not be designed as an isolated steel plate alone?',choices:['Its resistance depends on interaction with the surrounding boundary elements','The plate has no strength','The frame is decorative only','The plate carries only gravity'],answer:0,explanation:'The system action is a coupled plate-and-boundary-frame mechanism.',source:S}
]);
add('11:Examples',[
{id:'ch11-ex-1',title:'Worked-example scope',level:'foundation',kind:'classification',q:'Which topic is repeatedly included in the Chapter 11 worked examples?',choices:['Web shear buckling and stiffener checks','Only steel density','Only paint thickness','Only bolt-hole diameter'],answer:0,explanation:'The examples integrate shear buckling, tension field action, stiffener checks and ordinary flexural design.',source:S},
{id:'ch11-ex-2',title:'Beyond first buckling',level:'core',kind:'reasoning',q:'Why do the examples distinguish first web buckling from ultimate shear resistance?',choices:['A stiffened slender web may carry additional load through post-buckling action','Buckling never occurs','Ultimate shear is always lower than zero','The web carries no shear'],answer:0,explanation:'The examples demonstrate both pre-buckling and post-buckling behaviour where permitted.',source:S},
{id:'ch11-ex-3',title:'Stiffener spacing',level:'core',kind:'application',q:'Why can changing transverse stiffener spacing change a web shear result?',choices:['It changes the web panel geometry and therefore buckling behaviour','It changes steel density','It removes bending moment','It changes the span automatically'],answer:0,explanation:'Panel aspect ratio and dimensions affect shear-buckling resistance and tension-field action.',source:S},
{id:'ch11-ex-4',title:'Iterative design',level:'application',kind:'reasoning',q:'Why may a complete plate-girder example require more than one trial section?',choices:['Depth, web slenderness, flange area and stiffener arrangement interact','Only one section is legally permitted','Steel properties change after each calculation','Reactions are unknown until painting'],answer:0,explanation:'Plate girder design is iterative because changing one component changes several checks.',source:S},
{id:'ch11-ex-5',title:'Check sequence',level:'application',kind:'sequence',q:'After choosing trial web and flange dimensions, what kind of verification must follow?',choices:['Strength, web stability, stiffeners and connections','Only member weight','Only flange colour','Only fabrication drawing scale'],answer:0,explanation:'A trial section is not complete until all relevant limit states and force transfers are verified.',source:S},
{id:'ch11-ex-6',title:'Learning objective',level:'retrieval',kind:'concept',q:'What is the main value of the Chapter 11 worked examples?',choices:['They show how separate bending, shear, stability and detailing rules combine in one girder design','They replace the need to understand force flow','They prove all girders use the same dimensions','They focus only on terminology'],answer:0,explanation:'The worked examples demonstrate integrated application of the chapter procedures.',source:S}
]);
add('11:Summary',[
{id:'ch11-sum-1',title:'Central division',level:'foundation',kind:'retrieval',q:'What is the basic plate-girder force division emphasized in the summary?',choices:['Flanges mainly resist bending and the web mainly resists shear','Web mainly resists bending and flanges mainly resist shear','Stiffeners resist all actions','Welds resist all global loads'],answer:0,explanation:'The efficient allocation of flexural and shear functions is central to the chapter.',source:S},
{id:'ch11-sum-2',title:'Thin-web strategy',level:'core',kind:'reasoning',q:'Why can the web be made relatively thin in an economical plate girder?',choices:['Stiffeners and post-buckling behaviour can be used to control slender-web stability','The web has no structural role','Thin steel cannot buckle','Flanges carry all shear'],answer:0,explanation:'Thin webs save material but require explicit stability and stiffener design.',source:S},
{id:'ch11-sum-3',title:'Related systems',level:'core',kind:'classification',q:'Which system is presented as a related application of thin-plate shear behaviour?',choices:['Steel plate shear wall','Prestressed concrete slab only','Timber roof truss only','Masonry arch'],answer:0,explanation:'The chapter connects plate-girder web mechanics to SPSW tension-field behaviour.',source:S},
{id:'ch11-sum-4',title:'Alternative web form',level:'core',kind:'recognition',q:'Which plate-girder form uses geometry instead of conventional transverse stiffeners to improve web stability?',choices:['Corrugated-web girder','Solid circular shaft','Tension rod','Plain rolled angle'],answer:0,explanation:'Corrugation provides out-of-plane web stiffness through its folded shape.',source:S},
{id:'ch11-sum-5',title:'Torsion option',level:'application',kind:'classification',q:'Which girder form is especially useful where torsional stiffness is important?',choices:['Box girder','Open flat bar','Tie rod','Single plate only'],answer:0,explanation:'A closed box section provides high torsional stiffness.',source:S},
{id:'ch11-sum-6',title:'Chapter synthesis',level:'retrieval',kind:'concept',q:'Which phrase best summarizes Chapter 11?',choices:['Fabricate an efficient deep flexural member while deliberately managing slender-plate stability and force transfer','Use maximum plate thickness everywhere','Ignore buckling after checking yield stress','Treat web, flange and stiffeners as unrelated parts'],answer:0,explanation:'The chapter integrates beam action, thin-plate stability, stiffeners, welding and alternative girder forms.',source:S}
]);
add('11:Exercises',[
{id:'ch11-exr-1',title:'Exercise emphasis',level:'foundation',kind:'concept',q:'What do the Chapter 11 exercises primarily require?',choices:['Integrated calculation and design rather than terminology alone','Only memorization of definitions','Only drawing section shapes','Only material chemistry'],answer:0,explanation:'The exercise set combines proportioning, resistance and stability checks.',source:S},
{id:'ch11-exr-2',title:'Buckling task',level:'core',kind:'classification',q:'Which calculation belongs directly to the Chapter 11 exercise scope?',choices:['Web shear-buckling resistance','Concrete shrinkage strain only','Soil consolidation only','Timber moisture content'],answer:0,explanation:'Web shear buckling and stiffener design are major exercise themes.',source:S},
{id:'ch11-exr-3',title:'Tension-field task',level:'core',kind:'concept',q:'What must be understood before using tension-field resistance in an exercise?',choices:['The web has buckled in shear but remains anchored by an adequate surrounding panel frame','The web is completely unloaded','The flanges have been removed','The girder carries axial tension only'],answer:0,explanation:'Tension-field action is a post-buckling mechanism requiring suitable boundaries.',source:S},
{id:'ch11-exr-4',title:'Iteration trigger',level:'application',kind:'reasoning',q:'If a trial web is too slender for the selected stiffener arrangement, what type of response is appropriate?',choices:['Revise web thickness, depth or stiffener arrangement and recheck','Ignore the failed check','Increase paint thickness','Reduce Young’s modulus'],answer:0,explanation:'The exercises are intentionally iterative because the design variables interact.',source:S},
{id:'ch11-exr-5',title:'Compare alternatives',level:'application',kind:'reasoning',q:'Why might an exercise compare stiffened and unstiffened web solutions?',choices:['To assess structural adequacy and economy of different stability strategies','Because both must always have identical weight','Because stiffeners change steel grade','Because unstiffened webs carry no shear'],answer:0,explanation:'Alternative proportioning strategies can satisfy the same demand with different weight and fabrication implications.',source:S},
{id:'ch11-exr-6',title:'Integrated outcome',level:'retrieval',kind:'concept',q:'What competency should a student gain from completing the plate-girder exercises?',choices:['Ability to proportion and verify a complete girder across flexure, shear, stability and detailing','Ability to memorize one equation only','Ability to ignore fabrication','Ability to size flanges without a web'],answer:0,explanation:'The exercise set is intended to build complete design competence.',source:S}
]);
add('11:Review Questions',[
{id:'ch11-rev-1',title:'Beam versus plate girder',level:'foundation',kind:'retrieval',q:'What fundamental distinction should you be able to state after reviewing Chapter 11?',choices:['A plate girder is a custom built-up deep flexural member, unlike a fixed catalogue rolled beam','A plate girder carries no shear','A rolled beam has no flange','Only plate girders are made from steel'],answer:0,explanation:'The review begins with the purpose and structural form of plate girders.',source:S},
{id:'ch11-rev-2',title:'Web buckling recall',level:'core',kind:'retrieval',q:'What is the key instability associated with a deep slender plate-girder web under high shear?',choices:['Shear buckling','Lateral buckling of a cable','Concrete crushing','Timber splitting'],answer:0,explanation:'Shear buckling and its post-buckling response are central review topics.',source:S},
{id:'ch11-rev-3',title:'Stiffener recall',level:'core',kind:'classification',q:'Which two broad stiffener roles should be distinguished?',choices:['Improving web-panel stability and carrying/localizing concentrated forces','Increasing steel density and changing yield stress','Replacing flanges and replacing welds','Only architectural decoration'],answer:0,explanation:'Intermediate and bearing/load-carrying stiffeners address different structural needs.',source:S},
{id:'ch11-rev-4',title:'Opening recall',level:'core',kind:'reasoning',q:'Why does a web opening deserve special review?',choices:['It interrupts web shear and tension-field force paths','It always strengthens the web','It removes bending from the girder','It has no structural effect'],answer:0,explanation:'Openings can significantly reduce slender-web shear and post-buckling performance.',source:S},
{id:'ch11-rev-5',title:'Alternative forms',level:'application',kind:'classification',q:'Which pairing is correct?',choices:['Corrugated web — geometric web stiffening; box girder — high torsional stiffness','Corrugated web — no shear; box girder — no bending','Hybrid girder — identical steel grades; SPSW — gravity-only system','Box girder — open section; SPSW — compression-only plate'],answer:0,explanation:'The alternative forms each address different efficiency or stability objectives.',source:S},
{id:'ch11-rev-6',title:'Final retrieval',level:'retrieval',kind:'concept',q:'Which chain best represents the complete Chapter 11 design logic?',choices:['Actions → trial geometry → flange/web resistance → plate stability/stiffeners → connections/detailing → serviceability/economy','Paint → density → colour → span','Flange only → finish','Web only → ignore supports'],answer:0,explanation:'A complete plate-girder design follows the force path from global actions through member resistance, stability and detailing.',source:S}
]);
})();
