Object.assign(window.REVISION_BANK,{
'13:Second-order Moments in Beam-columns':[
{id:'steel26-pdelta-local',title:'Second-order moment amplification',level:'core',kind:'formula',q:'For a compression member carrying axial force P with lateral deflection Δ, the basic additional second-order moment is approximately:',choices:['PΔ','P/Δ','EIΔ','PΔ/L²'],answer:0,explanation:'Axial load acting through the displaced geometry creates an additional moment PΔ, which amplifies first-order bending.',math:'M_{II}\\approx M_I+P\\Delta',source:'N. Subramanian Ch.13 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-pdelta-significance',title:'When second-order effects grow',level:'application',kind:'reasoning',q:'Second-order effects become more significant when a beam-column is:',choices:['Slender and heavily compressed','Very stocky with negligible axial load','Unloaded','Subjected only to uniform temperature'],answer:0,explanation:'Large axial compression and low lateral stiffness increase geometric nonlinearity and moment amplification.',source:'N. Subramanian Ch.13 topic + supplemental textbook-aligned practice (model-generated)'}
],
'13:Beam-column under Biaxial Loading':[
{id:'steel26-biaxial',title:'Biaxial beam-column action',level:'foundation',kind:'concept',q:'A beam-column under biaxial loading simultaneously carries:',choices:['Axial force plus bending about both principal axes','Only torsion','Only shear in one direction','Pure tension without bending'],answer:0,explanation:'Biaxial beam-columns combine axial load with moments about two orthogonal axes.',source:'N. Subramanian Ch.13 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-biax-interaction',title:'Why interaction equations are needed',level:'core',kind:'reasoning',q:'Why are interaction equations used for biaxially bent compression members?',choices:['Because axial compression and bending demands consume strength simultaneously','Because each action is completely independent','Because bending eliminates buckling','Because axial force changes steel density'],answer:0,explanation:'Combined actions cannot generally be checked independently at full capacity; interaction expressions represent shared resistance.',source:'N. Subramanian Ch.13 topic + supplemental textbook-aligned practice (model-generated)'}
],
'14:Purlins, Girts, and Eave Strut':[
{id:'steel26-purlin-role',title:'Purlin structural role',level:'foundation',kind:'concept',q:'In an industrial steel building, a roof purlin primarily:',choices:['Supports roof sheeting and transfers roof loads to primary frames or trusses','Supports foundations','Carries crane wheel loads directly','Acts only as architectural cladding'],answer:0,explanation:'Purlins are secondary roof members spanning between primary frames or trusses and supporting roof sheeting.',source:'N. Subramanian Ch.14 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-purlin-biax',title:'Why inclined purlins can bend biaxially',level:'application',kind:'reasoning',q:'A purlin on a sloping roof may experience biaxial bending because:',choices:['Gravity load has components about both section axes depending on orientation','Young’s modulus differs in x and y for structural steel','The purlin carries no shear','Roof slope eliminates bending'],answer:0,explanation:'The load resolved relative to the purlin section can produce bending about both principal axes.',source:'N. Subramanian Ch.14 topic + supplemental textbook-aligned practice (model-generated)'}
],
'14:Plane Trusses':[
{id:'steel26-truss-action',title:'Ideal truss member action',level:'foundation',kind:'concept',q:'Under the ideal pin-jointed truss assumption with loads applied at joints, members carry primarily:',choices:['Axial tension or compression','Pure bending only','Pure torsion only','Hydrostatic pressure'],answer:0,explanation:'Ideal truss members are two-force members, so internal action is axial.',source:'N. Subramanian Ch.14 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-truss-depth',title:'Truss depth and chord force',level:'application',kind:'reasoning',q:'For a given global bending moment, increasing truss depth generally tends to:',choices:['Reduce chord axial forces','Increase chord axial forces proportionally','Eliminate web forces completely','Make member length zero'],answer:0,explanation:'Chord force is broadly related to moment divided by truss depth, so greater depth can reduce required chord force.',math:'N_{chord}\\sim\\frac{M}{h}',source:'N. Subramanian Ch.14 topic + supplemental textbook-aligned practice (model-generated)'}
],
'15:Corrosion-protection Methods':[
{id:'steel26-corrosion-barrier',title:'Barrier protection principle',level:'foundation',kind:'concept',q:'Paint systems protect structural steel primarily by:',choices:['Separating steel from moisture and aggressive species','Increasing Young’s modulus','Eliminating all residual stress','Making steel stainless throughout its thickness'],answer:0,explanation:'Barrier coatings reduce contact between the steel surface and the environment needed for electrochemical corrosion.',source:'N. Subramanian Ch.15 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-galvanic',title:'Sacrificial zinc protection',level:'core',kind:'concept',q:'Galvanizing provides corrosion protection partly because zinc:',choices:['Can act sacrificially and preferentially corrode to protect exposed steel','Has infinite strength','Prevents all thermal expansion','Eliminates oxygen from air'],answer:0,explanation:'Zinc coatings provide both barrier protection and sacrificial electrochemical protection at small coating defects.',source:'N. Subramanian Ch.15 topic + supplemental textbook-aligned practice (model-generated)'}
],
'16:Mechanical Properties of Steel at Elevated Temperatures':[
{id:'steel26-fire-E',title:'Elastic modulus at high temperature',level:'foundation',kind:'concept',q:'As structural steel temperature rises substantially in fire, its elastic modulus generally:',choices:['Decreases','Increases without bound','Remains exactly constant','Becomes unrelated to temperature'],answer:0,explanation:'Elevated temperatures reduce stiffness as well as strength, increasing deformations and instability susceptibility.',source:'N. Subramanian Ch.16 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-fire-strength',title:'Strength reduction consequence',level:'application',kind:'reasoning',q:'Why can a steel member fail in fire even if the applied mechanical load does not increase?',choices:['Material strength and stiffness reduce as temperature rises','Dead load disappears','Steel density becomes zero','Connections become infinitely rigid'],answer:0,explanation:'Thermal degradation reduces resistance while thermal expansion and restraint can add further demand.',source:'N. Subramanian Ch.16 topic + supplemental textbook-aligned practice (model-generated)'}
],
'16:Passive Protection for Steelwork':[
{id:'steel26-passive',title:'Purpose of passive fire protection',level:'foundation',kind:'concept',q:'The main purpose of passive fire protection around steelwork is to:',choices:['Slow the rate at which steel temperature rises','Increase room ventilation','Increase permanent load','Prevent any thermal expansion'],answer:0,explanation:'Insulation or protective systems delay heat transfer so the steel retains adequate properties for longer.',source:'N. Subramanian Ch.16 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-sectionfactor',title:'Section factor intuition',level:'core',kind:'reasoning',q:'All else equal, a steel member with a large exposed perimeter relative to its steel volume tends to:',choices:['Heat more rapidly in fire','Heat more slowly regardless of protection','Remain at ambient temperature','Gain yield strength'],answer:0,explanation:'A high heated perimeter-to-volume (or mass) ratio exposes more surface for heat input per unit steel, increasing heating rate.',source:'N. Subramanian Ch.16 topic + supplemental textbook-aligned practice (model-generated)'}
],
'17:Stress Methods':[
{id:'steel26-fatigue-range',title:'Stress range in fatigue',level:'foundation',kind:'formula',q:'For cyclic stress varying between σ_max and σ_min, the stress range is:',choices:['Δσ=σ_max−σ_min','Δσ=(σ_max+σ_min)/2','Δσ=σ_maxσ_min','Δσ=σ_max/σ_min'],answer:0,explanation:'Fatigue design commonly uses the repeated stress range, the difference between maximum and minimum stress in a cycle.',math:'\\Delta\\sigma=\\sigma_{max}-\\sigma_{min}',source:'N. Subramanian Ch.17 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-fatigue-detail',title:'Detail category matters',level:'core',kind:'reasoning',q:'Why can two members made from the same steel grade have very different fatigue strengths?',choices:['Connection geometry, weld details and stress concentrations strongly affect crack initiation and growth','Fatigue depends only on yield strength','Member length is the only variable','Steel grade removes all notch effects'],answer:0,explanation:'Fatigue resistance is highly detail-sensitive; welded attachments and geometric discontinuities can dominate performance.',source:'N. Subramanian Ch.17 topic + supplemental textbook-aligned practice (model-generated)'}
],
'17:Fatigue Assessment for Variable Stress Ranges':[
{id:'steel26-miner',title:'Miner cumulative damage',level:'core',kind:'formula',q:'Miner’s linear cumulative-damage rule is commonly expressed as:',choices:['Σ(n_i/N_i)≤1','Σ(n_iN_i)=0','Σ(N_i/n_i)=1 always','Δσ/E=1'],answer:0,explanation:'Each stress-range block consumes a fraction n_i/N_i of fatigue life, and the fractions are summed.',math:'D=\\sum_i\\frac{n_i}{N_i}',source:'N. Subramanian Ch.17 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-variable',title:'Why variable amplitude needs accumulation',level:'application',kind:'reasoning',q:'A variable-amplitude fatigue history cannot be represented adequately by only the largest stress range because:',choices:['Many lower-amplitude cycles can cumulatively consume fatigue life','Small cycles always cause zero damage','Only mean stress matters','Cycle count is irrelevant'],answer:0,explanation:'Fatigue damage accumulates over repeated cycles at different stress ranges, so both range and number of cycles matter.',source:'N. Subramanian Ch.17 topic + supplemental textbook-aligned practice (model-generated)'}
],
'18:Shear Centre':[
{id:'steel26-shearcentre',title:'Load through shear centre',level:'foundation',kind:'concept',q:'A transverse load applied through the shear centre of a thin-walled section ideally produces:',choices:['Bending without twisting from that load','Pure torsion only','No bending moment','Uniform axial tension only'],answer:0,explanation:'The shear centre is the point through which transverse load can act without inducing twist of the section.',source:'N. Subramanian Ch.18 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-sc-sym',title:'Shear centre and symmetry',level:'core',kind:'reasoning',q:'For a doubly symmetric I-section, the shear centre lies:',choices:['At the centroid where the two symmetry axes intersect','At the top flange tip','Outside the section by definition','At any arbitrary point'],answer:0,explanation:'For doubly symmetric sections, symmetry places the shear centre at the centroid.',source:'N. Subramanian Ch.18 topic + supplemental textbook-aligned practice (model-generated)'}
],
'18:Torsional Deformations':[
{id:'steel26-twist',title:'St Venant twist rate',level:'core',kind:'formula',q:'For uniform St Venant torsion of a prismatic member, twist rate is related to torque T by:',choices:['dθ/dx=T/(GJ)','dθ/dx=GJT','dθ/dx=EI/T','dθ/dx=T/(EA)'],answer:0,explanation:'Torsional rigidity GJ relates torque to rate of twist for uniform St Venant torsion.',math:'\\frac{d\\theta}{dx}=\\frac{T}{GJ}',source:'N. Subramanian Ch.18 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel26-twist-length',title:'Twist grows with length',level:'application',kind:'formula',q:'For constant T, G and J over member length L, total St Venant twist is:',choices:['θ=TL/(GJ)','θ=T/(GJL)','θ=GJL/T','θ=TJ/(GL)'],answer:0,explanation:'Integrating the constant twist rate T/(GJ) over length L gives total twist TL/(GJ).',math:'\\theta=\\frac{TL}{GJ}',source:'N. Subramanian Ch.18 topic + supplemental textbook-aligned practice (model-generated)'}
]
});