(() => {
const add={
'1:Introduction':[
{id:'c1-intro-compare',title:'Material is not the whole design',level:'core',kind:'reasoning',q:'Two structures use the same steel grade but different structural forms. Can their structural performance still differ?',choices:['Yes, structural form is also a fundamental design choice','No, steel grade alone fixes all behaviour','Only paint changes performance','Only fabrication date matters'],answer:0,explanation:'The chapter opening treats both structural form and material as basic design choices, so identical material does not imply identical structural behaviour.',source:'Subramanian Ch.1 Introduction'},
{id:'c1-intro-recall',title:'Opening chapter retrieval',level:'retrieval',kind:'concept',q:'Which statement best captures why steel is introduced alongside other structural materials?',choices:['Material selection must suit the structural form and performance requirements','Steel is mandatory for every structure','Other materials cannot carry load','Material selection is unrelated to design'],answer:0,explanation:'The introduction places steel among several structural materials and frames selection around required structural performance.',source:'Subramanian Ch.1 Introduction'}
],
'1:Historical Development':[
{id:'c1-hist-transition',title:'From iron to steel',level:'core',kind:'sequence',q:'What broad historical transition does the chapter trace?',choices:['Cast/wrought iron use evolving into modern structural steel production','Steel being replaced completely by timber','Concrete production evolving into ironmaking','Welding being replaced by mining'],answer:0,explanation:'The historical discussion follows the progression from earlier iron products toward modern steel and large-scale steelmaking.',source:'Subramanian Ch.1 Historical Development'},
{id:'c1-hist-scale',title:'Production scale consequence',level:'application',kind:'reasoning',q:'Why did industrial-scale steelmaking change structural engineering practice?',choices:['It made structural steel available in large quantities for widespread construction','It eliminated the need for connections','It made all structures statically determinate','It removed the need for rolling'],answer:0,explanation:'Large-scale production made steel practical as a widely available structural material rather than a limited specialty material.',source:'Subramanian Ch.1 Historical Development'}
],
'1:Processes Used for Iron and Steel Making':[
{id:'c1-process-product',title:'Production chain output',level:'core',kind:'reasoning',q:'Why are casting and rolling discussed after steelmaking?',choices:['They turn produced steel into usable structural products and shapes','They convert steel back into ore','They determine wind load','They are forms of corrosion protection'],answer:0,explanation:'The chapter presents casting and rolling as downstream operations that convert steel into structural products.',source:'Subramanian Ch.1 Processes Used for Iron and Steel Making'},
{id:'c1-process-retrieve',title:'Manufacturing route retrieval',level:'retrieval',kind:'sequence',q:'Which stage comes before rolling structural sections in the chapter production sequence?',choices:['Steelmaking','Painting the completed building','Structural analysis','Foundation excavation'],answer:0,explanation:'Steel must first be produced before it can be cast and rolled into structural shapes.',source:'Subramanian Ch.1 Processes Used for Iron and Steel Making'}
],
'1:Iron and Steel in India':[
{id:'c1-india-system',title:'Integrated production logic',level:'core',kind:'reasoning',q:'Why is the word “integrated” important when describing a steel plant?',choices:['Several production stages are combined within one industrial system','Only one operation is performed','The plant only fabricates finished buildings','It refers only to computer integration'],answer:0,explanation:'The chapter uses integrated steel plants to describe facilities that combine multiple stages of iron and steel production.',source:'Subramanian Ch.1 Iron and Steel in India'},
{id:'c1-india-retrieve',title:'India context retrieval',level:'retrieval',kind:'concept',q:'What is the main structural-engineering relevance of the chapter discussion on Indian steel production?',choices:['Availability of steel underpins construction and infrastructure development','It determines only architectural style','It replaces material testing','It removes the need for design standards'],answer:0,explanation:'The section connects the steel industry and its production capacity with construction and infrastructure needs.',source:'Subramanian Ch.1 Iron and Steel in India'}
],
'1:Metallurgy of Steel':[
{id:'c1-met-link',title:'Structure-property link',level:'core',kind:'reasoning',q:'What chain of reasoning is central to the metallurgy section?',choices:['Composition and thermal history influence microstructure, which influences engineering properties','Member span determines crystal structure directly','Paint colour determines toughness','Loads determine chemical composition'],answer:0,explanation:'The metallurgy discussion connects internal structure and phase behaviour with strength, ductility, toughness and other properties.',source:'Subramanian Ch.1 Metallurgy of Steel'},
{id:'c1-met-retrieve',title:'Metallurgy retrieval',level:'retrieval',kind:'concept',q:'Which topic belongs directly to steel metallurgy rather than structural analysis?',choices:['Crystal and phase structure of iron-carbon alloys','Bending-moment distribution in a frame','Wind pressure on cladding','Bolt-group eccentricity'],answer:0,explanation:'Crystal and phase structure are material-level topics used to explain steel behaviour in the metallurgy section.',source:'Subramanian Ch.1 Metallurgy of Steel'}
],
'1:Alloying Elements in Steel':[
{id:'c1-alloy-not-one',title:'No single-property view',level:'core',kind:'reasoning',q:'Why is selecting alloying additions not simply a matter of maximizing strength?',choices:['Alloying can affect toughness, ductility, corrosion behaviour and weldability as well as strength','Alloying affects only colour','Every alloying element has the same effect','Strength is unrelated to composition'],answer:0,explanation:'The chapter discusses alloying as a way to alter several engineering properties, so material selection involves trade-offs.',source:'Subramanian Ch.1 Alloying Elements in Steel'},
{id:'c1-alloy-retrieve',title:'Alloying retrieval',level:'retrieval',kind:'classification',q:'Which property can be influenced by alloying according to the chapter?',choices:['Weldability','Member support condition','Bay spacing','Applied wind direction'],answer:0,explanation:'Composition and alloy additions influence fabrication-related behaviour including weldability.',source:'Subramanian Ch.1 Alloying Elements in Steel'}
],
'1:Chemical Composition of Steel':[
{id:'c1-chem-performance',title:'Chemistry to performance',level:'core',kind:'reasoning',q:'A steel grade satisfies dimensional requirements but has unsuitable weldability. What chapter topic explains why this can happen?',choices:['Chemical composition of the steel','Beam span alone','Section depth alone','Paint system alone'],answer:0,explanation:'Chemical composition affects weldability and cracking susceptibility, so dimensions alone cannot describe fabrication performance.',source:'Subramanian Ch.1 Chemical Composition of Steel'},
{id:'c1-chem-retrieve',title:'Composition retrieval',level:'retrieval',kind:'concept',q:'What does the carbon-equivalent idea condense into a useful engineering indicator?',choices:['The combined influence of chemical composition on weldability','The geometric slenderness of a member','The mass density of the section','The corrosion coating thickness'],answer:0,explanation:'The chapter introduces carbon-equivalent concepts to summarize composition effects relevant to weldability.',source:'Subramanian Ch.1 Chemical Composition of Steel'}
],
'1:Types of Structural Steel':[
{id:'c1-types-match',title:'Match steel to demand',level:'core',kind:'reasoning',q:'Why might two projects legitimately specify different structural-steel families even if both require adequate strength?',choices:['They may have different toughness, corrosion, fabrication or fire-performance requirements','Steel type affects only colour','All structural steels are identical','Only density can differ'],answer:0,explanation:'The chapter distinguishes steel families because projects demand different combinations of structural and durability properties.',source:'Subramanian Ch.1 Types of Structural Steel'},
{id:'c1-types-retrieve',title:'Steel family retrieval',level:'retrieval',kind:'classification',q:'Which pair are both presented as distinct structural-steel categories?',choices:['Weathering steel and stainless steel','Concrete and timber','Brick and glass','Soil and grout'],answer:0,explanation:'Weathering and stainless steels are among the steel types discussed for different performance needs.',source:'Subramanian Ch.1 Types of Structural Steel'}
],
'1:Mechanical Properties of Steel':[
{id:'c1-mech-property-choice',title:'Choose the right property',level:'application',kind:'reasoning',q:'If concern is resistance to sudden fracture with energy absorption, which property is most relevant?',choices:['Toughness','Density','Thermal conductivity','Coefficient of friction only'],answer:0,explanation:'Toughness describes the ability to absorb energy before fracture and is distinct from yield strength or hardness.',source:'Subramanian Ch.1 Mechanical Properties of Steel'},
{id:'c1-mech-retrieve2',title:'Mechanical-property retrieval',level:'retrieval',kind:'concept',q:'Which pair are both read directly from the tensile stress-strain behaviour discussed in the chapter?',choices:['Yield behaviour and ultimate tensile strength','Wind speed and seismic zone','Bolt pitch and weld throat','Soil pressure and water table'],answer:0,explanation:'The tensile stress-strain curve is used to discuss yielding, ultimate strength, ductility and related material response.',source:'Subramanian Ch.1 Mechanical Properties of Steel'}
],
'1:Residual Stresses':[
{id:'c1-res-equilibrium2',title:'Residual-stress equilibrium',level:'core',kind:'reasoning',q:'What must be true of a residual-stress pattern in an unloaded member?',choices:['Its internal tensile and compressive effects are self-equilibrating','It must create a net external force','It must be uniformly tensile everywhere','It can exist only with an applied load'],answer:0,explanation:'Residual stresses remain without external loading because the internal stress field is self-equilibrating.',source:'Subramanian Ch.1 Residual Stresses'},
{id:'c1-res-retrieve2',title:'Residual-stress retrieval',level:'retrieval',kind:'classification',q:'Which process is specifically associated with residual stresses in structural steel?',choices:['Nonuniform heating and cooling during welding','Measuring member length','Applying paint to a cold surface','Reading a drawing'],answer:0,explanation:'Welding and other nonuniform thermal or forming processes can leave locked-in residual stresses.',source:'Subramanian Ch.1 Residual Stresses'}
],
'1:Stress Concentration':[
{id:'c1-sc-flow',title:'Disturbed stress flow',level:'core',kind:'reasoning',q:'Why does a hole or sharp notch create a local stress peak?',choices:['It disturbs the otherwise smoother transmission of stress through the material','It increases Young’s modulus locally','It removes all load from the section','It makes stress perfectly uniform'],answer:0,explanation:'Geometric discontinuities disturb the stress field and create localized peaks around the discontinuity.',source:'Subramanian Ch.1 Stress Concentration'},
{id:'c1-sc-retrieve',title:'Stress-concentration retrieval',level:'retrieval',kind:'application',q:'Which detail would most directly prompt a stress-concentration check?',choices:['A sharp re-entrant corner or hole','A long uniform prismatic region with no discontinuity','A change in drawing scale','A painted flat surface'],answer:0,explanation:'Abrupt geometry changes such as holes and notches are classic sources of stress concentration.',source:'Subramanian Ch.1 Stress Concentration'}
],
'1:Cold Work and Strain Hardening':[
{id:'c1-cold-tradeoff',title:'Cold-work trade-off',level:'core',kind:'reasoning',q:'Why can cold working improve one property while making another less favourable?',choices:['Strain hardening can raise yield strength while reducing ductility','Cold work makes all properties identical','Cold work removes plastic deformation','Cold work always lowers strength to zero'],answer:0,explanation:'The chapter notes that cold work and strain hardening can increase strength but may reduce ductility and introduce residual effects.',source:'Subramanian Ch.1 Cold Work and Strain Hardening'},
{id:'c1-cold-retrieve',title:'Cold-work retrieval',level:'retrieval',kind:'concept',q:'What mechanism explains the increased yield level after prior plastic deformation at low temperature?',choices:['Strain hardening','Elastic unloading only','Corrosion allowance','Thermal insulation'],answer:0,explanation:'The section identifies strain hardening as the reason plastic deformation can raise subsequent yield strength.',source:'Subramanian Ch.1 Cold Work and Strain Hardening'}
],
'1:Structural Steel Products':[
{id:'c1-prod-selection',title:'Product selection logic',level:'application',kind:'reasoning',q:'Why might a designer choose a hollow section rather than an angle or plate even when all are steel?',choices:['Section form and properties must suit the structural role and fabrication needs','All steel products have identical section properties','Product geometry never affects behaviour','Only paint availability matters'],answer:0,explanation:'The chapter surveys different products because geometry, section properties, availability and fabrication influence selection.',source:'Subramanian Ch.1 Structural Steel Products'},
{id:'c1-prod-retrieve',title:'Product retrieval',level:'retrieval',kind:'classification',q:'Which list contains only structural-steel product forms discussed in the chapter?',choices:['Plate, angle, channel, I/H section, hollow section','Brick, timber, glass, gypsum','Sand, aggregate, cement, water','Soil, rock, grout, clay'],answer:0,explanation:'Plates, rolled sections and hollow sections are among the structural-steel products surveyed.',source:'Subramanian Ch.1 Structural Steel Products'}
],
'1:Cold-formed Steel Sections':[
{id:'c1-cfs-thin',title:'Thin-wall implication',level:'core',kind:'reasoning',q:'What design consequence follows directly from cold-formed sections being made from relatively thin sheet?',choices:['Local buckling becomes especially important','Elastic modulus becomes zero','Connections are unnecessary','Yield strength is irrelevant'],answer:0,explanation:'Thin, slender plate elements make local buckling a key consideration for cold-formed members.',source:'Subramanian Ch.1 Cold-formed Steel Sections'},
{id:'c1-cfs-retrieve',title:'Cold-formed retrieval',level:'retrieval',kind:'concept',q:'How are cold-formed steel sections distinguished from ordinary hot-rolled structural shapes in the chapter?',choices:['They are formed from relatively thin sheet at room temperature','They are cast as concrete members','They are always solid circular bars','They are produced only by welding thick plates'],answer:0,explanation:'Cold-formed sections are produced by forming relatively thin sheet at room temperature.',source:'Subramanian Ch.1 Cold-formed Steel Sections'}
],
'1:High-performance Steel':[
{id:'c1-hps-balance',title:'Performance combination',level:'core',kind:'reasoning',q:'Why does “high-performance” steel not simply mean “highest strength steel”?',choices:['The concept combines strength with properties such as toughness, fabrication and durability performance','Only density defines performance','It means stainless steel only','It means no design checks are required'],answer:0,explanation:'The chapter presents high-performance steel as a balanced combination of useful structural and durability/fabrication properties.',source:'Subramanian Ch.1 High-performance Steel'},
{id:'c1-hps-retrieve',title:'High-performance retrieval',level:'retrieval',kind:'concept',q:'Which objective is consistent with high-performance steel?',choices:['Achieve a useful combination of strength, toughness and durability/fabrication qualities','Maximize density regardless of behaviour','Eliminate all structural analysis','Use one grade for every environment'],answer:0,explanation:'High-performance steel is selected for a broader property package rather than strength alone.',source:'Subramanian Ch.1 High-performance Steel'}
],
'1:Stainless Steel':[
{id:'c1-ss-passive',title:'Passive protection idea',level:'core',kind:'reasoning',q:'What material feature underlies the corrosion resistance emphasized for stainless steel?',choices:['Chromium-rich passive surface behaviour','Very high density','Zero thermal expansion','Absence of iron'],answer:0,explanation:'The chapter attributes stainless-steel corrosion resistance mainly to chromium-related passive behaviour.',source:'Subramanian Ch.1 Stainless Steel'},
{id:'c1-ss-retrieve',title:'Stainless-steel retrieval',level:'retrieval',kind:'reasoning',q:'Why cannot stainless steel simply be designed exactly like ordinary carbon steel in every respect?',choices:['Its material response, cost and design/fabrication characteristics differ','It has no stress-strain curve','It cannot carry structural load','It has zero stiffness'],answer:0,explanation:'The chapter notes stainless steel has distinct stress-strain behaviour and design considerations despite its durability advantages.',source:'Subramanian Ch.1 Stainless Steel'}
],
'1:Advantages of Steel as a Structural Material':[
{id:'c1-adv-balance',title:'Advantages with limitations',level:'core',kind:'reasoning',q:'Why does the chapter discuss corrosion, fire and buckling in a section about steel advantages?',choices:['A realistic material choice must balance strengths with known limitations','Those issues prove steel cannot be structural','Advantages are unrelated to design','Steel never needs protection'],answer:0,explanation:'The chapter presents steel positively but also acknowledges limitations that must be addressed by design and protection.',source:'Subramanian Ch.1 Advantages of Steel as a Structural Material'},
{id:'c1-adv-retrieve',title:'Steel advantage retrieval',level:'retrieval',kind:'classification',q:'Which pair are genuine advantages emphasized for structural steel?',choices:['High strength-to-weight ratio and prefabrication/rapid erection','No corrosion and no buckling','Zero fire sensitivity and zero maintenance','Infinite stiffness and zero mass'],answer:0,explanation:'High strength relative to weight and suitability for prefabrication and rapid erection are among the chapter’s listed benefits.',source:'Subramanian Ch.1 Advantages of Steel as a Structural Material'}
],
'1:Types of Steel Structures':[
{id:'c1-struct-action',title:'Classify by action',level:'core',kind:'classification',q:'Which pairing correctly matches a common structural member with its primary action?',choices:['Beam — bending','Tie — compression only','Column — pure bending only','Plate girder — no shear'],answer:0,explanation:'The chapter relates structural members to actions such as tension, compression, bending and combined action.',source:'Subramanian Ch.1 Types of Steel Structures'},
{id:'c1-struct-retrieve',title:'Structure-type retrieval',level:'retrieval',kind:'classification',q:'Which is an example of a steel structural system discussed in the chapter?',choices:['Truss or portal frame','Only unreinforced masonry wall','Only timber joist floor','Only plain concrete block'],answer:0,explanation:'Buildings, bridges, portal frames, trusses, towers and storage structures are among the steel systems illustrated.',source:'Subramanian Ch.1 Types of Steel Structures'}
],
'1:Aluminium Alloys':[
{id:'c1-al-modulus',title:'Lower stiffness implication',level:'core',kind:'reasoning',q:'Why can an aluminium member require different deflection or buckling consideration from a geometrically similar steel member?',choices:['Aluminium has a much lower modulus of elasticity','Aluminium has infinite stiffness','Steel and aluminium have identical E','Aluminium has zero strength'],answer:0,explanation:'The chapter highlights aluminium’s lower elastic modulus as an important structural design difference from steel.',source:'Subramanian Ch.1 Aluminium Alloys'},
{id:'c1-al-retrieve',title:'Aluminium retrieval',level:'retrieval',kind:'concept',q:'Which combination best reflects the chapter comparison of aluminium with steel?',choices:['Lower density and good corrosion resistance, but lower elastic modulus','Higher density and identical modulus','No corrosion resistance and no formability','Infinite strength and zero expansion'],answer:0,explanation:'Aluminium is presented as a light, corrosion-resistant structural metal with lower stiffness and different design behaviour.',source:'Subramanian Ch.1 Aluminium Alloys'}
],
'1:Fabrication and Erection':[
{id:'c1-fab-tolerance',title:'Why tolerances matter',level:'core',kind:'reasoning',q:'Why are fabrication accuracy and tolerances structurally important?',choices:['Errors can accumulate and interfere with assembly and erection','They affect only drawing appearance','Steel components always self-correct on site','Tolerance has no relation to fit-up'],answer:0,explanation:'The chapter notes that dimensional accuracy matters because fabrication errors can propagate into site assembly.',source:'Subramanian Ch.1 Fabrication and Erection'},
{id:'c1-fab-retrieve',title:'Fabrication retrieval',level:'retrieval',kind:'sequence',q:'Which sequence is most consistent with structural-steel delivery?',choices:['Fabrication operations → transport → site erection','Erection → mining → rolling','Painting → structural analysis → ore extraction','Foundation demolition → alloying → drilling'],answer:0,explanation:'The chapter describes shop fabrication followed by transport and site erection.',source:'Subramanian Ch.1 Fabrication and Erection'}
],
'1:Aesthetics of Steel Structures':[
{id:'c1-aes-logic',title:'Structure and appearance',level:'core',kind:'reasoning',q:'How can structural efficiency contribute to architectural quality in exposed steelwork?',choices:['Clear proportions, member forms and connections can express the structural logic','Only heavier members are attractive','Connections should always be hidden regardless of concept','Structural layout has no visual effect'],answer:0,explanation:'The chapter argues that structural logic, proportion and detailing can reinforce the visual quality of steel structures.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'},
{id:'c1-aes-retrieve',title:'Aesthetic retrieval',level:'retrieval',kind:'classification',q:'Which design choice can influence the aesthetics of an exposed steel structure?',choices:['Connection detailing','Steel density alone','Only the construction date','Only the soil classification'],answer:0,explanation:'Member proportion, exposed framing and connection detailing are among the aesthetic considerations discussed.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'}
],
'1:Composite Construction':[
{id:'c1-comp-action',title:'Why combine materials?',level:'core',kind:'reasoning',q:'What is the structural idea behind composite construction?',choices:['Use different materials together so their useful properties contribute to the member/system response','Prevent any force transfer between materials','Use steel only as decoration','Make the materials act independently by definition'],answer:0,explanation:'The chapter introduces composite construction as deliberate combined action between materials such as steel and concrete.',source:'Subramanian Ch.1 Composite Construction'},
{id:'c1-comp-retrieve',title:'Composite retrieval',level:'retrieval',kind:'concept',q:'Which pairing is most characteristic of the composite construction discussed?',choices:['Steel and concrete acting together','Timber and glass with no force transfer','Soil and paint','Air and water only'],answer:0,explanation:'Steel-concrete composite action is the principal structural combination introduced in the chapter.',source:'Subramanian Ch.1 Composite Construction'}
],
'1:Summary':[
{id:'c1-summary-link',title:'Chapter 1 integration',level:'core',kind:'reasoning',q:'Which chain best summarizes the chapter’s overall logic?',choices:['Production/composition → material properties → products/fabrication → structural applications','Paint colour → soil type → rainfall → member size','Wind load → chemistry → mining → aesthetics','Only one topic matters: density'],answer:0,explanation:'Chapter 1 links how steel is made and composed to its properties, products, fabrication and structural use.',source:'Subramanian Ch.1 Summary'},
{id:'c1-summary-retrieve',title:'Summary retrieval',level:'retrieval',kind:'concept',q:'Which subject is NOT outside the scope of Chapter 1?',choices:['Residual stresses and stress concentration','Detailed reinforced-concrete slab design','Hydraulic pipe-network analysis','Soil consolidation settlement'],answer:0,explanation:'Residual stresses and stress concentration are explicit Chapter 1 topics in the steel-material overview.',source:'Subramanian Ch.1 Summary'}
],
'1:Review Questions':[
{id:'c1-review-purpose',title:'Review-question purpose',level:'core',kind:'reasoning',q:'What is the best way to use the Chapter 1 review questions in a revision course?',choices:['As retrieval practice that reconnects material production, properties and structural use','As a substitute for all source reading','Only as memorization of page numbers','To avoid checking understanding'],answer:0,explanation:'The review section is intended to test recall and understanding across the chapter’s major material and structural concepts.',source:'Subramanian Ch.1 Review Questions'},
{id:'c1-review-retrieve',title:'Chapter 1 checkpoint',level:'retrieval',kind:'concept',q:'Which statement would be a sound Chapter 1 review conclusion?',choices:['Steel behaviour and structural suitability depend on production, composition, properties, product form and fabrication','All steels behave identically regardless of composition or processing','Fabrication has no effect on structural steel','Material selection is unrelated to structural performance'],answer:0,explanation:'The chapter repeatedly links manufacture and material properties with fabrication and structural application.',source:'Subramanian Ch.1 Review Questions'}
]
};
window.REVISION_BANK=window.REVISION_BANK||{};
for(const [k,v] of Object.entries(add)) window.REVISION_BANK[k]=[...(window.REVISION_BANK[k]||[]),...v];
})();
