Object.assign(window.REVISION_BANK,{
'13:Second-order Moments in Beam-columns':[
{id:'steel4-pdelta',title:'Second-order moment',level:'core',kind:'formula',q:'For an axially compressed beam-column with lateral displacement Δ, the additional second-order moment is approximately:',choices:['PΔ','P/Δ','EIΔ','VΔ²'],answer:0,explanation:'Axial force acting through the lateral offset produces an additional destabilizing P-Delta moment.',math:'M_{2}\\approx P\\Delta',source:'Subramanian Ch.13 topic inventory + standard beam-column bridge (source-grounding pending)'},
{id:'steel4-secondorder-growth',title:'Why second-order effects grow',level:'application',kind:'reasoning',q:'As axial compression approaches the member buckling load, second-order moment amplification generally:',choices:['Increases','Decreases to zero','Remains exactly 1.0','Becomes independent of stiffness'],answer:0,explanation:'Higher axial compression magnifies the effect of lateral displacement and reduces effective stability.',source:'Subramanian Ch.13 topic inventory + standard beam-column bridge (source-grounding pending)'}
],
'13:Beam-column under Biaxial Loading':[
{id:'steel4-biaxial',title:'Biaxial beam-column action',level:'foundation',kind:'concept',q:'A beam-column under biaxial loading resists:',choices:['Axial force plus bending about both principal axes','Shear only','Torsion only','Axial tension only with no bending'],answer:0,explanation:'Biaxial beam-columns combine compression or tension with moments about both section axes.',source:'Subramanian Ch.13 topic inventory + standard beam-column bridge (source-grounding pending)'},
{id:'steel4-interaction',title:'Interaction-check idea',level:'core',kind:'concept',q:'Why are interaction equations used for biaxial beam-columns?',choices:['Because axial force and the two bending moments consume capacity simultaneously','Because each action is always independent','To compute only self-weight','To eliminate stability checks'],answer:0,explanation:'Combined actions must be checked together because the available resistance to one action is affected by the others.',source:'Subramanian Ch.13 topic inventory + standard design bridge (source-grounding pending)'}
],
'14:Purlins, Girts, and Eave Strut':[
{id:'steel4-purlin-role',title:'Purlin role',level:'foundation',kind:'concept',q:'The primary role of a roof purlin is to:',choices:['Support roof sheeting and transfer loads to main frames/trusses','Support foundations','Act as a column base','Carry only crane wheel load'],answer:0,explanation:'Purlins are secondary roof members spanning between primary frames or trusses.',source:'Subramanian Ch.14 topic inventory + standard industrial-building bridge (source-grounding pending)'},
{id:'steel4-girt-role',title:'Girt role',level:'foundation',kind:'concept',q:'A wall girt primarily supports:',choices:['Wall cladding','Roof ridge only','Column base plate','Crane rail only'],answer:0,explanation:'Girts are secondary horizontal wall members transferring cladding loads to the primary frame.',source:'Subramanian Ch.14 topic inventory + standard industrial-building bridge (source-grounding pending)'}
],
'14:Plane Trusses':[
{id:'steel4-truss-action',title:'Ideal truss-member action',level:'foundation',kind:'concept',q:'In an ideal pin-jointed plane truss with loads applied at joints, members carry primarily:',choices:['Axial force','Pure bending only','Torsion only','Plate shear'],answer:0,explanation:'The pin-jointed idealization makes each member a two-force member carrying tension or compression.',source:'Subramanian Ch.14 topic inventory + standard truss bridge (source-grounding pending)'},
{id:'steel4-truss-stability',title:'Triangulation',level:'core',kind:'reasoning',q:'Why is triangulation fundamental in plane trusses?',choices:['A triangle is geometrically stable without changing member lengths','It eliminates axial force','It guarantees zero deflection','It removes all support reactions'],answer:0,explanation:'Triangulation provides geometric stability for pin-jointed assemblies.',source:'Subramanian Ch.14 topic inventory + standard truss bridge (source-grounding pending)'}
],
'15:Corrosion of Steel':[
{id:'steel4-corrosion-cell',title:'Electrochemical corrosion',level:'foundation',kind:'concept',q:'Ordinary atmospheric corrosion of carbon steel is fundamentally:',choices:['An electrochemical process involving anodic and cathodic reactions','A purely mechanical buckling process','A fatigue crack only','A thermal expansion effect'],answer:0,explanation:'Corrosion requires electrochemical reactions, typically aided by moisture and oxygen.',source:'Subramanian Ch.15 topic inventory + standard durability bridge (source-grounding pending)'},
{id:'steel4-sectionloss',title:'Structural effect of corrosion',level:'application',kind:'reasoning',q:'Progressive corrosion can reduce structural capacity mainly because it:',choices:['Removes effective cross-sectional area and can create local pits','Increases Young’s modulus','Eliminates residual stress','Always improves ductility'],answer:0,explanation:'Material loss reduces area and section properties; localized pitting may also intensify stress concentration.',source:'Subramanian Ch.15 topic inventory + standard durability bridge (source-grounding pending)'}
],
'15:Corrosion-protection Methods':[
{id:'steel4-coating',title:'Barrier protection',level:'foundation',kind:'concept',q:'A protective paint system primarily reduces corrosion by:',choices:['Separating steel from moisture/oxygen/electrolyte','Increasing member slenderness','Reducing yield strength','Creating more exposed steel'],answer:0,explanation:'Barrier coatings interrupt contact between steel and the corrosive environment.',source:'Subramanian Ch.15 topic inventory + standard durability bridge (source-grounding pending)'},
{id:'steel4-galvanizing',title:'Galvanizing principle',level:'core',kind:'concept',q:'Hot-dip galvanizing protects steel using a coating rich in:',choices:['Zinc','Copper','Concrete','Lead only'],answer:0,explanation:'Zinc provides both barrier protection and sacrificial electrochemical protection.',source:'Subramanian Ch.15 topic inventory + standard durability bridge (source-grounding pending)'}
],
'16:Calculation of Temperature Rise in Steel Members':[
{id:'steel4-fire-sectionfactor',title:'Section factor in fire',level:'core',kind:'concept',q:'For similar exposure, a steel member with a larger exposed-perimeter-to-volume ratio tends to:',choices:['Heat up faster','Heat up slower in every case','Stay at ambient temperature','Lose no strength'],answer:0,explanation:'A high section factor means more heated surface relative to thermal mass, generally increasing heating rate.',math:'A_m/V',source:'Subramanian Ch.16 topic inventory + standard fire-engineering bridge (source-grounding pending)'},
{id:'steel4-specificheat',title:'Thermal inertia',level:'application',kind:'reasoning',q:'Greater thermal mass generally causes steel temperature to rise:',choices:['More slowly for the same net heat input','Instantly','At a rate independent of section size','Only after yielding'],answer:0,explanation:'More energy is required to raise the temperature of a member with greater mass and heat capacity.',source:'Subramanian Ch.16 topic inventory + standard fire-engineering bridge (source-grounding pending)'}
],
'16:Mechanical Properties of Steel at Elevated Temperatures':[
{id:'steel4-hot-strength',title:'Strength at elevated temperature',level:'foundation',kind:'concept',q:'As structural steel temperature becomes very high during fire, its yield strength generally:',choices:['Reduces','Increases without limit','Remains exactly unchanged','Becomes irrelevant to design'],answer:0,explanation:'Elevated temperatures degrade both strength and stiffness, requiring temperature-dependent reduction factors in fire design.',source:'Subramanian Ch.16 topic inventory + standard fire-engineering bridge (source-grounding pending)'},
{id:'steel4-hot-e',title:'Elastic modulus in fire',level:'core',kind:'reasoning',q:'The modulus of elasticity of steel at high fire temperatures generally:',choices:['Reduces','Doubles','Remains constant at all temperatures','Becomes negative'],answer:0,explanation:'Loss of elastic stiffness increases deformation and can worsen stability during fire.',source:'Subramanian Ch.16 topic inventory + standard fire-engineering bridge (source-grounding pending)'}
],
'17:Fatigue Loading':[
{id:'steel4-fatigue-range',title:'Stress range',level:'core',kind:'formula',q:'For a fatigue cycle with maximum stress σ_max and minimum stress σ_min, the stress range is:',choices:['σ_max−σ_min','σ_max+σ_min','σ_max/σ_min only','(σ_max−σ_min)²'],answer:0,explanation:'Fatigue design commonly uses the fluctuation range between maximum and minimum stress.',math:'\\Delta\\sigma=\\sigma_{max}-\\sigma_{min}',source:'Subramanian Ch.17 topic inventory + standard fatigue bridge (source-grounding pending)'},
{id:'steel4-cycles',title:'Why repeated cycles matter',level:'foundation',kind:'concept',q:'Fatigue failure can occur at stresses below static yield because:',choices:['Repeated cycling can initiate and propagate cracks','Steel has no elastic range','Yield strength becomes zero after one cycle','Static strength is unrelated to material'],answer:0,explanation:'Damage accumulates through crack initiation and growth under repeated stress fluctuations.',source:'Subramanian Ch.17 topic inventory + standard fatigue bridge (source-grounding pending)'}
],
'17:Factors Affecting Fatigue Life':[
{id:'steel4-detail-category',title:'Detail geometry and fatigue',level:'core',kind:'reasoning',q:'Which detail is generally more fatigue-sensitive?',choices:['A sharp welded geometric discontinuity','A smooth gradual transition','A perfectly uniform unnotched plate','A member with no cyclic stress'],answer:0,explanation:'Stress concentrations and weld-detail geometry strongly influence fatigue crack initiation.',source:'Subramanian Ch.17 topic inventory + standard fatigue bridge (source-grounding pending)'},
{id:'steel4-meanstress',title:'Stress history matters',level:'application',kind:'concept',q:'Fatigue life depends strongly on:',choices:['Stress range, number of cycles and detail category','Only member mass','Only paint colour','Only Young’s modulus'],answer:0,explanation:'Repeated stress range and connection/detail quality are central fatigue-design variables.',source:'Subramanian Ch.17 topic inventory + standard fatigue bridge (source-grounding pending)'}
],
'18:Distortion of Thin Walled Members':[
{id:'steel4-distortional',title:'Distortional response',level:'foundation',kind:'concept',q:'Distortion of a thin-walled open section under torsion means:',choices:['The cross-sectional shape changes rather than remaining rigid','The section translates with no strain','Only axial shortening occurs','All shear stress vanishes'],answer:0,explanation:'Thin-walled sections can warp and distort because the cross-section is not perfectly rigid under torsional loading.',source:'Subramanian Ch.18 topic inventory + standard torsion bridge (source-grounding pending)'},
{id:'steel4-stiffener',title:'Torsional stiffening',level:'application',kind:'reasoning',q:'Diaphragms or torsional stiffeners can help by:',choices:['Restraining cross-sectional distortion and warping','Reducing steel modulus','Increasing unbraced length','Removing all bending stiffness'],answer:0,explanation:'Appropriate restraints improve torsional behaviour by limiting distortion/warping at critical locations.',source:'Subramanian Ch.18 topic inventory + standard torsion bridge (source-grounding pending)'}
]
});