Object.assign(window.REVISION_BANK,{
'4:Elastic Analysis':[
{id:'elastic-analysis',title:'Elastic analysis meaning',level:'foundation',kind:'concept',q:'What is assumed in first-order elastic structural analysis?',choices:['Material remains elastic and equilibrium is written on the undeformed geometry','Plastic hinges form immediately','Member stiffness is zero','Loads are ignored'],answer:0,explanation:'First-order elastic analysis assumes linear elastic response and small-displacement geometry.',source:'Subramanian Ch.4'},
{id:'superposition',title:'Superposition condition',level:'core',kind:'reasoning',q:'When is superposition valid in structural analysis?',choices:['For a linear system','For any strongly nonlinear system','Only after collapse','Only when loads are zero'],answer:0,explanation:'Superposition requires linear governing equations and linear response.',source:'Subramanian Ch.4'}
],
'4:Second-Order Inelastic Analyses':[
{id:'second-order',title:'Second-order effects',level:'foundation',kind:'concept',q:'What do second-order effects account for?',choices:['Additional actions caused by loads acting through deformed geometry','Only material density','Only weld shrinkage','Only dead load'],answer:0,explanation:'P-Δ and P-δ effects arise because equilibrium is influenced by deformation.',source:'Subramanian Ch.4'},
{id:'inelastic',title:'Inelastic response',level:'core',kind:'concept',q:'What does an inelastic analysis allow that a purely elastic one does not?',choices:['Material yielding and stiffness degradation','Infinite stiffness','Zero strain','No equilibrium checks'],answer:0,explanation:'Inelastic analysis can represent yielding and redistribution beyond the elastic range.',source:'Subramanian Ch.4'}
],
'6:Types and Properties of Welds':[
{id:'fillet-weld',title:'Fillet weld geometry',level:'foundation',kind:'concept',q:'Which weld type is commonly used to join overlapping or intersecting plates without edge preparation?',choices:['Fillet weld','Butt weld only','Plug-free joint','Rivet weld'],answer:0,explanation:'Fillet welds are common in lap, tee and corner connections.',source:'Subramanian Ch.6'},
{id:'throat',title:'Effective throat',level:'core',kind:'concept',q:'In fillet-weld design, the effective throat is important because it represents:',choices:['The shortest effective load-resisting thickness through the weld','The plate gross width','The bolt shank length','The member span'],answer:0,explanation:'Design shear stress is evaluated over the effective throat area.',source:'Subramanian Ch.6'}
],
'6:Design of Welds':[
{id:'weld-strength',title:'Weld design strength idea',level:'core',kind:'reasoning',q:'For a straight fillet weld under uniform longitudinal load, weld resistance depends directly on:',choices:['Effective throat area and design weld stress','Beam span only','Young modulus only','Bolt diameter'],answer:0,explanation:'The basic resistance is stress capacity multiplied by effective throat area.',source:'Subramanian Ch.6'},
{id:'weld-length',title:'Effect of weld length',level:'application',kind:'reasoning',q:'If effective throat and allowable/design weld stress stay unchanged, doubling effective weld length ideally makes the basic uniform-load resistance:',choices:['Double','Half','One quarter','Unchanged'],answer:0,explanation:'Effective throat area is proportional to weld length.',source:'Subramanian Ch.6'}
],
'7:Slenderness Ratio':[
{id:'tension-slenderness',title:'Why limit tension-member slenderness?',level:'foundation',kind:'concept',q:'Why are slenderness limits still relevant for tension members even though Euler compression buckling is not their main strength mode?',choices:['To control handling, vibration, sag and service behaviour','Because tension members buckle elastically under pure tension','To determine concrete strength','To eliminate net-section checks'],answer:0,explanation:'Tension-member slenderness limits are mainly serviceability and robustness controls.',source:'Subramanian Ch.7'},
{id:'slenderness-form',title:'Slenderness measure',level:'core',kind:'formula',q:'Which expression is the usual geometric slenderness ratio?',choices:['L/r','r/L','A/L','I/A²'],answer:0,explanation:'Slenderness is length divided by radius of gyration.',math:'\\lambda=\\frac{L}{r}',source:'Subramanian Ch.7'}
],
'8:Cross Section Classification':[
{id:'class-purpose',title:'Why classify sections?',level:'foundation',kind:'concept',q:'Why are steel cross-sections classified by element slenderness?',choices:['Local buckling can limit the stress distribution and rotation capacity','Classification changes steel density','It determines dead load only','It removes the need for stability checks'],answer:0,explanation:'Plate-element slenderness controls whether a section can reach yield or plastic capacity before local buckling.',source:'Subramanian Ch.8'},
{id:'plastic-section',title:'Plastic section behaviour',level:'core',kind:'concept',q:'A plastic section is expected to:',choices:['Develop full plastic moment and adequate rotation for plastic analysis','Buckle locally before reaching yield anywhere','Remain fully elastic at collapse','Carry axial load only'],answer:0,explanation:'Plastic sections have sufficiently stocky elements to develop and sustain plastic moment with rotation capacity.',source:'Subramanian Ch.8'}
],
'10:Shear Strength of Steel Beams':[
{id:'beam-shear',title:'Where beam shear acts',level:'foundation',kind:'concept',q:'In a typical rolled I-section under vertical shear, most shear is carried by:',choices:['The web','The flange tips only','The neutral-axis point only','The bolts regardless of connection'],answer:0,explanation:'The web provides most of the effective shear area in an I-section.',source:'Subramanian Ch.10'},
{id:'shear-area',title:'Shear resistance trend',level:'core',kind:'reasoning',q:'All else equal, increasing effective web shear area generally causes beam shear resistance to:',choices:['Increase','Decrease','Become zero','Remain unrelated to area'],answer:0,explanation:'Basic shear resistance is proportional to effective shear area times design shear stress.',source:'Subramanian Ch.10'}
],
'10:Maximum Deflection':[
{id:'deflection-service',title:'Why check deflection?',level:'foundation',kind:'concept',q:'Beam deflection limits are mainly associated with:',choices:['Serviceability','Gross-section rupture only','Bolt bearing only','Material chemistry'],answer:0,explanation:'Excessive deflection can impair finishes, drainage, appearance and usability without causing immediate strength failure.',source:'Subramanian Ch.10'},
{id:'ei-effect',title:'Flexural rigidity effect',level:'core',kind:'reasoning',q:'For the same beam, load and span, increasing EI generally makes elastic deflection:',choices:['Smaller','Larger','Unchanged','Infinite'],answer:0,explanation:'Elastic deflection varies inversely with flexural rigidity.',source:'Subramanian Ch.10'}
],
'11:Web Panel Subjected to Shear':[
{id:'web-buckling',title:'Plate-girder web buckling',level:'foundation',kind:'concept',q:'A very slender plate-girder web under high shear is susceptible to:',choices:['Shear buckling','Euler column buckling of the flange only','Net-section rupture of bolts only','Pure torsion with no shear'],answer:0,explanation:'Thin webs can buckle in diagonal shear before material shear yielding controls.',source:'Subramanian Ch.11'},
{id:'stiffener-role',title:'Transverse stiffener role',level:'core',kind:'concept',q:'What is a key role of transverse web stiffeners in a plate girder?',choices:['Limit web-panel dimensions and improve buckling resistance','Increase concrete strength','Eliminate flange bending','Reduce steel modulus'],answer:0,explanation:'Stiffeners subdivide slender webs into panels and support shear-buckling resistance.',source:'Subramanian Ch.11'}
],
'18:Torsional Loading in Practice':[
{id:'torsion-cause',title:'Practical source of torsion',level:'foundation',kind:'concept',q:'Which situation can create torsion in a structural member?',choices:['Load acting eccentric to the shear centre','Pure concentric axial tension only','Uniform temperature with free expansion','Zero load'],answer:0,explanation:'Eccentric transverse loading can create a twisting moment.',source:'Subramanian Ch.18'},
{id:'torque',title:'Torque from eccentric load',level:'application',kind:'formula',q:'A transverse force P acts at eccentricity e from the shear centre. What torsional moment is produced?',choices:['T=Pe','T=P/e','T=P+e','T=e/P'],answer:0,explanation:'Moment equals force times perpendicular eccentricity.',math:'T=Pe',source:'Subramanian Ch.18'}
]
});