Object.assign(window.REVISION_BANK,{
'5:Introduction':[
{id:'ch5-intro-weaklink',title:'Connection as weakest link',level:'foundation',kind:'concept',q:'Why can a poor connection govern the safety of an otherwise adequate steel frame?',choices:['The load path must pass through the connection between members','Connections do not carry force','Member strength automatically repairs joint weakness','Connections affect appearance only'],answer:0,explanation:'Chapter 5 treats connections as essential parts of the structural load path; inadequate connection resistance can govern failure.',source:'Subramanian Ch.5'},
{id:'ch5-intro-actions',title:'Actions transferred',level:'core',kind:'recognition',q:'Which actions may a structural steel connection need to transfer between members?',choices:['Forces and moments','Density and temperature only','Paint thickness only','Concrete shrinkage only'],answer:0,explanation:'Connections make separate members act together by transferring the relevant forces and moments.',source:'Subramanian Ch.5'},
{id:'ch5-intro-real',title:'Real joint behaviour',level:'core',kind:'reasoning',q:'Why is real connection behaviour more complicated than an ideal pin or rigid joint?',choices:['Slip, lack of fit, residual stress, flexibility and nonlinear deformation can occur','Every connection is perfectly rigid','Bolt holes have zero clearance','Fabrication produces no imperfections'],answer:0,explanation:'The chapter highlights several physical effects that make actual joint behaviour depart from idealized models.',source:'Subramanian Ch.5'},
{id:'ch5-intro-model',title:'Use an idealized model',level:'application',kind:'reasoning',q:'Why does connection design still use simplified idealizations despite complex real behaviour?',choices:['A rational simplified model allows practical safe design of the force path','Exact behaviour is always known without calculation','Safety factors make equilibrium unnecessary','All joints behave identically'],answer:0,explanation:'Practical design idealizes the important load-transfer behaviour while retaining appropriate safety.',source:'Subramanian Ch.5'},
{id:'ch5-intro-compatible',title:'Analysis and connection compatibility',level:'application',kind:'concept',q:'What should be true of the assumed joint behaviour used in frame analysis and the connection actually detailed?',choices:['They should be compatible','They should deliberately contradict each other','The analysis should always assume a pin regardless of detail','Connection stiffness never matters'],answer:0,explanation:'The structural analysis idealization and the real connection detail must represent compatible force and rotation behaviour.',source:'Subramanian Ch.5; Chapter 5 PPT rigid and pinned connection examples'},
{id:'ch5-intro-goal',title:'Design goal',level:'retrieval',kind:'concept',q:'What practical connection-design objective is emphasized at the start of Chapter 5?',choices:['Provide reliable force transfer without the connection becoming the premature weak link','Make every connection heavier than the members','Eliminate all joint deformation','Avoid all fasteners'],answer:0,explanation:'The chapter frames connection design around safe, reliable transfer of actions between structural components.',source:'Subramanian Ch.5'}
],
'5:Rivets and Riveted Connections':[
{id:'ch5-rivet-form',title:'Rivet anatomy',level:'foundation',kind:'recognition',q:'A traditional structural rivet consists primarily of:',choices:['A ductile steel shank with a preformed head and a second head formed during installation','A threaded screw with two nuts','A hollow copper tube only','A welded stud with no head'],answer:0,explanation:'The chapter illustrates conventional rivets as ductile round shanks with one preformed head and another formed during driving.',source:'Subramanian Ch.5; Chapter 5 PPT Fig. 5.3'},
{id:'ch5-rivet-hot',title:'Hot riveting sequence',level:'core',kind:'sequence',q:'Which sequence best describes traditional hot riveting?',choices:['Heat rivet → insert through hole → form second head → allow to cool','Cool rivet → weld hole → remove head','Insert bolt → apply adhesive → drill afterwards','Cast plate around a cold rivet'],answer:0,explanation:'Hot riveting requires heating, insertion, heading and cooling.',source:'Subramanian Ch.5'},
{id:'ch5-rivet-clamp',title:'Cooling effect',level:'core',kind:'concept',q:'What useful effect occurs as a hot-driven rivet cools after installation?',choices:['Contraction develops clamping action between the connected parts','The rivet loses both heads','The hole becomes larger than the plate','The plates separate intentionally'],answer:0,explanation:'Cooling contraction of the installed hot rivet creates clamping force.',source:'Subramanian Ch.5'},
{id:'ch5-rivet-types',title:'Recognise rivet heads',level:'core',kind:'recognition',q:'Which item is shown among traditional rivet-head forms in the Chapter 5 presentation?',choices:['Snap/button head','Hexagonal nut only','Tension-control spline only','Countersunk screw without shank'],answer:0,explanation:'The Chapter 5 PPT illustrates traditional rivet forms including snap/button and countersunk heads.',source:'Chapter 5 PPT Fig. 5.3'},
{id:'ch5-rivet-decline',title:'Why riveting declined',level:'application',kind:'reasoning',q:'Which practical disadvantage helped bolting and welding replace structural riveting?',choices:['It needs heating, labour-intensive driving and difficult correction of defective rivets','It requires no labour','It cannot produce clamping','It is silent and effortless to inspect'],answer:0,explanation:'The source cites labour, noise, preheating and inspection/removal effort among reasons riveting became obsolete.',source:'Subramanian Ch.5'},
{id:'ch5-rivet-history',title:'Modern use',level:'retrieval',kind:'concept',q:'How should riveted connections mainly be viewed in modern structural-steel practice?',choices:['As historically important details largely replaced by bolting and welding','As the only permitted connection type','As a concrete reinforcement system','As a torsion-only device'],answer:0,explanation:'Rivets are important for understanding older structures but are uncommon in new structural work.',source:'Subramanian Ch.5'}
],
'5:Bolted Connections':[
{id:'ch5-bolt-black',title:'Black bolt use',level:'foundation',kind:'concept',q:'Ordinary black bolts are most suited to which situation described in the chapter?',choices:['Light structures or erection work under mainly static loading','Highly fatigue-sensitive crane connections','Connections where slip must be prevented by pretension','Aerospace fracture-critical joints'],answer:0,explanation:'The source presents ordinary black bolts as economical fasteners for light/static work and erection.',source:'Subramanian Ch.5'},
{id:'ch5-bolt-components',title:'Fastener components',level:'foundation',kind:'recognition',q:'Which set correctly identifies the visible parts of a typical structural bolt assembly shown in Chapter 5?',choices:['Hex head, shank, threads, nut and washer','Flange, web, stiffener and slab','Electrode, flux and weld toe','Pin, bearing and concrete pedestal only'],answer:0,explanation:'The Chapter 5 PPT labels the bolt head, shank, threads, nut and washer.',source:'Chapter 5 PPT Fig. 5.4'},
{id:'ch5-bolt-grade',title:'High-strength choice',level:'core',kind:'reasoning',q:'When slip resistance or fatigue performance is important, which broad bolt family does Chapter 5 favour?',choices:['High-strength preloaded/friction-grip bolts','Loose ordinary black bolts','Hot rivets only','Timber screws'],answer:0,explanation:'High-strength friction-grip bolts are used where pretension and slip resistance are important.',source:'Subramanian Ch.5'},
{id:'ch5-bolt-holes',title:'Hole type matters',level:'core',kind:'concept',q:'Why is bolt-hole type relevant to connection behaviour?',choices:['Clearance or slotted holes can influence slip and load transfer','Hole geometry cannot affect a bolted joint','A bolt never contacts a hole','All holes are exactly the bolt diameter'],answer:0,explanation:'Chapter 5 discusses standard and slotted holes because fit and movement affect connection response.',source:'Subramanian Ch.5; Chapter 5 PPT slotted-hole slides'},
{id:'ch5-bolt-dynamic',title:'Avoid black bolts for cycling',level:'application',kind:'reasoning',q:'Why are ordinary black bolts not the preferred choice for impact or repeated dynamic loading in the chapter?',choices:['Their bearing/slip-type behaviour is less suitable than preloaded high-strength bolts for such service','They are made of concrete','They cannot be tightened at all','They have no shear resistance'],answer:0,explanation:'The source specifically discourages ordinary black bolts for impact, fatigue and dynamic loading.',source:'Subramanian Ch.5'},
{id:'ch5-bolt-selection',title:'Select by behaviour',level:'retrieval',kind:'application',q:'What should primarily drive the choice between ordinary bearing bolts and HSFG bolts?',choices:['Required connection behaviour such as load type, slip resistance and fatigue demand','Member paint colour','Drawing sheet size','Site latitude alone'],answer:0,explanation:'Bolt selection follows the performance demanded of the joint.',source:'Subramanian Ch.5'}
],
'5:Behaviour of Bolted Joints':[
{id:'ch5-behav-single',title:'Single shear',level:'foundation',kind:'recognition',q:'In a simple lap joint, a bolt is commonly idealized as being in:',choices:['Single shear','Four-plane shear','Pure torsion only','No shear'],answer:0,explanation:'A lap joint normally creates one shear plane through the bolt.',source:'Subramanian Ch.5'},
{id:'ch5-behav-double',title:'Double shear',level:'core',kind:'concept',q:'Why can a bolt in a double-cover butt joint have two shear planes?',choices:['The main plate is sandwiched between cover plates so two interfaces can shear the bolt','The bolt diameter doubles','The nut creates a second bolt','Bearing disappears'],answer:0,explanation:'A double-cover butt joint produces two potential shear interfaces through the bolt.',source:'Subramanian Ch.5'},
{id:'ch5-behav-failures',title:'Failure family',level:'core',kind:'classification',q:'Which set contains failure modes relevant to a bearing-type bolted joint?',choices:['Bolt shear, bearing and net-section rupture','Concrete creep, timber splitting and soil heave','Only lateral-torsional buckling','Only weld throat rupture'],answer:0,explanation:'Chapter 5 illustrates multiple bolt and plate failure modes, including shear, bearing and section failure.',source:'Subramanian Ch.5; Chapter 5 PPT Fig. 5.13'},
{id:'ch5-behav-ecc',title:'Eccentric loading',level:'core',kind:'reasoning',q:'What additional effect appears when a load does not pass through the centroid of a bolt group?',choices:['A moment acts on the bolt group in addition to direct force','All bolt forces become zero','Only axial compression remains','The connection becomes a pin automatically'],answer:0,explanation:'Eccentricity creates a moment that must be distributed through the group.',source:'Subramanian Ch.5'},
{id:'ch5-behav-slip',title:'Initial slip mechanism',level:'application',kind:'concept',q:'What distinguishes the initial load-transfer mechanism of an HSFG joint from an ordinary bearing joint?',choices:['HSFG pretension develops interface friction before bearing-type slip occurs','HSFG bolts are intentionally loose','Ordinary bolts always use welding','HSFG bolts do not clamp plates'],answer:0,explanation:'Pretension in HSFG bolts clamps the faying surfaces and provides frictional slip resistance.',source:'Subramanian Ch.5'},
{id:'ch5-behav-combined',title:'Combined bolt actions',level:'retrieval',kind:'concept',q:'A bolt may need an interaction check when it is subjected simultaneously to:',choices:['Shear and tension','Density and colour','Temperature and paint thickness only','Only self-weight of the nut'],answer:0,explanation:'The chapter treats bolts under direct tension, shear and combined shear-plus-tension.',source:'Subramanian Ch.5'}
],
'5:Design Strength of Ordinary Black Bolts':[
{id:'ch5-black-modes',title:'Governing bolt capacity',level:'foundation',kind:'concept',q:'Why is there no single universal strength value for an ordinary black bolt in a connection?',choices:['Shear, bearing, tension and interaction can govern depending on the detail','Every bolt fails only by shear','Plate properties never matter','Bolt strength is unrelated to load direction'],answer:0,explanation:'The design checks the relevant limit states and adopts the governing capacity.',source:'Subramanian Ch.5'},
{id:'ch5-black-thread',title:'Threads in shear plane',level:'core',kind:'reasoning',q:'Why does it matter whether a bolt shear plane passes through the threaded portion?',choices:['The effective resisting area differs from that of the plain shank','Threads increase plate thickness','It changes steel density','It removes bearing from the joint'],answer:0,explanation:'Shear strength depends on whether the shear plane crosses the reduced threaded area or full shank area.',source:'Subramanian Ch.5'},
{id:'ch5-black-long',title:'Long-joint effect',level:'core',kind:'concept',q:'What does the chapter do when a bearing-bolt joint becomes sufficiently long?',choices:['Apply an appropriate reduction to reflect nonuniform load distribution','Assume every bolt carries exactly zero load','Double all bolt diameters automatically','Ignore joint length completely'],answer:0,explanation:'The textbook includes a reduction factor for long joints because force distribution is not perfectly uniform.',source:'Subramanian Ch.5'},
{id:'ch5-black-grip',title:'Large grip length',level:'core',kind:'concept',q:'Why can a large grip length require a reduction in ordinary bolt shear strength?',choices:['A long bolt grip changes deformation and load-transfer behaviour','It increases steel yield stress','It eliminates bending in the bolt','It guarantees double shear'],answer:0,explanation:'Chapter 5 includes a reduction factor for large grip lengths.',source:'Subramanian Ch.5'},
{id:'ch5-black-prying',title:'Prying action',level:'application',kind:'reasoning',q:'In a tension connection, prying action is important because it can:',choices:['Add bolt tension caused by deformation of the connected plate or flange','Remove all bolt tension','Convert steel into concrete','Eliminate connection flexibility'],answer:0,explanation:'The chapter treats prying forces as additional tension that may develop in certain connected details.',source:'Subramanian Ch.5'},
{id:'ch5-black-design',title:'Choose the governing check',level:'retrieval',kind:'application',q:'After calculating the relevant ordinary-bolt strengths, what controls design?',choices:['The least adequate governing resistance among the applicable limit states','The largest number obtained regardless of mode','Only the bolt nominal diameter','Only the plate gross area'],answer:0,explanation:'Connection design is governed by the critical applicable limit state.',source:'Subramanian Ch.5'}
],
'5:Design Strength of High Strength Friction Grip Bolts':[
{id:'ch5-hsfg-preload',title:'Purpose of pretension',level:'foundation',kind:'concept',q:'What is the primary purpose of pretensioning an HSFG bolt?',choices:['Clamp the connected plates so interface friction can resist slip','Create a loose-fit bearing joint','Reduce the number of friction interfaces to zero','Make the bolt act as a pin'],answer:0,explanation:'Pretension creates clamping force, which produces frictional resistance at the faying surfaces.',source:'Subramanian Ch.5'},
{id:'ch5-hsfg-slipfactor',title:'Slip factor',level:'core',kind:'concept',q:'Which surface property directly affects HSFG slip resistance?',choices:['Slip factor of the faying surfaces','Concrete cube strength','Bolt paint colour','Beam span only'],answer:0,explanation:'The design slip resistance depends on the slip factor of the interfaces.',source:'Subramanian Ch.5'},
{id:'ch5-hsfg-interfaces',title:'Friction interfaces',level:'core',kind:'reasoning',q:'All else equal, why can more effective friction interfaces increase HSFG slip resistance?',choices:['More clamped interfaces can contribute frictional resistance','They reduce bolt pretension to zero','They eliminate plate contact','They make hole type irrelevant'],answer:0,explanation:'The number of effective friction interfaces is one of the parameters in slip resistance.',source:'Subramanian Ch.5'},
{id:'ch5-hsfg-hole',title:'Hole factor',level:'core',kind:'concept',q:'Why does the design treatment of an HSFG bolt distinguish hole types?',choices:['Oversize or slotted holes can modify slip resistance and are represented by a hole factor','Hole type changes Young’s modulus','A hole cannot affect movement','Only standard holes exist'],answer:0,explanation:'Chapter 5 includes a hole factor in the slip-resistance calculation.',source:'Subramanian Ch.5; Chapter 5 PPT slotted-hole slides'},
{id:'ch5-hsfg-tightening',title:'Pretension control',level:'application',kind:'recognition',q:'Which device shown in the Chapter 5 presentation provides a direct indication of bolt pretension during tightening?',choices:['Direct tension indicator washer','Ordinary flat washer only','Timber wedge','Concrete spacer'],answer:0,explanation:'The PPT illustrates direct-tension-indicator tightening and the reduction of the indicator gap.',source:'Chapter 5 PPT Fig. 5.7'},
{id:'ch5-hsfg-service',title:'Service behaviour',level:'retrieval',kind:'reasoning',q:'Why are HSFG bolts attractive for fatigue-sensitive or dynamically loaded joints?',choices:['Pretension and friction reduce slip and stress fluctuations in the fastener','They are always installed loose','They rely on large hole bearing from the start','They eliminate the need for any inspection'],answer:0,explanation:'The source links HSFG bolts with slip resistance and improved fatigue/dynamic performance.',source:'Subramanian Ch.5'}
],
'5:Pin Connections':[
{id:'ch5-pin-purpose',title:'Pin idealization',level:'foundation',kind:'concept',q:'What structural behaviour is a true pin connection intended to permit?',choices:['Relative rotation with essentially negligible moment transfer','Full moment continuity with zero rotation','No shear transfer','No axial force transfer'],answer:0,explanation:'Pins are used where rotation is desired and moment transfer is intended to be negligible.',source:'Subramanian Ch.5'},
{id:'ch5-pin-machined',title:'Machined surfaces',level:'core',kind:'reasoning',q:'Why are structural pins and their holes machined smooth?',choices:['To obtain proper fit and minimize unwanted friction during rotation','To maximize roughness and lock rotation','To increase plate corrosion','To make the pin hollow'],answer:0,explanation:'The chapter notes machining to provide smooth bearing/rotation surfaces.',source:'Subramanian Ch.5'},
{id:'ch5-pin-use',title:'Application recognition',level:'core',kind:'classification',q:'Which is a typical application of a structural pin connection mentioned in the chapter?',choices:['Hinged arches or suspension-bridge links','Continuous welded pressure vessel only','Concrete slab reinforcement splice','Timber nail plate only'],answer:0,explanation:'Pins are used in hinged arches, links, bracing and bridge details where rotation is required.',source:'Subramanian Ch.5'},
{id:'ch5-pin-bearing',title:'Pin force transfer',level:'core',kind:'concept',q:'Even when a pin transfers negligible moment, which local action must still be resisted at the pin-hole interface?',choices:['Bearing','Only thermal radiation','Only torsion with no contact','No force at all'],answer:0,explanation:'A loaded pin transfers force through contact/bearing with the connected plates.',source:'Subramanian Ch.5'},
{id:'ch5-pin-not-rigid',title:'Do not confuse with rigid joint',level:'application',kind:'reasoning',q:'Which connection choice is inconsistent with a design requirement for essentially free end rotation?',choices:['A fully rigid moment connection','A properly detailed pin','A hinge detail','A pinned link'],answer:0,explanation:'A rigid moment joint restrains rotation, opposite to the intended behaviour of a pin.',source:'Subramanian Ch.5'},
{id:'ch5-pin-code',title:'Source of pin provisions',level:'retrieval',kind:'recognition',q:'According to the textbook edition, where were the pin-design provisions taken from because corresponding IS 800 provisions were unavailable there?',choices:['BS 5950','A concrete code only','A timber code only','No published source'],answer:0,explanation:'The chapter explicitly notes use of BS 5950 provisions for pin design.',source:'Subramanian Ch.5'}
],
'5:Simple Connections':[
{id:'ch5-simple-ideal',title:'Simple-joint idealization',level:'foundation',kind:'concept',q:'How is a simple beam connection idealized with respect to moment?',choices:['It transfers mainly shear and provides little moment restraint','It transfers full plastic moment','It cannot carry shear','It is infinitely stiff in rotation'],answer:0,explanation:'Simple or flexible connections are designed mainly for force/shear transfer with negligible design moment.',source:'Subramanian Ch.5'},
{id:'ch5-simple-ppt',title:'Recognise a pinned detail',level:'core',kind:'recognition',q:'Which detail is shown among the pinned connection examples in the Chapter 5 presentation?',choices:['Seated-angle beam-to-column connection','Extended end-plate moment connection only','Portal-frame haunch only','Rigid flange cover-plate connection only'],answer:0,explanation:'The PPT illustrates seated-angle and several web/end-plate details as pinned connection examples.',source:'Chapter 5 PPT Fig. 5.2'},
{id:'ch5-simple-web',title:'Web connection role',level:'core',kind:'reasoning',q:'Why are web-angle or flexible end-plate details suitable for simple beam connections?',choices:['They can transfer beam shear while allowing substantial end rotation','They are intended to transfer full plastic flange moment','They prevent all joint deformation','They eliminate bolt forces'],answer:0,explanation:'Their detailing is consistent with mainly shear transfer and limited rotational restraint.',source:'Subramanian Ch.5'},
{id:'ch5-simple-ecc',title:'Small eccentricities',level:'core',kind:'concept',q:'How are small eccentricities commonly treated in the idealized design model of a simple connection?',choices:['They may be neglected when consistent with the accepted simple-joint idealization','They always convert the joint to fully rigid','They make shear equal to zero','They are replaced by temperature load'],answer:0,explanation:'The chapter notes that practical simple-joint idealization may neglect minor eccentric effects.',source:'Subramanian Ch.5'},
{id:'ch5-simple-truss',title:'Truss joint',level:'application',kind:'concept',q:'Why is a simple connection concept often appropriate at an idealized truss joint?',choices:['The analysis assumes members meet at joints primarily transferring axial force without significant joint moment','Truss joints are always fully fixed','Trusses carry no force','Bolts cannot rotate'],answer:0,explanation:'Simple connection behaviour is compatible with the pin-jointed truss idealization.',source:'Subramanian Ch.5'},
{id:'ch5-simple-check',title:'Behaviour before label',level:'retrieval',kind:'reasoning',q:'What makes a connection “simple” in design: its appearance alone or its intended force-rotation behaviour?',choices:['Its intended force-transfer and rotational behaviour','Its paint colour','The number of drawing views','Whether it uses any steel plate'],answer:0,explanation:'Connection classification is based on structural behaviour, not appearance alone.',source:'Subramanian Ch.5'}
],
'5:Moment Resistant Connections':[
{id:'ch5-moment-purpose',title:'Moment joint role',level:'foundation',kind:'concept',q:'Why is a moment-resistant connection used in a frame?',choices:['To transfer significant bending moment and restrain relative member rotation','To guarantee zero moment transfer','To behave as a free pin','To transfer only self-weight of bolts'],answer:0,explanation:'Moment connections provide the rotational restraint required for frame action.',source:'Subramanian Ch.5'},
{id:'ch5-moment-actions',title:'Combined actions',level:'core',kind:'classification',q:'A moment-resistant beam-column connection may need to transfer:',choices:['Moment together with shear and sometimes axial force','Only temperature','Only torsion with zero shear','No structural action'],answer:0,explanation:'The connection must transfer all design actions present at the joint.',source:'Subramanian Ch.5'},
{id:'ch5-moment-ecc',title:'Eccentric load decomposition',level:'core',kind:'formula',q:'For an eccentric load P acting at eccentricity e from a bolt-group centroid, which moment is introduced?',choices:['M = Pe','M = P/e','M = e/P','M = P + e'],answer:0,explanation:'The eccentric force is represented as a concentric force plus the moment Pe.',math:'M=Pe',source:'Subramanian Ch.5'},
{id:'ch5-moment-group',title:'Bolt-group consequence',level:'core',kind:'reasoning',q:'In an eccentrically loaded bolt group, why do all bolts not generally carry identical resultant force?',choices:['The moment component distributes additional force according to bolt position relative to the group centroid','Every bolt is unloaded by the moment','Eccentricity affects only plate colour','Moment is carried by concrete only'],answer:0,explanation:'The direct force and moment-induced force combine differently at different bolt locations.',source:'Subramanian Ch.5'},
{id:'ch5-moment-details',title:'Rigid connection recognition',level:'application',kind:'recognition',q:'Which detail is shown among rigid/moment connection examples in the Chapter 5 PPT?',choices:['Extended end plate','Simple tie-rod pin only','Unconnected beam end','Loose lap joint only'],answer:0,explanation:'The presentation identifies flush and extended end plates among rigid connection examples.',source:'Chapter 5 PPT Fig. 5.1'},
{id:'ch5-moment-rotation',title:'Frame compatibility',level:'retrieval',kind:'reasoning',q:'What would be structurally inconsistent about analysing a frame joint as fully rigid and then detailing a very flexible simple connection?',choices:['The real rotation and moment transfer would not match the analysis assumption','There is no inconsistency','A simple joint is always stiffer than a rigid joint','Analysis never depends on connection behaviour'],answer:0,explanation:'The connection detail must be compatible with the rotational restraint assumed in analysis.',source:'Subramanian Ch.5'}
],
'5:Beam-to-Beam Connections':[
{id:'ch5-b2b-simple',title:'Common detail',level:'foundation',kind:'recognition',q:'Which simple detail can connect a secondary beam to a supporting beam?',choices:['Web angles or a flexible end plate','Only a concrete corbel','Only a welded pressure shell','No connection is required'],answer:0,explanation:'Chapter 5 applies common simple beam details to beam-to-beam joints.',source:'Subramanian Ch.5'},
{id:'ch5-b2b-cope',title:'Why cope a beam?',level:'core',kind:'concept',q:'Why might the end of a secondary beam be coped?',choices:['To allow the secondary and supporting beam top flanges to be at the same level','To increase the beam gross section','To eliminate all shear','To create a pin hole'],answer:0,explanation:'Coping provides geometric clearance when beam elevations must align.',source:'Subramanian Ch.5'},
{id:'ch5-b2b-reduced',title:'Effect of coping',level:'core',kind:'reasoning',q:'What structural consequence follows from removing part of a beam flange/web in a cope?',choices:['The local section capacity is reduced and must be checked','The steel yield stress doubles','The beam can no longer deflect','The web area increases'],answer:0,explanation:'Coping removes material and can make the end region critical.',source:'Subramanian Ch.5'},
{id:'ch5-b2b-block',title:'Coped web check',level:'core',kind:'concept',q:'Which limit state is specifically important around a bolted coped beam end?',choices:['Block shear of the reduced web region','Euler buckling of a 100 m column only','Concrete punching','Soil bearing failure'],answer:0,explanation:'The source identifies block shear and related local effects in the coped web as important checks.',source:'Subramanian Ch.5'},
{id:'ch5-b2b-torsion',title:'Moment continuity consequence',level:'application',kind:'reasoning',q:'Why can a beam-to-beam moment connection introduce torsion into the supporting primary beam?',choices:['Moment from the framing beam can act eccentrically relative to the primary beam shear centre/load path','Moment connections eliminate all moments','Primary beams cannot twist','Torsion occurs only in circular shafts'],answer:0,explanation:'The chapter notes that moment continuity at beam-to-beam joints may generate torsional action in the supporting beam.',source:'Subramanian Ch.5'},
{id:'ch5-b2b-detail',title:'Detail and force path',level:'retrieval',kind:'application',q:'Before accepting a beam-to-beam detail, what should the designer trace?',choices:['How shear, moment if present, and local forces pass through the connection into the supporting beam','Only the drawing border','Only the bolt manufacturer name','Only the beam paint system'],answer:0,explanation:'Connection design follows the complete force path and checks the locally reduced supporting/connected regions.',source:'Subramanian Ch.5'}
],
'5:Beam and Column Splices':[
{id:'ch5-splice-why',title:'Why splice?',level:'foundation',kind:'concept',q:'Which practical condition can require a beam or column splice?',choices:['Transport or available mill-length limitations','A desire to eliminate all forces','Only paint selection','Only concrete curing time'],answer:0,explanation:'Splices are used where full-length members are impractical or where section size changes.',source:'Subramanian Ch.5'},
{id:'ch5-splice-beam',title:'Beam splice actions',level:'core',kind:'classification',q:'A beam splice should be designed to transfer which actions present at the splice?',choices:['Bending moment and shear, and any other relevant force','Only density','Only thermal conductivity','No force because it is a splice'],answer:0,explanation:'The splice must continue the member force path across the break.',source:'Subramanian Ch.5'},
{id:'ch5-splice-flangeweb',title:'Flange and web roles',level:'core',kind:'reasoning',q:'In a conventional I-beam splice, why are separate flange and web splice plates often used?',choices:['They provide practical paths for the bending-related flange forces and web shear','They remove all member stress','They convert the beam into a pin','They are decorative only'],answer:0,explanation:'Flange and web splice components are arranged to transfer the member actions through appropriate parts of the section.',source:'Subramanian Ch.5'},
{id:'ch5-splice-column',title:'Column splice actions',level:'core',kind:'concept',q:'What must a column splice be capable of transferring when present in the design?',choices:['Required axial load plus any relevant moment and shear','Only beam deflection','Only dead weight of bolts','No axial force'],answer:0,explanation:'Column splices continue the column force path and may carry axial force, moment and shear.',source:'Subramanian Ch.5'},
{id:'ch5-splice-align',title:'Axis alignment',level:'application',kind:'reasoning',q:'Why should column axes be aligned at a splice where practicable?',choices:['Misalignment introduces eccentricity and additional moment that must otherwise be designed for','Alignment reduces steel strength','Misalignment removes axial load','Axes are irrelevant to force transfer'],answer:0,explanation:'Eccentricity between member axes creates additional moment and complicates the splice force path.',source:'Subramanian Ch.5'},
{id:'ch5-splice-change',title:'Change of section',level:'retrieval',kind:'application',q:'A splice at a deliberate change in member size should be detailed so that:',choices:['Forces transfer smoothly between the two section sizes without unintended eccentricity','The smaller member carries no load','The larger member is disconnected','Only one bolt is always used'],answer:0,explanation:'A change-of-section splice must maintain a rational, aligned load path.',source:'Subramanian Ch.5'}
],
'5:Semi-Rigid Connections':[
{id:'ch5-semi-continuum',title:'Connection continuum',level:'foundation',kind:'concept',q:'How does Chapter 5 describe real joint rotational behaviour?',choices:['As a continuum from flexible through semi-rigid to rigid','As only two exact states with no intermediate behaviour','As unrelated to stiffness','As always perfectly pinned'],answer:0,explanation:'Real connections exhibit finite stiffness and often fall between ideal pin and rigid limits.',source:'Subramanian Ch.5'},
{id:'ch5-semi-stiffness',title:'Finite rotational stiffness',level:'core',kind:'definition',q:'What parameter distinguishes a semi-rigid joint from ideal pinned or perfectly rigid behaviour?',choices:['Finite rotational stiffness','Zero steel density','Infinite member length','Zero shear strength'],answer:0,explanation:'Semi-rigid joints develop moment while also undergoing appreciable rotation.',source:'Subramanian Ch.5'},
{id:'ch5-semi-moment',title:'Moment redistribution',level:'core',kind:'reasoning',q:'Why can semi-rigid connection stiffness change the bending moments in a frame?',choices:['Joint rotation changes compatibility and therefore redistributes internal forces','Connection stiffness changes gravity','Moment is independent of joint rotation','Semi-rigid joints carry no moment'],answer:0,explanation:'Finite joint stiffness affects compatibility and the distribution of frame moments.',source:'Subramanian Ch.5'},
{id:'ch5-semi-drift',title:'Frame drift',level:'core',kind:'reasoning',q:'What global response can increase when beam-column connections are softer than assumed?',choices:['Frame drift','Steel density','Bolt ultimate strength','Concrete cover'],answer:0,explanation:'The source notes that connection softening can substantially increase frame drift.',source:'Subramanian Ch.5'},
{id:'ch5-semi-analysis',title:'Model the stiffness',level:'application',kind:'concept',q:'When semi-rigid behaviour is significant, what should the structural model reflect?',choices:['An appropriate moment-rotation/rotational-stiffness representation','A perfect pin regardless of detail','Zero displacement at every joint','No connection at all'],answer:0,explanation:'Analysis should include the relevant finite connection stiffness when it materially affects response.',source:'Subramanian Ch.5'},
{id:'ch5-semi-class',title:'Classify by behaviour',level:'retrieval',kind:'classification',q:'Which ordering correctly moves from least to greatest rotational restraint?',choices:['Flexible/simple → semi-rigid → rigid','Rigid → semi-rigid → flexible','Semi-rigid → flexible → rigid only','All three have identical stiffness'],answer:0,explanation:'Simple joints provide low restraint, semi-rigid joints intermediate restraint and rigid joints high restraint.',source:'Subramanian Ch.5'}
],
'5:Fatigue Behaviour':[
{id:'ch5-fatigue-cycle',title:'Repeated loading',level:'foundation',kind:'concept',q:'What loading feature makes fatigue relevant to a bolted connection?',choices:['Repeated cyclic stress fluctuations','One permanently constant zero load','Only member colour changes','Only static density'],answer:0,explanation:'Fatigue damage develops under repeated stress cycles.',source:'Subramanian Ch.5'},
{id:'ch5-fatigue-hole',title:'Crack initiation location',level:'core',kind:'reasoning',q:'Why are bolt holes important in fatigue-sensitive details?',choices:['They create local stress concentrations where cracks can initiate','They eliminate local stress','They always increase net area','They prevent all cyclic strain'],answer:0,explanation:'The chapter links fatigue cracking to stress concentrations around holes and details.',source:'Subramanian Ch.5'},
{id:'ch5-fatigue-hsfg',title:'Preferred fastener',level:'core',kind:'classification',q:'Which fastener system does Chapter 5 prefer for fatigue-sensitive bolted work?',choices:['HSFG bolts','Loose black bolts','Hot rivets only','Unthreaded timber dowels'],answer:0,explanation:'Pretensioned HSFG bolts are preferred where fatigue performance matters.',source:'Subramanian Ch.5'},
{id:'ch5-fatigue-drill',title:'Hole quality',level:'core',kind:'reasoning',q:'Why does accurate hole preparation matter for fatigue resistance?',choices:['Poor hole geometry and roughness can raise local stress concentration','Drilling changes steel into aluminium','Hole quality affects only appearance','Fatigue is independent of local detail'],answer:0,explanation:'Smooth, accurately formed details help limit stress concentrations that promote fatigue cracking.',source:'Subramanian Ch.5'},
{id:'ch5-fatigue-pretension',title:'Pretension benefit',level:'application',kind:'reasoning',q:'How does HSFG pretension help under fluctuating service loads?',choices:['It reduces slip and the amplitude of stress fluctuation carried directly by the bolt','It makes the bolt completely unstressed','It removes all plate stress','It guarantees infinite fatigue life'],answer:0,explanation:'Pretension stabilizes the joint and reduces damaging bolt stress reversal compared with a loose bearing connection.',source:'Subramanian Ch.5'},
{id:'ch5-fatigue-detail',title:'Detail the force flow',level:'retrieval',kind:'application',q:'Which detailing strategy is most consistent with Chapter 5 fatigue guidance?',choices:['Promote smooth force flow and avoid severe stress concentrations','Add abrupt notches near bolt holes','Use loose bolts for cyclic loads','Ignore hole quality'],answer:0,explanation:'Fatigue-resistant detailing aims to reduce local stress raisers and cyclic slip.',source:'Subramanian Ch.5'}
],
'5:Examples':[
{id:'ch5-ex-forcepath',title:'Start with the force path',level:'foundation',kind:'reasoning',q:'What is the first useful step when approaching a Chapter 5 connection example?',choices:['Identify how the applied actions pass through bolts, plates and connected members','Choose bolt count randomly','Check only member colour','Assume the connection cannot fail'],answer:0,explanation:'The worked examples repeatedly begin by identifying the load path and relevant actions.',source:'Subramanian Ch.5 examples'},
{id:'ch5-ex-modes',title:'List limit states',level:'core',kind:'application',q:'After identifying the force path, what should be listed before sizing the fastener group?',choices:['Applicable bolt and connected-plate limit states','Only the largest bolt diameter sold','Only fabrication cost','Only paint specification'],answer:0,explanation:'Worked design checks all relevant fastener and plate failure modes before selecting the governing capacity.',source:'Subramanian Ch.5 examples'},
{id:'ch5-ex-govern',title:'Governing resistance',level:'core',kind:'reasoning',q:'If bolt shear resistance exceeds plate bearing resistance, which should govern that connection check?',choices:['Plate bearing resistance','Bolt shear resistance because it is larger','Neither resistance matters','Steel density'],answer:0,explanation:'The weakest applicable limit state governs the connection resistance.',source:'Subramanian Ch.5 examples'},
{id:'ch5-ex-ecc',title:'Eccentric bracket logic',level:'core',kind:'formula',q:'For an eccentric bracket load P acting at distance e from the bolt-group centroid, which action must be added to direct load?',choices:['Moment Pe','Moment P/e','Axial strain e/P','No additional action'],answer:0,explanation:'The worked eccentric-group method resolves the load into direct force plus the moment Pe.',math:'M=Pe',source:'Subramanian Ch.5 examples'},
{id:'ch5-ex-plate',title:'Do not stop at bolts',level:'application',kind:'reasoning',q:'Why is a bolt-count calculation alone insufficient for a complete connection example?',choices:['Connected plates, net sections, bearing/block-shear regions and detailing may govern','The plate can never fail','Bolts carry no force','Only welds require checking'],answer:0,explanation:'The examples check both fastener resistance and the connected material/detail.',source:'Subramanian Ch.5 examples'},
{id:'ch5-ex-final',title:'Final design step',level:'retrieval',kind:'application',q:'After bolt strength is satisfactory, what remains essential before accepting the detail?',choices:['Check geometry, spacing/edge conditions, connected material and constructability','Delete all dimensions','Assume erection is irrelevant','Remove washers from every HSFG joint'],answer:0,explanation:'A complete connection design includes resistance plus practical detailing and force-transfer checks.',source:'Subramanian Ch.5 examples'}
],
'5:Summary':[
{id:'ch5-sum-rivets',title:'Technology shift',level:'foundation',kind:'retrieval',q:'Which broad change in steel connection practice is emphasized in the Chapter 5 summary?',choices:['Bolting and welding have largely replaced structural riveting','Riveting has replaced all bolting','Pins replaced all beam connections','Connections are no longer required'],answer:0,explanation:'The summary notes the decline of riveting and the dominant role of modern bolting/welding.',source:'Subramanian Ch.5 summary'},
{id:'ch5-sum-types',title:'Bolt families',level:'core',kind:'classification',q:'Which two bolt behaviours are central to the Chapter 5 summary?',choices:['Ordinary bearing-type black bolts and high-strength friction-grip bolts','Timber nails and screws','Only rivets and adhesives','Concrete anchors only'],answer:0,explanation:'The chapter contrasts ordinary bearing bolts with preloaded HSFG bolts.',source:'Subramanian Ch.5 summary'},
{id:'ch5-sum-pin',title:'Pin purpose recap',level:'core',kind:'retrieval',q:'A pin connection is selected primarily when the designer wants:',choices:['Rotation with negligible moment transfer','Maximum rotational restraint','No force transfer','A welded joint only'],answer:0,explanation:'Pins provide an intentional hinge-like rotational condition.',source:'Subramanian Ch.5 summary'},
{id:'ch5-sum-simple',title:'Simple versus moment',level:'core',kind:'classification',q:'What is the clearest distinction between simple and moment-resistant connections?',choices:['Simple joints mainly transfer shear with low rotational restraint; moment joints transfer significant bending moment','Both are identical','Simple joints transfer full moment; rigid joints transfer none','Neither can carry shear'],answer:0,explanation:'Connection classification follows force transfer and rotational restraint.',source:'Subramanian Ch.5 summary'},
{id:'ch5-sum-semi',title:'Intermediate behaviour',level:'application',kind:'concept',q:'Where does a semi-rigid connection lie relative to ideal simple and rigid joints?',choices:['Between them in rotational stiffness and moment-transfer behaviour','Outside structural mechanics','Exactly equal to a free pin','Exactly infinitely rigid'],answer:0,explanation:'Semi-rigid behaviour occupies the intermediate range of the joint stiffness continuum.',source:'Subramanian Ch.5 summary'},
{id:'ch5-sum-model',title:'Rational simplification',level:'retrieval',kind:'reasoning',q:'Why does the chapter accept rational simplified connection models?',choices:['Real joint behaviour is complex, so practical design captures governing behaviour with safe idealizations','Equilibrium is optional','Every joint has exactly the same response','Connections never deform'],answer:0,explanation:'The summary emphasizes practical idealization of complex connection behaviour.',source:'Subramanian Ch.5 summary'}
],
'5:Exercises':[
{id:'ch5-exer-lap',title:'Lap-joint exercise',level:'foundation',kind:'recognition',q:'Which basic connection type appears in the Chapter 5 exercise set?',choices:['Bolted lap joint','Prestressed concrete slab only','Timber mortise joint only','Soil retaining wall only'],answer:0,explanation:'The exercise set includes lap and butt-joint design among its fundamentals.',source:'Subramanian Ch.5 exercises'},
{id:'ch5-exer-hsfg',title:'HSFG exercise',level:'core',kind:'recognition',q:'Which high-strength fastening topic is explicitly practised in the exercises?',choices:['HSFG connection design','Only hot riveting','Only adhesive bonding','No bolt design'],answer:0,explanation:'The exercise set includes HSFG joints and hanger-type details.',source:'Subramanian Ch.5 exercises'},
{id:'ch5-exer-pin',title:'Pin exercise',level:'core',kind:'recognition',q:'What rotating connection form is included among the Chapter 5 exercise problems?',choices:['Pin-linked tension detail','Fixed concrete footing only','Timber hinge only','No rotational connection'],answer:0,explanation:'Pin connection design is part of the chapter exercise set.',source:'Subramanian Ch.5 exercises'},
{id:'ch5-exer-ecc',title:'Eccentric group exercise',level:'core',kind:'application',q:'What extra structural action must be handled in an eccentric bolted-bracket exercise?',choices:['Moment caused by load eccentricity','Only axial temperature strain','Only self-weight of washers','No moment'],answer:0,explanation:'Eccentric bracket problems require direct-load plus moment distribution through the bolt group.',source:'Subramanian Ch.5 exercises'},
{id:'ch5-exer-cope',title:'Coped-beam exercise',level:'application',kind:'recognition',q:'Which local detail appears in the exercise set and requires checks around a reduced beam end?',choices:['Coped beam connection','Solid circular shaft only','Concrete punching cone only','Timber notch only'],answer:0,explanation:'The exercises include coped-beam web-cleat type design.',source:'Subramanian Ch.5 exercises'},
{id:'ch5-exer-splice',title:'Splice exercise',level:'retrieval',kind:'classification',q:'Which member-continuity details are included in Chapter 5 exercises?',choices:['Beam and column splices','Only roof sheeting laps','Only concrete construction joints','Only expansion bearings'],answer:0,explanation:'The exercise set includes design of both beam and column splices.',source:'Subramanian Ch.5 exercises'}
],
'5:Review Questions':[
{id:'ch5-review-factors',title:'Joint behaviour factors',level:'foundation',kind:'retrieval',q:'Which item can influence the real behaviour of a steel connection?',choices:['Slip and connection flexibility','Only steel colour','Only drawing scale','Only site altitude'],answer:0,explanation:'The review returns to physical factors such as slip, fit, stiffness and deformation.',source:'Subramanian Ch.5 review questions'},
{id:'ch5-review-goal',title:'Connection-design purpose',level:'core',kind:'retrieval',q:'What is the fundamental goal of connection design?',choices:['Transfer the required actions safely between connected components','Make the joint visually large','Eliminate all structural analysis','Prevent every possible rotation in every joint'],answer:0,explanation:'Connection design provides a reliable structural load path between members.',source:'Subramanian Ch.5 review questions'},
{id:'ch5-review-class',title:'Three joint classes',level:'core',kind:'classification',q:'Which three behavioural classes are revisited by the Chapter 5 review?',choices:['Simple/flexible, semi-rigid and rigid','Elastic, plastic and concrete','Hot, cold and warm','Tension, soil and fluid'],answer:0,explanation:'The review explicitly revisits simple, semi-rigid and rigid connection behaviour.',source:'Subramanian Ch.5 review questions'},
{id:'ch5-review-rigid',title:'Rigid-joint meaning',level:'core',kind:'concept',q:'Which statement best describes an ideal rigid connection?',choices:['It transfers significant moment with very small relative joint rotation','It is a free hinge','It transfers no action','It must contain a pin'],answer:0,explanation:'Rigid connection idealization assumes high rotational restraint and moment transfer.',source:'Subramanian Ch.5 review questions'},
{id:'ch5-review-rivet',title:'Rivet installation recall',level:'application',kind:'sequence',q:'Which action is part of traditional hot-rivet installation?',choices:['Forming the second head while the rivet is hot','Leaving the rivet permanently unheaded','Pretensioning with a tension-control spline','Welding the nut to concrete'],answer:0,explanation:'The review includes rivet installation; hot riveting forms the second head before cooling.',source:'Subramanian Ch.5 review questions'},
{id:'ch5-review-ideal',title:'Idealization check',level:'retrieval',kind:'reasoning',q:'Why must the chosen simple, semi-rigid or rigid classification agree with the actual connection detail?',choices:['Frame force distribution and rotation depend on joint behaviour','Connection class changes steel density only','Joint stiffness cannot affect analysis','All classes transfer identical moments'],answer:0,explanation:'Connection classification must be compatible with the structural model and expected joint response.',source:'Subramanian Ch.5 review questions'}
]
});
