(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, supplementary Ch.22 Design for Torsion';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('18:Introduction',[
{id:'ch18-intro-1',title:'When torsion matters',level:'foundation',kind:'concept',q:'When does the chapter say torsional moment must be checked explicitly?',choices:['When torsion is significant or acts with other forces such as bending and axial compression','Only when a member is in pure tension','Only for concrete beams','Never, because torsion is always secondary'],answer:0,explanation:'The chapter treats torsion as sometimes significant and often combined with bending or axial force.',source:S},
{id:'ch18-intro-2',title:'Best section family for torsion',level:'foundation',kind:'classification',q:'Which section family is identified as torsionally stronger for similar area?',choices:['Circular, square or rectangular hollow sections','Open I, T and angle sections','Flat plates only','Channels only'],answer:0,explanation:'Closed hollow sections develop much greater torsional stiffness than comparable open sections.',source:S},
{id:'ch18-intro-3',title:'Bending efficiency is not torsion efficiency',level:'core',kind:'reasoning',q:'Why can an I-section be efficient in bending yet relatively inefficient in torsion?',choices:['Material far from the bending centroid does not by itself create the closed shear-flow path that gives high torsional stiffness','I-sections have no bending stiffness','Torsion depends only on area','I-sections cannot carry shear'],answer:0,explanation:'The source explicitly contrasts shapes efficient in bending with hollow sections that are much more efficient in torsion.',source:S},
{id:'ch18-intro-4',title:'IS 800 scope',level:'core',kind:'retrieval',q:'What limitation of IS 800:2007 is stated at the start of the chapter?',choices:['It does not provide direct member-design provisions for torsion','It contains no beam provisions','It prohibits hollow sections','It covers only timber'],answer:0,explanation:'The chapter develops mechanics and approximate procedures because IS 800:2007 does not provide direct torsion member-design provisions.',source:S},
{id:'ch18-intro-5',title:'Uniform versus non-uniform torsion',level:'core',kind:'classification',q:'Which distinction is a central theme of the chapter?',choices:['Uniform St Venant torsion versus restrained/non-uniform warping torsion','Dead load versus live load only','Elasticity versus corrosion','Bolts versus rivets'],answer:0,explanation:'The chapter explicitly develops the difference between uniform torsion and non-uniform warping torsion.',source:S},
{id:'ch18-intro-6',title:'Design strategy',level:'application',kind:'reasoning',q:'What broad design strategy does the chapter encourage when torsion is difficult to analyse?',choices:['Use suitable section choice and detailing to minimize torsional effects where practical','Always ignore torsion','Increase span without restraint','Use only open sections'],answer:0,explanation:'The summary notes that practical detailing can often reduce torsion more effectively than relying only on complex stress calculations.',source:S}
]);
add('18:Torsional Loading in Practice',[
{id:'ch18-load-1',title:'Primary versus secondary torsion',level:'foundation',kind:'classification',q:'What distinguishes primary torsion from secondary torsion?',choices:['Primary torsion is required for load transfer; secondary torsion arises from compatible joint or frame deformation','Primary torsion is always smaller','Secondary torsion is caused only by temperature','There is no distinction'],answer:0,explanation:'The chapter classifies torsion by whether it is essential to load transfer or induced as a secondary compatibility action.',source:S},
{id:'ch18-load-2',title:'Three primary torsion classes',level:'core',kind:'retrieval',q:'How is primary torsion classified in the chapter?',choices:['Free (uniform), restrained (warping/non-uniform), and destabilizing','Elastic, plastic, and thermal','Static, dynamic, and fatigue','Major, minor, and local'],answer:0,explanation:'These three classes are shown in the chapter primary-torsion classification figure.',source:S},
{id:'ch18-load-3',title:'Secondary torsion prediction',level:'core',kind:'application',q:'How may the magnitude of secondary torsion in a frame be predicted?',choices:['By a three-dimensional structural analysis','By steel density alone','By beam depth alone','By ignoring joint rotations'],answer:0,explanation:'The source states that secondary torsion caused by compatible differential twists can be predicted using 3D analysis.',source:S},
{id:'ch18-load-4',title:'Purlin orientation',level:'application',kind:'reasoning',q:'Why can the orientation of a channel purlin strongly influence torsion?',choices:['It changes the eccentricity between the load line and the shear centre','It changes steel density','It removes gravity load','It makes the section doubly symmetric'],answer:0,explanation:'The chapter purlin example shows torsion increasing when the load application point lies farther from the shear centre.',source:S}
]);
add('18:Behaviour of Members Due to Torsion',[
{id:'ch18-beh-1',title:'Uniform torsion definition',level:'foundation',kind:'concept',q:'What characterizes uniform torsion?',choices:['The rate of change of twist is constant along the member','Warping varies arbitrarily along the member','There is no shear stress','The member has zero torque'],answer:0,explanation:'Uniform torsion has a constant twist rate and uniform longitudinal warping along the length.',source:S},
{id:'ch18-beh-2',title:'Non-uniform torsion definition',level:'foundation',kind:'concept',q:'What characterizes non-uniform torsion?',choices:['The twist rate and warping vary along the member','The cross-section is always circular','No warping stress develops','The torque must be zero'],answer:0,explanation:'Restrained warping causes the twist rate and longitudinal warping displacement to vary along the member.',source:S},
{id:'ch18-beh-3',title:'Circular-section shear stress',level:'core',kind:'formula',q:'For a solid circular section under St Venant torsion, which relation gives shear stress at radius r?',choices:['f_st = Tr/I_p','f_st = I_p/(Tr)','f_st = T/r','f_st = Gr/T'],answer:0,explanation:'The source gives the linear torsional shear-stress relation f_st=Tr/I_p.',math:'f_{st}=\\frac{Tr}{I_p}',source:S},
{id:'ch18-beh-4',title:'Open-section torsional constant',level:'core',kind:'formula',q:'For a thin-walled open section made from slender rectangular elements, how is St Venant torsional constant approximated?',choices:['I_t ≈ Σ(bt³/3)','I_t ≈ Σ(b³t/12)','I_t = A² only','I_t = I_y+I_z always'],answer:0,explanation:'For open sections, the chapter sums bt cubed over 3 for the individual wall elements.',math:'I_t\\approx\\sum\\frac{bt^3}{3}',source:S},
{id:'ch18-beh-5',title:'Two torque components',level:'core',kind:'formula',q:'How is total torque on an I- or channel section represented in restrained torsion?',choices:['T = T_v + T_w','T = T_v T_w','T = T_v/T_w','T = 0'],answer:0,explanation:'The elastic formulation splits total torque into St Venant and warping components.',math:'T=T_v+T_w',source:S},
{id:'ch18-beh-6',title:'Torsion parameter meaning',level:'application',kind:'reasoning',q:'What does a high value of the chapter torsion parameter k_t indicate?',choices:['Uniform St Venant torsion is predominant','Warping-only behaviour is predominant','No torsion exists','The section must be a channel'],answer:0,explanation:'The chapter classification associates high k_t with uniform torsion and low k_t with dominant warping.',source:S}
]);
add('18:Shear Centre',[
{id:'ch18-sc-1',title:'Channel shear centre',level:'core',kind:'retrieval',q:'Where does the chapter place the shear centre of a channel section relative to its web?',choices:['Outside the web, while the centroid lies inside','Always at the centroid','At the flange tip only','Inside the web at every location'],answer:0,explanation:'For channels, the shear centre lies outside the web whereas the centroid is inside the section.',source:S},
{id:'ch18-sc-2',title:'Two-plate-element sections',level:'application',kind:'classification',q:'For sections made from two intersecting plate elements such as angles and tees, where is the shear centre stated to lie?',choices:['At the plate-intersection point','At the centroid in every case','At the farthest flange tip','At mid-depth of the web'],answer:0,explanation:'The chapter states that for angles, tees and cruciform-type intersecting plate elements, the shear centre is at the plate intersection point.',source:S}
]);
add('18:Approximate Design Procedure for Torsion',[
{id:'ch18-apx-1',title:'Purpose of the approximation',level:'foundation',kind:'concept',q:'What is the approximate torsion procedure intended for?',choices:['Preliminary design when full restrained-torsion analysis is too complex','Exact nonlinear collapse analysis only','Corrosion design','Fatigue counting'],answer:0,explanation:'The method is presented as a conservative preliminary-design procedure.',source:S},
{id:'ch18-apx-2',title:'Dominant stress in approximation',level:'core',kind:'reasoning',q:'Which torsion-induced stress is treated as most important in the approximate method?',choices:['Compressive stress from warping/lateral flange bending','Only direct axial tension','Only bearing stress','Only thermal stress'],answer:0,explanation:'The source says the compressive warping component is usually the most important quantity for preliminary design.',source:S},
{id:'ch18-apx-3',title:'Flexural analogy',level:'core',kind:'concept',q:'What mechanical analogy underlies the approximate method?',choices:['Treat torsion as lateral bending of the individual flanges','Treat torsion as pure axial tension','Treat torsion as hydrostatic pressure','Treat torsion as plate bearing only'],answer:0,explanation:'The method converts the torsional action into equivalent lateral flange bending.',source:S},
{id:'ch18-apx-4',title:'Cantilever flange moment',level:'core',kind:'formula',q:'For the chapter cantilever with tip load P at eccentricity e, length L and flange-centroid spacing h, what flange bending moment is used?',choices:['M_f = PeL/h','M_f = Ph/e','M_f = PLh','M_f = Pe/hL'],answer:0,explanation:'Equation 22.16 gives M_f=PeL/h for the flange flexural analogy.',math:'M_f=\\frac{PeL}{h}',source:S},
{id:'ch18-apx-5',title:'Why the method is conservative',level:'application',kind:'reasoning',q:'What did the chapter comparison of flexural analogy with the differential-equation solution show?',choices:['The flexural analogy produced higher, conservative stresses, especially warping bending stress','The flexural analogy always produced zero stress','Both methods were identical in every stress component','The differential equation was always more conservative'],answer:0,explanation:'The worked comparison reported substantially higher stresses from the flexural analogy, particularly lateral warping bending stress.',source:S},
{id:'ch18-apx-6',title:'Combined checks',level:'retrieval',kind:'application',q:'Besides capacity under combined bending and torsion, what additional check does the chapter emphasize?',choices:['A buckling check where lateral-torsional buckling may govern','Only paint thickness','Only dead load','No further check'],answer:0,explanation:'The approximate procedure includes both capacity and stability/buckling considerations.',source:S}
]);
add('18:Distortion of Thin Walled Members',[
{id:'ch18-dist-1',title:'Why distortion matters',level:'core',kind:'reasoning',q:'Why can cross-section distortion invalidate ordinary bending-stress expectations?',choices:['Out-of-plane deformation can introduce additional distortional stresses and change the stress distribution','It makes all stresses zero','It changes only member colour','It affects only solid circular shafts'],answer:0,explanation:'The chapter warns that local force distribution can produce twisting and distortion that alter the usual bending-stress distribution.',source:S},
{id:'ch18-dist-2',title:'Open-section distortion resistance',level:'core',kind:'classification',q:'How are open thin-walled sections described with respect to distortion resistance?',choices:['Relatively flexible','Always rigid','More resistant than closed triangular cells','Unaffected by local torque'],answer:0,explanation:'Open sections are identified as more flexible in distortion.',source:S},
{id:'ch18-dist-3',title:'Highest distortion resistance',level:'core',kind:'classification',q:'Which thin-walled cell shape is identified as having high resistance to distortion?',choices:['Closed triangular cell','Open channel','Rectangular cell with no stiffening','Trapezoidal cell only'],answer:0,explanation:'The source contrasts flexible open sections and rectangular/trapezoidal cells with highly distortion-resistant closed triangular cells.',source:S},
{id:'ch18-dist-4',title:'Design response to significant distortion',level:'application',kind:'reasoning',q:'If twisting and distortion are significant, what actions may the designer need to take?',choices:['Increase member strength or limit both twisting and distortion','Ignore the out-of-plane action','Reduce all restraints','Use a thinner open section'],answer:0,explanation:'The chapter explicitly states that strength may need to be increased or twisting/distortion limited to avoid failure.',source:S}
]);
add('18:Torsional Stiffening and End Restraints',[
{id:'ch18-stiff-1',title:'Preferred section when torsion unavoidable',level:'foundation',kind:'application',q:'When torsion cannot be avoided, which section type does the chapter recommend considering first?',choices:['Box section','Single angle only','Open channel only','Flat bar only'],answer:0,explanation:'Box sections are recommended because they are highly effective in torsion.',source:S},
{id:'ch18-stiff-2',title:'End boxing plate length',level:'core',kind:'retrieval',q:'What length is recommended for longitudinal boxing plates used at the ends of an I-beam?',choices:['Approximately equal to the beam depth','Ten times the span','Half the flange width only','Any arbitrary length'],answer:0,explanation:'The source states that the boxing plate length should be equal to the beam depth.',source:S},
{id:'ch18-stiff-3',title:'Effect of end boxing',level:'core',kind:'concept',q:'What end conditions are associated with the longitudinal boxing-plate detail described in the chapter?',choices:['Twist and twist rate restrained: φ=0 and φ′=0','Free twist: φ unrestricted','Only axial displacement restrained','No change in torsional restraint'],answer:0,explanation:'The stated boxing detail is intended to produce φ=0 and φ′=0 at the beam end.',math:'\\phi=0,\\quad \\phi^{\\prime}=0',source:S},
{id:'ch18-stiff-4',title:'More efficient end stiffening',level:'application',kind:'classification',q:'Which end detail is described as more efficient than parallel longitudinal plates for forming a torsionally stiff end?',choices:['A channel, angle or bent plate welded between the flanges to form a stiff box','Removing the web','Cutting the flanges','Leaving the end completely unstiffened'],answer:0,explanation:'The chapter recommends forming a stiff closed box between flanges using channel, angle or bent plate details.',source:S},
{id:'ch18-stiff-5',title:'Real unstiffened end restraint',level:'core',kind:'reasoning',q:'If no special torsional end stiffening is provided, how does the chapter describe the actual restraint?',choices:['Neither ideal simple nor ideal fixed; end twist is approximately zero','Perfectly free in every sense','Always perfectly fixed','Always a pure pin with zero torque'],answer:0,explanation:'The source cautions against idealizing ordinary ends as exactly simple or fixed in torsion.',source:S},
{id:'ch18-stiff-6',title:'What must connections do?',level:'retrieval',kind:'application',q:'What must connections and bracing of torsion-loaded members achieve?',choices:['Transfer the torsional reactions to the supports consistently with the analysis model','Carry only vertical reaction','Eliminate all bending moments automatically','Remain unmodelled'],answer:0,explanation:'The chapter stresses correct idealization and careful detailing so torsional reactions reach the supports.',source:S}
]);
add('18:Torsional Buckling',[
{id:'ch18-buck-1',title:'Torsional buckling shape',level:'foundation',kind:'concept',q:'What distinguishes pure torsional buckling from ordinary flexural buckling?',choices:['The longitudinal axis can remain straight while cross-sections rotate','The member bends laterally with no twist','Only local plate yielding occurs','The member is in tension'],answer:0,explanation:'In torsional buckling the member twists under compression while its longitudinal axis may remain straight.',source:S},
{id:'ch18-buck-2',title:'Susceptible sections',level:'foundation',kind:'classification',q:'Which section types are specifically identified as potentially susceptible to torsional buckling under compression?',choices:['Angles, tees, Z-sections, cruciforms and channels with low torsional stiffness','Only solid circular bars','Only concrete columns','Only thick box sections'],answer:0,explanation:'The chapter lists thin-walled open sections with relatively low torsional stiffness.',source:S},
{id:'ch18-buck-3',title:'Critical-stress ingredients',level:'core',kind:'reasoning',q:'What governs the torsional critical stress according to the chapter?',choices:['St Venant torsional stiffness, warping resistance, and end restraint','Density only','Yield stress only','Flange width only'],answer:0,explanation:'The critical stress depends on torsional stiffness and resistance to warping supplied by the member and its end restraints.',source:S},
{id:'ch18-buck-4',title:'Warping effective-length factor',level:'core',kind:'retrieval',q:'In the chapter torsional-buckling equation, what effective-length factor K is used when both ends are free to warp?',choices:['1.0','0.5','0.7','2.0'],answer:0,explanation:'Equation 22.25b uses K=1 for ends free to warp and K=0.5 for complete warping restraint.',source:S},
{id:'ch18-buck-5',title:'Complete warping restraint',level:'core',kind:'retrieval',q:'What K value is given when warping at both ends is completely restrained?',choices:['0.5','1.0','1.5','2.0'],answer:0,explanation:'The chapter assigns K=0.5 for complete warping restraint at both ends.',source:S},
{id:'ch18-buck-6',title:'Equivalent radius method',level:'application',kind:'reasoning',q:'How is the equivalent radius of gyration r_e used for doubly or point-symmetric sections?',choices:['Compare r_e with r_y and r_z to identify whether torsional or flexural buckling is more critical','Use it only to calculate self-weight','Add it directly to member length','Use it only for tensile rupture'],answer:0,explanation:'The chapter converts torsional buckling into an equivalent slenderness KL/r_e for comparison with principal-axis flexural buckling.',source:S}
]);
add('18:Torsional Deformations',[
{id:'ch18-def-1',title:'Rotation formula',level:'core',kind:'formula',q:'Which expression does the chapter give for angle of rotation φ at distance x under working-load torque T?',choices:['φ = Tx/(GI_t)','φ = GI_t/(Tx)','φ = T/(Gx)','φ = xI_t/T'],answer:0,explanation:'Equation 22.27 gives φ=Tx/(GI_t).',math:'\\phi=\\frac{Tx}{GI_t}',source:S},
{id:'ch18-def-2',title:'Steel shear modulus relation',level:'core',kind:'retrieval',q:'What relation for steel shear modulus G is used in the chapter deformation examples?',choices:['G = E/2.6','G = 2.6E','G = E²','G = E/10'],answer:0,explanation:'The source uses G=E/2.6 for steel.',math:'G=\\frac{E}{2.6}',source:S},
{id:'ch18-def-3',title:'Effect of torsional constant',level:'application',kind:'reasoning',q:'For the same T, x and G, what happens to twist if I_t increases?',choices:['Twist decreases','Twist increases','Twist is unchanged','Twist becomes independent of torque'],answer:0,explanation:'The rotation formula is inversely proportional to I_t.',source:S},
{id:'ch18-def-4',title:'Effect of member distance',level:'application',kind:'reasoning',q:'For uniform St Venant torsion with constant T, G and I_t, how does φ vary with distance x from the support?',choices:['Linearly with x','With x squared','Independent of x','Inversely with x'],answer:0,explanation:'Equation 22.27 is directly proportional to x.',source:S},
{id:'ch18-def-5',title:'Combined deformation components',level:'core',kind:'classification',q:'When bending acts together with torsion, which deformation components does the chapter suggest evaluating separately?',choices:['Major-axis bending, minor-axis bending, and torsion','Only vertical bending','Only axial shortening','Only thermal strain'],answer:0,explanation:'The source recommends evaluating these three working-load deformation components separately.',source:S},
{id:'ch18-def-6',title:'Combining movements',level:'retrieval',kind:'reasoning',q:'How may the separate deformation components be combined when actual movement is required?',choices:['Vectorially','By multiplying all deflections','By ignoring torsion','By adding only their absolute squares without square root'],answer:0,explanation:'The chapter states that major-axis, minor-axis and torsional movements may be combined vectorially if required.',source:S}
]);
add('18:Examples',[
{id:'ch18-ex-1',title:'Example 22.1 objective',level:'foundation',kind:'retrieval',q:'What two outputs are calculated in the chapter first torsion example for different shaft sections?',choices:['Maximum shear stress and maximum angle of rotation','Only axial shortening and temperature','Only bending moment and reaction','Only fatigue life and crack length'],answer:0,explanation:'Example 22.1 compares shear stress and twist for several section shapes under the same torque.',source:S},
{id:'ch18-ex-2',title:'Example torque and length',level:'core',kind:'retrieval',q:'What torque and member length are used in Example 22.1?',choices:['15 kN·m and 1.5 m','20 kN·m and 2 m','3 kN·m and 6 m','50 kN·m and 4 m'],answer:0,explanation:'Example 22.1 applies a 15 kN·m twisting moment to a 1.5 m long member.',source:S},
{id:'ch18-ex-3',title:'Flexural analogy comparison',level:'application',kind:'reasoning',q:'What key conclusion comes from comparing the flexural-analogy and differential-equation example results?',choices:['Flexural analogy is conservative, especially for warping bending stress','Flexural analogy always underestimates stress','Both methods always give the same result','Warping stress is always zero'],answer:0,explanation:'The chapter comparison shows higher stresses from the approximate flexural analogy.',source:S},
{id:'ch18-ex-4',title:'Cantilever eccentricity example',level:'core',kind:'retrieval',q:'In Example 22.4, what eccentricity is used for the 50 kN tip load on the 4 m cantilever?',choices:['30 mm','3 mm','300 mm','75 mm'],answer:0,explanation:'Example 22.4 uses a 50 kN load applied 30 mm eccentrically.',source:S},
{id:'ch18-ex-5',title:'Cruciform example conclusion',level:'application',kind:'reasoning',q:'In the cruciform-column example, why does torsional buckling govern when r_e is smaller than both principal radii?',choices:['The corresponding torsional slenderness KL/r_e is the largest and gives the lowest buckling resistance','A smaller radius always increases tensile strength','Flexural buckling becomes impossible','The member has no axial load'],answer:0,explanation:'The example compares equivalent and principal radii to identify the weakest buckling mode.',source:S},
{id:'ch18-ex-6',title:'Worked-example sequence',level:'retrieval',kind:'sequence',q:'What sequence best reflects the chapter worked torsion design examples?',choices:['Determine section properties and torsional actions → calculate stresses/deformations → perform capacity/stability checks','Select paint → ignore torque → check only self-weight','Compute fatigue cycles only','Check concrete creep only'],answer:0,explanation:'The examples repeatedly establish torsional properties/actions before checking stress, deformation and stability.',source:S}
]);
add('18:Summary',[
{id:'ch18-sum-1',title:'Main torsion trigger',level:'foundation',kind:'retrieval',q:'According to the chapter summary, what is the main geometric trigger for torsion from transverse loading?',choices:['The load plane does not pass through the shear centre','The load passes exactly through the shear centre','The member has zero span','The material is steel'],answer:0,explanation:'Eccentricity between load and shear centre produces torsional moment.',source:S},
{id:'ch18-sum-2',title:'Primary torsion that should be avoided',level:'core',kind:'retrieval',q:'Which class of primary torsion does the summary say should not be allowed in structures?',choices:['Destabilizing torsion','Free torsion','Restrained torsion','Secondary torsion'],answer:0,explanation:'The summary explicitly states that destabilizing torsion should not be allowed.',source:S},
{id:'ch18-sum-3',title:'Closed versus open',level:'core',kind:'reasoning',q:'What section-selection lesson is emphasized in the summary?',choices:['Closed tubes and boxes resist torsion much better than open I, channel, angle or T sections','Open sections always have greater torsional stiffness','Section shape has no effect','Channels are always strongest'],answer:0,explanation:'The summary highlights the major torsional-efficiency advantage of closed sections.',source:S},
{id:'ch18-sum-4',title:'Warping properties',level:'core',kind:'classification',q:'Which two section properties control non-uniform torsional deformation?',choices:['Torsional constant I_t and warping constant I_w','Area and density only','Yield stress and temperature only','Bolt diameter and pitch'],answer:0,explanation:'The summary identifies both I_t and I_w as governing restrained-torsion deformation.',source:S},
{id:'ch18-sum-5',title:'Practical detailing lesson',level:'application',kind:'reasoning',q:'What practical choice may be easier than fully calculating combined torsion and bending stresses?',choices:['Detail the beam ends to minimize torsional effects','Remove all restraints','Use a thinner web','Ignore eccentricity'],answer:0,explanation:'The chapter summary encourages torsion-reducing detailing where practical.',source:S},
{id:'ch18-sum-6',title:'Buckling method in summary',level:'retrieval',kind:'concept',q:'What simplified concept is used in the chapter for flexural-torsional buckling assessment of symmetric open sections?',choices:['Equivalent radius of gyration','Equivalent concrete cube strength','Equivalent paint thickness','Equivalent fatigue life'],answer:0,explanation:'The summary notes the use of an equivalent radius of gyration to compare torsional and flexural buckling.',source:S}
]);
add('18:Exercises',[
{id:'ch18-exer-1',title:'Exercise 1 comparison',level:'foundation',kind:'retrieval',q:'What does Exercise 1 compare under the same 20 kN·m torque?',choices:['Solid circular, hollow circular and square box sections','Three concrete grades','Three bolt classes','Three paint systems'],answer:0,explanation:'Exercise 1 asks for maximum torsional stress and twist for three different section forms.',source:S},
{id:'ch18-exer-2',title:'Differential-equation exercise',level:'core',kind:'retrieval',q:'What method is explicitly required in Exercise 2 for the wide-flange beam under a 3.0 kN·m midspan torque?',choices:['Differential-equation restrained-torsion solution','Only Euler buckling','Only plastic collapse','Only fatigue S-N analysis'],answer:0,explanation:'Exercise 2 asks for combined bending and torsional stresses using the differential-equation solution.',source:S},
{id:'ch18-exer-3',title:'Method-comparison exercise',level:'core',kind:'reasoning',q:'What is the purpose of Exercise 3?',choices:['Recompute Exercise 2 by flexural analogy and compare the results','Change the steel to concrete','Check only corrosion','Calculate fire resistance'],answer:0,explanation:'Exercise 3 directly compares the approximate flexural analogy with the more refined method.',source:S},
{id:'ch18-exer-4',title:'Cantilever design exercise',level:'application',kind:'retrieval',q:'In Exercise 4, what eccentricity is applied to the 20 kN tip load on the 5 m cantilever?',choices:['25 mm','2.5 mm','250 mm','50 mm'],answer:0,explanation:'The exercise specifies a 25 mm eccentricity and fy=250 MPa.',source:S},
{id:'ch18-exer-5',title:'RHS combined-action exercise',level:'application',kind:'classification',q:'Which combined actions appear in Exercise 7 for the rectangular hollow-section member?',choices:['Axial compression, biaxial bending and torsion','Pure tension only','Only vertical shear','Only temperature'],answer:0,explanation:'Exercise 7 combines 30 kN compression, Mz, My and a torsional moment.',source:S},
{id:'ch18-exer-6',title:'Warping-restraint column exercise',level:'retrieval',kind:'classification',q:'Which two section types are compared in Exercise 8 with warping prevented at the ends?',choices:['Cruciform and T-section','Circular tube and box only','I-section and channel only','Angle and flat bar only'],answer:0,explanation:'Exercise 8 asks for maximum load of cruciform and T-section columns with restrained warping.',source:S}
]);
add('18:Review Questions',[
{id:'ch18-rev-1',title:'Review: strongest torsion section',level:'foundation',kind:'retrieval',q:'Among I-sections, channels, and tubes/hollow sections, which does the chapter review identify as strongest in torsion?',choices:['Tubes and hollow sections','I-sections','Channels','All are identical'],answer:0,explanation:'Closed hollow sections have much higher torsional efficiency.',source:S},
{id:'ch18-rev-2',title:'Review: destabilizing example',level:'core',kind:'retrieval',q:'Which arrangement in the chapter illustrates destabilizing torsion?',choices:['A cantilevering member that restrains neither twist nor lateral deflection of the torsion member','A doubly symmetric tube loaded through its shear centre','A fully boxed beam end','A circular shaft under pure torque'],answer:0,explanation:'The primary-torsion classification figure shows destabilizing torsion when the framing member permits lateral deflection and twist.',source:S},
{id:'ch18-rev-3',title:'Review: St Venant condition',level:'core',kind:'concept',q:'When is St Venant torsion obtained along a member?',choices:['When warping is free/unrestrained and uniform along the length','When warping is completely prevented everywhere','Only after yielding','Only in concrete'],answer:0,explanation:'Uniform torsion corresponds to unrestrained, uniform warping and constant twist rate.',source:S},
{id:'ch18-rev-4',title:'Review: single-cell constant',level:'core',kind:'formula',q:'Which expression is given for the torsional constant of a single-cell closed thin-walled section?',choices:['I_t = 4A²/(∮ds/t)','I_t = Σbt³/3 for every closed cell','I_t = I_y+I_z','I_t = A/t'],answer:0,explanation:'Equation 22.9 gives the single-cell closed-section torsional constant using the wall midline.',math:'I_t=\\frac{4A^2}{\\oint ds/t}',source:S},
{id:'ch18-rev-5',title:'Review: pure torsional buckling condition',level:'core',kind:'reasoning',q:'Under what geometric condition is pure torsional buckling strictly possible?',choices:['Centroid and shear centre coincide','Centroid and shear centre are far apart','The section has no symmetry and no torsional stiffness','The member is in pure tension'],answer:0,explanation:'The chapter states that pure torsional buckling requires coincident centroid and shear centre.',source:S},
{id:'ch18-rev-6',title:'Review: rotation equation',level:'retrieval',kind:'formula',q:'Which variables directly increase torsional rotation in φ=Tx/(GI_t)?',choices:['Torque T and distance x','G and I_t','Only I_t','Only G'],answer:0,explanation:'Rotation grows with torque and distance, and decreases as shear modulus or torsional constant increases.',math:'\\phi=\\frac{Tx}{GI_t}',source:S}
]);
})();
