(() => {
  const B=window.REVISION_BANK=window.REVISION_BANK||{};
  const add=(topic,rows)=>{const key=`9:${topic}`;B[key]=[...(B[key]||[]),...rows.map((r,i)=>({id:`ch9-deep-${i+1}`,title:r[0],level:r[1],kind:r[2],q:r[3],choices:r[4],answer:0,explanation:r[5],source:'N. Subramanian, Design of Steel Structures, Ch. 9 / matching Oxford chapter presentation'}))];};
  const Q=(t,l,k,q,c,d1,d2,d3,e)=>[t,l,k,q,[c,d1,d2,d3],e];

  add('Introduction',[
    Q('Compression member role','foundation','concept','Chapter 9 introduction — what defines a compression member?','Its dominant axial force is compressive.','It carries only pure tension.','It carries only torsion.','It has zero axial force.','Columns, struts and similar members are principally required to resist axial compression.'),
    Q('Strength is not enough','core','reasoning','Why can a compression member fail before the material reaches its squash load?','Instability or buckling can govern before full cross-sectional yielding.','Compression always increases stiffness.','Yield stress is irrelevant.','Buckling occurs only in tension.','Compression members are often stability-controlled, especially as slenderness increases.'),
    Q('Member vocabulary','foundation','classification','Which term is commonly used for a compression member in a truss?','Strut.','Tie.','Purlin.','Girt.','A strut is a member carrying compression, commonly in trusses and bracing systems.'),
    Q('Design variables','core','concept','Which combination most directly governs compression-member resistance?','Section strength, slenderness, imperfections and end restraint.','Paint colour and density only.','Span alone.','Bolt grade only.','Compression resistance depends on both material/section capacity and stability-related variables.'),
    Q('Column versus short block','application','reasoning','Two members have the same area and steel grade, but one is much longer and less restrained. Which is more vulnerable to buckling?','The longer, less restrained member.','The shorter stockier member.','Both must have identical resistance.','Neither can buckle.','Greater effective slenderness reduces stability resistance.'),
    Q('Chapter purpose','retrieval','concept','What is the central purpose of Chapter 9?','To connect compression-member behaviour, buckling and practical design/detailing.','To design only welded joints.','To analyse only beams.','To calculate wind pressure only.','The chapter develops compression behaviour from ideal buckling through real-column design and built-up members.')
  ]);

  add('Construction Details',[
    Q('Load path at a column joint','foundation','concept','Construction Details — what should a column connection achieve first?','A clear, stable path for axial force and any accompanying moment/shear.','A deliberate eccentricity in every case.','Zero contact between connected parts.','No continuity of force.','Column details must transmit the actual forces safely through joints, splices and supports.'),
    Q('Eccentricity concern','core','reasoning','Why should unnecessary eccentricity in a compression-member connection be avoided?','It introduces additional bending into a nominally axial member.','It always reduces bending moment to zero.','It increases radius of gyration automatically.','It eliminates buckling.','An eccentric load produces a moment in addition to compression.'),
    Q('Splice alignment','core','application','Why is it desirable for a column splice to align member centroidal axes closely?','To reduce unintended eccentricity and secondary bending.','To make the column more slender.','To increase hole diameter.','To remove axial force.','Good alignment helps preserve the intended compression load path.'),
    Q('Bearing surfaces','core','concept','When column ends are intended to transfer substantial compression by direct bearing, what detailing issue matters?','Adequate contact and fit of the bearing surfaces.','Only paint thickness.','Only bolt colour.','No surface contact.','Direct-bearing details depend on reliable contact between the member ends or bearing components.'),
    Q('Connection reality','trap','reasoning','Which statement is unsafe as a general assumption?','Every column connection is perfectly concentric and moment-free.','Column details can introduce moments.','Splices need a defined force path.','Base details transfer forces to foundations.','Real details may transmit axial force, shear and moment and can introduce eccentricity.'),
    Q('Detailing objective','retrieval','concept','What is the best summary of compression-member construction detailing?','Maintain alignment, restraint and a reliable force-transfer path.','Maximise eccentricity.','Avoid all fasteners.','Make every joint flexible.','Construction details strongly influence actual restraint and member behaviour.')
  ]);

  add('Possible Failure Modes',[
    Q('Stocky member mode','foundation','classification','Which failure mode is most associated with a very short stocky compression member?','Cross-sectional yielding/crushing rather than global Euler buckling.','Lateral-torsional buckling of a beam only.','Net-section tension rupture.','Fatigue crack growth only.','Very stocky members can approach material compressive strength before overall instability governs.'),
    Q('Slender member mode','foundation','classification','Which mode becomes increasingly important as a compression member becomes slender?','Overall flexural buckling.','Gross-section tension yielding.','Bolt slip only.','Concrete punching.','Slender members are increasingly controlled by instability.'),
    Q('Local versus global','core','concept','What distinguishes local buckling from overall flexural buckling?','Local buckling deforms plate elements of the cross-section; global buckling bends the member as a whole.','They are identical.','Local buckling occurs only in cables.','Global buckling changes only paint thickness.','Compression design must consider instability at both plate-element and member scales.'),
    Q('Torsional possibilities','core','concept','Which additional instability can affect some open or unsymmetric compression sections?','Torsional or flexural-torsional buckling.','Only hydrostatic uplift.','Only fatigue in pure tension.','No other mode exists.','Some shapes can twist or buckle through coupled flexure and torsion.'),
    Q('Failure interaction','application','reasoning','A thin-walled compression section locally buckles before the member reaches its global column curve resistance. What governs?','The premature local instability must be accounted for; global resistance alone is insufficient.','The local buckling can be ignored.','The yield stress becomes infinite.','The effective length becomes zero.','The governing resistance is limited by the earliest relevant failure mode.'),
    Q('Design mindset','retrieval','concept','Why are several compression failure modes checked?','Because section slenderness, member slenderness and symmetry/restraint can activate different instabilities.','Because all columns fail identically.','Because axial force has no role.','Because only fabrication controls strength.','Compression behaviour is sensitive to geometry and restraint, so no single failure mode covers every member.')
  ]);

  add('Classification of Cross Section',[
    Q('Classification purpose','foundation','concept','Why are compression cross-sections classified by element slenderness?','To identify whether local buckling may limit usable cross-sectional strength.','To determine steel density.','To calculate only self-weight.','To select paint colour.','Plate-element width-to-thickness limits indicate susceptibility to local buckling.'),
    Q('Slender plate effect','core','reasoning','What happens when a compression plate element is very slender?','Local buckling can occur before uniform yielding over the full area.','It becomes immune to buckling.','Its elastic modulus increases.','Its yield stress doubles.','Slender plate elements may not fully develop gross-section compressive strength.'),
    Q('Effective area idea','core','concept','Why may a very slender compression section require an effective-area concept?','Because locally buckled portions cannot be treated as fully effective at the same stress.','Because gross area always becomes zero.','Because holes always add area.','Because density changes.','Effective-section methods represent reduced participation after local buckling.'),
    Q('Stocky element','application','reasoning','A section has plate elements well within the code slenderness limits. What benefit does this provide?','Local buckling is less likely to prevent development of the intended section resistance.','Global buckling is automatically impossible.','Effective length becomes zero.','Residual stress disappears.','Stocky elements help ensure cross-sectional capacity can be mobilized, though member buckling still requires checking.'),
    Q('Classification trap','trap','concept','Which statement is incorrect?','A compact cross-section guarantees that the entire column cannot buckle globally.','Section classification addresses local plate behaviour.','Global member buckling is a separate check.','Thin compression elements are more locally buckling-sensitive.','Cross-section classification does not replace member stability design.'),
    Q('Classification bridge','retrieval','concept','What two levels of instability must a compression-member designer distinguish?','Local plate buckling and overall member buckling.','Only weld and bolt failure.','Only bending and torsion of beams.','Only service deflection.','Section classification manages local behaviour, while column design manages overall stability.')
  ]);

  add('Behaviour of Compression Members',[
    Q('Short member behaviour','foundation','concept','How does a short compression member primarily respond as load rises?','Predominantly by axial shortening until material yielding becomes important.','By elastic lateral buckling at negligible load.','By pure tension.','By torsion only.','Stocky members behave mainly as compressed material rather than slender stability systems.'),
    Q('Intermediate member behaviour','core','concept','Why are intermediate columns more complex than ideal very short or very slender members?','Material yielding, residual stress, imperfections and buckling interact.','They have no axial stress.','They are always perfectly elastic.','Their length is irrelevant.','Real column curves bridge squash-type strength and elastic buckling.'),
    Q('Slenderness trend','core','reasoning','As effective slenderness increases, what generally happens to compression resistance?','It decreases because buckling becomes more influential.','It always increases.','It remains exactly fyA.','It becomes independent of E.','Longer/slenderer columns become stability-controlled.'),
    Q('Initial crookedness','application','reasoning','Why does a small initial out-of-straightness matter under axial compression?','The axial force acts through the lateral offset and creates bending.','It eliminates bending.','It increases area.','It prevents second-order effects.','Geometric imperfection turns nominal axial compression into combined compression and bending.'),
    Q('Post-buckling distinction','core','concept','For an ideal Euler column, what happens at the critical bifurcation load in the perfect model?','A straight equilibrium path becomes unstable and a laterally deflected equilibrium form is possible.','The member necessarily fractures instantly.','The area becomes zero.','The steel changes grade.','Euler buckling is a stability bifurcation, not a material fracture criterion.'),
    Q('Behaviour summary','retrieval','concept','Which continuum best summarizes compression-member behaviour?','Stocky yielding → inelastic interaction → elastic buckling as slenderness increases.','Tension rupture → fatigue → corrosion only.','Shear yielding only.','No change with slenderness.','Column behaviour transitions from material strength control to stability control with increasing slenderness.')
  ]);

  add('Elastic Buckling of Slender Compression Members',[
    Q('Euler relation','core','formula','Which expression gives the Euler elastic critical load for an ideal prismatic column?','Pcr = π²EI/(KL)².','Pcr = fyA.','Pcr = AE/L.','Pcr = WL/8.','Euler load depends on flexural rigidity and the square of effective length.'),
    Q('Length sensitivity','application','numerical','If the effective length of an ideal Euler column doubles with EI unchanged, the Euler load becomes:','One quarter of its original value.','Twice its original value.','Four times its original value.','Unchanged.','Pcr varies inversely with (KL)².'),
    Q('Stiffness sensitivity','core','reasoning','If I doubles while E and effective length remain unchanged, what happens to Euler load?','It doubles.','It halves.','It becomes one quarter.','It is unchanged.','Euler critical load is directly proportional to EI.'),
    Q('Weak-axis buckling','application','reasoning','A section has Iy much smaller than Iz and equal effective lengths about both axes. Which flexural mode is more critical?','Buckling about the axis with the smaller I.','Buckling about the larger-I axis.','Both have identical Pcr regardless of I.','No buckling can occur.','Smaller flexural rigidity gives the lower Euler load.'),
    Q('Radius of gyration','core','formula','Which relation defines radius of gyration?','r = √(I/A).','r = I/A.','r = √(A/I).','r = AI.','Radius of gyration packages section area and second moment into a length measure used in slenderness.'),
    Q('Effective slenderness','retrieval','formula','Which expression is the effective slenderness ratio of a column?','KL/r.','Kr/L.','A/L.','EI/A.','Effective length divided by radius of gyration is the central geometric slenderness measure.')
  ]);

  add('Behaviour of Real Compression Members',[
    Q('Ideal versus real','foundation','concept','Which feature distinguishes a real column from the perfect Euler idealization?','Initial imperfections and residual stresses are present.','Its material has infinite E.','It is perfectly straight by definition.','It has no end restraint.','Real members contain geometric and material imperfections.'),
    Q('Residual stress effect','core','reasoning','Why can residual stresses reduce real-column resistance?','Some fibres can yield earlier, reducing effective tangent stiffness before gross-section yielding.','They always increase Euler load.','They eliminate bending.','They increase radius of gyration.','Residual stresses contribute to gradual yielding and inelastic buckling.'),
    Q('Crookedness effect','core','reasoning','What does initial crookedness do to an axially compressed column?','Creates bending from the axial force acting through the initial offset.','Guarantees concentric stress.','Eliminates P-δ effects.','Increases area.','Imperfections produce bending from the start of loading.'),
    Q('No perfect bifurcation','core','concept','Why does a real imperfect column not usually show the sharp ideal Euler bifurcation?','It deflects laterally from the beginning and response evolves continuously.','It has no stiffness.','It carries only tension.','Its yield stress is zero.','Imperfections remove the perfectly straight pre-buckling path of the ideal model.'),
    Q('Strength curve meaning','application','concept','Why are design column curves lower than the ideal Euler curve over important slenderness ranges?','They account for imperfections, residual stress and inelastic effects.','They ignore all real effects.','They use a larger E than steel.','They assume zero axial force.','Design curves calibrate real-column behaviour rather than perfect elastic theory alone.'),
    Q('Real-column takeaway','retrieval','concept','Which statement best summarizes real compression behaviour?','Imperfections convert nominal compression into combined compression/bending and reduce idealized stability.','Real columns are stronger than Euler columns in every case.','Residual stress is irrelevant.','Initial curvature improves stability.','The chapter emphasizes departures from ideal theory caused by real fabrication and geometry.')
  ]);

  add('Development of Multiple Column Curves',[
    Q('Why multiple curves','foundation','concept','Why does modern steel design use more than one column buckling curve?','Different section shapes, axes and fabrication routes have different imperfection/residual-stress sensitivity.','Every column behaves identically.','Curves are chosen by paint colour.','Only yield stress matters.','A family of curves better represents distinct real-column behaviours.'),
    Q('Imperfection factor','core','concept','What does the buckling-curve imperfection parameter represent broadly?','The severity of real-column imperfections embodied in the design curve.','Steel density.','Concrete strength.','Bolt pretension.','Different imperfection factors shift the reduction curve to reflect different member behaviours.'),
    Q('Curve severity','core','reasoning','For the same nondimensional slenderness, which curve should give lower design resistance?','The curve representing larger imperfection sensitivity.','The curve representing smaller imperfections.','All curves must be identical.','The curve with no axial force.','Greater imperfection sensitivity produces a stronger reduction from squash strength.'),
    Q('Section/axis selection','application','reasoning','Why can the same rolled section use different buckling curves about its major and minor axes?','Residual-stress patterns and geometry influence the two buckling modes differently.','The steel grade changes with axis.','Area changes when the axis changes.','Density changes with axis.','Buckling behaviour depends on the mode, not only gross area.'),
    Q('Design use','core','sequence','What is the correct conceptual sequence when using multiple column curves?','Identify section/fabrication/axis → select buckling curve → evaluate slenderness reduction.','Select a random curve → ignore slenderness.','Use Euler load only for all columns.','Use area only.','Curve choice precedes the reduction-factor/design-stress calculation.'),
    Q('Multiple-curves purpose','retrieval','concept','What problem do multiple column curves solve?','They avoid forcing all real columns onto one universal imperfection model.','They remove the need for section properties.','They eliminate effective length.','They make all columns perfectly straight.','Different real-column classes require different calibrated resistance curves.')
  ]);

  add('Sections Used for Compression Members',[
    Q('Section choice objective','foundation','concept','What is a desirable geometric feature for an efficient compression section?','Adequate radius of gyration about both potential buckling axes.','All area concentrated at the centroid.','Very small weak-axis I.','Maximum eccentricity.','Compression sections benefit from distributing material to provide stiffness against likely buckling modes.'),
    Q('Weak-axis balance','core','reasoning','Why is a section with extremely unequal radii of gyration often inefficient as a column?','The weak axis can govern long before the strong-axis capacity is utilized.','The strong axis always governs.','Radius of gyration has no effect.','Area becomes zero.','Column strength is controlled by the most critical effective slenderness.'),
    Q('Common forms','foundation','classification','Which is a common steel compression-member form?','Rolled I/H section or built-up/laced section.','Cable only.','Roof sheeting only.','Thin membrane only.','Rolled shapes and built-up arrangements are common column/strut forms.'),
    Q('Built-up need','application','reasoning','Why may a built-up section be selected instead of a single rolled section?','To obtain required area/stiffness and more favourable geometry when one rolled shape is unsuitable.','To eliminate all connectors.','To make the member flexible.','To reduce radius of gyration intentionally.','Built-up members allow tailoring of area and stiffness.'),
    Q('Hollow-section benefit','core','concept','What general stability advantage can a hollow section offer as a compression member?','Relatively efficient distribution of material around both axes.','Zero torsional stiffness.','No local buckling possibility.','No need for connections.','Closed shapes can provide efficient biaxial stiffness, though local slenderness still requires checking.'),
    Q('Selection rule','retrieval','concept','What should govern section selection for a compression member?','Strength, buckling about all relevant axes, connection/detailing and constructability.','Area alone.','Colour alone.','Weight alone regardless of stability.','A practical column section must work as both a structural member and a buildable detail.')
  ]);

  add('Effective Length of Compression Members',[
    Q('Effective length meaning','foundation','concept','What does effective length represent in column buckling design?','The equivalent pin-ended length having the same elastic buckling load.','The physical length in every case.','The bolt spacing.','The flange width.','End rotational/translational restraint changes buckling strength and is represented through KL.'),
    Q('Effective length formula','core','formula','How is effective length written?','Le = KL.','Le = K/L.','Le = L/K² always.','Le = r/K.','K is the effective-length factor multiplying actual member length.'),
    Q('Restraint effect','core','reasoning','If end restraint against rotation and/or sway becomes stronger, what generally happens to effective length?','It tends to reduce.','It must increase without limit.','It is always exactly L.','It becomes unrelated to buckling.','Greater restraint raises buckling resistance and is represented by a shorter equivalent effective length.'),
    Q('Sway frame effect','application','reasoning','Why can an unbraced/sway frame give larger column effective lengths than a comparable braced frame?','Frame translation couples column end rotations and can reduce stability.','Sway increases EI.','Bracing reduces section area.','Unbraced frames have no axial loads.','Translational restraint is an important boundary condition in column stability.'),
    Q('Different planes','core','concept','Can one column have different effective lengths about its two principal axes?','Yes, because restraints and framing can differ by plane.','No, effective length is a scalar fixed only by material.','Only concrete columns can.','Only if area changes.','Column restraint conditions commonly differ in orthogonal planes.'),
    Q('Practical determination','retrieval','concept','What information is needed to determine effective length correctly?','Member end rotational restraint, translational restraint and surrounding-frame behaviour.','Only steel density.','Only yield stress.','Only base-plate thickness.','Effective length is fundamentally a system/restraint property, not just a member dimension.')
  ]);

  add('Flexural-Torsional Buckling',[
    Q('Mode definition','foundation','concept','What is flexural-torsional buckling?','An instability involving coupled lateral bending and twist.','Pure axial shortening only.','Local plate yielding only.','Pure tension rupture.','Some open sections lose stability through simultaneous flexure and torsion.'),
    Q('Susceptible shapes','core','classification','Which sections are especially susceptible to coupled torsional effects?','Open monosymmetric or unsymmetric sections.','Only solid circular bars.','Only doubly symmetric closed tubes.','Only cables.','Lack of symmetry and low torsional/warping stiffness can activate coupled modes.'),
    Q('Why flexure alone may fail','core','reasoning','Why is checking only Euler flexural buckling insufficient for some compression sections?','A lower coupled flexural-torsional mode may exist.','Euler always includes every torsional mode automatically.','Torsion cannot occur under compression.','Area alone controls all buckling.','The governing eigenmode can involve twist as well as lateral displacement.'),
    Q('Shear-centre relevance','application','concept','Why are centroid and shear-centre relationships relevant in torsional column stability?','Their geometry affects coupling between flexure and torsion.','They determine steel density.','They eliminate warping.','They are always identical for every open section.','Unsymmetric sections can have coupled flexural/torsional behaviour because key geometric centres do not coincide simply.'),
    Q('Design implication','core','reasoning','A compression section has good flexural stiffness but very weak torsional stiffness. What should the designer consider?','A torsional or flexural-torsional buckling check may govern.','Flexural stiffness guarantees safety.','Torsion is impossible under axial compression.','Only local yielding matters.','Strong bending stiffness alone does not rule out a coupled instability.'),
    Q('Mode takeaway','retrieval','concept','What is the key lesson of flexural-torsional buckling?','Compression stability may be governed by a coupled deformation mode, not a single-axis flexural mode.','All columns buckle only about the weak principal axis.','Twist always increases resistance.','Warping restraint never matters.','The chapter extends column stability beyond simple Euler flexure.')
  ]);

  add('Columns with No Axis of Symmetry',[
    Q('Unsymmetric challenge','foundation','concept','Why are columns with no axis of symmetry more complex to analyse?','Flexural and torsional responses can be strongly coupled.','They cannot carry axial force.','They always have zero shear centre offset.','They never buckle.','Unsymmetric geometry removes simplifications available to doubly symmetric sections.'),
    Q('Principal axes','core','concept','For an unsymmetric section, why are principal axes useful?','They identify directions in which product of inertia vanishes for flexural analysis.','They determine paint thickness.','They make torsion impossible.','They are always horizontal and vertical.','Principal-axis properties help describe bending, though torsional coupling may still remain.'),
    Q('Centroid/shear centre','core','reasoning','What geometric feature can intensify coupled behaviour in an unsymmetric column?','Centroid and shear centre may not coincide.','Area is always zero.','Yield stress varies by axis.','Length disappears.','Offsets among geometric centres influence torsion-flexure coupling.'),
    Q('Design trap','trap','reasoning','Which assumption is unsafe for a column with no symmetry axis?','Treating it automatically as a simple pin-ended Euler column about one centroidal axis only.','Checking possible coupled instability.','Using actual section properties.','Considering torsional stiffness.','Unsymmetric shapes may require a more general stability model.'),
    Q('Section choice','application','reasoning','If an unsymmetric compression shape produces difficult coupled buckling, what practical design response may help?','Select a more symmetric/stable section or provide restraint where feasible.','Reduce all restraints.','Increase eccentricity.','Ignore torsion.','Section choice and bracing can simplify or improve stability behaviour.'),
    Q('Unsymmetric takeaway','retrieval','concept','What distinguishes no-symmetry columns from ordinary doubly symmetric columns?','Their stability equations can couple bending and torsion more strongly.','They have no centroid.','They cannot be fabricated.','They always fail by yielding only.','Geometry changes the nature of the possible buckling modes.')
  ]);

  add('Prevention of Buckling Failure',[
    Q('Reduce slenderness','foundation','concept','Which action directly helps prevent flexural buckling?','Reduce effective length or increase radius of gyration.','Increase effective length.','Reduce I.','Remove lateral restraints.','Since slenderness is KL/r, reducing KL or increasing r improves stability.'),
    Q('Intermediate restraint','core','reasoning','Why can an intermediate brace increase column buckling resistance?','It reduces the unrestrained/effective buckling length in the restrained plane.','It reduces E.','It increases initial crookedness.','It removes area.','Shorter buckling lengths raise critical load.'),
    Q('Section redistribution','application','reasoning','For the same approximate area, why can moving material farther from the weak axis improve column stability?','It increases I and radius of gyration about that axis.','It decreases radius of gyration.','It reduces E.','It increases effective length.','Better material distribution increases flexural rigidity and lowers slenderness.'),
    Q('Local buckling prevention','core','concept','What helps prevent local buckling in a compression section?','Keep plate-element width-to-thickness ratios within appropriate limits.','Increase plate slenderness.','Remove stiffeners from slender plates.','Increase unsupported width indefinitely.','Stockier plate elements have higher local-buckling resistance.'),
    Q('Imperfection control','core','concept','Why do fabrication straightness and alignment tolerances matter?','They limit initial eccentricity/crookedness that magnifies bending under compression.','They change steel grade.','They eliminate axial load.','They guarantee zero residual stress.','Smaller geometric imperfections improve real-column behaviour.'),
    Q('Buckling prevention summary','retrieval','concept','Which strategy best captures buckling prevention?','Control slenderness, provide restraint, choose stable geometry and detail members accurately.','Rely on yield strength alone.','Remove all bracing.','Ignore weak-axis behaviour.','Stability is improved by both member geometry and system restraint.')
  ]);

  add('Single Angle Struts',[
    Q('Angle strut complication','foundation','concept','Why is a single-angle strut not a simple concentric column in many connections?','It is often connected through one leg, creating eccentricity and coupled bending.','Its centroid always lies on the connected leg.','It carries tension only.','Angles cannot buckle.','Single-leg connection makes angle-strut behaviour inherently eccentric.'),
    Q('Unsymmetric section effect','core','reasoning','Why can a single angle exhibit flexural-torsional tendencies?','Its open unsymmetric geometry couples bending and twisting.','Its torsional stiffness is infinite.','It has two axes of symmetry.','It is a closed tube.','Angle geometry makes simple weak-axis Euler reasoning incomplete in some cases.'),
    Q('Connection length','core','concept','Why does the end connection configuration matter for an angle strut?','It influences eccentricity and effective restraint.','It changes steel density.','It removes all compression.','It determines only colour.','The connected leg and fastener arrangement affect actual member boundary conditions.'),
    Q('Design approach','application','reasoning','What should be avoided when designing a single-angle compression member?','Assuming pure concentric compression without accounting for prescribed angle-strut provisions/eccentricity effects.','Checking slenderness.','Considering the connected leg.','Using actual length.','Single-angle struts need treatment reflecting their connection and unsymmetric behaviour.'),
    Q('Member orientation','core','reasoning','Why can angle orientation relative to gusset and bracing plane affect response?','It changes the relationship between load path, principal axes and eccentricity.','It changes yield stress.','It changes material density.','It makes length zero.','Orientation influences how axial load and secondary bending act on the angle.'),
    Q('Angle takeaway','retrieval','concept','What is the central lesson for single-angle struts?','Connection eccentricity and unsymmetric buckling behaviour must be included in design.','Treat them exactly like solid circular columns.','Ignore torsion.','Use area alone.','Their geometry and one-leg connection require specific compression-member treatment.')
  ]);

  add('Design of Compression Members',[
    Q('Design sequence start','foundation','sequence','What should be established first in compression-member design?','Factored axial force, member length/restraints and trial section properties.','Paint colour.','Final bolt torque only.','Concrete cover only.','Loads, geometry and restraint define the stability problem before resistance is checked.'),
    Q('Critical slenderness','core','sequence','After selecting a trial section, what stability quantity is evaluated about relevant axes?','Effective slenderness KL/r.','Only gross area.','Only flange width.','Only density.','The governing effective slenderness feeds the column buckling resistance.'),
    Q('Curve selection','core','sequence','What follows evaluation of section type, fabrication and buckling axis?','Select the appropriate buckling curve/class and obtain compression design strength.','Ignore imperfections.','Use fyA regardless of slenderness.','Set K to zero.','Column resistance uses a calibrated buckling curve matched to the member class.'),
    Q('Resistance form','core','concept','At a high level, design axial resistance is obtained from:','Effective area multiplied by the design compressive stress/resistance level.','Length multiplied by density only.','Moment divided by span only.','E multiplied by temperature.','The reduced compressive strength is applied to the effective cross-sectional area.'),
    Q('Iterative design','application','reasoning','A trial section fails the compression-resistance check. What is the normal design response?','Revise section size/geometry or restraint and repeat the checks.','Ignore the failure.','Reduce load without basis.','Delete the buckling check.','Compression-member design is iterative until strength, stability and detailing are satisfactory.'),
    Q('Complete check','retrieval','concept','Which set best represents a complete compression-member design?','Section classification, effective length/slenderness, buckling resistance and practical detailing.','Area only.','Yield stress only.','Euler load only.','Design combines local section behaviour, global stability and constructability.')
  ]);

  add('Built-up Compression Members',[
    Q('Built-up definition','foundation','concept','What is a built-up compression member?','Two or more main components connected so they act together as one column/strut.','A single solid bar only.','A cable bundle.','A welded beam with no compression.','Built-up columns combine components using lacing, battens or other connectors.'),
    Q('Lacing purpose','core','concept','What is the structural purpose of lacing in a built-up column?','Tie components together and transfer shear so the assembly acts as a unit.','Carry only roof sheeting.','Eliminate axial force.','Increase individual-member spacing without limit.','Lacing provides interaction between the main components.'),
    Q('Batten purpose','core','concept','What is the alternative role of battens?','Transverse plates/connectors tie the main components and transmit required shear/moment between them.','They are decorative only.','They replace the column bases.','They carry no force.','Batten systems maintain composite action of the built-up column components.'),
    Q('Shear deformation','core','reasoning','Why can a laced/battened built-up column require an effective-slenderness increase relative to an ideal solid member?','Connector-system shear deformation reduces overall stiffness.','Lacing makes E infinite.','Battens eliminate deflection.','Area becomes zero.','The code accounts for non-rigid shear interaction of separated components.'),
    Q('Component slenderness','application','reasoning','Why must individual components between lacing/batten points also be sufficiently stocky?','They can buckle locally between connectors even if the built-up member as a whole is adequate.','Only the whole-member slenderness matters.','Components carry no compression.','Connections prevent every possible buckle.','Built-up design has both global and component-level stability requirements.'),
    Q('Built-up takeaway','retrieval','concept','What makes a built-up column behave as one member?','Adequate lacing/battens and connections transferring the interaction forces between components.','Paint only.','Contact without any connectors in all cases.','Concrete cover only.','The connecting system is essential to composite column action.')
  ]);

  add('Compression Members Composed of Two Components Back-to-back',[
    Q('Back-to-back concept','foundation','concept','What is a back-to-back compression member?','Two angles/channels/tees arranged together and connected along their length.','Two beams crossing without connection.','A single tube.','Two tension cables.','Paired shapes can form a practical built-up strut when connected to act together.'),
    Q('Intermediate connections','core','reasoning','Why are intermediate connections required between back-to-back components?','To limit individual-component slenderness and enable combined action.','To increase free buckling length.','To remove shear transfer.','To create eccentricity.','Without sufficient ties, components could buckle independently.'),
    Q('End connections','core','concept','Why must the ends of paired components be securely tied together?','To establish the intended load sharing and built-up action from the member ends.','To make each component independent.','To eliminate axial compression.','To reduce area to zero.','End tying is essential to make the pair function as a unit.'),
    Q('Packing','core','concept','When separated back-to-back components are connected by bolts, why may packing/spacers be required?','To provide solid load transfer and maintain the intended separation/connection geometry.','To reduce bolt diameter to zero.','To eliminate all contact.','To increase unsupported spacing.','Packings support reliable connection action between separated components.'),
    Q('Component stability','application','reasoning','The pair is globally adequate but each angle between intermediate connections is too slender. Is the design satisfactory?','No, individual component buckling between connections must also be controlled.','Yes, global adequacy overrides all component checks.','Yes, because angles cannot buckle.','No, because paired members cannot carry compression.','Both whole-member and component slenderness requirements apply.'),
    Q('Back-to-back takeaway','retrieval','concept','What is the governing detailing idea for paired compression components?','Use sufficient end and intermediate connections so the components act together and do not buckle independently.','Connect only one end.','Use no packing where separation exists.','Ignore connector forces.','The paired system depends on connector spacing and strength.')
  ]);

  add('Column Bases and Caps',[
    Q('Base function','foundation','concept','What is the primary function of a steel column base?','Transfer column axial force, moment and shear into the foundation safely.','Support only roof sheeting.','Eliminate all reactions.','Carry tension only.','Base plates and anchorage spread and transfer column actions to concrete/foundation.'),
    Q('Bearing pressure','core','reasoning','Why is a base plate larger than the column footprint commonly required?','To spread compression to a bearing pressure the support can resist.','To increase column slenderness.','To reduce contact area.','To eliminate axial load.','A larger plate distributes concentrated steel-column force over a larger foundation area.'),
    Q('Moment at base','core','concept','What changes when a column base must transmit significant moment as well as compression?','Bearing becomes nonuniform and anchors/base-plate bending can become important.','Pressure remains uniform by definition.','Anchors become unnecessary in every case.','The column becomes a tension cable.','Moment creates compression variation and possibly uplift/tension demands.'),
    Q('Shear transfer','application','reasoning','How can column-base shear be transferred when friction alone is insufficient?','Through suitable anchorage or a shear key/detail designed for the shear.','By reducing plate area.','By removing anchor bolts.','By increasing column effective length.','Base design must provide a deliberate load path for shear.'),
    Q('Column cap role','foundation','concept','What is the purpose of a column cap or cap plate in relevant framing?','Provide a practical bearing/connection interface for loads delivered to the column top.','Increase unsupported length.','Carry only paint.','Remove axial compression.','Caps help distribute and connect supported member reactions into the column.'),
    Q('Base takeaway','retrieval','concept','Which design principle governs bases and caps?','Transmit concentrated member actions through adequately stiff and strong bearing/connection details.','Assume zero contact stress.','Ignore moment and shear.','Use the thinnest possible plate without checking.','These details are force-transfer interfaces, not merely geometric terminations.')
  ]);

  add('Compression Members with Other Materials and Shapes',[
    Q('Beyond rolled steel','foundation','concept','Why does the chapter discuss compression members with other materials or shapes?','Column behaviour depends on stiffness, strength, geometry and restraint, not on one rolled-section family only.','Only I-sections can carry compression.','Material has no influence.','Shape has no influence.','The same stability principles extend to alternative structural forms with appropriate properties.'),
    Q('Composite/cased idea','core','concept','What can encasing or combining a steel column with another material potentially change?','Stiffness, strength, fire behaviour and restraint of the steel component.','Only paint colour.','Only steel density.','Nothing structural.','Composite/cased arrangements alter member properties and interaction.'),
    Q('Arch compression','core','concept','Why are arches relevant to compression-member discussion?','Their geometry carries substantial load through axial compression along the arch, though bending may also occur.','Arches carry pure tension only.','Arches cannot buckle.','They have no reactions.','Arches are structural forms in which compression action is fundamental.'),
    Q('Shape effect','application','reasoning','Two columns use the same steel area but very different cross-sectional geometry. Can their buckling resistance differ?','Yes, because I and radius of gyration depend strongly on geometry.','No, area alone fixes buckling resistance.','No, E changes to compensate.','Only length matters.','Distribution of material controls flexural rigidity and therefore stability.'),
    Q('Material stiffness','core','reasoning','For otherwise identical ideal columns, what happens to Euler load if elastic modulus E is lower?','Euler load is lower.','Euler load is higher.','Euler load is unchanged.','Euler load becomes fyA.','Pcr is directly proportional to E.'),
    Q('Generalization takeaway','retrieval','concept','What principle carries across different compression-member materials and shapes?','Check material resistance together with geometry-dependent stability.','Use area only.','Ignore end restraint.','Assume all shapes share one radius of gyration.','Compression design always couples section properties with stability behaviour.')
  ]);

  add('Displacement',[
    Q('Why displacement matters','foundation','concept','Why should compression-member displacement be considered in addition to strength?','Lateral deflection can affect serviceability and amplify second-order bending.','Displacement never affects compression members.','Only tension members deflect.','Deflection increases E.','Compression acting through deflection creates additional moments.'),
    Q('P-delta relation','core','formula','Which simple expression represents additional moment from axial force P acting through lateral displacement δ?','Approximately Pδ.','P/δ.','EI/P.','Aδ.','Second-order member moment arises from axial load times lateral offset.'),
    Q('Imperfection link','core','reasoning','Why can an initially crooked column have lateral displacement even before a theoretical bifurcation load?','Its initial geometry is already offset from the load line.','Its E is zero.','It carries no axial force.','Its area changes with load.','Real columns start with imperfections and therefore bend progressively under compression.'),
    Q('Near-critical behaviour','application','reasoning','As a slender column approaches its stability limit, what happens to lateral displacement sensitivity?','It increases strongly.','It decreases to zero.','It becomes independent of load.','The member straightens automatically.','Near instability, small load changes can produce large displacement increases.'),
    Q('Bracing effect','core','reasoning','How can lateral bracing affect column displacement in the restrained direction?','It limits lateral movement and reduces the relevant buckling length.','It increases sway intentionally.','It removes axial load.','It makes I zero.','Restraint controls both displacement shape and stability.'),
    Q('Displacement takeaway','retrieval','concept','Why is displacement inseparable from compression stability?','Because axial force acting on deformed geometry produces destabilizing second-order moments.','Because displacement changes steel grade.','Because columns carry no bending.','Because Euler theory ignores geometry.','Geometric nonlinearity makes deformation part of the force equilibrium problem.')
  ]);

  add('Examples',[
    Q('Example workflow','foundation','sequence','In a worked compression-member example, what should be checked after selecting a trial section?','Section classification/properties, effective slenderness and design compression resistance.','Paint system only.','Concrete slump only.','Bolt colour only.','Worked examples apply the chapter sequence from geometry and restraint to resistance.'),
    Q('Axis comparison','core','reasoning','A worked example gives different KL/r values about two axes. Which one is normally more critical for flexural buckling?','The larger effective slenderness, subject to the applicable buckling curve.','Always the smaller slenderness.','Both are ignored.','Only gross area matters.','Column design compares relevant axis/mode resistances.'),
    Q('Trial fails','application','reasoning','A worked trial section has design compression resistance below the factored axial force. What conclusion follows?','Revise the section/restraint and repeat the design.','Accept it because trial sections need not pass.','Delete the axial load.','Use Euler load as the applied load.','The design resistance must meet or exceed the required factored action.'),
    Q('Built-up example logic','core','sequence','In a built-up-column example, what must be designed in addition to the main components?','The lacing/batten system and its connections.','Only paint.','Only base concrete.','Nothing else.','The interconnecting system is structural and must transfer the specified interaction forces.'),
    Q('Base example logic','core','sequence','A column-base example normally checks which interface first?','Bearing/load distribution between base plate and supporting foundation, along with plate/anchor actions.','Roof sheeting.','Purlin sag.','Cable tension only.','The base is designed as the force-transfer interface into the support.'),
    Q('Examples purpose','retrieval','concept','What should you extract from Chapter 9 examples besides final section sizes?','The repeatable decision sequence linking load, restraint, slenderness, buckling curve and resistance.','Only the final weight.','Only the steel grade.','Only one numerical answer.','Examples teach the design workflow, not just isolated arithmetic.')
  ]);

  add('Summary',[
    Q('Summary hierarchy','foundation','concept','Chapter 9 summary — what is the main hierarchy of compression behaviour?','Cross-section behaviour, member slenderness, imperfections and system restraint together govern resistance.','Yield stress alone governs every column.','Area alone governs every column.','Connection details never matter.','The chapter combines local, global and real-member effects.'),
    Q('Euler role','core','concept','How should Euler buckling be viewed in the chapter summary?','As the ideal elastic foundation from which real-column design is developed.','As the complete design rule for every column.','As a tension formula.','As a weld-strength equation.','Real design modifies ideal buckling to account for imperfections and inelastic response.'),
    Q('Multiple curves role','core','concept','Why are multiple design curves retained in the summary?','Different section/fabrication/mode classes need different imperfection allowances.','To vary steel density.','To avoid calculating slenderness.','To remove effective length.','The curves represent different real-column sensitivities.'),
    Q('Effective length role','core','concept','What system property appears repeatedly in the chapter summary?','End/sway restraint represented through effective length.','Paint thickness.','Concrete cover.','Bolt washer size only.','Column stability depends strongly on how the surrounding structure restrains the member.'),
    Q('Built-up role','application','concept','What does the summary emphasize for built-up compression members?','Component interaction through lacing/battens must be designed, not assumed.','Components act together without connections.','Only area matters.','Built-up columns cannot buckle.','Connector systems are integral to built-up member stability.'),
    Q('Summary recall','retrieval','concept','Which phrase best captures Chapter 9?','Compression resistance is a strength-plus-stability problem.','Compression resistance equals fyA for all lengths.','Columns never bend.','Buckling is only a local plate phenomenon.','The chapter’s central message is that stability fundamentally modifies compressive strength.')
  ]);

  add('Exercises',[
    Q('Exercise skill 1','foundation','application','Which calculation should you be able to perform before attempting Chapter 9 design exercises?','Compute radius of gyration and KL/r about relevant axes.','Compute only paint volume.','Compute only bolt-hole area in tension.','Compute only wind pressure.','Effective slenderness is the starting quantity for column buckling checks.'),
    Q('Exercise skill 2','core','application','A Chapter 9 exercise changes end restraint but keeps section and actual length fixed. What quantity changes directly?','Effective length factor K and therefore KL/r.','Yield stress fy.','Section area A.','Elastic modulus E.','Boundary conditions are represented through K.'),
    Q('Exercise skill 3','core','application','An exercise asks you to compare two candidate sections of equal area. Which property is especially important for buckling?','Radius of gyration / second moment about the governing axis.','Density, which is essentially the same steel value.','Paint colour.','Bolt pitch unrelated to the member.','Column efficiency depends strongly on material distribution.'),
    Q('Exercise skill 4','application','reasoning','An exercise gives a laced built-up column. What extra checks are required beyond whole-member axial resistance?','Lacing/component slenderness and connection forces.','Only roof drainage.','Only concrete cover.','No extra checks.','Built-up systems have component and connector requirements.'),
    Q('Exercise skill 5','application','reasoning','An exercise gives an unsymmetric or angle strut. What should trigger caution?','Eccentric/coupled buckling behaviour may require special provisions.','Area alone is always sufficient.','Torsion can never occur.','Connection orientation is irrelevant.','Unsymmetric compression members are not always captured by simple one-axis Euler checks.'),
    Q('Exercise objective','retrieval','concept','What is the best way to use the Chapter 9 exercises?','Practice identifying the governing mode and carrying a complete stability-based design sequence.','Memorize only final answers.','Skip restraint assumptions.','Ignore failed trial sections.','Exercises reinforce the logic of compression design under varied geometry and restraint.')
  ]);

  add('Review Questions',[
    Q('Review: short vs slender','foundation','classification','Review Questions — what primarily distinguishes short and slender compression-member failure?','Short members are material-strength dominated; slender members are buckling dominated.','Both always fail identically.','Short members fail only in tension.','Slenderness affects only self-weight.','The chapter organizes behaviour by the increasing influence of instability.'),
    Q('Review: real columns','core','concept','Why is a real column weaker than the perfect Euler ideal over much of the practical range?','Initial crookedness, residual stress and inelastic response reduce ideal stability.','Real E is infinite.','Real columns have no area.','Imperfections increase capacity.','Real-column design curves account for these nonideal effects.'),
    Q('Review: K factor','core','concept','What does the effective-length factor K encode?','Rotational/translational restraint and frame stability conditions.','Material density.','Yield stress.','Plate thickness only.','K is a boundary-condition/system parameter.'),
    Q('Review: curves','core','concept','Why is one universal buckling curve not used for every steel column?','Section shape, axis and fabrication lead to different imperfection/residual-stress behaviour.','Codes prefer random curves.','Area changes with curve.','E changes by axis.','Multiple curves better fit observed real-column strengths.'),
    Q('Review: built-up','application','concept','What ensures separated components in a built-up column act together?','Properly designed lacing/battens and their connections.','Paint only.','Gravity only.','No connectors.','The connector system transfers interaction forces and restrains individual components.'),
    Q('Review: final principle','retrieval','reasoning','A column has adequate squash strength fyA but excessive effective slenderness. Can squash strength alone justify the design?','No, buckling resistance may govern well below fyA.','Yes, fyA always governs.','Yes, slenderness is only serviceability.','No, because columns carry no axial force.','Compression design must satisfy stability as well as cross-sectional strength.')
  ]);
})();