(() => {
  const B=window.REVISION_BANK=window.REVISION_BANK||{};
  const add=(k,a)=>B[k]=(B[k]||[]).concat(a);

  add('15:Introduction',[
    {id:'ch15-intro-durability',title:'Durability as a design objective',level:'foundation',kind:'concept',q:'Why does the chapter treat durability as part of structural design rather than only a maintenance issue?',choices:['Because the structure must retain its intended function through the anticipated exposure and service life','Because durability changes steel density','Because corrosion affects appearance only','Because strength checks are unnecessary'],answer:0,explanation:'The chapter defines durability in terms of satisfactory performance over the intended service life without unacceptable corrosion-related loss of section or strength.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-sls',title:'Limit-state classification',level:'core',kind:'classification',q:'How does the chapter classify durability and corrosion in the design framework?',choices:['As serviceability-limit-state considerations','Only as accidental loads','Only as fabrication tolerances','As plastic-collapse mechanisms'],answer:0,explanation:'The introduction explicitly treats durability and corrosion as serviceability-limit-state criteria.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-choice',title:'Protection-system choice',level:'core',kind:'reasoning',q:'Which combination most directly governs the corrosion-protection method selected in the chapter?',choices:['Environmental severity, structural importance, initial cost and life-cycle cost','Only member span','Only steel density','Only paint colour'],answer:0,explanation:'The chapter says the protection method depends on environmental severity, importance of the structure, and both initial and life-cycle cost.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-loss',title:'What durability protects',level:'core',kind:'recognition',q:'Which deterioration does the chapter definition of a durable steel structure specifically seek to avoid?',choices:['Loss of cross-sectional area and strength due to corrosion','Increase in Young’s modulus','Decrease in member length from loading','Increase in steel density'],answer:0,explanation:'A durable structure should perform without unacceptable corrosion-related loss of cross-sectional area and strength.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-system',title:'Durability system',level:'application',kind:'reasoning',q:'Which approach best follows the chapter’s durability philosophy?',choices:['Coordinate material, detailing, fabrication, erection, surface protection, inspection and maintenance','Rely on paint alone regardless of exposure','Ignore inaccessible surfaces','Design only for initial strength'],answer:0,explanation:'The chapter treats durability as a coordinated strategy involving material selection, detailing, fabrication, erection and protection.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-lifecycle',title:'Life-cycle economy',level:'application',kind:'reasoning',q:'Why can a protection system with a higher initial cost still be preferable?',choices:['Lower inspection, repair and recoating costs can make it more economical over the service life','Higher initial cost always means lower durability','Maintenance cost is excluded from structural decisions','Corrosion stops after erection'],answer:0,explanation:'Life-cycle cost, not initial cost alone, is part of the chapter’s durability decision framework.',source:'Subramanian supplementary Ch.19 Introduction'},
    {id:'ch15-intro-retrieval',title:'Durability retrieval',level:'retrieval',kind:'concept',q:'Which statement is inconsistent with the chapter introduction?',choices:['Durability can be postponed until after construction because detailing has no effect','Exposure conditions influence durability decisions','Life-cycle cost matters','Surface protection is one part of the durability strategy'],answer:0,explanation:'Detailing and other design-stage decisions directly affect corrosion and durability, so they cannot be postponed to maintenance alone.',source:'Subramanian supplementary Ch.19 Introduction'}
  ]);

  add('15:Corrosion of Steel',[
    {id:'ch15-cor-electrochemical',title:'Electrochemical mechanism',level:'foundation',kind:'concept',q:'What is the basic nature of the corrosion process described for structural steel?',choices:['An electrochemical process involving anodic and cathodic regions','A purely elastic deformation process','A mechanical buckling mechanism','A thermal expansion process only'],answer:0,explanation:'The chapter describes corrosion as electrochemical, analogous to a miniature battery with anodic and cathodic regions.',source:'Subramanian supplementary Ch.19 §19.1'},
    {id:'ch15-cor-anode',title:'What happens at the anode?',level:'core',kind:'concept',q:'In the chapter’s battery analogy, what happens to the anodic region?',choices:['It supplies electrons and is consumed by corrosion','It becomes perfectly protected','It gains steel thickness','It carries no electrochemical reaction'],answer:0,explanation:'The anodic body supplies electrons to the cathode and is the region that is attacked.',source:'Subramanian supplementary Ch.19 §19.1'},
    {id:'ch15-cor-pitting',title:'Pitting danger',level:'core',kind:'reasoning',q:'Why is pitting corrosion potentially more dangerous than uniform corrosion?',choices:['It is localized, difficult to detect and pits can act as stress raisers','It always removes material uniformly','It cannot initiate cracking','It is easier to predict than uniform corrosion'],answer:0,explanation:'The source notes that pitting is localized, can be hidden by rust, is harder to predict, and pits can initiate fatigue or stress-corrosion cracking.',source:'Subramanian supplementary Ch.19 §19.1.1'},
    {id:'ch15-cor-crevice',title:'Crevice mechanism',level:'core',kind:'reasoning',q:'Why can stagnant water trapped in a crevice make that region anodic?',choices:['Its oxygen content becomes lower than the surrounding exposed water','Its temperature always reaches boiling','Its density becomes zero','It removes the electrolyte'],answer:0,explanation:'Reduced oxygen in trapped water creates an electrochemical difference that can make the crevice anodic to the surrounding metal.',source:'Subramanian supplementary Ch.19 §19.1.1'},
    {id:'ch15-cor-galvanic',title:'Dissimilar-metal contact',level:'application',kind:'reasoning',q:'Which detail most directly creates a galvanic-corrosion risk?',choices:['Steel and aluminium in electrical contact while wet','Two identical dry steel plates','A painted steel plate in a dry room','A single isolated steel bar'],answer:0,explanation:'Galvanic corrosion can occur when dissimilar metals are electrically coupled in a corrosive electrolyte.',source:'Subramanian supplementary Ch.19 §19.1.1'},
    {id:'ch15-cor-stress',title:'Stress-corrosion cracking',level:'application',kind:'concept',q:'What combination defines stress-corrosion cracking in the chapter?',choices:['Tensile stress plus a corrosive environment','Compression alone in dry air','Temperature alone','Uniform paint thickness plus dead load'],answer:0,explanation:'Stress-corrosion cracking requires tensile stress, applied or residual, together with a corrosive environment.',source:'Subramanian supplementary Ch.19 §19.1.1'},
    {id:'ch15-cor-hydrogen',title:'Hydrogen embrittlement',level:'retrieval',kind:'concept',q:'What is the main structural effect of hydrogen embrittlement described in the chapter?',choices:['Reduced ductility and load-carrying capacity, with possible brittle cracking below yield stress','Increased ductility without cracking','Uniform section thickening','Higher corrosion resistance in every alloy'],answer:0,explanation:'Hydrogen ingress can reduce ductility and carrying capacity and can cause brittle cracking, especially in vulnerable high-strength materials.',source:'Subramanian supplementary Ch.19 §19.1.1'}
  ]);

  add('15:Corrosion-protection Methods',[
    {id:'ch15-protect-barrier',title:'Barrier principle',level:'foundation',kind:'concept',q:'What is the basic purpose of a protective coating on steel?',choices:['Separate the steel surface from the corrosive environment','Increase the unsupported length','Reduce the elastic modulus','Create a crevice'],answer:0,explanation:'Painting, zinc coating and other barriers protect primarily by isolating the steel from the environment.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-prep',title:'Surface preparation',level:'core',kind:'reasoning',q:'Why is surface preparation critical before applying a coating?',choices:['Coating durability depends strongly on a clean, suitably prepared surface and good adhesion','It increases steel density','It eliminates the need for coating','It creates more mill scale'],answer:0,explanation:'The chapter stresses that coating performance depends largely on correct surface preparation.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-blast',title:'Blast-cleaning purpose',level:'core',kind:'recognition',q:'What does abrasive blast cleaning achieve before coating?',choices:['A clean, roughened surface that improves coating adhesion','A polished surface covered with oil','A permanent cathodic current','A thicker steel section'],answer:0,explanation:'Abrasive particles remove contaminants and produce a clean rough surface suitable for coating adhesion.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-galv',title:'Hot-dip galvanizing',level:'core',kind:'recognition',q:'What metal is most commonly applied by hot-dip galvanizing in the chapter?',choices:['Zinc','Copper','Lead','Silver'],answer:0,explanation:'Hot-dip galvanizing protects steel by immersion in molten zinc; the chapter also discusses aluminium in metal-coating contexts.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-spray',title:'Metal spraying',level:'application',kind:'concept',q:'How does metal spraying differ from hot-dip galvanizing according to the chapter?',choices:['Molten zinc or aluminium is sprayed onto a prepared surface without the same alloying process as hot dipping','The entire member is immersed in concrete','No surface preparation is needed','Only organic paint is used'],answer:0,explanation:'Metal spraying deposits molten zinc or aluminium on a grit-blasted surface; the chapter notes that no alloying takes place as in hot dipping.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-cathodic',title:'Cathodic protection',level:'application',kind:'concept',q:'What is the central idea of cathodic protection?',choices:['Make the steel act as the cathode, using impressed current or a sacrificial anode','Make the steel the anode so it corrodes faster','Remove all electrical connection from the structure','Increase atmospheric humidity'],answer:0,explanation:'Cathodic protection suppresses steel dissolution by making the protected steel cathodic.',source:'Subramanian supplementary Ch.19 §19.2'},
    {id:'ch15-protect-selection',title:'Select for service life',level:'retrieval',kind:'reasoning',q:'Which factor should NOT be ignored when comparing corrosion-protection systems?',choices:['Inspection, repair and maintenance requirements over the service life','Only the first coat colour','Only member depth','Only fabrication drawing scale'],answer:0,explanation:'The chapter highlights maintainability, reliability and overall economy in addition to initial protection effectiveness.',source:'Subramanian supplementary Ch.19 §19.2'}
  ]);

  add('15:Atmospheric-Corrosion-Resistant Steels',[
    {id:'ch15-weathering-def',title:'Weathering steel',level:'foundation',kind:'definition',q:'What type of material is weathering steel in the chapter?',choices:['A low-alloy atmospheric-corrosion-resistant steel','A non-metallic coating','Pure iron without alloying','A concrete encasement system'],answer:0,explanation:'Weathering steel is an atmospheric-corrosion-resistant low-alloy steel.',source:'Subramanian supplementary Ch.19 §19.3'},
    {id:'ch15-weathering-film',title:'Protective rust film',level:'core',kind:'concept',q:'What gives weathering steel its improved atmospheric corrosion resistance?',choices:['A stable, fine-textured rust film that limits further water and oxygen access','Permanent removal of all iron','Continuous immersion in water','A sacrificial concrete layer'],answer:0,explanation:'Repeated exposure can transform initial rust into a stable protective film that greatly slows further attack.',source:'Subramanian supplementary Ch.19 §19.3'},
    {id:'ch15-weathering-cycles',title:'Wetting and drying',level:'core',kind:'reasoning',q:'Why are repeated wetting-and-drying cycles important for weathering steel?',choices:['They promote development of the stable protective rust layer','They prevent any oxide from forming','They dissolve all alloying elements','They make the steel stainless'],answer:0,explanation:'The source states that stable protective-film formation generally requires repeated wetting and drying.',source:'Subramanian supplementary Ch.19 §19.3'},
    {id:'ch15-weathering-use',title:'Application',level:'application',kind:'recognition',q:'Which applications are explicitly associated with atmospheric-corrosion-resistant steels in the chapter?',choices:['Buildings, bridges and storage tanks','Only buried concrete footings','Only timber roofs','Only aluminium windows'],answer:0,explanation:'The chapter notes applications in buildings, bridges and storage tanks.',source:'Subramanian supplementary Ch.19 §19.3'},
    {id:'ch15-weathering-cost',title:'Life-cycle value',level:'application',kind:'reasoning',q:'Why can the higher initial price of weathering steel be economically justified?',choices:['Reduced repeated painting and maintenance can lower life-cycle cost','Its density is zero','It never requires structural design','It eliminates all forms of corrosion in every environment'],answer:0,explanation:'The source explicitly compares the extra initial cost with savings from repeated painting and maintenance.',source:'Subramanian supplementary Ch.19 §19.3'},
    {id:'ch15-stainless-passive',title:'Stainless-steel protection',level:'core',kind:'concept',q:'What is the main corrosion-resistance mechanism of stainless steel?',choices:['A chromium-rich passive surface film','A sacrificial zinc anode built into every member','A concrete cover layer','A thick ordinary-rust scale'],answer:0,explanation:'Stainless steel relies mainly on a chromium-rich passive film.',source:'Subramanian supplementary Ch.19 §19.3; Ch.1 stainless-steel discussion'},
    {id:'ch15-weathering-limit',title:'Weathering-steel limitation',level:'retrieval',kind:'reasoning',q:'Which condition is unfavourable for developing the protective weathering-steel patina?',choices:['Persistent wetness without effective drying','Alternating rain and drying','Exposure that permits repeated wet-dry cycles','Air circulation that promotes drying'],answer:0,explanation:'Weathering steel depends on drying; persistently wet or severe chloride conditions can prevent satisfactory protective-film development.',source:'Subramanian supplementary Ch.19 §19.3'}
  ]);

  add('15:Corrosion Allowance',[
    {id:'ch15-allow-def',title:'Allowance concept',level:'foundation',kind:'definition',q:'What is added when the corrosion-allowance method is used?',choices:['Extra steel thickness equal to the expected section loss over the design life','Extra live load','Extra bolt slip','Extra elastic modulus'],answer:0,explanation:'The structural thickness is determined first, then expected corrosion loss is added as sacrificial thickness.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-app',title:'Where allowance is used',level:'core',kind:'recognition',q:'Which type of structure is specifically suited to the corrosion-allowance approach in the chapter?',choices:['Steel piles or underwater/underground steelwork','Dry internal office partitions only','Timber trusses','Masonry walls'],answer:0,explanation:'The chapter cites piles, sheet piles, offshore and other underground/underwater steelwork.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-rate',title:'Need a corrosion rate',level:'core',kind:'reasoning',q:'Why must the designer know the expected corrosion rate before specifying an allowance?',choices:['The required sacrificial thickness depends on expected loss over time','The rate determines Young’s modulus','The rate fixes bolt diameter directly','The allowance is unrelated to service life'],answer:0,explanation:'Allowance requires a credible estimate of thickness loss over the intended service life.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-example-rate',title:'Textbook corrosion rate',level:'core',kind:'quantitative',q:'What average corrosion rate is quoted in the chapter’s Japanese pile example?',choices:['About 0.024 mm/year','About 2.4 mm/year','About 24 mm/year','About 0.00024 mm/year'],answer:0,explanation:'The example cites an average corrosion rate of about 0.024 mm per year.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-calc',title:'Allowance life calculation',level:'application',kind:'numerical',q:'Using the chapter’s rate of 0.024 mm/year, approximately how long would a 2 mm corrosion allowance represent?',choices:['About 80 years','About 8 years','About 800 years','About 2 years'],answer:0,explanation:'2/0.024 is about 83 years; the chapter summarizes this as roughly 80 years.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-order',title:'Design sequence',level:'application',kind:'ordering',q:'Which sequence matches the corrosion-allowance design procedure?',choices:['Determine structural thickness → estimate service-life corrosion loss → add allowance','Add arbitrary thickness → ignore structural checks → estimate life','Choose paint colour → calculate Euler load → remove thickness','Estimate rust colour → reduce wall thickness'],answer:0,explanation:'The source first determines thickness for structural actions, then adds the expected corrosion loss.',source:'Subramanian supplementary Ch.19 §19.4'},
    {id:'ch15-allow-trap',title:'Allowance limitation',level:'retrieval',kind:'reasoning',q:'What is the main weakness of using a corrosion allowance without reliable exposure data?',choices:['The added thickness may not correspond to the actual service-life loss','The steel automatically becomes stainless','The member becomes immune to all local corrosion','The elastic modulus is doubled'],answer:0,explanation:'The method depends directly on credible corrosion-rate information for the actual environment.',source:'Subramanian supplementary Ch.19 §19.4'}
  ]);

  add('15:Detailing to Reduce Corrosion',[
    {id:'ch15-detail-water',title:'Avoid water traps',level:'foundation',kind:'concept',q:'What is the chapter’s central geometric principle for corrosion-resistant detailing?',choices:['Shed water rather than retain it','Create pockets that hold water','Seal dirt into corners','Prevent all air circulation'],answer:0,explanation:'Long wetness accelerates corrosion, so details should drain and dry rapidly.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-drainage',title:'Drainage holes',level:'core',kind:'application',q:'When should drainage holes or breaks be provided?',choices:['Where geometry could allow water to accumulate','Only where water can never enter','Only in concrete members','Never in steelwork'],answer:0,explanation:'The chapter explicitly recommends suitable drainage breaks or holes to prevent water accumulation.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-air',title:'Promote drying',level:'core',kind:'reasoning',q:'Why should detailing encourage free air movement around exposed steel?',choices:['To promote rapid drying and reduce time of wetness','To increase condensation','To create crevice corrosion','To reduce steel strength'],answer:0,explanation:'Air circulation promotes drying, and corrosion rate is strongly influenced by duration of wetness.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-crevice',title:'Crevice avoidance',level:'core',kind:'reasoning',q:'Why should crevices be avoided in exposed steel details?',choices:['They can trap stagnant moisture and create localized corrosion cells','They always improve coating access','They prevent oxygen differences','They make inspection easier'],answer:0,explanation:'Crevices are prone to stagnant moisture and differential aeration, leading to localized corrosion.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-access',title:'Inspection access',level:'application',kind:'concept',q:'Why is physical access to joints and components part of corrosion-resistant detailing?',choices:['Inspection, cleaning, repair and maintenance must remain possible','Access increases corrosion by definition','Coatings never require maintenance','Joints do not corrode'],answer:0,explanation:'The chapter requires suitable access, especially at bridge joints, for periodic inspection and maintenance.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-dissimilar',title:'Dissimilar materials',level:'application',kind:'reasoning',q:'What contact should detailing avoid when moisture may be present?',choices:['Direct contact between dissimilar metals that can promote galvanic corrosion','Contact between identical steel plates','Contact between paint layers','Contact between steel and dry air'],answer:0,explanation:'Avoiding dissimilar-metal contact reduces galvanic-corrosion risk.',source:'Subramanian supplementary Ch.19 §19.5'},
    {id:'ch15-detail-hsfg',title:'HSFG faying surfaces',level:'retrieval',kind:'concept',q:'What special caution does the chapter give for friction-grip-bolt faying surfaces?',choices:['Do not apply a protective treatment that interferes with the required friction behaviour','Always oil the faying surfaces heavily','Fill the joint with water','Polish the surface to eliminate all friction'],answer:0,explanation:'The chapter cautions against protective treatment on faying surfaces when it would interfere with friction-grip action.',source:'Subramanian supplementary Ch.19 §19.5'}
  ]);

  add('15:Encasing in Concrete',[
    {id:'ch15-encase-alkaline',title:'Why concrete can protect',level:'foundation',kind:'concept',q:'Why can concrete encasement protect structural steel from corrosion initially?',choices:['Cement hydration creates a highly alkaline environment that supports a passive oxide film','Concrete permanently removes all oxygen from the world','Concrete increases steel yield strength chemically','Concrete acts as a sacrificial metal'],answer:0,explanation:'The alkaline pore solution around steel promotes passivation.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-ph',title:'Concrete alkalinity',level:'core',kind:'quantitative',q:'What approximate pH range does the chapter quote for sound concrete around encased steel?',choices:['About 12.5–13.5','About 1–2','About 5–6','Exactly 7'],answer:0,explanation:'The chapter cites an alkaline pH of approximately 12.5 to 13.5 due to cement hydration.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-passive-loss',title:'Loss of passivity',level:'core',kind:'concept',q:'At approximately what pH does the chapter say passive protection near the steel can break down?',choices:['Below about 9','Above about 14 only','Exactly 12.5','At every pH above 7'],answer:0,explanation:'The source says passivity can break when the pH adjoining the steel falls below about 9.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-spall',title:'Corrosion and spalling',level:'core',kind:'reasoning',q:'How can corrosion of encased steel contribute to concrete spalling?',choices:['Corrosion products expand and increase pressure on the surrounding concrete','Steel corrosion shrinks to zero volume','Concrete becomes weightless','Passivity always strengthens concrete'],answer:0,explanation:'Expansion associated with corrosion products creates pressure that can crack and spall the encasement.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-weight',title:'Dead-load penalty',level:'application',kind:'reasoning',q:'What structural cost can arise from concrete encasement?',choices:['Higher dead load can increase foundation demand and cost','Lower dead load always results','Steel density becomes zero','Foundation loads disappear'],answer:0,explanation:'The chapter notes that encasement adds dead weight and can increase foundation cost.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-access',title:'Inspection drawback',level:'application',kind:'reasoning',q:'Why does concrete encasement make future corrosion management harder?',choices:['The steel surface is hidden from inspection and repair','The steel becomes more visible','Corrosion products become transparent','Inspection is no longer needed'],answer:0,explanation:'Hidden steel cannot be readily inspected or repaired, one reason the chapter does not favour encasement as a general modern protection method.',source:'Subramanian supplementary Ch.19 §19.6'},
    {id:'ch15-encase-paint',title:'Before encasement',level:'retrieval',kind:'concept',q:'What does the chapter state about painting or oiling steel that will be encased in concrete for corrosion protection?',choices:['The steel should neither be painted nor oiled before encasement','It must always receive a thick oil film','It must be galvanized in every case','It must be coated with bitumen in every case'],answer:0,explanation:'The source explicitly states that members encased in concrete should neither be painted nor oiled.',source:'Subramanian supplementary Ch.19 §19.6'}
  ]);

  add('15:Summary',[
    {id:'ch15-summary-conditions',title:'Conditions for corrosion',level:'foundation',kind:'retrieval',q:'Which two environmental ingredients does the chapter summary identify as fundamental for ordinary steel corrosion?',choices:['Water and oxygen','Dry nitrogen and vacuum','Concrete and timber','Heat and compression only'],answer:0,explanation:'The summary states that corrosion will not occur unless water and oxygen are both present on the steel surface.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-rate',title:'What controls corrosion rate?',level:'core',kind:'retrieval',q:'Which pair is emphasized in the summary as a major control on atmospheric corrosion rate?',choices:['Atmospheric pollution and duration of surface wetness','Steel density and member span','Bolt pitch and weld size','Floor live load and roof slope'],answer:0,explanation:'The summary emphasizes atmospheric pollution and the duration of wetness.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-exposure',title:'Exposure classes',level:'core',kind:'classification',q:'How many environmental severity classes does the chapter summary attribute to IS 800?',choices:['Five','Two','Three','Ten'],answer:0,explanation:'The summary lists mild, moderate, severe, very severe and extreme.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-indoor',title:'Indoor steel',level:'core',kind:'reasoning',q:'Why is corrosion of steel inside many ordinary buildings described as insignificant?',choices:['The members normally have little contact with moisture','Indoor steel contains no iron','Oxygen is absent from buildings','Indoor loads prevent corrosion'],answer:0,explanation:'Dry interior conditions generally limit the moisture needed for significant atmospheric corrosion.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-surface',title:'Preparation and coating',level:'application',kind:'reasoning',q:'What relationship does the summary stress between surface preparation and coating performance?',choices:['Good coating performance depends strongly on correct surface preparation','Surface preparation damages every coating','Paint adhesion is independent of the surface','Only coating colour matters'],answer:0,explanation:'The chapter repeatedly emphasizes correct preparation as essential to durable coatings.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-methods',title:'Protection family',level:'application',kind:'classification',q:'Which set contains corrosion-control methods summarized in the chapter?',choices:['Painting/linings, galvanizing or metal spraying, cathodic protection, resistant steels and detailing','Only increasing live load','Only heat treatment','Only adding concrete dead load'],answer:0,explanation:'The summary covers barrier coatings, metallic coatings, cathodic protection, resistant steels, allowance and good detailing.',source:'Subramanian supplementary Ch.19 Summary'},
    {id:'ch15-summary-maint',title:'Maintenance principle',level:'retrieval',kind:'reasoning',q:'Why can no corrosion-protection system be treated as permanently maintenance-free?',choices:['Coatings age or suffer damage, anodes are consumed, and even resistant steels are not absolutely immune','Corrosion protection becomes stronger forever without inspection','Paint never deteriorates','Cathodic anodes are never consumed'],answer:0,explanation:'The chapter stresses periodic inspection and maintenance because protection systems deteriorate in service.',source:'Subramanian supplementary Ch.19 §19.2 and Summary'}
  ]);

  add('15:Review Questions',[
    {id:'ch15-review-three',title:'Break the corrosion cell',level:'foundation',kind:'retrieval',q:'What general prevention idea is tested by the review question asking what must be eliminated to prevent corrosion?',choices:['Break one or more essential parts of the corrosion process, such as moisture/oxygen/electrochemical continuity','Increase all corrosion-cell components','Add more stagnant water','Create more dissimilar-metal contacts'],answer:0,explanation:'The review revisits the basic electrochemical mechanism and how eliminating necessary conditions can prevent attack.',source:'Subramanian supplementary Ch.19 Review Questions'},
    {id:'ch15-review-rust',title:'Rust versus steel loss',level:'core',kind:'retrieval',q:'Does the presence of a bulky rust layer mean the same thickness of original steel remains?',choices:['No; rust volume/thickness is not the same as the original steel thickness lost','Yes, rust is unchanged steel','Rust always restores lost section','Rust carries the original design strength'],answer:0,explanation:'The review explicitly tests the relationship between rust thickness and actual steel loss; corrosion products occupy a different volume than the consumed metal.',source:'Subramanian supplementary Ch.19 Review Questions'},
    {id:'ch15-review-surface',title:'Preparation method match',level:'core',kind:'classification',q:'Which surface-preparation method does the chapter associate with hot-dip galvanizing?',choices:['Chemical cleaning/pickling','Leaving heavy loose rust in place','Applying grease before dipping','No cleaning at all'],answer:0,explanation:'The summary and review associate chemical cleaning with hot-dip galvanizing.',source:'Subramanian supplementary Ch.19 Summary and Review Questions'},
    {id:'ch15-review-lining',title:'Where linings are used',level:'application',kind:'recognition',q:'Which application is specifically associated with protective linings?',choices:['Internal surfaces of tanks and pipes in chemical plants','Only dry classroom beams','Only roof purlins in sealed interiors','Only temporary scaffolding'],answer:0,explanation:'The chapter identifies tanks and pipes in chemical plants, plus selected external pipes, bridge cables and piles, as lining applications.',source:'Subramanian supplementary Ch.19 Review Questions and Summary'},
    {id:'ch15-review-weather-stainless',title:'Weathering versus stainless',level:'application',kind:'comparison',q:'What is the key difference in the protective surface mechanism emphasized for weathering and stainless steels?',choices:['Weathering steel develops a stable rust patina; stainless steel relies on a chromium-rich passive film','Both depend only on concrete encasement','Both require sacrificial zinc anodes','Neither forms a protective surface film'],answer:0,explanation:'The chapter contrasts the stabilized rust layer of weathering steel with the chromium-rich passive film of stainless steel.',source:'Subramanian supplementary Ch.19 §19.3 and Review Questions'},
    {id:'ch15-review-detail',title:'Detailing retrieval',level:'application',kind:'reasoning',q:'Which design change most directly answers the chapter review emphasis on corrosion-resistant detailing?',choices:['Remove water traps and provide drainage, drying and inspection access','Add more re-entrant pockets','Make joints inaccessible','Place dissimilar metals in wet contact'],answer:0,explanation:'The detailing section and review focus on drainage, drying, accessibility and avoiding corrosion-prone geometries.',source:'Subramanian supplementary Ch.19 §19.5 and Review Questions'},
    {id:'ch15-review-integrate',title:'Integrated chapter check',level:'retrieval',kind:'reasoning',q:'A coastal steel component has persistent moisture and difficult maintenance access. Which response best follows the chapter as a whole?',choices:['Treat exposure severity, material/detailing, preparation/protection and future maintenance as one coordinated design problem','Use the same minimal coating as a dry interior member','Ignore drainage because coating alone is sufficient','Base the decision only on initial paint price'],answer:0,explanation:'The chapter’s central message is integrated durability design based on exposure, detailing, protection and life-cycle maintenance.',source:'Subramanian supplementary Ch.19'}
  ]);
})();
