(() => {
  const B = window.REVISION_BANK = window.REVISION_BANK || {};
  const add = (topic, rows) => {
    const key = `8:${topic}`;
    B[key] = [...(B[key] || []), ...rows.map((r,i)=>({
      id:`ch8-deep-${i+1}`,
      title:r[0], level:r[1], kind:r[2], q:r[3], choices:r[4], answer:0,
      explanation:r[5], source:'N. Subramanian, Design of Steel Structures, Ch. 8 / matching Oxford chapter presentation'
    }))];
  };
  const Q=(title,level,kind,q,correct,d1,d2,d3,explanation)=>[title,level,kind,q,[correct,d1,d2,d3],explanation];

  add('Introduction',[
    Q('Why Chapter 8 joins two behaviours','foundation','concept','Chapter 8 introduction — central design issue: which statement is correct?','It links reserve strength after yielding with loss of capacity or stiffness from buckling.','It treats only elastic deflection.','It deals only with connection fatigue.','It assumes instability is irrelevant.','The chapter deliberately connects plastic redistribution and buckling because both control real steel resistance beyond simple elastic strength.'),
    Q('First yield is not always collapse','core','reasoning','Chapter 8 introduction — after first yield, why can a steel structure still have reserve strength?','Ductile redistribution can allow additional load before a collapse mechanism forms.','The yield stress automatically rises without limit.','Buckling disappears after yielding.','All moments become zero.','Plastic behaviour can redistribute moments after local yielding, so first yield need not equal structural collapse.'),
    Q('Buckling consequence','core','concept','Chapter 8 introduction — what can buckling do before full material strength is mobilized?','Reduce usable load-carrying capacity and stiffness.','Increase section thickness.','Eliminate residual stress.','Convert bending into pure tension.','Instability can limit a member or plate before full plastic resistance is available.'),
    Q('Design sequence intuition','application','reasoning','Chapter 8 introduction — a section has high plastic reserve but very slender compression plates. What should concern the designer?','Local buckling may prevent the reserve strength from being developed.','The section must therefore be perfectly elastic forever.','Only density matters.','The plastic moment necessarily increases.','Plastic capacity is useful only when instability does not intervene first.'),
    Q('Elastic versus plastic viewpoint','retrieval','classification','Chapter 8 introduction — which viewpoint best matches plastic design?','Follow response beyond first yield toward redistribution and mechanism formation.','Stop analysis as soon as any fibre reaches yield.','Ignore equilibrium after yielding.','Assume brittle fracture at first yield.','Plastic design exploits ductility beyond first yield while still respecting strength and stability limits.'),
    Q('Chapter bridge','retrieval','concept','Chapter 8 introduction — which later design topics does this chapter prepare you for?','Beam and column design where yielding and buckling interact with section behaviour.','Only concrete mix design.','Only soil bearing capacity.','Only thermal expansion.','The chapter is background for later member design because section plasticity and local/global instability directly influence beams and columns.')
  ]);

  add('Plastic Theory',[
    Q('Reserve strength','foundation','concept','Plastic Theory — what does “reserve strength” mean here?','Capacity available after first yield before collapse.','Strength below zero load.','Only the difference between density and unit weight.','A corrosion allowance.','Plastic theory recognizes useful capacity between first yield and formation of a collapse mechanism.'),
    Q('Shape factor definition','core','formula','Plastic Theory — which relation defines shape factor?','Shape factor = plastic section modulus / elastic section modulus.','Shape factor = elastic modulus / yield stress.','Shape factor = area / length.','Shape factor = density × gravity.','Shape factor compares fully plastic and first-yield bending capacities through Zp/Ze.'),
    Q('Moment ratio','core','formula','Plastic Theory — for the same yield stress, which ratio equals Mp/My?','Zp/Ze.','Ze/Zp.','A/I.','L/r.','Because My = fy Ze and Mp = fy Zp, their ratio is the shape factor Zp/Ze.'),
    Q('Ductility role','application','reasoning','Plastic Theory — why is ductility essential for redistribution?','Sections must sustain inelastic deformation and rotation without premature fracture.','It raises density.','It eliminates equilibrium.','It guarantees zero deflection.','Redistribution requires stable plastic deformation and rotation.'),
    Q('First yield trap','trap','concept','Plastic Theory — which statement is NOT consistent with the chapter?','The structure necessarily collapses at the first yielded fibre.','Plastic analysis can continue beyond first yield.','Plastic hinges may form before the final mechanism.','Reserve strength depends on section and structural behaviour.','The chapter explicitly rejects first yield as automatic collapse for ductile indeterminate structures.'),
    Q('Section-property meaning','retrieval','concept','Plastic Theory — what does the plastic section modulus represent in bending?','The geometric measure used with fy to obtain the fully plastic moment.','The elastic modulus of steel.','The member slenderness ratio.','The shear modulus.','Mp is obtained from fy multiplied by Zp for the idealized fully yielded stress distribution.')
  ]);

  add('General Requirements for Plastic Design',[
    Q('Material idealization','foundation','concept','General Requirements — which stress–strain idealization is adopted for basic plastic design?','Elastic-perfectly-plastic behaviour.','Perfectly brittle behaviour.','Purely viscous behaviour.','No yielding at any stress.','The chapter uses an idealized elastic-perfectly-plastic material model.'),
    Q('Tension and compression assumption','core','concept','General Requirements — what is assumed about yield stress in tension and compression?','The same yield stress is used in both.','Compression yield is taken as zero.','Tension yield is ignored.','They are unrelated random values.','The simplified plastic model assumes the same yield stress in tension and compression.'),
    Q('Rigid segments between hinges','core','concept','General Requirements — how is plastic deformation idealized in a frame mechanism?','Rotations concentrate at plastic hinges with intervening segments treated as rigid.','Every point rotates freely with zero moment.','All deformation is only axial.','No hinge rotation occurs.','Rigid-plastic mechanism analysis concentrates rotation at hinge locations.'),
    Q('Rotation capacity','application','reasoning','General Requirements — what must a section possess so a planned plastic mechanism can actually develop?','Sufficient ductility and plastic-rotation capacity.','Only high density.','Zero residual stress in every fibre.','No elastic deformation at all.','Without adequate rotation capacity the intended sequence of hinge formation may be interrupted.'),
    Q('Stability prerequisite','application','reasoning','General Requirements — why must local and lateral buckling be controlled?','They can prevent the section from reaching or sustaining Mp during required rotations.','They increase Mp.','They have no relation to plastic design.','They occur only after collapse.','Plastic design assumes the section can develop and maintain plastic resistance long enough for the mechanism to form.'),
    Q('Hinge moment limit','retrieval','concept','General Requirements — in the ideal plastic model, what moment is associated with a plastic hinge?','Approximately the plastic moment capacity Mp.','Exactly zero.','The Euler load.','Only the first-yield moment My forever.','A plastic hinge rotates while resisting approximately Mp in the idealization.')
  ]);

  add('Plastic Hinge Concept',[
    Q('Progressive yielding','foundation','sequence','Plastic Hinge — what happens between first yield and a fully plastic section?','Yielding spreads progressively through the section depth.','The section instantly loses all moment resistance.','Only density changes.','The neutral axis vanishes physically.','As moment increases beyond My, more fibres reach fy until the stress block becomes fully plastic.'),
    Q('Moment during rotation','core','concept','Plastic Hinge — once fully plastic in the idealization, how does moment behave while rotation increases?','It remains approximately at Mp.','It falls immediately to zero.','It must increase without limit.','It becomes independent of section capacity.','The ideal hinge sustains roughly the plastic moment while accumulating rotation.'),
    Q('Not a physical pin','trap','concept','Plastic Hinge — which statement is the common misconception?','A plastic hinge is a literal frictionless pin carrying zero moment.','It represents a yielded rotating region.','It still transmits moment.','It forms over a finite yielded zone in reality.','A plastic hinge is a behavioural idealization, not a hardware hinge.'),
    Q('Finite hinge length','core','concept','Plastic Hinge — what does “hinge length” recognize?','The yielded region occupies a finite length rather than a mathematical point.','The beam has zero span.','The support is infinitely rigid.','The plastic moment is zero.','Real yielding spreads over a region whose length depends on loading and section geometry.'),
    Q('Moment-curvature link','application','reasoning','Plastic Hinge — why does curvature rise strongly near Mp?','Large plastic strains develop while moment changes relatively little.','Elastic modulus becomes infinite.','The section unloads completely.','The beam becomes axially rigid only.','The moment–curvature relation flattens near full plasticity, producing large rotation demand.'),
    Q('Hinge formation use','retrieval','application','Plastic Hinge — why is hinge formation useful in an indeterminate structure?','It permits moment redistribution to other regions before final mechanism formation.','It removes all reactions.','It prevents any further loading.','It eliminates equilibrium.','After one hinge forms, redundancy can allow other regions to take additional moment until enough hinges form for collapse.')
  ]);

  add('Plastic-collapse Load',[
    Q('Collapse definition','foundation','concept','Plastic-collapse Load — what defines the collapse load?','Enough plastic hinges have formed to convert the structure into a mechanism.','The first elastic deflection appears.','One fibre reaches proportional limit.','Every member has zero moment.','Collapse is identified by mechanism formation, not first yield.'),
    Q('Redundancy rule','core','formula','Plastic-collapse Load — for degree of redundancy r, how many plastic hinges are generally needed for total collapse?','r + 1.','r − 1.','2r + 2 always.','Exactly one regardless of redundancy.','The chapter gives the useful rule that total collapse generally requires r+1 hinges.'),
    Q('First hinge in indeterminate beam','core','reasoning','Plastic-collapse Load — what usually follows formation of the first plastic hinge in an indeterminate structure?','Moment redistributes and additional load may be carried.','Immediate collapse in every case.','All support moments vanish.','The material becomes elastic again.','Redundancy permits continued loading after an initial hinge.'),
    Q('Mechanism criterion','application','reasoning','Plastic-collapse Load — two hinges have formed but the structure still has kinematic restraint. Has total collapse occurred?','No, not until the required mechanism exists.','Yes, any two hinges always collapse a structure.','Yes, because all moments become zero.','No, because plastic hinges cannot rotate.','The decisive condition is mechanism formation, not a fixed hinge count independent of redundancy.'),
    Q('Collapse versus yield','trap','classification','Plastic-collapse Load — which event normally occurs earlier?','First yield occurs earlier than the plastic-collapse mechanism.','Plastic collapse always occurs before first yield.','They are identical for every indeterminate structure.','Neither can occur in steel.','Plastic reserve exists between initial yielding and mechanism formation.'),
    Q('Design meaning','retrieval','concept','Plastic-collapse Load — why is the collapse load useful in plastic design?','It represents the limiting load associated with a kinematically unstable plastic mechanism.','It is the service deflection limit.','It is the steel density.','It is a weld size.','Plastic analysis seeks the load at which the structure becomes a mechanism under the assumed plastic capacities.')
  ]);

  add('Conditions of Plastic Analysis',[
    Q('Three conditions','foundation','classification','Conditions of Plastic Analysis — which set is required for a complete collapse solution?','Equilibrium, mechanism and plasticity.','Strength, density and colour.','Creep, shrinkage and settlement.','Yield, fatigue and fire only.','The chapter states equilibrium, mechanism and plasticity as the three governing conditions.'),
    Q('Equilibrium condition','core','concept','Conditions — what does equilibrium require?','Internal moments/reactions must balance the applied loading.','All hinges must rotate equally.','Every section must be at Mp.','No reaction may exist.','A statically admissible moment field must satisfy structural equilibrium.'),
    Q('Mechanism condition','core','concept','Conditions — what does the mechanism condition require at collapse?','Enough hinges must exist for the structure or relevant part to become a mechanism.','All members must remain elastic.','The support reactions must be zero.','The load factor must be one.','Kinematic freedom at collapse comes from the required hinge pattern.'),
    Q('Plasticity condition','core','concept','Conditions — what does the plasticity condition prohibit?','A bending moment exceeding the section plastic moment capacity.','Any bending moment below Mp.','Elastic regions between hinges.','Support reactions.','Plastic admissibility requires |M| not to exceed Mp anywhere.'),
    Q('Check an assumed solution','application','reasoning','Conditions — an assumed mechanism gives virtual-work collapse load, but another section would require M > Mp. Is the solution valid?','No, it violates the plasticity condition.','Yes, mechanism alone is sufficient.','Yes, because equilibrium is optional.','No, because plastic hinges carry zero moment.','All three conditions must be satisfied for the true solution.'),
    Q('Uniqueness intuition','retrieval','reasoning','Conditions — why does satisfying all three conditions matter?','Together they identify a statically and kinematically admissible collapse state consistent with section capacities.','They only determine density.','They replace the need for loads.','They ensure the structure remains elastic.','The complete plastic solution must satisfy force balance, mechanism kinematics and moment-capacity limits simultaneously.')
  ]);

  add('Theorems of Plastic Collapse',[
    Q('Lower-bound theorem','foundation','concept','Plastic Collapse Theorems — what kind of field gives a lower-bound collapse load?','A statically admissible equilibrium moment field nowhere exceeding Mp.','Any assumed mechanism regardless of moments.','A field with moments above Mp.','An elastic deflection curve only.','The lower-bound theorem is based on equilibrium plus plastic admissibility.'),
    Q('Upper-bound theorem','foundation','concept','Plastic Collapse Theorems — what gives an upper-bound collapse load?','A kinematically admissible collapse mechanism evaluated by virtual work.','Only an elastic stress distribution.','A corrosion allowance.','Any reaction diagram without a mechanism.','The kinematic theorem uses an assumed mechanism and virtual work.'),
    Q('Coincident bounds','core','reasoning','Plastic Collapse Theorems — what follows if upper- and lower-bound solutions give the same load?','That common load is the true collapse load.','The section must remain elastic.','The analysis is impossible.','The lower bound must be ignored.','Coincidence of admissible upper and lower bounds establishes the unique collapse load.'),
    Q('Lower-bound safety sense','core','reasoning','Plastic Collapse Theorems — why is a lower-bound solution called “safe” in the theorem sense?','It does not overestimate collapse while equilibrium and Mp limits are respected.','It always equals zero.','It ignores section capacity.','It assumes a mechanism that cannot occur.','A statically admissible field under the capacity limit cannot require collapse below that load.'),
    Q('Upper-bound search','application','reasoning','Plastic Collapse Theorems — several mechanisms are examined. Which upper-bound mechanism governs?','The one giving the lowest collapse load among the admissible mechanisms.','The one giving the highest load.','Any mechanism regardless of work balance.','The one with the most hinges automatically.','Kinematic analysis searches possible mechanisms and the minimum upper-bound load governs.'),
    Q('Theorem distinction','retrieval','classification','Plastic Collapse Theorems — which pairing is correct?','Static/equilibrium method → lower bound; kinematic/mechanism method → upper bound.','Static method → upper bound only; kinematic → lower bound only.','Both methods always give unrelated service loads.','Neither method uses Mp.','The static and kinematic approaches correspond to the lower- and upper-bound theorems respectively.')
  ]);

  add('Methods of Plastic Analysis',[
    Q('Static method','foundation','concept','Methods of Plastic Analysis — what is constructed in the static method?','An equilibrium bending-moment field with no moment exceeding Mp.','Only a deflected shape.','Only a stress–strain curve.','A fatigue S-N curve.','The static method seeks a statically admissible moment distribution.'),
    Q('Kinematic method','foundation','concept','Methods of Plastic Analysis — what is assumed first in the kinematic method?','A possible collapse mechanism.','A zero-load state.','A corrosion rate.','An elastic buckling eigenmode only.','The kinematic method begins with a possible mechanism and then applies virtual work.'),
    Q('Virtual work balance','core','formula','Methods — at plastic collapse, what equality is used in the kinematic method?','External work = internal work at plastic hinges.','External work = zero always.','Internal work = density × volume.','Elastic strain energy = corrosion loss.','Virtual work equates load work to hinge work Mp times compatible rotations.'),
    Q('Hinge work','core','formula','Methods — for one plastic hinge rotating through θ at constant Mp, what is its ideal internal work contribution?','Mp θ.','Mp/θ.','θ/Mp.','Zero.','Plastic hinge work is moment times plastic rotation.'),
    Q('Mechanism refinement','application','reasoning','Methods — if a chosen mechanism gives a higher collapse load than another admissible mechanism, which should govern?','The lower collapse load mechanism.','The higher one.','Their average.','Neither, because mechanisms are not compared.','The kinematic upper-bound search must identify the least collapse load among plausible mechanisms.'),
    Q('Cross-check logic','retrieval','reasoning','Methods — what is the strongest confirmation of a plastic-collapse calculation?','Static and kinematic solutions coincide at the same load while all moment limits are satisfied.','Only a mechanism sketch is drawn.','Only one reaction is calculated.','The section remains below first yield everywhere.','Agreement of lower- and upper-bound solutions confirms the true collapse load.')
  ]);

  add('Plastic Design of Continuous Beams',[
    Q('Two design tasks','foundation','concept','Continuous Beams — what two broad tasks accompany plastic design?','Find the collapse mechanism/Mp requirement and ensure secondary instability does not prevent it.','Check only density and paint.','Check only elastic deflection.','Ignore local buckling.','Plastic beam design couples mechanism analysis with stability/detailing checks.'),
    Q('Moment redistribution','core','concept','Continuous Beams — why can moments redistribute after a support section reaches Mp?','A plastic hinge can rotate while other regions take changing moments.','The support moment becomes infinite.','The beam loses equilibrium.','The elastic modulus becomes zero everywhere.','Plastic hinge rotation allows redistribution in a redundant beam.'),
    Q('Internal span idealization','core','recognition','Continuous Beams — how are internal spans described at collapse in the chapter?','They behave like fixed-ended beams in the plastic mechanism idealization.','They are always cantilevers.','They carry only axial force.','They have no support moments.','The chapter treats internal spans as fixed-ended at collapse.'),
    Q('End span idealization','core','recognition','Continuous Beams — how are end spans treated in the chapter plastic-design idealization?','As propped cantilevers.','As free-free beams.','As pure tension bars.','As columns only.','End spans are treated as propped cantilevers for mechanism analysis.'),
    Q('Premature local buckling','application','reasoning','Continuous Beams — what happens if a compression flange locally buckles before the required hinge rotation develops?','The assumed plastic mechanism may not be achievable.','Collapse load necessarily increases.','The hinge rotation capacity improves.','Redistribution becomes unlimited.','Plastic design requires stable hinge regions so moment resistance is maintained during redistribution.'),
    Q('Design objective','retrieval','concept','Continuous Beams — what is the practical objective of plastic redistribution?','Use section reserve strength across several locations before a collapse mechanism forms.','Keep every moment exactly elastic.','Eliminate support reactions.','Avoid all plasticity.','Plastic design uses ductility and redundancy to redistribute moment until the mechanism develops.')
  ]);

  add('Plastic Design of Portal Frames',[
    Q('Mechanism families','foundation','classification','Portal Frames — which mechanism families must be considered?','Beam, sway and combined mechanisms.','Only beam mechanisms.','Only local plate buckling.','Only torsional vibration.','Portal frames may collapse through beam, sway or combined mechanisms.'),
    Q('Why multiple mechanisms','core','reasoning','Portal Frames — why must more than one possible mechanism be examined?','Different hinge patterns can produce different collapse loads.','All mechanisms always give the same load.','Portal frames cannot sway.','Plastic hinges cannot form in columns.','The governing collapse mode is the admissible mechanism with the lowest collapse load.'),
    Q('Sway mechanism recognition','core','concept','Portal Frames — what characterizes a sway mechanism?','Lateral frame translation associated with plastic hinge rotations.','Only vertical shortening with no joint translation.','A single elastic fibre yielding.','Pure torsion of one bolt.','A sway mechanism allows the frame to translate laterally as hinges rotate.'),
    Q('Beam mechanism recognition','core','concept','Portal Frames — what characterizes a beam mechanism?','Plastic hinges form so a beam region becomes a mechanism without requiring overall frame sway.','All columns buckle elastically.','The frame translates as a rigid body with no hinge.','Only axial tension develops.','A beam mechanism is driven primarily by hinge formation in the beam system.'),
    Q('Combined mechanism','application','reasoning','Portal Frames — when is a combined mechanism relevant?','When beam-type and sway-type hinge rotations participate together in collapse.','When no plastic hinges form.','Only in a statically determinate truss.','Only when the frame has zero horizontal load.','Combined mechanisms superpose elementary mechanism features and must be checked for a lower collapse load.'),
    Q('Governing mechanism','retrieval','reasoning','Portal Frames — after virtual-work calculations for several mechanisms, which controls design?','The admissible mechanism with the smallest collapse load.','The mechanism with the largest load.','The mechanism with the fewest calculations.','The average of all mechanisms.','Plastic design must be based on the earliest possible collapse mechanism.')
  ]);

  add('Effect of Axial and Shear Force on Plastic Moment Capacity',[
    Q('Axial interaction','foundation','concept','Axial/Shear Interaction — what is the general effect of significant axial force on plastic moment capacity?','It reduces available plastic bending capacity.','It always increases Mp.','It has no effect on the stress block.','It changes only density.','Axial force changes the balance of tension and compression resultants, leaving less capacity for pure bending.'),
    Q('Plastic neutral axis shift','core','reasoning','Axial/Shear Interaction — why does axial force shift the plastic neutral axis?','Tension and compression resultants are no longer equal as in pure bending.','The section loses area physically.','Elastic modulus becomes infinite.','Shear force becomes zero.','Combined axial force and bending require unequal tension/compression resultants, shifting the plastic neutral axis.'),
    Q('Shear interaction','foundation','concept','Axial/Shear Interaction — what is the general effect of high shear on bending resistance?','High shear can reduce the bending resistance available under yielding interaction.','High shear always doubles Mp.','Shear has no stress interaction with yielding.','Shear acts only in concrete.','The chapter uses yielding interaction concepts to show that substantial shear can reduce bending capacity.'),
    Q('Web role','core','concept','Axial/Shear Interaction — in an I-section, which component carries most of the shear?','The web.','Only the flange tips.','Only the neutral-axis line with zero area.','The bolt heads.','The web is the principal shear-carrying element in an I-section.'),
    Q('von Mises link','core','recognition','Axial/Shear Interaction — which yielding criterion is used to discuss shear interaction?','The von Mises criterion.','Euler buckling only.','Rankine earth pressure.','Darcy law.','The chapter invokes the von Mises yield criterion to relate normal and shear stress interaction.'),
    Q('Design implication','application','reasoning','Axial/Shear Interaction — a section is near full plastic bending capacity and also has large shear. What is the safe design attitude?','Check the interaction because full pure-bending Mp may not remain available.','Ignore shear because Mp is unaffected.','Increase moment demand to compensate.','Assume the web carries no shear.','Combined actions can reduce available resistance, so interaction must be checked.')
  ]);

  add('Special Considerations',[
    Q('Mechanism alone is insufficient','foundation','concept','Special Considerations — why is a mathematically valid plastic mechanism not enough for practical design?','Stability, rotation capacity, deflection and connection behaviour can prevent the assumed mechanism.','Mechanisms automatically satisfy every limit state.','Plastic hinges require no restraint.','Local buckling increases rotation capacity.','Real members and connections must sustain the assumed plastic behaviour without premature instability or other failure.'),
    Q('Hinge restraint','core','reasoning','Special Considerations — why should plastic-hinge regions be laterally restrained?','To prevent lateral/torsional instability from reducing moment resistance during rotation.','To make the hinge moment zero.','To eliminate all axial force.','To increase density.','Hinge regions need stable rotation capacity while sustaining near-Mp resistance.'),
    Q('Local buckling risk','core','reasoning','Special Considerations — what can local buckling do in a plastic hinge region?','Cause moment resistance to deteriorate before the required rotation is achieved.','Guarantee higher Mp.','Prevent any yielding.','Increase section modulus.','Local instability can terminate useful plastic rotation prematurely.'),
    Q('Column action','application','concept','Special Considerations — why must column action be considered in plastic frame design?','Axial compression can interact with bending and stability, altering hinge capacity and mechanism behaviour.','Columns carry no axial force.','Compression always increases plastic rotation.','Frame collapse is independent of columns.','Plastic frame behaviour can be strongly affected by axial load and column stability.'),
    Q('Connection behaviour','application','reasoning','Special Considerations — what must connections do in a plastic design?','Transmit the required forces/moments while accommodating the intended ductile mechanism behaviour.','Act as frictionless pins in all cases.','Fail before the member yields.','Remove all moment redistribution.','Connections must be compatible with the force and rotation demands implied by the plastic mechanism.'),
    Q('Deflection awareness','retrieval','concept','Special Considerations — why can deflection still matter even when strength is checked plastically?','Large inelastic deformations may affect serviceability, stability and mechanism feasibility.','Plastic design eliminates deformation.','Deflection exists only in concrete.','Deflection always becomes zero at Mp.','Plastic strength does not remove deformation or stability considerations.')
  ]);

  add('Local Buckling of Plates',[
    Q('Plate-element view','foundation','concept','Local Buckling — how are many rolled steel cross-sections viewed for local-buckling purposes?','As assemblies of relatively slender plate elements.','As solid blocks with no plate behaviour.','As cables only.','As fluids.','Flanges and webs behave as plate elements whose local slenderness can control resistance.'),
    Q('Slenderness measure','core','formula','Local Buckling — which geometric ratio is central to plate slenderness?','Width-to-thickness ratio b/t.','Length-to-density ratio.','Area-to-volume ratio only.','Bolt diameter/pitch only.','Local buckling sensitivity rises strongly with plate width relative to thickness.'),
    Q('Effect of increasing b/t','core','reasoning','Local Buckling — what generally happens as width-to-thickness ratio increases?','Elastic local-buckling stress decreases.','Buckling stress necessarily increases.','Plate behaviour becomes independent of supports.','The plate becomes perfectly plastic sooner.','Wider/thinner plate elements are more susceptible to local instability.'),
    Q('Boundary-condition role','core','concept','Local Buckling — besides b/t, what strongly affects plate buckling stress?','Boundary/support conditions and loading pattern.','Paint colour only.','Steel density only.','Member label only.','Plate buckling depends on how edges are supported and how compression is distributed.'),
    Q('Premature instability','application','reasoning','Local Buckling — why can a slender compression element reduce section strength before full yield?','It may buckle locally before the entire section can develop its material capacity.','Buckling raises yield stress.','It removes compression.','It makes thickness irrelevant.','Local instability can precede full-section yielding.'),
    Q('Design connection','retrieval','concept','Local Buckling — why does local buckling lead directly to cross-section classification?','Classification limits element slenderness according to the level of plastic strength/rotation that can be developed.','Classification is based only on member colour.','Classification ignores plate geometry.','Classification applies only to concrete.','Section class summarizes whether local buckling prevents plastic moment, rotation, or even first yield.')
  ]);

  add('Cross Section Classification',[
    Q('Four classes','foundation','classification','Cross Section Classification — which sequence is correct?','Plastic, compact, semi-compact, slender.','Elastic, viscous, brittle, fluid.','Short, medium, long, infinite.','Bolted, welded, riveted, glued.','The chapter uses four behavioural classes based on local-buckling susceptibility.'),
    Q('Plastic class capability','core','concept','Cross Section Classification — what can a plastic (Class 1) section do?','Develop Mp and sustain enough rotation for a plastic mechanism.','Only reach first yield.','Buckle before yield.','Carry no bending.','Class 1 sections have sufficient local stability and rotation capacity for plastic analysis.'),
    Q('Compact class capability','core','concept','Cross Section Classification — what distinguishes a compact (Class 2) section?','It can reach Mp but lacks sufficient plastic-hinge rotation capacity for a full mechanism.','It buckles before any fibre yields.','It can never reach yield.','It has unlimited rotation capacity.','Class 2 sections develop plastic moment but not the rotation capacity required for Class 1 behaviour.'),
    Q('Semi-compact class capability','core','concept','Cross Section Classification — what can a semi-compact (Class 3) section develop?','Yield at the extreme compression fibre but not the full plastic moment.','Full Mp with unlimited rotation.','No elastic moment.','Only axial tension.','Class 3 reaches first yield in compression but local buckling prevents full plastic stress distribution.'),
    Q('Slender class behaviour','core','concept','Cross Section Classification — what characterizes a slender (Class 4) section?','One or more elements buckle locally before yield is reached in the relevant part.','It always reaches Mp first.','It has more hinge rotation than Class 1.','It cannot buckle locally.','Class 4 local buckling precedes full yield and requires reduced/effective section treatment.'),
    Q('Classification purpose','application','reasoning','Cross Section Classification — why does design need section class before choosing a bending resistance model?','The class determines whether plastic, elastic or reduced effective-section resistance is appropriate.','Class only changes steel density.','All classes have identical moment capacity and rotation.','Classification is decorative only.','Local-buckling behaviour governs which resistance model the section can legitimately use.')
  ]);

  add('Behaviour and Ultimate Strength of Plates',[
    Q('Post-buckling reserve','foundation','concept','Plate Ultimate Strength — what can an internally supported slender plate do after elastic local buckling?','Carry additional load through post-buckling stress redistribution.','Carry no load whatsoever.','Instantly develop a plastic hinge across the member.','Become perfectly rigid.','Plates supported along both longitudinal edges can develop useful post-buckling reserve.'),
    Q('Effective width','core','concept','Plate Ultimate Strength — what is the effective-width concept used for?','Represent only the portion of a locally buckled plate treated as fully effective in design.','Increase the physical plate width.','Define member length.','Calculate steel density.','Effective width converts non-uniform post-buckling stress into a simplified effective section.'),
    Q('Internal versus outstand plate','core','reasoning','Plate Ultimate Strength — which generally has more useful post-buckling reserve?','An internally supported plate with both longitudinal edges supported.','An outstand plate with one free longitudinal edge.','They are always identical.','Neither can carry post-buckling load.','Internal plates can redistribute membrane stresses more effectively than outstand elements.'),
    Q('Stress redistribution','core','concept','Plate Ultimate Strength — after local buckling, where does load tend to redistribute in an internally supported plate?','Toward more effective regions near supported edges.','Uniformly to zero everywhere.','Only into the air.','Only into bolts regardless of plate support.','Post-buckling membrane action shifts stress toward zones that remain effective.'),
    Q('Design interpretation','application','reasoning','Plate Ultimate Strength — why is elastic buckling stress not necessarily the ultimate strength of an internally supported slender plate?','Post-buckling action can provide reserve beyond first local buckling.','Buckling stress is always greater than ultimate stress by definition.','Yield stress becomes zero at buckling.','The plate stops carrying all load immediately.','Elastic local buckling can precede ultimate failure because supported plates can redistribute stress.'),
    Q('Effective-section consequence','retrieval','concept','Plate Ultimate Strength — what happens to design section properties when slender elements are treated by effective width?','The effective area and related section properties are reduced relative to the gross section.','They always increase.','They become independent of geometry.','They are replaced by density only.','Only the effective portions are credited, reducing design section properties.')
  ]);

  add('Examples',[
    Q('Rectangle shape factor','foundation','numerical','Chapter 8 Examples — what shape factor is obtained for the solid rectangular section example?','1.5.','1.0.','2.0.','0.5.','The worked example gives Zp/Ze = 1.5 for a solid rectangle.'),
    Q('Worked-example themes','core','classification','Chapter 8 Examples — which calculation family is included?','Elastic/plastic section moduli, shape factors and plastic moments.','Concrete shrinkage only.','Soil consolidation only.','Wind tunnel testing only.','The examples include section plasticity calculations as well as structural mechanism problems.'),
    Q('Virtual-work example','core','concept','Chapter 8 Examples — what principle is used in beam/frame collapse calculations?','Equate external work with internal plastic-hinge work.','Set every moment to zero.','Use only Hooke law.','Ignore hinge rotations.','Worked collapse examples use virtual work for assumed mechanisms.'),
    Q('Mechanism comparison','application','reasoning','Chapter 8 Examples — if two possible mechanisms give different collapse loads, which result controls?','The lower admissible collapse load.','The higher load.','Their arithmetic mean.','The mechanism with more drawing detail.','The least upper-bound mechanism governs the kinematic collapse estimate.'),
    Q('Section-modulus link','application','formula','Chapter 8 Examples — if fy is fixed, what directly increases Mp in the ideal section calculation?','A larger plastic section modulus Zp.','A smaller Zp.','A smaller area regardless of geometry.','A lower yield stress.','Mp = fy Zp, so plastic moment increases with Zp for the same steel grade.'),
    Q('Example purpose','retrieval','concept','Chapter 8 Examples — why are both plastic-collapse and local-buckling calculations included?','To show that usable plastic resistance depends on both mechanism strength and section stability.','Because buckling and plasticity are unrelated.','Only to calculate density.','Only to check paint thickness.','The examples connect the two chapter themes: plastic reserve and instability limits.')
  ]);

  add('Summary',[
    Q('Summary synthesis','foundation','concept','Chapter 8 Summary — which two major themes are synthesized?','Plastic-collapse analysis and local plate-buckling behaviour.','Concrete creep and soil settlement.','Fire and corrosion only.','Timber and masonry only.','The summary joins plastic strength/redistribution with local instability and section classification.'),
    Q('Section-property recap','core','classification','Chapter 8 Summary — which section properties are explicitly tied to plastic bending?','Elastic section modulus, plastic section modulus and shape factor.','Only density and Poisson ratio.','Only area and perimeter.','Only thermal expansion.','The summary recaps Ze, Zp and shape factor as the section-level basis of plastic bending.'),
    Q('Collapse-analysis recap','core','concept','Chapter 8 Summary — what structural concepts are reviewed for plastic collapse?','Plastic hinges, mechanisms, and static/kinematic methods.','Only elastic vibration modes.','Only corrosion pits.','Only weld symbols.','These are the core tools for determining plastic limit loads.'),
    Q('Interaction recap','core','concept','Chapter 8 Summary — which actions are noted as reducing available plastic moment?','Significant axial force and shear.','Only self-weight.','Only temperature with no stress.','Only paint thickness.','The summary retains the chapter interaction warning for combined axial/shear and bending.'),
    Q('Classification recap','application','reasoning','Chapter 8 Summary — why is section classification placed next to plastic analysis?','It tells whether local buckling permits the strength and rotation assumptions used by plastic design.','It changes steel chemistry.','It replaces equilibrium.','It determines only member colour.','Plastic analysis requires sections capable of developing and sustaining the assumed plastic response.'),
    Q('Post-buckling recap','retrieval','concept','Chapter 8 Summary — what concept represents strength of slender internally supported plates after local buckling?','Effective width.','Plastic hinge length.','Radius of gyration only.','Bolt pitch.','Effective width is the design representation of post-buckling stress redistribution.')
  ]);

  add('Exercises',[
    Q('Exercise scope','foundation','classification','Chapter 8 Exercises — which combination matches the exercise scope?','Shape factors, plastic moments, collapse mechanisms and local-buckling checks.','Only concrete slab design.','Only soil bearing.','Only fire temperature.','The exercise set spans section plasticity, structural mechanisms and plate slenderness.'),
    Q('Shape-factor exercise skill','core','formula','Chapter 8 Exercises — what two section properties are needed to calculate shape factor?','Zp and Ze.','Area and density only.','E and G only.','Length and temperature only.','Shape factor is Zp/Ze.'),
    Q('Collapse-load exercise skill','core','concept','Chapter 8 Exercises — what must be identified before applying virtual work to a collapse problem?','A kinematically admissible mechanism and its compatible hinge rotations.','Only the steel density.','Only the support colour.','A corrosion category.','Virtual work depends on a defined mechanism and compatible displacements/rotations.'),
    Q('Elastic-plastic comparison','application','reasoning','Chapter 8 Exercises — why compare elastic and plastic design results?','To see the reserve strength and redistribution available beyond first yield.','To prove elastic and plastic capacities are always identical.','To remove equilibrium.','To avoid section properties.','The comparison illustrates the extra resistance captured by plastic design where permitted.'),
    Q('Plate slenderness exercise','application','reasoning','Chapter 8 Exercises — what does a flange slenderness check protect against?','Premature local buckling before the intended section resistance is developed.','Excessive steel density.','Fatigue from every load cycle.','Foundation settlement.','Width-to-thickness limits control local instability.'),
    Q('Exercise strategy','retrieval','reasoning','Chapter 8 Exercises — which sequence is most sensible for a plastic-collapse numerical?','Identify Mp/section capacity → choose mechanism → relate rotations/displacements → equate internal and external work.','Ignore section capacity → guess load only.','Calculate density → stop.','Assume all moments are zero.','Worked plastic analysis combines section capacity with mechanism kinematics and work balance.')
  ]);

  add('Review Questions',[
    Q('Elastic versus plastic','foundation','concept','Chapter 8 Review — what is the key distinction between elastic and plastic design?','Plastic design can use reserve strength and redistribution beyond first yield when ductility/stability permit.','Elastic design always permits unlimited redistribution.','Plastic design ignores yield.','There is no distinction.','This distinction is one of the chapter review themes.'),
    Q('Shape factor recall','core','formula','Chapter 8 Review — what does shape factor compare?','Plastic moment capacity with first-yield moment capacity through Zp/Ze.','Density with yield stress.','Area with length.','Shear with temperature.','Shape factor measures section reserve between first yield and full plasticity.'),
    Q('Virtual work recall','core','concept','Chapter 8 Review — what principle underlies the kinematic plastic-analysis method?','External virtual work equals internal work at plastic hinges.','Moments exceed Mp everywhere.','All deformations are zero.','Only elastic strain energy is used.','The kinematic method uses virtual work of a collapse mechanism.'),
    Q('Collapse theorem recall','core','classification','Chapter 8 Review — which theorem is associated with a statically admissible moment field?','Lower-bound theorem.','Upper-bound theorem only.','Euler theorem.','Fatigue damage theorem.','The static/equilibrium approach provides a lower bound.'),
    Q('Section class recall','application','classification','Chapter 8 Review — which class is required for full plastic hinge rotation capacity?','Plastic/Class 1.','Compact/Class 2.','Semi-compact/Class 3.','Slender/Class 4.','Class 1 sections can develop Mp and sustain sufficient rotation for mechanism formation.'),
    Q('Whole-chapter retrieval','retrieval','reasoning','Chapter 8 Review — what single design question ties plastic analysis and local buckling together?','Can the section and structure develop and sustain the assumed plastic mechanism before instability limits the resistance?','What is the paint colour?','What is the concrete slump?','What is the soil permeability?','Plastic strength is usable only if local/global stability and rotation capacity permit the intended mechanism.')
  ]);
})();
