Object.assign(window.REVISION_BANK,{
'4:Buckling (Critical Load) Analysis':[
{id:'steel27-eigenbuckling',title:'Linear elastic buckling eigenvalue',level:'core',kind:'formula',q:'In a linearized elastic buckling analysis, the critical load factor is obtained from an eigenvalue condition commonly written as:',choices:['\\(\\det([K]+\\lambda[K_G])=0\\)','\\([M]\\ddot u+[C]\\dot u+[K]u=0\\)','\\(AE/L=0\\)','\\(\\sigma=E\\varepsilon\\) only'],answer:0,explanation:'Linear buckling analysis combines the elastic stiffness and geometric stiffness. Loss of stiffness at an eigenvalue identifies a bifurcation load factor.',math:'\\det([K]+\\lambda[K_G])=0',source:'N. Subramanian Ch.4 topic + supplemental textbook-aligned practice (model-generated)'},
{id:'steel27-buckling-interpret',title:'Meaning of the first buckling mode',level:'application',kind:'reasoning',q:'The lowest positive eigenvalue from an ideal elastic buckling analysis should usually be interpreted as:',choices:['An idealized critical load factor and associated instability mode, not automatically the final design strength','The guaranteed collapse load including imperfections','The yield strength of steel','A fatigue life prediction'],answer:0,explanation:'Eigenvalue buckling neglects many imperfections and nonlinearities, so it is primarily an ideal stability indicator.',source:'N. Subramanian Ch.4 topic + supplemental textbook-aligned practice (model-generated)',visual:{type:'mode-shape',description:'Straight compression member and first lateral eigen-buckling mode'}}
],
'5:Behaviour of Bolted Joints':[
{id:'steel27-bolt-bearing-slip',title:'Bearing-type bolt load transfer',level:'foundation',kind:'concept',q:'In an ordinary bearing-type bolted connection after any initial clearance is taken up, load is transferred mainly by:',choices:['Bolt shear together with bearing between bolt and connected plate','Friction alone with no bolt contact','Weld throat stress','Torsion of the entire plate only'],answer:0,explanation:'Bearing-type joints develop contact between the bolt shank and hole edge; resistance is governed by bolt shear, plate bearing and related limit states.',source:'N. Subramanian Ch.5 topic + supplemental textbook-aligned practice (model-generated)',visual:{type:'connection-diagram',description:'Single-lap bolted joint showing bolt shear plane and plate bearing zones'}},
{id:'steel27-bolt-pitch',title:'Why bolt spacing limits matter',level:'core',kind:'reasoning',q:'Minimum bolt pitch and edge-distance requirements primarily help to:',choices:['Avoid local tearing/splitting and provide practical force transfer and fabrication clearance','Increase Young’s modulus','Eliminate all connection deformation','Make every joint slip-critical'],answer:0,explanation:'Adequate spacing reduces local failure risks around holes and allows proper fabrication and installation.',source:'N. Subramanian Ch.5 topic + supplemental textbook-aligned practice (model-generated)'}
],
'7:Modes of Failure':[
{id:'steel27-tension-modes',title:'Three key tension-member limit states',level:'core',kind:'concept',q:'A steel tension member is commonly checked for which set of fundamental strength limit states?',choices:['Gross-section yielding, net-section rupture, and block shear','Euler buckling, web crippling, and torsional buckling only','Bearing, fatigue, and fire only','Local plate buckling only'],answer:0,explanation:'Tension-member design must consider yielding of the gross area, rupture through the reduced net area and block-shear failure around connections.',source:'N. Subramanian Ch.7 topic + IS 800-aligned supplemental practice (model-generated)'},
{id:'steel27-netarea',title:'Why bolt holes reduce rupture resistance',level:'application',kind:'formula',q:'For a plate with a transverse line of bolt holes, rupture resistance is based on net area because the holes:',choices:['Reduce the effective cross-sectional area available to carry tensile stress','Increase gross area','Eliminate stress concentration','Increase plate thickness'],answer:0,explanation:'The critical rupture path passes through reduced material area at holes, so net-section properties govern that limit state.',math:'A_n=A_g-\\sum d_h t\\quad\\text{(simple straight critical path)}',source:'N. Subramanian Ch.7 topic + IS 800-aligned supplemental practice (model-generated)',visual:{type:'connection-diagram',description:'Tension plate with a transverse row of bolt holes and highlighted net section'}}
],
'8:Plastic Hinge Concept':[
{id:'steel27-plastic-hinge',title:'Plastic hinge rotation',level:'core',kind:'concept',q:'An ideal plastic hinge in a beam section is characterized by:',choices:['Moment remaining approximately at plastic moment while substantial rotation develops','Zero moment and zero rotation','Elastic moment increasing without limit','Axial force becoming zero automatically'],answer:0,explanation:'Once the full section yields in bending, additional rotation can occur at approximately constant plastic moment in the idealized rigid-plastic model.',math:'M\\approx M_p\\quad\\text{during plastic rotation}',source:'N. Subramanian Ch.8 topic + supplemental textbook-aligned practice (model-generated)',visual:{type:'graph',description:'Idealized moment-rotation curve showing elastic rise and plastic plateau'}}
],
'10:Lateral Torsional Buckling of Symmetric Sections':[
{id:'steel27-ltb-restraint',title:'What restraint raises LTB resistance?',level:'application',kind:'reasoning',q:'For an I-beam susceptible to lateral-torsional buckling, reducing the unrestrained length of the compression flange generally:',choices:['Increases lateral-torsional buckling resistance','Decreases resistance in every case','Has no effect on stability','Eliminates bending stress'],answer:0,explanation:'Closer effective lateral/torsional restraint reduces the length over which the beam can buckle laterally and twist.',source:'N. Subramanian Ch.10 topic + supplemental textbook-aligned practice (model-generated)',visual:{type:'buckling-mode',description:'I-beam segment showing coupled lateral displacement and twist between restraints'}}
]
});