window.REVISION_BANK={
'1:Mechanical Properties of Steel':[
{id:'stress-strain-zones',title:'Read the stress–strain curve',level:'foundation',kind:'concept',q:'Which sequence best describes the usual progression of a ductile structural-steel tensile test?',choices:['Elastic response → yielding → strain hardening → necking/fracture','Yielding → elastic response → no fracture','Necking → elastic response → yielding','Only perfectly elastic behaviour'],answer:0,explanation:'Structural steel first behaves approximately elastically, then yields, strain hardens, reaches ultimate strength and finally necks/fractures.',source:'Subramanian Ch.1 mechanical properties'},
{id:'young-modulus',title:'Young’s modulus',level:'core',kind:'formula',q:'In the initial linear elastic range, which relation defines Young’s modulus E?',choices:['E=σ/ε','E=ε/σ','E=σ·ε','E=ρg'],answer:0,explanation:'Young’s modulus is the slope of the linear elastic stress–strain curve.',math:'E=\\frac{\\sigma}{\\varepsilon}',source:'Subramanian Ch.1 mechanical properties'},
{id:'yield-vs-ultimate',title:'Yield versus ultimate strength',level:'core',kind:'concept',q:'Which strength normally occurs first as a ductile steel tensile specimen is loaded monotonically?',choices:['Yield strength','Ultimate tensile strength','Fracture strength always before yield','Both are identical for all steels'],answer:0,explanation:'Yield marks the onset of substantial plastic deformation; the ultimate tensile strength is reached later.',source:'Subramanian Ch.1 mechanical properties'},
{id:'strain-number',title:'Elastic strain calculation',level:'application',kind:'numerical',q:'Using E=200 GPa, what elastic strain corresponds to σ=100 MPa?',choices:['0.0005','0.005','0.05','500'],answer:0,explanation:'Convert units consistently: 100 MPa / 200,000 MPa = 0.0005.',math:'\\varepsilon=\\frac{100}{200000}=5\\times10^{-4}',source:'Subramanian Ch.1 mechanical properties'}
],
'1:Residual Stresses':[
{id:'residual-source',title:'Origin of residual stress',level:'foundation',kind:'concept',q:'Which fabrication process can generate residual stresses in a steel member?',choices:['Welding with nonuniform heating and cooling','Only applying a perfectly uniform temporary load','Painting at room temperature only','Measuring the section dimensions'],answer:0,explanation:'Nonuniform thermal expansion and contraction during welding can leave self-equilibrating stresses after cooling.',source:'Subramanian Ch.1 residual stresses'},
{id:'self-equilibrating',title:'Self-equilibrating stress field',level:'core',kind:'reasoning',q:'Why can residual stress exist without an external force resultant?',choices:['Tensile and compressive residual regions can balance each other over the cross-section','Residual stress violates equilibrium','The member mass becomes zero','Residual stress is not a real stress'],answer:0,explanation:'Residual stresses are internally balanced so their net force and moment can satisfy equilibrium.',source:'Subramanian Ch.1 residual stresses'},
{id:'buckling-effect',title:'Residual stress and buckling',level:'application',kind:'concept',q:'Why are residual stresses important in compression-member design?',choices:['Some fibres may reach yield earlier, affecting inelastic buckling behaviour','They always increase Euler load','They eliminate imperfections','They make slenderness irrelevant'],answer:0,explanation:'Residual stresses contribute to early yielding and are one reason real columns depart from ideal Euler behaviour.',source:'Subramanian Ch.1 and compression-member context'}
],
'2:Limit States Method (LSM)':[
{id:'limit-state-idea',title:'What is a limit state?',level:'foundation',kind:'concept',q:'What does a limit state represent in structural design?',choices:['A condition beyond which the structure no longer satisfies a required performance criterion','A fixed member length','Only the yield stress of steel','Only a construction sequence'],answer:0,explanation:'Limit states describe unacceptable conditions such as collapse or excessive serviceability response.',source:'Subramanian Ch.2'},
{id:'ultimate-service',title:'Ultimate versus serviceability',level:'core',kind:'classification',q:'Which is primarily a serviceability concern?',choices:['Excessive deflection','Overall structural collapse','Plastic mechanism formation','Loss of equilibrium'],answer:0,explanation:'Serviceability limit states concern usability, comfort, appearance and similar performance, while ultimate states concern safety against failure.',source:'Subramanian Ch.2'},
{id:'design-strength',title:'Characteristic to design strength',level:'core',kind:'formula',q:'In a partial-safety-factor format, design material strength is generally obtained by:',choices:['Dividing characteristic strength by an appropriate material partial factor','Multiplying characteristic strength by every load factor','Ignoring material variability','Adding dead load to yield stress'],answer:0,explanation:'Material partial factors reduce characteristic resistance to a design resistance level.',math:'f_d=\\frac{f_k}{\\gamma_m}',source:'Subramanian Ch.2 limit-state concepts'}
],
'3:Dead Loads':[
{id:'dead-definition',title:'Recognise dead load',level:'foundation',kind:'concept',q:'Which is most clearly a dead load?',choices:['Self-weight of a permanent steel beam','A moving crane trolley','A temporary crowd','A gust of wind'],answer:0,explanation:'Dead load comes from permanent components and fixed construction.',source:'Subramanian Ch.3'},
{id:'selfweight',title:'Compute member self-weight',level:'application',kind:'formula',q:'Which expression gives the weight W of a prismatic member from density ρ, area A and length L?',choices:['W=ρALg','W=ρA/L','W=AL/g','W=ρg/A'],answer:0,explanation:'Mass is ρAL and weight is mass times gravitational acceleration.',math:'W=\\rho A L g',source:'Subramanian Ch.3'}
],
'3:Load Combinations':[
{id:'why-combine',title:'Why use load combinations?',level:'foundation',kind:'concept',q:'Why are structural loads checked in combinations rather than one at a time only?',choices:['Several actions can occur together and their design probabilities/effects must be represented','Loads never occur simultaneously','Combination removes the need for analysis','Only dead load matters in steel design'],answer:0,explanation:'Design combinations represent plausible simultaneous actions with prescribed factors.',source:'Subramanian Ch.3'},
{id:'factor-purpose',title:'Purpose of load factors',level:'core',kind:'concept',q:'What is the main role of load partial factors in limit-state design?',choices:['Account for uncertainty and target reliability in design actions','Convert steel to concrete','Calculate Young’s modulus','Set member colour'],answer:0,explanation:'Factors account for variability and uncertainty in actions and design situations.',source:'Subramanian Ch.2–3'}
],
'5:Bolted Connections':[
{id:'bolt-actions',title:'How bolts transfer load',level:'foundation',kind:'concept',q:'In a bearing-type bolted lap joint, which actions are central to load transfer?',choices:['Bolt shear and bearing at the connected plates/bolt','Only flexural buckling of the bolt as a long column','Only torsion of the plate','Only thermal expansion'],answer:0,explanation:'Ordinary bearing connections commonly transfer load through bolt shear and bearing between bolt and plate.',source:'Subramanian Ch.5'},
{id:'bolt-shear-planes',title:'Single versus double shear',level:'core',kind:'concept',q:'Why can a bolt in double shear carry more shear than the same bolt in single shear, all else equal?',choices:['Two shear planes participate instead of one','Its diameter doubles automatically','The plate thickness becomes zero','Bearing is eliminated'],answer:0,explanation:'Double shear provides two resisting shear planes through the bolt.',source:'Subramanian Ch.5'},
{id:'bolt-group',title:'Bolt-group load sharing',level:'application',kind:'reasoning',q:'For a concentric direct shear load applied through the centroid of a symmetric identical bolt group, the simplest elastic assumption is that:',choices:['Direct shear is shared equally among the bolts','Only one bolt carries all load','No bolt carries shear','The outer bolt always carries zero'],answer:0,explanation:'For concentric direct load and identical bolts, the basic direct-shear component is distributed equally.',source:'Subramanian Ch.5 connection fundamentals'}
],
'7:Modes of Failure':[
{id:'tension-modes',title:'Tension-member failure modes',level:'foundation',kind:'classification',q:'Which set contains recognised tension-member limit states?',choices:['Gross-section yielding, net-section rupture, block shear','Euler buckling only','Lateral-torsional buckling only','Concrete punching only'],answer:0,explanation:'Tension-member design checks yielding, rupture and connection-region block shear among the main strength modes.',source:'Subramanian Ch.7'},
{id:'gross-yield',title:'Gross-section yielding',level:'core',kind:'concept',q:'Which area is associated with yielding of the gross section?',choices:['Gross area A_g','Net area A_n only','Bolt area only','Weld throat only'],answer:0,explanation:'Gross-section yielding is based on the full gross cross-sectional area.',source:'Subramanian Ch.7'},
{id:'net-rupture',title:'Net-section rupture',level:'core',kind:'concept',q:'Why can bolt holes reduce tension-member rupture strength?',choices:['They reduce the effective/net area available to resist tension','They increase Young’s modulus','They remove all stress concentration','They increase gross area'],answer:0,explanation:'Material removed by holes reduces the net section; connection geometry can also create shear-lag effects.',source:'Subramanian Ch.7'}
],
'8:Plastic Hinge Concept':[
{id:'hinge-meaning',title:'Meaning of a plastic hinge',level:'foundation',kind:'concept',q:'What is a plastic hinge in idealised plastic analysis?',choices:['A yielded cross-section that can undergo substantial rotation at approximately plastic moment','A physical pin installed in the beam','A zero-moment support only','A fracture through the entire member'],answer:0,explanation:'A plastic hinge is an idealisation of a fully yielded section sustaining near-plastic moment while rotation increases.',source:'Subramanian Ch.8'},
{id:'mp',title:'Plastic moment',level:'core',kind:'formula',q:'Which expression defines ideal plastic moment capacity from yield stress and plastic section modulus?',choices:['M_p=f_y Z_p','M_p=EI/L','M_p=AE/L','M_p=f_y/A'],answer:0,explanation:'The plastic section modulus Z_p converts yield stress into fully plastic moment capacity.',math:'M_p=f_y Z_p',source:'Subramanian Ch.8'},
{id:'mechanism',title:'From hinges to mechanism',level:'application',kind:'concept',q:'What happens when enough plastic hinges form to convert a statically restrained structure into a mechanism?',choices:['Plastic collapse mechanism can develop','Elastic stiffness becomes infinite','All moments become zero instantly','The structure becomes more stable'],answer:0,explanation:'Collapse in ideal plastic analysis occurs when a mechanism forms under the applied load pattern.',source:'Subramanian Ch.8'}
],
'9:Elastic Buckling of Slender Compression Members':[
{id:'euler-formula',title:'Euler buckling load',level:'core',kind:'formula',q:'For an ideal slender column, which expression gives Euler elastic critical load?',choices:['P_cr=π²EI/(KL)²','P_cr=AE/L','P_cr=f_yA','P_cr=EI/L'],answer:0,explanation:'Elastic critical load depends on flexural rigidity and inverse square of effective length.',math:'P_{cr}=\\frac{\\pi^2EI}{(KL)^2}',source:'Subramanian Ch.9'},
{id:'axis-choice',title:'Which axis buckles first?',level:'application',kind:'reasoning',q:'For the same effective length, about which principal axis is flexural buckling most likely first?',choices:['The axis with the smaller second moment of area I','The axis with the larger I','Either axis regardless of I','Only the vertical global axis'],answer:0,explanation:'Euler load is proportional to I, so the weaker axis has the smaller elastic buckling load.',source:'Subramanian Ch.9'},
{id:'radius-gyration',title:'Radius of gyration',level:'core',kind:'formula',q:'How is radius of gyration r related to area A and second moment of area I?',choices:['r=√(I/A)','r=I/A','r=√(A/I)','r=IA'],answer:0,explanation:'Radius of gyration packages section stiffness and area into the slenderness definition.',math:'r=\\sqrt{\\frac{I}{A}}',source:'Subramanian Ch.9'},
{id:'slenderness',title:'Member slenderness',level:'application',kind:'formula',q:'Which expression represents effective slenderness ratio?',choices:['KL/r','Kr/L','A/L','EI/A'],answer:0,explanation:'Effective length divided by radius of gyration is the central nondimensional slenderness measure.',math:'\\lambda=\\frac{KL}{r}',source:'Subramanian Ch.9'}
],
'10:Lateral Torsional Buckling of Symmetric Sections':[
{id:'ltb-idea',title:'What is lateral-torsional buckling?',level:'foundation',kind:'concept',q:'What characterises lateral-torsional buckling of an unrestrained beam?',choices:['Lateral movement of the compression region accompanied by twist','Pure axial shortening without bending','Only local bolt shear','Only vertical deflection with no twist'],answer:0,explanation:'An unrestrained beam can lose stability by moving laterally and twisting under major-axis bending.',source:'Subramanian Ch.10'},
{id:'restraint-effect',title:'Effect of lateral restraint',level:'core',kind:'reasoning',q:'What generally happens to lateral-torsional buckling resistance when effective lateral restraint spacing is reduced?',choices:['Resistance generally increases','Resistance always decreases','It has no effect','The beam becomes a tension member'],answer:0,explanation:'Shorter unrestrained lengths inhibit lateral-torsional instability.',source:'Subramanian Ch.10'},
{id:'compression-flange',title:'Compression flange role',level:'core',kind:'concept',q:'Why is restraint of the compression flange especially important for a beam susceptible to lateral-torsional buckling?',choices:['The compression region tends to move laterally and initiate coupled twist','The tension flange alone determines all buckling','Compression has no relation to instability','It removes shear force entirely'],answer:0,explanation:'Lateral restraint to the compression region is a primary stabilising mechanism against LTB.',source:'Subramanian Ch.10'}
],
'18:Shear Centre':[
{id:'shear-centre-def',title:'Meaning of shear centre',level:'foundation',kind:'concept',q:'What is the shear centre of a cross-section?',choices:['The point through which transverse load can act without causing twist','The centroid in every possible section','The point of maximum normal stress only','The centre of every bolt hole'],answer:0,explanation:'For open or unsymmetric sections, the shear centre may differ from the centroid; loading through it avoids torsional rotation from transverse shear.',source:'Subramanian Ch.18'},
{id:'centroid-vs-sc',title:'Centroid versus shear centre',level:'core',kind:'concept',q:'For a doubly symmetric I-section, where is the shear centre?',choices:['At the centroid/intersection of symmetry axes','Always outside the section','At the top flange tip','At a random web point'],answer:0,explanation:'For doubly symmetric sections, symmetry places the shear centre at the centroid.',source:'Subramanian Ch.18'}
]};