(() => {
const B=window.REVISION_BANK;
const add=(k,rows)=>{B[k]=[...(B[k]||[]),...rows.map((r,i)=>({id:`ch3d-${i+1}-${k.replace(/[^a-z0-9]/gi,'').toLowerCase()}`,title:r[0],level:r[1],kind:r[2],q:r[3],choices:r[4],answer:r[5],explanation:r[6],...(r[7]?{math:r[7]}:{}),source:'N. Subramanian, Design of Steel Structures, Ch.3'}))]};
add('3:Introduction',[
['Load identification','foundation','classification','Which action belongs in the Chapter 3 loading inventory?',['Wind action','Steel yield strength','Bolt grade','Weld electrode class'],0,'Wind is one of the natural actions the chapter requires the designer to identify before analysis.'],
['Why combinations matter','core','reasoning','What is the main danger in checking every load only in isolation?',['A simultaneous combination may produce a more unfavourable effect','Dead load disappears','Material strength becomes unknown','All actions become static'],0,'Design must consider combinations because simultaneous actions can govern member forces and stability.'],
['Natural versus man-made','foundation','classification','Which pair contains one natural and one man-made action from the chapter opening list?',['Earthquake and crane load','Yield stress and density','Buckling and corrosion','Ductility and toughness'],0,'Earthquake is a natural hazard action; crane loading is associated with use or operation.'],
['Loading before member design','core','sequence','Why does the loading chapter logically come before detailed member design?',['Member actions cannot be assessed until design loads and combinations are established','Steel properties are irrelevant','Connections are designed without forces','Loads are chosen after sections'],0,'Loads and their combinations generate the action effects used in member design.'],
['Unfavourable effect','application','reasoning','A load increases compression in one member but reduces it in another. What should the designer seek?',['The arrangement that is most unfavourable for the particular effect being checked','Always the largest numerical load alone','Always the smallest reaction','Only dead load'],0,'The governing case is tied to the response quantity being checked, not simply to the largest individual action.'],
['Opening chapter recall','retrieval','mcq','Which set best summarises the Chapter 3 task?',['Identify actions → quantify them → combine them → obtain governing effects','Choose steel grade → ignore actions → detail bolts','Calculate density → paint → erect','Select a section before loading'],0,'Chapter 3 establishes the actions and combinations that feed structural analysis and design.']]);
add('3:Characteristic Actions (Loads)',[
['Return period meaning','foundation','concept','A return period R corresponds to what annual exceedance probability in the chapter?',['1/R','R','1-R','R²'],0,'The annual probability of exceedance is taken as 1/R.','\\displaystyle p=\\frac{1}{R}'],
['Fifty-year annual exceedance','application','numerical','For a 50-year return period, what annual exceedance probability follows directly from 1/R?',['2%','5%','20%','50%'],0,'1/50 = 0.02 = 2%.','\\displaystyle p=\\frac{1}{50}=0.02'],
['At least one exceedance','core','formula','Which expression gives the probability of at least one exceedance in N years for return period R?',['1-(1-1/R)^N','(1/R)^N','N/R only in all cases','1-NR'],0,'The chapter uses the complement of no exceedance in all N years.','P_N=1-\\left(1-\\frac1R\\right)^N'],
['Characteristic load idea','foundation','concept','What is a characteristic action intended to represent?',['A load level associated with an accepted small probability of exceedance','The smallest load ever measured','Only dead load','A material resistance'],0,'Characteristic actions are probabilistic design values tied to an accepted exceedance likelihood.'],
['When statistics are unavailable','core','reasoning','What does the chapter indicate should be used when reliable statistical load data are not available?',['The code-specified load','Zero load','Yield strength','A guessed average without reference'],0,'Codal values provide the characteristic action where direct statistical definition is unavailable.'],
['Probability distinction','retrieval','mcq','Which statement is correct?',['Return period is not the same as a guarantee that the event occurs exactly once every R years','A 50-year event must occur on year 50','Characteristic load is always the maximum physically possible load','Annual exceedance probability equals R'],0,'Return period is a probabilistic measure, not a deterministic timetable.']]);
add('3:Dead Loads',[
['Permanent action','foundation','classification','Which load is permanent for the completed structure?',['Self-weight of fixed cladding','Movable furniture','A passing crane trolley load','A gust of wind'],0,'Dead load includes permanent structural and non-structural components.'],
['Dead-load source','core','concept','How is member self-weight commonly estimated in the chapter approach?',['From nominal/average dimensions and unit weight','From wind speed','From response spectrum','From yield stress alone'],0,'Permanent self-weight is obtained from geometry and material unit weight.'],
['Fixed equipment','foundation','classification','Fixed permanently installed equipment is generally treated as:',['Dead load','Earthquake load only','Temperature effect','Residual stress'],0,'Permanent fixed equipment contributes to dead load.'],
['Stabilising dead load','core','reasoning','Why can overestimating dead load be unsafe in an uplift or overturning check?',['Dead load may be a stabilising action, so exaggerating it can overstate resistance','Dead load always destabilises','Dead load changes steel yield stress','It eliminates wind'],0,'When permanent weight provides stability, an excessive estimate can be unconservative.'],
['Dead-load predictability','core','reasoning','Compared with many environmental actions, why is dead load usually more predictable?',['Permanent geometry and material weights are relatively well defined','It has no uncertainty at all','It occurs only during construction','It is always zero after erection'],0,'Dead loads are generally tied to known permanent components, though tolerances and actual weights still vary.'],
['Dead-load recall','retrieval','mcq','Which code family does the chapter associate with dead-load unit weights in India?',['IS 875 Part 1','IS 1893 only','IS 800 Section 12 only','IS 456 only'],0,'The chapter refers to IS 875 Part 1 for dead loads.']]);
add('3:Imposed Loads',[
['Former terminology','foundation','recognition','Imposed load was traditionally called:',['Live load','Dead load','Residual load','Prestress'],0,'The chapter notes the older term live load for imposed load.'],
['Occupancy source','foundation','classification','Which is a typical imposed load?',['People occupying a floor','Permanent beam self-weight','Fixed wall weight','Steel residual stress'],0,'Occupants and movable contents are typical imposed loads.'],
['Variation','core','reasoning','Why do imposed loads require probabilistic/codal treatment?',['They vary with use, position and time','They are identical at every instant','They are material strengths','They act only during earthquakes'],0,'Occupancy and movable loads are variable rather than permanently fixed.'],
['Gradual loading','core','concept','A gradually applied imposed load may often be represented by:',['A static equivalent','Only an impact factor','A thermal strain','A residual stress diagram'],0,'The chapter distinguishes gradually applied loads from dynamic/impact actions.'],
['Impact distinction','core','classification','Repeated impact or rapidly applied operational loading should be treated differently because it is:',['Dynamic rather than purely static','Always dead load','A material property','Never structural'],0,'Rapid or repeated application can introduce dynamic effects.'],
['Imposed-load recall','retrieval','mcq','Which code part does the chapter associate with occupancy imposed loads in India?',['IS 875 Part 2','IS 875 Part 1 only','IS 1893 only','IS 808'],0,'IS 875 Part 2 covers imposed loads for occupancies.']]);
add('3:Temperature Effects',[
['Heating response','foundation','concept','What does an unrestrained steel member tend to do when its temperature rises?',['Expand','Contract','Lose all mass','Develop zero strain only'],0,'Positive temperature change produces free thermal expansion.'],
['Cooling response','foundation','concept','What does an unrestrained steel member tend to do when temperature falls?',['Contract','Expand','Twist necessarily','Yield necessarily'],0,'Cooling produces thermal contraction.'],
['Thermal movement formula','core','formula','Which relation gives free thermal length change?',['ΔL=αΔTL','ΔL=P/A','ΔL=My/I','ΔL=VL/EI'],0,'Free thermal movement is coefficient of expansion times temperature change times original length.','\\Delta L=\\alpha\\,\\Delta T\\,L'],
['Steel expansion coefficient','core','recognition','What approximate coefficient of linear thermal expansion for steel is cited in the Chapter 3 lesson?',['12×10⁻⁶/°C','12×10⁻³/°C','200×10³/°C','0.3/°C'],0,'The lesson records approximately 12×10^-6 per °C.','\\alpha\\approx12\\times10^{-6}/^\\circ C'],
['Restraint effect','application','reasoning','When can temperature change create significant structural stress?',['When free expansion or contraction is restrained','Only when movement is completely free','Only when dead load is zero','Never in steel'],0,'Restraint converts otherwise free thermal movement into force and stress.'],
['Expansion-joint purpose','retrieval','mcq','Why are expansion joints or suitable bracing layouts relevant to temperature effects?',['They can permit or manage thermal movement','They increase steel density','They eliminate gravity loads','They determine yield strength'],0,'Detailing and restraint conditions determine whether thermal movement becomes a force effect.']]);
add('3:Hydrostatic and Soil Pressure',[
['Below-ground actions','foundation','classification','Which structure is especially likely to require soil and hydrostatic pressure checks?',['Basement wall','Roof purlin only','Interior floor beam only','Tension rod in dry air only'],0,'Basements and retaining/foundation elements interact with soil and groundwater.'],
['Surcharge effect','core','reasoning','What can a surface surcharge do to lateral earth pressure?',['Increase it','Always reduce it to zero','Change steel grade','Remove water pressure'],0,'Additional surcharge can increase the pressure carried by retaining elements.'],
['Below water table','core','concept','How does the chapter treat soil below the water table?',['Use buoyant/reduced soil weight together with full hydrostatic pressure','Use dry weight and ignore water','Use water pressure only and no soil','Treat it as dead load only'],0,'Buoyancy reduces effective soil weight while water pressure acts hydrostatically.'],
['Hydrostatic trend','foundation','reasoning','Hydrostatic pressure in a static liquid generally increases with:',['Depth','Steel yield strength','Beam span only','Bolt diameter'],0,'Pressure increases with liquid head/depth.'],
['Foundation uplift','application','reasoning','Why may a basement foundation slab need an uplift check?',['Groundwater pressure can act upward on the slab','Dead load always acts upward','Soil has no weight','Wind acts below ground only'],0,'Hydrostatic pressure can create net upward force.'],
['Stability checks','retrieval','mcq','Which stability checks are specifically associated with soil/water actions in the lesson?',['Uplift, overturning and sliding','Only fatigue','Only lateral-torsional buckling','Only weld throat'],0,'Foundation and retaining systems can require uplift, overturning and sliding checks.']]);
add('3:Erection Loads',[
['Construction-stage action','foundation','classification','Which load exists specifically because the structure is being assembled?',['Stored erection materials on a partially completed frame','Final office occupancy only','Permanent self-weight only','Long-term corrosion loss'],0,'Materials and equipment during construction create erection-stage actions.'],
['Equipment action','foundation','classification','Which is an erection-stage source mentioned in the lesson?',['Erection equipment and its operation','Only finished cladding','Only snow after handover','Steel modulus'],0,'Construction equipment and operation loads must be considered.'],
['Temporary bracing','core','reasoning','Why can temporary bracing be essential during erection?',['The incomplete structure may not yet possess its final stability system','Final bracing is always already active','It reduces material density','It removes all wind'],0,'Construction stages can be less stable than the completed structure.'],
['Codes and erection','core','reasoning','Why should erection loads not be ignored merely because ordinary building-load tables focus on completed use?',['Temporary construction conditions can govern members or stability','Erection loads are never structural','They are always smaller than zero','They only affect paint'],0,'Construction-stage loading can be critical even if not fully stipulated in ordinary occupancy tables.'],
['Concurrent erection actions','application','reasoning','During erection, which other actions may still need consideration according to the lesson?',['Dead, wind and appropriate imposed loads','No other actions','Only corrosion','Only fatigue'],0,'The erection state is checked with relevant concurrent permanent and environmental/variable actions.'],
['Erection recall','retrieval','mcq','Which statement is safest?',['Design should consider the structure at vulnerable temporary stages as well as in its final state','Only the final completed state matters','Temporary instability cannot occur in steel','Erection equipment is never a load'],0,'Structural safety must extend through construction, not just service.']]);
add('3:Accidental Loads',[
['Accidental-action nature','foundation','concept','Accidental actions are typically:',['Low-probability but potentially severe','Permanent daily gravity loads','Material properties','Always small serviceability loads'],0,'The chapter treats accidental events as rare but potentially serious.'],
['Impact example','foundation','classification','Vehicle collision with a column is best classified as:',['Accidental impact action','Dead load','Temperature action','Residual stress'],0,'Collision/impact is a listed accidental action.'],
['Explosion example','foundation','classification','Blast from an explosion belongs to which action category?',['Accidental','Permanent','Imposed occupancy only','Thermal expansion only'],0,'Explosion is explicitly listed as an accidental event.'],
['Fire link','core','classification','In the chapter loading context, fire is treated as:',['An accidental design situation/action','A dead load','A section property','A wind coefficient'],0,'Fire is among the accidental events linked to structural safety.'],
['Progressive collapse','core','reasoning','Why does structural integrity matter after a local accidental failure?',['Alternate load paths can limit disproportionate collapse','It makes accidental actions more frequent','It removes all deformation','It guarantees no local damage'],0,'Robustness aims to prevent local damage from propagating into widespread collapse.'],
['Accidental recall','retrieval','mcq','Which set contains only accidental events from the lesson?',['Collision, explosion, fire','Dead load, live load, snow','Temperature, settlement, self-weight','Yielding, buckling, fatigue'],0,'Impact/collision, explosion and fire are the listed accidental-event group.']]);
add('3:Other Loads',[
['Settlement action','foundation','classification','Differential settlement is important because it can create:',['Secondary structural actions and deformation','Only dead weight reduction','Wind pressure','Material hardening'],0,'Unequal support movement can induce internal forces in restrained structures.'],
['Wave/current','foundation','classification','Wave and current effects are especially relevant to:',['Structures interacting with water','Interior office partitions only','Dry roof purlins only','Steel chemistry'],0,'The chapter includes wave and current loads among special actions.'],
['Ponding feedback','core','reasoning','What makes roof ponding a feedback problem?',['Deflection collects more water, which adds load and causes further deflection','Water decreases load as deflection grows','Deflection drains all roofs automatically','Ponding changes yield strength'],0,'Added water load can amplify the initial sag.'],
['Lack-of-fit','core','concept','Lack-of-fit stresses can arise when:',['Fabricated/erected geometry does not fit the intended configuration without forcing','All members fit freely','There is no restraint','Only steel density changes'],0,'Forced assembly or geometric mismatch can introduce secondary stress.'],
['Resonance','core','reasoning','Why can a resonant load become critical?',['Repeated forcing near a natural frequency can amplify response','It always reduces vibration','It is identical to dead load','It changes unit weight'],0,'Resonance is a dynamic amplification phenomenon included among other actions.'],
['Tall-building shortening','retrieval','mcq','Which tall-building effect is listed among the chapter other loads?',['Differential shortening of columns','Only snow drifting','Only bolt pretension','Only corrosion'],0,'Different column shortening can create compatibility effects in tall structures.']]);
add('3:Natural Hazards',[
['Hazard recognition','foundation','classification','Which is a natural hazard listed by the chapter?',['Landslide','Weld shrinkage','Bolt slip','Residual stress'],0,'Landslides are among the natural hazards considered.'],
['Flood recognition','foundation','classification','Flood belongs to which category in the Chapter 3 discussion?',['Natural hazard','Material defect','Connection resistance','Fabrication tolerance'],0,'Flood is explicitly treated as a natural hazard.'],
['Avalanche recognition','foundation','classification','An avalanche is classified as:',['Natural hazard','Dead load','Residual stress','Steel property'],0,'Avalanche is among the natural hazards listed.'],
['Why hazards matter','core','reasoning','Why are natural hazards central to structural loading?',['They can cause life loss, property damage and interruption of function','They affect only appearance','They never create dynamic response','They are material strengths'],0,'Hazards can have severe structural and societal consequences.'],
['Detailed treatment','core','retrieval','Which two natural actions receive especially detailed treatment in the chapter lesson?',['Wind and earthquake','Corrosion and welding','Density and hardness','Bolting and painting'],0,'Wind and earthquake are developed in detail because of their structural importance.'],
['Hazard versus effect','retrieval','mcq','Which statement is correct?',['A hazard is a source/event; structural analysis evaluates the actions/effects it induces','A hazard is identical to yield stress','Every hazard is permanent','Natural hazards cannot be codified'],0,'The hazard generates actions that must be represented for design.']]);
add('3:Extreme Winds',[
['Wind origin','foundation','concept','The chapter links wind primarily to:',['Atmospheric pressure differences associated with unequal heating','Steel thermal expansion only','Groundwater flow','Bolt pretension'],0,'Wind is moving air driven by atmospheric pressure differences.'],
['Dynamic wind','core','reasoning','Why can wind on a tall flexible building not always be treated as a steady static pressure?',['Pressure fluctuates and the structure can respond dynamically','Wind has no time variation','Tall buildings have infinite stiffness','Only dead load matters'],0,'Extreme wind can cause fluctuating along-wind and cross-wind response.'],
['Along-wind','foundation','recognition','Along-wind response refers broadly to motion:',['In the general direction of the wind action','Only vertically downward','Only about the member axis','With zero lateral load'],0,'The chapter distinguishes along-wind from cross-wind behaviour.'],
['Cross-wind','foundation','recognition','Cross-wind response is important because wind can generate:',['Motion transverse to the mean wind direction','Only gravity compression','No oscillation','Only temperature strain'],0,'Tall slender structures can develop transverse dynamic response.'],
['Wind tunnel outputs','application','classification','Which quantity can a wind-tunnel study provide for a tall building?',['Surface pressures and dynamic response information','Steel carbon percentage','Concrete cube strength','Bolt ultimate strength'],0,'Wind tunnels can measure pressure distributions and response-related data.'],
['Neighbour interference','application','reasoning','Why are neighbouring buildings relevant in a wind-tunnel study?',['They can alter the local wind field and interference effects','They change steel grade','They eliminate wind','They only affect dead load'],0,'Surrounding geometry can significantly modify pressures and response.']]);
add('3:Earthquakes',[
['Ground motion','foundation','concept','Earthquake structural action begins with:',['Ground motion/acceleration','Wind pressure','Thermal expansion','Dead load removal'],0,'Seismic action is induced by ground motion.'],
['Inertia force','core','formula','Which basic mechanics relation explains seismic inertia force?',['F=ma','F=EI/L','F=fyZp','F=ρg/A'],0,'Accelerating structural mass develops inertia force.','F=ma'],
['Cyclic reversal','core','reasoning','Why can earthquake design require resistance in both directions?',['Ground motion is cyclic and can reverse force/stress sign','Earthquake force is always one-way','Steel cannot carry reversed stress','Dead load reverses every second'],0,'Seismic actions can reverse, producing positive and negative member demands.'],
['Dynamic property','core','reasoning','Structural earthquake response depends on ground motion and also on:',['The structure’s dynamic properties','Paint colour','Only member density with no stiffness','Only bolt count'],0,'Period, mass, stiffness and related dynamic behaviour affect response.'],
['Gravity contrast','foundation','classification','Which statement best distinguishes earthquake action from ordinary gravity loading?',['Seismic inertia is dynamic and generated by acceleration','Gravity is always cyclic reversal','Earthquake is permanent self-weight','They are identical'],0,'Earthquake loading is fundamentally dynamic and inertia-based.'],
['Earthquake recall','retrieval','mcq','Which design implication follows from cyclic seismic action?',['Member actions may need checks for both positive and negative directions','Only downward reactions occur','No ductility is relevant','Only static self-weight is needed'],0,'Force reversal is a key characteristic of seismic response.']]);
add('3:Determination of Earthquake Forces',[
['Performance philosophy','foundation','concept','For minor frequent earthquakes, what performance objective is stated in the lesson?',['No damage','Collapse is acceptable','Major permanent deformation is required','Ignore the event'],0,'The lesson describes a tiered performance philosophy with little/no damage for minor events.'],
['Moderate event','core','concept','For a moderate earthquake, the lesson aims primarily to:',['Avoid significant structural damage','Guarantee no movement at all','Permit collapse','Ignore nonstructural effects completely'],0,'Moderate events should not cause significant structural damage.'],
['Major event','core','concept','For a major infrequent earthquake, the essential objective is:',['No collapse, even if damage occurs','No cracking of finishes under any condition','Zero acceleration','No member yielding ever'],0,'Life safety/collapse prevention governs severe rare events.'],
['Seismic zoning','foundation','recognition','Why does the code framework use seismic zoning?',['To represent regional variation in seismic hazard','To classify steel grades','To calculate dead load','To choose weld type'],0,'Seismic zones are part of representing spatial variation in earthquake hazard.'],
['Static versus dynamic procedures','core','reasoning','Why might different structures require static or dynamic seismic procedures?',['Structural characteristics and code applicability differ','Earthquake action is never dynamic','Only material density matters','Static analysis always gives exact response'],0,'The lesson notes that procedure choice depends on the structure and code framework.'],
['Seismic uncertainty','retrieval','mcq','Which earthquake attributes are described as uncertain?',['Amplitude, duration and frequency content','Steel density and yield stress only','Member colour and paint thickness','Bolt diameter only'],0,'Seismic ground motions vary in amplitude, duration and frequency characteristics.']]);
add('3:Determination of Wind Loads as per IS 875 (Part 3)',[
['Basic wind speed','foundation','concept','The mapped basic wind speed Vb in the chapter framework is referenced at what height?',['10 m','1 m','100 m','Roof ridge only'],0,'The lesson states the mapped basic wind speed is referenced at 10 m height.'],
['Return period basis','core','recognition','What return period is associated with the mapped basic wind speed in the lesson?',['50 years','1 year','5 years','500 years'],0,'The source lesson states a 50-year return period for the mapped basic wind speed.'],
['Design speed factors','core','formula','Which is the chapter expression for design wind speed?',['Vz=Vb k1 k2 k3 k4','Vz=Vb+k1+k2+k3+k4','Vz=Vb/(k1+k2)','Vz=fy/E'],0,'The design speed is the basic speed multiplied by modification factors.','V_z=V_bk_1k_2k_3k_4'],
['Risk factor','foundation','recognition','Which symbol in the chapter wind-speed equation represents the first modification factor?',['k1','fy','γm0','Zp'],0,'The design speed uses factors k1 through k4; k1 is the risk/probability factor in this framework.'],
['Terrain-height-size','core','recognition','Which factor is associated with terrain, height and structure size in the chapter framework?',['k2','k1 only','k4 only','E'],0,'The lesson identifies k2 with terrain/height/size effects.'],
['From speed to force','application','sequence','After obtaining design wind speed, what is the next conceptual step toward member loading?',['Convert speed to design pressure and then use pressure/force coefficients','Convert speed to yield stress','Ignore geometry','Calculate thermal strain'],0,'The wind framework proceeds from speed to pressure and then to forces using coefficients.']]);
add('3:Pattern Loading',[
['Continuous-structure need','foundation','concept','Pattern loading is especially relevant to:',['Continuous beams and rigid frames','Only isolated simply supported members with no continuity','Only tension coupons','Only material tests'],0,'Continuity makes member moments sensitive to where variable loads are placed.'],
['Alternate spans','core','recognition','Which arrangement is explicitly mentioned for pattern loading?',['Full imposed load on alternate spans','Dead load removed from all spans','Wind only on every third bolt','Temperature only at supports'],0,'Alternate-span live loading is one of the textbook pattern cases.'],
['Adjacent spans','core','recognition','Another pattern identified in the lesson is full imposed load on:',['Two adjacent spans','No spans','Only supports','Only one bolt'],0,'Two adjacent loaded spans are checked because they can govern support or span effects.'],
['All spans','foundation','recognition','Why is loading all spans still part of the pattern set?',['It can govern some response quantities even though other patterns govern others','It always gives zero moment','It eliminates dead load','It is only for earthquakes'],0,'Different response quantities can be governed by different live-load arrangements.'],
['Positive/negative moments','application','reasoning','Why can alternate live-load placement change whether positive or negative moments govern?',['Continuity redistributes response according to which spans carry variable load','Moment is independent of load position','Only steel grade controls moment','Supports carry no reaction'],0,'Continuous-system moment diagrams depend strongly on the location of variable loads.'],
['Pattern loading recall','retrieval','mcq','What is the goal of pattern loading?',['Find the realistic live-load arrangement that maximizes the effect being checked','Always maximize total building weight','Minimize every support reaction','Replace load combinations'],0,'Pattern loading searches for the critical spatial arrangement of variable action.']]);
add('3:Load Combinations',[
['Permanent plus variable','foundation','concept','Why are permanent and variable actions combined with different factors?',['Their uncertainties and probabilities differ','They are identical actions','Steel density changes','Factors are only for unit conversion'],0,'Limit-state combinations reflect different action characteristics and reliability treatment.'],
['Accompanying action','core','concept','What is an accompanying variable action?',['A variable action present with the leading variable action but generally reduced in the combination','A dead load','A material resistance','A residual stress'],0,'When several variable actions occur together, one may lead while others accompany it.'],
['Combination-factor logic','core','reasoning','Why are accompanying variable actions commonly reduced?',['Simultaneous maxima of independent variable actions are unlikely','Variable actions never occur together','Dead load is uncertain only','Reduction increases every load'],0,'Combination factors represent the reduced likelihood of coincident peaks.'],
['Accidental situation','core','classification','Does the chapter use the same combination format for ordinary and accidental design situations?',['No, accidental situations have separate combination expressions','Yes, always exactly identical','Accidental loads are ignored','Only dead load is used accidentally'],0,'The source distinguishes accidental design situations from ordinary combinations.'],
['Governing combination','application','reasoning','How should a designer select among several prescribed load combinations?',['Analyse/check them and use the one producing the governing design effect','Pick the one with the most terms without calculation','Always use dead load only','Average all combinations'],0,'Different combinations can govern different members and effects.'],
['Combination recall','retrieval','mcq','Which actions are among those combined in the chapter practical cases?',['Dead, imposed, wind, earthquake, crane/snow, erection and accidental actions','Only dead and paint','Only steel strength and density','Only temperature and hardness'],0,'The chapter provides combinations spanning the principal permanent, variable, environmental and accidental actions.']]);
add('3:Examples',[
['Worked-example purpose','foundation','concept','What is the main role of the Chapter 3 examples?',['Apply load definitions, calculations and combinations to design cases','Introduce steel metallurgy','Design weld electrodes','Classify cross-sections only'],0,'The examples convert loading concepts into quantitative design actions.'],
['Roof example data','core','recognition','In Example 3.13, what dead load is quoted in the lesson?',['1.60 kN/m²','1.15 kN/m²','0.70 kN/m²','4.14 kN/m²'],0,'The recorded example data are DL=1.60, LL=1.15 and WL=0.70 kN/m².'],
['Live-load example data','core','recognition','In Example 3.13, what live load is quoted?',['1.15 kN/m²','1.60 kN/m²','0.70 kN/m²','4.14 kN/m²'],0,'The lesson records LL=1.15 kN/m².'],
['Wind-load example data','core','recognition','In Example 3.13, what wind load magnitude is quoted?',['0.70 kN/m²','1.60 kN/m²','1.15 kN/m²','4.14 kN/m²'],0,'The lesson records WL=0.70 kN/m².'],
['Combination arithmetic','application','numerical','Using the quoted Example 3.13 values, what is 1.2(DL+LL+WL)?',['4.14 kN/m²','3.45 kN/m²','2.76 kN/m²','0.39 kN/m²'],0,'1.2(1.60+1.15+0.70)=1.2×3.45=4.14 kN/m².','1.2(1.60+1.15+0.70)=4.14\\;\\mathrm{kN/m^2}'],
['Examples recall','retrieval','mcq','Which topics do the worked examples span according to the lesson?',['Characteristic loads, roof/purlin loading, wind, earthquake, pattern loading and combinations','Only steel chemistry','Only weld design','Only corrosion'],0,'The examples cover the main loading calculations developed through the chapter.']]);
add('3:Summary',[
['Four-phase chain','foundation','sequence','Which sequence matches the chapter summary?',['Choose system → calculate loads → analyse → design members','Design members → ignore loads → paint → analyse','Analyse → choose loads afterward → demolish','Fabricate → calculate density → no analysis'],0,'The summary places load calculation before structural analysis and member design.'],
['Why loading is difficult','core','reasoning','Why does the summary call load determination especially important?',['Every later analysis/design result depends on the actions assumed','Loads do not affect member forces','Only appearance depends on loads','Material strength is determined by wind'],0,'Incorrect loading propagates directly into action effects and design decisions.'],
['Predictability contrast','core','classification','Which action is described as relatively predictable compared with wind and earthquake?',['Dead load','Extreme wind','Earthquake','Accidental blast'],0,'Permanent component weights are generally more predictable than environmental extremes.'],
['Probabilistic need','core','reasoning','Why do wind and earthquake require probabilistic/codal treatment?',['Their extreme occurrence and magnitude are uncertain','They are permanent','They are material properties','They never vary in time'],0,'Environmental hazards are inherently variable and uncertain.'],
['Chapter integration','application','reasoning','What error would undermine even a perfectly executed structural analysis?',['Using an incomplete or incorrect loading model','Using equilibrium equations','Checking combinations','Including dead load'],0,'Analysis is only as meaningful as the actions supplied to it.'],
['Summary recall','retrieval','mcq','What is the central message of Chapter 3?',['Correctly identify, quantify and combine actions before design','Member design is independent of loads','Only wind matters','Only dead load matters'],0,'The chapter is the bridge from hazards/use conditions to structural design actions.']]);
add('3:Exercise',[
['Characteristic-load practice','foundation','classification','Which exercise skill is explicitly mentioned in the lesson?',['Deriving a characteristic floor load from measurements','Calculating weld throat only','Finding steel carbon content','Designing a column base only'],0,'The exercise set includes a characteristic-load problem based on measurements.'],
['Probability practice','core','classification','Which probability task appears in the exercise description?',['Finding the probability of exceeding a specified office load','Finding probability of steel yielding from chemistry','Wind tunnel calibration only','Bolt slip probability only'],0,'The exercises include load-exceedance probability practice.'],
['Purlin practice','foundation','classification','What purlin-related calculation is included?',['Estimating purlin dead and live loads','Calculating torsional constant only','Corrosion allowance only','Weld electrode selection'],0,'The exercise set includes purlin load estimation.'],
['Truss practice','core','classification','Which structural effect is mentioned for a roof-truss exercise?',['Bending moments','Only corrosion','Only thermal conductivity','Only density'],0,'The lesson explicitly mentions obtaining roof-truss bending moments.'],
['Integrated practice','application','reasoning','Why are the Chapter 3 exercises important after reading the theory?',['They require conversion of load concepts into quantitative action effects','They replace the textbook','They remove the need for units','They test only memory of titles'],0,'Exercises build the calculation skill needed to apply the load definitions.'],
['Exercise recall','retrieval','mcq','Which broader topics also appear in the exercise set?',['Wind, earthquake, dynamic analysis and governing combinations','Only metallurgy','Only bolting','Only fire protection'],0,'The exercise set extends across the major environmental and combination topics.']]);
add('3:Review Questions',[
['Static/dynamic recall','foundation','classification','What distinction do the review questions ask the reader to make?',['Static versus dynamic loads','Elastic versus plastic steel grades only','Paint versus galvanizing','Bolts versus welds only'],0,'The review set opens with examples of static and dynamic actions.'],
['Action classifications','core','retrieval','Which three action classes are attributed to IS 800:2007 in the chapter review?',['Permanent, variable and accidental','Elastic, plastic and fracture','Wind, rain and snow only','Dead, steel and concrete'],0,'The review questions ask for permanent, variable and accidental action classifications.'],
['Code recall','core','retrieval','Which subject code references are included in the review scope?',['Wind, dead/live, earthquake and crane loading','Only concrete mix design','Only timber design','Only welding electrodes'],0,'The review set asks readers to identify relevant Indian standards for major load types.'],
['Characteristic definition','core','retrieval','Which definition is explicitly revisited by the Chapter 3 review questions?',['Characteristic load','Plastic section modulus only','Residual stress only','Weld throat only'],0,'Characteristic load is one of the early review prompts.'],
['Closed-book method','application','learning','What is the recommended way to use these review questions in Steel Quest?',['Attempt them from memory before checking the source','Read the source answer first every time','Skip retrieval','Memorise only page numbers'],0,'Active recall exposes gaps before the source is consulted.'],
['Review scope','retrieval','mcq','Why should the review node come after the topic ladder?',['It tests integrated recall across the whole chapter','It introduces a different subject','It replaces all calculations','It contains only dead-load questions'],0,'The review questions span the chapter and serve as an integrated retrieval checkpoint.']]);
})();