(() => {
const add={
'1:Introduction':[
{id:'c1-intro-role',title:'Purpose of structural design',level:'foundation',kind:'concept',q:'What two choices are central at the start of structural design?',choices:['Structural form and material','Paint colour and office location','Only member density','Only construction date'],answer:0,explanation:'The chapter opens by framing structural design around selecting a suitable structural form and material so the finished structure safely carries loads and performs acceptably.',source:'Subramanian Ch.1 Introduction'},
{id:'c1-intro-performance',title:'Beyond carrying load',level:'core',kind:'reasoning',q:'Why is simply carrying load not a complete description of structural design?',choices:['The structure must also perform acceptably in service','Only appearance matters','Loads are never uncertain','Steel has infinite stiffness'],answer:0,explanation:'The chapter links safety with acceptable structural performance; design is not only a question of avoiding immediate collapse.',source:'Subramanian Ch.1 Introduction'},
{id:'c1-intro-materials',title:'Steel among structural materials',level:'foundation',kind:'classification',q:'Which material is presented as one of several possible structural materials rather than the only option?',choices:['Steel','Only steel can be structural','Only aluminium can be structural','Only masonry can be structural'],answer:0,explanation:'The chapter positions steel alongside other structural materials before developing why steel is widely used.',source:'Subramanian Ch.1 Introduction'},
{id:'c1-intro-logic',title:'Design logic',level:'application',kind:'reasoning',q:'A proposed structural form cannot safely carry the intended actions. What does the chapter opening imply?',choices:['The form/material choice must be reconsidered','Ignore the actions','Increase paint thickness only','Proceed because steel is strong'],answer:0,explanation:'Structural form and material are design choices that must satisfy the required structural performance.',source:'Subramanian Ch.1 Introduction'}
],
'1:Historical Development':[
{id:'c1-hist-iron',title:'Before modern steel',level:'foundation',kind:'concept',q:'Which materials preceded widespread modern structural steel in the historical development described?',choices:['Cast iron and wrought iron','Only stainless steel','Only aluminium','Only reinforced concrete'],answer:0,explanation:'The chapter traces structural use from earlier iron products such as cast and wrought iron toward modern steel.',source:'Subramanian Ch.1 Historical Development'},
{id:'c1-hist-bessemer',title:'Bessemer significance',level:'core',kind:'reasoning',q:'What changed with the Bessemer process?',choices:['Steel could be produced much faster on a large scale','Steel stopped containing iron','Welding became unnecessary','All steels became stainless'],answer:0,explanation:'The historical importance is rapid large-scale steel production, which helped make steel practical for structural use.',source:'Subramanian Ch.1 Historical Development'},
{id:'c1-hist-modern',title:'Later steelmaking routes',level:'foundation',kind:'classification',q:'Which later processes are identified as modern developments after early steelmaking?',choices:['Basic-oxygen and electric processes','Timber seasoning and kiln drying','Concrete batching only','Electroplating only'],answer:0,explanation:'The chapter follows the historical sequence into basic-oxygen and electric steelmaking routes.',source:'Subramanian Ch.1 Historical Development'},
{id:'c1-hist-why',title:'Why history matters',level:'application',kind:'reasoning',q:'Why did faster steelmaking matter to structural engineering?',choices:['It made large-scale availability of structural steel practical','It eliminated structural analysis','It removed all fabrication operations','It made every section identical'],answer:0,explanation:'Mass production changed steel from a limited material into one that could support widespread structural construction.',source:'Subramanian Ch.1 Historical Development'}
],
'1:Processes Used for Iron and Steel Making':[
{id:'c1-process-order',title:'Manufacturing sequence',level:'foundation',kind:'sequence',q:'Which order best matches the chapter manufacturing route?',choices:['Ironmaking → steelmaking → casting/rolling','Rolling → mining → painting','Welding → ironmaking → mining','Casting → ore extraction → erection'],answer:0,explanation:'The chapter separates ironmaking, steelmaking, and the later casting/rolling operations used to create structural products.',source:'Subramanian Ch.1 steel manufacturing process; Chapter 1 PPT slides 2–5'},
{id:'c1-process-furnace',title:'Furnace role',level:'foundation',kind:'concept',q:'Why are furnace types discussed in the steelmaking chapter?',choices:['Different furnace routes are used in iron and steel production','Furnaces determine beam span directly','Furnaces are only for painting','Furnaces replace rolling'],answer:0,explanation:'The Chapter 1 slides begin with furnace types because thermal processing is fundamental to iron and steel production.',source:'Subramanian Ch.1; Chapter 1 PPT slides 2–5'},
{id:'c1-process-rolling',title:'From steel to section',level:'core',kind:'reasoning',q:'After steelmaking, which operation helps create common structural shapes?',choices:['Rolling','Soil compaction','Concrete curing','Timber laminating'],answer:0,explanation:'Casting and rolling convert steel into usable structural products.',source:'Subramanian Ch.1 steel manufacturing process'},
{id:'c1-process-distinction',title:'Ironmaking vs steelmaking',level:'core',kind:'concept',q:'Why does the source treat ironmaking and steelmaking as separate stages?',choices:['They are distinct production stages before final shaping','They are identical names for painting','One is a design code check','Neither affects production'],answer:0,explanation:'The chapter explicitly presents ironmaking and steelmaking as separate steps in the production chain.',source:'Subramanian Ch.1 steel manufacturing process'}
],
'1:Iron and Steel in India':[
{id:'c1-india-integrated',title:'Integrated plant meaning',level:'foundation',kind:'concept',q:'What best describes an integrated steel plant?',choices:['A plant combining multiple stages of iron and steel production','A shop that only paints finished beams','A laboratory that only tests bolts','A site that only erects trusses'],answer:0,explanation:'Integrated plants combine several stages of the production chain in one industrial system.',source:'Subramanian Ch.1 Iron and Steel in India; Chapter 1 PPT slide 6'},
{id:'c1-india-map',title:'Why plant locations are shown',level:'foundation',kind:'reasoning',q:'Why does the Chapter 1 slide deck include a map of integrated steel plants in India?',choices:['To connect structural steel with its industrial production base','To calculate beam deflection','To define plastic hinges','To classify bolts'],answer:0,explanation:'The map supports the chapter discussion of Indian steel production and availability.',source:'Subramanian Chapter 1 PPT slide 6'},
{id:'c1-india-history',title:'Long history of iron use',level:'core',kind:'concept',q:'What broad point does the chapter make about India and iron?',choices:['India has a long history of iron use and steel production','Iron was introduced only after aluminium','India has no integrated steel industry','Steel is used only for bridges'],answer:0,explanation:'The chapter places modern production in the context of a long history of iron use in India.',source:'Subramanian Ch.1 Iron and Steel in India'},
{id:'c1-india-infrastructure',title:'Industry importance',level:'application',kind:'reasoning',q:'Why is domestic steel production relevant to structural engineering?',choices:['Construction and infrastructure depend on reliable structural-steel supply','It determines only architectural colour','It removes the need for fabrication','It fixes every section size'],answer:0,explanation:'The source connects the steel industry with construction and infrastructure development.',source:'Subramanian Ch.1 Iron and Steel in India'}
],
'1:Metallurgy of Steel':[
{id:'c1-met-crystal',title:'Crystal structure',level:'foundation',kind:'concept',q:'What internal feature is introduced before discussing steel behaviour?',choices:['Crystalline structure','Paint pigment','Bolt spacing only','Concrete aggregate size'],answer:0,explanation:'The Chapter 1 slides introduce crystalline structure and the structure of steel to connect microstructure with engineering properties.',source:'Subramanian Chapter 1 PPT slides 7–9'},
{id:'c1-met-property',title:'Microstructure and properties',level:'core',kind:'reasoning',q:'Why does a structural engineer care about steel microstructure?',choices:['It influences strength, ductility and toughness','It controls only surface colour','It makes loading irrelevant','It replaces section properties'],answer:0,explanation:'The chapter uses metallurgy to explain why material behaviour changes with internal structure.',source:'Subramanian Ch.1 Metallurgy of Steel'},
{id:'c1-met-heat',title:'Heat treatment',level:'foundation',kind:'concept',q:'What is the purpose of discussing heat treatment in the metallurgy section?',choices:['Heat treatment can modify steel microstructure and properties','It is only a fire-protection coating','It measures density','It eliminates carbon from all steel'],answer:0,explanation:'Heat treatment is presented as a way of changing microstructure and therefore material properties.',source:'Subramanian Chapter 1 PPT slide 9'},
{id:'c1-met-diagram',title:'Iron–carbon context',level:'core',kind:'concept',q:'The iron–carbon equilibrium diagram is useful mainly because it relates:',choices:['Composition and phase structure','Member length and wind speed','Bolt diameter and paint colour','Concrete slump and steel density'],answer:0,explanation:'The metallurgy discussion uses the iron–carbon relationship to connect composition, phases and material response.',source:'Subramanian Ch.1 Metallurgy of Steel'}
],
'1:Alloying Elements in Steel':[
{id:'c1-alloy-purpose',title:'Why alloy steel?',level:'foundation',kind:'concept',q:'Why are alloying elements intentionally added to steel?',choices:['To modify important engineering properties','Only to increase density','To eliminate all maintenance','To remove the need for fabrication'],answer:0,explanation:'The source discusses alloy additions because composition can change strength, ductility, toughness, corrosion behaviour and weldability.',source:'Subramanian Ch.1 Alloying Elements in Steel'},
{id:'c1-alloy-list',title:'Recognise alloying elements',level:'foundation',kind:'classification',q:'Which item is an alloying element discussed in structural-steel composition?',choices:['Manganese','Concrete','Timber','Gypsum board'],answer:0,explanation:'Manganese is among the alloying additions discussed in the chapter.',source:'Subramanian Ch.1 Alloying Elements in Steel'},
{id:'c1-alloy-combination',title:'Property trade-offs',level:'core',kind:'reasoning',q:'Why should alloying be viewed as a property trade-off rather than simply “more is better”?',choices:['Different additions affect several properties including weldability and toughness','All additions have exactly the same effect','Alloying changes only colour','Alloying never affects fabrication'],answer:0,explanation:'The chapter treats composition as a balance among mechanical, durability and fabrication properties.',source:'Subramanian Ch.1 Alloying Elements in Steel'},
{id:'c1-alloy-selection',title:'Material selection',level:'application',kind:'reasoning',q:'A project needs improved corrosion behaviour as well as adequate structural strength. What does the alloying discussion suggest?',choices:['Select a steel whose composition provides the required property combination','Use any steel because composition is irrelevant','Increase member length only','Ignore material grade'],answer:0,explanation:'Alloying is one route to tailoring steel for different performance requirements.',source:'Subramanian Ch.1 Alloying Elements in Steel'}
],
'1:Chemical Composition of Steel':[
{id:'c1-chem-weld',title:'Composition and weldability',level:'core',kind:'reasoning',q:'Why can chemical composition matter during welding?',choices:['It influences hardenability and cracking tendency near welds','It only changes member mass','It guarantees zero residual stress','It fixes support conditions'],answer:0,explanation:'The chapter links composition to weldability and cracking behaviour in and near welded regions.',source:'Subramanian Ch.1 Chemical Composition of Steel'},
{id:'c1-chem-grade',title:'Grade limits',level:'foundation',kind:'concept',q:'Why do steel grades include chemical-composition limits?',choices:['Composition influences performance and fabrication behaviour','Only to specify paint colour','Only to set member length','Because all grades have identical chemistry'],answer:0,explanation:'Chemical limits help control the material properties and fabrication response associated with a grade.',source:'Subramanian Ch.1 Chemical Composition of Steel'},
{id:'c1-chem-carbon-eq',title:'Carbon-equivalent idea',level:'core',kind:'concept',q:'What broad purpose does a carbon-equivalent concept serve?',choices:['Summarise composition effects relevant to weldability','Calculate beam deflection','Determine concrete cover','Measure corrosion coating thickness'],answer:0,explanation:'The source introduces carbon-equivalent thinking as a way to relate chemical composition to weldability.',source:'Subramanian Ch.1 Chemical Composition of Steel'},
{id:'c1-chem-not-just-lab',title:'Design relevance of chemistry',level:'application',kind:'reasoning',q:'Why is steel chemistry not merely a manufacturing laboratory issue?',choices:['It can affect fabrication and structural material behaviour','It never affects welding','It changes only branding','It is unrelated to engineering properties'],answer:0,explanation:'Composition affects properties and fabrication, so it has direct engineering implications.',source:'Subramanian Ch.1 Chemical Composition of Steel'}
],
'1:Types of Structural Steel':[
{id:'c1-types-variety',title:'Why multiple steel types?',level:'foundation',kind:'concept',q:'Why does the chapter distinguish several structural-steel types?',choices:['Applications need different combinations of strength, toughness, durability and fabrication properties','Only density changes','Every structure needs identical steel','Steel type matters only cosmetically'],answer:0,explanation:'The chapter presents multiple steel families because performance requirements vary between applications.',source:'Subramanian Ch.1 Types of Structural Steel'},
{id:'c1-types-weathering',title:'Weathering steel',level:'foundation',kind:'classification',q:'Which steel type is selected specifically for improved atmospheric corrosion performance?',choices:['Weathering steel','Ordinary timber','Plain concrete','Glass'],answer:0,explanation:'Weathering steel is one of the structural-steel types introduced for improved atmospheric corrosion behaviour.',source:'Subramanian Ch.1 Types of Structural Steel'},
{id:'c1-types-stainless',title:'Stainless category',level:'foundation',kind:'classification',q:'Which category is particularly associated with passive corrosion resistance?',choices:['Stainless steel','Cast iron only','Cold-formed shape as a geometry only','Timber'],answer:0,explanation:'Stainless steel is identified as a distinct structural material family with high corrosion resistance.',source:'Subramanian Ch.1 Types of Structural Steel'},
{id:'c1-types-selection',title:'Select by requirement',level:'application',kind:'reasoning',q:'What is the soundest basis for selecting among structural-steel types?',choices:['Match the required property combination to the application','Always choose the highest nominal strength only','Ignore fabrication needs','Choose by density alone'],answer:0,explanation:'The chapter emphasises different performance needs rather than one universally best steel type.',source:'Subramanian Ch.1 Types of Structural Steel'}
],
'1:Mechanical Properties of Steel':[
{id:'c1-mech-elastic',title:'Elastic response',level:'foundation',kind:'concept',q:'In which region does steel approximately return to its original shape when unloaded?',choices:['Elastic region','After complete fracture','Only during necking','Only after ultimate load'],answer:0,explanation:'The initial stress–strain response is approximately elastic before significant yielding occurs.',source:'Subramanian Chapter 1 PPT slides 10–15'},
{id:'c1-mech-ductility',title:'Ductility meaning',level:'core',kind:'concept',q:'Which property describes the ability of steel to undergo substantial deformation before fracture?',choices:['Ductility','Density','Thermal conductivity','Hardness only'],answer:0,explanation:'Ductility is a key mechanical property highlighted by the chapter stress–strain discussion.',source:'Subramanian Ch.1 Mechanical Properties of Steel'},
{id:'c1-mech-toughness',title:'Toughness meaning',level:'core',kind:'concept',q:'Which property is most closely associated with energy absorption before fracture?',choices:['Toughness','Unit weight','Poisson ratio only','Surface roughness'],answer:0,explanation:'The Chapter 1 slides devote several slides to toughness because it describes resistance to fracture with energy absorption.',source:'Subramanian Chapter 1 PPT slides 16–18'},
{id:'c1-mech-hardness',title:'Hardness',level:'foundation',kind:'concept',q:'Hardness is primarily a measure of resistance to:',choices:['Indentation or local surface deformation','Global frame sway','Elastic buckling length','Wind pressure'],answer:0,explanation:'Hardness is introduced as a mechanical property distinct from strength, ductility and toughness.',source:'Subramanian Chapter 1 PPT slide 22'}
],
'1:Residual Stresses':[
{id:'c1-res-zero-load',title:'Stress with zero external load',level:'foundation',kind:'concept',q:'A rolled or welded member is unloaded. Can internal stresses still remain?',choices:['Yes, residual stresses can remain','No, all stresses must vanish','Only in concrete','Only after fracture'],answer:0,explanation:'Residual stresses are self-equilibrating stresses that remain without externally applied load.',source:'Subramanian Chapter 1 PPT slides 23–26'},
{id:'c1-res-thermal',title:'Thermal origin',level:'core',kind:'reasoning',q:'Why can welding create residual stress?',choices:['Different regions heat and cool nonuniformly and cannot freely contract','Welding makes temperature perfectly uniform','Welding removes all plastic strain','Only gravity acts'],answer:0,explanation:'Nonuniform heating and cooling during welding can leave locked-in tensile and compressive residual regions.',source:'Subramanian Ch.1 Residual Stresses'},
{id:'c1-res-balance',title:'Internal balance',level:'core',kind:'reasoning',q:'Why do residual stresses not require an external resultant force?',choices:['Tensile and compressive regions can balance internally','Residual stress violates equilibrium','Residual stress has no physical meaning','The member becomes weightless'],answer:0,explanation:'Residual stress distributions are self-equilibrating over the section.',source:'Subramanian Ch.1 Residual Stresses'},
{id:'c1-res-design',title:'Design consequence',level:'application',kind:'reasoning',q:'Why can residual stresses influence compression-member behaviour later in design?',choices:['Some regions may yield earlier during compression','They always double Euler load','They eliminate buckling','They remove geometric imperfections'],answer:0,explanation:'Residual stresses contribute to early yielding and help explain why real compression members differ from ideal Euler columns.',source:'Subramanian Ch.1 Residual Stresses'}
],
'1:Stress Concentration':[
{id:'c1-sc-hole',title:'Hole effect',level:'foundation',kind:'concept',q:'What happens to a nominally uniform stress field near a hole?',choices:['Local stresses become concentrated','Stress remains perfectly uniform','All stress becomes zero','Only density changes'],answer:0,explanation:'Holes and other abrupt geometric changes disturb the stress flow and create local peaks.',source:'Subramanian Ch.1 Stress Concentration'},
{id:'c1-sc-notch',title:'Notch effect',level:'foundation',kind:'concept',q:'Which detail is most likely to cause stress concentration?',choices:['A sharp notch','A perfectly smooth prismatic region','A uniform long plate away from discontinuities','A constant-width bar with no holes'],answer:0,explanation:'Abrupt discontinuities such as notches are classic stress concentrators.',source:'Subramanian Ch.1 Stress Concentration'},
{id:'c1-sc-fatigue',title:'Why fatigue cares',level:'core',kind:'reasoning',q:'Why are stress concentrations especially important under repeated loading?',choices:['Local peak stresses can promote fatigue crack initiation','They eliminate cyclic stress','They always improve fatigue life','They make material perfectly ductile'],answer:0,explanation:'The chapter connects local peak stresses with fatigue- and fracture-sensitive behaviour.',source:'Subramanian Ch.1 Stress Concentration'},
{id:'c1-sc-detail',title:'Detailing response',level:'application',kind:'reasoning',q:'What design instinct follows from stress-concentration behaviour?',choices:['Avoid unnecessarily abrupt changes in geometry','Add sharp re-entrant corners','Concentrate holes at one point','Ignore local geometry'],answer:0,explanation:'Smoother load paths and geometry reduce local stress peaks.',source:'Subramanian Ch.1 Stress Concentration'}
],
'1:Cold Work and Strain Hardening':[
{id:'c1-cold-definition',title:'Cold work',level:'foundation',kind:'concept',q:'Cold working means significant plastic deformation carried out:',choices:['At relatively low temperature compared with hot working','Only above steel melting temperature','Only during a building fire','Only after corrosion'],answer:0,explanation:'The chapter discusses cold working as deformation at low temperature that changes subsequent material response.',source:'Subramanian Chapter 1 PPT slide 27'},
{id:'c1-cold-yield',title:'Strength after cold work',level:'core',kind:'concept',q:'What commonly happens to yield strength after significant cold working?',choices:['It can increase due to strain hardening','It must become zero','It always halves','It becomes unrelated to strain'],answer:0,explanation:'Cold work can raise yield strength through strain hardening.',source:'Subramanian Ch.1 Cold Work and Strain Hardening'},
{id:'c1-cold-ductility',title:'Ductility trade-off',level:'core',kind:'reasoning',q:'What trade-off may accompany strain hardening?',choices:['Reduced ductility','Infinite ductility','Zero residual effects always','No change in material behaviour'],answer:0,explanation:'The chapter notes that increased strength from cold work can be accompanied by reduced ductility.',source:'Subramanian Ch.1 Cold Work and Strain Hardening'},
{id:'c1-cold-history',title:'Loading history matters',level:'application',kind:'reasoning',q:'Why can previous plastic deformation matter in later structural behaviour?',choices:['It changes the subsequent stress–strain response','Steel forgets all prior deformation','It changes only paint colour','It removes yield behaviour'],answer:0,explanation:'Cold work and strain hardening demonstrate that material response depends on prior plastic deformation.',source:'Subramanian Ch.1 Cold Work and Strain Hardening'}
],
'1:Structural Steel Products':[
{id:'c1-prod-family',title:'Recognise a steel product',level:'foundation',kind:'classification',q:'Which is a common structural-steel product?',choices:['Rolled I-section','Clay brick','Timber plank only','Glass panel only'],answer:0,explanation:'The chapter surveys rolled I/H sections, channels, angles, tees, plates, bars, hollow sections and built-up products.',source:'Subramanian Chapter 1 PPT slides 28–33'},
{id:'c1-prod-builtup',title:'Built-up products',level:'foundation',kind:'concept',q:'Why might a welded built-up section be used?',choices:['To obtain a section geometry or capacity not conveniently available as a standard rolled shape','To eliminate all fabrication','To make steel non-metallic','To avoid any connection'],answer:0,explanation:'The source includes welded and hybrid sections as structural products that can be tailored beyond standard rolled shapes.',source:'Subramanian Chapter 1 PPT slides 31–32'},
{id:'c1-prod-cellular',title:'Cellular beam recognition',level:'foundation',kind:'classification',q:'Which product shown in the Chapter 1 slides contains repeated web openings?',choices:['Cellular beam','Solid round bar','Flat plate only','Concrete slab'],answer:0,explanation:'The Chapter 1 slide deck illustrates cellular beams with repeated web openings.',source:'Subramanian Chapter 1 PPT slide 33'},
{id:'c1-prod-selection',title:'Product selection',level:'application',kind:'reasoning',q:'Which factors should influence selection of a structural-steel product?',choices:['Section properties, availability, fabrication and structural role','Only colour','Only density','Only supplier logo'],answer:0,explanation:'The chapter treats product selection as both a structural and fabrication decision.',source:'Subramanian Ch.1 Structural Steel Products'}
],
'1:Cold-formed Steel Sections':[
{id:'c1-cfs-process',title:'How cold-formed sections are made',level:'foundation',kind:'concept',q:'Cold-formed steel sections are typically made by:',choices:['Forming relatively thin sheet at room temperature','Casting massive concrete','Hot forging complete buildings','Melting finished beams on site'],answer:0,explanation:'The chapter describes cold-formed members as thin sheet formed at relatively low temperature.',source:'Subramanian Chapter 1 PPT slide 34'},
{id:'c1-cfs-buckle',title:'Thin-wall consequence',level:'core',kind:'reasoning',q:'Why is local buckling especially important for cold-formed sections?',choices:['Their plate elements are often thin and slender','They have no compressive stress','They are always solid','They cannot deform'],answer:0,explanation:'Thin walls make plate slenderness and local buckling central design issues.',source:'Subramanian Ch.1 Cold-formed Steel Sections'},
{id:'c1-cfs-connection',title:'Connection sensitivity',level:'core',kind:'reasoning',q:'Why can connection detailing be particularly important in thin cold-formed members?',choices:['Thin material changes local bearing and deformation behaviour','Connections carry no load','Thin sheet has infinite stiffness','All cold-formed members are welded continuously'],answer:0,explanation:'The chapter flags connection and detailing behaviour as important alongside local buckling.',source:'Subramanian Ch.1 Cold-formed Steel Sections'},
{id:'c1-cfs-not-roll',title:'Cold-formed versus hot-rolled',level:'foundation',kind:'classification',q:'Which statement best distinguishes cold-formed from conventional hot-rolled sections?',choices:['Cold-formed sections commonly start as thin sheet shaped at room temperature','They are always much thicker than hot-rolled sections','They contain no steel','They cannot be structural'],answer:0,explanation:'The manufacturing route and thin-walled geometry are defining features of cold-formed sections.',source:'Subramanian Chapter 1 PPT slide 34'}
],
'1:High-performance Steel':[
{id:'c1-hps-purpose',title:'High-performance concept',level:'foundation',kind:'concept',q:'High-performance steel is intended to improve:',choices:['A useful combination of structural and durability properties','Density only','Paint colour only','Member length only'],answer:0,explanation:'The chapter presents HPS as improving several performance attributes rather than strength alone.',source:'Subramanian Chapter 1 PPT slide 35'},
{id:'c1-hps-strengthonly',title:'Not strength alone',level:'core',kind:'reasoning',q:'Why is “highest strength” not a complete definition of high-performance steel?',choices:['Fabrication, toughness, corrosion performance and other properties also matter','Strength never matters','Only cost matters','All steels have the same toughness'],answer:0,explanation:'The source describes high performance as a balanced property package.',source:'Subramanian Ch.1 High-performance Steel'},
{id:'c1-hps-demand',title:'Demanding applications',level:'application',kind:'reasoning',q:'Where is a balanced high-performance steel most attractive?',choices:['Structures requiring several demanding performance properties simultaneously','Only decorative nonstructural labels','Any case where material properties are irrelevant','Only timber structures'],answer:0,explanation:'HPS is introduced for demanding structural applications where multiple properties matter.',source:'Subramanian Ch.1 High-performance Steel'},
{id:'c1-hps-fabrication',title:'Fabrication performance',level:'core',kind:'concept',q:'Which property category may be part of “high performance” in addition to mechanical strength?',choices:['Fabrication/weldability behaviour','Only density','Only magnetic colour','Only section name'],answer:0,explanation:'The source includes fabrication-related performance among the reasons for developing high-performance steels.',source:'Subramanian Ch.1 High-performance Steel'}
],
'1:Stainless Steel':[
{id:'c1-ss-passive',title:'Passive protection',level:'foundation',kind:'concept',q:'What gives stainless steel its characteristic corrosion resistance?',choices:['A chromium-rich passive surface behaviour','A timber coating','Zero iron content','No exposure to oxygen'],answer:0,explanation:'The chapter attributes stainless-steel corrosion resistance mainly to chromium-rich passive behaviour.',source:'Subramanian Chapter 1 PPT slides 36–38'},
{id:'c1-ss-architecture',title:'Architectural use',level:'foundation',kind:'concept',q:'Why is stainless steel attractive for exposed architectural structures?',choices:['Durability can combine with visual finish','It has zero cost','It never needs structural design','It has no thermal expansion'],answer:0,explanation:'The chapter links stainless steel with durability and architectural applications.',source:'Subramanian Ch.1 Stainless Steel'},
{id:'c1-ss-response',title:'Different material response',level:'core',kind:'reasoning',q:'Why should stainless steel not automatically be designed exactly like ordinary carbon steel?',choices:['Its stress–strain response and design behaviour differ','It is not a metal','It has no strength','It has identical behaviour in every respect'],answer:0,explanation:'The chapter notes important stress–strain and design differences from carbon steel.',source:'Subramanian Ch.1 Stainless Steel'},
{id:'c1-ss-example',title:'Chapter example',level:'foundation',kind:'recall',q:'What structural example is shown in the Chapter 1 slides for stainless steel?',choices:['A stainless-steel double-layer grid roof in Haryana','A timber suspension bridge','A concrete dam','A masonry arch only'],answer:0,explanation:'The slide deck shows India’s first stainless-steel double-layer grid roof at Hissar, Haryana.',source:'Subramanian Chapter 1 PPT slide 38'}
],
'1:Advantages of Steel as a Structural Material':[
{id:'c1-adv-strengthweight',title:'Strength-to-weight',level:'foundation',kind:'concept',q:'Which is a major structural advantage of steel?',choices:['High strength-to-weight ratio','It cannot corrode','It cannot buckle','It has zero thermal expansion'],answer:0,explanation:'The chapter highlights high strength relative to structural weight among steel’s major advantages.',source:'Subramanian Ch.1 Advantages of Steel'},
{id:'c1-adv-prefab',title:'Prefabrication',level:'foundation',kind:'reasoning',q:'How can prefabrication benefit steel construction?',choices:['Components can be produced accurately off-site and erected rapidly','It prevents all design errors','It removes every connection','It makes foundations unnecessary'],answer:0,explanation:'Steel is well suited to prefabrication and rapid site erection.',source:'Subramanian Ch.1 Advantages of Steel'},
{id:'c1-adv-ductile',title:'Ductility advantage',level:'core',kind:'concept',q:'Why is ductility considered an advantage in structural steel?',choices:['It permits significant deformation before fracture and supports redistribution','It makes steel infinitely strong','It prevents all local buckling','It means no yielding occurs'],answer:0,explanation:'Ductile behaviour gives warning and allows inelastic deformation rather than sudden brittle failure.',source:'Subramanian Ch.1 Advantages of Steel'},
{id:'c1-adv-limit',title:'Advantages do not remove limits',level:'application',kind:'reasoning',q:'Which statement is consistent with the chapter’s balanced view of steel?',choices:['Steel has major advantages but still requires checks for corrosion, fire and buckling','Steel has no disadvantages','Steel never needs maintenance','Steel is lighter per cubic metre than concrete'],answer:0,explanation:'The chapter lists benefits while also acknowledging corrosion, fire protection and stability issues.',source:'Subramanian Ch.1 Advantages of Steel'}
],
'1:Types of Steel Structures':[
{id:'c1-struct-variety',title:'Structural forms',level:'foundation',kind:'classification',q:'Which is a steel structural form illustrated by the chapter?',choices:['Truss','Only soil retaining fill','Only masonry wall','Only timber deck'],answer:0,explanation:'The Chapter 1 slides illustrate several types of steel structures including trusses, buildings, bridges and towers.',source:'Subramanian Chapter 1 PPT slides 39–43'},
{id:'c1-struct-beam',title:'Member action: beam',level:'foundation',kind:'classification',q:'A beam is primarily associated with:',choices:['Bending','Pure corrosion','Chemical composition','Heat treatment'],answer:0,explanation:'The chapter also classifies structural members by their principal action.',source:'Subramanian Ch.1 Types of Steel Structures'},
{id:'c1-struct-column',title:'Member action: column',level:'foundation',kind:'classification',q:'A column is primarily associated with:',choices:['Compression','Pure tension only','Painting','Welding heat input only'],answer:0,explanation:'Compression members such as columns are one of the basic structural-member categories.',source:'Subramanian Ch.1 Types of Steel Structures'},
{id:'c1-struct-combined',title:'Combined action',level:'core',kind:'reasoning',q:'Can a steel member be subjected to more than one basic structural action?',choices:['Yes, combined axial force and bending can occur','No, each member can carry only one action','Only concrete has combined action','Combined action is impossible in frames'],answer:0,explanation:'The chapter recognises members carrying tension, compression, bending and combined actions.',source:'Subramanian Ch.1 Types of Steel Structures'}
],
'1:Aluminium Alloys':[
{id:'c1-al-light',title:'Relative weight',level:'foundation',kind:'concept',q:'What broad material advantage does aluminium have compared with steel?',choices:['Lower density','Higher elastic modulus','No thermal expansion','Infinite yield strength'],answer:0,explanation:'The chapter introduces aluminium as a lighter structural metal.',source:'Subramanian Ch.1 Aluminium Alloys'},
{id:'c1-al-modulus',title:'Elastic modulus difference',level:'core',kind:'concept',q:'Compared with steel, aluminium has:',choices:['A much lower modulus of elasticity','A much higher modulus in every alloy','Exactly the same modulus','No elastic behaviour'],answer:0,explanation:'The lower elastic modulus is an important structural difference because it affects stiffness and buckling.',source:'Subramanian Ch.1 Aluminium Alloys'},
{id:'c1-al-corrosion',title:'Durability property',level:'foundation',kind:'concept',q:'Which useful property of aluminium is highlighted?',choices:['Good corrosion resistance','No oxidation can ever occur','Zero temperature sensitivity','No connection issues'],answer:0,explanation:'The chapter notes good corrosion resistance among aluminium’s useful structural properties.',source:'Subramanian Ch.1 Aluminium Alloys'},
{id:'c1-al-design',title:'Do not copy steel design blindly',level:'application',kind:'reasoning',q:'Why should aluminium members not simply be treated as steel members with a lower weight?',choices:['Their stiffness, strength, buckling and connection behaviour differ','Only the colour differs','They have identical material response','Aluminium has no structural use'],answer:0,explanation:'The source explicitly notes different modulus, strength, buckling and connection behaviour.',source:'Subramanian Ch.1 Aluminium Alloys'}
],
'1:Fabrication and Erection':[
{id:'c1-fab-ops',title:'Fabrication operations',level:'foundation',kind:'classification',q:'Which activity is part of steel fabrication?',choices:['Cutting and drilling','Concrete curing only','Soil consolidation only','Wind-tunnel testing only'],answer:0,explanation:'The chapter lists cutting, drilling, welding, bolting, straightening, painting and inspection among fabrication activities.',source:'Subramanian Ch.1 Fabrication and Erection'},
{id:'c1-fab-erect',title:'Erection stage',level:'foundation',kind:'concept',q:'What happens after shop fabrication and transport?',choices:['Members are assembled and erected on site','Steelmaking starts again','The ore is remelted on site','All connections are removed'],answer:0,explanation:'Fabricated components are transported and erected as the structural frame.',source:'Subramanian Ch.1 Fabrication and Erection'},
{id:'c1-fab-tolerance',title:'Why tolerances matter',level:'core',kind:'reasoning',q:'Why are dimensional accuracy and tolerances important in fabricated steelwork?',choices:['Errors can accumulate and prevent proper site assembly','Steel stretches to any required size automatically','Connections never require alignment','Tolerance affects only paint colour'],answer:0,explanation:'The chapter stresses accuracy because fabrication errors propagate into erection and connection fit-up.',source:'Subramanian Ch.1 Fabrication and Erection'},
{id:'c1-fab-inspect',title:'Inspection role',level:'application',kind:'reasoning',q:'Why is inspection included in fabrication?',choices:['To verify workmanship and dimensional/connection quality before and during assembly','To increase density','To replace structural calculations','To eliminate transport'],answer:0,explanation:'Inspection is part of achieving the specified fabricated quality and successful erection.',source:'Subramanian Ch.1 Fabrication and Erection'}
],
'1:Aesthetics of Steel Structures':[
{id:'c1-aesth-proportion',title:'Visual proportion',level:'foundation',kind:'concept',q:'Which factor can improve the visual quality of an exposed steel structure?',choices:['Good proportion of members','Random member sizing','Ignoring connection layout','Adding weight without structural reason'],answer:0,explanation:'The chapter argues that proportion and clear structural expression contribute to aesthetics.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'},
{id:'c1-aesth-connection',title:'Connections are visible design',level:'core',kind:'reasoning',q:'Why can connection detailing affect aesthetics?',choices:['Connections are part of the visible structural language in exposed steelwork','Connections are always invisible','Connections affect only density','Connection geometry never changes appearance'],answer:0,explanation:'Exposed connections can either reinforce or disrupt the visual logic of the structure.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'},
{id:'c1-aesth-logic',title:'Structure and architecture',level:'core',kind:'concept',q:'What relationship does the chapter encourage between structural efficiency and appearance?',choices:['They can reinforce each other','They must always conflict','Appearance requires inefficient structure','Structural logic should always be hidden'],answer:0,explanation:'The source presents steel as a material where structural logic and architecture can work together.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'},
{id:'c1-aesth-example',title:'Expressive steel form',level:'application',kind:'reasoning',q:'For an exposed frame, which design choice is most consistent with the chapter’s aesthetic approach?',choices:['Coordinate member shape, proportion and connection detailing with the architecture','Choose members only by random availability','Hide all load paths with arbitrary geometry','Ignore the visual effect of connections'],answer:0,explanation:'Aesthetic quality is tied to proportion, member shape, connections and architectural integration.',source:'Subramanian Ch.1 Aesthetics of Steel Structures'}
],
'1:Composite Construction':[
{id:'c1-comp-idea',title:'Composite action',level:'foundation',kind:'concept',q:'What is the central idea of composite construction?',choices:['Different materials are arranged to act together structurally','Only steel is allowed to resist load','Materials must remain completely independent','Concrete is used only as decoration'],answer:0,explanation:'Composite construction combines materials so their useful properties contribute together to structural action.',source:'Subramanian Chapter 1 PPT slide 45'},
{id:'c1-comp-steelconcrete',title:'Common pairing',level:'foundation',kind:'classification',q:'Which is a common composite structural combination?',choices:['Steel beam with concrete slab','Timber paint with soil','Glass pane with air only','Brick with no connection'],answer:0,explanation:'Steel and concrete are commonly combined so that the system behaves compositely.',source:'Subramanian Ch.1 Composite Construction'},
{id:'c1-comp-transfer',title:'Need for force transfer',level:'core',kind:'reasoning',q:'What is necessary for two materials to act compositely rather than simply sit next to each other?',choices:['Effective transfer of forces between them','No connection at all','Identical density','Identical thermal colour'],answer:0,explanation:'Composite action requires interaction/force transfer between the participating components.',source:'Subramanian Ch.1 Composite Construction'},
{id:'c1-comp-why',title:'Why combine materials?',level:'application',kind:'reasoning',q:'Why use composite construction?',choices:['To exploit complementary properties of different materials','To ensure only one material carries all actions','To avoid any connections','To make structural analysis unnecessary'],answer:0,explanation:'Composite systems are used because the participating materials can complement one another structurally.',source:'Subramanian Ch.1 Composite Construction'}
],
'1:Summary':[
{id:'c1-summary-thread',title:'Chapter 1 thread',level:'foundation',kind:'recall',q:'Which sequence best captures Chapter 1?',choices:['Manufacture and metallurgy → properties → products → structural applications','Painting → demolition → soil mechanics','Only bolt design','Only beam buckling'],answer:0,explanation:'Chapter 1 moves from how steel is made and behaves to the products and structural systems that use it.',source:'Subramanian Ch.1 Summary'},
{id:'c1-summary-property',title:'Property linkage',level:'core',kind:'reasoning',q:'What is the strongest unifying idea of the chapter?',choices:['Material production and internal structure influence engineering behaviour and structural use','Section shape is unrelated to material','Fabrication is unrelated to steel properties','All steel products behave identically'],answer:0,explanation:'The chapter links production, metallurgy, properties, products, fabrication and structural application.',source:'Subramanian Ch.1 Summary'},
{id:'c1-summary-realsteel',title:'Real steel is not ideal steel',level:'core',kind:'reasoning',q:'Which Chapter 1 topics remind the designer that real steel members are not perfectly ideal materials?',choices:['Residual stress, cold work and stress concentration','Only density','Only member colour','Only steel plant location'],answer:0,explanation:'These topics show how manufacturing, fabrication and geometry influence actual behaviour.',source:'Subramanian Ch.1 Summary'},
{id:'c1-summary-selection',title:'Material selection mindset',level:'application',kind:'reasoning',q:'Which mindset best reflects Chapter 1 material selection?',choices:['Choose steel type/product based on the required combination of structural, fabrication and durability properties','Always choose the strongest grade regardless of context','Ignore product availability','Ignore fabrication and erection'],answer:0,explanation:'The chapter repeatedly connects material choice with structural role, fabrication and service requirements.',source:'Subramanian Ch.1 Summary'}
],
'1:Review Questions':[
{id:'c1-review-manufacture',title:'Review: manufacturing',level:'review',kind:'mcq',q:'Which operation belongs after steelmaking in the route to common structural products?',choices:['Casting and rolling','Concrete curing','Soil compaction','Timber seasoning'],answer:0,explanation:'Casting and rolling turn steel into usable structural forms.',source:'Subramanian Ch.1 Review Questions and Chapter 1 manufacturing material'},
{id:'c1-review-yield',title:'Review: material behaviour',level:'review',kind:'mcq',q:'Which point on a ductile steel stress–strain response indicates the onset of substantial plastic deformation?',choices:['Yield','Density','Thermal conductivity','Specific gravity'],answer:0,explanation:'Yield marks the transition into significant plastic deformation.',source:'Subramanian Ch.1 Review Questions and mechanical-properties material'},
{id:'c1-review-residual',title:'Review: fabrication effect',level:'review',kind:'mcq',q:'Which statement about residual stress is correct?',choices:['It can exist in a member with no external load','It always has a nonzero resultant force','It occurs only in concrete','It is removed by every welding operation'],answer:0,explanation:'Residual stresses are self-equilibrating internal stresses left by manufacturing or fabrication effects.',source:'Subramanian Ch.1 Review Questions and residual-stress material'},
{id:'c1-review-products',title:'Review: products and systems',level:'review',kind:'mcq',q:'Which pairing is consistent with Chapter 1?',choices:['Cold-formed sections → thin-walled local-buckling sensitivity','Stainless steel → no corrosion mechanism at all','Aluminium → higher elastic modulus than steel','Composite construction → no force transfer between materials'],answer:0,explanation:'Cold-formed members are thin-walled and therefore particularly sensitive to local buckling.',source:'Subramanian Ch.1 Review Questions and structural-products material'}
]
};
window.REVISION_BANK=window.REVISION_BANK||{};
for(const [k,v] of Object.entries(add)) window.REVISION_BANK[k]=[...(window.REVISION_BANK[k]||[]),...v];
})();
