(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, Ch.10 source-grounded lesson';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('10:Introduction',[
{id:'ch10-intro-1',title:'Primary beam action',level:'foundation',kind:'concept',q:'A member carrying loads mainly transverse to its longitudinal axis is primarily acting as what?',choices:['A beam','A tension tie','A column under concentric load','A hanger'],answer:0,explanation:'Transverse loading produces bending moment and shear, which are the characteristic actions in beams.',source:S},
{id:'ch10-intro-2',title:'Beyond flexural strength',level:'core',kind:'reasoning',q:'Why is checking bending strength alone insufficient for a steel beam?',choices:['Stability, web behaviour and serviceability can also govern','Steel beams cannot carry shear','Bending never occurs in beams','Deflection is an ultimate strength check only'],answer:0,explanation:'A usable beam must satisfy strength, stability, local web and serviceability requirements.',source:S},
{id:'ch10-intro-3',title:'Eccentric transverse loading',level:'core',kind:'application',q:'If a transverse load is applied away from the shear centre, which additional action may become important?',choices:['Torsion','Pure axial tension only','Hydrostatic pressure','No additional action'],answer:0,explanation:'Eccentricity relative to the shear centre can introduce a twisting moment in addition to bending and shear.',source:S},
{id:'ch10-intro-4',title:'Beam design actions',level:'foundation',kind:'classification',q:'Which pair of internal actions normally governs the basic design of a transversely loaded beam?',choices:['Bending moment and shear force','Axial tension and soil pressure','Temperature and corrosion only','Bearing and torsion only'],answer:0,explanation:'Transverse loading develops bending moment and shear force along the beam.',source:S},
{id:'ch10-intro-5',title:'Serviceability matters',level:'application',kind:'reasoning',q:'A steel beam has adequate ultimate bending resistance but deflects excessively. Is it acceptable?',choices:['No, serviceability can govern even when strength is adequate','Yes, strength is the only beam criterion','Yes, if the web is thin','No, because all beams must remain perfectly straight'],answer:0,explanation:'Strength adequacy does not waive deflection and other serviceability limits.',source:S},
{id:'ch10-intro-6',title:'Design mindset',level:'retrieval',kind:'concept',q:'Which statement best captures the Chapter 10 design approach?',choices:['Check the complete load path and all relevant limit states','Choose a section from depth alone','Check only the largest bending moment','Ignore restraint conditions'],answer:0,explanation:'Beam design is an integrated strength, stability and serviceability problem.',source:S}
]);
add('10:Types',[
{id:'ch10-types-1',title:'Roof secondary beam',level:'foundation',kind:'classification',q:'Which beam type directly supports roof sheeting between rafters or trusses?',choices:['Purlin','Lintel','Column cap','Tie rod'],answer:0,explanation:'Purlins are secondary roof beams supporting sheeting and transferring load to primary roof members.',source:S},
{id:'ch10-types-2',title:'Opening support beam',level:'foundation',kind:'classification',q:'Which beam is placed over a door or window opening to support the wall above?',choices:['Lintel','Purlin','Stringer only','Column base'],answer:0,explanation:'A lintel bridges a wall opening and carries the material above it.',source:S},
{id:'ch10-types-3',title:'Support description',level:'core',kind:'classification',q:'Which description classifies a beam by its support condition rather than its building role?',choices:['Cantilever beam','Purlin','Lintel','Spandrel beam'],answer:0,explanation:'Cantilever, simply supported and continuous describe structural support/continuity conditions.',source:S},
{id:'ch10-types-4',title:'Role and arrangement',level:'core',kind:'reasoning',q:'Why does beam terminology include names such as girder, joist, lintel and purlin?',choices:['The names identify structural role and load-transfer context','Each name denotes a different steel chemistry','They specify only paint systems','They mean the same support condition'],answer:0,explanation:'Beam names often communicate where the member sits in the structural hierarchy and what it supports.',source:S},
{id:'ch10-types-5',title:'Continuity',level:'application',kind:'concept',q:'A beam extending over more than one support with continuity through the supports is best described as:',choices:['Continuous','Cantilever only','Pinned tension member','Isolated lintel by definition'],answer:0,explanation:'Continuity across supports distinguishes a continuous beam from separate simply supported spans.',source:S},
{id:'ch10-types-6',title:'Function first',level:'retrieval',kind:'concept',q:'What should the designer infer first from a label such as “purlin” or “lintel”?',choices:['Its structural function and typical load path','Its exact yield stress','Its exact span','Its fabrication tolerance'],answer:0,explanation:'The role name indicates how the beam participates in the structure, not a fixed material grade or size.',source:S}
]);
add('10:Section Classification',[
{id:'ch10-class-1',title:'Why classify beams',level:'foundation',kind:'reasoning',q:'Why are beam cross-sections classified by plate-element width-to-thickness ratios?',choices:['Local buckling controls how much bending capacity and rotation can develop','Classification determines steel density','It replaces shear design','It fixes the beam span'],answer:0,explanation:'Compression-element slenderness governs whether local buckling occurs before yield or plastic capacity develops.',source:S},
{id:'ch10-class-2',title:'Plastic class',level:'core',kind:'concept',q:'Which section class can develop plastic moment and enough rotation for plastic analysis?',choices:['Plastic','Semi-compact','Slender','Any section'],answer:0,explanation:'Plastic sections have sufficiently stocky compression elements for plastic moment and rotation capacity.',source:S},
{id:'ch10-class-3',title:'Compact class',level:'core',kind:'concept',q:'How does a compact section differ from a plastic section?',choices:['It can reach plastic moment but has less rotation capacity','It cannot reach yield anywhere','It must use effective-width properties','It is always slender'],answer:0,explanation:'Compact sections can develop plastic moment but do not have the same rotation capacity required for plastic analysis.',source:S},
{id:'ch10-class-4',title:'Semi-compact limit',level:'core',kind:'classification',q:'A semi-compact section is generally limited by which bending condition?',choices:['First yield at the extreme fibre using elastic section properties','Full plastic rotation','No yielding at all','Torsional yielding only'],answer:0,explanation:'Semi-compact sections are designed on an elastic first-yield basis rather than full plastic moment.',source:S},
{id:'ch10-class-5',title:'Slender section treatment',level:'application',kind:'reasoning',q:'What is the key consequence of a slender compression element in beam design?',choices:['Effective/reduced section properties may be required because local buckling occurs early','Plastic capacity automatically increases','LTB becomes impossible','Shear force becomes zero'],answer:0,explanation:'Slender elements can locally buckle before full section yield and therefore need reduced effective properties.',source:S},
{id:'ch10-class-6',title:'Classification hierarchy',level:'retrieval',kind:'classification',q:'Which sequence goes from greatest plastic rotation capability toward earliest local-buckling limitation?',choices:['Plastic → compact → semi-compact → slender','Slender → plastic → compact → semi-compact','Compact → slender → plastic → semi-compact','All classes have identical behaviour'],answer:0,explanation:'The classes progressively reduce the usable stress distribution and rotation capacity as plate slenderness increases.',source:S}
]);
add('10:Lateral Stability of Beams',[
{id:'ch10-latstab-1',title:'Compression flange instability',level:'foundation',kind:'concept',q:'Which part of a major-axis bent I-beam is especially prone to lateral instability when unrestrained?',choices:['The compression flange','The tension flange only','The neutral axis only','The support bolt only'],answer:0,explanation:'The compression flange tends to move laterally and initiates coupled twisting of the section.',source:S},
{id:'ch10-latstab-2',title:'Coupled response',level:'core',kind:'concept',q:'Lateral instability of an unrestrained beam generally combines which motions?',choices:['Lateral displacement and twist','Vertical deflection and axial elongation only','Web yielding and no movement','Pure torsion without lateral displacement'],answer:0,explanation:'The instability is lateral-torsional rather than a purely lateral or purely torsional mode.',source:S},
{id:'ch10-latstab-3',title:'Effect of restraint',level:'core',kind:'reasoning',q:'What is the most direct way to improve lateral stability of the compression flange?',choices:['Provide effective lateral restraint at suitable intervals','Increase unbraced length','Remove torsional restraint','Apply the load farther from the shear centre'],answer:0,explanation:'Effective restraint reduces the length over which the compression flange can buckle laterally.',source:S},
{id:'ch10-latstab-4',title:'Cross-section influence',level:'application',kind:'reasoning',q:'Why can two beams with similar major-axis bending strength have different lateral stability?',choices:['Their minor-axis, torsional and warping stiffness can differ','Steel density alone fixes LTB','Lateral stability depends only on span load','Section shape has no effect'],answer:0,explanation:'Lateral-torsional behaviour depends on several stiffness components beyond major-axis section modulus.',source:S},
{id:'ch10-latstab-5',title:'Load position',level:'application',kind:'concept',q:'Why can the height at which load is applied affect lateral stability?',choices:['Load position relative to the shear centre can have a stabilizing or destabilizing effect','Load height changes steel yield stress','Load height eliminates bending moment','It changes only self-weight'],answer:0,explanation:'The torsional effect of load application relative to the shear centre influences buckling response.',source:S},
{id:'ch10-latstab-6',title:'Stability checklist',level:'retrieval',kind:'concept',q:'Which group belongs in a lateral-stability check?',choices:['Unbraced length, restraint, section stiffness and load position','Paint colour, density and temperature only','Bolt grade only','Foundation soil only'],answer:0,explanation:'These are central variables controlling lateral-torsional stability.',source:S}
]);
add('10:Lateral Torsional Buckling of Symmetric Sections',[
{id:'ch10-ltb-1',title:'Ideal LTB assumptions',level:'foundation',kind:'concept',q:'Ideal elastic lateral-torsional buckling theory assumes the beam is initially:',choices:['Straight and elastic without residual-stress imperfections','Fully yielded','Locally buckled','Cracked through the web'],answer:0,explanation:'Ideal theory excludes initial imperfections and inelastic effects that are present in real beams.',source:S},
{id:'ch10-ltb-2',title:'Critical moment meaning',level:'core',kind:'concept',q:'What does the elastic critical moment in LTB represent?',choices:['The ideal moment at which lateral-torsional instability occurs','The plastic moment of every beam','The maximum shear capacity','The serviceability deflection limit'],answer:0,explanation:'It is the elastic instability threshold for the idealized member and loading/restraint conditions.',source:S},
{id:'ch10-ltb-3',title:'Stiffness ingredients',level:'core',kind:'classification',q:'Which stiffness properties influence elastic LTB of a symmetric I-beam?',choices:['Minor-axis flexural, torsional and warping stiffness','Only axial area','Only major-axis section modulus','Only steel density'],answer:0,explanation:'LTB couples lateral flexure with torsion and warping, so these stiffnesses matter directly.',source:S},
{id:'ch10-ltb-4',title:'Unbraced length effect',level:'application',kind:'reasoning',q:'If all else is unchanged, what generally happens to LTB resistance as unbraced length increases?',choices:['It decreases','It increases without limit','It is unchanged','It becomes a shear-only problem'],answer:0,explanation:'A longer unrestrained length is more susceptible to instability.',source:S},
{id:'ch10-ltb-5',title:'Moment distribution',level:'application',kind:'concept',q:'Why does moment gradient matter in LTB?',choices:['Different bending-moment distributions change how much of the unbraced length is highly stressed','Moment gradient changes steel density','It eliminates torsion','It affects only support reactions'],answer:0,explanation:'The extent and distribution of compression along the beam influence buckling susceptibility.',source:S},
{id:'ch10-ltb-6',title:'LTB versus local buckling',level:'retrieval',kind:'classification',q:'Which statement correctly distinguishes LTB from local buckling?',choices:['LTB is overall lateral/twist instability; local buckling is plate-element instability','They are identical','LTB occurs only in webs','Local buckling is a foundation failure'],answer:0,explanation:'LTB is a member stability mode, while local buckling concerns individual plate elements of the cross-section.',source:S}
]);
add('10:Factors Affecting Lateral Stability',[
{id:'ch10-factors-1',title:'Shorter unbraced length',level:'foundation',kind:'reasoning',q:'Which change is generally favourable to lateral stability?',choices:['Reducing the distance between effective lateral restraints','Increasing the unbraced length','Removing bracing','Weakening torsional restraint'],answer:0,explanation:'Shorter unbraced lengths reduce the opportunity for lateral-torsional buckling.',source:S},
{id:'ch10-factors-2',title:'End restraint',level:'core',kind:'concept',q:'Why can stronger end restraint improve lateral stability?',choices:['It limits lateral/torsional deformation at the boundaries','It lowers steel modulus','It increases load eccentricity','It makes the beam slenderer'],answer:0,explanation:'Boundary restraint changes the buckling mode and raises the instability resistance when effective.',source:S},
{id:'ch10-factors-3',title:'Compression-flange loading',level:'application',kind:'reasoning',q:'Compared with loading near the shear centre, why can loading through the compression flange be less favourable?',choices:['Its position can produce a destabilizing torsional effect','It removes compression','It increases web thickness','It always eliminates twist'],answer:0,explanation:'Load height relative to the shear centre influences the torsional component of buckling.',source:S},
{id:'ch10-factors-4',title:'Intermediate bracing',level:'application',kind:'concept',q:'What is the structural purpose of effective intermediate lateral bracing on a beam?',choices:['Subdivide the unbraced length and restrain lateral movement','Increase dead load only','Create local buckling','Reduce the section modulus'],answer:0,explanation:'Intermediate restraints can substantially improve stability by shortening the effective unbraced segment.',source:S},
{id:'ch10-factors-5',title:'Moment gradient benefit',level:'core',kind:'reasoning',q:'Why can a nonuniform moment diagram behave differently from uniform moment for LTB?',choices:['The compression demand is not equally severe over the whole unbraced length','Steel properties change along the span automatically','The beam carries no shear','Restraint becomes irrelevant'],answer:0,explanation:'Buckling response depends on the distribution of bending stress along the unbraced segment.',source:S},
{id:'ch10-factors-6',title:'Stability variables recall',level:'retrieval',kind:'classification',q:'Which is NOT a principal lateral-stability variable identified in the chapter?',choices:['Paint colour','Unbraced length','End restraint','Load position relative to shear centre'],answer:0,explanation:'Paint colour does not control the structural LTB mechanics discussed here.',source:S}
]);
add('10:Buckling of Real Beams',[
{id:'ch10-real-1',title:'Real-beam imperfections',level:'foundation',kind:'classification',q:'Which imperfection can reduce the buckling resistance of a real beam?',choices:['Initial crookedness or twist','Perfect straightness','Zero residual stress','Ideal full restraint'],answer:0,explanation:'Real beams may contain geometric imperfections and residual stresses that lower practical stability.',source:S},
{id:'ch10-real-2',title:'Residual stress effect',level:'core',kind:'reasoning',q:'Why can residual stresses matter before the nominal section reaches full yield?',choices:['Some regions may yield earlier, changing stiffness and buckling behaviour','They make the beam perfectly straight','They always raise the elastic critical moment','They eliminate local buckling'],answer:0,explanation:'Residual stresses create nonuniform pre-existing stress states and can trigger earlier inelasticity.',source:S},
{id:'ch10-real-3',title:'Design reduction',level:'core',kind:'concept',q:'Why do design rules use calibrated LTB reduction factors or buckling curves?',choices:['To account for real imperfections and inelastic response absent from ideal elastic theory','To ignore stability','To increase every critical moment','To replace section classification'],answer:0,explanation:'Calibrated design resistance bridges ideal theory and observed real-member behaviour.',source:S},
{id:'ch10-real-4',title:'Imperfect restraint',level:'application',kind:'reasoning',q:'A restraint assumed perfect in analysis is flexible in reality. What is the likely design concern?',choices:['Actual lateral stability may be lower than assumed','The beam becomes fully plastic automatically','Deflection becomes zero','Shear force disappears'],answer:0,explanation:'Restraint stiffness and effectiveness influence the real buckling mode and resistance.',source:S},
{id:'ch10-real-5',title:'Elastic critical moment use',level:'application',kind:'concept',q:'Should the ideal elastic critical moment normally be used directly as the design bending resistance of a real unrestrained beam?',choices:['No, real-member reductions and section limits are required','Yes, always','Only if the web is painted','Only for lintels'],answer:0,explanation:'Design resistance must account for imperfections, inelasticity and the applicable member buckling treatment.',source:S},
{id:'ch10-real-6',title:'Ideal versus real',level:'retrieval',kind:'classification',q:'Which feature belongs to a real beam but is excluded from ideal elastic buckling theory?',choices:['Residual stress','Elastic modulus','Cross-section geometry','Member length'],answer:0,explanation:'Residual stresses and initial imperfections are key departures from the idealized model.',source:S}
]);
add('10:Behaviour of Beams in Bending',[
{id:'ch10-bendbeh-1',title:'Elastic stress distribution',level:'foundation',kind:'concept',q:'Before yielding, the normal bending stress distribution across a prismatic elastic beam depth is approximately:',choices:['Linear','Uniform everywhere','Parabolic with zero extreme-fibre stress','Random'],answer:0,explanation:'Elastic flexure produces a linear normal-stress distribution with zero stress at the neutral axis.',source:S},
{id:'ch10-bendbeh-2',title:'First yield',level:'core',kind:'concept',q:'Where does first yield occur in ordinary elastic bending?',choices:['At the most highly stressed extreme fibre','At every fibre simultaneously','Only at the neutral axis','Only in the web centre'],answer:0,explanation:'The extreme fibre reaches yield first as the linear elastic stress distribution increases.',source:S},
{id:'ch10-bendbeh-3',title:'Yield spread',level:'core',kind:'reasoning',q:'For a compact or plastic section, what happens as moment increases beyond first yield?',choices:['Yielding spreads progressively into the section','All stress drops to zero','The section immediately fractures','The neutral axis must vanish'],answer:0,explanation:'Plasticity spreads from the extreme fibres toward the interior as moment rises.',source:S},
{id:'ch10-bendbeh-4',title:'Plastic moment availability',level:'application',kind:'reasoning',q:'Why can a slender section fail to develop the same bending capacity as a stocky plastic section?',choices:['Local buckling can intervene before a full plastic stress distribution forms','Its yield stress is always zero','It has no neutral axis','It cannot carry shear'],answer:0,explanation:'Local buckling limits usable stress distribution in slender compression elements.',source:S},
{id:'ch10-bendbeh-5',title:'High shear interaction',level:'core',kind:'concept',q:'What can happen to bending resistance when shear becomes sufficiently high?',choices:['Available bending resistance may need to be reduced','Bending resistance always doubles','Shear becomes irrelevant','The beam becomes laterally restrained'],answer:0,explanation:'High shear and bending share section capacity and may require interaction treatment.',source:S},
{id:'ch10-bendbeh-6',title:'Behaviour sequence',level:'retrieval',kind:'classification',q:'Which sequence best describes increasing bending demand in a stocky ductile beam section?',choices:['Elastic response → first yield → spread of yielding → plastic capacity','Plastic capacity → elastic response → first yield','Fracture → elastic response → yield','Local buckling must always occur before yield'],answer:0,explanation:'This sequence captures the transition from elastic to plastic bending behaviour for stocky sections.',source:S}
]);
add('10:Design Strength of Laterally Supported Beams in Bending',[
{id:'ch10-supported-1',title:'Effect of lateral support',level:'foundation',kind:'concept',q:'What instability is effectively prevented when a beam has adequate lateral restraint to its compression flange?',choices:['Lateral-torsional buckling','Local web bearing','Material yielding','Vertical shear'],answer:0,explanation:'Adequate lateral restraint removes LTB as the controlling member instability mode.',source:S},
{id:'ch10-supported-2',title:'Remaining bending controls',level:'core',kind:'reasoning',q:'Once LTB is prevented, what primarily controls bending strength?',choices:['Section classification and cross-section capacity','Soil bearing capacity','Unbraced length alone','Paint thickness'],answer:0,explanation:'The usable cross-section stress distribution and local slenderness become central.',source:S},
{id:'ch10-supported-3',title:'Plastic/compact capacity',level:'core',kind:'concept',q:'Which section classes may use plastic section capacity subject to code limits when laterally supported?',choices:['Plastic and compact','Slender only','Semi-compact only','All classes without distinction'],answer:0,explanation:'Plastic and compact classes can develop plastic moment, although only plastic sections have the full rotation capacity for plastic analysis.',source:S},
{id:'ch10-supported-4',title:'Semi-compact design basis',level:'core',kind:'classification',q:'Which property is central to bending resistance of a laterally supported semi-compact section?',choices:['Elastic section modulus to the extreme fibre','Plastic rotation capacity only','Warping constant only','Torsional constant only'],answer:0,explanation:'Semi-compact sections are limited by first yield and therefore use an elastic section-property basis.',source:S},
{id:'ch10-supported-5',title:'High shear check',level:'application',kind:'reasoning',q:'A laterally supported beam has very high shear near a region of high moment. What additional design issue arises?',choices:['Bending resistance may need reduction for shear interaction','LTB automatically governs','Deflection becomes irrelevant','Section classification can be ignored'],answer:0,explanation:'High shear can reduce the moment resistance even when LTB is prevented.',source:S},
{id:'ch10-supported-6',title:'Supported beam recall',level:'retrieval',kind:'concept',q:'Adequate lateral support removes which check but not the others?',choices:['LTB check; section strength, shear and serviceability still remain','All beam checks','Shear check only','Deflection check only'],answer:0,explanation:'Lateral support addresses member instability, not every other limit state.',source:S}
]);
add('10:Design Strength of Laterally Unsupported Beams',[
{id:'ch10-unsupported-1',title:'Extra design limit',level:'foundation',kind:'concept',q:'What distinguishes the design of a laterally unsupported beam from an otherwise similar supported beam?',choices:['Lateral-torsional buckling resistance must also be checked','Shear no longer exists','Section classification is unnecessary','Deflection is forbidden'],answer:0,explanation:'An unrestrained compression flange introduces a member stability limit state.',source:S},
{id:'ch10-unsupported-2',title:'Beam slenderness role',level:'core',kind:'concept',q:'What is the purpose of beam slenderness in LTB design?',choices:['Relate instability susceptibility to the elastic critical moment and section resistance','Determine steel density','Replace the bending moment diagram','Calculate concrete strength'],answer:0,explanation:'Beam slenderness is used with a buckling curve/reduction factor to obtain practical LTB resistance.',source:S},
{id:'ch10-unsupported-3',title:'Reduction factor',level:'core',kind:'reasoning',q:'Why is a lateral-torsional buckling reduction factor applied?',choices:['To reduce ideal/section capacity to a realistic instability-controlled design resistance','To increase the applied moment','To ignore imperfections','To eliminate shear'],answer:0,explanation:'The reduction accounts for susceptibility to member instability and real-member behaviour.',source:S},
{id:'ch10-unsupported-4',title:'Lower resistance governs',level:'application',kind:'concept',q:'If section bending capacity exceeds the LTB-controlled resistance, which value governs?',choices:['The lower LTB-controlled resistance','The higher section capacity','Their sum','Neither'],answer:0,explanation:'The design moment resistance is limited by the most restrictive applicable limit state.',source:S},
{id:'ch10-unsupported-5',title:'Adding restraint',level:'application',kind:'reasoning',q:'What is the expected effect of adding effective lateral restraint to the compression flange of an unsupported beam?',choices:['Increase usable bending resistance by reducing LTB susceptibility','Decrease shear area','Increase local buckling automatically','Remove the bending moment'],answer:0,explanation:'Shortening the unbraced length generally improves LTB resistance.',source:S},
{id:'ch10-unsupported-6',title:'Unsupported beam sequence',level:'retrieval',kind:'classification',q:'Which sequence is appropriate for a laterally unsupported beam?',choices:['Section capacity → elastic LTB basis/slenderness → reduction → governing design resistance','Deflection only → stop','Shear only → stop','Ignore restraint → use plastic moment always'],answer:0,explanation:'Both cross-section resistance and instability reduction must be considered.',source:S}
]);
add('10:Shear Strength of Steel Beams',[
{id:'ch10-shear-1',title:'Main shear element',level:'foundation',kind:'concept',q:'Why does the web of an I-section carry most of the vertical shear?',choices:['Its area lies through the depth where beam shear flow is concentrated','The flanges have zero stress','The web carries no bending stress','Only the web has yield strength'],answer:0,explanation:'The web provides the principal shear-resisting area through the section depth.',source:S},
{id:'ch10-shear-2',title:'Shear distribution',level:'core',kind:'concept',q:'Where is elastic shear stress generally greatest in a typical I-beam web?',choices:['Near the neutral-axis region','At the outer flange surface','At the very top flange tip only','Uniformly at all points'],answer:0,explanation:'The elastic shear-stress distribution peaks around the neutral axis and reduces toward free flange surfaces.',source:S},
{id:'ch10-shear-3',title:'Web area effect',level:'core',kind:'reasoning',q:'All else equal, what happens to basic shear resistance if effective web shear area is increased?',choices:['It increases','It decreases','It becomes zero','It is unrelated to area'],answer:0,explanation:'Shear resistance is directly linked to the effective shear-resisting web area and design shear stress.',source:S},
{id:'ch10-shear-4',title:'High shear and moment',level:'application',kind:'reasoning',q:'Why is a high-shear region checked for interaction with bending?',choices:['Large shear can reduce the section capacity available for moment','Shear always increases plastic moment','Moment disappears wherever shear exists','Only lateral restraint matters'],answer:0,explanation:'At sufficiently high shear, the web cannot simultaneously provide its full contribution to bending capacity.',source:S},
{id:'ch10-shear-5',title:'Flange versus web role',level:'application',kind:'classification',q:'Which simplified load-sharing description is most appropriate for an I-beam?',choices:['Flanges are highly effective in bending; web is highly effective in vertical shear','Web carries all bending and flanges carry all shear','Only flanges matter for every action','Only web matters for every action'],answer:0,explanation:'The I-shape efficiently places flange material far from the neutral axis while retaining a web for shear transfer.',source:S},
{id:'ch10-shear-6',title:'Shear recall',level:'retrieval',kind:'concept',q:'A beam passes bending checks but its web shear resistance is inadequate. Is the beam acceptable?',choices:['No, every relevant strength check must pass','Yes, bending always governs','Yes, if deflection is small','Only if the beam is unrestrained'],answer:0,explanation:'Shear is an independent strength limit state that must be satisfied.',source:S}
]);
add('10:Maximum Deflection',[
{id:'ch10-defl-1',title:'Serviceability classification',level:'foundation',kind:'classification',q:'Maximum beam deflection is primarily what type of limit-state issue?',choices:['Serviceability','Ultimate material rupture only','Fatigue only','Corrosion only'],answer:0,explanation:'Deflection governs usability, finishes, appearance and function rather than necessarily imminent collapse.',source:S},
{id:'ch10-defl-2',title:'Flexural rigidity',level:'core',kind:'reasoning',q:'For the same load and span, what happens to elastic deflection when flexural rigidity EI increases?',choices:['It decreases','It increases','It remains identical','It becomes independent of stiffness'],answer:0,explanation:'Elastic deflection varies inversely with flexural rigidity for a given loading and boundary condition.',source:S},
{id:'ch10-defl-3',title:'Span sensitivity',level:'core',kind:'reasoning',q:'Why are long-span beams often serviceability-sensitive?',choices:['Deflection is strongly influenced by span','Yield strength becomes zero with span','Shear force always vanishes','Long spans eliminate bending'],answer:0,explanation:'Elastic deflection grows strongly with span for common beam load cases.',source:S},
{id:'ch10-defl-4',title:'Brittle finishes',level:'application',kind:'reasoning',q:'Why can brittle cladding or finishes require tighter deflection control?',choices:['Excessive movement can crack or damage them','They increase steel yield stress','They prevent all bending','They eliminate service loads'],answer:0,explanation:'Nonstructural brittle components may be damaged by deformations that are still below steel strength limits.',source:S},
{id:'ch10-defl-5',title:'Drainage concern',level:'application',kind:'concept',q:'Which functional problem can excessive roof-beam deflection create?',choices:['Poor drainage or ponding tendency','Higher steel modulus','Elimination of wind load','Automatic lateral restraint'],answer:0,explanation:'Excessive sag can alter drainage geometry and impair service performance.',source:S},
{id:'ch10-defl-6',title:'Strength versus stiffness',level:'retrieval',kind:'concept',q:'What does a failed deflection check usually indicate even if strength checks pass?',choices:['The beam may need greater stiffness, changed span/restraint or another section','The steel has no yield strength','The beam must be a tension member','The web must be removed'],answer:0,explanation:'Serviceability can require a stiffer solution independently of ultimate strength capacity.',source:S}
]);
add('10:Web Buckling and Web Crippling',[
{id:'ch10-web-1',title:'Concentrated web demand',level:'foundation',kind:'concept',q:'Where are web buckling and crippling especially important?',choices:['Near concentrated loads and support reactions','Only at zero-shear points','Only at midspan under pure moment','Only in tension flanges'],answer:0,explanation:'Concentrated compression enters the web near loads and supports and can trigger local failure.',source:S},
{id:'ch10-web-2',title:'Buckling versus crippling',level:'core',kind:'classification',q:'Which statement best distinguishes web buckling from web crippling?',choices:['Buckling is instability; crippling is local crushing/yielding-type failure','They are identical to LTB','Crippling is only torsion','Buckling is only corrosion'],answer:0,explanation:'The chapter treats web buckling as instability and crippling/bearing as local compressive failure.',source:S},
{id:'ch10-web-3',title:'Load dispersion',level:'core',kind:'reasoning',q:'Why is an effective load-dispersion width used in concentrated web checks?',choices:['The reaction/load spreads through the flange into a finite length of web','The load acts at one mathematical point with no spread','It increases Young’s modulus','It eliminates bearing'],answer:0,explanation:'Local compressive stress is distributed over an effective web length rather than an ideal zero-width line.',source:S},
{id:'ch10-web-4',title:'Stiffener trigger',level:'application',kind:'concept',q:'When should a bearing/transverse stiffener be considered at a support?',choices:['When the unstiffened web cannot safely resist the concentrated reaction','Whenever bending moment is nonzero','Only when shear is zero','Only in fully restrained beams'],answer:0,explanation:'Stiffeners provide an additional load path when local web resistance is inadequate.',source:S},
{id:'ch10-web-5',title:'Stiffener function',level:'application',kind:'reasoning',q:'What does a bearing stiffener primarily do at a concentrated reaction?',choices:['Help transfer concentrated compression safely through the web region','Increase unbraced length','Create web openings','Reduce flange area'],answer:0,explanation:'It strengthens the local compression load path and reduces susceptibility to buckling/crippling.',source:S},
{id:'ch10-web-6',title:'Local web recall',level:'retrieval',kind:'concept',q:'Can a beam with adequate global bending strength still fail locally at a support?',choices:['Yes, web buckling or crippling can govern','No, bending strength guarantees every local check','Only concrete beams can','Only if there is no reaction'],answer:0,explanation:'Global flexural adequacy does not automatically ensure local concentrated-load resistance.',source:S}
]);
add('10:Holes in Beams',[
{id:'ch10-holes-1',title:'Why openings matter',level:'foundation',kind:'reasoning',q:'Why can a web opening affect beam strength?',choices:['It interrupts shear flow and removes effective material','It increases web area','It guarantees full lateral restraint','It increases elastic modulus'],answer:0,explanation:'Openings alter the load path and reduce available web material.',source:S},
{id:'ch10-holes-2',title:'Size and location',level:'core',kind:'concept',q:'Which two geometric features are especially important when assessing a beam opening?',choices:['Its size and location','Paint colour and age','Steel density and temperature only','Bolt head shape only'],answer:0,explanation:'The structural effect depends strongly on how much material is removed and where the opening lies relative to high shear/moment regions.',source:S},
{id:'ch10-holes-3',title:'Bolt holes',level:'core',kind:'classification',q:'Small bolt holes are generally addressed through which type of design considerations?',choices:['Relevant net-section and connection provisions','Fire resistance only','Soil pressure only','Concrete creep'],answer:0,explanation:'Small connection holes are handled using the applicable net-section and connection checks.',source:S},
{id:'ch10-holes-4',title:'Large web opening',level:'application',kind:'reasoning',q:'A large service opening is introduced into a web in a high-shear region. What should the designer expect?',choices:['A potentially significant reduction/disturbance of shear capacity and local action','No structural effect','Automatic increase in bending capacity','Elimination of web buckling'],answer:0,explanation:'Large openings can substantially disturb web shear transfer and local bending behaviour.',source:S},
{id:'ch10-holes-5',title:'Gross-section assumption',level:'application',kind:'concept',q:'Is it valid to assume a beam with a significant opening behaves exactly like the unperforated gross section?',choices:['No, the opening must be explicitly considered','Yes, always','Yes, if the beam is steel','Only if the flange is in compression'],answer:0,explanation:'Significant openings alter effective section and load paths.',source:S},
{id:'ch10-holes-6',title:'Opening design recall',level:'retrieval',kind:'concept',q:'What is the safest general design principle for beam openings?',choices:['Check the modified load path, remaining section and local effects','Ignore openings below mid-depth','Assume openings increase stiffness','Use only the original section modulus'],answer:0,explanation:'Openings require explicit structural assessment rather than a gross-section assumption.',source:S}
]);
add('10:Latticed Beams',[
{id:'ch10-lattice-1',title:'Open-web concept',level:'foundation',kind:'concept',q:'What replaces the solid web in a latticed beam?',choices:['A triangulated system of bars or angles','A concrete slab','A solid timber panel','Nothing at all'],answer:0,explanation:'Latticed beams use a triangulated open web between chords.',source:S},
{id:'ch10-lattice-2',title:'Shear transfer mechanism',level:'core',kind:'reasoning',q:'How is vertical shear transferred through a latticed beam web system?',choices:['Primarily by axial forces in the diagonal lattice members','Only by flange bending','Only by torsion','By paint adhesion'],answer:0,explanation:'Triangulation converts the web shear demand into axial tension/compression in lattice elements.',source:S},
{id:'ch10-lattice-3',title:'Weight advantage',level:'core',kind:'concept',q:'Why can a latticed beam be lighter than a comparable solid-web beam?',choices:['The solid web plate is replaced by discrete members where material is structurally useful','Steel density is reduced','The flanges are removed','The beam carries no shear'],answer:0,explanation:'Open-web geometry can reduce material while maintaining depth and load transfer.',source:S},
{id:'ch10-lattice-4',title:'Services advantage',level:'application',kind:'concept',q:'What practical building-services advantage does an open-web latticed beam provide?',choices:['Services may pass through the open web depth','It eliminates all service penetrations','It makes the beam solid','It prevents any duct crossing'],answer:0,explanation:'The open web can accommodate pipes, ducts and other services through the beam depth.',source:S},
{id:'ch10-lattice-5',title:'Connection importance',level:'application',kind:'reasoning',q:'Why are lattice-member connections structurally important?',choices:['They must transfer the axial forces that make the triangulated shear load path work','They carry no force','They are decorative only','They eliminate chord forces'],answer:0,explanation:'The open-web mechanism depends on reliable force transfer at lattice-to-chord joints.',source:S},
{id:'ch10-lattice-6',title:'Lattice design scope',level:'retrieval',kind:'classification',q:'Which set must be designed in a latticed beam?',choices:['Chords, lattice members and their connections','Only the top chord','Only paint protection','Only support bolts'],answer:0,explanation:'All components of the triangulated force system must satisfy strength and stability requirements.',source:S}
]);
add('10:Castellated Beams',[
{id:'ch10-cast-1',title:'How castellated beams are made',level:'foundation',kind:'concept',q:'How is a castellated beam commonly produced from a rolled I-section?',choices:['Cut the web in a pattern, shift the halves and rejoin them','Drill random flange holes only','Weld two channels back-to-back without cutting','Remove both flanges'],answer:0,explanation:'The cut-and-rejoin process creates a deeper member with repeated web openings.',source:S},
{id:'ch10-cast-2',title:'Depth advantage',level:'core',kind:'reasoning',q:'Why can increasing the depth of a castellated beam improve bending efficiency?',choices:['Material is moved farther from the neutral axis, increasing section modulus','Steel density decreases','Yield stress increases automatically','Shear becomes zero'],answer:0,explanation:'Greater depth increases leverage of flange material and can improve bending section properties.',source:S},
{id:'ch10-cast-3',title:'Opening consequence',level:'core',kind:'concept',q:'What new local action can web openings introduce in castellated beams?',choices:['Vierendeel-type local bending around openings','Only pure axial tension','No additional action','Foundation overturning'],answer:0,explanation:'The opening geometry interrupts the web and can create local frame-like bending around the opening.',source:S},
{id:'ch10-cast-4',title:'Web-post stability',level:'application',kind:'concept',q:'Which local stability check is associated with the solid web strip between adjacent castellated openings?',choices:['Web-post buckling','Euler buckling of the entire flange only','Soil bearing','Concrete punching'],answer:0,explanation:'The web post between openings can become a critical slender compression/shear element.',source:S},
{id:'ch10-cast-5',title:'Fabrication joint',level:'application',kind:'reasoning',q:'Why must the rejoining welds of a castellated beam be designed carefully?',choices:['They restore force transfer between the cut halves of the web','They are decorative only','They eliminate shear','They increase beam depth without carrying force'],answer:0,explanation:'The fabricated section relies on those welds to act as an integrated beam.',source:S},
{id:'ch10-cast-6',title:'Castellated trade-off',level:'retrieval',kind:'concept',q:'What is the central castellated-beam trade-off?',choices:['Greater depth and bending efficiency, but additional opening-related local checks','Lower depth with no openings','No fabrication with higher weight only','Elimination of all shear and buckling'],answer:0,explanation:'The geometric efficiency comes with additional local strength and stability considerations.',source:S}
]);
add('10:Lintels',[
{id:'ch10-lintel-1',title:'Location of lintel',level:'foundation',kind:'concept',q:'Where is a structural lintel normally located?',choices:['Over an opening in a wall','Under a column base','Between roof trusses only','Inside a foundation pile'],answer:0,explanation:'Lintels bridge openings such as doors and windows.',source:S},
{id:'ch10-lintel-2',title:'Load carried',level:'foundation',kind:'concept',q:'What load does a lintel primarily transfer around an opening?',choices:['Wall/masonry or associated construction above the opening','Crane wheel load only','Foundation uplift only','Pure torsion only'],answer:0,explanation:'The lintel carries the material that cannot continue directly through the opening.',source:S},
{id:'ch10-lintel-3',title:'Possible steel forms',level:'core',kind:'classification',q:'Which steel forms may be used as lintels depending on span and loading?',choices:['Angles, channels or beam sections','Only solid round bars','Only cables','Only plates with no bending stiffness'],answer:0,explanation:'The chapter notes several practical steel-section arrangements for lintel action.',source:S},
{id:'ch10-lintel-4',title:'Lintel checks',level:'core',kind:'classification',q:'Which group of checks belongs to lintel design?',choices:['Bending, shear, bearing and deflection','Only corrosion colour','Only Euler column buckling','Only bolt pretension'],answer:0,explanation:'A lintel is still a beam and must satisfy the relevant strength and serviceability checks.',source:S},
{id:'ch10-lintel-5',title:'Support length',level:'application',kind:'reasoning',q:'Why must a lintel have adequate support/bearing length at its ends?',choices:['To transfer reactions safely into the supporting wall or structure','To increase steel density','To eliminate bending moment','To make the opening wider automatically'],answer:0,explanation:'End reactions need a safe bearing load path into the adjacent construction.',source:S},
{id:'ch10-lintel-6',title:'Architectural fit',level:'retrieval',kind:'concept',q:'Why is dimensional fit important in steel lintel design?',choices:['The beam must fit within the wall construction while providing adequate structural support','It changes yield stress','It eliminates serviceability','It makes lateral stability irrelevant'],answer:0,explanation:'Lintels are integrated with wall geometry, so structural and construction requirements must both be satisfied.',source:S}
]);
add('10:Purlins',[
{id:'ch10-purlin-1',title:'Purlin load path',level:'foundation',kind:'concept',q:'A roof purlin transfers roof sheeting loads to which primary members?',choices:['Rafters or trusses','Foundation piles only','Wall lintels','Column bases only'],answer:0,explanation:'Purlins span between primary roof frames/trusses and carry the sheeting.',source:S},
{id:'ch10-purlin-2',title:'Why biaxial bending',level:'core',kind:'reasoning',q:'Why can a sloping-roof purlin bend about both principal axes?',choices:['Gravity/wind load components act relative to the inclined section axes','Purlins carry only axial force','Roof slope eliminates bending','Steel anisotropy creates the second moment'],answer:0,explanation:'Roof inclination and wind direction can resolve loading into components about both section axes.',source:S},
{id:'ch10-purlin-3',title:'Sag rods',level:'core',kind:'concept',q:'What is one structural purpose of sag rods or similar restraints in purlin systems?',choices:['Provide intermediate restraint/support to improve purlin behaviour','Increase roof load','Remove the sheeting','Create larger unbraced lengths'],answer:0,explanation:'Sag rods can restrain and help stabilize secondary roof members depending on the system.',source:S},
{id:'ch10-purlin-4',title:'Wind reversal',level:'application',kind:'reasoning',q:'Why must purlin design consider wind as well as gravity?',choices:['Wind can change the magnitude and direction of roof loading, including uplift','Wind affects paint only','Wind never acts on roofs','Gravity disappears during wind'],answer:0,explanation:'Roof secondary members must transfer both gravity and wind actions from sheeting.',source:S},
{id:'ch10-purlin-5',title:'Spacing effect',level:'application',kind:'concept',q:'Why does purlin spacing matter structurally?',choices:['It affects the tributary roof area and therefore load carried by each purlin','It changes steel modulus','It fixes yield stress','It removes bending about one axis'],answer:0,explanation:'Purlin spacing controls how much sheeting load is collected by each secondary member.',source:S},
{id:'ch10-purlin-6',title:'Purlin design recall',level:'retrieval',kind:'classification',q:'Which set best describes purlin design considerations?',choices:['Roof loads, biaxial bending, restraint/spacing and serviceability','Only axial tension','Only concrete bearing','Only torsional buckling with no bending'],answer:0,explanation:'Purlins are secondary beams with roof-specific loading and restraint conditions.',source:S}
]);
add('10:Biaxial Bending',[
{id:'ch10-biax-1',title:'Definition',level:'foundation',kind:'concept',q:'Biaxial bending means that a member has bending moment components about:',choices:['Both principal axes','Only one principal axis','Only its longitudinal axis as torsion','No axis'],answer:0,explanation:'Two simultaneous principal-axis bending components define biaxial bending.',source:S},
{id:'ch10-biax-2',title:'Principal strengths',level:'core',kind:'reasoning',q:'Why must bending resistance about each principal axis be known in a biaxial check?',choices:['The two moment components consume capacities associated with their respective axes','Both axes always have identical resistance','Only the stronger axis matters','Bending capacity is independent of section geometry'],answer:0,explanation:'A section can have very different major- and minor-axis strengths.',source:S},
{id:'ch10-biax-3',title:'Interaction concept',level:'core',kind:'concept',q:'What is the purpose of a biaxial bending interaction relationship?',choices:['Assess the combined utilization from both moment components','Convert bending into pure shear','Calculate steel density','Ignore the weaker axis'],answer:0,explanation:'The interaction check ensures the combined demand remains within the section/member resistance.',source:S},
{id:'ch10-biax-4',title:'Shear centre condition',level:'application',kind:'reasoning',q:'Why is loading through the shear centre useful when discussing pure biaxial bending?',choices:['It avoids adding torsion from transverse-load eccentricity','It eliminates both bending moments','It makes the section symmetric','It increases yield strength'],answer:0,explanation:'If the load acts through the shear centre, the analysis can focus on bending components without eccentric torsion.',source:S},
{id:'ch10-biax-5',title:'Purlin link',level:'application',kind:'classification',q:'Which Chapter 10 member commonly illustrates biaxial bending because of roof slope and wind?',choices:['Purlin','Column base','Tie rod','Bearing stiffener'],answer:0,explanation:'Purlins frequently experience load components about both principal axes.',source:S},
{id:'ch10-biax-6',title:'Biaxial recall',level:'retrieval',kind:'concept',q:'Can a member be adequate about each axis separately yet require a combined biaxial interaction check?',choices:['Yes, simultaneous utilization must be assessed together','No, separate checks are always sufficient','Only in concrete','Only if no moment exists'],answer:0,explanation:'Simultaneous bending components interact and therefore require a combined design assessment.',source:S}
]);
add('10:Unsymmetrical Bending',[
{id:'ch10-unsymbend-1',title:'When it occurs',level:'foundation',kind:'concept',q:'Unsymmetrical bending occurs when the applied bending moment is not aligned with:',choices:['A principal centroidal axis','The member longitudinal axis only','Any support reaction','The web thickness'],answer:0,explanation:'Oblique bending relative to principal axes produces combined principal-axis flexure.',source:S},
{id:'ch10-unsymbend-2',title:'Resolution method',level:'core',kind:'reasoning',q:'How is an oblique bending moment conveniently analysed?',choices:['Resolve it into components about the principal axes','Ignore the smaller component','Treat it as axial tension','Assume one section modulus for every direction'],answer:0,explanation:'Principal-axis components can be analysed separately and their normal stresses combined.',source:S},
{id:'ch10-unsymbend-3',title:'Stress combination',level:'core',kind:'concept',q:'The normal stress at a point under unsymmetrical bending is obtained from:',choices:['The combined effects of the principal-axis bending components','Only shear stress','Only axial stress','Only torsional shear'],answer:0,explanation:'Each bending component contributes normal stress; superposition gives the total elastic bending stress.',source:S},
{id:'ch10-unsymbend-4',title:'Neutral axis',level:'application',kind:'reasoning',q:'Why need the neutral axis not coincide with an arbitrarily chosen geometric axis in unsymmetrical bending?',choices:['The stress field follows the resolved principal-axis moments and section properties','The neutral axis is always horizontal','Steel has no centroid','Bending stress is uniform'],answer:0,explanation:'The orientation of zero normal stress depends on the combined principal-axis bending components.',source:S},
{id:'ch10-unsymbend-5',title:'Principal axes importance',level:'application',kind:'concept',q:'Why are principal axes especially useful for unsymmetrical bending calculations?',choices:['The product of inertia is zero about them, simplifying independent bending components','They always equal the web and flange axes','They remove all torsion','They determine steel grade'],answer:0,explanation:'Principal axes provide the natural uncoupled bending directions for the cross-section.',source:S},
{id:'ch10-unsymbend-6',title:'Unsymmetrical bending recall',level:'retrieval',kind:'classification',q:'Which action is the correct first step for a moment applied at an oblique angle to the principal axes?',choices:['Resolve the moment into principal-axis components','Set the smaller component to zero','Convert it to shear only','Assume a symmetric section'],answer:0,explanation:'Principal-axis resolution is the basic analytical step.',source:S}
]);
add('10:Unsymmetric Sections',[
{id:'ch10-unsymsec-1',title:'Centroid and shear centre',level:'foundation',kind:'concept',q:'For an unsymmetric open section, must the centroid and shear centre coincide?',choices:['No','Yes, always','Only for angles','Only for channels'],answer:0,explanation:'In unsymmetric open sections, these important geometric points can be different.',source:S},
{id:'ch10-unsymsec-2',title:'Load off shear centre',level:'core',kind:'reasoning',q:'What happens when a transverse load on an unsymmetric section does not pass through its shear centre?',choices:['Bending is accompanied by torsion','Bending disappears','All stresses become uniform','The section becomes doubly symmetric'],answer:0,explanation:'The eccentric load creates a twisting moment about the shear centre.',source:S},
{id:'ch10-unsymsec-3',title:'Principal axes',level:'core',kind:'concept',q:'Why must principal axes be identified for unsymmetric sections?',choices:['Their stiffness and bending response need not align with obvious geometric axes','Steel has no modulus on geometric axes','They determine corrosion rate only','They remove the centroid'],answer:0,explanation:'The natural bending directions may be rotated relative to convenient drawing axes.',source:S},
{id:'ch10-unsymsec-4',title:'Typical shapes',level:'foundation',kind:'classification',q:'Which section type may require special attention to shear-centre location and unsymmetrical behaviour?',choices:['Channel or angle','Doubly symmetric solid circle only','Concrete cube','Flat slab'],answer:0,explanation:'Channels, angles, tees and similar open sections can have noncoincident centroid/shear-centre or rotated principal axes.',source:S},
{id:'ch10-unsymsec-5',title:'Design implication',level:'application',kind:'reasoning',q:'Why is using only centroidal load eccentricity insufficient for some open unsymmetric beams?',choices:['Torsion depends on eccentricity relative to the shear centre','The centroid is not defined','Bending does not depend on load position','Only supports matter'],answer:0,explanation:'The shear centre, not merely the centroid, governs whether transverse loading produces twist.',source:S},
{id:'ch10-unsymsec-6',title:'Unsymmetric-section checklist',level:'retrieval',kind:'classification',q:'Which set should be established before analysing an unsymmetric beam section?',choices:['Centroid, principal axes, section properties and shear centre','Only mass density','Only flange width','Only paint thickness'],answer:0,explanation:'These properties define the bending and torsional response of the section.',source:S}
]);
add('10:Design of Beams',[
{id:'ch10-design-1',title:'First design step',level:'foundation',kind:'concept',q:'Before selecting a beam section, what must first be established?',choices:['Design actions and load effects','Paint system only','The final section depth','The final bolt count'],answer:0,explanation:'Factored loads and resulting moment, shear and other actions define the required structural resistance.',source:S},
{id:'ch10-design-2',title:'Trial section',level:'core',kind:'reasoning',q:'Why is steel-beam selection typically iterative?',choices:['A trial section must be checked against multiple criteria and revised if any fail','One section always satisfies every span','Only self-weight changes','Classification is independent of section dimensions'],answer:0,explanation:'Strength, stability, web and serviceability checks may require changes to section size or restraint.',source:S},
{id:'ch10-design-3',title:'Classification step',level:'core',kind:'concept',q:'Why should section classification be established early in beam design?',choices:['It determines what bending stress distribution/capacity can be used','It determines roof load','It fixes support type','It replaces LTB checks'],answer:0,explanation:'Classification sets whether plastic, elastic or effective-section bending resistance is appropriate.',source:S},
{id:'ch10-design-4',title:'Restraint decision',level:'application',kind:'reasoning',q:'What additional check becomes essential if the compression flange is not adequately laterally restrained?',choices:['Lateral-torsional buckling','Only corrosion','Only bolt slip','Only axial tension'],answer:0,explanation:'Unrestrained beams require member stability assessment in addition to cross-section strength.',source:S},
{id:'ch10-design-5',title:'Concentrated reaction',level:'application',kind:'concept',q:'A large support reaction acts on a relatively thin web. Which local check must be included?',choices:['Web buckling/crippling or bearing resistance','Only purlin biaxial bending','Only fatigue','Only plastic hinge length'],answer:0,explanation:'Concentrated loads and reactions can govern the local web design.',source:S},
{id:'ch10-design-6',title:'Final verification',level:'retrieval',kind:'classification',q:'Which complete set best represents final beam verification?',choices:['Bending, shear, stability, local web effects and serviceability','Bending only','Deflection only','Shear only'],answer:0,explanation:'A beam is acceptable only after all relevant strength, stability and serviceability checks pass.',source:S}
]);
add('10:Examples',[
{id:'ch10-ex-1',title:'Worked-example purpose',level:'foundation',kind:'reasoning',q:'What is the main design habit reinforced by the Chapter 10 worked examples?',choices:['Check every relevant limit state rather than selecting by section modulus alone','Select the lightest beam without checks','Use only elastic bending stress','Ignore restraint and deflection'],answer:0,explanation:'The examples demonstrate integrated member selection and verification.',source:S},
{id:'ch10-ex-2',title:'Supported versus unsupported',level:'core',kind:'classification',q:'Why do worked examples distinguish laterally supported and unsupported beams?',choices:['The unsupported case adds lateral-torsional stability requirements','Supported beams carry no moment','Unsupported beams carry no shear','Section classification applies only to supported beams'],answer:0,explanation:'Compression-flange restraint changes the governing member stability checks.',source:S},
{id:'ch10-ex-3',title:'Special beam forms',level:'core',kind:'concept',q:'Which special members are included in the Chapter 10 example scope?',choices:['Purlins and castellated beams','Only columns','Only foundations','Only cables'],answer:0,explanation:'The chapter applies beam-design logic to several special forms and loading situations.',source:S},
{id:'ch10-ex-4',title:'Local web example lesson',level:'application',kind:'reasoning',q:'What should an example involving a large support reaction prompt the designer to check beyond global moment capacity?',choices:['Web buckling/crippling and need for stiffening','Only paint adhesion','Only torsional buckling of a column','Only net tension area'],answer:0,explanation:'Concentrated reactions can control local web design.',source:S},
{id:'ch10-ex-5',title:'Biaxial example lesson',level:'application',kind:'concept',q:'What is the key extra feature of a purlin or biaxial-bending example?',choices:['Moments about both principal axes must be assessed together','The member has no shear','Only one axis can bend','No serviceability check is needed'],answer:0,explanation:'Biaxial loading requires combined treatment of both bending components.',source:S},
{id:'ch10-ex-6',title:'Example retrieval',level:'retrieval',kind:'concept',q:'What should you do after a trial section passes bending in a worked design?',choices:['Continue checking shear, stability, web and serviceability as applicable','Stop immediately','Ignore restraint','Assume deflection passes'],answer:0,explanation:'Passing one check is only one step in the full design workflow.',source:S}
]);
add('10:Summary',[
{id:'ch10-summary-1',title:'Multiple governing modes',level:'foundation',kind:'concept',q:'Which statement best summarizes steel-beam design?',choices:['Different strength, stability, local and serviceability limit states can govern','Bending stress always governs','Shear always governs','Deflection is never relevant'],answer:0,explanation:'The controlling criterion depends on the member, loading, restraint and section geometry.',source:S},
{id:'ch10-summary-2',title:'Cross-section versus member',level:'core',kind:'classification',q:'Which pair distinguishes a cross-section issue from a member stability issue?',choices:['Local section classification versus lateral-torsional buckling','Paint versus corrosion','Dead load versus live load','Bolt versus weld'],answer:0,explanation:'Section classification concerns plate/local behaviour; LTB concerns overall beam instability.',source:S},
{id:'ch10-summary-3',title:'High shear',level:'core',kind:'reasoning',q:'Why is shear not simply checked independently and forgotten?',choices:['At high levels it can reduce available bending resistance','It always increases bending capacity','It has no web stress','It controls steel density'],answer:0,explanation:'Shear-bending interaction can become important at high shear demand.',source:S},
{id:'ch10-summary-4',title:'Serviceability role',level:'application',kind:'concept',q:'What can govern a beam even after all ultimate strength checks pass?',choices:['Deflection/serviceability','Steel chemistry only','Foundation settlement only','Bolt pretension only'],answer:0,explanation:'A strong beam may still be too flexible for its intended use.',source:S},
{id:'ch10-summary-5',title:'Special forms',level:'application',kind:'reasoning',q:'Why do castellated beams and purlins need geometry-specific checks in addition to general beam checks?',choices:['Their load paths and geometry introduce additional local or biaxial effects','They are not beams','They carry no bending','They have no web'],answer:0,explanation:'Special configurations introduce specific behaviours while retaining the general beam limit states.',source:S},
{id:'ch10-summary-6',title:'Chapter synthesis',level:'retrieval',kind:'classification',q:'Which set belongs to the Chapter 10 synthesis?',choices:['Classification, LTB, bending, shear, deflection and local web checks','Only tension-member rupture','Only column bases','Only welding symbols'],answer:0,explanation:'These are the principal beam-design themes of the chapter.',source:S}
]);
add('10:Exercises',[
{id:'ch10-exercise-1',title:'Exercise objective',level:'foundation',kind:'concept',q:'What skill do the Chapter 10 exercises emphasize?',choices:['Selecting and iterating a beam until all relevant criteria pass','Memorizing density only','Drawing weld symbols only','Calculating axial tension only'],answer:0,explanation:'The exercises require integrated application rather than a single isolated formula.',source:S},
{id:'ch10-exercise-2',title:'Section selection',level:'core',kind:'reasoning',q:'Why is selecting a section generally harder than checking a supplied section?',choices:['The designer must choose a trial member and iterate across several limit states','A supplied section has no loads','Selection requires no calculations','Checking always requires more unknowns'],answer:0,explanation:'Section selection combines sizing judgement with repeated verification.',source:S},
{id:'ch10-exercise-3',title:'Restraint interpretation',level:'application',kind:'concept',q:'Before solving an exercise on an unsupported beam, what condition must be understood clearly?',choices:['Lateral restraint and unbraced length','Paint colour','Concrete grade','Bolt head type only'],answer:0,explanation:'Restraint directly affects LTB resistance and therefore section adequacy.',source:S},
{id:'ch10-exercise-4',title:'Deflection exercise',level:'application',kind:'reasoning',q:'If an exercise specifies a serviceability-sensitive use, what should be checked after strength?',choices:['Deflection under the relevant service condition','Only ultimate moment again','Only steel density','Only column slenderness'],answer:0,explanation:'Serviceability verification is a separate required stage.',source:S},
{id:'ch10-exercise-5',title:'Purlin exercise',level:'application',kind:'concept',q:'What extra feature should be expected in a purlin exercise compared with a simple vertical-plane beam?',choices:['Bending about two axes due to roof loading geometry','No bending moment','No shear','Pure axial tension only'],answer:0,explanation:'Purlins commonly require biaxial bending assessment.',source:S},
{id:'ch10-exercise-6',title:'Exercise workflow recall',level:'retrieval',kind:'classification',q:'Which sequence is most appropriate when solving a design exercise?',choices:['Determine actions → choose trial section → check all applicable limits → revise if necessary','Choose section → ignore loads → finish','Check deflection only → finish','Check one formula only → finish'],answer:0,explanation:'Iterative verification is the core exercise skill.',source:S}
]);
add('10:Review Questions',[
{id:'ch10-review-1',title:'Classification review',level:'foundation',kind:'retrieval',q:'Which topic should you be able to explain before starting beam bending-strength design?',choices:['Section classification','Concrete mix design','Soil consolidation','Timber seasoning'],answer:0,explanation:'Classification determines the usable bending stress distribution and section capacity.',source:S},
{id:'ch10-review-2',title:'LTB review',level:'core',kind:'retrieval',q:'What two motions define lateral-torsional buckling?',choices:['Lateral bending and twist','Axial shortening and no twist','Vertical deflection only','Local web yielding only'],answer:0,explanation:'LTB is the coupled lateral/torsional instability of an unrestrained beam.',source:S},
{id:'ch10-review-3',title:'Real beam review',level:'core',kind:'retrieval',q:'Name the type of effects that make real beam buckling resistance lower than ideal elastic theory.',choices:['Initial imperfections, residual stress and inelasticity','Higher steel density only','Perfect restraint','Zero initial curvature'],answer:0,explanation:'Real-member imperfections and early yielding are central reasons for calibrated design reductions.',source:S},
{id:'ch10-review-4',title:'Web review',level:'application',kind:'retrieval',q:'Which two local web failure ideas should be recalled for concentrated loads/reactions?',choices:['Web buckling and web crippling','LTB and fatigue only','Gross yielding and net rupture','Corrosion and fire'],answer:0,explanation:'Concentrated compression can cause either instability or local bearing/crippling failure of the web.',source:S},
{id:'ch10-review-5',title:'Special forms review',level:'application',kind:'classification',q:'Which beam form introduces repeated web openings and possible Vierendeel/web-post effects?',choices:['Castellated beam','Solid lintel only','Purlin only','Tie rod'],answer:0,explanation:'Castellated beams gain depth but require checks around their web openings.',source:S},
{id:'ch10-review-6',title:'Full chapter recall',level:'retrieval',kind:'concept',q:'Which single principle best connects the Chapter 10 review topics?',choices:['Beam design requires both load-path understanding and checks for all relevant limit states','Every beam is designed from one section-modulus equation','Stability is unrelated to restraint','Serviceability is optional'],answer:0,explanation:'The chapter integrates cross-section resistance, member stability, local behaviour and serviceability.',source:S}
]);
})();
