(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, Ch.13 source-grounded lesson';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('13:Introduction',[
{id:'ch13-intro-1',title:'Combined action',level:'foundation',kind:'concept',q:'Which loading combination defines the beam-column problem in Chapter 13?',choices:['Significant axial force together with bending','Pure shear only','Pure torsion only','Hydrostatic pressure only'],answer:0,explanation:'A beam-column carries meaningful axial force and bending at the same time.',source:S},
{id:'ch13-intro-2',title:'Source of bending',level:'foundation',kind:'classification',q:'Which situation can introduce bending into a column?',choices:['Load eccentricity','Perfectly concentric axial load in an ideal straight member only','Zero load','Uniform temperature with no restraint'],answer:0,explanation:'The chapter lists eccentricity among the practical sources of column bending.',source:S},
{id:'ch13-intro-3',title:'Frame action',level:'core',kind:'reasoning',q:'Why can a nominal “column” in a rigid frame behave as a beam-column?',choices:['Frame action can transfer end moments into the column','Columns cannot carry moment','Rigid frames eliminate bending','Only roof sheeting creates moment'],answer:0,explanation:'Frame continuity and joint action can impose bending moments on columns.',source:S},
{id:'ch13-intro-4',title:'Bracket effect',level:'application',kind:'concept',q:'A bracket applies a vertical load at an offset from the column centreline. What additional action does that offset create?',choices:['Bending moment','Pure axial force only','No structural effect','Only thermal strain'],answer:0,explanation:'An eccentric bracket load creates a moment in addition to axial force.',source:S},
{id:'ch13-intro-5',title:'Why interaction matters',level:'core',kind:'reasoning',q:'Why should compression and bending not be checked as unrelated actions in a beam-column?',choices:['They interact and can affect both strength and stability','They occur in different materials','Axial force always cancels bending','Bending has no effect on columns'],answer:0,explanation:'Beam-column behaviour is governed by combined force effects and stability interaction.',source:S},
{id:'ch13-intro-6',title:'Recognition',level:'retrieval',kind:'classification',q:'Which member is most clearly a beam-column?',choices:['A frame column carrying axial compression and end moments','A tension-only cable','A simply supported tie with no bending','A plate under uniform in-plane shear only'],answer:0,explanation:'The frame column has simultaneous axial and bending actions.',source:S}
]);
add('13:General Behaviour of Beam-columns',[
{id:'ch13-beh-1',title:'Beam and column traits',level:'foundation',kind:'concept',q:'Why is the term beam-column appropriate?',choices:['The member exhibits both beam-like bending and column-like axial/stability behaviour','It is always two members welded together','It carries no axial force','It is only a connection detail'],answer:0,explanation:'Its response combines bending behaviour with axial-load and buckling behaviour.',source:S},
{id:'ch13-beh-2',title:'Possible governing mode',level:'core',kind:'classification',q:'Which can govern a beam-column depending on slenderness and restraint?',choices:['In-plane buckling','Only concrete crushing','Only soil bearing','Only bolt slip'],answer:0,explanation:'The chapter identifies in-plane column buckling as one possible governing mechanism.',source:S},
{id:'ch13-beh-3',title:'Lateral stability',level:'core',kind:'concept',q:'When can lateral-torsional buckling become relevant to a beam-column?',choices:['When bending and insufficient lateral restraint permit lateral movement and twist','Only under pure tension','Only when no bending exists','Only in concrete columns'],answer:0,explanation:'Beam-column bending can interact with lateral-torsional instability.',source:S},
{id:'ch13-beh-4',title:'Stocky versus slender',level:'application',kind:'reasoning',q:'Compared with a stocky beam-column, what becomes more important as member slenderness increases?',choices:['Instability and buckling effects','Steel density','Paint colour','Thermal conductivity only'],answer:0,explanation:'Greater slenderness increases sensitivity to stability failure.',source:S},
{id:'ch13-beh-5',title:'Role of restraint',level:'application',kind:'reasoning',q:'How can improved lateral restraint change beam-column behaviour?',choices:['It can suppress an instability mode and increase usable strength','It always reduces strength','It removes axial load','It changes steel grade'],answer:0,explanation:'Restraint can delay lateral or torsional instability.',source:S},
{id:'ch13-beh-6',title:'Behaviour variables',level:'retrieval',kind:'classification',q:'Which group contains variables emphasized in beam-column behaviour?',choices:['Axial load, moment, slenderness and restraint','Paint, colour and humidity only','Concrete slump and curing age','Bolt head shape only'],answer:0,explanation:'These variables govern the interaction between strength, deformation and instability.',source:S}
]);
add('13:Second-order Moments in Beam-columns',[
{id:'ch13-so-1',title:'Member second-order effect',level:'foundation',kind:'concept',q:'What does the P-δ effect describe?',choices:['Axial load acting through the deflected shape of an individual member','Wind pressure on cladding','Bolt slip','Local plate corrosion'],answer:0,explanation:'P-δ is the member-level second-order moment caused by axial load acting through member curvature.',source:S},
{id:'ch13-so-2',title:'Frame second-order effect',level:'foundation',kind:'concept',q:'What does the P-Δ effect describe?',choices:['Axial load acting through overall frame or storey sway','Only local flange yielding','Shear lag in a tension plate','Thermal expansion of a beam'],answer:0,explanation:'P-Δ is the structure-level second-order effect associated with sway.',source:S},
{id:'ch13-so-3',title:'Moment relation',level:'core',kind:'formula',q:'Which simple product expresses the additional second-order moment created by axial load P acting through a lateral displacement?',choices:['PΔ','P/Δ','Δ/P','P+Δ'],answer:0,explanation:'The added moment is of the form axial force multiplied by lateral offset.',source:S},
{id:'ch13-so-4',title:'Magnitude trend',level:'application',kind:'reasoning',q:'If axial compression increases while the lateral displacement stays the same, what happens to the PΔ contribution?',choices:['It increases','It decreases to zero','It is unchanged','It becomes a shear force'],answer:0,explanation:'The second-order moment is proportional to the axial force for a given displacement.',source:S},
{id:'ch13-so-5',title:'Approaching instability',level:'core',kind:'reasoning',q:'Why do second-order effects become especially important near instability?',choices:['Deflections and moment magnification grow as stiffness degrades','Axial force disappears','The member becomes perfectly rigid','Moments automatically become zero'],answer:0,explanation:'Near instability, deformation-sensitive moment amplification becomes large.',source:S},
{id:'ch13-so-6',title:'Distinguish scales',level:'retrieval',kind:'classification',q:'Which pairing is correct?',choices:['P-δ: member curvature; P-Δ: frame sway','P-δ: corrosion; P-Δ: fatigue','P-δ: shear lag; P-Δ: block shear','P-δ: weld defect; P-Δ: bolt slip'],answer:0,explanation:'The notation separates local member and global frame second-order effects.',source:S}
]);
add('13:Elastic Torsional Buckling of Beam-columns',[
{id:'ch13-etb-1',title:'Added action',level:'foundation',kind:'concept',q:'What extra action is introduced when beam lateral-torsional buckling theory is extended to beam-columns?',choices:['Axial compressive force','Concrete prestress only','Hydrostatic pressure','Temperature load only'],answer:0,explanation:'Beam-column torsional buckling includes axial compression in addition to bending.',source:S},
{id:'ch13-etb-2',title:'Coupled deformation',level:'core',kind:'concept',q:'Which deformation pattern is associated with elastic torsional buckling of a beam-column?',choices:['Lateral deflection coupled with twist','Pure axial shortening only','Pure vertical translation with no twist','Only local bearing'],answer:0,explanation:'The instability couples lateral bending and torsion.',source:S},
{id:'ch13-etb-3',title:'Interaction idea',level:'core',kind:'reasoning',q:'Why can axial compression reduce the lateral-torsional stability of a bent member?',choices:['Compression participates in the instability and changes the elastic critical condition','Compression always braces the member','Compression removes bending','Compression increases torsional restraint automatically'],answer:0,explanation:'The axial force contributes to the coupled stability problem.',source:S},
{id:'ch13-etb-4',title:'Property dependence',level:'application',kind:'reasoning',q:'Why does elastic critical behaviour depend on bending-torsion section properties?',choices:['The mode involves both lateral flexure and twist','Only cross-sectional area matters','The member cannot twist','Steel density controls buckling alone'],answer:0,explanation:'The deformation mode requires both flexural and torsional resistance.',source:S},
{id:'ch13-etb-5',title:'Restraint effect',level:'application',kind:'concept',q:'What generally helps a beam-column resist lateral-torsional instability?',choices:['Effective lateral and torsional restraint','Longer unrestrained length','Greater initial twist','Removing all bracing'],answer:0,explanation:'Restraints suppress the lateral/twist mode.',source:S},
{id:'ch13-etb-6',title:'Mode recognition',level:'retrieval',kind:'classification',q:'Which statement best distinguishes elastic torsional buckling from simple in-plane buckling?',choices:['It includes twisting coupled with lateral displacement','It has no lateral movement','It occurs only after fracture','It is a connection slip mode'],answer:0,explanation:'Twist is a defining part of this coupled instability.',source:S}
]);
add('13:Interaction between Beam-column and Structure',[
{id:'ch13-int-1',title:'Frame restraint',level:'foundation',kind:'concept',q:'Why is a beam-column not always an isolated member problem?',choices:['Adjacent members provide restraint and affect stability','Steel density changes at joints','Only foundations carry moments','Columns cannot interact with beams'],answer:0,explanation:'The surrounding frame changes end restraint and stability response.',source:S},
{id:'ch13-int-2',title:'Effective length caution',level:'core',kind:'reasoning',q:'Why can a simple effective-length shortcut become awkward in a real frame?',choices:['Frame moment distribution and buckling restraint interact','Effective length changes steel chemistry','It eliminates all second-order effects','It applies only to tension members'],answer:0,explanation:'Member and system behaviour are coupled, so one isolated length factor may not capture all interactions.',source:S},
{id:'ch13-int-3',title:'Joint stiffness',level:'core',kind:'concept',q:'If adjoining beams become stiffer, what aspect of the column can change?',choices:['Its rotational restraint and stability behaviour','Its material density','Its yield stress automatically','Its thermal expansion coefficient'],answer:0,explanation:'Stiffer surrounding members can provide stronger rotational restraint.',source:S},
{id:'ch13-int-4',title:'System effect',level:'application',kind:'reasoning',q:'Why may first-order member moments be misleading near frame instability?',choices:['Second-order response can alter moment magnitude and distribution','Moments vanish near instability','Axial forces become zero','Connections stop transmitting forces'],answer:0,explanation:'Geometric nonlinearity can materially change the force pattern as instability is approached.',source:S},
{id:'ch13-int-5',title:'Member versus system',level:'application',kind:'classification',q:'Which check most clearly addresses a system-level issue rather than only local section strength?',choices:['Frame stability and second-order interaction','Gross section area only','Bolt diameter only','Paint thickness only'],answer:0,explanation:'System stability depends on the interaction of multiple members and restraints.',source:S},
{id:'ch13-int-6',title:'Design principle',level:'retrieval',kind:'concept',q:'What is the key lesson of beam-column/structure interaction?',choices:['Member stability can depend strongly on the surrounding frame','Every member can always be designed independently','Frame action has no effect on columns','Only connection strength matters'],answer:0,explanation:'The chapter emphasizes that beam-column and frame behaviour cannot always be separated cleanly.',source:S}
]);
add('13:Nominal Strength—Instability in the Plane of Bending',[
{id:'ch13-plane-1',title:'Nonlinear interaction',level:'foundation',kind:'concept',q:'Why is axial compression plus bending not treated by simple linear strength addition?',choices:['Their strength and stability interaction is nonlinear','Axial compression has no effect','Bending is always negligible','Steel is perfectly rigid'],answer:0,explanation:'Beam-column strength is an interaction problem, not two independent capacities.',source:S},
{id:'ch13-plane-2',title:'Imperfection effect',level:'core',kind:'reasoning',q:'How can initial crookedness reduce beam-column strength?',choices:['It creates bending from axial load even before additional transverse bending is considered','It removes moments','It raises stiffness automatically','It eliminates residual stress'],answer:0,explanation:'Axial load acting through an initial offset introduces additional bending.',source:S},
{id:'ch13-plane-3',title:'Residual stress',level:'core',kind:'reasoning',q:'Why do residual stresses matter for in-plane beam-column strength?',choices:['They can cause earlier yielding and stiffness reduction','They always increase Euler load','They make the member perfectly straight','They eliminate second-order effects'],answer:0,explanation:'Residual stress can trigger premature yielding in parts of the section.',source:S},
{id:'ch13-plane-4',title:'Moment magnification',level:'application',kind:'concept',q:'What does moment magnification represent in beam-column design?',choices:['Increase of bending demand due to second-order effects','Reduction of all applied moments to zero','Increase of material yield stress','Conversion of bending into shear only'],answer:0,explanation:'Second-order deformation amplifies the bending moment that must be resisted.',source:S},
{id:'ch13-plane-5',title:'Strength trend',level:'application',kind:'reasoning',q:'For the same section and bending pattern, what generally happens to available bending strength as compression becomes more severe?',choices:['The combined resistance margin reduces','It always increases','It is completely unchanged','Bending capacity becomes infinite'],answer:0,explanation:'Greater axial compression consumes more of the member resistance and worsens stability interaction.',source:S},
{id:'ch13-plane-6',title:'Key ingredients',level:'retrieval',kind:'classification',q:'Which group belongs in an in-plane beam-column strength assessment?',choices:['Axial force, bending, imperfections and second-order effects','Only paint and corrosion','Only bolt spacing','Only temperature'],answer:0,explanation:'These are central to the nominal in-plane interaction problem.',source:S}
]);
add('13:Beam-column under Biaxial Loading',[
{id:'ch13-biax-1',title:'Biaxial definition',level:'foundation',kind:'concept',q:'What makes beam-column loading biaxial?',choices:['Bending acts about both principal axes together with axial force','Only one bending moment acts','Only torsion acts','Only shear acts'],answer:0,explanation:'Biaxial loading combines major- and minor-axis bending with axial force.',source:S},
{id:'ch13-biax-2',title:'Three-dimensional demand',level:'core',kind:'reasoning',q:'Why is biaxial beam-column behaviour common in real buildings?',choices:['Three-dimensional frames can transfer moments about both axes','Buildings carry loads in only one plane','Columns cannot bend about minor axes','Axial force prevents biaxial bending'],answer:0,explanation:'Spatial framing and eccentric actions can produce moments about both principal axes.',source:S},
{id:'ch13-biax-3',title:'Interaction surface',level:'core',kind:'concept',q:'What does a three-dimensional beam-column interaction surface represent?',choices:['Permissible combinations of normalized axial force and moments about two axes','Only the steel stress-strain curve','Only bolt-group geometry','Only support reactions'],answer:0,explanation:'The surface expresses combined capacity in axial force and two bending dimensions.',source:S},
{id:'ch13-biax-4',title:'Stocky member behaviour',level:'application',kind:'reasoning',q:'Compared with a very slender member, what is more likely in a stocky beam-column before failure?',choices:['Substantial section yielding','Immediate elastic buckling at tiny load','No deformation','Only torsional fracture'],answer:0,explanation:'Stockier members can develop more material yielding before instability governs.',source:S},
{id:'ch13-biax-5',title:'Slender member behaviour',level:'application',kind:'reasoning',q:'What becomes more influential in a slender biaxially loaded beam-column?',choices:['Buckling and second-order effects','Paint thickness','Concrete shrinkage only','Bolt hole diameter only'],answer:0,explanation:'Slenderness increases sensitivity to instability.',source:S},
{id:'ch13-biax-6',title:'Demand recognition',level:'retrieval',kind:'classification',q:'Which action set is a biaxial beam-column case?',choices:['P, Mx and My','Only P','Only Mx','Only V'],answer:0,explanation:'Biaxial beam-column demand contains axial force and moments about both principal axes.',source:S}
]);
add('13:Interaction Equations for Local Capacity Check',[
{id:'ch13-local-1',title:'Local versus overall',level:'foundation',kind:'concept',q:'Why is a local section-capacity check still required when overall buckling has been checked?',choices:['A cross-section can reach its combined axial-and-bending capacity locally before overall instability governs','Overall buckling automatically proves every section safe','Local yielding cannot occur in steel','Buckling checks include all connection details'],answer:0,explanation:'Local cross-section capacity and overall member stability are distinct limit states.',source:S},
{id:'ch13-local-2',title:'Critical section',level:'core',kind:'concept',q:'Where should the local interaction check be made?',choices:['Where the combined axial force and bending demand is greatest','Only at mid-depth of the web','Only at the foundation regardless of moment','At a random section'],answer:0,explanation:'The most highly demanded section controls the local capacity check.',source:S},
{id:'ch13-local-3',title:'Interior maximum',level:'application',kind:'reasoning',q:'Why might the critical local section occur inside the member rather than at an end?',choices:['Transverse loading can create an interior maximum moment','Axial force is zero inside the member','End moments never exist','Interior sections have different steel grade'],answer:0,explanation:'A transverse load can shift the peak bending demand away from the ends.',source:S},
{id:'ch13-local-4',title:'Normalized interaction',level:'core',kind:'concept',q:'What is the basic role of terms such as applied axial force divided by axial capacity and moment divided by moment capacity?',choices:['Express how much of each resistance is being used in an interaction check','Calculate steel density','Determine support settlement','Replace all stability analysis'],answer:0,explanation:'Normalized demand/capacity terms allow combined actions to be assessed together.',source:S},
{id:'ch13-local-5',title:'Section class effect',level:'application',kind:'reasoning',q:'Why can the form of a local interaction equation depend on cross-section class?',choices:['Section class controls the usable stress distribution and section capacity','Section class changes span length','Section class changes load factors','Section class removes axial force'],answer:0,explanation:'Plastic, compact, semi-compact and slender behaviour affects available local resistance.',source:S},
{id:'ch13-local-6',title:'Check purpose',level:'retrieval',kind:'classification',q:'A local interaction equation primarily checks which failure family?',choices:['Cross-section capacity under combined axial force and bending','Foundation settlement','Fire insulation loss','Fatigue crack growth only'],answer:0,explanation:'It verifies the section itself under combined actions.',source:S}
]);
add('13:Code Design Procedures',[
{id:'ch13-code-1',title:'Two-part procedure',level:'foundation',kind:'classification',q:'Which pair of checks does the Chapter 13 IS 800 procedure require?',choices:['Local capacity and overall buckling','Only fatigue and fire','Only deflection and vibration','Only weld and bolt strength'],answer:0,explanation:'The textbook identifies both section capacity and member stability checks.',source:S},
{id:'ch13-code-2',title:'Moment input',level:'core',kind:'concept',q:'What kind of moments should be used in a beam-column code check?',choices:['Moments that include second-order amplification where relevant','Only unamplified first-order moments in every case','Zero moments','Only self-weight moments'],answer:0,explanation:'Second-order effects must be reflected directly or by amplification.',source:S},
{id:'ch13-code-3',title:'Analysis route',level:'core',kind:'reasoning',q:'How can second-order moments be obtained for code design?',choices:['From direct second-order analysis or by permitted amplification of first-order moments','Only from material tests','Only from wind-tunnel tests','By ignoring frame sway'],answer:0,explanation:'The chapter describes both direct and amplified first-order approaches.',source:S},
{id:'ch13-code-4',title:'Why two checks',level:'application',kind:'reasoning',q:'Why does a satisfactory local-capacity check not eliminate the need for an overall buckling check?',choices:['A member may be locally strong yet globally unstable','Local strength always controls','Buckling occurs only in plates','Overall instability is a serviceability issue only'],answer:0,explanation:'Section resistance and overall stability are separate limit states.',source:S},
{id:'ch13-code-5',title:'Interaction format',level:'application',kind:'concept',q:'Why do modern beam-column codes commonly use interaction equations?',choices:['They provide a practical format for combined axial and bending utilization','They eliminate the need for section properties','They apply only to pure beams','They replace load combinations'],answer:0,explanation:'Interaction equations combine multiple demand-to-capacity effects in a usable design form.',source:S},
{id:'ch13-code-6',title:'Code mindset',level:'retrieval',kind:'concept',q:'Which statement best summarizes the code procedure described in the chapter?',choices:['Use appropriate second-order demand, then verify both section capacity and member stability','Check only first yield','Ignore restraint and slenderness','Check only one principal axis'],answer:0,explanation:'The procedure integrates amplified demand with local and global resistance checks.',source:S}
]);
add('13:Design of Beam-columns',[
{id:'ch13-design-1',title:'Trial section',level:'foundation',kind:'concept',q:'What is the first practical step in the chapter beam-column design workflow?',choices:['Select a trial section','Assume every section is safe','Ignore the axial force','Design the base plate first in every case'],answer:0,explanation:'Beam-column design is iterative and begins with a trial section.',source:S},
{id:'ch13-design-2',title:'Section classification',level:'core',kind:'reasoning',q:'Why is cross-section class determined during beam-column design?',choices:['It affects the usable local axial and bending capacities','It fixes the applied load','It determines building height','It replaces buckling analysis'],answer:0,explanation:'Section class governs how much section strength can be mobilized.',source:S},
{id:'ch13-design-3',title:'Axis checks',level:'core',kind:'classification',q:'For a biaxial beam-column, which bending resistances are relevant?',choices:['Resistance about both principal axes','Major-axis resistance only in every case','Minor-axis resistance only','No bending resistance'],answer:0,explanation:'Biaxial loading requires major- and minor-axis bending capacities.',source:S},
{id:'ch13-design-4',title:'Compression check',level:'application',kind:'reasoning',q:'Why is compression resistance evaluated separately from bending resistance before applying interaction equations?',choices:['The interaction needs the relevant component capacities as reference resistances','Compression never affects bending','It is only for calculating self-weight','It replaces section classification'],answer:0,explanation:'Interaction checks use the available axial and bending resistances.',source:S},
{id:'ch13-design-5',title:'Iteration',level:'application',kind:'concept',q:'What should be done if the interaction result for a trial section is unsafe?',choices:['Select another section and repeat the checks','Ignore the interaction equation','Reduce the calculated load without justification','Mark the member complete'],answer:0,explanation:'The chapter explicitly treats the process as trial-and-error iteration.',source:S},
{id:'ch13-design-6',title:'Workflow recall',level:'retrieval',kind:'sequence',q:'Which sequence best matches the Chapter 13 design approach?',choices:['Trial section → properties/class → strengths/stability → interaction check → revise if needed','Paint → weld → ignore loads → finish','Base plate → concrete slump → steel density','Choose depth only → accept'],answer:0,explanation:'The workflow combines section selection, capacity, stability and interaction checks iteratively.',source:S}
]);
add('13:Beam-columns Subjected to Tension and Bending',[
{id:'ch13-tb-1',title:'Source of bending in tension member',level:'foundation',kind:'classification',q:'Which can cause bending in a tension member?',choices:['Connection eccentricity','Perfect concentricity with no transverse load','Zero gravity','No load'],answer:0,explanation:'The chapter lists connection eccentricity, self-weight and transverse loading as sources of bending.',source:S},
{id:'ch13-tb-2',title:'Tension effect',level:'core',kind:'reasoning',q:'How does axial tension tend to affect the primary bending moment?',choices:['It tends to reduce it','It magnifies it like compression','It always doubles it','It has no mechanical interaction'],answer:0,explanation:'The chapter contrasts tension with compression: tension tends to reduce primary bending.',source:S},
{id:'ch13-tb-3',title:'Secondary bending',level:'core',kind:'concept',q:'Why can secondary bending due to tension be conservatively neglected in the textbook treatment?',choices:['The tensile force tends to reduce rather than magnify the primary bending effect','Tension creates no stress','Tension makes the member rigid','Bending capacity becomes infinite'],answer:0,explanation:'The stabilizing direction of the tensile second-order effect makes neglect conservative in the cited treatment.',source:S},
{id:'ch13-tb-4',title:'Local capacity remains',level:'application',kind:'reasoning',q:'Does axial tension remove the need for a combined local-capacity check with bending?',choices:['No','Yes, always','Only for steel grades above a fixed value','Only if the member is painted'],answer:0,explanation:'The member must still satisfy combined section-capacity requirements.',source:S},
{id:'ch13-tb-5',title:'Lateral stability remains',level:'application',kind:'concept',q:'Can lateral-torsional buckling still require consideration in a member under tension plus bending?',choices:['Yes, where the bending and restraint conditions make it relevant','No, tension makes LTB impossible in every case','Only in concrete members','Only when axial force is zero'],answer:0,explanation:'The chapter retains an LTB check using an effective bending moment where applicable.',source:S},
{id:'ch13-tb-6',title:'Contrast with compression',level:'retrieval',kind:'classification',q:'Which statement correctly contrasts axial tension and compression in second-order bending?',choices:['Compression tends to magnify bending; tension tends to reduce it','Both always magnify equally','Tension always causes buckling','Compression always eliminates bending'],answer:0,explanation:'This contrast is central to the textbook treatment.',source:S}
]);
add('13:Crane Columns',[
{id:'ch13-crane-1',title:'Industrial role',level:'foundation',kind:'concept',q:'What additional structural function distinguishes a crane column from an ordinary building column?',choices:['It supports crane-related loads in addition to building loads','It carries only roof sheeting','It carries no axial force','It is always a tension member'],answer:0,explanation:'Crane columns carry roof/building actions plus crane vertical and horizontal effects.',source:S},
{id:'ch13-crane-2',title:'Uniform bracket arrangement',level:'foundation',kind:'classification',q:'Which arrangement uses a bracket attached to a generally uniform column to support the gantry girder?',choices:['Uniform column with bracket','Stepped column only','Cable mast','Concrete wall'],answer:0,explanation:'The chapter shows a uniform column with a bracket as one common arrangement.',source:S},
{id:'ch13-crane-3',title:'Stepped column',level:'core',kind:'concept',q:'Why is the lower portion of a stepped crane column made heavier?',choices:['It must resist the larger combined crane and building actions below the crane level','To reduce all moments to zero','To avoid carrying axial force','Only for appearance'],answer:0,explanation:'The lower part carries more severe combined actions and is therefore strengthened.',source:S},
{id:'ch13-crane-4',title:'Separate columns',level:'core',kind:'classification',q:'What is the third crane-column arrangement described in the chapter?',choices:['Separate building and crane columns tied together','A tension cable only','A timber truss leg','A concrete pile'],answer:0,explanation:'The textbook presents separate building and crane columns connected together.',source:S},
{id:'ch13-crane-5',title:'Eccentric action',level:'application',kind:'reasoning',q:'Why can crane loads create substantial bending in the supporting column?',choices:['Vertical and horizontal crane actions often act with eccentricity','Crane loads are always concentric','Crane loads contain no horizontal force','Columns cannot transmit moments'],answer:0,explanation:'Eccentric load paths and horizontal crane actions produce bending moments.',source:S},
{id:'ch13-crane-6',title:'Load set',level:'retrieval',kind:'classification',q:'Which load set belongs in crane-column design?',choices:['Roof reaction plus crane vertical and horizontal actions','Only dead load of paint','Only temperature','Only self-weight of bolts'],answer:0,explanation:'The crane column must combine building and crane actions.',source:S}
]);
add('13:Design of Eccentrically Loaded Base Plates',[
{id:'ch13-base-1',title:'Actions transferred',level:'foundation',kind:'classification',q:'Which actions can an eccentrically loaded column base transfer to the foundation?',choices:['Axial force, shear and moment','Only temperature','Only torsion with no force','Only self-weight of the plate'],answer:0,explanation:'The chapter treats bases carrying axial load, shear and moment.',source:S},
{id:'ch13-base-2',title:'Full compression',level:'core',kind:'concept',q:'When can the base remain in compression over the full plate area?',choices:['When axial compression is sufficiently large relative to the moment','Whenever moment is dominant','Only when axial force is zero','Only when anchors are absent'],answer:0,explanation:'A high enough compressive resultant can keep the contact pressure compressive across the plate.',source:S},
{id:'ch13-base-3',title:'Partial compression',level:'core',kind:'reasoning',q:'What happens when the moment is large relative to axial compression?',choices:['Only part of the plate may remain in compression while anchors take tension','The entire plate remains uniformly compressed in every case','All contact pressure vanishes','The foundation carries no load'],answer:0,explanation:'Large eccentricity can create uplift on part of the base, requiring anchor tension.',source:S},
{id:'ch13-base-4',title:'Anchor role',level:'application',kind:'concept',q:'What is the principal role of holding-down or anchor bolts when part of the base tends to lift?',choices:['Resist tension','Carry only concrete compression','Eliminate all shear automatically','Increase steel yield strength'],answer:0,explanation:'Anchors resist the tensile component created by overturning moment.',source:S},
{id:'ch13-base-5',title:'Horizontal shear',level:'application',kind:'classification',q:'Which device may be used when substantial horizontal shear must be transferred at the base?',choices:['Shear key or lug','Plastic hinge','Roof purlin','Tension rod above the roof'],answer:0,explanation:'The chapter identifies a shear key/lug as a way to transfer significant horizontal force.',source:S},
{id:'ch13-base-6',title:'Contact pattern',level:'retrieval',kind:'concept',q:'What mainly determines whether the concrete bearing contact is full-area or partial?',choices:['The relative magnitude of axial compression and moment','Paint colour','Steel density','Bolt head shape'],answer:0,explanation:'The resultant eccentricity from P and M controls the contact-pressure pattern.',source:S}
]);
add('13:Examples',[
{id:'ch13-ex-1',title:'Example purpose',level:'foundation',kind:'concept',q:'What is the purpose of the Chapter 13 worked examples?',choices:['Apply combined axial, bending and stability checks to practical members','Calculate only steel density','Study only corrosion','Avoid design interaction'],answer:0,explanation:'The examples demonstrate the complete combined-action workflow.',source:S},
{id:'ch13-ex-2',title:'Factored actions',level:'core',kind:'sequence',q:'Before checking interaction equations in a worked beam-column example, what must be established?',choices:['The relevant design actions and section properties','Paint system only','Concrete curing time only','Weld colour'],answer:0,explanation:'Interaction checks require factored demands and member capacities.',source:S},
{id:'ch13-ex-3',title:'Second-order step',level:'core',kind:'reasoning',q:'Why may a worked example amplify moments before the final interaction check?',choices:['To include second-order effects','To change the steel grade','To remove axial load','To avoid buckling checks'],answer:0,explanation:'The design moments should reflect geometric second-order response where relevant.',source:S},
{id:'ch13-ex-4',title:'Biaxial example',level:'application',kind:'classification',q:'Which capacities are needed for an example with compression plus major- and minor-axis moments?',choices:['Compression resistance and bending resistance about both axes','Only major-axis bending resistance','Only shear resistance','Only tension resistance'],answer:0,explanation:'Biaxial interaction requires axial and both bending resistances.',source:S},
{id:'ch13-ex-5',title:'Crane example',level:'application',kind:'reasoning',q:'Why is a crane-column example a useful beam-column application?',choices:['It naturally combines axial force, eccentric vertical load and horizontal actions','It is a pure tension problem','It contains no moments','It has no stability issues'],answer:0,explanation:'Crane columns are practical combined-action members.',source:S},
{id:'ch13-ex-6',title:'Base example',level:'retrieval',kind:'concept',q:'What additional design issue appears in an eccentrically loaded base example beyond member interaction?',choices:['Concrete bearing/contact and anchor tension or shear transfer','Only roof deflection','Only fatigue of a cable','Only corrosion allowance'],answer:0,explanation:'The base must transfer the combined column actions into the foundation.',source:S}
]);
add('13:Summary',[
{id:'ch13-sum-1',title:'Sources of bending recall',level:'foundation',kind:'classification',q:'Which is a source of column bending summarized in Chapter 13?',choices:['Eccentric axial load','Only concentric axial load in an ideal member','Zero load','Uniform corrosion'],answer:0,explanation:'Eccentricity is one of several practical sources of bending in columns.',source:S},
{id:'ch13-sum-2',title:'Behaviour factor',level:'core',kind:'classification',q:'Which factor affects beam-column behaviour according to the chapter summary?',choices:['Moment distribution','Paint colour only','Concrete slump only','Bolt coating only'],answer:0,explanation:'Moment distribution is explicitly among the behaviour-controlling variables.',source:S},
{id:'ch13-sum-3',title:'Stability factor',level:'core',kind:'reasoning',q:'Why does member length matter in beam-column behaviour?',choices:['It influences slenderness and stability sensitivity','It changes steel chemistry','It removes moments','It fixes the load factor'],answer:0,explanation:'Longer effective lengths generally increase instability sensitivity.',source:S},
{id:'ch13-sum-4',title:'Bracing factor',level:'application',kind:'reasoning',q:'Why is lateral bracing included in the summary of beam-column behaviour?',choices:['It can restrain lateral instability and change member strength','It only supports paint','It increases axial load by definition','It has no structural role'],answer:0,explanation:'Lateral restraint directly affects possible buckling modes.',source:S},
{id:'ch13-sum-5',title:'Key design tools',level:'application',kind:'classification',q:'Which pair is central to the chapter summary?',choices:['Second-order effects and interaction equations','Only density and temperature','Only fatigue and fire','Only bolts and welds'],answer:0,explanation:'The chapter centers on amplified combined actions and interaction-based design.',source:S},
{id:'ch13-sum-6',title:'Scope recall',level:'retrieval',kind:'classification',q:'Which special applications are explicitly included in Chapter 13?',choices:['Crane columns and eccentrically loaded base plates','Timber trusses and masonry walls','Prestressed concrete tanks only','Soil retaining walls only'],answer:0,explanation:'Both are included as practical beam-column-related applications.',source:S}
]);
add('13:Exercises',[
{id:'ch13-exer-1',title:'Core exercise skill',level:'foundation',kind:'concept',q:'What is the main skill tested by the Chapter 13 exercises?',choices:['Complete combined-action design and checking','Only formula memorization','Only steel density calculation','Only connection sketching'],answer:0,explanation:'The exercises require full beam-column selection and verification.',source:S},
{id:'ch13-exer-2',title:'Alternative section',level:'core',kind:'reasoning',q:'Why might an exercise ask for redesign using a different built-up section?',choices:['To compare how section properties alter interaction and stability checks','To avoid calculations','To change the load combination','To eliminate bending'],answer:0,explanation:'Different section geometry changes capacities and stability response.',source:S},
{id:'ch13-exer-3',title:'Biaxial task',level:'core',kind:'classification',q:'Which exercise most directly tests three-dimensional beam-column interaction?',choices:['Design under axial compression with moments about both principal axes','Pure axial tension only','Pure shear plate design','Paint selection'],answer:0,explanation:'Biaxial bending plus axial force is the 3D interaction case.',source:S},
{id:'ch13-exer-4',title:'Crane-column task',level:'application',kind:'reasoning',q:'What makes a crane-column exercise more than a simple column check?',choices:['It combines building and crane actions with eccentric bending effects','It contains no axial force','It contains only self-weight','It ignores stability'],answer:0,explanation:'Crane columns carry combined and often eccentric actions.',source:S},
{id:'ch13-exer-5',title:'Base-plate task',level:'application',kind:'concept',q:'Which additional component may need design in an eccentrically loaded base-plate exercise when shear is large?',choices:['Shear lug or key','Plastic hinge in the roof','Purlin','Tension cable'],answer:0,explanation:'A shear key/lug can transfer substantial horizontal force.',source:S},
{id:'ch13-exer-6',title:'Workflow retrieval',level:'retrieval',kind:'sequence',q:'What should a complete exercise solution demonstrate?',choices:['Actions → section properties → second-order/stability checks → interaction → detailing/base checks as relevant','Only final section size','Only load calculation','Only steel grade'],answer:0,explanation:'The exercises are intended to practise the entire interaction-based design process.',source:S}
]);
add('13:Review Questions',[
{id:'ch13-rev-1',title:'Definition recall',level:'foundation',kind:'concept',q:'What is a beam-column?',choices:['A member subjected to significant axial force and bending','A pure beam with zero axial force','A pure tie','A plate girder web'],answer:0,explanation:'This is the foundational definition reviewed by the chapter.',source:S},
{id:'ch13-rev-2',title:'Bending source recall',level:'foundation',kind:'classification',q:'Which can generate moment in a column?',choices:['Portal-frame action','Perfectly concentric isolated axial load only','Zero deformation','No load'],answer:0,explanation:'Frame action is one of the listed sources of column bending.',source:S},
{id:'ch13-rev-3',title:'Second-order recall',level:'core',kind:'classification',q:'Which pair should you recall when reviewing geometric second-order effects?',choices:['P-δ and P-Δ','Gross yield and block shear','Fire and fatigue','Bearing and slip'],answer:0,explanation:'The chapter separates member and frame second-order effects using these symbols.',source:S},
{id:'ch13-rev-4',title:'Interaction recall',level:'core',kind:'reasoning',q:'Why are interaction equations required in beam-column design?',choices:['Axial force and bending share the available member resistance','Axial force and bending are always independent','They calculate steel density','They replace analysis'],answer:0,explanation:'Combined actions must be evaluated together against available capacity.',source:S},
{id:'ch13-rev-5',title:'Code recall',level:'application',kind:'classification',q:'What two design levels should be remembered for the code procedure?',choices:['Local section capacity and overall member buckling','Only local weld and bolt checks','Only fire and fatigue','Only serviceability and aesthetics'],answer:0,explanation:'The code procedure requires both local and overall checks.',source:S},
{id:'ch13-rev-6',title:'Practical scope recall',level:'retrieval',kind:'classification',q:'Which pair of practical topics rounds out the chapter review scope?',choices:['Crane columns and eccentrically loaded base plates','Timber beams and masonry arches','Prestressed slabs and soil anchors','Composite decks and cable nets'],answer:0,explanation:'These are explicit practical applications in Chapter 13.',source:S}
]);
})();
