(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, supplementary Ch.20 Fire-resistant Design';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('16:Introduction',[
{id:'ch16-intro-1',title:'Steel and fire',level:'foundation',kind:'concept',q:'Which statement best describes structural steel in a building fire?',choices:['Steel is non-combustible but can lose strength and stiffness as temperature rises','Steel burns like timber at room temperature','Steel gains unlimited strength when heated','Fire affects only the paint and never the structure'],answer:0,explanation:'The fire problem is not combustion of steel; it is the deterioration of structural properties at elevated temperature.',source:S},
{id:'ch16-intro-2',title:'Fire-safety objective',level:'foundation',kind:'reasoning',q:'What is a principal structural aim of fire-resistant design?',choices:['Prevent premature collapse for the required fire exposure period','Keep every steel surface exactly at room temperature','Guarantee zero deformation in any fire','Replace evacuation planning with member design'],answer:0,explanation:'The chapter focuses on maintaining structural integrity long enough to satisfy the prescribed fire-resistance requirement.',source:S},
{id:'ch16-intro-3',title:'Why not concrete encasement always?',level:'core',kind:'reasoning',q:'Why did the chapter discuss alternatives to traditional concrete encasement of steel?',choices:['Concrete encasement adds dead weight and can slow construction','Concrete has no thermal mass','Concrete always increases steel temperature','Encasement cannot surround columns'],answer:0,explanation:'The source notes added dead load, larger foundations and construction-time disadvantages of concrete encasement.',source:S},
{id:'ch16-intro-4',title:'Modern protection options',level:'core',kind:'classification',q:'Which is a fire-protection option introduced for structural steel?',choices:['Intumescent coating','Removing all fire exits','Increasing combustible contents','Reducing member stability'],answer:0,explanation:'The chapter introduces sprays, boards, intumescent coatings and other protection systems.',source:S},
{id:'ch16-intro-5',title:'Design target',level:'application',kind:'reasoning',q:'A steel member becomes hot during fire but still carries the required fire-design action for the specified period. What does this illustrate?',choices:['Fire design is about adequate structural performance, not necessarily keeping steel cold','Any temperature rise means automatic failure','Steel must remain elastic at room-temperature properties','Protection is successful only if temperature never changes'],answer:0,explanation:'The target is adequate resistance for the required exposure, accounting for reduced properties at temperature.',source:S},
{id:'ch16-intro-6',title:'Traditional code focus',level:'retrieval',kind:'concept',q:'Traditional fire regulations described in the chapter are primarily concerned with which outcome?',choices:['Avoiding premature collapse, enabling evacuation and limiting fire spread','Preventing all cosmetic damage','Guaranteeing reuse without inspection','Maintaining room temperature everywhere'],answer:0,explanation:'Traditional requirements focus mainly on life safety, structural stability and containment rather than preventing all property damage.',source:S}
]);
add('16:Fire Research',[
{id:'ch16-research-1',title:'Fire as reaction',level:'foundation',kind:'concept',q:'The chapter describes fire primarily as what type of chemical process?',choices:['An exothermic oxidation reaction that releases heat','An endothermic reaction that always cools the room','A purely mechanical vibration','A corrosion process with no heat release'],answer:0,explanation:'Fire is described as an exothermic chemical reaction, essentially oxidation of hydrocarbons.',source:S},
{id:'ch16-research-2',title:'Factors controlling fire',level:'core',kind:'classification',q:'Which factor can materially influence compartment-fire temperature and development?',choices:['Window opening area','Steel section colour only','Bolt thread pitch only','Column base grout thickness only'],answer:0,explanation:'Ventilation/openings are among the factors affecting the magnitude and distribution of fire.',source:S},
{id:'ch16-research-3',title:'Three fire phases',level:'core',kind:'sequence',q:'Which sequence matches the compartment-fire phases in the chapter?',choices:['Growth/pre-flashover → fully developed/post-flashover → decay','Decay → ignition → no heating','Fully developed → pre-flashover → ignition','Only one constant-temperature phase'],answer:0,explanation:'The source divides compartment fire into growth, fully developed and decay phases.',source:S},
{id:'ch16-research-4',title:'Pre-flashover concern',level:'core',kind:'reasoning',q:'Why is the pre-flashover phase especially important for people even though it may not govern structural heating?',choices:['It is critical for evacuation and fire-fighting while toxic gases can be produced','It always gives maximum steel temperature','It occurs after all fuel is consumed','It contains no smoke or heat'],answer:0,explanation:'The source notes that the early phase is especially important for evacuation and fire-fighting.',source:S},
{id:'ch16-research-5',title:'Decay still matters',level:'application',kind:'reasoning',q:'Why can the decay phase still matter to insulated or low-section-factor steel members?',choices:['Stored heat can continue flowing into the steel even while room temperature falls','Heat transfer stops immediately at the start of decay','Insulation generates no thermal lag','Steel instantly returns to ambient temperature'],answer:0,explanation:'The chapter notes that member temperature can continue rising during decay because of thermal lag.',source:S},
{id:'ch16-research-6',title:'Fully developed phase',level:'retrieval',kind:'concept',q:'Which fire phase generally produces the largest flame and highest rate of heating?',choices:['Fully developed post-flashover phase','Pre-ignition phase','After complete cooling','Before fuel is present'],answer:0,explanation:'The fully developed phase is associated with the greatest heating and most structural damage.',source:S}
]);
add('16:Design Curves and Fire Models',[
{id:'ch16-curves-1',title:'Design-fire meaning',level:'foundation',kind:'concept',q:'What does a design fire describe?',choices:['The relationship of fire temperature with time and, where relevant, space','Only the steel yield stress at room temperature','Only the building height','Only the evacuation route'],answer:0,explanation:'The chapter defines a design fire in terms of temperature, time and possibly spatial variation.',source:S},
{id:'ch16-curves-2',title:'Nominal versus natural',level:'core',kind:'classification',q:'What distinguishes a natural or parametric fire model from a nominal fire curve?',choices:['It uses physical inputs such as fire load, openings and enclosure properties','It contains no physical parameters by definition','It is always a straight line','It ignores ventilation completely'],answer:0,explanation:'Parametric models incorporate physical features of the compartment and fuel load.',source:S},
{id:'ch16-curves-3',title:'ISO 834 equation',level:'core',kind:'formula',q:'Which expression is the ISO 834 standard temperature-time relationship given in the chapter?',choices:['Tf−To=345 log(8t+1)','Tf−To=8t/345','Tf=To−345t','Tf−To=345/t'],answer:0,explanation:'The source gives Tf−To = 345 log(8t+1), with t in minutes.',math:'T_f-T_o=345\\log(8t+1)',source:S},
{id:'ch16-curves-4',title:'Nominal-curve limitation',level:'core',kind:'reasoning',q:'Why should the ISO 834 curve not be interpreted as the exact temperature history of every real fire?',choices:['It is a standardized furnace-test exposure used mainly for comparison','It includes every room geometry and fuel layout exactly','It always includes a realistic cooling phase','It is derived from one unique building'],answer:0,explanation:'Nominal curves are standardized test curves, not universal simulations of real fires.',source:S},
{id:'ch16-curves-5',title:'Fire-load definition',level:'application',kind:'concept',q:'What does fire load represent in a compartment?',choices:['The maximum heat potentially released by combustible contents, usually per unit floor area','The self-weight of structural steel only','The live load used for floor deflection','The number of fire exits'],answer:0,explanation:'Fire load is based on combustible mass and calorific value and is commonly expressed per unit floor area.',source:S},
{id:'ch16-curves-6',title:'Wood equivalent',level:'retrieval',kind:'numerical',q:'The chapter states that 1 kg of wood is approximately equivalent to how much heat release?',choices:['18 MJ','1.8 MJ','180 MJ','0.18 MJ'],answer:0,explanation:'The source uses approximately 18 MJ as the heat equivalent of 1 kg of wood.',source:S}
]);
add('16:Fire Engineering Design Problems',[
{id:'ch16-problems-1',title:'Broad fire-engineering concerns',level:'foundation',kind:'classification',q:'Which is one of the broad fire-engineering problems listed in the chapter?',choices:['Structural integrity','Only paint selection','Only foundation settlement','Only corrosion allowance'],answer:0,explanation:'The chapter lists structural integrity among occupant protection, movement, life support, communications and fire protection.',source:S},
{id:'ch16-problems-2',title:'Prevention versus protection',level:'core',kind:'concept',q:'What is the difference between fire prevention and fire protection in the chapter?',choices:['Prevention reduces the chance of fire starting; protection mitigates effects after fire occurs','They are exactly the same term','Protection means only painting steel','Prevention begins only after flashover'],answer:0,explanation:'The chapter separates reducing ignition likelihood from measures that limit consequences after ignition.',source:S},
{id:'ch16-problems-3',title:'Active system',level:'core',kind:'classification',q:'Which item is an active fire-protection system?',choices:['Fire detection and alarm','Board encasement','Concrete encasement','Passive thermal shielding'],answer:0,explanation:'Active protection includes detection, alarms, extinguishing systems and smoke control.',source:S},
{id:'ch16-problems-4',title:'Passive system',level:'core',kind:'classification',q:'Which item is a passive fire-protection measure?',choices:['Structural fire protection around steelwork','Portable extinguisher operation','Automatic alarm signal','Fire-hydrant pumping'],answer:0,explanation:'Passive protection includes structural protection and measures that resist spread or collapse without active operation.',source:S},
{id:'ch16-problems-5',title:'Sprinkler trade-off',level:'application',kind:'reasoning',q:'Why can effective active systems influence the required passive fire resistance in some codes?',choices:['They can reduce the severity or likelihood of a fully developed fire, although the source notes they do not justify total elimination of fire resistance','They make steel properties temperature-independent','They remove gravity load from the building','They stop heat conduction through steel completely'],answer:0,explanation:'The chapter discusses partial trade-offs where sprinklers are installed, not complete removal of structural fire requirements.',source:S},
{id:'ch16-problems-6',title:'Steel still needs protection',level:'retrieval',kind:'reasoning',q:'Why may passive protection be necessary even though steel is incombustible?',choices:['High temperature can substantially reduce yield strength and elastic modulus','Steel begins to burn at ordinary room temperature','Steel has no thermal conductivity','Fire removes all structural actions'],answer:0,explanation:'Loss of mechanical properties, not combustibility, drives the structural fire concern.',source:S}
]);
add('16:Fire Engineering Design of Steel Structures',[
{id:'ch16-eng-1',title:'FRL meaning',level:'foundation',kind:'concept',q:'What does the required fire resistance level (FRL) specify?',choices:['A required duration of standard-fire resistance without collapse','The annual probability of wind','The corrosion rate of steel','The normal service life in years'],answer:0,explanation:'FRL is specified as a fire-resistance duration, usually in minutes or hours.',source:S},
{id:'ch16-eng-2',title:'FRL dependence',level:'core',kind:'reasoning',q:'According to the chapter, what influences the required FRL?',choices:['Building use and evacuation time','Only steel density','Only beam span','Only paint colour'],answer:0,explanation:'Occupancy/use and the time required for evacuation are among the governing considerations.',source:S},
{id:'ch16-eng-3',title:'PSA versus FRL',level:'core',kind:'comparison',q:'Which statement correctly distinguishes PSA from FRL?',choices:['FRL is the required duration; PSA is the member’s achieved structural-adequacy time','PSA is always a load factor and FRL is a steel grade','They are identical to yield and ultimate strength','FRL is measured in MPa and PSA in mm'],answer:0,explanation:'The design requirement is FRL; the member performance measure is PSA.',source:S},
{id:'ch16-eng-4',title:'Historical FRL range',level:'core',kind:'recognition',q:'What range of FRL does the chapter state for the cited Indian fire standards?',choices:['About 30 minutes to 4 hours','1 second to 1 minute','10 to 20 hours only','Exactly 24 hours for all buildings'],answer:0,explanation:'The textbook cites a historical range from 30 min to 4 h depending on occupancy and evacuation needs.',source:S},
{id:'ch16-eng-5',title:'Protected-member criterion',level:'application',kind:'reasoning',q:'For a protected member, what basic relationship should the protection system achieve?',choices:['PSA at least equal to the required FRL','PSA always less than FRL','Zero steel temperature at all times','Section factor equal to zero'],answer:0,explanation:'Adequacy requires the achieved structural-adequacy period to meet or exceed the specified resistance period.',source:S},
{id:'ch16-eng-6',title:'Calculation-based PSA',level:'retrieval',kind:'sequence',q:'Which sequence represents a rational calculation-based fire assessment?',choices:['Determine strength versus temperature → predict steel temperature versus time → find when limiting temperature is reached','Choose paint colour → ignore heat transfer → use room-temperature strength','Calculate corrosion → calculate fatigue → stop','Assume failure time without checking temperature'],answer:0,explanation:'The textbook describes thermal response and temperature-dependent strength as the key linked calculations.',source:S}
]);
add('16:Calculation Approach',[
{id:'ch16-calc-1',title:'Uniform-temperature assumption',level:'foundation',kind:'concept',q:'What simplifying thermal assumption is commonly made in the chapter’s basic calculation approach?',choices:['Use a uniform mean steel temperature over the section','Assume one flange is at absolute zero','Assume steel has no heat capacity','Assume room temperature never changes'],answer:0,explanation:'Simplified calculations often treat the steel section with a uniform mean temperature.',source:S},
{id:'ch16-calc-2',title:'Thermal properties',level:'core',kind:'classification',q:'Which property is directly relevant to heat-transfer calculations for steel or insulation?',choices:['Specific heat','Bolt pitch only','Yield-line pattern only','Column effective length only'],answer:0,explanation:'Density, specific heat and conductivity are among the thermal properties used in the calculation approach.',source:S},
{id:'ch16-calc-3',title:'Steel density',level:'core',kind:'recognition',q:'What steel density is commonly used in the simplified calculations described in the chapter?',choices:['About 7850 kg/m³','About 785 kg/m³','About 78,500 kg/m³','About 100 kg/m³'],answer:0,explanation:'The source-grounded lesson uses approximately 7850 kg/m³ for steel density.',source:S},
{id:'ch16-calc-4',title:'Thermal gradient limitation',level:'core',kind:'reasoning',q:'When is the uniform-temperature simplification less reliable?',choices:['When substantial thermal gradients develop, such as in partially protected or composite situations','When the section is uniformly heated','When steel temperature is measured directly','When the member is short'],answer:0,explanation:'Large temperature gradients violate the central uniform-temperature assumption.',source:S},
{id:'ch16-calc-5',title:'Load ratio role',level:'application',kind:'reasoning',q:'Why is the fire-design load ratio important in the calculation approach?',choices:['It helps determine how much reduced strength the member must retain at elevated temperature','It determines the room fire load only','It changes steel density','It eliminates the need for thermal calculation'],answer:0,explanation:'A lightly loaded member can tolerate more strength reduction before reaching its fire limit state than a heavily loaded one.',source:S},
{id:'ch16-calc-6',title:'Core calculation objective',level:'retrieval',kind:'concept',q:'What quantity links the thermal analysis to the structural capacity check?',choices:['Steel temperature','Paint colour','Floor plan area alone','Bolt count alone'],answer:0,explanation:'Predicted steel temperature is used to obtain temperature-reduced material properties and capacity.',source:S}
]);
add('16:Calculation of Temperature Rise in Steel Members',[
{id:'ch16-rise-1',title:'Section-factor meaning',level:'foundation',kind:'concept',q:'What does a high exposed-surface-to-mass or section factor generally imply for an unprotected steel member?',choices:['Faster heating','Slower heating in every case','No temperature change','No radiation exposure'],answer:0,explanation:'More exposed surface per unit thermal mass causes faster temperature rise.',source:S},
{id:'ch16-rise-2',title:'Heat-transfer modes',level:'core',kind:'classification',q:'Which heat-transfer mechanisms are used to describe heating of exposed steel in fire?',choices:['Convection and radiation','Only groundwater seepage','Only mechanical work','Only chemical corrosion'],answer:0,explanation:'Net heat flux to an unprotected member includes convective and radiative components.',source:S},
{id:'ch16-rise-3',title:'Protection effect',level:'core',kind:'reasoning',q:'What is the primary thermal role of insulation around a steel member?',choices:['Introduce resistance to heat flow and delay steel temperature rise','Increase fire gas temperature deliberately','Eliminate steel heat capacity','Increase section factor without limit'],answer:0,explanation:'Protection slows the transfer of heat from the fire environment into the steel.',source:S},
{id:'ch16-rise-4',title:'Insulation parameters',level:'core',kind:'classification',q:'Which property of fire protection directly affects protected-steel heating?',choices:['Thermal conductivity of the insulation','Bolt hole diameter only','Column slenderness only','Weld electrode strength only'],answer:0,explanation:'Protection thickness, conductivity, density and specific heat all influence protected-member temperature response.',source:S},
{id:'ch16-rise-5',title:'Three-sided exposure',level:'application',kind:'reasoning',q:'Why can a beam heated on three sides respond differently from the same section heated on four sides?',choices:['The heated perimeter and therefore the section factor are different','Steel density changes with the number of heated sides','Young’s modulus is independent of temperature only for three sides','Radiation cannot occur on three sides'],answer:0,explanation:'The amount of exposed perimeter per unit steel mass changes with the exposure condition.',source:S},
{id:'ch16-rise-6',title:'Protection in example',level:'retrieval',kind:'concept',q:'What did the textbook comparison with a 12.5 mm gypsum board illustrate?',choices:['Even relatively thin protection can dramatically reduce steel temperature rise','Gypsum makes steel heat faster than bare steel','Protection has no thermal effect','Gypsum increases steel yield strength chemically'],answer:0,explanation:'The worked comparison showed a large reduction in steel temperature when gypsum protection was provided.',source:S}
]);
add('16:Mechanical Properties of Steel at Elevated Temperatures',[
{id:'ch16-mech-1',title:'Three strain components',level:'foundation',kind:'classification',q:'Which strain components are discussed for steel at elevated temperature?',choices:['Mechanical, thermal and creep strain','Only elastic strain','Only shrinkage strain','Only corrosion strain'],answer:0,explanation:'The chapter separates mechanical deformation, thermal expansion and creep effects.',source:S},
{id:'ch16-mech-2',title:'Modulus trend',level:'core',kind:'concept',q:'How does the modulus of elasticity of ordinary structural steel generally change as fire temperature rises?',choices:['It decreases','It increases without limit','It remains exactly constant','It becomes negative at low temperature'],answer:0,explanation:'Elevated temperature reduces stiffness as well as strength.',source:S},
{id:'ch16-mech-3',title:'Yield-strength trend',level:'core',kind:'concept',q:'How does elevated temperature affect ordinary steel yield strength?',choices:['It generally reduces it','It always doubles it','It has no effect','It makes yield strength equal to density'],answer:0,explanation:'Loss of yield strength is a central reason fire resistance must be checked.',source:S},
{id:'ch16-mech-4',title:'Critical-temperature region',level:'core',kind:'recognition',q:'The chapter associates substantial strength loss for ordinary structural steel with a critical-temperature region around what value for a uniformly heated, highly loaded member?',choices:['About 550°C','About 55°C','About 5°C','About 1550°C'],answer:0,explanation:'The source-grounded lesson notes around 550°C as a commonly cited critical-temperature region under the stated assumptions.',source:S},
{id:'ch16-mech-5',title:'Why room-temperature properties fail',level:'application',kind:'reasoning',q:'Why is it unsafe to check a hot steel member using only room-temperature fy and E?',choices:['Both strength and stiffness may have fallen substantially at the fire temperature','Fire increases both properties exactly','Thermal strain removes all force','Room-temperature properties are always conservative'],answer:0,explanation:'Fire design must use temperature-reduced mechanical properties.',source:S},
{id:'ch16-mech-6',title:'Creep in fire',level:'retrieval',kind:'concept',q:'Why is creep included in elevated-temperature deformation?',choices:['At high temperature, time-dependent strain can contribute to total deformation','Creep occurs only in concrete at room temperature','Creep raises yield strength','Creep eliminates thermal expansion'],answer:0,explanation:'The source includes creep strain as one component of deformation at elevated temperature.',source:S}
]);
add('16:Time to Reach Limiting Temperature',[
{id:'ch16-time-1',title:'Limiting temperature',level:'foundation',kind:'concept',q:'What is the limiting temperature of a member in fire design?',choices:['The steel temperature at which the member can no longer sustain the required fire-design action','The temperature at which paint first changes colour','The ambient temperature at construction','The melting point of every steel member'],answer:0,explanation:'Limiting temperature is tied to structural capacity under the fire-design action, not necessarily melting.',source:S},
{id:'ch16-time-2',title:'Exposure condition',level:'core',kind:'reasoning',q:'Why does the chapter give different time-to-temperature expressions for three-sided and four-sided fire exposure?',choices:['The exposed surface area relative to mass differs','Steel chemistry changes with exposure side count','Fire load becomes zero for three-sided exposure','Only four-sided exposure transfers heat'],answer:0,explanation:'Different heated perimeters produce different heating rates.',source:S},
{id:'ch16-time-3',title:'Section-factor effect',level:'core',kind:'reasoning',q:'For otherwise similar unprotected members, what happens to the time to reach a given limiting temperature as exposed surface-to-mass ratio increases?',choices:['It generally decreases','It always increases','It becomes unrelated to geometry','It becomes infinite'],answer:0,explanation:'Higher section factor means faster heating and hence less time to reach a target temperature.',source:S},
{id:'ch16-time-4',title:'Time-domain criterion',level:'core',kind:'formula',q:'Which inequality expresses adequate performance in the time domain?',choices:['Time to failure ≥ required fire duration','Time to failure < required fire duration','Steel temperature = 0°C','FRL = 0'],answer:0,explanation:'The member must remain adequate for at least the specified fire-resistance period.',source:S},
{id:'ch16-time-5',title:'Load level effect',level:'application',kind:'reasoning',q:'If two identical members have different fire-design load ratios, which one would generally reach its structural limiting condition at a lower steel temperature?',choices:['The more heavily loaded member','The unloaded member','Both must always have identical limiting temperatures','Load ratio has no relation to capacity'],answer:0,explanation:'A higher applied fraction of capacity leaves less allowable strength reduction before failure.',source:S},
{id:'ch16-time-6',title:'Design comparison',level:'retrieval',kind:'sequence',q:'What is the final comparison after calculating time to limiting temperature?',choices:['Compare the calculated time with the required fire-resistance duration','Compare steel density with concrete density only','Compare paint thickness with bolt diameter','Compare wind speed with fire load'],answer:0,explanation:'The time-domain check directly compares available structural adequacy time with required FRL.',source:S}
]);
add('16:Passive Protection for Steelwork',[
{id:'ch16-passive-1',title:'Passive-protection principle',level:'foundation',kind:'concept',q:'What is the main function of passive protection on steelwork?',choices:['Slow heat transfer into the steel','Actively pump water onto the fire','Increase combustible content','Reduce evacuation time by alarm'],answer:0,explanation:'Passive systems insulate or shield steel and therefore delay temperature rise.',source:S},
{id:'ch16-passive-2',title:'Spray protection',level:'core',kind:'classification',q:'Which is a characteristic advantage of sprayed fire protection discussed in the chapter?',choices:['It can cover complex member geometry relatively quickly','It always gives the best architectural finish','It requires no adhesion to the substrate','It is a structural load-carrying plate'],answer:0,explanation:'Spray systems are adaptable to irregular details and can be economical and fast to apply.',source:S},
{id:'ch16-passive-3',title:'Board systems',level:'core',kind:'reasoning',q:'What detailing issue is especially important for board fire protection?',choices:['Joints and continuity of the board enclosure','Increasing steel carbon content','Changing section yield stress','Removing all connections'],answer:0,explanation:'Board systems need careful joint and enclosure detailing to maintain protection continuity.',source:S},
{id:'ch16-passive-4',title:'Intumescent action',level:'core',kind:'concept',q:'What happens to an intumescent coating when exposed to fire?',choices:['It expands to form an insulating char','It contracts into a heat conductor','It dissolves the steel surface','It functions as a sprinkler'],answer:0,explanation:'Expansion produces a thicker insulating layer that delays steel heating.',source:S},
{id:'ch16-passive-5',title:'Connection continuity',level:'application',kind:'reasoning',q:'Why must fire protection be continued appropriately over connection components?',choices:['Unprotected bolts, welds or splice plates can become local hot weak points','Connections never heat','Connection steel has infinite strength','Protection is required only for appearance'],answer:0,explanation:'The source and IS 800 provisions emphasize maintaining protection over connection components.',source:S},
{id:'ch16-passive-6',title:'Other passive systems',level:'retrieval',kind:'classification',q:'Which system is also discussed as a passive or thermal fire-protection approach?',choices:['Water-filled hollow steel members','Removing all compartment walls','Increasing fuel load','Disabling smoke control'],answer:0,explanation:'The chapter discusses water-filled members, concrete encasement, composite shielding and partial encasement in addition to sprays, boards and coatings.',source:S}
]);
add('16:Fire-resistant Steels',[
{id:'ch16-frs-1',title:'Purpose of FR steel',level:'foundation',kind:'concept',q:'Why are fire-resistant steels developed?',choices:['To retain more structural strength at elevated temperature than ordinary steel','To eliminate all thermal expansion','To make steel non-metallic','To make fire load zero'],answer:0,explanation:'Their value is improved elevated-temperature strength retention.',source:S},
{id:'ch16-frs-2',title:'Alloying role',level:'core',kind:'concept',q:'Which alloying additions are mentioned as helping stabilize fire-resistant steel microstructure?',choices:['Molybdenum and chromium','Lead and mercury only','Hydrogen and oxygen','Only carbon removal'],answer:0,explanation:'The chapter cites molybdenum and chromium among additions used to improve elevated-temperature performance.',source:S},
{id:'ch16-frs-3',title:'Strength retention',level:'core',kind:'numerical',q:'At about 600°C, what minimum fraction of room-temperature yield strength is stated for the fire-resistant steel discussed?',choices:['About 65%','About 6.5%','About 100% for all grades','About 5%'],answer:0,explanation:'The source states that the fire-resistant steel discussed retains at least about 65% at roughly 600°C.',source:S},
{id:'ch16-frs-4',title:'Ordinary-steel comparison',level:'core',kind:'comparison',q:'At roughly 600°C, the chapter compares ordinary structural steel strength retention at about:',choices:['40% of room-temperature yield strength','95% for every steel','0% exactly','80% more than fire-resistant steel'],answer:0,explanation:'The source contrasts about 40% for ordinary steel with about 65% for the fire-resistant steel discussed.',source:S},
{id:'ch16-frs-5',title:'Protection implication',level:'application',kind:'reasoning',q:'What practical benefit can improved high-temperature strength retention provide?',choices:['It may reduce conventional fire-protection requirements in suitable applications','It guarantees no fire design is required','It eliminates all heating of steel','It removes the need for evacuation'],answer:0,explanation:'Fire-resistant steel can reduce reliance on applied protection where the design and regulations allow.',source:S},
{id:'ch16-frs-6',title:'Use limitation',level:'retrieval',kind:'reasoning',q:'Why is fire-resistant steel not automatically used for every steel structure?',choices:['Its higher cost can limit economical use','It has no elevated-temperature benefit','It cannot be fabricated','It is always weaker at room temperature than timber'],answer:0,explanation:'The chapter notes cost as an important limitation despite the improved elevated-temperature performance.',source:S}
]);
add('16:Fire Performance Assessment',[
{id:'ch16-assess-1',title:'Master criterion',level:'foundation',kind:'concept',q:'What is the fundamental comparison in fire-performance assessment?',choices:['Fire resistance must be at least equal to fire severity','Fire severity must always be zero','Room-temperature strength must equal density','Fire load must equal wind load'],answer:0,explanation:'The source expresses the governing concept as available resistance being sufficient for the fire demand/severity.',source:S},
{id:'ch16-assess-2',title:'Time domain',level:'core',kind:'classification',q:'Which statement is a time-domain fire check?',choices:['Time to failure is not less than required fire duration','Steel density exceeds concrete density','Temperature is lower than melting point only','Paint thickness exceeds bolt diameter'],answer:0,explanation:'The time-domain criterion compares duration to failure with the required exposure time.',source:S},
{id:'ch16-assess-3',title:'Temperature domain',level:'core',kind:'classification',q:'Which statement is a temperature-domain fire check?',choices:['Failure temperature is at least as high as the maximum steel temperature reached','Fire duration exceeds member span','Load capacity equals room temperature exactly','Section factor equals density'],answer:0,explanation:'The temperature-domain check compares limiting/failure temperature with predicted maximum temperature.',source:S},
{id:'ch16-assess-4',title:'Strength domain',level:'core',kind:'classification',q:'Which statement is a strength-domain fire check?',choices:['Elevated-temperature capacity exceeds the applied fire-design action','Ambient temperature exceeds steel density','Fire duration equals wind return period','Section factor exceeds span'],answer:0,explanation:'The strength-domain check compares reduced capacity at temperature with the fire-design load effect.',source:S},
{id:'ch16-assess-5',title:'Accidental design situation',level:'application',kind:'reasoning',q:'Why are fire load combinations treated differently from ordinary ultimate design combinations?',choices:['Fire is an accidental design situation with its own load factors and temperature-reduced resistance','Fire always occurs with maximum values of every variable load','Material properties remain at room temperature','No loads act during fire'],answer:0,explanation:'Fire design uses accidental-situation actions while simultaneously reducing material resistance for temperature.',source:S},
{id:'ch16-assess-6',title:'Large deformation',level:'retrieval',kind:'concept',q:'What is the primary structural concern in the chapter even though large fire-induced deformations may occur?',choices:['Avoiding collapse during the required fire period','Maintaining zero deflection under all fire conditions','Keeping finishes perfectly undamaged','Preventing all thermal expansion'],answer:0,explanation:'Structural integrity and collapse prevention are the principal fire limit-state concerns.',source:S}
]);
add('16:Examples',[
{id:'ch16-ex-1',title:'Example inputs',level:'foundation',kind:'sequence',q:'Which input is repeatedly needed in the chapter’s steel-temperature examples?',choices:['Section factor or exposed perimeter relative to steel mass/area','Concrete cube strength only','Soil bearing capacity only','Bolt proof load only'],answer:0,explanation:'Section factor controls how quickly a given steel section absorbs heat.',source:S},
{id:'ch16-ex-2',title:'Protected versus unprotected',level:'core',kind:'reasoning',q:'What comparison do the worked examples make between protected and unprotected members?',choices:['Their temperature-time histories','Only their paint colours','Only their room-temperature weights','Only their bolt layouts'],answer:0,explanation:'The examples demonstrate the thermal delay created by fire protection.',source:S},
{id:'ch16-ex-3',title:'Capacity fraction',level:'core',kind:'application',q:'When an example asks what fraction of beam capacity can be safely used for a stated fire duration, what must be related?',choices:['Fire duration, steel temperature and temperature-reduced member strength','Only span and density','Only paint thickness and colour','Only wind load and corrosion rate'],answer:0,explanation:'Capacity fraction problems connect thermal history with reduced mechanical strength.',source:S},
{id:'ch16-ex-4',title:'Insulation design',level:'core',kind:'sequence',q:'What is varied when a worked problem asks for the protection required to achieve a target fire rating?',choices:['Insulation thickness','Steel density arbitrarily','Gravity acceleration','Poisson ratio'],answer:0,explanation:'Protection thickness is adjusted so that steel temperature remains within the required structural limit for the duration.',source:S},
{id:'ch16-ex-5',title:'Negative early increment',level:'application',kind:'reasoning',q:'In the protected-member calculation shown in the chapter, why were some very early computed steel-temperature increments set to zero?',choices:['The insulation initially absorbed heat, giving a negative calculated increment that was not used as physical steel cooling','Steel temperature was below absolute zero','Radiation was turned off permanently','The member had no heat capacity'],answer:0,explanation:'The worked calculation notes negative early increments because heat is initially stored in the insulation; these were set to zero.',source:S},
{id:'ch16-ex-6',title:'Example 20.3 context',level:'retrieval',kind:'recognition',q:'Example 20.3 asks about an ISMB 500 supporting a concrete floor for what required fire resistance?',choices:['30 minutes','3 minutes','300 minutes','24 hours'],answer:0,explanation:'The source snippet states a 30 min fire-resistance requirement for that example.',source:S}
]);
add('16:Summary',[
{id:'ch16-sum-1',title:'Summary sequence',level:'foundation',kind:'sequence',q:'Which sequence best summarizes structural fire design?',choices:['Define fire exposure → determine required duration → predict steel temperature → reduce material properties → verify resistance','Select steel colour → ignore heat → verify corrosion only','Assume full room-temperature strength throughout','Check wind load only'],answer:0,explanation:'The chapter integrates fire exposure, thermal response and reduced structural capacity.',source:S},
{id:'ch16-sum-2',title:'Active/passive distinction',level:'core',kind:'classification',q:'Which pairing is correct?',choices:['Sprinkler = active; board encasement = passive','Board encasement = active; alarm = passive','Both are corrosion protection only','Both eliminate fire load'],answer:0,explanation:'Active systems act to detect/control fire, while passive systems resist its effects through construction or insulation.',source:S},
{id:'ch16-sum-3',title:'Standard fire purpose',level:'core',kind:'retrieval',q:'What is ISO 834 mainly used for in this chapter?',choices:['Standardized fire-resistance testing and comparison','Exact prediction of every natural fire','Corrosion classification','Fatigue cycle counting'],answer:0,explanation:'ISO 834 is the standardized nominal heating exposure used for fire-resistance assessment.',source:S},
{id:'ch16-sum-4',title:'Steel-heating driver',level:'core',kind:'reasoning',q:'Which geometric quantity is repeatedly emphasized as controlling steel heating rate?',choices:['Section factor / exposed surface-to-mass ratio','Only member span','Only flange width','Only bolt spacing'],answer:0,explanation:'Heating rate depends strongly on exposed surface relative to thermal mass.',source:S},
{id:'ch16-sum-5',title:'Temperature-strength link',level:'application',kind:'reasoning',q:'Why must thermal analysis and structural analysis be linked in fire design?',choices:['Steel temperature determines the reduced strength and stiffness available to resist fire-design actions','Temperature never changes mechanical properties','Structural capacity determines fire load exactly','Thermal analysis replaces equilibrium'],answer:0,explanation:'Predicted temperature is the input for elevated-temperature material properties and capacity.',source:S},
{id:'ch16-sum-6',title:'Protection families',level:'retrieval',kind:'classification',q:'Which list contains only protection approaches discussed in the chapter?',choices:['Spray, boards, intumescent coating, concrete encasement, water-filled members','Wind bracing, soil anchors, drainage blanket','Cathodic protection, galvanizing, anodizing only','Prestressing tendons, timber sheathing only'],answer:0,explanation:'Those systems form the chapter’s main passive-protection families.',source:S}
]);
add('16:Exercises',[
{id:'ch16-exer-1',title:'Three-sided column',level:'foundation',kind:'recognition',q:'One Chapter 16 exercise asks for the temperature rise of which member under three-sided ISO 834 exposure?',choices:['An ISMB 300 column','A timber beam','A concrete pile','An aluminium cable'],answer:0,explanation:'Exercise 1 asks for the temperature rise of an ISMB 300 column heated on three sides for 20 min.',source:S},
{id:'ch16-exer-2',title:'Exposure time',level:'core',kind:'numerical',q:'For the ISMB 300 three-sided ISO 834 exercise, what exposure time is specified?',choices:['20 min','2 min','200 min','60 min'],answer:0,explanation:'The exercise specifies 20 minutes.',source:S},
{id:'ch16-exer-3',title:'Protected-column exercise',level:'core',kind:'recognition',q:'What protection material is specified in the exercise for the protected ISMB 500 column?',choices:['Mineral wool','Zinc coating','Epoxy paint only','Concrete grout only'],answer:0,explanation:'The exercise specifies mineral-wool protection and provides its density and specific heat.',source:S},
{id:'ch16-exer-4',title:'Beam fire rating',level:'core',kind:'recognition',q:'What fire-resistance duration is specified for the ISMB 400 beam-capacity exercise?',choices:['45 min','4.5 min','450 min','15 min'],answer:0,explanation:'The exercise asks what fraction of capacity can be carried for a 45 min fire resistance.',source:S},
{id:'ch16-exer-5',title:'Insulation-thickness extension',level:'application',kind:'reasoning',q:'Why does the final exercise ask how insulation thickness changes when fire rating increases to 90 min?',choices:['Longer required exposure generally demands greater thermal delay from the protection system','Longer fire rating reduces all heating','Insulation has no effect after 45 min','Steel density doubles at 90 min'],answer:0,explanation:'The exercise is designed to connect higher required duration with the needed protection thickness.',source:S},
{id:'ch16-exer-6',title:'Exercise skill chain',level:'retrieval',kind:'sequence',q:'Which chain of skills is necessary to solve the Chapter 16 exercises?',choices:['ISO fire exposure → section factor/protection → steel temperature → reduced capacity or required insulation','Wind speed → earthquake coefficient → corrosion allowance','Only room-temperature bending','Only bolt shear'],answer:0,explanation:'The exercise set deliberately links thermal exposure and structural resistance.',source:S}
]);
add('16:Review Questions',[
{id:'ch16-review-1',title:'Fire-test criteria',level:'foundation',kind:'retrieval',q:'Which three failure criteria are used for fire-resistance testing in the chapter?',choices:['Stability, integrity and insulation','Yielding, fatigue and corrosion','Wind, snow and earthquake','Strength, colour and density'],answer:0,explanation:'The standard fire-test criteria are stability, integrity and insulation.',source:S},
{id:'ch16-review-2',title:'Natural-fire inputs',level:'core',kind:'retrieval',q:'Which input belongs to a natural/parametric fire model?',choices:['Fire-load density','Only room-temperature yield stress','Only bolt diameter','Only member effective length'],answer:0,explanation:'Fire load, ventilation and enclosure thermal characteristics are central natural-fire inputs.',source:S},
{id:'ch16-review-3',title:'Section factor recall',level:'core',kind:'reasoning',q:'Why is section factor repeatedly asked about in the review questions?',choices:['It strongly influences the rate of steel temperature rise','It determines fire load chemistry','It gives the evacuation time directly','It is the same as yield strength'],answer:0,explanation:'Section factor is the key geometric thermal parameter for member heating.',source:S},
{id:'ch16-review-4',title:'PSA recall',level:'core',kind:'concept',q:'What does PSA measure?',choices:['Time for a member to reach the structural-adequacy limit state under standard fire exposure','Annual probability of fire','Steel paint life','Room-temperature service life'],answer:0,explanation:'PSA is the member’s achieved period of structural adequacy.',source:S},
{id:'ch16-review-5',title:'Protection recall',level:'application',kind:'classification',q:'Which of the following should be classified as passive rather than active protection?',choices:['Intumescent coating','Automatic smoke detector','Fire alarm','Fire-hydrant pump'],answer:0,explanation:'Intumescent coating works as passive thermal protection without active operation during the fire.',source:S},
{id:'ch16-review-6',title:'Three-domain recall',level:'retrieval',kind:'classification',q:'What three verification domains close the chapter’s fire-performance discussion?',choices:['Time, temperature and strength','Length, mass and time','Wind, seismic and fatigue','Cost, quality and schedule'],answer:0,explanation:'The chapter frames equivalent checks in time, temperature and strength domains.',source:S}
]);
})();
