(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const S='N. Subramanian, Design of Steel Structures, supplementary Ch.21 Fatigue-resistant Design';
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
add('17:Introduction',[
{id:'ch17-intro-1',title:'Fatigue meaning',level:'foundation',kind:'concept',q:'In the chapter, fatigue damage is caused primarily by what?',choices:['Repeated or fluctuating stresses that initiate and propagate cracks','One static load only','Uniform room temperature','Surface painting alone'],answer:0,explanation:'Fatigue is the initiation and propagation of cracks under repeated stress or strain cycles.',source:S},
{id:'ch17-intro-2',title:'Why static safety can mislead',level:'core',kind:'reasoning',q:'Why can a component fail by fatigue even when the cyclic stress is below its static yield or ultimate strength?',choices:['Damage accumulates through repeated crack initiation and growth','Yield strength becomes zero after one cycle','Fatigue requires the stress to exceed ultimate strength','The member loses all area immediately'],answer:0,explanation:'Fatigue failure can occur at stresses considered safe by static analysis because repeated cycling progressively grows cracks.',source:S},
{id:'ch17-intro-3',title:'Four stages',level:'core',kind:'sequence',q:'Which sequence matches the four fatigue-failure stages described in the chapter?',choices:['Crack initiation → crack growth → crack propagation → final rupture','Yielding → corrosion → melting → buckling','Rupture → initiation → welding → growth','Elasticity → creep → fire → rupture'],answer:0,explanation:'The chapter presents fatigue as a progressive process ending in final rupture.',source:S},
{id:'ch17-intro-4',title:'High versus low cycle',level:'core',kind:'classification',q:'Which statement distinguishes high-cycle from low-cycle fatigue in the chapter?',choices:['High-cycle fatigue is mainly elastic and stress-range based; low-cycle fatigue involves significant cyclic plastic strain','High-cycle fatigue always has fewer cycles','Low-cycle fatigue is always fully elastic','There is no mechanical difference'],answer:0,explanation:'High-cycle fatigue is primarily elastic, while low-cycle fatigue is associated with macroscopic cyclic plasticity.',source:S},
{id:'ch17-intro-5',title:'Fatigue-prone structures',level:'application',kind:'classification',q:'Which structure is specifically identified as fatigue-prone?',choices:['Gantry girder subjected to repeated crane loading','An ordinary lightly cycled building beam only','A decorative non-loadbearing wall','A static foundation block with no cyclic action'],answer:0,explanation:'Bridges, cranes, gantry girders, towers, offshore platforms and rotating-equipment supports are cited as fatigue-sensitive.',source:S},
{id:'ch17-intro-6',title:'Why welds are critical',level:'retrieval',kind:'reasoning',q:'Why do many fatigue cracks in welded structures start at welds?',choices:['Welds contain discontinuities and sharp toe/root geometry that create local stress concentrations','Weld metal has no strength','Welds remove all residual stress','Welds are always unloaded'],answer:0,explanation:'Existing imperfections and sharp weld geometry shorten or eliminate the crack-initiation phase and accelerate propagation.',source:S}
]);
add('17:Factors Affecting Fatigue Life',[
{id:'ch17-factor-1',title:'Three dominant factors',level:'foundation',kind:'classification',q:'Which three factors does the chapter identify as especially important to fatigue life?',choices:['Number of cycles, stress range, and type of member/detail','Density, colour, and span only','Yield stress, paint colour, and bolt count','Temperature, concrete grade, and roof slope only'],answer:0,explanation:'Fatigue life is strongly governed by cycle count, stress range and detail category.',source:S},
{id:'ch17-factor-2',title:'Stress concentration',level:'core',kind:'reasoning',q:'What does a notch or hole do to fatigue behaviour?',choices:['Raises local stress range and encourages crack initiation','Eliminates cyclic stress','Guarantees compressive residual stress','Makes the section immune to fatigue'],answer:0,explanation:'Stress raisers amplify local cyclic stresses and are common crack-initiation sites.',source:S},
{id:'ch17-factor-3',title:'Plate thickness effect',level:'core',kind:'reasoning',q:'Why can thicker welded plates have lower fatigue strength?',choices:['Stress-gradient, technological-size and statistical-size effects can increase crack severity','Thicker plates have zero stiffness','Thicker plates cannot be welded','Their nominal stress is always zero'],answer:0,explanation:'The chapter gives stress-gradient, technological-size and statistical-size explanations for thickness effects.',source:S},
{id:'ch17-factor-4',title:'Fatigue-limit relation',level:'core',kind:'formula',q:'Which empirical relation for fatigue limit fl and ultimate stress fu is given in the chapter?',choices:['fl = 140 + 0.25fu MPa','fl = fu/140','fl = 140fu','fl = fu − 1400'],answer:0,explanation:'The chapter gives fl = 140 + 0.25fu in MPa as a general relation.',math:'f_l=140+0.25f_u',source:S},
{id:'ch17-factor-5',title:'Imperfection orientation',level:'application',kind:'reasoning',q:'Which crack-like imperfection is generally more severe under tensile stress?',choices:['One oriented perpendicular to the tensile stress','One parallel to the tensile stress','One that is perfectly absent','Any orientation is always identical'],answer:0,explanation:'Planar crack-like discontinuities perpendicular to tensile stress are especially harmful because they tend to open.',source:S},
{id:'ch17-factor-6',title:'Post-weld treatment',level:'retrieval',kind:'concept',q:'How can post-weld treatment improve fatigue performance?',choices:['By reducing stress peaks, removing crack-like toe defects and creating favourable residual stress','By increasing weld roughness','By adding sharp notches','By increasing tensile residual stress deliberately'],answer:0,explanation:'The source describes weld-profile improvement, defect removal and reduction of detrimental tensile residual stress.',source:S}
]);
add('17:Different Approaches to Fatigue Analysis',[
{id:'ch17-approach-1',title:'Three approaches',level:'foundation',kind:'classification',q:'What are the three fatigue-analysis approaches listed in the chapter?',choices:['Stress, strain, and crack-propagation methods','Elastic, plastic, and thermal methods','Wind, seismic, and fire methods','Bolted, welded, and riveted methods'],answer:0,explanation:'The chapter classifies fatigue analysis into stress, strain and fracture-mechanics/crack-propagation approaches.',source:S},
{id:'ch17-approach-2',title:'High-cycle method',level:'core',kind:'classification',q:'Which approach is traditionally associated with high-cycle, low-stress fatigue?',choices:['Stress-range method','Only strain-range method','Only creep analysis','Only plastic collapse analysis'],answer:0,explanation:'High-cycle fatigue is mainly elastic and is commonly described using stress range.',source:S},
{id:'ch17-approach-3',title:'Low-cycle method',level:'core',kind:'classification',q:'Why is strain range more suitable for low-cycle fatigue?',choices:['The stresses are high enough to cause significant cyclic plastic deformation','Low-cycle fatigue contains no deformation','Stress is always zero','The material remains perfectly elastic'],answer:0,explanation:'Low-cycle fatigue involves plastic strains, so strain-based characterization is more appropriate.',source:S},
{id:'ch17-approach-4',title:'Crack-propagation premise',level:'core',kind:'concept',q:'What basic assumption underlies the crack-propagation method?',choices:['Engineering components contain pre-existing flaws whose growth can be tracked','Every component is initially flawless','Cracks cannot be detected','Fatigue life ends before any crack grows'],answer:0,explanation:'Fracture-mechanics fatigue analysis starts from an initial flaw and estimates cycles to a critical crack size.',source:S},
{id:'ch17-approach-5',title:'NDT role',level:'application',kind:'reasoning',q:'Why are non-destructive testing methods important in a crack-propagation approach?',choices:['They help estimate the initial flaw size used in life prediction','They increase Young’s modulus','They remove all cyclic loads','They replace the need to know fracture toughness'],answer:0,explanation:'Initial flaw size may be established using visual, penetrant, radiographic, ultrasonic, magnetic or related methods.',source:S},
{id:'ch17-approach-6',title:'Book scope',level:'retrieval',kind:'concept',q:'Which fatigue-analysis approach does the chapter mainly develop because it is followed by IS 800?',choices:['Stress method','Strain method only','Crack-propagation method only','Creep-fatigue method only'],answer:0,explanation:'The book confines detailed treatment mainly to the stress method.',source:S}
]);
add('17:Fatigue Loading',[
{id:'ch17-load-1',title:'Stress range',level:'foundation',kind:'formula',q:'How is applied stress range defined for a constant-amplitude cycle?',choices:['fmax − fmin','fmax + fmin','fmax/fmin','(fmax + fmin)/2'],answer:0,explanation:'Stress range is the algebraic difference between maximum and minimum stress.',math:'\\Delta f=f_{max}-f_{min}',source:S},
{id:'ch17-load-2',title:'Mean stress',level:'core',kind:'formula',q:'Which expression gives the mean stress of a constant-amplitude cycle?',choices:['(fmax + fmin)/2','fmax − fmin','2(fmax − fmin)','fmin/fmax'],answer:0,explanation:'Mean stress is the algebraic average of maximum and minimum stress.',math:'f_m=\\frac{f_{max}+f_{min}}{2}',source:S},
{id:'ch17-load-3',title:'Stress amplitude',level:'core',kind:'formula',q:'How is stress amplitude related to the stress range?',choices:['It is half the stress range','It is twice the stress range','It equals the mean stress always','It equals fmin/fmax'],answer:0,explanation:'Stress amplitude is (fmax−fmin)/2.',math:'f_a=\\frac{f_{max}-f_{min}}{2}',source:S},
{id:'ch17-load-4',title:'Stress ratio',level:'core',kind:'formula',q:'Which expression defines the stress ratio R?',choices:['R=fmin/fmax','R=fmax/fmin always','R=fmax−fmin','R=(fmax+fmin)/2'],answer:0,explanation:'R expresses the relative minimum and maximum stress in the cycle.',math:'R=\\frac{f_{min}}{f_{max}}',source:S},
{id:'ch17-load-5',title:'Simple numerical cycle',level:'application',kind:'numerical',q:'For fmax=120 MPa and fmin=40 MPa, what is the stress range?',choices:['80 MPa','160 MPa','40 MPa','3 MPa'],answer:0,explanation:'Stress range = 120−40 = 80 MPa.',math:'\\Delta f=120-40=80\\text{ MPa}',source:S},
{id:'ch17-load-6',title:'Variable amplitude',level:'retrieval',kind:'classification',q:'Which loading history is typical of truck loading on bridges or wave loading on offshore structures?',choices:['Variable-amplitude loading','Perfectly constant-amplitude loading only','No cyclic loading','Pure static dead load only'],answer:0,explanation:'These actions vary irregularly in magnitude and sequence and are cited as variable-amplitude histories.',source:S}
]);
add('17:Stress Methods',[
{id:'ch17-stress-1',title:'Fatigue strength',level:'foundation',kind:'concept',q:'What is fatigue strength?',choices:['The cyclic stress range a material or detail can withstand for a specified number of cycles without failure','The static dead load of a member','The elastic modulus at one cycle','The paint adhesion strength'],answer:0,explanation:'Fatigue strength is tied to a specified fatigue life or number of cycles.',source:S},
{id:'ch17-stress-2',title:'Fatigue limit',level:'core',kind:'concept',q:'What is meant by fatigue or endurance limit in the stress-method discussion?',choices:['The maximum repeated stress range that can be sustained indefinitely in the idealized test sense','The ultimate tensile strength under one load','The yield stress divided by density','The minimum bolt pitch'],answer:0,explanation:'The fatigue limit is the limiting cyclic stress range associated with very long or idealized infinite life.',source:S},
{id:'ch17-stress-3',title:'S-N meaning',level:'core',kind:'concept',q:'What does an S-N curve relate?',choices:['Stress or stress range to number of cycles to failure','Strain to temperature only','Load factor to corrosion rate','Section area to density'],answer:0,explanation:'S-N curves plot fatigue stress measure against cycles to fracture, commonly on logarithmic axes.',source:S},
{id:'ch17-stress-4',title:'Detail class reference',level:'core',kind:'recognition',q:'In the IS 800 S-N system described in the chapter, what does the detail-category number represent?',choices:['Reference normal fatigue stress range at 2 million cycles','Member length in mm','Yield stress at one cycle','Number of bolts in the joint'],answer:0,explanation:'Each category number represents the reference fatigue stress range at N=2×10^6 cycles.',source:S},
{id:'ch17-stress-5',title:'Constant-amplitude point',level:'application',kind:'recognition',q:'At approximately how many cycles does the chapter place the constant-amplitude fatigue-limit point for normal-stress S-N curves?',choices:['5 million cycles','5 thousand cycles','50 cycles','500 million cycles'],answer:0,explanation:'The source identifies the constant-amplitude fatigue limit at 5×10^6 cycles.',source:S},
{id:'ch17-stress-6',title:'Shear S-N slope',level:'retrieval',kind:'concept',q:'What m-value is used for the shear-stress fatigue-strength curves shown in the chapter table?',choices:['m=5','m=1','m=2','m=10'],answer:0,explanation:'The table gives shear-stress S-N curves with slope parameter m=5.',source:S}
]);
add('17:Fatigue Assessment for Variable Stress Ranges',[
{id:'ch17-var-1',title:'Miner principle',level:'foundation',kind:'concept',q:'What does the Palmgren-Miner rule do?',choices:['Adds damage fractions from different stress-range blocks','Calculates only static yield strength','Ignores cycle count','Assumes every load block causes zero damage'],answer:0,explanation:'Miner’s rule is a linear cumulative-damage method for variable-amplitude fatigue.',source:S},
{id:'ch17-var-2',title:'Damage fraction',level:'core',kind:'formula',q:'For a stress range occurring ni times when Ni cycles would cause failure at that range, what is its Miner damage fraction?',choices:['ni/Ni','Ni/ni','ni×Ni','ni+Ni'],answer:0,explanation:'Each block contributes the used fraction of its fatigue life, ni/Ni.',math:'D_i=\\frac{n_i}{N_i}',source:S},
{id:'ch17-var-3',title:'Linear damage criterion',level:'core',kind:'formula',q:'Which expression represents the basic Palmgren-Miner cumulative-damage check?',choices:['Σ(ni/Ni) ≤ 1','Σ(niNi) = 0','Σ(Ni/ni) ≤ 0','Σni = fy'],answer:0,explanation:'The accumulated damage is the sum of life fractions; unity represents the basic failure threshold.',math:'D=\\sum_i\\frac{n_i}{N_i}',source:S},
{id:'ch17-var-4',title:'Cycle counting',level:'core',kind:'classification',q:'Which two cycle-counting methods are specifically explained in the chapter?',choices:['Reservoir counting and rainflow counting','Euler and Rankine counting','Moment distribution and slope deflection','Shot blasting and grit blasting'],answer:0,explanation:'The chapter describes reservoir and rainflow methods for reducing irregular histories to stress-range cycles.',source:S},
{id:'ch17-var-5',title:'Why transform history?',level:'application',kind:'reasoning',q:'Why is a variable-amplitude stress history converted into constant-amplitude blocks before applying Miner’s rule?',choices:['Each stress range needs a corresponding fatigue life Ni from the S-N relation','Miner’s rule uses only member mass','Variable histories contain no cycles','The conversion removes all stress concentrations'],answer:0,explanation:'Damage is evaluated block-by-block using the fatigue life corresponding to each counted stress range.',source:S},
{id:'ch17-var-6',title:'Miner limitation',level:'retrieval',kind:'reasoning',q:'What limitation of the linear Miner rule does the chapter mention?',choices:['It assumes sequence independence and independent linear damage accumulation','It explicitly models all load-sequence effects exactly','It cannot use S-N data','It applies only to one cycle'],answer:0,explanation:'The source notes that nonlinear rules can address sequence and interaction effects that Miner’s linear rule neglects.',source:S}
]);
add('17:General Guidelines for Fatigue-resistant Design',[
{id:'ch17-guide-1',title:'Detailing matters',level:'foundation',kind:'reasoning',q:'What does the chapter identify as a major cause of fatigue failures in practice?',choices:['Improper detailing and weld defects','Excessive concrete curing','Too much elastic modulus','Using multiple load paths'],answer:0,explanation:'The source emphasizes that poor details and weld defects cause many fatigue problems.',source:S},
{id:'ch17-guide-2',title:'Redundancy',level:'core',kind:'reasoning',q:'Why are multiple load paths desirable in fatigue-sensitive structures?',choices:['They reduce the chance that one fatigue failure causes total collapse','They guarantee no crack ever forms','They eliminate inspections','They increase stress concentration intentionally'],answer:0,explanation:'Redundancy helps the structure survive local fatigue failure and supports fail-safe behaviour.',source:S},
{id:'ch17-guide-3',title:'Geometry transition',level:'core',kind:'reasoning',q:'Which detailing action is recommended for fatigue resistance?',choices:['Avoid abrupt changes in cross-section or stiffness','Introduce sharp re-entrant corners','Increase eccentricity deliberately','Place welds at peak stress whenever possible'],answer:0,explanation:'Smooth geometry and stiffness transitions reduce stress concentration.',source:S},
{id:'ch17-guide-4',title:'Weld location',level:'core',kind:'application',q:'Where should joints and welds preferably be located when practicable?',choices:['At lower-stress regions such as near points of contraflexure or the neutral axis','Always at maximum tensile stress','Only at maximum shear regardless of detail','At random locations'],answer:0,explanation:'The chapter recommends placing joints and welds in low-stress regions when possible.',source:S},
{id:'ch17-guide-5',title:'Coped beam risk',level:'application',kind:'reasoning',q:'Why can a flame-cut coped beam end be fatigue-sensitive?',choices:['Small radius, cutting roughness and connection restraint can create local cyclic stresses','A cope always eliminates all moment and stress','Flame cutting removes every imperfection','The cope makes the beam a closed section'],answer:0,explanation:'The source warns that rough, small-radius copes and restraint can promote fatigue cracking even near nominal zero-moment regions.',source:S},
{id:'ch17-guide-6',title:'Fail-safe inspection',level:'retrieval',kind:'concept',q:'What operational requirement accompanies a fail-safe fatigue-design philosophy?',choices:['Periodic in-service inspection to find and repair cracked members','No inspection for the life of the structure','Immediate replacement after every load cycle','Elimination of redundancy'],answer:0,explanation:'Fail-safe design assumes cracks may occur and therefore relies on inspectability, slow crack growth and alternate load paths.',source:S}
]);
add('17:Fatigue Assessment Under Combined Stresses',[
{id:'ch17-comb-1',title:'Concurrent stresses',level:'foundation',kind:'reasoning',q:'When considerable normal and shear stresses occur concurrently at a fatigue-critical location, what does the chapter recommend?',choices:['Calculate principal stresses and use the corresponding stress range','Ignore shear stress','Add only the mean stresses','Use static yield strength only'],answer:0,explanation:'For simultaneous normal and shear action, the principal-stress range is used for fatigue evaluation.',source:S},
{id:'ch17-comb-2',title:'Normal-stress direction',level:'core',kind:'concept',q:'How does the chapter define normal stress for the combined-stress fatigue discussion?',choices:['Stress perpendicular to the direction of the potential fatigue crack','Stress parallel to every crack by definition','Only vertical gravity stress','Only residual stress'],answer:0,explanation:'Normal stress is taken perpendicular to the prospective crack direction.',source:S},
{id:'ch17-comb-3',title:'Non-simultaneous combination',level:'core',kind:'formula',q:'Which interaction form is suggested when normal and shear stress effects occur at the same location but not simultaneously?',choices:['(fe/ffd)^3 + (te/tfd)^5 ≤ 1','fe+te=0 always','(fe/ffd)+(te/tfd)=10','fe×te=fy'],answer:0,explanation:'The chapter gives a Miner-type interaction using exponents 3 for normal stress and 5 for shear stress.',math:'\\left(\\frac{f_e}{f_{fd}}\\right)^3+\\left(\\frac{\\tau_e}{\\tau_{fd}}\\right)^5\\le1',source:S},
{id:'ch17-comb-4',title:'Subscript e',level:'core',kind:'recognition',q:'In the combined-stress equation, what does subscript e denote?',choices:['Calculated equivalent stress range','Elastic modulus','Endurance time in years','Eccentricity only'],answer:0,explanation:'The source defines e as the equivalent stress range calculated for fatigue assessment.',source:S},
{id:'ch17-comb-5',title:'Subscript fd',level:'application',kind:'recognition',q:'What does subscript fd denote in the combined-stress interaction?',choices:['Design fatigue strength for the detail','Factored dead load','Flange depth','Final deformation'],answer:0,explanation:'The denominator uses the design fatigue strength appropriate to the detail and stress type.',source:S},
{id:'ch17-comb-6',title:'Interaction judgement',level:'retrieval',kind:'reasoning',q:'If the combined-stress interaction value exceeds 1.0, what is the design implication?',choices:['The fatigue check is not satisfied','The detail is automatically safe','No fatigue assessment is needed','The member becomes compression-only'],answer:0,explanation:'The stated criterion requires the interaction sum not to exceed unity.',source:S}
]);
add('17:Fatigue Analysis of Building Frames',[
{id:'ch17-frame-1',title:'Ordinary building practice',level:'foundation',kind:'concept',q:'Why is fatigue usually not a governing design check for ordinary building members?',choices:['Typical cyclic stresses and occurrence frequencies are generally too low to govern','Buildings never experience any changing load','Steel cannot fatigue in buildings','Dead load reverses every second'],answer:0,explanation:'The chapter notes that ordinary building cyclic demands are generally low compared with fatigue-sensitive structures such as bridges and cranes.',source:S},
{id:'ch17-frame-2',title:'Wind and earthquake',level:'core',kind:'recognition',q:'What does the chapter state about routine fatigue analysis of steel building frames subjected to wind or earthquakes?',choices:['It is not presently required in the cited code context','It is always the primary design check','It replaces strength and ductility checks','It is required for every dead-load case'],answer:0,explanation:'The source says fatigue analysis is not presently required for steel structures subjected to wind or earthquakes in the cited framework.',source:S},
{id:'ch17-frame-3',title:'Seismic philosophy',level:'core',kind:'reasoning',q:'Why is low-cycle fatigue still conceptually relevant to severe earthquake response?',choices:['Strong earthquakes may cause repeated inelastic deformation and structural damage','Earthquakes produce only static elastic stress','Ductility prevents all yielding','Seismic loading contains no reversals'],answer:0,explanation:'Seismic design permits inelastic action, so deformation-based low-cycle fatigue concepts can become relevant even if not explicit in routine code checks.',source:S},
{id:'ch17-frame-4',title:'Fatigue-rule regimes',level:'core',kind:'classification',q:'According to the chapter summary table, which fatigue regime is associated with buildings under seismic loading?',choices:['Very low-cycle inelastic-deformation regime','Only high-cycle elastic regime','No-deformation regime','Pure corrosion regime'],answer:0,explanation:'The source table associates seismic building response with relatively few cycles and generalized inelastic deformation ranges.',source:S},
{id:'ch17-frame-5',title:'Code focus',level:'application',kind:'reasoning',q:'Which properties does the chapter say seismic design codes primarily emphasize?',choices:['Stiffness, strength and ductility','Only fatigue category number','Only corrosion resistance','Only paint thickness'],answer:0,explanation:'The cited seismic-design approach focuses on stiffness, strength and ductility, accepting some inelastic damage in strong events.',source:S},
{id:'ch17-frame-6',title:'High-cycle versus seismic',level:'retrieval',kind:'comparison',q:'What is the central parameter shift from high-cycle fatigue to the seismic low-cycle regime described in the chapter?',choices:['From stress range toward deformation or inelastic deformation range','From deformation to paint colour','From cycles to density only','From stress range to corrosion rate only'],answer:0,explanation:'The chapter contrasts stress-range-based high-cycle fatigue with deformation-based treatment for low-cycle seismic response.',source:S}
]);
add('17:Examples',[
{id:'ch17-ex-1',title:'Example 21.1 cycles',level:'foundation',kind:'numerical',q:'In Example 21.1, a crane makes 3 trips/hour for 8 hours/day, 200 days/year over 50 years. How many stress cycles are counted?',choices:['240,000','24,000','2,400,000','80,000'],answer:0,explanation:'N=3×8×200×50=240,000 cycles.',math:'N=3\\times8\\times200\\times50=240000',source:S},
{id:'ch17-ex-2',title:'Example detail class',level:'core',kind:'retrieval',q:'Which detail category is used for the ISMB 400 gantry girder in Example 21.1?',choices:['Category 118','Category 36','Category 1600','Category 5'],answer:0,explanation:'The worked example identifies the beam detail as category 118.',source:S},
{id:'ch17-ex-3',title:'Example moment',level:'core',kind:'numerical',q:'For the Example 21.1 central load of 120 kN on a 6 m simply supported girder, what maximum moment is used?',choices:['180 kN·m','360 kN·m','60 kN·m','720 kN·m'],answer:0,explanation:'For a central point load, M=PL/4=120×6/4=180 kN·m.',math:'M=PL/4=120\\times6/4=180\\text{ kN m}',source:S},
{id:'ch17-ex-4',title:'Example stress range',level:'core',kind:'retrieval',q:'What actual normal stress range is obtained in Example 21.1?',choices:['176 MPa','282.26 MPa','16.85 MPa','324.6 MPa'],answer:0,explanation:'The example obtains fmax=176 MPa and fmin=0, giving a 176 MPa stress range.',source:S},
{id:'ch17-ex-5',title:'Example decision',level:'application',kind:'reasoning',q:'Why is the gantry girder judged satisfactory in normal-stress fatigue in Example 21.1?',choices:['Actual stress range 176 MPa is below design fatigue strength 282.26 MPa','Actual stress is above yield strength','The cycle count is zero','No detail category is required'],answer:0,explanation:'The comparison 176 < 282.26 MPa satisfies the fatigue-strength check.',source:S},
{id:'ch17-ex-6',title:'Example support shear',level:'retrieval',kind:'numerical',q:'What support shear force is used in Example 21.1?',choices:['60 kN','120 kN','180 kN','30 kN'],answer:0,explanation:'The 120 kN central load gives a support reaction of 60 kN.',math:'V=120/2=60\\text{ kN}',source:S}
]);
add('17:Summary',[
{id:'ch17-sum-1',title:'Summary: governing variables',level:'foundation',kind:'retrieval',q:'Which combination best summarizes the main variables governing fatigue resistance?',choices:['Stress range, number of cycles and detail category','Density, colour and member name','Only yield stress','Only dead load'],answer:0,explanation:'The chapter repeatedly emphasizes stress range, cycle count and detail severity.',source:S},
{id:'ch17-sum-2',title:'Summary: welded details',level:'core',kind:'reasoning',q:'Why does the summary emphasize welded-detail classification?',choices:['Different weld geometries and defects produce different stress-concentration severity and S-N performance','All welded details have identical fatigue strength','Weld geometry affects only appearance','Detail class is based only on steel density'],answer:0,explanation:'Fatigue strength varies strongly with the stress concentration associated with the detail.',source:S},
{id:'ch17-sum-3',title:'Summary: code method',level:'core',kind:'retrieval',q:'Which fatigue method is described as the basis of IS 800 in this chapter?',choices:['Nominal stress/S-N method','Only strain-life method','Only crack-growth integration','Only creep rupture'],answer:0,explanation:'The chapter develops the nominal stress S-N approach used by the cited structural codes.',source:S},
{id:'ch17-sum-4',title:'Summary: variable history',level:'core',kind:'sequence',q:'Which sequence best summarizes variable-amplitude fatigue assessment?',choices:['Count cycles → assign stress ranges → obtain S-N lives → sum damage fractions','Ignore cycles → use yield stress only','Find dead load → stop','Compute corrosion rate → multiply by span'],answer:0,explanation:'Irregular histories are reduced by cycle counting, evaluated using S-N data, and accumulated with Miner damage.',source:S},
{id:'ch17-sum-5',title:'Summary: detailing',level:'application',kind:'reasoning',q:'Which design action most directly improves fatigue performance according to the chapter?',choices:['Reduce stress concentrations and avoid poor fatigue details','Increase abrupt geometry changes','Add eccentricity','Locate welds at peak stress'],answer:0,explanation:'Good fatigue design is strongly detail-driven: smooth load paths and reduced stress concentrations matter greatly.',source:S},
{id:'ch17-sum-6',title:'Summary: inspection',level:'retrieval',kind:'concept',q:'What complements fail-safe structural redundancy in fatigue-sensitive structures?',choices:['Inspection and access for crack detection','Eliminating all access','Assuming cracks cannot occur','Using only static calculations'],answer:0,explanation:'Fail-safe philosophy depends on detectability, inspection and repair as well as alternate load paths.',source:S}
]);
add('17:Exercises',[
{id:'ch17-exercise-1',title:'Exercise 1 cycle count',level:'foundation',kind:'numerical',q:'For Exercise 1, 3 trips/hour, 6 hours/day, 250 days/year and 60 years gives how many cycles?',choices:['270,000','27,000','2,700,000','90,000'],answer:0,explanation:'N=3×6×250×60=270,000 cycles.',math:'N=3\\times6\\times250\\times60=270000',source:S},
{id:'ch17-exercise-2',title:'Exercise 2 changed use',level:'core',kind:'reasoning',q:'Exercise 2 increases the crane from 3 to 5 trips per hour. What fatigue quantity increases directly?',choices:['Number of stress cycles over the design life','Section modulus automatically','Yield stress','Elastic modulus'],answer:0,explanation:'More trips per hour increase the total number of load and stress cycles.',source:S},
{id:'ch17-exercise-3',title:'Exercise 2 cycle count',level:'core',kind:'numerical',q:'Using 5 trips/hour, 6 hours/day, 250 days/year and 60 years, how many cycles result?',choices:['450,000','45,000','4,500,000','150,000'],answer:0,explanation:'N=5×6×250×60=450,000 cycles.',math:'N=5\\times6\\times250\\times60=450000',source:S},
{id:'ch17-exercise-4',title:'Equivalent stress task',level:'core',kind:'recognition',q:'What does Exercise 3 ask the student to determine using the equivalent-stress method?',choices:['Percentage of fatigue life expended by the loading','Corrosion allowance','Fire resistance time','Euler buckling load'],answer:0,explanation:'Exercise 3 explicitly asks for the percentage of fatigue life expended.',source:S},
{id:'ch17-exercise-5',title:'Reservoir counting task',level:'application',kind:'recognition',q:'What method does Exercise 4 require for the given sequence of stress peaks and valleys?',choices:['Reservoir counting','Moment distribution','Plastic-hinge analysis','Slope-deflection'],answer:0,explanation:'The exercise asks for reservoir counting of the given gantry-girder stress history.',source:S},
{id:'ch17-exercise-6',title:'Exercise detail class',level:'retrieval',kind:'recognition',q:'Which detail category is specified in Exercise 4 for the plate girder with multiple cover plates?',choices:['Category 37','Category 118','Category 160','Category 90'],answer:0,explanation:'The exercise identifies the multiple-cover-plate detail as category 37.',source:S}
]);
add('17:Review Questions',[
{id:'ch17-review-1',title:'Review: crack initiators',level:'foundation',kind:'retrieval',q:'Which two broad features commonly initiate fatigue cracks according to the review material?',choices:['Flaws and stress concentrations','High density and low temperature only','Paint and colour','Member length and mass only'],answer:0,explanation:'The chapter repeatedly identifies flaws and stress concentrations as crack-initiation drivers.',source:S},
{id:'ch17-review-2',title:'Review: weld imperfections',level:'core',kind:'classification',q:'Which is a planar weld imperfection?',choices:['Crack or lack of fusion','Blow hole only','Paint blister only','Uniform mill scale only'],answer:0,explanation:'The chapter classifies cracks and lack of fusion as planar imperfections.',source:S},
{id:'ch17-review-3',title:'Review: cycle terminology',level:'core',kind:'formula',q:'If fmax=90 MPa and fmin=−30 MPa, what is the stress amplitude?',choices:['60 MPa','120 MPa','30 MPa','−60 MPa'],answer:0,explanation:'Amplitude=(90−(−30))/2=60 MPa.',math:'f_a=\\frac{90-(-30)}{2}=60\\text{ MPa}',source:S},
{id:'ch17-review-4',title:'Review: fatigue categories',level:'core',kind:'concept',q:'Why are structural details placed into different fatigue categories?',choices:['Their geometry and fabrication produce different fatigue strengths and S-N curves','Their density differs greatly','Every category has the same fatigue strength','Categories only describe colour'],answer:0,explanation:'Detail categories capture the effect of geometry, welds, holes and stress concentration on fatigue resistance.',source:S},
{id:'ch17-review-5',title:'Review: assessment omission',level:'application',kind:'reasoning',q:'When a stress range is below the relevant fatigue threshold for the detail and loading regime, what may follow?',choices:['A detailed fatigue assessment may not be required under the stated code conditions','Static yield strength becomes zero','The member must automatically be rejected','Cycle counting becomes larger'],answer:0,explanation:'The chapter includes conditions under which fatigue assessment can be omitted when stress ranges are sufficiently low.',source:S},
{id:'ch17-review-6',title:'Review: core design philosophy',level:'retrieval',kind:'concept',q:'What is the most effective broad strategy for fatigue-resistant structural design?',choices:['Control stress range, choose fatigue-friendly details, provide redundancy/inspection where needed','Rely only on higher static yield strength','Ignore weld geometry','Maximize eccentricity'],answer:0,explanation:'Fatigue performance depends on cyclic demand, detail quality, load paths and inspection philosophy rather than static strength alone.',source:S}
]);
})();
