(() => {
const B=window.REVISION_BANK||(window.REVISION_BANK={});
const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
const S12='N. Subramanian, Design of Steel Structures, Ch.12 source-grounded lesson';
const SLOAD='N. Subramanian Ch.12; IS 800:2007 crane-load provisions';
const SFAT='N. Subramanian Ch.12; supplementary fatigue chapter where noted';
add('12:Introduction',[
{id:'ch12-intro-1',title:'Runway purpose',level:'foundation',kind:'concept',q:'What is the primary structural role of a gantry girder in an overhead-crane system?',choices:['Support the crane rail and transfer crane actions to the supporting structure','Support only roof sheeting','Act only as a foundation tie','Carry only wall cladding'],answer:0,explanation:'The gantry girder is the runway beam supporting the crane rail and delivering crane reactions to columns or brackets.',source:S12},
{id:'ch12-intro-2',title:'Runway components',level:'foundation',kind:'recognition',q:'Which item belongs to the crane-runway system described in the chapter?',choices:['Crane rail and its attachments','Only a roof gutter','Only a floor drain','Only a masonry partition'],answer:0,explanation:'The runway system includes the crane, rail and attachments, gantry girder, supports and crane stops.',source:S12},
{id:'ch12-intro-3',title:'Manufacturer data',level:'core',kind:'reasoning',q:'Why is crane-manufacturer information important before final gantry-girder design?',choices:['Wheel spacing, hook approach, clearances and crane reactions affect the structural actions','It determines steel density','It eliminates the need for load placement','It makes impact effects impossible'],answer:0,explanation:'Final design depends on exact crane geometry, loading and clearance data rather than only preliminary estimates.',source:S12},
{id:'ch12-intro-4',title:'Support path',level:'core',kind:'sequence',q:'Which load path is consistent with the chapter description?',choices:['Crane wheel → rail → gantry girder → bracket/column','Crane wheel → roof sheeting → soil','Rail → cladding → purlin only','Crane wheel → paint → foundation directly'],answer:0,explanation:'Wheel reactions pass through the rail into the runway girder and then into the supporting frame.',source:S12},
{id:'ch12-intro-5',title:'Industrial use',level:'application',kind:'classification',q:'Where are gantry girders especially associated with structural steelwork?',choices:['Factories, mills and workshops with overhead travelling cranes','Residential partition walls only','Gravity dams only','Buried pipelines only'],answer:0,explanation:'The chapter introduces gantry girders as industrial crane-runway members.',source:S12},
{id:'ch12-intro-6',title:'Future operation',level:'retrieval',kind:'reasoning',q:'Why can likely future crane-operating requirements matter during planning?',choices:['The supporting runway should be compatible with anticipated crane demands and clearances','They change the modulus of elasticity','They remove all fatigue cycles','They make section properties irrelevant'],answer:0,explanation:'The chapter notes that crane selection and runway design should consider likely future operating needs.',source:S12}
]);
add('12:Loading Considerations',[
{id:'ch12-load-1',title:'More than vertical load',level:'foundation',kind:'concept',q:'Why is gantry-girder loading not represented adequately by vertical wheel reactions alone?',choices:['Impact, transverse surge and longitudinal drag can also act','Vertical wheel loads never occur','Only temperature effects act on cranes','Crane rails eliminate horizontal actions'],answer:0,explanation:'The chapter includes vertical wheel effects together with dynamic and horizontal crane actions.',source:SLOAD},
{id:'ch12-load-2',title:'Impact allowance',level:'core',kind:'concept',q:'What does an impact allowance represent in crane-runway design?',choices:['Dynamic increase associated with crane operation superimposed on vertical loading','A reduction in steel density','Only thermal expansion of the rail','A corrosion allowance'],answer:0,explanation:'Vertical crane loading is increased to account for dynamic effects from operation.',source:SLOAD},
{id:'ch12-load-3',title:'Surge direction',level:'core',kind:'classification',q:'How is the lateral surge load oriented relative to the crane runway?',choices:['Transversely across the crane rail direction','Only vertically downward','Only along the rail','Only through the column axis'],answer:0,explanation:'Surge is the transverse horizontal action associated with trolley/crab acceleration or braking.',source:SLOAD},
{id:'ch12-load-4',title:'Drag direction',level:'core',kind:'classification',q:'How is longitudinal drag oriented?',choices:['Along the crane rail/runway direction','Across the rail only','Only vertically','Normal to every structural plane'],answer:0,explanation:'Longitudinal crane braking or acceleration produces a horizontal action along the runway.',source:SLOAD},
{id:'ch12-load-5',title:'Crane effects in imposed load',level:'application',kind:'reasoning',q:'Which group of effects does IS 800 require to be considered under crane imposed loads?',choices:['Vertical loads, eccentricity effects, impact, surge and longitudinal thrust','Only self-weight of the gantry girder','Only roof live load','Only wind on cladding'],answer:0,explanation:'IS 800 explicitly lists vertical, eccentricity, impact, transverse surge and longitudinal crane effects.',source:SLOAD},
{id:'ch12-load-6',title:'Preliminary versus final loading',level:'retrieval',kind:'reasoning',q:'What is the safest interpretation of preliminary crane-load estimates?',choices:['Useful for initial sizing, but final design should use manufacturer data','They permanently replace manufacturer information','They remove moving-load effects','They guarantee fatigue safety'],answer:0,explanation:'The chapter permits preliminary estimates but requires final checking against actual crane data.',source:S12}
]);
add('12:Maximum Load Effects',[
{id:'ch12-max-1',title:'Moving-wheel consequence',level:'foundation',kind:'concept',q:'Why do gantry-girder bending moment and shear change during crane travel?',choices:['The wheel reactions move along the span','Steel modulus changes with wheel position','The girder span changes length','Support conditions disappear'],answer:0,explanation:'Moving wheel loads make the internal-force effect depend on load position.',source:S12},
{id:'ch12-max-2',title:'Influence-line tool',level:'core',kind:'recognition',q:'Which analysis tool is used to position crane wheels for maximum response at a chosen section or support?',choices:['Influence line','Mohr circle only','S-N curve','Fire-temperature curve'],answer:0,explanation:'Influence lines directly show how a moving load contributes to a response quantity.',source:S12},
{id:'ch12-max-3',title:'Maximum shear region',level:'core',kind:'reasoning',q:'For a simply supported gantry girder, where is the wheel group generally moved when seeking a maximum support shear effect?',choices:['Close to the support of interest','Always at exact midspan','Outside the span','At a point of zero influence ordinate only'],answer:0,explanation:'Support shear is maximized by placing significant wheel loads near that support.',source:S12},
{id:'ch12-max-4',title:'Maximum moment region',level:'core',kind:'reasoning',q:'For a simply supported runway girder, where is maximum positive bending moment generally associated?',choices:['The mid-span region with the wheel group positioned for maximum moment','Only exactly over a support','Only outside the span','Only where shear is zero by definition for every load pattern'],answer:0,explanation:'The chapter distinguishes wheel placement for maximum moment from placement for maximum shear.',source:S12},
{id:'ch12-max-5',title:'Different effects, different positions',level:'application',kind:'reasoning',q:'Why should the same wheel position not automatically be used for maximum moment and maximum shear checks?',choices:['Each response quantity has a different influence line and therefore a different critical placement','Moment and shear are always identical','Wheel spacing has no effect','Only one wheel can ever act'],answer:0,explanation:'The load arrangement must be positioned specifically for the structural effect being maximized.',source:S12},
{id:'ch12-max-6',title:'Multi-wheel placement',level:'retrieval',kind:'concept',q:'What extra issue appears when a crane has several wheels on the runway girder?',choices:['The whole wheel group and its spacing must be positioned to maximize the selected effect','Wheel spacing may be ignored','Only the heaviest single wheel is ever considered','Influence lines stop being applicable'],answer:0,explanation:'For two-wheel and multi-wheel cases, spacing and group position are part of the moving-load problem.',source:S12}
]);
add('12:Fatigue Effects',[
{id:'ch12-fat-1',title:'Why fatigue matters',level:'foundation',kind:'concept',q:'What makes a gantry girder a fatigue-sensitive member?',choices:['Repeated moving crane loads create stress cycles','It is always loaded only once','Its stress is always above yield','Fatigue requires corrosion only'],answer:0,explanation:'Repeated crane operation creates fluctuating stresses capable of initiating and propagating fatigue cracks.',source:SFAT},
{id:'ch12-fat-2',title:'Below-yield fatigue',level:'core',kind:'reasoning',q:'Can fatigue failure occur when the maximum cyclic stress is below the static yield strength?',choices:['Yes, repeated cycles can cause fatigue failure below yield','No, fatigue requires full-section yielding every cycle','Only in concrete','Only if the girder has zero stress range'],answer:0,explanation:'Fatigue is governed by cyclic stress history and detail sensitivity, not merely by exceeding yield stress.',source:SFAT},
{id:'ch12-fat-3',title:'Stress ratio',level:'core',kind:'formula',q:'Which expression defines the stress ratio R used in the chapter discussion?',choices:['R=f_min/f_max','R=f_max-f_min','R=f_max+f_min','R=f_y/E'],answer:0,explanation:'The chapter identifies stress ratio as minimum stress divided by maximum stress.',math:'R=\\frac{f_{min}}{f_{max}}',source:SFAT},
{id:'ch12-fat-4',title:'Detail sensitivity',level:'core',kind:'reasoning',q:'Which feature can make a gantry-girder detail more fatigue-sensitive?',choices:['A notch, poor fit or weld toe/root stress concentration','A smooth gradual detail with no stress concentration','Zero cyclic loading','A perfectly constant zero stress'],answer:0,explanation:'Stress concentrations at discontinuities and weld details are important fatigue initiation locations.',source:SFAT},
{id:'ch12-fat-5',title:'Cycle count importance',level:'application',kind:'reasoning',q:'Why does crane duty or operating frequency matter in fatigue assessment?',choices:['It controls the number of repeated stress cycles accumulated over the design life','It changes steel density','It eliminates the stress range','It makes detail geometry irrelevant'],answer:0,explanation:'Fatigue resistance depends strongly on both stress range and number of cycles.',source:SFAT},
{id:'ch12-fat-6',title:'Heavy-duty implication',level:'retrieval',kind:'concept',q:'Which crane-runway situation most clearly warrants explicit fatigue attention in the chapter?',choices:['Heavy-duty repeated crane operation','A permanently unloaded runway','A member with no moving load','A decorative rail with no structural action'],answer:0,explanation:'The chapter contrasts lighter duty cases with heavy-duty gantry girders that require fatigue checking.',source:SFAT}
]);
add('12:Selection of Gantry Girder',[
{id:'ch12-select-1',title:'Section-selection drivers',level:'foundation',kind:'concept',q:'Which demand set should influence selection of a gantry-girder section?',choices:['Vertical, horizontal, local wheel and serviceability demands','Only paint thickness','Only self-weight with no crane load','Only thermal strain'],answer:0,explanation:'The section must satisfy combined crane actions, local effects and deflection requirements.',source:S12},
{id:'ch12-select-2',title:'Rolled-section use',level:'core',kind:'classification',q:'For shorter spans and lighter cranes, what type of runway member can be appropriate?',choices:['A rolled beam, sometimes strengthened with plates, channels or angles','Only a massive box girder','Only a cable','Only a concrete arch'],answer:0,explanation:'The chapter lists rolled sections with strengthening components for lighter-duty and shorter-span applications.',source:S12},
{id:'ch12-select-3',title:'Plate-girder use',level:'core',kind:'classification',q:'When does a plate girder become a more natural gantry-girder option?',choices:['For larger spans or heavier demands beyond efficient rolled-section use','Only for zero-load runways','Only when no rail is present','Only where bending is absent'],answer:0,explanation:'Fabricated plate girders are among the options for larger span and load demands.',source:S12},
{id:'ch12-select-4',title:'Box-girder use',level:'core',kind:'recognition',q:'Which section form is listed as an option for long-span crane runways?',choices:['Box girder','Timber batten only','Masonry lintel only','Solid concrete cube'],answer:0,explanation:'The chapter includes box girders among long-span runway alternatives.',source:S12},
{id:'ch12-select-5',title:'Why single span?',level:'application',kind:'reasoning',q:'Why are single-span gantry girders generally preferred over two-span systems in the chapter?',choices:['They avoid uplift, settlement sensitivity and maintenance complications','They eliminate impact','They prevent all fatigue','They require no supports'],answer:0,explanation:'The source specifically points to practical complications of two-span runway girders.',source:S12},
{id:'ch12-select-6',title:'Not strength alone',level:'retrieval',kind:'reasoning',q:'Why can the smallest section satisfying only vertical bending be an inadequate gantry-girder choice?',choices:['Horizontal action, local wheel effects, stability and deflection also have to be satisfied','Vertical bending is never present','Steel sections have no minor-axis strength','Serviceability is irrelevant'],answer:0,explanation:'Section selection is controlled by multiple limit states, not one vertical bending check.',source:S12}
]);
add('12:Design of Gantry Girder',[
{id:'ch12-design-1',title:'Iterative design',level:'foundation',kind:'sequence',q:'Why is gantry-girder design described as iterative?',choices:['A trial section is selected, checked for several effects and revised if necessary','The first guessed section is always final','Loads are ignored after section selection','Only one check is required'],answer:0,explanation:'The procedure cycles through trial sizing, property evaluation and multiple strength/serviceability checks.',source:S12},
{id:'ch12-design-2',title:'First loading step',level:'core',kind:'sequence',q:'What loading quantity is established early in the design procedure?',choices:['Maximum wheel load including impact','Only girder paint weight','Only wind on the roof','Only column base shear'],answer:0,explanation:'The design sequence starts from crane wheel actions including impact before calculating governing effects.',source:S12},
{id:'ch12-design-3',title:'Biaxial response',level:'core',kind:'reasoning',q:'Why is bending about both principal axes checked?',choices:['Vertical crane loading and horizontal crane action bend the girder in different planes','The girder carries no vertical load','All steel beams are always biaxially bent','Minor-axis bending is caused by temperature only'],answer:0,explanation:'The top flange and overall girder must resist horizontal action in addition to major-axis vertical bending.',source:S12},
{id:'ch12-design-4',title:'Compression-flange stability',level:'core',kind:'reasoning',q:'When is a buckling-resistance check especially necessary for the gantry girder?',choices:['When the compression flange is not adequately laterally restrained','Whenever the girder is fully braced at every point','Only when no bending exists','Only after fatigue failure'],answer:0,explanation:'An unrestrained compression flange can be vulnerable to lateral stability failure.',source:S12},
{id:'ch12-design-5',title:'Local web check',level:'application',kind:'reasoning',q:'Why is the web checked at wheel loads and support reactions?',choices:['Concentrated forces can cause local buckling or crushing of the web','The web carries no local force','Only the flange can experience concentration effects','Support reactions never enter the web'],answer:0,explanation:'Concentrated wheel and reaction forces can locally distress the web even when global bending is satisfactory.',source:S12},
{id:'ch12-design-6',title:'Serviceability closeout',level:'retrieval',kind:'concept',q:'Which serviceability quantity remains part of the final gantry-girder design check?',choices:['Deflection','Only steel density','Only bolt colour','Only corrosion allowance'],answer:0,explanation:'The design procedure includes deflection in addition to strength and stability checks.',source:S12}
]);
add('12:Examples',[
{id:'ch12-ex-1',title:'Example scope',level:'foundation',kind:'concept',q:'What distinguishes the Chapter 12 worked examples from a simple single-load beam problem?',choices:['They combine moving wheels, horizontal crane actions, section checks and serviceability','They use only a fixed uniform load','They ignore wheel placement','They check only paint'],answer:0,explanation:'The examples integrate the full crane-runway design workflow.',source:S12},
{id:'ch12-ex-2',title:'Strength plus serviceability',level:'core',kind:'reasoning',q:'Why does a worked gantry-girder example calculate deflection as well as stresses?',choices:['A member can satisfy strength yet still fail a serviceability requirement','Deflection determines steel density','Stress checks are unnecessary','Serviceability applies only to concrete'],answer:0,explanation:'The examples deliberately treat strength and deflection as separate design requirements.',source:S12},
{id:'ch12-ex-3',title:'Wheel placement first',level:'core',kind:'sequence',q:'Before selecting a final section in a moving-wheel example, what analytical task must be completed?',choices:['Determine critical wheel positions and resulting maximum actions','Choose paint colour','Ignore wheel spacing','Assume every response is maximum at midspan'],answer:0,explanation:'Governing moving-load effects must be established before the section can be checked properly.',source:S12},
{id:'ch12-ex-4',title:'Horizontal effect',level:'core',kind:'reasoning',q:'Why do the examples retain horizontal crane actions after vertical moment has been found?',choices:['The section must also resist minor-axis or lateral effects from crane operation','Horizontal actions cannot reach the girder','Vertical moment automatically includes surge','Horizontal loads affect only foundations'],answer:0,explanation:'The runway member is subjected to combined vertical and horizontal effects.',source:S12},
{id:'ch12-ex-5',title:'Restraint assumption',level:'application',kind:'reasoning',q:'Why must the assumed lateral restraint condition be stated in a worked example?',choices:['It changes whether lateral buckling resistance has to be checked','It changes steel density','It removes support reactions','It changes the number of crane wheels'],answer:0,explanation:'Compression-flange restraint is a key stability assumption.',source:S12},
{id:'ch12-ex-6',title:'Integrated workflow',level:'retrieval',kind:'sequence',q:'Which sequence best reflects the worked-example logic?',choices:['Loads and wheel positions → actions → trial section → strength/stability/web checks → deflection','Deflection → paint → wheel spacing ignored → finish','Section chosen permanently before loads → no checks','Fatigue only → no bending calculation'],answer:0,explanation:'The examples progress from loading and placement to section verification and serviceability.',source:S12}
]);
add('12:Summary',[
{id:'ch12-sum-1',title:'Core complication',level:'foundation',kind:'concept',q:'What two features make gantry-girder design more involved than an ordinary static beam?',choices:['Moving crane loads and repeated/fatigue effects','Only self-weight and paint','Only uniform temperature','Only axial tension'],answer:0,explanation:'The chapter summary emphasizes moving loads and fatigue as central complications.',source:S12},
{id:'ch12-sum-2',title:'Final-data rule',level:'core',kind:'retrieval',q:'What should replace preliminary assumptions before final design?',choices:['Exact crane loading and clearance data from the manufacturer','A random wheel spacing','Only the girder self-weight','A roof-load table'],answer:0,explanation:'Manufacturer data are required for final loading and geometry verification.',source:S12},
{id:'ch12-sum-3',title:'Maximum-effect coverage',level:'core',kind:'classification',q:'Which response quantities are highlighted for moving-load calculation in the chapter summary?',choices:['Bending, shear and deflection','Only axial tension','Only torsion','Only temperature strain'],answer:0,explanation:'The summary refers to maximum bending/shear/deflection calculations for crane wheel loading.',source:S12},
{id:'ch12-sum-4',title:'Section choice',level:'core',kind:'reasoning',q:'What follows naturally after determining governing crane actions?',choices:['Select and verify an appropriate runway-girder section','Ignore section properties','Change steel chemistry','Remove the rail'],answer:0,explanation:'Loading analysis feeds into section selection and the step-by-step design checks.',source:S12},
{id:'ch12-sum-5',title:'Connection context',level:'application',kind:'concept',q:'Besides the girder cross-section itself, what supporting detail is included in the chapter summary?',choices:['Column/bracing connection details','Only roof drainage','Only slab reinforcement','Only soil classification'],answer:0,explanation:'The summary notes supporting and bracing connection considerations as part of runway design.',source:S12},
{id:'ch12-sum-6',title:'Whole-chapter retrieval',level:'retrieval',kind:'reasoning',q:'Which statement best captures the chapter design philosophy?',choices:['Establish realistic crane actions, find their critical moving-load effects, then check strength, stability, local response, fatigue and serviceability','Check only vertical bending once','Select a section before knowing the crane','Ignore repeated loading'],answer:0,explanation:'The chapter combines loading, moving-load analysis, fatigue, section selection and complete verification.',source:S12}
]);
add('12:Exercises',[
{id:'ch12-exer-1',title:'Exercise purpose',level:'foundation',kind:'concept',q:'Why do the exercises vary crane capacity, span, wheel spacing and restraint conditions?',choices:['To make the learner repeat the complete design workflow under different realistic conditions','To show that those variables never matter','To test only steel density','To avoid section design'],answer:0,explanation:'The exercise set is intended to develop transferable full-design skill rather than one memorized solution.',source:S12},
{id:'ch12-exer-2',title:'Two-crane case',level:'core',kind:'reasoning',q:'What additional challenge is introduced by an exercise involving two cranes?',choices:['More than one moving-load system may contribute to the governing effect','All wheel loads disappear','Influence lines become invalid','Only dead load remains'],answer:0,explanation:'Multiple crane systems require careful placement and combination of moving reactions.',source:S12},
{id:'ch12-exer-3',title:'Unrestrained case',level:'core',kind:'classification',q:'What extra concern is emphasized when an exercise specifies an unrestrained gantry girder?',choices:['Lateral stability of the compression flange/member','Concrete punching shear only','Soil liquefaction only','No strength checks'],answer:0,explanation:'Unrestrained compression regions require buckling resistance verification.',source:S12},
{id:'ch12-exer-4',title:'Plate-girder alternative',level:'core',kind:'reasoning',q:'Why might an exercise ask for a welded plate-girder alternative?',choices:['To practise section selection and design when rolled sections are not the only feasible solution','To eliminate bending','To make wheel spacing irrelevant','To avoid fabrication considerations'],answer:0,explanation:'The chapter includes fabricated runway forms for larger demands.',source:S12},
{id:'ch12-exer-5',title:'Changing rail weight',level:'application',kind:'reasoning',q:'Why does changing rail weight affect the exercise solution?',choices:['The rail contributes permanent load to the runway girder','Rail weight changes Young’s modulus','Rail weight eliminates crane impact','Rail weight changes wheel spacing automatically'],answer:0,explanation:'Rail self-weight contributes to the permanent load carried by the gantry girder.',source:S12},
{id:'ch12-exer-6',title:'Exercise completion',level:'retrieval',kind:'sequence',q:'Which set of tasks indicates that a gantry-girder exercise has been completed rather than partially attempted?',choices:['Critical load placement, section selection, strength/stability/local checks and serviceability verification','Only one bending-moment calculation','Only identification of the crane type','Only drawing the rail'],answer:0,explanation:'The exercises are complete-design problems covering the full chain of verification.',source:S12}
]);
add('12:Review Questions',[
{id:'ch12-rev-1',title:'Review breadth',level:'foundation',kind:'concept',q:'What does the Chapter 12 review section test?',choices:['Crane types, runway components, loads, moving effects, fatigue, section choice and design checks','Only steel density','Only fire resistance','Only corrosion'],answer:0,explanation:'The review questions intentionally audit the entire chapter.',source:S12},
{id:'ch12-rev-2',title:'Surge versus drag',level:'core',kind:'classification',q:'Which distinction should a learner be able to state after the review?',choices:['Surge is transverse; drag is longitudinal','Surge is vertical; drag is thermal','Both are identical vertical loads','Neither is a crane action'],answer:0,explanation:'The review explicitly tests the directional distinction between the two horizontal crane effects.',source:SLOAD},
{id:'ch12-rev-3',title:'Impact review',level:'core',kind:'concept',q:'Why are impact allowances included among the review topics?',choices:['Crane operation introduces dynamic amplification beyond static vertical wheel load','Impact changes steel density','Impact is a corrosion mechanism','Impact only affects roof cladding'],answer:0,explanation:'Dynamic crane operation requires an impact allowance in vertical loading.',source:SLOAD},
{id:'ch12-rev-4',title:'Rail attachment',level:'core',kind:'reasoning',q:'Why can rail attachment appear in a structural review of gantry girders?',choices:['The rail and its attachment form part of the load-transfer and runway system','The rail is decorative only','The rail carries no wheel force','Attachment has no structural role'],answer:0,explanation:'The rail transfers wheel actions into the gantry girder and is part of the runway system.',source:S12},
{id:'ch12-rev-5',title:'Moving-load review',level:'application',kind:'reasoning',q:'What key analysis principle should be recalled when asked how maximum wheel-load effects are obtained?',choices:['Position the moving wheel group using the relevant influence line','Place every wheel at midspan for every effect','Ignore wheel spacing','Use only a fatigue S-N curve'],answer:0,explanation:'Critical wheel placement depends on the response quantity being maximized.',source:S12},
{id:'ch12-rev-6',title:'Design-check recall',level:'retrieval',kind:'classification',q:'Which list most closely matches the final checks reviewed for a gantry girder?',choices:['Biaxial bending, stability, local web response, fatigue where relevant, and deflection','Only axial tension','Only concrete shear','Only paint adhesion'],answer:0,explanation:'The chapter review spans the multiple strength, stability, fatigue and serviceability checks unique to crane runways.',source:S12}
]);
})();
