Object.assign(window.REVISION_BANK,{
'2:Design Considerations':[
{id:'dc-purpose',title:'Purpose of design considerations',level:'foundation',kind:'concept',q:'Why does structural design begin with design considerations rather than member sizing?',choices:['The designer must first define safety, serviceability, economy and other performance needs','Member sizes are fixed before loads are known','Only appearance matters at the start','Analysis is unnecessary in steel design'],answer:0,explanation:'The chapter treats design as a broader decision process in which performance requirements guide analysis and proportioning.',source:'Subramanian Ch.2 Design Considerations'},
{id:'dc-economy',title:'Economy in design',level:'core',kind:'reasoning',q:'Which statement best reflects economy in structural design?',choices:['Economy must be balanced with safety, serviceability and constructability','The lightest possible section is always the best design','The cheapest material always gives the lowest life-cycle cost','Safety factors may be ignored to reduce cost'],answer:0,explanation:'Economy is one design objective among several and cannot override required performance.',source:'Subramanian Ch.2 Design Considerations'},
{id:'dc-durability',title:'Durability as a design consideration',level:'core',kind:'concept',q:'Why is durability considered during structural design?',choices:['The structure must retain satisfactory performance over its intended service life','Durability affects only temporary works','Corrosion cannot influence steel structures','Durability is unrelated to maintenance'],answer:0,explanation:'The textbook links present-day design to service life, maintenance and long-term environmental exposure.',source:'Subramanian Ch.2; supplementary corrosion chapter cross-reference'},
{id:'dc-constructability',title:'Constructability',level:'application',kind:'reasoning',q:'A structurally adequate detail is very difficult to fabricate and erect. Which design consideration has been neglected?',choices:['Constructability','Density','Poisson ratio','Thermal conductivity only'],answer:0,explanation:'A practical design must be capable of fabrication, transport and erection, not merely satisfy calculation checks.',source:'Subramanian Ch.2 Design Considerations'},
{id:'dc-lifecycle',title:'Life-cycle view',level:'application',kind:'concept',q:'Which choice is most consistent with a life-cycle design viewpoint?',choices:['Consider initial cost together with maintenance and durability','Consider only purchase price of steel','Ignore future inspection access','Assume no deterioration can occur'],answer:0,explanation:'The chapter broadens design beyond initial cost to long-term performance and life-cycle implications.',source:'Subramanian Ch.2 Design Considerations'},
{id:'dc-balance',title:'Balanced design judgement',level:'retrieval',kind:'concept',q:'Which combination best represents the broad design concerns developed in Chapter 2?',choices:['Safety, serviceability, economy, durability and constructability','Density, colour and supplier name only','Only ultimate strength','Only architectural appearance'],answer:0,explanation:'Chapter 2 frames structural design as balancing several performance and practical objectives.',source:'Subramanian Ch.2 Design Considerations'}
],
'2:Steps Involved in Construction':[
{id:'steps-sequence',title:'Project sequence',level:'foundation',kind:'sequence',q:'Which sequence best represents the normal progression of a structural project?',choices:['Planning/design → detailing/fabrication → erection/construction → service','Erection → loading definition → design → planning','Painting → demolition → design → analysis','Inspection → mining → analysis only'],answer:0,explanation:'The chapter presents construction as a sequence from conception and design through fabrication and erection to completed service.',source:'Subramanian Ch.2 Steps Involved in Construction'},
{id:'steps-design-input',title:'Early design inputs',level:'core',kind:'concept',q:'Before final member design, what must be established?',choices:['Structural system, actions and performance requirements','Final bolt count without any loads','Paint colour only','The demolition method only'],answer:0,explanation:'Design depends on a defined structural system, loading and required performance.',source:'Subramanian Ch.2 Steps Involved in Construction'},
{id:'steps-detailing',title:'Role of detailing',level:'core',kind:'concept',q:'Why does detailing follow structural analysis and member design?',choices:['Calculated member and connection requirements must be converted into information that can be fabricated and erected','Detailing determines gravity','Detailing replaces analysis','Detailing is only decorative'],answer:0,explanation:'Detailing translates the design intent into buildable dimensions and connection information.',source:'Subramanian Ch.2 Steps Involved in Construction'},
{id:'steps-fabrication',title:'Fabrication stage',level:'application',kind:'classification',q:'Which activity belongs primarily to fabrication rather than structural analysis?',choices:['Cutting, drilling and assembling steel components','Computing frame reactions','Selecting load combinations','Checking overall stability'],answer:0,explanation:'Fabrication physically prepares steel components according to the design and drawings.',source:'Subramanian Ch.2 with Ch.1 fabrication context'},
{id:'steps-erection',title:'Erection awareness',level:'application',kind:'reasoning',q:'Why must the designer consider erection while developing the structure?',choices:['Temporary construction stages can have different restraint and load conditions from the completed structure','Erection never changes stability','All members are fully braced before they are lifted','Construction sequence cannot affect force paths'],answer:0,explanation:'Temporary stages can govern stability or detailing and must be compatible with the intended construction sequence.',source:'Subramanian Ch.2 Steps Involved in Construction'},
{id:'steps-feedback',title:'Design-construction feedback',level:'retrieval',kind:'reasoning',q:'If a connection cannot be fabricated with available shop capabilities, what is the appropriate response?',choices:['Revise the design/detail while maintaining required structural performance','Ignore the fabrication limitation','Reduce required strength without checking','Omit the connection'],answer:0,explanation:'The chapter emphasizes coordination between design intent and practical construction capability.',source:'Subramanian Ch.2; Chapter review context'}
],
'2:Role and Responsibilities of the Designer':[
{id:'designer-safety',title:'Primary professional responsibility',level:'foundation',kind:'concept',q:'Which responsibility is fundamental for the structural designer?',choices:['Provide a structure that satisfies required safety and performance criteria','Maximise steel weight','Avoid documenting assumptions','Delegate all structural judgement to the fabricator'],answer:0,explanation:'The designer is responsible for structural adequacy and for communicating the design basis and intent.',source:'Subramanian Ch.2 Role and Responsibilities of the Designer'},
{id:'designer-behaviour',title:'Visualise structural behaviour',level:'core',kind:'reasoning',q:'Why should a structural engineer visualise the behaviour of the whole structure as well as individual members?',choices:['System force paths and stability can govern even when isolated members appear adequate','Members never interact','Connections cannot redistribute forces','Only member self-weight matters'],answer:0,explanation:'The source stresses understanding system behaviour, not merely checking separate member capacities.',source:'Subramanian Ch.2 review questions; uploaded quiz Q13'},
{id:'designer-fabrication',title:'Know fabrication capability',level:'core',kind:'concept',q:'Why should a designer understand fabrication-shop capabilities?',choices:['Details must be practical to manufacture and inspect','Fabrication has no relation to structural design','It changes the yield strength specified by the code','It eliminates the need for drawings'],answer:0,explanation:'Practical knowledge of fabrication helps avoid details that are difficult, unsafe or uneconomic to produce.',source:'Subramanian Ch.2 review context; uploaded quiz Q13'},
{id:'designer-welds',title:'Weld quality awareness',level:'application',kind:'concept',q:'Why should a structural engineer understand weld defects and non-destructive testing?',choices:['Connection performance depends on fabrication quality and defects may require inspection','Weld defects affect appearance only','Welds are always defect-free','Testing is relevant only to concrete'],answer:0,explanation:'The chapter review material expects the designer to understand fabrication quality, weld defects and inspection methods.',source:'Uploaded textbook quiz Q13'},
{id:'designer-communication',title:'Communicate design intent',level:'application',kind:'reasoning',q:'Which action best demonstrates the designer responsibility to communicate design intent?',choices:['Provide clear drawings, specifications and critical assumptions','Leave connection requirements undefined','Rely on verbal memory only','Omit load information'],answer:0,explanation:'Design information must be conveyed clearly so fabrication and construction match the structural assumptions.',source:'Subramanian Ch.2 Role and Responsibilities of the Designer'},
{id:'designer-ethics',title:'Professional judgement',level:'retrieval',kind:'reasoning',q:'A proposed change reduces cost but creates an unverified stability risk. What should govern the designer decision?',choices:['Required safety and verified structural behaviour','Cost reduction alone','Speed regardless of consequence','Aesthetic preference alone'],answer:0,explanation:'Professional responsibility requires safety and structural adequacy to govern decisions.',source:'Subramanian Ch.2 Role and Responsibilities of the Designer'}
],
'2:Structural Systems':[
{id:'systems-definition',title:'Meaning of structural system',level:'foundation',kind:'concept',q:'What is a structural system?',choices:['An arrangement of connected members that transfers actions to the supports and foundations','A list of steel grades only','A single isolated bolt','Only the architectural facade'],answer:0,explanation:'A structural system provides the overall load path through interacting members and connections.',source:'Subramanian Ch.2 Structural Systems'},
{id:'systems-loadpath',title:'Load path',level:'core',kind:'reasoning',q:'What is meant by a load path?',choices:['The route by which applied actions are transferred through structural components to the supports/foundation','The transport route from mill to site','The painted line on a beam','The order of drawing sheets'],answer:0,explanation:'Structural-system behaviour depends on a continuous and understandable transfer of forces to the ground.',source:'Subramanian Ch.2 Structural Systems'},
{id:'systems-frame',title:'Framed structure',level:'core',kind:'classification',q:'Which arrangement is most clearly a framed structural system?',choices:['Beams and columns connected to transfer loads through a frame','An isolated steel plate lying on the ground','A paint coating','A single loose bolt'],answer:0,explanation:'Frames use connected line members to transfer loads and provide stiffness/stability.',source:'Subramanian Ch.2 Structural Systems; uploaded quiz Q14-Q15 context'},
{id:'systems-simple-connection',title:'Simple construction idealisation',level:'application',kind:'concept',q:'In the textbook quiz description of simple construction, beam ends are idealised primarily to transfer:',choices:['Shear','Full plastic moment only','Torsion only','No force'],answer:0,explanation:'The uploaded textbook quiz states that in simple construction beam-end connections are treated as transmitting shear only.',source:'Uploaded textbook quiz Q15'},
{id:'systems-3d',title:'Three-dimensional behaviour',level:'application',kind:'reasoning',q:'Why may a dome require three-dimensional structural analysis?',choices:['Its load paths and geometry act in more than one plane','A dome is always a straight beam','Three-dimensional effects occur only in concrete','Steel cannot form spatial systems'],answer:0,explanation:'Spatial systems require analysis that represents their three-dimensional force transfer.',source:'Uploaded textbook quiz Q15'},
{id:'systems-selection',title:'Selecting a structural system',level:'retrieval',kind:'reasoning',q:'Which factor should influence selection of a structural system?',choices:['Load path, span, stability, construction and functional requirements','Only section colour','Only density of air','Only drawing scale'],answer:0,explanation:'System choice must satisfy structural, functional and construction requirements together.',source:'Subramanian Ch.2 Structural Systems'}
],
'2:Structural Integrity':[
{id:'integrity-meaning',title:'Meaning of structural integrity',level:'foundation',kind:'concept',q:'What does structural integrity primarily seek to ensure?',choices:['The structure has continuity and robustness so local damage does not cause disproportionate collapse','Every member has the same section size','All connections are pinned','No deformation ever occurs'],answer:0,explanation:'Integrity concerns tying the structure together and limiting the consequences of local damage.',source:'Subramanian Ch.2 Structural Integrity'},
{id:'integrity-continuity',title:'Continuity and robustness',level:'core',kind:'reasoning',q:'Why is continuity between structural elements important for integrity?',choices:['It can provide alternate force transfer when a local element is damaged','It guarantees zero stress','It removes all accidental actions','It makes material strength irrelevant'],answer:0,explanation:'Continuity and tying can help redistribute forces and reduce vulnerability to progressive collapse.',source:'Subramanian Ch.2 Structural Integrity'},
{id:'integrity-local',title:'Local damage versus global collapse',level:'core',kind:'concept',q:'Which outcome is structural-integrity provisions intended to avoid?',choices:['A small local failure triggering collapse of a large part of the structure','A local paint scratch','Normal elastic deflection','Routine inspection'],answer:0,explanation:'Robustness aims to prevent disproportionate consequences from limited local damage.',source:'Subramanian Ch.2 Structural Integrity'},
{id:'integrity-ties',title:'Role of ties',level:'application',kind:'concept',q:'Why are horizontal ties used as an integrity measure?',choices:['They help maintain continuity and provide tensile tying between parts of the structure','They are provided only for architectural colour','They eliminate gravity loads','They replace all columns'],answer:0,explanation:'Ties contribute to structural continuity and robustness under abnormal/local-damage scenarios.',source:'Subramanian Ch.2 Structural Integrity; uploaded quiz Q16'},
{id:'integrity-accidental',title:'Abnormal events',level:'application',kind:'reasoning',q:'Structural integrity is especially relevant when considering:',choices:['Accidental or abnormal local damage','Only routine dead load with no damage scenario','Only steel density','Only paint thickness'],answer:0,explanation:'Integrity provisions are associated with robustness under abnormal events or local loss of support/member action.',source:'Subramanian Ch.2 Structural Integrity'},
{id:'integrity-design',title:'Integrity design judgement',level:'retrieval',kind:'reasoning',q:'A building has strong individual members but no reliable alternate load path after one key element is lost. What concern remains?',choices:['Structural integrity/robustness','Material density','Elastic modulus measurement','Surface finish'],answer:0,explanation:'Adequate isolated member strength does not by itself guarantee system robustness.',source:'Subramanian Ch.2 Structural Integrity'}
],
'2:Analysis and Design':[
{id:'ad-difference',title:'Analysis versus design',level:'foundation',kind:'concept',q:'What is the main difference between structural analysis and structural design?',choices:['Analysis determines structural response; design selects/proportions members and details to satisfy requirements','Analysis paints members; design measures density','They are completely unrelated','Design is done before any actions are known'],answer:0,explanation:'Analysis predicts forces, moments and deformations, while design uses those effects to proportion the structure.',source:'Subramanian Ch.2 Analysis and Design'},
{id:'ad-iteration',title:'Why design is iterative',level:'core',kind:'reasoning',q:'Why are analysis and design often iterative?',choices:['Changing member sizes changes stiffness and therefore structural response','Member size never affects stiffness','Analysis results are independent of the model','Only colour changes during design'],answer:0,explanation:'Selected sections alter stiffness and sometimes force distribution, requiring updated analysis/checks.',source:'Subramanian Ch.2 Analysis and Design'},
{id:'ad-determinate',title:'Determinate analysis',level:'core',kind:'concept',q:'For a statically determinate structure, internal forces can be obtained primarily using:',choices:['Equilibrium equations','Material failure criteria only','Paint specifications','Fatigue S-N curves only'],answer:0,explanation:'A determinate system has enough independent equilibrium equations to solve its reactions/internal forces.',source:'Subramanian Ch.2 Analysis and Design'},
{id:'ad-indeterminate',title:'Indeterminate methods',level:'application',kind:'classification',q:'Which is a recognised method for analysing statically indeterminate structures?',choices:['Moment distribution, slope-deflection or matrix methods','Only density measurement','Only tensile testing','Only visual inspection'],answer:0,explanation:'The uploaded textbook quiz lists moment distribution, slope-deflection and matrix methods for indeterminate analysis.',source:'Uploaded textbook quiz Q17'},
{id:'ad-model',title:'Analysis model',level:'application',kind:'reasoning',q:'Why must support and connection assumptions in the analysis model match intended structural behaviour?',choices:['They influence force distribution, moments and deflections','They affect only drawing appearance','They cannot influence results','They matter only after demolition'],answer:0,explanation:'Analysis results depend on the idealisation of restraints, connections and system stiffness.',source:'Subramanian Ch.2 Analysis and Design'},
{id:'ad-check',title:'Design feedback loop',level:'retrieval',kind:'reasoning',q:'After selecting a trial section, what is the designer expected to do?',choices:['Check strength, stability and serviceability and revise if required','Assume it is adequate because it exists in a table','Skip analysis permanently','Check only its mass'],answer:0,explanation:'Design proceeds by trial, analysis/checking and revision until requirements are satisfied.',source:'Subramanian Ch.2 Analysis and Design'}
],
'2:Codes and Specifications':[
{id:'codes-purpose',title:'Purpose of codes',level:'foundation',kind:'concept',q:'Why are structural design codes used?',choices:['To provide agreed minimum requirements and procedures for safe, reliable design','To replace engineering judgement completely','To specify architectural colour only','To guarantee every structure has identical dimensions'],answer:0,explanation:'Codes establish consistent requirements for actions, resistance, serviceability, detailing and safety.',source:'Subramanian Ch.2 Codes and Specifications'},
{id:'codes-is800',title:'Steel design standard',level:'core',kind:'recognition',q:'Which Indian Standard is identified in the uploaded textbook quiz as central to general structural steel design?',choices:['IS 800:2007','IS 456:2000 only','IS 875 Part 1 only','IS 808 only'],answer:0,explanation:'The textbook and quiz use IS 800:2007 as the principal general steel-design standard for this edition.',source:'Uploaded textbook quiz Q18'},
{id:'codes-loads',title:'Loading standard family',level:'core',kind:'recognition',q:'Which standard family in the uploaded quiz is associated with building loads?',choices:['IS 875 Parts 1–5','IS 808 only','IS 456 only','IS 2062 only'],answer:0,explanation:'IS 875 parts are cited for building loads in the textbook course context.',source:'Uploaded textbook quiz Q18'},
{id:'codes-sections',title:'Section dimensions standard',level:'application',kind:'recognition',q:'Which cited standard is associated with dimensions/properties of hot-rolled steel sections in the textbook quiz context?',choices:['IS 808','IS 875','IS 1893 only','IS 1641 only'],answer:0,explanation:'IS 808 is cited with structural steel section dimensions in the textbook quiz.',source:'Uploaded textbook quiz Q18'},
{id:'codes-judgement',title:'Code plus judgement',level:'application',kind:'reasoning',q:'What is the correct role of engineering judgement when using a design code?',choices:['Interpret and apply provisions to a sound structural model and real construction context','Ignore the code whenever convenient','Assume code equations remove the need to understand behaviour','Use only the final numerical answer'],answer:0,explanation:'Codes support but do not replace competent modelling, detailing and professional judgement.',source:'Subramanian Ch.2 Codes and Specifications'},
{id:'codes-edition',title:'Code edition awareness',level:'retrieval',kind:'reasoning',q:'Why should a designer identify the edition of a referenced code?',choices:['Requirements can change between editions and the applicable project basis must be clear','Code editions affect only page colour','Older and newer editions are always identical','Edition is irrelevant to design'],answer:0,explanation:'The project design basis must clearly identify the applicable standard and edition.',source:'Subramanian Ch.2 Codes and Specifications'}
],
'2:Design Philosophies':[
{id:'phil-purpose',title:'Why design philosophies exist',level:'foundation',kind:'concept',q:'What is a design philosophy?',choices:['A framework for relating loads, resistance, uncertainty and acceptable performance','A method for choosing paint colour','A fabrication machine','A steel grade only'],answer:0,explanation:'Design philosophies define how safety and uncertainty are represented in structural calculations.',source:'Subramanian Ch.2 Design Philosophies'},
{id:'phil-wsm',title:'Working stress method',level:'core',kind:'concept',q:'What is the basic idea of the working stress method?',choices:['Keep stresses under service/working loads below permissible stresses derived using factors of safety','Form a plastic mechanism at service load','Ignore elastic behaviour','Apply no safety factor'],answer:0,explanation:'Working stress design uses elastic analysis and permissible stresses reduced from material strengths.',source:'Subramanian Ch.2 Design Philosophies'},
{id:'phil-ultimate',title:'Ultimate load approach',level:'core',kind:'concept',q:'What distinguishes an ultimate/load-factor design approach from working-stress design?',choices:['It focuses on factored loads and ultimate strength rather than only permissible elastic stress','It ignores structural strength','It checks paint thickness only','It requires zero deformation'],answer:0,explanation:'Ultimate-strength approaches explicitly assess resistance at factored load levels.',source:'Subramanian Ch.2 Design Philosophies'},
{id:'phil-lsm',title:'Limit-state philosophy',level:'application',kind:'concept',q:'What broad feature distinguishes limit-state design?',choices:['It checks multiple unacceptable states using characteristic values and partial factors','It checks only one elastic stress','It assumes all loads are certain','It ignores serviceability'],answer:0,explanation:'Limit-state design separates relevant performance states and applies appropriate partial factors.',source:'Subramanian Ch.2 Design Philosophies'},
{id:'phil-compare',title:'Compare philosophies',level:'application',kind:'reasoning',q:'Why did modern design move beyond a single global factor-of-safety concept?',choices:['Loads, material resistance and different failure/service modes have different uncertainties and consequences','All uncertainties are identical','Serviceability never matters','Material strength is deterministic'],answer:0,explanation:'Modern reliability formats distinguish sources of uncertainty and different limit states.',source:'Subramanian Ch.2 Design Philosophies'},
{id:'phil-selection',title:'Design philosophy retrieval',level:'retrieval',kind:'classification',q:'Which philosophy is the principal framework used by IS 800:2007 in this textbook?',choices:['Limit States Method','Pure allowable stress only','No-factor elastic theory','Empirical sizing without checks'],answer:0,explanation:'The textbook is explicitly organized around the limit-states method and IS 800:2007.',source:'Subramanian Ch.2 Design Philosophies'}
],
'2:Limit States Method (LSM)':[
{id:'lsm-characteristic',title:'Characteristic values',level:'core',kind:'concept',q:'Why does limit-state design use characteristic values?',choices:['They provide specified representative values for actions and material properties before partial factors are applied','They are arbitrary decorative numbers','They remove statistical uncertainty entirely','They are always equal to design values'],answer:0,explanation:'Characteristic values form the defined basis from which design actions and resistances are obtained.',source:'Subramanian Ch.2 Limit States Method'},
{id:'lsm-uls',title:'Ultimate limit state',level:'core',kind:'classification',q:'Which is an ultimate limit-state concern?',choices:['Loss of strength or overall stability','Minor visual vibration only','Routine maintenance access','Surface colour'],answer:0,explanation:'Ultimate states relate to safety against collapse, instability, rupture and other severe failure modes.',source:'Subramanian Ch.2; uploaded quiz Q20'},
{id:'lsm-sls',title:'Serviceability limit state',level:'core',kind:'classification',q:'Which is primarily a serviceability limit-state concern?',choices:['Excessive deflection or vibration affecting use','Gross-section rupture','Overall overturning collapse','Brittle fracture'],answer:0,explanation:'Serviceability addresses usability, deformation, vibration, durability and similar performance criteria.',source:'Subramanian Ch.2; uploaded quiz Q21'},
{id:'lsm-partial-load',title:'Partial factors on actions',level:'application',kind:'reasoning',q:'Why are partial safety factors applied to actions in limit-state design?',choices:['To account for uncertainty and achieve target reliability for the relevant design situation','To convert force to stress units','To calculate steel density','To eliminate load combinations'],answer:0,explanation:'Action factors account for uncertainty and the probability/importance of combinations in design.',source:'Subramanian Ch.2 Limit States Method'},
{id:'lsm-partial-material',title:'Partial factors on resistance',level:'application',kind:'reasoning',q:'Why are material/resistance partial factors used separately from load factors?',choices:['Uncertainty in resistance is distinct from uncertainty in applied actions','Loads and material strengths are exactly the same quantity','They are only used for aesthetics','They make characteristic strength larger'],answer:0,explanation:'Limit-state formats treat action and resistance uncertainties separately.',source:'Subramanian Ch.2 Limit States Method'},
{id:'lsm-governing',title:'Governing limit state',level:'retrieval',kind:'reasoning',q:'If a beam is safe in strength but its deflection exceeds the permitted service limit, is the design satisfactory?',choices:['No, all relevant limit states must be satisfied','Yes, strength alone is sufficient','Yes, serviceability is optional','Only if the beam is painted'],answer:0,explanation:'A limit-state design must satisfy both applicable ultimate and serviceability requirements.',source:'Subramanian Ch.2 Limit States Method'}
],
'2:Failure Criteria for Steel':[
{id:'fc-multiaxial',title:'Why failure criteria are needed',level:'foundation',kind:'concept',q:'Why are failure criteria needed when steel is subjected to multiaxial stress?',choices:['Yielding cannot be judged from one normal-stress component alone in a general stress state','Steel carries only uniaxial stress in all structures','Shear stress never affects yielding','Principal stresses are always zero'],answer:0,explanation:'Failure/yield criteria reduce a combined stress state to a condition that can be compared with material yield behaviour.',source:'Subramanian Ch.2 Failure Criteria for Steel'},
{id:'fc-principal',title:'Principal-stress criterion',level:'core',kind:'concept',q:'A maximum-principal-stress type criterion compares which quantity with the uniaxial material limit?',choices:['The largest principal normal stress','Density','Member length','Thermal conductivity'],answer:0,explanation:'Principal-stress criteria judge failure by the extreme principal normal stress.',source:'Subramanian Ch.2 Failure Criteria for Steel'},
{id:'fc-shear',title:'Maximum-shear criterion',level:'core',kind:'concept',q:'Which named yielding idea is associated with the maximum shear stress in a multiaxial state?',choices:['Maximum-shear-stress (Tresca-type) criterion','Euler buckling criterion','Miner fatigue rule','Bredt torsion formula'],answer:0,explanation:'The chapter discusses the maximum-shear-stress approach among classical steel failure criteria.',source:'Subramanian Ch.2 Failure Criteria for Steel'},
{id:'fc-vonmises',title:'Distortion-energy criterion',level:'core',kind:'recognition',q:'The von Mises-Hencky criterion is commonly associated with:',choices:['Distortion energy/equivalent stress','Euler elastic column load','Fatigue crack counting','Fire temperature rise'],answer:0,explanation:'The textbook presents the distortion-energy criterion as the von Mises-Hencky yielding approach.',source:'Subramanian Ch.2 Failure Criteria for Steel'},
{id:'fc-hydrostatic',title:'Yielding intuition',level:'application',kind:'reasoning',q:'Why is the distortion-energy view useful for ductile steel?',choices:['It focuses on distortional/shear-related energy rather than hydrostatic stress alone','It assumes density causes yielding','It ignores shear completely','It is a deflection formula'],answer:0,explanation:'Ductile yielding is closely associated with distortional effects in the stress state.',source:'Subramanian Ch.2 Failure Criteria for Steel'},
{id:'fc-purpose',title:'Failure-criterion application',level:'retrieval',kind:'reasoning',q:'What is the practical purpose of converting a combined stress state to an equivalent yield measure?',choices:['To compare the multiaxial state with the material uniaxial yield strength','To calculate member self-weight','To select paint','To determine span directly'],answer:0,explanation:'Equivalent-stress criteria provide a consistent way to check yielding under combined stresses.',source:'Subramanian Ch.2 Failure Criteria for Steel'}
],
'2:Summary':[
{id:'sum-scope',title:'Chapter 2 scope',level:'foundation',kind:'retrieval',q:'Which set best captures the scope of Chapter 2?',choices:['Design responsibilities, structural systems, codes, design philosophies, limit states and steel failure criteria','Only welding processes','Only plate-girder design','Only torsion'],answer:0,explanation:'The chapter establishes the basis and philosophy of structural steel design before later member-design chapters.',source:'Subramanian Ch.2 Summary'},
{id:'sum-system',title:'System before member',level:'core',kind:'reasoning',q:'What key design lesson links structural systems, integrity and analysis?',choices:['Safe design requires understanding the complete load path and system behaviour, not only isolated members','Only section tables matter','Connections do not affect behaviour','Load paths are an architectural issue only'],answer:0,explanation:'Chapter 2 repeatedly emphasizes the whole structural system and its continuity.',source:'Subramanian Ch.2 Summary'},
{id:'sum-code',title:'Code role recap',level:'core',kind:'concept',q:'How should codes be used according to the chapter logic?',choices:['As minimum design frameworks combined with sound structural judgement','As substitutes for understanding behaviour','Only for drawing formatting','Only after construction is complete'],answer:0,explanation:'Codes structure the design process but competent modelling and judgement remain necessary.',source:'Subramanian Ch.2 Summary'},
{id:'sum-limitstates',title:'Limit-state recap',level:'application',kind:'classification',q:'A structure passes collapse checks but has unacceptable vibration. Which Chapter 2 principle identifies the problem?',choices:['Both ultimate and serviceability limit states must be satisfied','Ultimate strength is the only criterion','Vibration is never structural','Only fabrication controls performance'],answer:0,explanation:'Limit-state design explicitly includes serviceability as well as ultimate safety.',source:'Subramanian Ch.2 Summary'},
{id:'sum-integrity',title:'Integrity recap',level:'application',kind:'reasoning',q:'Why can adequate member strength still be insufficient for a safe structural system?',choices:['Poor integrity, stability or load-path continuity can cause system-level failure','Member strength automatically guarantees robustness','Strong members eliminate connection behaviour','System behaviour is irrelevant'],answer:0,explanation:'The chapter broadens safety from component resistance to system integrity and stability.',source:'Subramanian Ch.2 Summary'},
{id:'sum-designprocess',title:'Design-process recap',level:'retrieval',kind:'sequence',q:'Which sequence best represents the Chapter 2 design logic?',choices:['Define requirements/system → analyse actions and response → proportion/check → detail/construct','Select final section → ignore loads → build','Fabricate → choose code → invent loads','Paint → demolish → analyse'],answer:0,explanation:'The chapter establishes an iterative process from requirements and structural system through analysis, checking and construction information.',source:'Subramanian Ch.2 Summary'}
],
'2:Review Questions':[
{id:'review-responsibility',title:'Review: designer knowledge',level:'foundation',kind:'retrieval',q:'Which knowledge area is explicitly expected of the structural engineer in the uploaded Chapter 2 quiz?',choices:['Weld defects, non-destructive testing and fabrication capability','Only paint chemistry','Only architectural rendering','Only soil colour'],answer:0,explanation:'The quiz explicitly checks knowledge of weld defects, NDT, fabrication capability and structural behaviour.',source:'Uploaded textbook quiz Q13'},
{id:'review-system',title:'Review: structural system',level:'core',kind:'retrieval',q:'Which statement from the uploaded review material is correct?',choices:['Domes often require three-dimensional analysis','Cables are compression-only members','Towers must always be plane frames','Composite construction has no shear transfer'],answer:0,explanation:'The textbook quiz identifies domes as systems that often need three-dimensional analysis.',source:'Uploaded textbook quiz Q15'},
{id:'review-composite',title:'Review: composite action',level:'core',kind:'concept',q:'In the uploaded review material, steel-concrete composite construction relies on what to transfer interface forces?',choices:['Shear connectors','Paint film only','Air pressure','Column base grout only'],answer:0,explanation:'Composite beams use shear connectors so the steel beam and concrete slab can act together.',source:'Uploaded textbook quiz Q15'},
{id:'review-analysis',title:'Review: indeterminate analysis',level:'application',kind:'classification',q:'Which group contains methods listed for indeterminate structural analysis?',choices:['Moment distribution, slope-deflection and matrix methods','Density test, tensile coupon and painting','Euler only','Hydrostatic pressure only'],answer:0,explanation:'The uploaded review question lists these established indeterminate-analysis methods.',source:'Uploaded textbook quiz Q17'},
{id:'review-uls',title:'Review: ultimate state',level:'application',kind:'classification',q:'Which item belongs to ultimate-limit-state checking?',choices:['Stability against overturning','Routine visual appearance','Minor service vibration only','Paint gloss'],answer:0,explanation:'Loss of equilibrium/stability is an ultimate safety concern.',source:'Uploaded textbook quiz Q20'},
{id:'review-sls',title:'Review: serviceability state',level:'retrieval',kind:'classification',q:'Which item belongs primarily to serviceability checking?',choices:['Deflection','Brittle fracture','Gross rupture','Collapse mechanism'],answer:0,explanation:'The uploaded quiz identifies deflection as a serviceability limit-state concern.',source:'Uploaded textbook quiz Q21'}
]
});
