(() => {
  const B=window.REVISION_BANK=window.REVISION_BANK||{};
  const add=(k,a)=>B[k]=(B[k]||[]).concat(a);
  add('14:Introduction',[
    {id:'ch14-intro-req',title:'Start with requirements',level:'foundation',kind:'concept',q:'Before choosing the industrial-building framing system, which information should the designer establish?',choices:['Site, span/bays, crane and operational requirements, materials, services and project constraints','Only the paint colour','Only steel density','Only the roof slope'],answer:0,explanation:'The chapter begins with planning, loading, operational, material and project requirements before structural-system selection.',source:'Subramanian Ch.14 Introduction'},
    {id:'ch14-intro-crane',title:'Crane input',level:'core',kind:'recognition',q:'Why is crane type and capacity an early industrial-building design input?',choices:['It can influence framing, columns, runway loads and foundations','It affects only wall colour','It removes wind loading','It determines concrete grade only'],answer:0,explanation:'Crane requirements can affect the main framing and several connected structural systems.',source:'Subramanian Ch.14 Introduction'},
    {id:'ch14-intro-future',title:'Future expansion',level:'core',kind:'reasoning',q:'Why should possible future expansion be identified during planning?',choices:['It can affect layout, framing arrangement and detailing choices made now','It matters only after demolition','It has no structural consequence','It determines only floor finish'],answer:0,explanation:'The chapter treats future expansion as one of the planning inputs that can influence the selected system.',source:'Subramanian Ch.14 Introduction'},
    {id:'ch14-intro-integrated',title:'Integrated design',level:'application',kind:'reasoning',q:'Which statement best reflects the industrial-building design approach in the chapter?',choices:['Primary framing, secondary members, cladding and operational requirements must be considered together','Every component can be designed without reference to the others','Only roof trusses control the project','Service loads can be ignored'],answer:0,explanation:'The chapter presents industrial-building design as an integrated system problem.',source:'Subramanian Ch.14 Introduction'},
    {id:'ch14-intro-sequence',title:'Design sequence',level:'application',kind:'ordering',q:'Which sequence is most consistent with the chapter?',choices:['Gather requirements → select system/materials/bays → analyse and design components','Select random sections → define use → check site','Design cladding last without considering framing','Choose foundations before knowing loads'],answer:0,explanation:'Planning information comes first, followed by system selection and detailed analysis/design.',source:'Subramanian Ch.14 Introduction'},
    {id:'ch14-intro-member-types',title:'Recognise member roles',level:'retrieval',kind:'classification',q:'Which set contains structural member types commonly present in industrial buildings?',choices:['Purlins/girts, bracing, columns, beam-columns and plates','Only slabs and masonry','Only cables','Only foundations'],answer:0,explanation:'Industrial buildings combine beams/secondary members, ties/bracing, columns, beam-columns, torsion-sensitive members and plates.',source:'Subramanian Ch.14; INTRODUCTION.pdf p.61'}
  ]);
  add('14:Selection of Roofing and Wall Material',[
    {id:'ch14-roof-load',title:'Cladding affects structure',level:'foundation',kind:'concept',q:'Why can roof or wall material change secondary-member design?',choices:['Its weight, stiffness, fastening and span capability affect purlin/girt spacing and loading','It changes only appearance','It eliminates wind','It fixes column base size directly'],answer:0,explanation:'Cladding choice influences loads, fastening, spacing, insulation, durability and erection.',source:'Subramanian Ch.14 Roofing and Wall Material'},
    {id:'ch14-roof-metal',title:'Metal roof systems',level:'core',kind:'recognition',q:'Which material family is explicitly discussed for industrial roof and wall systems?',choices:['Steel or aluminium decking/sheeting','Only timber shingles','Only stone slabs','Only glass blocks'],answer:0,explanation:'The chapter discusses metal roof systems using steel or aluminium decking and sheets.',source:'Subramanian Ch.14 Roofing and Wall Material'},
    {id:'ch14-roof-insulation',title:'Insulation consequence',level:'core',kind:'reasoning',q:'Why is insulation part of roof-system selection rather than a purely architectural issue?',choices:['It affects building performance and detailing together with the cladding system','It has no interaction with roof construction','It eliminates all thermal effects','It only changes paint adhesion'],answer:0,explanation:'The chapter considers insulation and fastening as part of roof/wall system selection.',source:'Subramanian Ch.14 Roofing and Wall Material'},
    {id:'ch14-roof-frp',title:'Translucent panels',level:'retrieval',kind:'recognition',q:'What additional roof material is mentioned for admitting light?',choices:['Translucent FRP sheets','Lead blocks','Granite tiles only','Copper bars'],answer:0,explanation:'Translucent FRP sheets are noted as one of the roof-system considerations.',source:'Subramanian Ch.14 Roofing and Wall Material'},
    {id:'ch14-roof-hvac',title:'Roof equipment',level:'application',kind:'reasoning',q:'Why must roof-mounted HVAC or other equipment be identified during roof design?',choices:['It introduces additional loading and detailing requirements','It makes purlins unnecessary','It removes rainwater loads','It affects only acoustics'],answer:0,explanation:'Roof-mounted equipment is an additional design consideration because it adds load and local support requirements.',source:'Subramanian Ch.14 Roofing and Wall Material'},
    {id:'ch14-roof-historical',title:'Historical material caution',level:'retrieval',kind:'concept',q:'How should asbestos-cement roofing mentioned in the textbook be treated today?',choices:['As historical textbook content with a recognized health risk, not a current recommendation','As the preferred modern roofing system','As structurally mandatory','As identical to FRP'],answer:0,explanation:'The chapter discusses it historically and notes its health risk.',source:'Subramanian Ch.14 Roofing and Wall Material'}
  ]);
  add('14:Selection of Bay Width',[
    {id:'ch14-bay-def',title:'Define a bay',level:'foundation',kind:'definition',q:'In an industrial building, what is a bay?',choices:['The spacing between adjacent primary frames','The depth of one footing','The thickness of cladding','The crane hook height'],answer:0,explanation:'The chapter defines bay width as the distance between adjacent frames.',source:'Subramanian Ch.14 Bay Width'},
    {id:'ch14-bay-purlin',title:'Bay width and purlins',level:'core',kind:'reasoning',q:'If bay width increases, which secondary-member consequence is directly relevant?',choices:['Purlin and girt spans generally increase','Purlins become shorter automatically','Cladding dead load becomes zero','Columns disappear'],answer:0,explanation:'Bay width affects the span and economy of purlins and girts.',source:'Subramanian Ch.14 Bay Width'},
    {id:'ch14-bay-cost',title:'Economy trade-off',level:'core',kind:'reasoning',q:'Why is there no single universally optimum bay width?',choices:['Frame, secondary-member, column/foundation cost and functional requirements trade off against each other','Steel density varies by bay','Wind speed becomes zero at one spacing','All buildings have identical operations'],answer:0,explanation:'Bay selection balances functional layout and the costs/behaviour of multiple systems.',source:'Subramanian Ch.14 Bay Width'},
    {id:'ch14-bay-range',title:'Typical range',level:'retrieval',kind:'quantitative',q:'What approximate bay-width range is cited in the chapter for industrial buildings?',choices:['About 4–8 m','About 0.2–0.5 m','About 20–40 m as the normal bay','Exactly 1 m'],answer:0,explanation:'The source notes typical bay widths roughly in the 4–8 m range.',source:'Subramanian Ch.14 Bay Width'},
    {id:'ch14-bay-econ',title:'Economical range',level:'retrieval',kind:'quantitative',q:'Which approximate bay range does the chapter note as often economical?',choices:['Around 6–7.5 m','Around 0.5–1 m','Around 15–18 m in every case','Exactly 3 m'],answer:0,explanation:'The chapter notes economical choices are often around 6–7.5 m, subject to function.',source:'Subramanian Ch.14 Bay Width'},
    {id:'ch14-bay-large',title:'When larger bays make sense',level:'application',kind:'reasoning',q:'When can a bay wider than the usual economical range still be justified?',choices:['When operations require wider column spacing','Whenever purlins are weakest','Only when wind is absent','Never'],answer:0,explanation:'Functional/operational needs can justify wider bays despite structural cost trade-offs.',source:'Subramanian Ch.14 Bay Width'}
  ]);
  add('14:Structural Framing',[
    {id:'ch14-frame-braced',title:'Braced frame load path',level:'foundation',kind:'concept',q:'What primarily carries longitudinal/lateral loads in a braced industrial building?',choices:['Dedicated roof and wall bracing systems transferring actions to foundations','Only roof cladding','Only purlin self-weight','Floor finishes'],answer:0,explanation:'Braced systems use explicit bracing load paths to carry lateral actions to the foundations.',source:'Subramanian Ch.14 Structural Framing'},
    {id:'ch14-frame-unbraced',title:'Unbraced frame action',level:'core',kind:'concept',q:'What does an unbraced industrial frame rely on more heavily?',choices:['Rigid-frame action such as portal-frame behaviour','Loose pin joints everywhere','Cladding alone as the lateral system','No lateral resistance'],answer:0,explanation:'Unbraced systems rely more on moment-resisting rigid-frame action.',source:'Subramanian Ch.14 Structural Framing'},
    {id:'ch14-frame-knee',title:'Knee bracing',level:'core',kind:'reasoning',q:'What is one structural purpose of knee bracing mentioned in the chapter?',choices:['Reduce column bending by providing additional bracing action','Increase unsupported column length','Remove all axial force','Support floor finishes only'],answer:0,explanation:'Knee bracing can reduce bending demand in columns.',source:'Subramanian Ch.14 Structural Framing'},
    {id:'ch14-frame-portal',title:'Portal recognition',level:'retrieval',kind:'classification',q:'Which system is a common unbraced industrial framing form?',choices:['Rigid portal frame','Simple hanging chain only','Unconnected columns','Masonry arch only'],answer:0,explanation:'Rigid portal frames are a common unbraced framing form.',source:'Subramanian Ch.14 Structural Framing'},
    {id:'ch14-frame-trussed',title:'Trussed framing',level:'retrieval',kind:'recognition',q:'Which alternative to a solid-rafter portal is discussed for industrial roofs?',choices:['Lattice-rafter or trussed framing','Only flat plates without supports','Cable-stayed roof only','Concrete shell only'],answer:0,explanation:'The chapter discusses lattice-rafter/trussed forms among industrial framing systems.',source:'Subramanian Ch.14 Structural Framing'},
    {id:'ch14-frame-checks',title:'Framing checks',level:'application',kind:'reasoning',q:'Which set best represents checks that may govern industrial steel framing?',choices:['Strength, local/lateral buckling, fatigue where relevant, and serviceability deflection','Only colour and texture','Only steel density','Only thermal conductivity'],answer:0,explanation:'The source emphasizes strength, stability and serviceability, with fatigue relevant in some industrial situations.',source:'Subramanian Ch.14 Structural Framing'}
  ]);
  add('14:Purlins, Girts, and Eave Strut',[
    {id:'ch14-purlin-role',title:'Purlin role',level:'foundation',kind:'classification',q:'What do purlins primarily support?',choices:['Roof cladding','Foundations','Floor slabs','Crane hooks'],answer:0,explanation:'Purlins support roof cladding and transfer roof loads to primary framing.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'},
    {id:'ch14-girt-role',title:'Girt role',level:'foundation',kind:'classification',q:'What do girts primarily support?',choices:['Wall cladding','Roof ridge only','Foundation soil','Crane rails only'],answer:0,explanation:'Girts carry wall cladding loads to the primary frames.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'},
    {id:'ch14-girt-biaxial',title:'Girt biaxial bending',level:'core',kind:'reasoning',q:'Why may a wall girt bend about two axes?',choices:['Wall gravity and wind actions can act in different directions relative to the section','Girts carry no transverse load','Only axial load is possible','Their centroid moves during fabrication'],answer:0,explanation:'Wind on wall cladding and gravity effects can produce biaxial bending in girts.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'},
    {id:'ch14-eave-location',title:'Eave strut location',level:'core',kind:'recognition',q:'Where is an eave strut located?',choices:['At the roof-wall junction','At footing level only','At the crane hook','At mid-depth of slab'],answer:0,explanation:'The eave strut occurs at the roof-wall junction.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'},
    {id:'ch14-sagrods',title:'Sag rods and bridging',level:'application',kind:'concept',q:'Why are sag rods or bridging used with some purlin systems?',choices:['To provide intermediate restraint/support to slender secondary members','To replace all primary frames','To increase cladding weight','To eliminate roof slope'],answer:0,explanation:'The chapter discusses sag rods/bridging as part of secondary-member restraint and behaviour.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'},
    {id:'ch14-purlin-checks',title:'Secondary member checks',level:'retrieval',kind:'classification',q:'Which two broad checks are explicitly important for purlins and girts?',choices:['Strength and deflection','Density and colour','Only corrosion potential','Only weld size'],answer:0,explanation:'The chapter notes both strength and serviceability deflection must be checked.',source:'Subramanian Ch.14 Purlins, Girts and Eave Strut'}
  ]);
  add('14:Plane Trusses',[
    {id:'ch14-truss-ideal',title:'Ideal truss load application',level:'foundation',kind:'concept',q:'Under the ideal plane-truss model, where should external loads be applied?',choices:['At joints/panel points','At random points between joints','Only at midspan of every member','Only at supports'],answer:0,explanation:'Joint loading is part of the ideal truss assumption that leads to predominantly axial member forces.',source:'Subramanian Ch.14 Plane Trusses'},
    {id:'ch14-truss-axis',title:'Centroidal axes',level:'core',kind:'concept',q:'What geometric assumption supports axial-force-only idealization in a plane truss?',choices:['Member centroidal axes meet at the joints','Members are curved','Every joint is rigidly offset','Loads act through flange tips'],answer:0,explanation:'Concurrent centroidal axes at joints reduce unintended eccentricity and bending in the ideal model.',source:'Subramanian Ch.14 Plane Trusses'},
    {id:'ch14-truss-purlin',title:'Real truss bending',level:'core',kind:'reasoning',q:'What can introduce bending into a roof-truss chord that is idealized as axial?',choices:['Purlin loads applied between panel points','Loads applied exactly at joints only','Perfectly concentric joints','Zero roof load'],answer:0,explanation:'The chapter warns that purlin loads between panel points can introduce chord bending.',source:'Subramanian Ch.14 Plane Trusses'},
    {id:'ch14-truss-compression',title:'Compression member issue',level:'application',kind:'reasoning',q:'What additional failure mode must be checked for a compression member in a roof truss?',choices:['Buckling','Net-section tension rupture only','Hydrostatic uplift only','Concrete punching'],answer:0,explanation:'Compression truss members require buckling checks in addition to force determination.',source:'Subramanian Ch.14 Plane Trusses'},
    {id:'ch14-truss-joints',title:'Joint design',level:'application',kind:'concept',q:'Why does analysing truss member axial forces not complete the truss design?',choices:['Connections/joints must also transfer those forces safely','Axial force automatically designs every bolt and weld','Joints carry no force','Truss analysis replaces detailing'],answer:0,explanation:'The chapter includes welded/bolted truss joint design as a separate necessary step.',source:'Subramanian Ch.14 Plane Trusses'},
    {id:'ch14-truss-computer',title:'Analysis method',level:'retrieval',kind:'recognition',q:'What analysis approach does the chapter note is commonly used for larger or more complex trusses?',choices:['Computer structural analysis','No analysis','Only graphical sketching','Only physical model testing'],answer:0,explanation:'Computer analysis is commonly used for larger or more complex trusses.',source:'Subramanian Ch.14 Plane Trusses'}
  ]);
  add('14:Floor Plates',[
    {id:'ch14-floor-use',title:'Industrial floor plates',level:'foundation',kind:'recognition',q:'Where are steel floor plates commonly used in the chapter context?',choices:['Platforms and access areas around industrial equipment','Deep foundations only','Roof drainage pipes only','Crane ropes'],answer:0,explanation:'The chapter discusses steel floor plates for industrial platforms around equipment.',source:'Subramanian Ch.14 Floor Plates'},
    {id:'ch14-floor-pattern',title:'Raised pattern',level:'core',kind:'reasoning',q:'Why may a chequered or raised-pattern plate be preferred for an industrial platform?',choices:['To improve footing/grip','To reduce steel density to zero','To eliminate bending','To make the plate transparent'],answer:0,explanation:'Raised patterns can improve footing on industrial platforms.',source:'Subramanian Ch.14 Floor Plates'},
    {id:'ch14-floor-fixing',title:'Plate attachment',level:'core',kind:'recognition',q:'How may floor plates be attached to supporting steelwork according to the chapter?',choices:['By welding or bolting','Only by adhesive tape','Only by gravity with no restraint','Only by prestressing'],answer:0,explanation:'The chapter notes floor plates may be welded or bolted to supporting beams.',source:'Subramanian Ch.14 Floor Plates'},
    {id:'ch14-floor-twoway',title:'Two-way behaviour',level:'application',kind:'concept',q:'When can a floor plate be treated as a two-way plate?',choices:['When supported on all four sides','When supported at one point only','When it is a cable','Only when vertical'],answer:0,explanation:'Four-side support permits two-way plate action using plate coefficients.',source:'Subramanian Ch.14 Floor Plates'},
    {id:'ch14-floor-defl',title:'Deflection check',level:'application',kind:'reasoning',q:'Why is deflection checked even if a floor plate has adequate bending strength?',choices:['Serviceability can govern usability and feel of the platform','Strength always guarantees zero deflection','Deflection affects only colour','Deflection is impossible in plates'],answer:0,explanation:'The chapter explicitly treats allowable deflection as a design consideration.',source:'Subramanian Ch.14 Floor Plates'},
    {id:'ch14-floor-coeff',title:'Plate coefficients',level:'retrieval',kind:'recognition',q:'What method is mentioned for evaluating bending and deflection of a four-side-supported floor plate?',choices:['Plate bending and deflection coefficients','Euler column formula only','Bolt slip equation only','Hydrostatic pressure table only'],answer:0,explanation:'The source uses plate coefficients for two-way supported plate behaviour.',source:'Subramanian Ch.14 Floor Plates'}
  ]);
  add('14:End Bearings',[
    {id:'ch14-bearing-role',title:'End bearing role',level:'foundation',kind:'concept',q:'What must a roof-truss end bearing transfer?',choices:['The truss support reaction into the supporting column, masonry or concrete','Only paint load','Only temperature without vertical load','No force at all'],answer:0,explanation:'End bearings transfer truss reactions into the supporting system.',source:'Subramanian Ch.14 End Bearings'},
    {id:'ch14-bearing-slide',title:'Sliding support',level:'core',kind:'reasoning',q:'What problem is reduced by allowing one truss end to move longitudinally?',choices:['Thermal restraint forces from expansion/contraction','Gravity reaction','Steel self-weight','Wind pressure on cladding'],answer:0,explanation:'A sliding detail accommodates thermal movement rather than restraining it.',source:'Subramanian Ch.14 End Bearings'},
    {id:'ch14-bearing-slot',title:'Slotted holes',level:'core',kind:'recognition',q:'What detailing feature can permit longitudinal movement at a truss support?',choices:['Slotted holes in support angles','Fully welded rigid restraint at both ends','Solid grout key only','Increasing plate density'],answer:0,explanation:'The chapter mentions slotted holes as a way to accommodate truss movement.',source:'Subramanian Ch.14 End Bearings'},
    {id:'ch14-bearing-plate',title:'Bearing plate',level:'application',kind:'concept',q:'Why is a bearing plate used when a truss bears on masonry or concrete?',choices:['To spread the concentrated support reaction over a larger area','To increase truss temperature','To remove uplift','To replace the truss joint'],answer:0,explanation:'Bearing plates distribute concentrated reactions into the support material.',source:'Subramanian Ch.14 End Bearings'},
    {id:'ch14-bearing-anchor',title:'Anchor bolts',level:'application',kind:'reasoning',q:'What action may require anchor bolts at a roof-truss support?',choices:['Uplift','Only downward dead load','Paint shrinkage','Floor vibration only'],answer:0,explanation:'The chapter notes anchor bolts are needed to resist uplift at the support.',source:'Subramanian Ch.14 End Bearings'},
    {id:'ch14-bearing-bothhinged',title:'Two hinged ends',level:'retrieval',kind:'reasoning',q:'If both roof-truss ends are hinged, what must the designer consider?',choices:['How horizontal actions are shared by the supporting columns','That horizontal actions vanish','That columns carry no force','That uplift is impossible'],answer:0,explanation:'The chapter notes horizontal actions must be shared by the supports when both ends are hinged.',source:'Subramanian Ch.14 End Bearings'}
  ]);
  add('14:Design of Slabs on Grade',[
    {id:'ch14-sog-layers',title:'Slab-on-grade build-up',level:'foundation',kind:'ordering',q:'Which sequence represents the typical industrial slab-on-grade build-up described?',choices:['Prepared subgrade → granular sub-base → optional vapour-barrier/sand layer → concrete slab','Concrete slab → roof cladding → purlin → footing','Steel plate → crane rail → soil only','Wall girt → vapour barrier → roof sheet'],answer:0,explanation:'The chapter describes a prepared subgrade, granular sub-base, optional vapour-control layer and the concrete slab.',source:'Subramanian Ch.14 Slabs on Grade'},
    {id:'ch14-sog-subgrade',title:'Subgrade importance',level:'core',kind:'reasoning',q:'Why is proper subgrade preparation critical for an industrial slab?',choices:['The slab performance depends on uniform, reliable support from the ground system','Subgrade carries no load','It affects only wall cladding','It eliminates joints'],answer:0,explanation:'The chapter emphasizes subgrade preparation as critical to slab performance.',source:'Subramanian Ch.14 Slabs on Grade'},
    {id:'ch14-sog-subbase',title:'Sub-base function',level:'core',kind:'classification',q:'Which is a function of the granular sub-base?',choices:['Bridge local weak spots, spread concentrated loads and help drainage','Act as roof bracing','Carry crane hook load directly to roof','Replace concrete reinforcement in all cases'],answer:0,explanation:'The source identifies load distribution, bridging weak areas and drainage as sub-base functions.',source:'Subramanian Ch.14 Slabs on Grade'},
    {id:'ch14-sog-vapour',title:'Vapour barrier caution',level:'application',kind:'reasoning',q:'Why does the chapter caution that a vapour barrier is not a neutral addition?',choices:['It can influence curing and curling behaviour of the slab','It makes concrete weightless','It removes shrinkage entirely','It acts as steel reinforcement'],answer:0,explanation:'The chapter notes vapour barriers can affect curing and curling.',source:'Subramanian Ch.14 Slabs on Grade'},
    {id:'ch14-sog-joints',title:'Joints matter',level:'application',kind:'concept',q:'Why are joints included in the slab-on-grade system description?',choices:['They are part of controlling and accommodating slab behaviour and construction','They carry roof truss reactions','They eliminate subgrade preparation','They are only decorative'],answer:0,explanation:'The source includes joints as part of the slab system along with reinforcement and finishes.',source:'Subramanian Ch.14 Slabs on Grade'},
    {id:'ch14-sog-ref',title:'Further guidance',level:'retrieval',kind:'recognition',q:'Which reference does the chapter point to for more detailed industrial slab-on-grade guidance?',choices:['ACI 302','ISO 834','IS 875 Part 3 only','AISC fatigue appendix only'],answer:0,explanation:'The textbook points to ACI 302 for more detailed treatment.',source:'Subramanian Ch.14 Slabs on Grade'}
  ]);
  add('14:Examples',[
    {id:'ch14-ex-purpose',title:'Worked-example scope',level:'foundation',kind:'concept',q:'Why are the Chapter 14 examples more than isolated member calculations?',choices:['They combine loads, analysis, member selection, stability, connections and serviceability','They only calculate steel density','They exclude wind','They avoid system interaction'],answer:0,explanation:'The worked examples integrate several parts of an industrial building design.',source:'Subramanian Ch.14 Examples'},
    {id:'ch14-ex1-span',title:'Example 14.1 span',level:'retrieval',kind:'quantitative',q:'What span is used for the industrial building in Example 14.1?',choices:['20 m','2 m','50 m','100 m'],answer:0,explanation:'Example 14.1 is described as a 20 m span industrial building.',source:'Subramanian Ch.14 Example 14.1'},
    {id:'ch14-ex1-place',title:'Example location',level:'retrieval',kind:'recognition',q:'Which location is used in Example 14.1?',choices:['Guwahati','Mumbai only','London','Tokyo'],answer:0,explanation:'The worked example is for an industrial building at Guwahati.',source:'Subramanian Ch.14 Example 14.1'},
    {id:'ch14-ex1-components',title:'Example components',level:'core',kind:'recognition',q:'Which component set is explicitly included in Example 14.1?',choices:['Roof truss, rafter bracing, purlins, tie runners, side runners and eave girder','Only one isolated bolt','Only slab reinforcement','Only a column base'],answer:0,explanation:'The example designs the truss and several associated secondary/bracing components.',source:'Subramanian Ch.14 Example 14.1'},
    {id:'ch14-ex1-loads',title:'Example loading',level:'application',kind:'classification',q:'Which load families are explicitly combined in Example 14.1?',choices:['Dead, imposed and wind loads','Only dead load','Only earthquake load','Only temperature'],answer:0,explanation:'The example includes dead, imposed and wind loading.',source:'Subramanian Ch.14 Example 14.1'},
    {id:'ch14-ex2',title:'Example 14.2',level:'retrieval',kind:'recognition',q:'What structural element is designed in Example 14.2?',choices:['A Vierendeel girder','A suspension cable','A concrete dome','A timber arch'],answer:0,explanation:'Example 14.2 designs a Vierendeel girder in the same industrial-building context.',source:'Subramanian Ch.14 Example 14.2'}
  ]);
  add('14:Summary',[
    {id:'ch14-sum-steel',title:'Why steel',level:'foundation',kind:'concept',q:'Which advantages make steel attractive for industrial buildings according to the summary?',choices:['Prefabrication, erection speed and adaptability','Zero corrosion and zero fire risk','No need for bracing','Infinite stiffness'],answer:0,explanation:'The summary highlights prefabrication, speed and adaptability as practical advantages.',source:'Subramanian Ch.14 Summary'},
    {id:'ch14-sum-interdep',title:'Interdependent choices',level:'core',kind:'reasoning',q:'Which design decisions does the summary treat as interdependent?',choices:['Cladding, bay width, framing, bracing, secondary members and roof systems','Only paint and signage','Only foundation colour','Only crane operator preference'],answer:0,explanation:'The summary stresses the interaction among major planning and structural choices.',source:'Subramanian Ch.14 Summary'},
    {id:'ch14-sum-vent',title:'Industrial-specific issue',level:'core',kind:'recognition',q:'Which building-performance issue is highlighted alongside structural framing?',choices:['Ventilation and drainage','Only acoustic music level','Only furniture layout','Only elevator speed'],answer:0,explanation:'Ventilation and drainage are among the industrial-building-specific considerations in the summary.',source:'Subramanian Ch.14 Summary'},
    {id:'ch14-sum-durability',title:'Durability and fire',level:'application',kind:'reasoning',q:'Why do corrosion and fire considerations appear in an industrial-building summary?',choices:['They influence durability, protection and life-cycle performance of steelwork','They are unrelated to steel structures','They affect only concrete','They matter only after demolition'],answer:0,explanation:'The chapter treats fire and corrosion as relevant practical considerations for industrial steel buildings.',source:'Subramanian Ch.14 Summary'},
    {id:'ch14-sum-prefab',title:'Prefabricated trusses',level:'retrieval',kind:'recognition',q:'Which component is specifically associated with prefabrication in the summary?',choices:['Roof trusses','Soil strata','Rainfall intensity','Concrete admixtures'],answer:0,explanation:'The summary notes the use of prefabricated roof trusses.',source:'Subramanian Ch.14 Summary'},
    {id:'ch14-sum-coldformed',title:'Cold-formed secondary members',level:'retrieval',kind:'recognition',q:'Which member category is noted as suitable for cold-formed construction?',choices:['Secondary members such as purlins/girts','Mass concrete foundations','Masonry infill only','Crane ropes'],answer:0,explanation:'Cold-formed secondary members are highlighted in the summary.',source:'Subramanian Ch.14 Summary'}
  ]);
  add('14:Review Questions',[
    {id:'ch14-review-roof',title:'Review roof systems',level:'foundation',kind:'retrieval',q:'Which topic belongs in a Chapter 14 conceptual review?',choices:['Roof types and roof materials','Only concrete chemistry','Only soil consolidation','Only cable dynamics'],answer:0,explanation:'The review questions span roof systems, framing, bracing, secondary members, trusses and floors.',source:'Subramanian Ch.14 Review Questions'},
    {id:'ch14-review-bay',title:'Review bay width',level:'core',kind:'retrieval',q:'A proper Chapter 14 review should be able to explain what about bay width?',choices:['How functional and structural/economic factors influence its selection','Only its colour','Why it is always fixed at one value','Why it has no effect on purlins'],answer:0,explanation:'Bay-width selection is one of the conceptual themes in the review section.',source:'Subramanian Ch.14 Review Questions'},
    {id:'ch14-review-bracing',title:'Review bracing',level:'core',kind:'retrieval',q:'Which question best tests understanding of bracing systems?',choices:['How lateral loads are transferred through roof/wall bracing to foundations','What is the density of paint','How to eliminate all lateral loads','Why bracing is purely decorative'],answer:0,explanation:'The chapter review expects understanding of braced-frame load paths.',source:'Subramanian Ch.14 Review Questions'},
    {id:'ch14-review-truss',title:'Review truss assumptions',level:'application',kind:'reasoning',q:'Which plane-truss assumption should a learner be able to state from the chapter review?',choices:['Loads applied at joints with members carrying mainly axial force','All loads act at member midpoints','All joints are fixed-end beams','Members carry pure torsion'],answer:0,explanation:'Ideal truss assumptions are among the chapter concepts to be retrieved.',source:'Subramanian Ch.14 Review Questions'},
    {id:'ch14-review-girt',title:'Review secondary members',level:'application',kind:'classification',q:'Which distinction should a learner retrieve about purlins and girts?',choices:['Purlins support roof cladding; girts support wall cladding','Both are foundations','Both are crane ropes','Both are only tension ties'],answer:0,explanation:'The functional distinction between secondary members is a core review item.',source:'Subramanian Ch.14 Review Questions'},
    {id:'ch14-review-goal',title:'Concept before calculations',level:'retrieval',kind:'reasoning',q:'What is the purpose of the review questions before full design exercises?',choices:['Confirm that the learner can explain system choices and assumptions conceptually','Replace all calculations forever','Provide only final numerical answers','Test unrelated material'],answer:0,explanation:'The review section tests conceptual understanding before integrated design tasks.',source:'Subramanian Ch.14 Review Questions'}
  ]);
  add('14:Exercises',[
    {id:'ch14-exer-integrated',title:'Exercise character',level:'foundation',kind:'concept',q:'What makes the Chapter 14 exercises integrated design problems?',choices:['They combine geometry, loads, analysis and member selection','They ask only vocabulary','They exclude structural analysis','They use only density conversions'],answer:0,explanation:'The exercises require a complete sequence from building data and loading to analysis and design.',source:'Subramanian Ch.14 Exercises'},
    {id:'ch14-exer-geometry',title:'Use given geometry',level:'core',kind:'reasoning',q:'Why are span, bay spacing and roof geometry supplied in industrial-building exercises?',choices:['They define load paths, member spans and analysis geometry','They are decorative details only','They remove the need for analysis','They determine steel chemistry'],answer:0,explanation:'Geometry is necessary to establish loads and structural response.',source:'Subramanian Ch.14 Exercises'},
    {id:'ch14-exer-location',title:'Location matters',level:'core',kind:'reasoning',q:'Why can the stated building location matter in a design exercise?',choices:['Environmental loading such as wind depends on location','Steel modulus changes arbitrarily by city','Bay width becomes fixed by latitude','Connections are unnecessary in some cities'],answer:0,explanation:'Location can affect environmental design actions used in the exercise.',source:'Subramanian Ch.14 Exercises'},
    {id:'ch14-exer-crane',title:'Operating requirements',level:'application',kind:'reasoning',q:'Why may crane or other operating requirements be included in an industrial-building exercise?',choices:['They can change applied actions and member/system demands','They affect only architectural signage','They always reduce loads','They eliminate serviceability checks'],answer:0,explanation:'Operating equipment is part of the structural loading context.',source:'Subramanian Ch.14 Exercises'},
    {id:'ch14-exer-sequence',title:'Exercise workflow',level:'application',kind:'ordering',q:'Which workflow best matches a full Chapter 14 exercise?',choices:['Establish loads → analyse framing → select/check members and associated details','Pick a section → ignore loads → stop','Calculate paint area only','Check deflection before defining geometry'],answer:0,explanation:'The exercises combine loading, analysis and member design in sequence.',source:'Subramanian Ch.14 Exercises'},
    {id:'ch14-exer-notisolated',title:'System thinking',level:'retrieval',kind:'reasoning',q:'What skill do the exercises test beyond formula substitution?',choices:['Coordinating several structural components and design decisions as one building system','Memorising one steel density value','Drawing only architectural elevations','Avoiding load combinations'],answer:0,explanation:'The exercise set is intended as integrated industrial-building design practice.',source:'Subramanian Ch.14 Exercises'}
  ]);
})();
