Object.assign(window.REVISION_BANK,{
'13:General Behaviour of Beam-columns':[
{id:'beamcolumn-combined',title:'Combined axial force and bending',level:'foundation',kind:'concept',q:'A beam-column is a member that carries:',choices:['Significant axial force together with bending moment','Only pure shear','Only torsion','Only temperature load'],answer:0,explanation:'Beam-columns require interaction checks because axial compression or tension acts together with flexure.',source:'Subramanian Ch.13 tracked-topic bridge'},
{id:'beamcolumn-amplification',title:'Axial load amplifies bending',level:'core',kind:'reasoning',q:'Why can compressive axial force increase the bending response of a beam-column?',choices:['The axial force acting through lateral deflection creates additional second-order moment','Compression always increases EI','Axial force removes curvature','Bending moment becomes independent of deformation'],answer:0,explanation:'The P-δ/P-Δ mechanism creates additional moment as the member or frame deflects.',math:'M_{2}\\sim P\\Delta',source:'Subramanian Ch.13 tracked-topic bridge'}
],
'13:Second-order Moments in Beam-columns':[
{id:'moment-magnification',title:'Moment magnification concept',level:'foundation',kind:'concept',q:'A moment-magnification approach is intended to account approximately for:',choices:['Second-order effects caused by axial load acting on deflection','Only bolt slip','Only residual stress','Only dead-load calculation'],answer:0,explanation:'First-order moments can be amplified to approximate geometric second-order effects when permitted by the design method.',source:'Subramanian Ch.13 tracked-topic bridge'},
{id:'pdelta-zero',title:'When P-Δ vanishes',level:'core',kind:'reasoning',q:'If a compressive axial force P acts through a frame story with zero lateral sway Δ, the global P-Δ moment contribution is:',choices:['Zero','P/Δ','Infinite','Always equal to the first-order moment'],answer:0,explanation:'The geometric moment contribution PΔ vanishes when the lateral displacement is zero.',math:'M_{P\\Delta}=P\\Delta',source:'Subramanian Ch.13 tracked-topic bridge'}
],
'13:Beam-column under Biaxial Loading':[
{id:'biaxial-bending',title:'Biaxial beam-column action',level:'foundation',kind:'classification',q:'Biaxial beam-column loading involves axial force plus bending about:',choices:['Both principal cross-section axes','No axis','Only the member longitudinal axis as torsion','Only one axis by definition'],answer:0,explanation:'A biaxially bent beam-column develops moment components about both cross-section axes in addition to axial force.',source:'Subramanian Ch.13 tracked-topic bridge'},
{id:'biaxial-interaction',title:'Why use an interaction equation?',level:'core',kind:'reasoning',q:'Why are interaction equations used for biaxially loaded beam-columns?',choices:['The utilisation from axial force and bending about both axes must be assessed together','Each action has no influence on the others','Only section area matters','They replace equilibrium analysis'],answer:0,explanation:'Combined actions consume the same member resistance and cannot generally be checked independently without interaction.',source:'Subramanian Ch.13 tracked-topic bridge'}
],
'14:Structural Framing':[
{id:'industrial-loadpath',title:'Industrial-building load path',level:'foundation',kind:'concept',q:'In a typical steel industrial building, roof loads commonly pass through which sequence?',choices:['Roof sheeting → purlins → rafters/trusses → columns → foundations','Columns → purlins → roof sheeting → air','Foundations → cladding only','Bolts → paint → soil'],answer:0,explanation:'Secondary roof members collect sheeting loads and transfer them to primary frames, which deliver reactions to the foundations.',source:'Subramanian Ch.14 tracked-topic bridge'},
{id:'bracing-purpose',title:'Purpose of bracing',level:'core',kind:'concept',q:'What is a primary structural role of bracing in an industrial steel building?',choices:['Provide lateral stability and transfer horizontal actions','Increase concrete cube strength','Eliminate all axial force','Replace purlins under gravity load'],answer:0,explanation:'Bracing systems stabilise the structure and provide load paths for wind, crane and other lateral actions.',source:'Subramanian Ch.14 tracked-topic bridge'}
],
'14:Purlins, Girts, and Eave Strut':[
{id:'purlin-role',title:'Purlin role',level:'foundation',kind:'classification',q:'What does a roof purlin primarily support?',choices:['Roof sheeting between main frames or trusses','Column bases','Foundation soil','Only crane rails'],answer:0,explanation:'Purlins are secondary roof members spanning between primary structural frames.',source:'Subramanian Ch.14 tracked-topic bridge'},
{id:'girt-role',title:'Girt role',level:'foundation',kind:'classification',q:'What is the analogous secondary member that supports wall cladding called?',choices:['Girt','Tie plate only','Base plate','Bearing stiffener'],answer:0,explanation:'Girts span between columns or wall framing to support wall sheeting and transfer wind loads.',source:'Subramanian Ch.14 tracked-topic bridge'}
],
'16:Calculation of Temperature Rise in Steel Members':[
{id:'steel-heating',title:'Why steel heats rapidly in fire',level:'foundation',kind:'concept',q:'Why can an unprotected steel section heat rapidly during fire exposure?',choices:['Steel has high thermal conductivity and relatively low section thermal mass for exposed slender members','Steel is non-conductive','Steel generates no heat transfer','Young’s modulus increases with temperature'],answer:0,explanation:'Heat is transferred efficiently through steel, and exposed surface area relative to mass strongly influences temperature rise.',source:'Subramanian Ch.16 tracked-topic bridge'},
{id:'section-factor',title:'Section factor trend',level:'core',kind:'reasoning',q:'For otherwise similar fire exposure, a steel member with a larger exposed perimeter-to-steel-volume ratio generally heats:',choices:['Faster','Slower','At exactly the same rate regardless of geometry','Only after yielding'],answer:0,explanation:'A larger section factor provides more exposed surface per unit thermal mass, increasing the heating rate.',source:'Subramanian Ch.16 tracked-topic bridge'}
],
'16:Mechanical Properties of Steel at Elevated Temperatures':[
{id:'hot-steel-strength',title:'Strength at elevated temperature',level:'foundation',kind:'concept',q:'As structural steel temperature becomes very high in fire, its yield strength generally:',choices:['Reduces','Increases without limit','Remains exactly unchanged','Becomes unrelated to temperature'],answer:0,explanation:'Elevated temperature degrades steel strength, requiring temperature-dependent reduction factors in fire design.',source:'Subramanian Ch.16 tracked-topic bridge'},
{id:'hot-steel-stiffness',title:'Stiffness at elevated temperature',level:'core',kind:'concept',q:'What generally happens to Young’s modulus of structural steel as temperature rises substantially?',choices:['It decreases','It doubles at every temperature step','It remains constant to melting','It becomes negative'],answer:0,explanation:'Steel stiffness degrades with temperature, increasing deformation and reducing stability resistance.',source:'Subramanian Ch.16 tracked-topic bridge'}
],
'17:Fatigue Loading':[
{id:'fatigue-cycles',title:'Fatigue loading concept',level:'foundation',kind:'concept',q:'Fatigue damage is primarily associated with:',choices:['Repeated or fluctuating stress cycles','One perfectly constant zero-stress state','Only short-term elastic deflection','Only corrosion colour'],answer:0,explanation:'Repeated stress fluctuations can initiate and propagate cracks even when peak stress is below static strength.',source:'Subramanian Ch.17 tracked-topic bridge'},
{id:'stress-range',title:'Stress range',level:'core',kind:'formula',q:'If a stress cycle varies from σ_min to σ_max, the stress range is:',choices:['Δσ=σ_max−σ_min','Δσ=σ_max+σ_min','Δσ=σ_max/σ_min always','Δσ=0'],answer:0,explanation:'Fatigue classifications are commonly expressed in terms of stress range rather than only maximum stress.',math:'\\Delta\\sigma=\\sigma_{max}-\\sigma_{min}',source:'Subramanian Ch.17 tracked-topic bridge'}
],
'17:Fatigue Assessment for Variable Stress Ranges':[
{id:'miner-rule',title:'Cumulative fatigue damage idea',level:'core',kind:'formula',q:'Which expression represents the Palmgren–Miner linear cumulative damage concept?',choices:['Σ(n_i/N_i) ≤ 1','Σ(n_i N_i)=0','N_i/n_i=0 for every range','Δσ_i=0 always'],answer:0,explanation:'Each stress-range block contributes a fraction of its constant-amplitude fatigue life; the fractions are summed.',math:'D=\\sum_i\\frac{n_i}{N_i}',source:'Subramanian Ch.17 tracked-topic bridge'},
{id:'variable-range',title:'Why classify stress ranges',level:'foundation',kind:'reasoning',q:'Why is a variable-amplitude stress history divided into stress-range blocks for fatigue assessment?',choices:['Different stress ranges consume fatigue life at different rates','Every stress cycle causes identical damage','Only the mean stress matters','It eliminates the need for cycle counting'],answer:0,explanation:'Fatigue life is strongly dependent on stress range, so the history is grouped or counted by range before cumulative damage is evaluated.',source:'Subramanian Ch.17 tracked-topic bridge'}
],
'18:Shear Centre':[
{id:'shear-centre-load',title:'Load through shear centre',level:'foundation',kind:'concept',q:'What happens ideally when a transverse load passes through the shear centre of an open thin-walled section?',choices:['The section bends without inducing Saint-Venant twisting from load eccentricity','The section must twist maximally','All shear stress vanishes','The member carries only axial load'],answer:0,explanation:'The shear centre is the point through which transverse loading produces bending without a net twisting moment.',source:'Subramanian Ch.18 tracked-topic bridge'},
{id:'shear-centre-symmetry',title:'Shear centre and symmetry',level:'core',kind:'reasoning',q:'For a doubly symmetric I-section, where does the shear centre lie?',choices:['At the centroid, at the intersection of the symmetry axes','At one flange tip','Outside the section in every case','At an arbitrary bolt hole'],answer:0,explanation:'For sections with two axes of symmetry, the shear centre coincides with the centroid.',source:'Subramanian Ch.18 tracked-topic bridge'}
]
});