Object.assign(window.REVISION_BANK,{
'4:Introduction':[
{id:'ch4-intro-system',title:'System-level behaviour',level:'foundation',kind:'concept',q:'Why can steel-frame design require more than separate isolated member checks?',choices:['Member strength, system stability and connection behaviour can interact','Every steel frame is statically determinate','Connections never influence global response','Elastic analysis always predicts collapse exactly'],answer:0,explanation:'Chapter 4 motivates system-aware analysis because frame stability, member behaviour and connection response may interact.',source:'Subramanian Ch.4; Chapter 4 PPT'},
{id:'ch4-intro-two-stage',title:'Traditional two-stage design',level:'core',kind:'recognition',q:'What is the traditional two-stage steel-design approach contrasted with advanced analysis?',choices:['Analyse the frame, then perform separate member strength/stability checks','Design every connection before analysing the frame','Ignore global analysis and size members by weight','Assume collapse load equals dead load'],answer:0,explanation:'The chapter contrasts conventional analysis followed by separate member checks with advanced methods that integrate system strength and stability.',source:'Subramanian Ch.4'},
{id:'ch4-intro-stability',title:'Why stability matters',level:'core',kind:'reasoning',q:'A frame can satisfy elastic stress checks yet still require a stability assessment because:',choices:['Instability can develop through geometric effects before a simple stress limit is decisive','Yield stress automatically prevents buckling','Buckling occurs only after fracture','Stability is unrelated to axial force'],answer:0,explanation:'The chapter treats stability as a system/member phenomenon that is not captured by a simple stress-only check.',source:'Subramanian Ch.4'},
{id:'ch4-intro-methods',title:'Analysis family recognition',level:'core',kind:'classification',q:'Which set belongs to the analysis families introduced in Chapter 4?',choices:['Elastic, buckling, plastic and second-order inelastic analyses','Only hydrostatic and thermal analyses','Only graphical statics','Only fatigue counting methods'],answer:0,explanation:'Chapter 4 organizes methods around elastic, critical-load, plastic and advanced inelastic analysis.',source:'Subramanian Ch.4; Chapter 4 PPT Fig. 4.1'},
{id:'ch4-intro-model',title:'Choose the model deliberately',level:'application',kind:'reasoning',q:'What should guide the choice of structural analysis model?',choices:['Whether the relevant real behaviour includes geometric, material or connection nonlinearity','The colour of the steel section','The drawing scale alone','The member mass alone'],answer:0,explanation:'The chapter emphasizes selecting a model that represents the important behaviour and failure mechanisms.',source:'Subramanian Ch.4'},
{id:'ch4-intro-advanced',title:'Purpose of advanced analysis',level:'retrieval',kind:'concept',q:'What is the main attraction of advanced analysis in steel design?',choices:['It can assess system strength and stability more directly in one analysis','It removes the need for equilibrium','It assumes infinite ductility in every member','It ignores frame imperfections'],answer:0,explanation:'Advanced analysis aims to represent both yielding and instability at system level rather than relying entirely on separate member checks.',source:'Subramanian Ch.4'}
],
'4:Methods of Analysis':[
{id:'ch4-method-graph',title:'Read the load-displacement map',level:'foundation',kind:'concept',q:'In the Chapter 4 load-displacement diagram, what is plotted on the horizontal axis?',choices:['Lateral deflection Δ','Yield stress fy','Steel density','Bolt diameter'],answer:0,explanation:'Figure 4.1 uses lateral deflection on the horizontal axis and load index on the vertical axis to compare analysis methods.',source:'Chapter 4 PPT Fig. 4.1'},
{id:'ch4-method-first',title:'First-order family',level:'core',kind:'classification',q:'Which method ignores equilibrium changes caused by the deformed geometry?',choices:['First-order elastic analysis','Second-order elastic analysis','Second-order plastic-zone analysis','Advanced inelastic analysis'],answer:0,explanation:'First-order analysis writes equilibrium on the undeformed configuration.',source:'Subramanian Ch.4'},
{id:'ch4-method-critical',title:'Critical-load analysis',level:'core',kind:'recognition',q:'Which analysis method is primarily intended to identify a critical load and buckling mode?',choices:['Buckling analysis','Dead-load take-off','Weld sizing only','Serviceability deflection check only'],answer:0,explanation:'Critical-load or buckling analysis searches for loss of stability and associated modes.',source:'Subramanian Ch.4'},
{id:'ch4-method-plastic',title:'Plastic limit load',level:'core',kind:'concept',q:'Which method targets a plastic limit load by allowing plastic hinges to form?',choices:['First-order plastic analysis','Linear elastic analysis','Linear buckling analysis only','Modal vibration analysis'],answer:0,explanation:'First-order plastic analysis idealizes plastic hinge formation and seeks the collapse mechanism/load.',source:'Subramanian Ch.4'},
{id:'ch4-method-actual',title:'Closest to actual nonlinear response',level:'application',kind:'reasoning',q:'Which family is intended to follow actual frame response most closely when yielding and second-order effects are important?',choices:['Second-order inelastic/advanced analysis','First-order elastic analysis only','Pure eigenvalue buckling only','Dead-load analysis'],answer:0,explanation:'Figure 4.1 shows advanced second-order inelastic methods tracking nonlinear response more realistically.',source:'Subramanian Ch.4; Chapter 4 PPT Fig. 4.1'},
{id:'ch4-method-bifurcation',title:'Meaning of bifurcation',level:'retrieval',kind:'concept',q:'In a stability analysis, a bifurcation point represents:',choices:['A load level where an alternative equilibrium path can emerge','The point where steel density changes','A weld throat limit','A concrete cracking load'],answer:0,explanation:'The Chapter 4 analysis map labels bifurcation at critical stability points.',source:'Chapter 4 PPT Fig. 4.1'}
],
'4:Elastic Analysis':[
{id:'ch4-elastic-pdelta',title:'P-Δ effect',level:'core',kind:'concept',q:'What does the P-Δ effect represent in a frame?',choices:['Additional moment from axial load acting through overall frame sway','Local weld shrinkage','Only shear deformation of a bolt','Temperature-induced expansion only'],answer:0,explanation:'Chapter 4 illustrates frame stability effects as axial load P acting through lateral sway Δ.',source:'Chapter 4 PPT Fig. 4.6'},
{id:'ch4-elastic-pdelta-small',title:'P-δ effect',level:'core',kind:'concept',q:'What does the P-δ effect refer to?',choices:['Additional member moment from axial load acting through local member curvature','Only global storey translation','Bolt bearing deformation','Foundation settlement only'],answer:0,explanation:'Second-order analysis distinguishes global frame sway P-Δ from local member curvature P-δ.',source:'Subramanian Ch.4; Chapter 4 PPT Fig. 4.7'},
{id:'ch4-elastic-sway',title:'Sway permitted versus restrained',level:'application',kind:'reasoning',q:'Why can an unbraced sway frame show larger second-order effects than a well-braced frame?',choices:['Global lateral displacement allows axial loads to create additional P-Δ moments','Bracing increases steel density','Unbraced frames have no axial force','Second-order effects occur only in beams'],answer:0,explanation:'The chapter compares braced and unbraced frames and shows how sway magnifies geometric effects.',source:'Chapter 4 PPT Figs 4.3, 4.4, 4.7'},
{id:'ch4-elastic-newton',title:'Incremental-iterative solution',level:'advanced',kind:'recognition',q:'Which method is shown in Chapter 4 for tracing a nonlinear load-deflection path iteratively?',choices:['Newton-Raphson method','Miner rule','Wohler method','Whitmore method'],answer:0,explanation:'Figure 4.8 presents a Newton-Raphson incremental-iterative solution for second-order elastic analysis.',source:'Chapter 4 PPT Fig. 4.8'}
],
'4:Buckling (Critical Load) Analysis':[
{id:'ch4-buckling-output',title:'Buckling output',level:'foundation',kind:'concept',q:'A linear buckling analysis normally returns:',choices:['Critical load factors and corresponding buckling modes','A complete nonlinear post-collapse path','Only support reactions at service load','Only weld stresses'],answer:0,explanation:'Linear critical-load analysis identifies elastic bifurcation loads and mode shapes.',source:'Subramanian Ch.4; Chapter 4 PPT'},
{id:'ch4-buckling-eigen',title:'Eigenvalue interpretation',level:'core',kind:'concept',q:'In a linear buckling eigenvalue problem, the eigenvalue is interpreted mainly as:',choices:['A critical load multiplier','A steel density ratio','A damping ratio','A weld efficiency factor'],answer:0,explanation:'The eigenvalue scales the reference load to the elastic critical condition.',source:'Subramanian Ch.4'},
{id:'ch4-buckling-mode',title:'Mode shape meaning',level:'core',kind:'concept',q:'What does the buckling eigenvector or mode shape describe?',choices:['The deformation pattern associated with the critical state','The chemical composition of steel','The load combination factor','The bolt-hole diameter'],answer:0,explanation:'Buckling modes describe the characteristic instability shape associated with an eigenvalue.',source:'Subramanian Ch.4'},
{id:'ch4-buckling-yield',title:'Limit of elastic buckling',level:'core',kind:'reasoning',q:'Why can an elastic eigenvalue buckling load overestimate the strength of a real steel frame?',choices:['It does not by itself capture yielding, residual stresses and imperfections','It always includes plasticity twice','It ignores elastic stiffness','It assumes zero axial load'],answer:0,explanation:'Real columns/frames may lose stiffness before the ideal elastic bifurcation load because of inelasticity and imperfections.',source:'Subramanian Ch.4'},
{id:'ch4-buckling-inelastic',title:'Inelastic buckling',level:'advanced',kind:'concept',q:'What is changed in an inelastic buckling treatment compared with a purely elastic one?',choices:['The stiffness representation is reduced to reflect inelastic material response','Gravity is removed','Boundary conditions are ignored','All members are assumed rigid'],answer:0,explanation:'The chapter notes inelastic buckling approaches that account for reduced stiffness as yielding develops.',source:'Subramanian Ch.4'},
{id:'ch4-buckling-use',title:'Use critical-load analysis wisely',level:'application',kind:'reasoning',q:'What is the best interpretation of a linear buckling result in design?',choices:['It is a stability indicator that must be interpreted with real imperfections and material behaviour','It is automatically the exact ultimate load','It replaces all strength checks','It proves the structure cannot buckle'],answer:0,explanation:'Critical-load analysis is valuable for identifying instability susceptibility but is not a complete ultimate-strength prediction.',source:'Subramanian Ch.4'}
],
'4:Sources of Non-linearity':[
{id:'ch4-nl-material',title:'Material nonlinearity',level:'foundation',kind:'classification',q:'Which is a material source of nonlinearity?',choices:['Yielding of steel','Rigid-body translation only','A constant elastic modulus in a linear range','Section length measurement'],answer:0,explanation:'Yielding and stiffness degradation are material nonlinearities discussed in Chapter 4.',source:'Subramanian Ch.4'},
{id:'ch4-nl-geometric',title:'Geometric nonlinearity',level:'foundation',kind:'classification',q:'Which is a geometric source of nonlinearity?',choices:['P-Δ effect','Yield plateau','Strain hardening only','Weld metal chemistry'],answer:0,explanation:'P-Δ and P-δ effects arise because equilibrium depends on the deformed geometry.',source:'Subramanian Ch.4'},
{id:'ch4-nl-imperfection',title:'Initial imperfections',level:'core',kind:'concept',q:'Why do initial out-of-straightness and frame imperfections matter in nonlinear analysis?',choices:['They can trigger second-order moments under axial load','They eliminate instability','They increase elastic modulus','They make joints perfectly rigid'],answer:0,explanation:'Geometric imperfections create eccentricity and amplify second-order response.',source:'Subramanian Ch.4'},
{id:'ch4-nl-residual',title:'Residual stress effect',level:'core',kind:'reasoning',q:'How can residual stresses contribute to nonlinear structural response?',choices:['They can cause some fibres to yield earlier than an ideal stress distribution predicts','They always raise the elastic critical load','They remove material yielding','They prevent moment redistribution'],answer:0,explanation:'Residual stress is a material imperfection that can initiate gradual yielding and stiffness reduction.',source:'Subramanian Ch.4'},
{id:'ch4-nl-connection',title:'Connection nonlinearity',level:'core',kind:'classification',q:'A nonlinear moment-rotation response of a semi-rigid connection belongs to which modelling issue?',choices:['Joint/connection nonlinearity','Material density','Dead-load calculation','Section classification only'],answer:0,explanation:'Chapter 4 treats real connection deformation as another source of nonlinear system behaviour.',source:'Subramanian Ch.4'},
{id:'ch4-nl-combined',title:'Combined nonlinearities',level:'application',kind:'reasoning',q:'Why can advanced analysis be more realistic than considering each nonlinearity separately?',choices:['Material yielding, geometric effects and connection response can interact during loading','Nonlinearities never occur simultaneously','Advanced analysis removes equilibrium requirements','It assumes all members remain undeformed'],answer:0,explanation:'The chapter motivates advanced system analysis because several nonlinear effects may act together.',source:'Subramanian Ch.4'}
],
'4:Joint and Connection Effects':[
{id:'ch4-joint-rigidzone',title:'Finite joint size',level:'foundation',kind:'concept',q:'Why can modelling a beam-column joint as a dimensionless point be inaccurate?',choices:['The finite width/depth of the joint region affects effective member geometry and stiffness','Joint size changes steel density','A joint cannot transfer force','All columns have zero width'],answer:0,explanation:'Chapter 4 specifically illustrates modelling the effect of column width in frame analysis.',source:'Chapter 4 PPT Figs 4.14'},
{id:'ch4-joint-panel',title:'Panel-zone flexibility',level:'core',kind:'concept',q:'What deformation can occur in the panel zone of a moment-resisting beam-column joint?',choices:['Shear deformation','Only uniform axial extension','No deformation by definition','Only thermal strain'],answer:0,explanation:'The PPT devotes several slides to panel-zone flexibility and its effect on frame response.',source:'Chapter 4 PPT panel-zone slides'},
{id:'ch4-joint-semirigid',title:'Semi-rigid idealisation',level:'core',kind:'concept',q:'How is a semi-rigid connection commonly represented in frame analysis?',choices:['By a moment-rotation relation or rotational spring','By deleting the joint','As infinitely strong concrete','As zero-length axial load only'],answer:0,explanation:'Chapter 4 presents modelling of semi-rigid connections using rotational response rather than an ideal pin/rigid binary assumption.',source:'Subramanian Ch.4; Chapter 4 PPT'},
{id:'ch4-joint-drift',title:'Connection flexibility and drift',level:'core',kind:'reasoning',q:'What can increased rotational flexibility at beam-column connections do to frame sway?',choices:['Increase lateral drift','Force drift to zero','Eliminate P-Δ effects','Increase steel yield strength'],answer:0,explanation:'Connection flexibility can reduce lateral stiffness and thereby increase drift and second-order effects.',source:'Subramanian Ch.4'},
{id:'ch4-joint-redistribution',title:'Moment redistribution',level:'application',kind:'reasoning',q:'Compared with a perfectly rigid idealisation, a semi-rigid connection can:',choices:['Redistribute end moments between connected members','Guarantee identical moments in every member','Remove all shear force','Prevent any rotation'],answer:0,explanation:'Moment-rotation flexibility changes the distribution of forces and moments in the frame.',source:'Subramanian Ch.4'},
{id:'ch4-joint-model',title:'When detailed joint modelling matters',level:'retrieval',kind:'reasoning',q:'Detailed joint modelling is most justified when:',choices:['Connection or panel-zone deformation materially influences system stiffness or strength','Every connection is known to be perfectly rigid','Only member self-weight is needed','The structure has no joints'],answer:0,explanation:'The chapter includes joint size, panel zones and semi-rigid response because these can materially affect frame analysis.',source:'Subramanian Ch.4; Chapter 4 PPT'}
],
'4:First-Order Plastic Analysis':[
{id:'ch4-plastic-rigid',title:'Rigid-plastic idealisation',level:'foundation',kind:'concept',q:'What material idealisation is commonly used in first-order plastic collapse analysis?',choices:['Rigid-plastic behaviour with concentrated plastic hinges','Perfectly brittle behaviour only','Linear elastic behaviour up to infinite load','Viscoelastic creep only'],answer:0,explanation:'First-order plastic analysis idealizes collapse through plastic hinge formation without second-order instability effects.',source:'Subramanian Ch.4'},
{id:'ch4-plastic-mechanism',title:'Mechanism condition',level:'core',kind:'concept',q:'What signals collapse in first-order plastic analysis?',choices:['Enough plastic hinges form to turn the structure into a mechanism','The first elastic stress appears','One support reaction becomes nonzero','The first bolt is installed'],answer:0,explanation:'Plastic collapse occurs when hinge formation creates a kinematic mechanism.',source:'Subramanian Ch.4'},
{id:'ch4-plastic-proportional',title:'Proportional loading',level:'core',kind:'recognition',q:'In the first-order plastic procedure described in the chapter, loads are generally increased:',choices:['Proportionally until a collapse mechanism forms','Only one load is allowed to change randomly','After the structure has already fractured','Without preserving equilibrium'],answer:0,explanation:'Plastic limit analysis commonly scales the prescribed load pattern proportionally to collapse.',source:'Subramanian Ch.4'},
{id:'ch4-plastic-ductility',title:'Rotation capacity',level:'core',kind:'reasoning',q:'Why is adequate ductility needed for plastic analysis?',choices:['Plastic hinges must sustain rotation so redistribution and a mechanism can develop','Ductility eliminates bending moments','Plastic analysis assumes no yielding','Rotation capacity increases steel density'],answer:0,explanation:'The chapter notes that sufficient plastic hinge rotation capacity is necessary to reach the assumed collapse mechanism.',source:'Subramanian Ch.4'},
{id:'ch4-plastic-stability',title:'Limitation of first-order plastic analysis',level:'advanced',kind:'reasoning',q:'Why can first-order plastic analysis be unsafe for a very slender frame?',choices:['It neglects geometric instability and second-order effects','It always underestimates member weight','It ignores dead load only','It assumes no plasticity'],answer:0,explanation:'First-order plastic analysis determines a plastic limit load while ignoring instability effects.',source:'Subramanian Ch.4'},
{id:'ch4-plastic-local',title:'Local buckling restriction',level:'application',kind:'reasoning',q:'Why must local or lateral buckling be controlled when relying on plastic moment capacity?',choices:['Premature instability can prevent the section from developing and sustaining the required plastic hinge','Buckling always improves rotation capacity','Plastic hinges require zero bending','Buckling changes only member colour'],answer:0,explanation:'The chapter notes restrictions needed so plastic capacity and hinge rotation can actually develop.',source:'Subramanian Ch.4'}
],
'4:Second-Order Inelastic Analyses':[
{id:'ch4-adv-plasticzone',title:'Plastic-zone method',level:'advanced',kind:'concept',q:'What distinguishes a plastic-zone analysis from a concentrated-hinge approximation?',choices:['It models the spread of yielding through member cross-sections/length more explicitly','It assumes no yielding anywhere','It uses only dead load','It replaces members with rigid links'],answer:0,explanation:'Plastic-zone analysis represents distributed yielding in greater detail than hinge methods.',source:'Subramanian Ch.4'},
{id:'ch4-adv-hinge',title:'Plastic-hinge method',level:'core',kind:'concept',q:'What computational simplification is made in plastic-hinge advanced methods?',choices:['Plasticity is concentrated at selected hinge locations rather than distributed continuously','All members are removed','Geometric effects are ignored by definition','Elastic stiffness is infinite'],answer:0,explanation:'Concentrated hinge methods trade detailed spread-of-yielding modelling for computational efficiency.',source:'Subramanian Ch.4'},
{id:'ch4-adv-refined',title:'Refined plastic-hinge method',level:'advanced',kind:'reasoning',q:'Why is the refined plastic-hinge approach attractive for design-office use?',choices:['It balances computational efficiency with modelling of stiffness degradation, imperfections and residual effects','It requires no structural model','It cannot include second-order effects','It assumes all joints are pins'],answer:0,explanation:'The chapter summary identifies refined plastic-hinge analysis as a practical compromise between accuracy and efficiency.',source:'Subramanian Ch.4'},
{id:'ch4-adv-system',title:'Direct system assessment',level:'application',kind:'concept',q:'What is assessed directly in a second-order inelastic analysis?',choices:['Overall strength and stability of the structural system','Only steel density','Only elastic deflection at zero load','Only connection bolt count'],answer:0,explanation:'Advanced analysis integrates material nonlinearity and geometric stability in one system analysis.',source:'Subramanian Ch.4'}
],
'4:Practical Out-of-Plane Advanced Analysis':[
{id:'ch4-oop-why',title:'Why 3D effects matter',level:'foundation',kind:'concept',q:'Why can a purely in-plane frame analysis miss an important failure mode?',choices:['Members may bend laterally, twist or buckle out of plane','Steel cannot carry in-plane load','Gravity acts only out of plane','Connections prevent all torsion'],answer:0,explanation:'Chapter 4 warns that real frames can fail by lateral bending, torsion or lateral/torsional buckling.',source:'Subramanian Ch.4'},
{id:'ch4-oop-restraint',title:'Lateral restraint',level:'core',kind:'reasoning',q:'What modelling feature is especially important when assessing out-of-plane stability?',choices:['Actual lateral and torsional restraints along the member','Paint colour','Only member mass','Concrete slump'],answer:0,explanation:'Out-of-plane response depends strongly on bracing, restraints and member torsional/lateral stiffness.',source:'Subramanian Ch.4'},
{id:'ch4-oop-imperf',title:'Out-of-plane imperfections',level:'core',kind:'concept',q:'Why should out-of-plane imperfections be represented in advanced analysis when relevant?',choices:['They can initiate lateral/torsional instability under load','They always increase strength','They eliminate geometric stiffness','They make all frames braced'],answer:0,explanation:'Initial imperfections influence stability paths and should be represented when they are relevant to the expected failure mode.',source:'Subramanian Ch.4'},
{id:'ch4-oop-combined',title:'Combined action',level:'core',kind:'reasoning',q:'Which combination can make out-of-plane advanced analysis necessary?',choices:['Axial force with in-plane bending plus susceptibility to lateral/torsional instability','Zero load with no restraint','Only uniform temperature in a free member','Only self-weight of a rigid block'],answer:0,explanation:'The chapter notes that axial force and in-plane bending may interact with out-of-plane buckling modes.',source:'Subramanian Ch.4'},
{id:'ch4-oop-3d',title:'Three-dimensional model',level:'application',kind:'concept',q:'A practical 3D advanced model should capture:',choices:['Member/frame lateral and torsional stiffness, imperfections and restraints','Only vertical reactions','Only material density','Only section labels'],answer:0,explanation:'Out-of-plane analysis requires the stiffness and restraint features that control lateral/torsional response.',source:'Subramanian Ch.4'},
{id:'ch4-oop-limit',title:'2D model limitation',level:'retrieval',kind:'reasoning',q:'When is a 2D in-plane advanced analysis most questionable?',choices:['When the governing failure may occur out of the analysis plane','When all members are fully laterally restrained and only in-plane response is relevant','When there is no load','When the structure is a simple scalar equation'],answer:0,explanation:'A 2D model cannot represent failure modes that require out-of-plane degrees of freedom.',source:'Subramanian Ch.4'}
],
'4:Summary':[
{id:'ch4-summary-conventional',title:'Conventional versus advanced',level:'foundation',kind:'concept',q:'What is the central contrast in the Chapter 4 summary?',choices:['Conventional analysis plus separate checks versus advanced direct system analysis','Steel versus timber density','Bolting versus painting','Dead load versus live load only'],answer:0,explanation:'The summary contrasts traditional first/second-order elastic analysis with separate member checks against direct advanced system assessment.',source:'Subramanian Ch.4 summary'},
{id:'ch4-summary-nonlinearity',title:'Nonlinear ingredients',level:'core',kind:'classification',q:'Which ingredients are highlighted as important refinements in advanced steel-frame analysis?',choices:['Residual stresses, imperfections, second-order effects and connection response','Only paint thickness and colour','Only steel density and temperature','Only support labels'],answer:0,explanation:'The chapter summary reviews the main real-behaviour effects that advanced models may need to include.',source:'Subramanian Ch.4 summary'},
{id:'ch4-summary-buckling',title:'Buckling role',level:'core',kind:'concept',q:'What does buckling analysis contribute that first-order elastic analysis does not?',choices:['Information about critical stability loads and modes','Chemical composition','Weld throat size','Concrete strength'],answer:0,explanation:'Buckling analysis examines stability and bifurcation rather than only linear force-displacement response.',source:'Subramanian Ch.4 summary'},
{id:'ch4-summary-plastic',title:'Plastic role',level:'core',kind:'concept',q:'What does plastic analysis add beyond purely elastic analysis?',choices:['Yielding, redistribution and plastic-collapse mechanisms','Infinite stiffness','Zero rotations','No need for equilibrium'],answer:0,explanation:'Plastic analysis allows yielding and hinge formation to be used in assessing collapse strength.',source:'Subramanian Ch.4 summary'},
{id:'ch4-summary-joints',title:'Joint effects reminder',level:'application',kind:'reasoning',q:'Why are semi-rigid joint effects included in the chapter summary?',choices:['Connection flexibility can change force distribution and drift','Joint response never affects frames','Semi-rigid means fully fixed','Panel zones have zero size'],answer:0,explanation:'Connection moment-rotation and panel-zone response are system-level modelling issues.',source:'Subramanian Ch.4 summary'},
{id:'ch4-summary-office',title:'Practical advanced method',level:'retrieval',kind:'concept',q:'Which advanced method is highlighted as a practical design-office compromise?',choices:['Refined plastic-hinge analysis','Only exact plastic-zone analysis','Only first-order elastic analysis','Only graphical statics'],answer:0,explanation:'The chapter summary identifies refined plastic-hinge analysis as especially practical.',source:'Subramanian Ch.4 summary'}
],
'4:Exercises':[
{id:'ch4-ex-braced',title:'Compare analysis orders',level:'foundation',kind:'application',q:'One Chapter 4 exercise theme is to compare:',choices:['First-order and second-order frame results','Steel and concrete colour','Paint and galvanizing cost only','Bolt and rivet density'],answer:0,explanation:'The exercise set explicitly asks readers to compare linear-elastic and second-order responses.',source:'Subramanian Ch.4 exercises'},
{id:'ch4-ex-buckling',title:'Buckling exercise',level:'core',kind:'application',q:'Which quantity is explicitly investigated in the Chapter 4 exercises?',choices:['Elastic and inelastic buckling loads','Concrete slump only','Weld electrode diameter only','Fire insulation thickness only'],answer:0,explanation:'Exercises include computing and comparing buckling loads.',source:'Subramanian Ch.4 exercises'},
{id:'ch4-ex-semirigid',title:'Connection modelling exercise',level:'core',kind:'application',q:'What connection-related modelling issue is included in the exercises?',choices:['Semi-rigid connection flexibility','Only rigid joints are allowed','No joint modelling','Only bolt counting'],answer:0,explanation:'The exercise set asks readers to include semi-rigid connection flexibility.',source:'Subramanian Ch.4 exercises'},
{id:'ch4-ex-foundation',title:'Foundation flexibility exercise',level:'core',kind:'application',q:'Which support effect is included among the Chapter 4 modelling exercises?',choices:['Foundation rotational stiffness','Foundation colour','Soil density only with no structural model','Zero support flexibility by definition'],answer:0,explanation:'The exercises include modelling foundation rotational stiffness and observing its structural effect.',source:'Subramanian Ch.4 exercises'},
{id:'ch4-ex-plastic',title:'Plastic-collapse exercise',level:'core',kind:'application',q:'Which nonlinear strength task appears in the exercises?',choices:['Calculate a plastic collapse load','Calculate only dead load','Measure paint thickness','Find atmospheric pressure'],answer:0,explanation:'The exercise set includes plastic-collapse calculations.',source:'Subramanian Ch.4 exercises'},
{id:'ch4-ex-advanced',title:'Advanced versus conventional',level:'retrieval',kind:'reasoning',q:'Why compare advanced-analysis member forces with conventional elastic-analysis/code-check results?',choices:['To see how modelling assumptions alter predicted structural response and design demand','To prove both methods must always be identical','To remove stability effects','To avoid interpreting results'],answer:0,explanation:'The exercises are intended to make the influence of modelling assumptions visible.',source:'Subramanian Ch.4 exercises'}
],
'4:Review Questions':[
{id:'ch4-rq-iterative',title:'Why analysis and design iterate',level:'foundation',kind:'concept',q:'Why can steel analysis and design become iterative?',choices:['Changing member sizes changes stiffness and therefore the force distribution and stability response','Member size never affects stiffness','Analysis is independent of geometry','Connections cannot affect forces'],answer:0,explanation:'The chapter review asks when analysis and design become iterative because design changes can alter the structural model.',source:'Subramanian Ch.4 review questions'},
{id:'ch4-rq-twostage',title:'Two-stage limitation',level:'core',kind:'reasoning',q:'What is a limitation of a strict analysis-then-separate-member-check workflow?',choices:['System interactions and nonlinear stability may not be represented directly in the analysis','It always includes every nonlinear effect','It is identical to plastic-zone analysis','It eliminates all conservatism'],answer:0,explanation:'The review questions highlight limitations of the traditional two-stage design process.',source:'Subramanian Ch.4 review questions'},
{id:'ch4-rq-inelastic',title:'Advantage of inelastic analysis',level:'core',kind:'concept',q:'What advantage can inelastic analysis offer for direct design?',choices:['It can represent yielding and redistribution in the structural system','It forces all members to remain elastic','It removes second-order effects','It ignores stability'],answer:0,explanation:'Direct inelastic analysis can represent material response that conventional elastic analysis leaves to separate checks.',source:'Subramanian Ch.4 review questions'},
{id:'ch4-rq-firstassump',title:'First-order assumption',level:'core',kind:'recognition',q:'Which assumption is central to first-order elastic analysis?',choices:['Equilibrium is based on the undeformed geometry','All members are plastic hinges','The frame is analysed after collapse','Geometric stiffness is always dominant'],answer:0,explanation:'The review asks for the assumptions and limitations of first-order elastic analysis.',source:'Subramanian Ch.4 review questions'},
{id:'ch4-rq-real',title:'Why first-order is incomplete',level:'application',kind:'reasoning',q:'Why may first-order results differ from true frame behaviour at high axial load or large drift?',choices:['They omit deformation-induced second-order actions','They include too many plastic hinges','They automatically include P-Δ twice','They use a nonlinear material model'],answer:0,explanation:'The chapter review emphasizes that first-order analysis does not capture important nonlinear geometric behaviour.',source:'Subramanian Ch.4 review questions'},
{id:'ch4-rq-methodselect',title:'Method selection retrieval',level:'retrieval',kind:'classification',q:'Which answer best lists analysis options discussed for steel frames?',choices:['First/second-order elastic, buckling, plastic and advanced inelastic methods','Only static equilibrium by hand','Only finite-difference heat flow','Only fatigue S-N analysis'],answer:0,explanation:'This is the chapter-wide retrieval point of the review section.',source:'Subramanian Ch.4 review questions'}
]
});