Object.assign(window.REVISION_BANK,{
'13:Nominal Strength—Instability in the Plane of Bending':[
{id:'steel25-inplane-instability',title:'In-plane beam-column instability',level:'core',kind:'concept',q:'A beam-column under compression and bending may lose resistance through:',choices:['Combined flexural instability and bending interaction','Pure temperature change only','Only bolt slip','Only corrosion loss'],answer:0,explanation:'Axial compression amplifies flexural response and can trigger overall in-plane instability before simple section strength is reached.',source:'Subramanian Ch.13 topic + standard beam-column bridge (model supplement)'},
{id:'steel25-pdelta-member',title:'Member P–δ effect',level:'application',kind:'formula',q:'For a compressed member with lateral deflection δ, the additional second-order moment is approximately:',choices:['Pδ','P/δ','EIδ²','Pδ/L²'],answer:0,explanation:'The axial force acting through the displaced member axis generates the local second-order P–δ moment.',math:'M_{2}\\approx P\\delta',source:'Subramanian Ch.13 topic + standard second-order bridge (model supplement)'}
],
'13:Beam-column under Biaxial Loading':[
{id:'steel25-biaxial',title:'Biaxial beam-column action',level:'foundation',kind:'concept',q:'Biaxial beam-column loading means the member is subjected to:',choices:['Axial force plus bending about both principal axes','Shear only','Torsion only','Axial tension only'],answer:0,explanation:'Biaxial beam-columns carry compression or tension together with moments about two axes.',source:'Subramanian Ch.13 topic + standard steel-design bridge (model supplement)'},
{id:'steel25-interaction',title:'Interaction equation concept',level:'core',kind:'formula',q:'Why are interaction equations used for beam-columns?',choices:['To combine utilization from axial force and bending actions','To calculate density','To replace stability checks','To determine weld color'],answer:0,explanation:'Interaction equations express how simultaneous axial and flexural demands consume member resistance.',math:'\\frac{N}{N_d}+\\frac{M_x}{M_{dx}}+\\frac{M_y}{M_{dy}}\\lesssim1\\quad\\text{(conceptual form)}',source:'Subramanian Ch.13 topic + conceptual beam-column design bridge (model supplement)'}
],
'14:Purlins, Girts, and Eave Strut':[
{id:'steel25-purlin-role',title:'Purlin structural role',level:'foundation',kind:'concept',q:'What is the primary role of a purlin in an industrial building?',choices:['Support roof sheeting and transfer roof loads to main frames or trusses','Support foundations','Act only as a column base','Carry crane wheels directly'],answer:0,explanation:'Purlins are secondary roof members spanning between primary frames or trusses.',source:'Subramanian Ch.14 topic + standard industrial-building bridge (model supplement)'},
{id:'steel25-girt-role',title:'Girt structural role',level:'foundation',kind:'concept',q:'A girt primarily supports:',choices:['Wall cladding and transfers lateral wall loads to frames','Roof ridge only','Column base plates','Crane rails only'],answer:0,explanation:'Girts are horizontal wall secondary members supporting cladding and wind loads.',source:'Subramanian Ch.14 topic + standard industrial-building bridge (model supplement)'}
],
'14:Plane Trusses':[
{id:'steel25-truss-assumption',title:'Ideal truss assumption',level:'foundation',kind:'concept',q:'In ideal plane-truss analysis, member forces are assumed to be primarily:',choices:['Axial','Bending only','Torsional only','Hydrostatic'],answer:0,explanation:'Pin-jointed idealization leads to two-force members carrying tension or compression.',source:'Subramanian Ch.14 topic + standard structural-analysis bridge (model supplement)'},
{id:'steel25-triangulation',title:'Why triangulate trusses?',level:'core',kind:'reasoning',q:'Why is triangulation fundamental in plane trusses?',choices:['A triangle is geometrically stable without requiring bending stiffness at joints','It eliminates axial force','It makes every member identical','It prevents all buckling'],answer:0,explanation:'Triangulation creates a stable pin-jointed framework whose geometry does not change without changing member lengths.',source:'Subramanian Ch.14 topic + standard structural-analysis bridge (model supplement)'}
],
'15:Corrosion of Steel':[
{id:'steel25-corrosion-cell',title:'Electrochemical corrosion',level:'core',kind:'concept',q:'Atmospheric corrosion of ordinary steel is fundamentally:',choices:['An electrochemical oxidation process','A purely mechanical buckling process','A thermal expansion process only','A fatigue crack only'],answer:0,explanation:'Corrosion involves anodic metal dissolution coupled with cathodic reactions in the presence of an electrolyte.',source:'Subramanian Ch.15 topic + standard corrosion bridge (model supplement)'},
{id:'steel25-section-loss',title:'Structural effect of corrosion',level:'application',kind:'reasoning',q:'Why is corrosion structurally important even if the steel grade itself has not changed?',choices:['Loss of cross-sectional area reduces resistance and stiffness','Young’s modulus always doubles','Member length becomes zero','Connections become frictionless'],answer:0,explanation:'Material loss can reduce area, section modulus and local thickness, directly affecting capacity.',source:'Subramanian Ch.15 topic + standard durability bridge (model supplement)'}
],
'15:Corrosion-protection Methods':[
{id:'steel25-coating',title:'Barrier protection',level:'foundation',kind:'concept',q:'Paint systems protect steel mainly by:',choices:['Creating a barrier that limits water, oxygen and contaminants reaching steel','Increasing yield stress permanently','Removing all residual stress','Preventing thermal expansion'],answer:0,explanation:'Protective coatings isolate the steel surface from the corrosive environment.',source:'Subramanian Ch.15 topic + standard corrosion-protection bridge (model supplement)'},
{id:'steel25-galvanizing',title:'Galvanizing principle',level:'core',kind:'concept',q:'Why can zinc galvanizing protect exposed steel even after a small coating scratch?',choices:['Zinc can provide sacrificial electrochemical protection','Zinc makes steel stainless','Zinc eliminates oxygen from air','Zinc prevents all fatigue'],answer:0,explanation:'Zinc is more active electrochemically than steel and can corrode preferentially, protecting nearby exposed steel.',source:'Subramanian Ch.15 topic + standard corrosion-protection bridge (model supplement)'}
],
'16:Calculation of Temperature Rise in Steel Members':[
{id:'steel25-fire-thermal',title:'Steel temperature rise',level:'core',kind:'reasoning',q:'For the same fire exposure, which unprotected steel member generally heats faster?',choices:['The one with higher exposed perimeter-to-section-area ratio','The one with lower surface factor','The heavier section with much more area per exposed perimeter','All heat identically'],answer:0,explanation:'A larger section factor means more heated surface per unit steel volume, producing faster temperature rise.',source:'Subramanian Ch.16 topic + standard structural-fire bridge (model supplement)'},
{id:'steel25-section-factor',title:'Section factor',level:'core',kind:'formula',q:'A common steel section factor used in fire calculations is proportional to:',choices:['Exposed perimeter divided by steel cross-sectional area','Area divided by density','Length squared divided by area','Yield stress divided by temperature'],answer:0,explanation:'The heated perimeter-to-area ratio controls how quickly heat enters the steel mass.',math:'H_p/A',source:'Subramanian Ch.16 topic + standard structural-fire bridge (model supplement)'}
],
'16:Mechanical Properties of Steel at Elevated Temperatures':[
{id:'steel25-hot-e',title:'Elastic modulus in fire',level:'foundation',kind:'concept',q:'As structural steel temperature becomes very high in a fire, its elastic modulus generally:',choices:['Decreases','Increases without limit','Remains exactly constant','Becomes negative immediately'],answer:0,explanation:'Elevated temperature progressively reduces stiffness.',source:'Subramanian Ch.16 topic + standard structural-fire bridge (model supplement)'},
{id:'steel25-hot-fy',title:'Strength reduction in fire',level:'core',kind:'reasoning',q:'Why can a steel member fail in fire even when the applied load has not increased?',choices:['Yield strength and stiffness reduce as temperature rises','Density becomes infinite','Dead load disappears','Poisson ratio alone controls collapse'],answer:0,explanation:'Thermal degradation lowers both strength and stiffness, reducing member resistance and stability.',source:'Subramanian Ch.16 topic + standard structural-fire bridge (model supplement)'}
],
'17:Fatigue Loading':[
{id:'steel25-stress-range',title:'Stress range',level:'foundation',kind:'formula',q:'In fatigue assessment, stress range Δσ is:',choices:['σ_max−σ_min','σ_max+σ_min','σ_max/σ_min always','σ_mean²'],answer:0,explanation:'Fatigue damage is strongly related to the repeated stress range experienced by the detail.',math:'\\Delta\\sigma=\\sigma_{max}-\\sigma_{min}',source:'Subramanian Ch.17 topic + standard fatigue bridge (model supplement)'},
{id:'steel25-cycles',title:'Why cycle count matters',level:'core',kind:'reasoning',q:'Why does the number of load cycles matter in fatigue design?',choices:['Repeated cycling can grow cracks even when each individual cycle is below static strength','Steel becomes heavier each cycle','Young’s modulus doubles with cycling','Residual stress vanishes after one cycle'],answer:0,explanation:'Fatigue is cumulative damage caused by repeated stress fluctuations.',source:'Subramanian Ch.17 topic + standard fatigue bridge (model supplement)'}
],
'18:Behaviour of Members Due to Torsion':[
{id:'steel25-torsion-types',title:'St Venant versus warping torsion',level:'core',kind:'concept',q:'In open thin-walled steel sections, torsional response may involve:',choices:['Both St Venant torsion and warping torsion','Only axial strain','Only hydrostatic pressure','No shear stress'],answer:0,explanation:'Open sections can experience significant warping in addition to uniform St Venant torsion.',source:'Subramanian Ch.18 topic + standard torsion bridge (model supplement)'},
{id:'steel25-torsion-stress',title:'St Venant torsional stiffness',level:'core',kind:'formula',q:'For uniform St Venant torsion, torsional stiffness is governed by:',choices:['GJ','EI only','AE only','ρA'],answer:0,explanation:'The product of shear modulus G and torsion constant J governs uniform torsional stiffness.',math:'T=GJ\\,\\frac{d\\theta}{dx}',source:'Subramanian Ch.18 topic + standard torsion bridge (model supplement)'}
]
});