window.STEEL_BOOK=[
[1,"Materials, Structures, and Specifications",`Introduction|Historical Development|Processes Used for Iron and Steel Making|Iron and Steel in India|Metallurgy of Steel|Alloying Elements in Steel|Chemical Composition of Steel|Types of Structural Steel|Mechanical Properties of Steel|Residual Stresses|Stress Concentration|Cold Work and Strain Hardening|Structural Steel Products|Cold-formed Steel Sections|High-performance Steel|Stainless Steel|Advantages of Steel as a Structural Material|Types of Steel Structures|Aluminium Alloys|Fabrication and Erection|Aesthetics of Steel Structures|Composite Construction|Summary|Review Questions`],
[2,"The Basis of Structural Design",`Design Considerations|Steps Involved in Construction|Role and Responsibilities of the Designer|Structural Systems|Structural Integrity|Analysis and Design|Codes and Specifications|Design Philosophies|Limit States Method (LSM)|Failure Criteria for Steel|Summary|Review Questions`],
[3,"Loading and Load Combinations",`Introduction|Characteristic Actions (Loads)|Dead Loads|Imposed Loads|Temperature Effects|Hydrostatic and Soil Pressure|Erection Loads|Accidental Loads|Other Loads|Natural Hazards|Extreme Winds|Earthquakes|Determination of Earthquake Forces|Determination of Wind Loads as per IS 875 (Part 3)|Pattern Loading|Load Combinations|Examples|Summary|Exercise|Review Questions`],
[4,"Methods of Structural Analysis",`Introduction|Methods of Analysis|Elastic Analysis|Buckling (Critical Load) Analysis|Sources of Non-linearity|Joint and Connection Effects|First-Order Plastic Analysis|Second-Order Inelastic Analyses|Practical Out-of-Plane Advanced Analysis|Summary|Exercises|Review Questions`],
[5,"Bolted Connections",`Introduction|Rivets and Riveted Connections|Bolted Connections|Behaviour of Bolted Joints|Design Strength of Ordinary Black Bolts|Design Strength of High Strength Friction Grip Bolts|Pin Connections|Simple Connections|Moment Resistant Connections|Beam-to-Beam Connections|Beam and Column Splices|Semi-Rigid Connections|Fatigue Behaviour|Examples|Summary|Exercises|Review Questions`],
[6,"Welded Connections",`Introduction|Welding Processes|Welding Electrodes|Advantages of Welding|Types and Properties of Welds|Types of Joints|Control of Shrinkage and Distortion|Weld Symbols|Weld Specifications|Effective Areas of Welds|Design of Welds|Simple Joints|Moment Resistant Connections|Continuous Beam-to-Column Connections|Continuous Beam-to-Beam Connections|Beam-Column Splices|Tubular Connections|Recent Developments in Connection Design|Application of Adhesives|Examples|Summary|Exercises|Review Questions`],
[7,"Design of Tension Members",`Introduction|Types of Tension Members|Design of Strands|Slenderness Ratio|Displacement of Tension Members|Behaviour of Tension Members|Modes of Failure|Factors Affecting the Strength of Tension Members|Angles Under Tension|Other Sections|Tension Rods|Design of a Tension Member|Lug Angles|Splices|Gussets|Fatigue Effects|Examples|Summary|Exercises|Review Questions`],
[8,"Plastic and Local Buckling Behaviour of Structural Steel",`Introduction|Plastic Theory|General Requirements for Plastic Design|Plastic Hinge Concept|Plastic-collapse Load|Conditions of Plastic Analysis|Theorems of Plastic Collapse|Methods of Plastic Analysis|Plastic Design of Continuous Beams|Plastic Design of Portal Frames|Effect of Axial and Shear Force on Plastic Moment Capacity|Special Considerations|Local Buckling of Plates|Cross Section Classification|Behaviour and Ultimate Strength of Plates|Examples|Summary|Exercises|Review Questions`],
[9,"Design of Compression Members",`Introduction|Construction Details|Possible Failure Modes|Classification of Cross Section|Behaviour of Compression Members|Elastic Buckling of Slender Compression Members|Behaviour of Real Compression Members|Development of Multiple Column Curves|Sections Used for Compression Members|Effective Length of Compression Members|Flexural-Torsional Buckling|Columns with No Axis of Symmetry|Prevention of Buckling Failure|Single Angle Struts|Design of Compression Members|Built-up Compression Members|Compression Members Composed of Two Components Back-to-back|Column Bases and Caps|Compression Members with Other Materials and Shapes|Displacement|Examples|Summary|Exercises|Review Questions`],
[10,"Design of Beams",`Introduction|Types|Section Classification|Lateral Stability of Beams|Lateral Torsional Buckling of Symmetric Sections|Factors Affecting Lateral Stability|Buckling of Real Beams|Behaviour of Beams in Bending|Design Strength of Laterally Supported Beams in Bending|Design Strength of Laterally Unsupported Beams|Shear Strength of Steel Beams|Maximum Deflection|Web Buckling and Web Crippling|Holes in Beams|Latticed Beams|Castellated Beams|Lintels|Purlins|Biaxial Bending|Unsymmetrical Bending|Unsymmetric Sections|Design of Beams|Examples|Summary|Exercises|Review Questions`],
[11,"Design of Plate Girders",`Introduction|Plate Girders|General Considerations|Distribution of Stress in a Plate Girder|Preliminary Design Procedure|Web Panel Subjected to Shear|Webs Subjected to Combined Bending and Shear|Design of Plate Girders using IS 800 Provisions|Behaviour of Longitudinally Stiffened Plate Girders|Girders with Openings in Slender Webs|Hybrid Plate Girders|Welding of Girder Components|Proportioning of the Section|Plate Girders With Corrugated Webs|Box Girders|Steel Plate Shear Walls (SPSW)|Examples|Summary|Exercises|Review Questions`],
[12,"Gantry Girders",`Introduction|Loading Considerations|Maximum Load Effects|Fatigue Effects|Selection of Gantry Girder|Design of Gantry Girder|Examples|Summary|Exercises|Review Questions`],
[13,"Design of Beam-columns",`Introduction|General Behaviour of Beam-columns|Second-order Moments in Beam-columns|Elastic Torsional Buckling of Beam-columns|Interaction between Beam-column and Structure|Nominal Strength—Instability in the Plane of Bending|Beam-column under Biaxial Loading|Interaction Equations for Local Capacity Check|Code Design Procedures|Design of Beam-columns|Beam-columns Subjected to Tension and Bending|Crane Columns|Design of Eccentrically Loaded Base Plates|Examples|Summary|Exercises|Review Questions`],
[14,"Design of Industrial Buildings",`Introduction|Selection of Roofing and Wall Material|Selection of Bay Width|Structural Framing|Purlins, Girts, and Eave Strut|Plane Trusses|Floor Plates|End Bearings|Design of Slabs on Grade|Examples|Summary|Review Questions|Exercises`],
[15,"Corrosion Protection of Steel Structures",`Introduction|Corrosion of Steel|Corrosion-protection Methods|Atmospheric-Corrosion-Resistant Steels|Corrosion Allowance|Summary|Review Questions`],
[16,"Fire-resistant Design",`Introduction|Fire Research|Design Curves and Fire Models|Fire Engineering Design Problems|Fire Engineering Design of Steel Structures|Calculation Approach|Calculation of Temperature Rise in Steel Members|Mechanical Properties of Steel at Elevated Temperatures|Time to Reach Limiting Temperature|Passive Protection for Steelwork|Fire-resistant Steels|Fire Performance Assessment|Examples|Summary|Exercises|Review Questions`],
[17,"Fatigue-resistant Design",`Introduction|Factors Affecting Fatigue Life|Different Approaches to Fatigue Analysis|Fatigue Loading|Stress Methods|Fatigue Assessment for Variable Stress Ranges|General Guidelines for Fatigue-resistant Design|Fatigue Assessment Under Combined Stresses|Fatigue Analysis of Building Frames|Examples|Summary|Exercises|Review Questions`],
[18,"Design for Torsion",`Introduction|Torsional Loading in Practice|Behaviour of Members Due to Torsion|Shear Centre|Approximate Design Procedure for Torsion|Distortion of Thin Walled Members|Torsional Stiffening and End Restraints|Torsional Buckling|Torsional Deformations|Examples|Summary|Exercises|Review Questions`]
].map(([n,title,s])=>({n,title,topics:s.split('|')}));

window.STEEL_APPENDICES=[
['A','Properties of Structural Steel Sections'],['B','Loads Due to Tsunami'],['C','Properties of Soils'],['D','Bending Moment, Shear Force, and Deflection of Beams and Frames'],['E','Computer Programs'],['F','Conversion Factors']
];

window.STEEL_DEEP={
'1:Introduction':{e:'Structural design selects a structural form and material so the finished structure can carry loads safely and perform acceptably. The chapter positions steel beside masonry, reinforced concrete and wood, then develops why steel is widely used.',q:'Which statement best matches the chapter opening view of structural design?',o:['Choose a structural form and material that safely carry loads','Choose the densest material available','Avoid considering service behaviour','Use steel for every structure'],a:0},
'1:Historical Development':{e:'The chapter traces iron and steel from ancient use through cast and wrought iron to modern steelmaking. The Bessemer process and later basic-oxygen and electric processes made large-scale structural-steel production practical.',q:'Why is the Bessemer process historically important in structural steel?',o:['It enabled much faster large-scale steel production','It invented reinforced concrete','It eliminated carbon from all steels','It was a welding method'],a:0},
'1:Processes Used for Iron and Steel Making':{e:'The source describes ironmaking in blast furnaces and steelmaking by routes such as basic oxygen and electric furnaces, followed by casting and rolling into structural products.',q:'Which sequence is consistent with the chapter manufacturing discussion?',o:['Ironmaking → steelmaking → casting/rolling','Rolling → mining → steelmaking','Welding → casting → iron ore','Painting → forging → mining'],a:0},
'1:Iron and Steel in India':{e:'The chapter notes India long history of iron use and discusses integrated steel plants and the importance of the steel industry to construction and infrastructure.',q:'What is an integrated steel plant intended to do?',o:['Carry out multiple stages of iron and steel production in one industrial system','Only paint finished beams','Only fabricate bolts','Only recycle aluminium'],a:0},
'1:Metallurgy of Steel':{e:'Steel behaviour depends on its internal crystal and phase structure. The chapter introduces crystal lattices, the iron–carbon equilibrium diagram and heat-treatment effects to connect microstructure with engineering properties.',q:'Why does metallurgy matter to a structural engineer?',o:['Microstructure influences strength, ductility and toughness','It determines only paint colour','It changes member span without changing material','It replaces structural analysis'],a:0},
'1:Alloying Elements in Steel':{e:'Carbon and alloying additions alter steel properties. The text discusses elements such as manganese, silicon, chromium, nickel, copper and others because composition affects strength, ductility, toughness, corrosion behaviour and weldability.',q:'What is the main reason alloying elements are discussed?',o:['They change important mechanical and durability properties','They change only density','They remove the need for design codes','They make all steels identical'],a:0},
'1:Chemical Composition of Steel':{e:'The chapter relates steel grades to chemical limits and discusses weldability through composition, including carbon-equivalent concepts. Composition is therefore a design and fabrication issue, not just a manufacturing detail.',q:'Why can chemical composition affect weldability?',o:['It influences hardenability and cracking tendency in and near welds','It changes beam length automatically','It eliminates residual stress completely','It determines only surface finish'],a:0},
'1:Types of Structural Steel':{e:'The source distinguishes structural carbon steels, higher-strength steels, microalloyed steels, quenched-and-tempered steels, weathering steels, stainless steels and fire-resistant steels, each selected for different performance needs.',q:'Why are there multiple structural-steel types?',o:['Different applications require different combinations of properties','Every structure needs the same steel','Only density varies between grades','Steel type matters only for appearance'],a:0},
'1:Mechanical Properties of Steel':{e:'The chapter develops tensile strength, yield strength, modulus of elasticity, ductility, toughness, hardness and related properties. The stress–strain curve connects these quantities to actual material response.',q:'Which property marks the onset of significant plastic deformation in ordinary structural steel?',o:['Yield strength','Density','Thermal conductivity','Poisson ratio'],a:0},
'1:Residual Stresses':{e:'Residual stresses are self-equilibrating stresses that remain without external load. The chapter links them to nonuniform heating, cooling, rolling, welding and fabrication, and shows typical distributions in rolled and welded sections.',q:'Can a steel member contain stress when external load is zero?',o:['Yes, residual stresses may remain','No, stress must always be zero','Only concrete can','Only after fracture'],a:0},
'1:Stress Concentration':{e:'Abrupt changes in geometry, holes and notches disturb a uniform stress field and can create local peak stresses. The chapter treats this as a local effect important for fatigue and fracture-sensitive details.',q:'What produces a stress concentration?',o:['A geometric discontinuity such as a hole or notch','A perfectly uniform prismatic bar','Zero load and zero fabrication effects','Increasing member length alone'],a:0},
'1:Cold Work and Strain Hardening':{e:'Plastic deformation at low temperature changes subsequent stress–strain behaviour. Cold work can raise yield strength through strain hardening, but it may reduce ductility and introduce residual effects.',q:'What commonly happens after significant cold working?',o:['Yield strength can increase while ductility may reduce','Steel becomes perfectly elastic','Residual effects disappear','Ultimate strength becomes zero'],a:0},
'1:Structural Steel Products':{e:'The chapter surveys plates, flats, bars, hot-rolled I/H sections, channels, angles, tees, hollow sections and built-up or welded products. Designers select a product using section properties, availability, fabrication and structural role.',q:'Which is a structural-steel product category covered in the chapter?',o:['Hot-rolled I-section','Clay brick only','Timber joist only','Glass fibre only'],a:0},
'1:Cold-formed Steel Sections':{e:'Cold-formed members are produced from relatively thin steel sheet by forming at room temperature. Their thin walls make local buckling and connection or detailing behaviour especially important.',q:'Why is local buckling especially relevant to cold-formed steel?',o:['The elements are thin and slender','Cold-formed steel has no yield strength','It is always solid and massive','It cannot be connected'],a:0},
'1:High-performance Steel':{e:'The chapter presents high-performance steel as a material developed to combine useful strength with improved fabrication, toughness, corrosion performance and other service properties for demanding structures.',q:'What is the point of high-performance steel?',o:['Improve a combination of structural and durability properties rather than strength alone','Maximise density','Eliminate all maintenance in every environment','Remove the need for welding controls'],a:0},
'1:Stainless Steel':{e:'Stainless steel obtains corrosion resistance mainly from chromium-rich passive behaviour. The chapter notes its different stress–strain response, good durability and architectural uses, while recognising cost and design differences from carbon steel.',q:'What is the defining practical advantage emphasised for stainless steel?',o:['High corrosion resistance','Very low density equal to timber','No thermal expansion','No need for structural design'],a:0},
'1:Advantages of Steel as a Structural Material':{e:'The source highlights high strength-to-weight ratio, ductility, uniformity, recyclability, prefabrication, speed of erection, adaptability and ease of strengthening, while also noting issues such as corrosion, fire protection and buckling.',q:'Which is a genuine structural advantage of steel?',o:['High strength-to-weight ratio and prefabrication potential','It can never corrode','It never buckles','It is always lighter per cubic metre than concrete'],a:0},
'1:Types of Steel Structures':{e:'The chapter illustrates buildings, bridges, industrial buildings, portal frames, trusses, towers and storage structures. It also classifies members by structural action such as tension, compression, bending and combined action.',q:'A beam is primarily associated with which action?',o:['Bending','Pure hydrostatic pressure','Chemical reaction','Only temperature'],a:0},
'1:Aluminium Alloys':{e:'The text introduces aluminium alloys as lighter structural metals with good corrosion resistance and useful forming or extrusion possibilities, but with lower elastic modulus and different strength, buckling and connection behaviour than steel.',q:'Compared with steel, what important design difference does aluminium have?',o:['A much lower modulus of elasticity','A much higher density','No thermal expansion','No corrosion resistance'],a:0},
'1:Fabrication and Erection':{e:'The chapter describes fabrication as operations such as cutting, drilling, welding, bolting, straightening, painting and inspection, followed by transport and site erection. Accuracy and tolerances matter because errors propagate into assembly.',q:'Which activity belongs to steel fabrication?',o:['Cutting and drilling member components','Determining soil chemistry only','Casting concrete cubes only','Surveying rainfall only'],a:0},
'1:Aesthetics of Steel Structures':{e:'The source argues that structural efficiency and appearance can reinforce each other. Proportion, exposed framing, member shape, connection detailing and integration with architecture all affect the visual quality of steel structures.',q:'What can contribute to the aesthetics of an exposed steel structure?',o:['Proportion and detailing of members and connections','Only increasing member weight','Ignoring connection layout','Hiding all structural logic'],a:0},
'1:Composite Construction':{e:'The chapter shows concrete-encased steel, concrete-filled steel sections and steel beams supporting concrete slabs. Shear connection can make steel and concrete act together, reducing depth or steel weight and improving other performance.',q:'Why are shear connectors used in a steel–concrete composite beam?',o:['To transfer interface shear so the materials act together','To increase slip between steel and concrete','Only to hold paint','To eliminate bending'],a:0},
'1:Summary':{e:'Use this checkpoint to reconstruct the chapter as one chain: steel production and metallurgy → composition and material properties → residual and local effects → products and steel types → structural applications, fabrication, aesthetics and composite construction.',q:'Which chain best represents the chapter overall logic?',o:['Production/material behaviour → products → structural use and fabrication','Paint → soil → masonry → timber','Loads → only concrete → corrosion → no design','Geometry → weather → chemistry only'],a:0},
'1:Review Questions':{e:'The chapter ends with review questions. Treat them as retrieval practice: attempt an answer from memory first, then check the textbook and repair the gap. Completing this node means you actively tested the chapter rather than only read it.',q:'What is the best way to use the chapter review questions for revision?',o:['Attempt from memory before checking the text','Read the answers first and skip retrieval','Ignore questions because the chapter was read once','Memorise page numbers only'],a:0}
};
